### ISSUE TITLE
mul(DMatrix,SXMatrix) not working in C++

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1002]
Multiplication of a DMatrix and an SXMatrix does not appear to work in C++, see forum post: https://groups.google.com/forum/#!topic/casadi-users/ZbWUV6vGqMQ.

I can reproduce the error.

**Comment by jgillis** [comment]
Still open as of 2023

**Comment by jaeandersson** [comment]
Mul does not even exist anymore

**Comment by jaeandersson** [comment]
The issue is that there is an implicit type conversion from SX to DM because of this constructor
```c++
    /** \brief Create a matrix from another matrix with a different entry type

     *  Assumes that the scalar conversion is valid.
        \identifier{18n} */
    template<typename A>
    Matrix(const Matrix<A>& x) : sparsity_(x.sparsity()), nonzeros_(std::vector<Scalar>(x.nnz())) {
      auto x_it = x->begin();
      for (auto&& d : nonzeros_) d = static_cast<Scalar>(*x_it++);
    }
```
The implementation calls the explicit conversion operator, hence no error if you try to use it:
```c++
  SX x = SX::ones(2,1);
  DM dmat = DM::ones(2,2);
  DM y = DM::mtimes(dmat, x);  # works
```
If you want to avoid ambiguity for the original overload, call the static function instead:
```c++
  SX x = SX::ones(2,1);
  DM dmat = DM::ones(2,2);
  // SX y = mtimes(dmat, x);  # compilation error
  SX y = SX::mtimes(dmat, x);  # works
```
I'll close it as wontfix. It's probably possible to find a solution. An obvious solution is to define DM and SX not as Matrix<double> and Matrix<SXElem> but as classes that inherit from Matrix<double> and Matrix<SXElem>. Then you can add the conversions you want. Anyway, this doesn't seem to be high priority, as there is a simple resolution anyway.
