### ISSUE TITLE
Finish snopt interface

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1008]
The biggest missing feature:
- [x] allow sparse linear objective without external objective gradient, @jgillis do you know a way to do this?

Stuff I can take care of:
- [ ] getOption isn't implemented
- [x] use iso_c fortran interface instead of @ghorn's magic headers
- [ ] handle `snoptc` error codes in a casadi-like way

Not sure if this is reasonable:
- [ ] unit tests for all permutations of linear/nonlinear/zero tags
- [x] unit tests for all variable and constraint permutations

Joris volunteered:
- [x] inline comments

another one:
- [ ] convert from `Infinity` to `1.1e20`, compensating for the constant offset shifting for linear rows

also:
- [ ] https://github.com/casadi/casadi/commit/83196c54853383c0cae24f620cc7bb2213f71500#commitcomment-5619550

**Comment by jgillis** [comment]
Let's wrap this up
