### ISSUE TITLE
add support for numerical differentiation

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1026]
I have a use case where I want to optimize something where most of the NLP is symbolic, but a small part is computed in an external numerical routine. What would numerical differentiation look like in casadi?

**Comment by jaeandersson** [comment]
Can be implemented easily and efficiently after #1336.

**Comment by jaeandersson** [comment]
Here is another reference (from 1985!): http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19850025225.pdf

**Comment by jaeandersson** [comment]
Anyway, the algorithm used in `gsl_deriv_central` looks very reasonable. Or combining that algorithm with a bisection algorithm.

**Comment by jaeandersson** [comment]
Too bad GSL is GPL :-(

**Comment by jaeandersson** [comment]
The source of `gsl_deriv_central ` references "pg. 204 of Conte and de Boor". So a possibility would be go get hold of that book. We can also get in contact with the copyright holder of `gsl_diff_central` and ask if it's possible to release under a different license. I'll send him a mail.

**Comment by jaeandersson** [comment]
Sent mail to copyright holder.

**Comment by jaeandersson** [comment]
In implemented! Spun #2073 #2074 #2075 as future improvements
