### ISSUE TITLE
unit test coverage

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1043]
We just lost more than a day on #1042 because it was tricky to distill a huge NLP into a simple test. It turned out it was just a one character fix in `inner_prod`: https://github.com/casadi/casadi/commit/4f7b7a7.

@jgillis noticed that inner_prod was untested and a simple test (now added) would have revealed this. So I thought maybe unit testing more or all of the atomics might have a high reward to work ratio. How would we go about detecting untested atomics?

We also realized that all the MX tests were disabled. I don't know how a coverage test would detect that though.

**Comment by jgillis** [comment]
Here's a neat place to dump coverage stats to: htpp://coveralls.io

**Comment by jgillis** [comment]
This issue is back on the menu since travis has become powerful enough to run all tests in one run.

**Comment by jgillis** [comment]
Voila [![Coverage Status](https://coveralls.io/repos/github/casadi/casadi/badge.svg?branch=develop)](https://coveralls.io/github/casadi/casadi?branch=develop)
