### ISSUE TITLE
treemap viewer for profiling output

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1056]

**Comment by jgillis** [comment]
I needed a treemap for my thesis:

![bench](https://cloud.githubusercontent.com/assets/329032/6146780/83cfc022-b1f0-11e4-9108-cf86aa6b6487.png)

Will try to commit this sometime.

**Comment by jaeandersson** [comment]
:+1:

**Comment by jgillis** [comment]
Remaining tasks is just to update css and javascript to https://gist.github.com/jgillis/c9c381e9c65b059cbe7b
Better switch to a mechanism where the build system converts a helper file into literal strings.
We have a simple construct for that in our build systems already, used for the runtime.
