### ISSUE TITLE
implement "map" for MX (was: implement "map" and "fold" for MX)

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1064]
When I code generate for optimal control problems, the amount of generated code is proportional to the horizon length, even though the symbolics were basically created with for loops. If there were atomic map and fold operations, the generated code could use for loops and generated code size would be independent of horizon length. This would be a pretty huge deal I think.

**Comment by ghorn** [comment]
bump

**Comment by jaeandersson** [comment]
@ghorn @jgillis Implemented `map` with optional parallelization (openmp). Replaces Parallelizer which has now been removed. There is some unit tests, but they don't cover all cases.
Known limitations:
 * OpenMP will only work with classes that work memoryless with work vector (FunctionInternal::evalD). Basically SXFunction and MXFunction and combinations thereof.
 * No code generation has been added, but can be added easily.
 * Only numerical evaluation is parallelized. But also sparsity pattern propagation can be (trivially) parallelized.

**Comment by ghorn** [comment]
Cool! what happens when you use parallel map on a function which is not parallelizable?

**Comment by jaeandersson** [comment]
You can get multiple threads accessing same memory. Anyway, the idea is that all functions should be threadsafe, hence parallelizable.

**Comment by ghorn** [comment]
Maybe it should throw an error instead of access the same memory. How can the user differentiate between parallel and serial map?

**Comment by jaeandersson** [comment]
When #1356 is completed, it should not be possible to get multiple thread accessing the same memory. And making the thread-safe functions "const" (cf. #1356), will avoid accidentally writing the same memory by multiple threads.
Difference between maps:
```python
# Serial:
[y1,y2] = f.map([x1,x2], 'serial')
[y1,y2] = f.map([x1,x2]) # serial is default
# Parallel (OpenMP)
[y1,y2] = f.map([x1,x2], 'openmp') # OpenMP parallelization, property will propagate to derivatives
```
More parallel evaluation models (e.g. MPI, OpenCL) can be added later.

**Comment by jaeandersson** [comment]
Arguably, we should have an error issued when trying to use a function that is not yet thread-safe. Pending the completion of #1356.

**Comment by jgillis** [comment]
Note to self:  map and fold map nicely onto opengl constructs. Seeing speedups of a factor 1000 here wrt to code-generated casadi..

**Comment by jgillis** [comment]
What will happen if I call Parallelizer with a million repetitions? will it allocate a million distinct inputs/outputs

**Comment by jaeandersson** [comment]
Parallelizer does not exist anymore. It's now a node, not a function. It will allocate a for loop. Memory will be same as evaluating the function once. If openmp, n times the work vectors needed.

**Comment by ghorn** [comment]
@jgillis you are doing opencl runs?

**Comment by jaeandersson** [comment]
Created separate issue for the implementation of "fold": #1395. Will close this issue as map is now available.
