### ISSUE TITLE
InputOutputSchemes is not modular enough?

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1090]
We've had some discussion about making casadi modular and extensible, meaning that 
* people can conveniently extend casadi without needing to edit the casadi source
* our modules are as independent as possible

The `InputOutputScheme` enum may be failing this:
* Since we generate the enum by parsing the casadi source and finding all schemes, no new schemes can be created outside of the casadi source
* Modules "leak": people using the only the casadi core can see schemes from ocp, convex programming, etc

The second point raises another question: why are things like `symbolic_ocp` in `casadi_symbolic` intead of `casadi_optimal_control`? I think there are also some `casadi_convex_programming` examples of this.

**Comment by jaeandersson** [comment]
This issue is moot. InputOutputSchemes replaced by vectors of strings, which are very modular.
