### ISSUE TITLE
Add fmod atomic operation

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1112]
As requested by @ghorn.

**Comment by b4be1** [comment]
Hi @jaeandersson & @ghorn,

I am using CasADi 3.4.5 from pip under Python 3.6.5 on MacOS Mojave 10.14.3 and there is no function `fmod` available. Could you check, please? In the meanwhile, I am using what Joel suggested

```python
a = ca.SX.sym('a')
b = ca.SX.sym('b')
fmod = ca.Function('fmod', [a, b], [a - b * ca.floor(a / b)])
```

**Comment by jaeandersson** [comment]
@b4be1 I think it's there. It looks like it's called "mod", not "fmod" in Python.

**Comment by b4be1** [comment]
Thanks @jaeandersson, I think I found the source of confusion. There are two kinds of modulo operation in python: `math.fmod` and `%` (see https://docs.python.org/3.6/library/math.html#math.fmod).

Function `casadi.mod` indeed behaves as python's `math.fmod`. Note that there is a typo in https://web.casadi.org/docs/ where it is called `casadi.fmod` in Section 10.2.

However, this `fmod` has a bit weird semantics. For example, `fmod(-1, 3) == -1`, whereas `-1 % 3 == 2`. What I need is the latter, which behaves as the mathematical modulo operation `x mod y` (see https://en.wikipedia.org/wiki/Modulo_operation). And the formula above that you provided actually corresponds to `%` and not `math.fmod`.

So, you could consider adding operation `a % b` to casadi or making a note in the documentation about these differences.

**Comment by jaeandersson** [comment]
CasADi's definition of fmod for negative numbers follows the C/C++ definition, since that's what's being called internally. I don't think we want to maintain multiple versions of it, but you are right that the documentation should be corrected.

**Comment by ghorn** [comment]
Why do you expose `fmod` as `mod` in python if it behaves differently for negative numbers than python's `%`? Why not expose it as `fmod`?

**Comment by jaeandersson** [comment]
> Why do you expose fmod as mod in python if it behaves differently for negative numbers than python's %? Why not expose it as fmod?

Yeah, it should really be renamed 'fmod'. Numpy btw defines both:
```python
numpy.fmod(-1., 3.) # -1.0
numpy.mod(-1., 3.) # 2.0
```

**Comment by jaeandersson** [comment]
It's possible to add an always positive modulo operator, but there isn't really any low-level C++ operator to map to, unlike https://en.cppreference.com/w/cpp/numeric/math/fmod, so I'm not really in favor of that. A suggested workaround for getting the desired behavior is:
```
fmod(x, y) + y*(x < 0)
```
