### ISSUE TITLE
distribute casadi_nlpsplver_worhp in .deb package

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1146]
According to Dennis Wassel, we can distribute the WORHP interface, linked dynamically against WORHP:

> Sure, distribute away, but please make sure to document which version of
WORHP the plugin is linked against.
The version check (i.e. the CHECK_WORHP_VERSION macro) will catch
incompatible stuff, but documenting this is better than relying on a
last-resort technical measure.

cf. #1076.

**Comment by jgillis** [comment]
worhp interface is distributed in linux binaries as of 2.3.0
