### ISSUE TITLE
Improve nice_stdout

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1218]
Right, now there is `nice_stdout` from `casadi.tools` that can be used as a decorator to make sure that stdout generated in the c++ world ends up in Python's sys.stdout.

This should be extended:
 * [ ]  Make sure that a full buffer will not block indefinitely
 * [ ]  Do a similar feat for stderr
 * [ ]  Make sure that every Python function internally uses the decorator

**Comment by jgillis** [comment]
Relevant: http://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/

**Comment by jaeandersson** [comment]
Note: The issue with the printouts to stdout is IMO not a Python issue. It's an issue for the corresponding interface and should be resolved at interface level, cf. #1450

**Comment by jgillis** [comment]
Other notes: http://xonsh.org/_modules/xonsh/proc.html

**Comment by jgillis** [comment]
Defining a pythonostream similar to mexostream, with `PySys_WriteStdout` goes a long way..
