### ISSUE TITLE
don't version control autogenerated files

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1243]
These files should be created by the build system, in the build directory.

By misc/autogenerate.py  (these are lightweight, dependencyless and could be ported to the build system ):
- [x] swig/autogenerated.i
- [x] casadi/core/autogenerated.cpp
- [x] casadi/core/function/schemes_metadata.cpp
- [x] casadi/core/function/schemes_metadata.hpp
- [x] casadi/core/function/schemes_helpers.hpp

By docs/api:
- [ ] docs/api/extra/a0_schemes.hpp
- [ ] docs/api/extra/b0_options.hpp
- [ ] docs/api/extra/c0_monitors.hpp
- [ ] docs/api/extra/d0_stats.hpp
- [ ] swig/doc.i
- [ ] swig/doc_merged.i
- [x] swig/deprecated.i
- [x] swig/internal.i
- [ ] *_meta.cpp

**Comment by jaeandersson** [comment]
Reopen if priority
