### ISSUE TITLE
Symbolic links to CasADi DLLs in Windows binaries of CasADi-Python?

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1250]
To avoiding having to set environment variables, CasADi DLLs are now copied to CasADi Python package on Windows.

Would it be possible to instead install CasADi in some standard location (e.g. `C:\CasADi-2.1\`), with the same directory structure as in Linux (e.g. a `casadi` subdirectory for plugins) and make symlinks to the DLLs? That would feel much more natural, especially if we will support Python 3, non-Python CasADi users in Windows (C++, Haskell, Matlab, Java etc).

**Comment by jgillis** [comment]
This discussion is obsolete.
The binaries packages are self-contained folders that have all the libraries in them.

This allows users without admin rights to try out CasADi.
