### ISSUE TITLE
Add sinc

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1271]
Related to #555

**Comment by mkatliar** [comment]
I believe the `sinc()` function would be a useful addition to CasADi. In particular, it emerges in quaternion math, when a 3D rotation vector is converted to a quaternion:

```python
def quat_from_rotation_vector(theta):
    angle = cs.norm_2(theta)
    return cs.vertcat(
        cs.cos(angle / 2.),
        theta * cs.sin(angle / 2.) / angle
    )
```

When I calculate the derivatives, I need to handle `theta == 0` as a special case, which is cumbersome and prone to errors. The approximation that @jgillis provided above unfortunately does not work well around `theta = 0`.

With `casadi.sinc()`, I could write:
```python
def quat_from_rotation_vector(theta):
    angle = cs.norm_2(theta)
    return cs.vertcat(
        cs.cos(angle / 2.),
        theta * cs.sinc(angle / 2.) / 2.
    )
```
and have all the derivatives nicely computed by CasADi.

Please consider adding `sinc()` to CasADi. I could also help with that, if you point me in the right direction in terms of where to do it in the code.
