### ISSUE TITLE
Refactor slicing, remove IndexList

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1295]
The functions getNZ, setNZ, sub and setSub have been wrapped in a lot of overloads called `indexed_nn` or `nz_indexed_nn'. It appears to me that only thing these overloads support is to work with the IndexList type, which appears to be very questionable since IndexList's functionality could probably be handled just as well by SWIG's dynamic dispatcher.

My proposal is to remove IndexList and all the `...indexed_...` overloads. Instead SWIG will call getNZ directly.

This will greatly facilitate #176.

**Comment by jaeandersson** [comment]
@jgillis I get license errors in WORHP if I try to run the testbot: `Unsuccessful termination: License error`. Any idea of what this is about?

**Comment by jgillis** [comment]
oh yeah license was dur to.expire

**Comment by jaeandersson** [comment]
OK, remaining issues should be resolved now. I refactored MX::setSub and Matrix::setSub in a way that I think is more efficient, in addition to working correctly for non-monotone indices.

**Comment by jaeandersson** [comment]
Note: Sparsity::enlarge is now longer needed internally. @jgillis - Do you think we should keep it? The current implementation only works for strictly increasing indices, so we should either remove it or add assertions.

**Comment by jaeandersson** [comment]
Will merge once trunktesterbot has a successful run.

**Comment by jaeandersson** [comment]
The amount of code duplication could probably be reduced by introducing ind2sub and sub2ind helper functions that works similar to the MATLAB functions with the same names.
