### ISSUE TITLE
Skipped tests during installing

### ISSUE THREAD

**Issue by jeslago** [casadi/casadi#1299]
I have a small question, I tried to find an answer in old issues and I couldn't find it, so I guess it might be a bit idiotic. Anyway, I ran the alltests.py file after installing casadi, and the final output was:

Ran 455 tests in 168.643s
OK (skipped=7)

I understand that I had no failures, however I am wondering whether there might be something wrong with my installation since some test were skipped, and some of them stating that there was some class not available. Particularly I got:

Not available <class 'casadi.casadi_core.NlpSolver'> skipping unittests
Not available slicot_periodic_schur, skipping unittests
Not available isSmooth, skipping unittests

Thanks a lot for your help, and sorry If this is a dumb question.

**Comment by jaeandersson** [comment]
Hi! Don't worry about this. It skips tests by default that are very slow I think. Or that uses optional components (like slicot) that isn't available on your system.

**Comment by jeslago** [comment]
Thanks a lot for the help!!
