### ISSUE TITLE
MATLAB naming in API

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1300]
There are a number of functions in the API that could be made more MATLAB-like:
 * Boolean queries in lower case instead of CamelCase: `issparse` instead of `isSparse`, `isdiag` instead of `isDiag` etc.
 * ~~`full`, `isfull` instead of `dense`, `isDense`~~ 
 * `blkdiag` instead of `diagcat`. (I replaced all instances of blkdiag but that might have been a mistake)
 * `size` returning shape, not number of nonzeros
 * `nnz` returning number of nonzeros
 * ~~`nonzeros` instead of `data`~~  (I'm adding nonzeros, but it is not a replacement, since the return type is different).
 * `iscolumn` instead of `isVector` (in MATLAB, `isvector` is true for row and column vectors.)

There are probably many more. Not sure if all changes makes sense, though. And changing the API might annoy users... On the other hand, it makes the syntax more familiar for MATLAB users.

**Comment by jgillis** [comment]
Is it correct that the examples you posted would correspond to global functions in matlab?
How about just adding those to the matlab interface and make them use the existing camelcase member functions?

**Comment by jaeandersson** [comment]
It is possible to use a different syntax in MATLAB, but the question is if it would be desirable. Having the same MATLAB-like syntax makes the learning curve less steep and avoids the confusions you get from having different syntaxes in different languages.

**Comment by jgillis** [comment]
Chaning `size` would definitely be annoying.
The others can all be done with gentle deprecations

**Comment by ghorn** [comment]
is the naming now based on numpy?

**Comment by jaeandersson** [comment]
The naming now is "MATLAB inspired". But many things are not really planned. Matrix.size() is named this way since many many iterations ago, Matrix was inheriting from std::vector...

**Comment by jaeandersson** [comment]
About size(), I'm also not sure about it. Anyway, the first step is to implement the sparsity iterators (#57)...

**Comment by ghorn** [comment]
I don't mind the C++ API to have matlab-like names, and no camel-case. I'm not sure how python users would feel.

My biggest worry would be having a function name which exactly matches matlab, but works subtly different on a matlab matrix than on a casadi matrix. (Or causes overloading issues)

**Comment by jaeandersson** [comment]
I would also like to deprecate the syntax `Y = SX.repmat(X, ...)`. It is enough to have `Y = repmat(X, ...)` with type of Y inferred from X. X can always be cast into the correct type to avoid ambiguity, e.g. `Y = repmat(SX(4), 5, 6)`.

**Comment by jaeandersson** [comment]
> Is it correct that the examples you posted would correspond to global functions in matlab?
How about just adding those to the matlab interface and make them use the existing camelcase member functions?

Thought I should clarify this: No, all the functions above corresponds to member functions in MATLAB. If you have a member function "issparse", that you would call using the syntax "x.issparse()" in C++, the MATLAB way of calling it would be 'issparse(x)". You *don't* want to have a global function called "issparse", because then this will be called instead of the built-in one when working with MATLAB built-in datatypes.

**Comment by jaeandersson** [comment]
I'd like to go with the following convention:
 * densify(A) returns a dense(r) CasADi matrix of the same type as A
 * dense(A) returns a dense MATLAB matrix when in MATLAB, it will be the standard way of converting CasADi type to dense MATLAB matrix. In Python, we could use the same syntax for returning a 2-dimensional numpy array.
 * sparsify(A) returns a sparse(r) CasADi matrix of the same type as A 
 * sparse(A) returns a sparse MATLAB matrix when in MATLAB, it will be the standard way of converting CasADi type to sparse MATLAB matrix. In Python, we could use the same syntax for returning a scipy.csc_matrix.
 * Sparsity.dense(n,m), Sparsity.sparse(n, m) will continue to work as now for constructing dense/sparse sparsity patterns.

**Comment by jaeandersson** [comment]
@jgillis  - any objections?

**Comment by jgillis** [comment]
what would full and sparse do for the sxmatrix and mx type? break doen into 1-by-1 s?

**Comment by jaeandersson** [comment]
Convert to numeric sparse/dense matrix, throw error if not possible.

**Comment by jaeandersson** [comment]
full(A) in matlab gives a dense numeric matrix for A dense or sparse matlab matrices. makes sense to have casadi matrices behave the same way. same with sparse.

**Comment by jgillis** [comment]
you seem very determined so go ahead. make sure to put some \see in the docstrings..

**Comment by jaeandersson** [comment]
If we want to be more MATLAB-like, then 'DMatrix.eye(3)` should return a dense matrix and `DMatrix.speye(3)` a sparse matrix... Just saying...

**Comment by jaeandersson** [comment]
Not sure if I'd like to change that though.

**Comment by jaeandersson** [comment]
Forget about DMatrix.speye(n). I retract that. DMatrix.eye is good as it is. I also want to deprecate current use of Matrix.sparse and replace with Matrix(Sparsity, Matrix) (cf #1320) and Matrix(int,int), Matrix(std::pair<int,int>).

**Comment by jaeandersson** [comment]
Closing this issue here. I left `diagcat ` as I can see some issues with `blkdiag`: it would make the syntax `diagsplit` illogical and breaks the pattern with `vertcat`, `horzcat`.
I also removed `size()` but postponed the renaming of `shape()` to `size()` for later to avoid weird errors.
