### ISSUE TITLE
Avoid code duplication when wrapping friend functions

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1301]
With #1285, functions that were previously standalone functions (e.g. `kron(A, B)`) have been moved into the class and declared `inline friend`. This is definitely the correct way of handing it on the C++ side as it provides additional encapsulation and enables automatic type conversion.

It should also have simplified SWIG since `kron(A, B)` no longer being template functions should be instantiated automatically. Unfortunately, if I let SWIG wrap the friend functions as-if, it doesn't work and I get warnings of the type:
```
/Users/janderss/dev/casadi/./casadi/core/mx/mx.hpp:474: Warning 503: Can't wrap 'casadi::getOperatorRepresentation' unless renamed to a valid identifier.
```
I don't understand why this happens.

As a workaround solution, I have declared free-standing functions with the corresponding signatures in SWIG (not instantiated in SWIG MATLAB since MATLAB uses the member functions directly). This appears to work fine, but introduces unnecessary code duplication which inhibits maintainability.

When fixed, the remaining functions in mx_tools.hpp and sx_tools.hpp should be declared friend and moved inside their respective classes.

**Comment by jaeandersson** [comment]
I'll answer in the #1285 issue.

**Comment by jaeandersson** [comment]
@jgillis - I managed to get rid of the code duplication by using macros. I think it's ok design pattern given the fact that by design, the friend functions should have one-liner definitions. The main issue with this approach is that I had to move the doxygen comment away from the function definition. Do you have an idea on how to do this in a more maintainable way? These functions are very central by the way - they should really go to the user guide and not just the API documentation.

**Comment by jgillis** [comment]
Why not put those c style comments inside the macro definitions?

**Comment by jaeandersson** [comment]
Nevermind the above, I'm doing another iteration.

**Comment by jaeandersson** [comment]
Cf. https://github.com/casadi/casadi/issues/1463#issuecomment-125626983

**Comment by jaeandersson** [comment]
There is not much less code duplication than before, but the design is cleaner and works in MATLAB. The C++ code is basically clean and the SWIG code is, well SWIG code.

**Comment by jaeandersson** [comment]
Reopened for Python.
