### ISSUE TITLE
More tidying up of API

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1302]
Implementing #1285, I've come across duplicate functions and functions with suboptimal syntax. There are also functions of limited usefulness that IMO should be removed to get a cleaner API.

This is a list of things I've come across:
 - [x] `simplify(SX or MX)` should be return-by-value
 - [x] `evalf(SX)` not needed. Users should know how to create functions
 - [x] `getFree(SX)` duplicate of `getSymbols(SX)`. Replace both of them with `symvar` (naming in MATLAB symbolic toolbox).
 - [x] `spy(SX)` should go away (it also has a very inefficient implementation)
 - [x] `substituteInPlace(SX or MX)` one overload is enough
 - [x] `project(Matrix)` appears to be a duplicate of `setSparse`. `project` might be a better name though.
 - [ ] ~~Replace `sumCols`, `sumRows` with a MATLAB-style `sum`~~
 - [x] Rename `getMinor` to `minor`.
 - [x] Remove `addMultiple(Matrix)`
 - [ ] ~~Remove `sum_square`~~
 - [ ] Refactor `solve(Matrix)`, `pinv(Matrix)`. Remove DMatrix-specific overloads.

I also still think the following should go:
 - [x] `vecNZcat`
 - [x] `sumAll`

This was already discussed in #983, so I won't go ahead with the above unless @jgillis and @ghorn  change opinion.

Cf also #983, #1300.

**Comment by ghorn** [comment]
This is fine with me with the following exceptions:

`sumCols`, `sumRows` - These functions are total functions, where `sum(Matrix, int)` is a partial function - it throws an exception if the dimension is not 0 or 1. I would leave in `sumCols`, `sumRows` and then implement `sum` in terms of them.

`veccat` - I use this extensively, I'd be sad to see it go. Am I doing something wrong?

`spy(SX)` - No opinion, but I don't understand what's wrong with it. Could you explain please? There should be some way of doing this even if you change the implementation right?

`sum_square` - This has a precedent in dcp tools, but if the casadi implementation is just naive `sum(x**2)` then I see no reason to keep it. We should keep it if we have an efficient version, like squaring and accumulating in one loop. (Or you could just implement a loop fusion optimization :D)

Also, don't forget to update https://github.com/casadi/casadi/wiki/Changes-v2.1.0-to-v2.2.0

**Comment by ghorn** [comment]
(That should have said wiki page `2.2.0 -> 2.3.0`)

**Comment by jaeandersson** [comment]
* `spy(A)` is an inefficient duplicate of `SX.ones(A.sparsity())`. I find the latter more readable.
 * `veccat` not so bad, so let's forget that. But `vecNZcat` is pretty bad IMO.

**Comment by jaeandersson** [comment]
I would expect `spy(A)` to print the sparsity pattern of A (like in MATLAB) and not (like now) return a sparse matrix with nonzeros replaced by 1.

**Comment by jaeandersson** [comment]
I left sumRows, sumCols and sum_square in place, mostly because of refactoring fatigue. I also left "solve", since it makes sense to address it together with a consolidated effort to better syntax and built-in algorithms for linear solve.
