### ISSUE TITLE
Streamline installation of MATLAB front-end

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1309]
It is now a pain, cf. https://github.com/casadi/casadi/wiki/matlab.

**Comment by jgillis** [comment]
Some matlab-packages can be bootstrapped by a one-liner in the matlab command line.
Definitely worth considering. This implies exporting the swig-generated wrapper files in some form.

**Comment by jaeandersson** [comment]
Yes, I've been thinking the same. casadiMATLAB.cxx and the MATLAB  proxy classes are portable. Then user does not need to compile a custom SWIG.

**Comment by mvukov** [comment]
Why don't you provide binaries?

**Comment by jaeandersson** [comment]
Distributing casadiMATLAB.cxx + proxy classes would be platform independent and compiler independent. But distributing binaries is also an option to consider, especially since MATLAB appears to be very picky with the compiler used (it wants gcc 4.7 on Linux).

**Comment by mvukov** [comment]
Agree. We've seen too much problems compiling ACADO for MATLAB on various platforms. My conclusion is that our lives would have been much easier if we've had precompiled everything and shipped *.mex and *.m.

**Comment by jaeandersson** [comment]
It's still not a trivial thing to do. We don't want to build up a second distribution of everything. We want to use the same plugins for MATLAB, Python, C++, Haskell.

**Comment by jgillis** [comment]
We have matlab binaries set up as of 2.3.0
