### ISSUE TITLE
MX matrix inverse can't be numerically evaluated

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1310]
``` python
L = MX.sym('L',2,2)
f = MXFunction([L], [inv(L)])
f.init()
f.setInput(1, 0)
f.evaluate()
```

produces

```
     32 f.init()
     33 f.setInput(1, 0)
---> 34 f.evaluate()

/home/ghorn/casadi_install/casadi/casadi.pyc in evaluate(self, *args)
  19007 
  19008         """
> 19009         return _casadi.Function_evaluate(self, *args)
  19010 
  19011     def jacobian(self, *args):

RuntimeError: MXNode::evaluateD not defined for class N6casadi7InverseE
```

**Comment by ghorn** [comment]
since a `DMatrix` can be inverted, i'm assuming this is an oversight

**Comment by jaeandersson** [comment]
The `DMatrix` is inverted using minor expansion, not useful for dimensions larger than say 4-by-4. You can also calculate inverse using QR decomposition.

**Comment by jaeandersson** [comment]
You need to add to the signature a name of a linear solver to be used to calculate the inverse. I.e.:
```c++
friend inline MatType inv(const MatType& m, const std::string& solver="default");
```

**Comment by ghorn** [comment]
I see. Would it be reasonable to have a portable default solver?

**Comment by jaeandersson** [comment]
CSparse is portable, but can't be used symbolically (for SX). I think it makes sense to invest time into implementing a good default linear solver that can be used numerically, symbolically and for codegen.

**Comment by Mathadon** [comment]
I'm also trying to invert a matrix (let's say size 20x20) using casadi. What's the cleanest way to do this? I'm using Jmodelica so preferably something that works in casadi 2.1. Thanks!

**Comment by jaeandersson** [comment]
Unrelated to this issue. See forum posts https://groups.google.com/forum/#!msg/casadi-users/OdNMM4TWVjM/ and https://groups.google.com/forum/#!msg/casadi-users/h1bydVJA-xg/.

**Comment by asteinh** [comment]
Gentle bump... the following still fails (Matlab):
```
x = MX.sym('x', 2, 2);
f = Function('f', {x}, {inv(x)});
f(eye(2))
```

**Comment by jaeandersson** [comment]
This is not a bug - it's a missing feature.
