### ISSUE TITLE
Default solver

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1312]
Would be nice to be able to set and use a default solver:
```python
NlpSolver.setDefault('ipopt')
solver = NlpSolver('default', nlp)
```
Especially makes sense for @jgillis' matryoshka doll convertors.

**Comment by jgillis** [comment]
We've been talking for quite a while about this..
I like the syntax `NlpSolver.setDefault('ipopt')` a lot.

**Comment by jaeandersson** [comment]
I think it's more natural to have a default solver in the place where it's actually used.
