### ISSUE TITLE
Clean up sparsity slicing

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1319]
Sparsity slicing, regardless of the question wether it is desirable to do, is now possible with three syntaxes:
```
x.setSparse(sp), x[Sparsity] and project(x,sp)
```

One of them should be enough, and `project` is the best candidate to keep.

* [ ] remove 'x[Sparsity]'
* [ ] Add project for MX'es

**Comment by jaeandersson** [comment]
Closed as duplicate. This is covered by #1302.
