### ISSUE TITLE
Simple syntax for creating a matrix with given nonzeros MX (was: Make MX (sp,MX) internal)

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1320]
I believe there ought to be a simple-syntax replacement for this action, which is essentially 'val.getNZ(IMatrix(sp, range(sp.size())'.

And this syntax should be available for all MX, SX and DMatrix

**Comment by jaeandersson** [comment]
After some thinking, I propose to essentially go back to the previous syntax, but make it unambiguous:
 `Matrix(Sparsity, Matrix)` creates a matrix with sparsity sp and nonzeros v. the type of v is Matrix. To resolve unambiguity, the overloads Matrix(Sparsity, vector<datatype>) and Matrix(Sparsity, datatype) will be added a dummy third argument.

**Comment by jgillis** [comment]
I'm a fan of this sudden turn of events

**Comment by jaeandersson** [comment]
Implementation is underway. Will push to separate branch and merge when passes all testss.

**Comment by jaeandersson** [comment]
Resolved. Matrix(Sparsity, Matrix) and MX(Sparsity, MX)  is now valid syntax for creating a sparse matrix with given sparsity and nonzeros.
