### ISSUE TITLE
Make IO scheme enums internal

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1321]
It makes little sense to work with constants such as `NLP_SOLVER_UBG` directly. Since there is already a working alternative, passing strings such as "ubg", I see no reason to keep them in the public API and in SWIG.

This would be beneficial in MATLAB since every enum entry corresponds to one file and because MATLAB appears to have problems handling files that only differ by case.

**Comment by jgillis** [comment]
What about the use of `derivative`? An expert user may wish to work with these enums.

**Comment by jaeandersson** [comment]
Isn't that a problem of the past?
```c++
      // Adjoint over adjoint to get the second order sensitivities
      Function I_aoa = I_adj.derivative(0,1);
      I_aoa.setInput(x0,"der_der_x0");
      I_aoa.setInput(u0,"der_der_p");
      I_aoa.setInput(0.0,"der_adj0_xf");
      I_aoa.setInput(1.0,"der_adj0_qf");
      I_aoa.setInput(1.0,"adj0_adj0_p");
```

**Comment by jgillis** [comment]
Yeah that way it is clear; but what if you want to create your own derivative to use with `function.setDerivative`

**Comment by jaeandersson** [comment]
Why use `function.setDerivative`? Correct way is to set "derivative_generator" option. Then the above names are created automatically.

**Comment by jgillis** [comment]
This has my blessing now, fwiw.
You can still use the lookup function if you absolutely need those index numbers

**Comment by jaeandersson** [comment]
Great! Let's make the API smaller:)

**Comment by jaeandersson** [comment]
Resolved. My `casadiPYTHON_wrap.cxx` lost another 2187 lines of code and is now at 115219.
