### ISSUE TITLE
make SXElement completely internal

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1322]
There are some API functions which have SXElement as an argument or return value. This is probably an accident, since the SXElement class is supposed to be internal

**Comment by jaeandersson** [comment]
Please be more specific. Which functions? There might be some leftovers from #983.

**Comment by ghorn** [comment]
You can try for yourself with

`$ grep -n10 "std::vector<(casadi::SXElement)>" ~/casadi-2.2.0/build/swig/json/casadi.json`

https://gist.github.com/ghorn/1d3be472ec61f666e130

If you just grep for `SXElement` you have to filter out `Matrix<SXElement>`

**Comment by jaeandersson** [comment]
OK, you're right. Should be a bit less after #1320, but there are probably some more leftovers.

**Comment by jaeandersson** [comment]
Blocked by #1360.
