### ISSUE TITLE
Get vertsplit, horzsplit, diagsplit working in MATLAB

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1326]
Vertsplit, horzsplit don't work in MATLAB since only the vector<int> overloads are exposed and they don't work properly.
Anyway, we also need to design on a syntax. Vertsplit returns a list of outputs. Do we want to pass the list to the user or do we convert it to multiple outputs?
```matlab
%alternative 1
[x1, x2, x3] = vertsplit(x)
%alternative 2
[x1,x2,x3] = vertsplit(x){:}
```
I am tending towards 2.

**Comment by jaeandersson** [comment]
Should be resolved.

**Comment by jgillis** [comment]
Unittests missing

**Comment by jaeandersson** [comment]
We don't have a working unit test framework beyond a simple script. I'm against expanding this into something truly unmaintainable. As things stand, it makes no sense to add tests for every working feature.

**Comment by jaeandersson** [comment]
What is really missing in MATLAB is more documented examples. That is a much better way avoid features like this breaking than a random line in `test.m`.

**Comment by jgillis** [comment]
Until there are such examples, `test.m` is the least bad option. I'll do its maintenance.

**Comment by jaeandersson** [comment]
There is no custom code for these operations. `vertsplit` is a friend function in C++, member function in MATLAB, just like any other.

**Comment by jaeandersson** [comment]
Confusing cleared about unit testing. These functions have nothing MATLAB specific in them.
