### ISSUE TITLE
Restrictions in derivative calculation syntax and algorithms

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1336]
I'd like to introduce the following restrictions to the way derivatives are calculated:
 * You either calculate forward or reverse mode derivatives, not a combination of the two
 * Derivatives are always evaluated at the (symbolic) inputs of the function

Concretely, this means that the current user functions for calculating directional derivatives need to be essentially removed:
```c++
    void callDerivative(const DMatrixVector& arg, DMatrixVector& SWIG_OUTPUT(res),
                        const DMatrixVectorVector& fseed, DMatrixVectorVector& SWIG_OUTPUT(fsens),
                        const DMatrixVectorVector& aseed, DMatrixVectorVector& SWIG_OUTPUT(asens),
                        bool always_inline=false, bool never_inline=false);

    void callDerivative(const SXVector& arg, SXVector& SWIG_OUTPUT(res),
                        const SXVectorVector& fseed, SXVectorVector& SWIG_OUTPUT(fsens),
                        const SXVectorVector& aseed, SXVectorVector& SWIG_OUTPUT(asens),
                        bool always_inline=false, bool never_inline=false);

    void callDerivative(const MXVector& arg, MXVector& SWIG_OUTPUT(res),
                        const MXVectorVector& fseed, MXVectorVector& SWIG_OUTPUT(fsens),
                        const MXVectorVector& aseed, MXVectorVector& SWIG_OUTPUT(asens),
                        bool always_inline=false, bool never_inline=false);
```
Furthermore, either `nfwd` or `nadj` always has to be 0 in the following overload:
```c++
    Function derivative(int nfwd, int nadj);
```
So it would make sense to replace it with the functions:
```c++
    Function derivativeFwd(int nfwd);
    Function derivativeAdj(int nadj);
```

I don't think these changes would actually influence actual usage a lot.

These changes would allow better structuring and more efficient implementations of SXFunction and MXFunction.

**Comment by jaeandersson** [comment]
Well, removing callDerivative is not really needed. It could be replaced by the two functions callForward and callReverse (or callAdjoint):
```c++
    void callForward(const DMatrixVector& arg, DMatrixVector& SWIG_OUTPUT(res),
                        const DMatrixVectorVector& fseed, DMatrixVectorVector& SWIG_OUTPUT(fsens),
                        bool always_inline=false, bool never_inline=false);

    void callForward(const SXVector& arg, SXVector& SWIG_OUTPUT(res),
                        const SXVectorVector& fseed, SXVectorVector& SWIG_OUTPUT(fsens),
                        bool always_inline=false, bool never_inline=false);

    void callForward(const MXVector& arg, MXVector& SWIG_OUTPUT(res),
                        const MXVectorVector& fseed, MXVectorVector& SWIG_OUTPUT(fsens),
                        bool always_inline=false, bool never_inline=false);

    void callReverse(const DMatrixVector& arg, DMatrixVector& SWIG_OUTPUT(res),
                        const DMatrixVectorVector& aseed, DMatrixVectorVector& SWIG_OUTPUT(asens),
                        bool always_inline=false, bool never_inline=false);

    void callReverse(const SXVector& arg, SXVector& SWIG_OUTPUT(res),
                        const SXVectorVector& aseed, SXVectorVector& SWIG_OUTPUT(asens),
                        bool always_inline=false, bool never_inline=false);

    void callReverse(const MXVector& arg, MXVector& SWIG_OUTPUT(res),
                        const MXVectorVector& aseed, MXVectorVector& SWIG_OUTPUT(asens),
                        bool always_inline=false, bool never_inline=false);
```

**Comment by jaeandersson** [comment]
OK, testing disabling this feature appears not really to be used in the test framework...

**Comment by jaeandersson** [comment]
Reverted as it breaks implicit_runge-kutta.py.

**Comment by jaeandersson** [comment]
Have introduced
```c++
    Function derivativeFwd(int nfwd);
    Function derivativeAdj(int nadj);
```
These functions work like `derivative(nfwd, 0)` and `derivative(0, nadj)` respectively, with the important difference that original function output is an input, not an output. These outputs may or may not be used by the derivative function. If they are never used, they can be set to an all-sparse input, meaning that the symbolics know that the value will be ignored.

**Comment by jaeandersson** [comment]
There are two tasks remaining:
 * Get CustomFunction working in Python
 * Implement PsdIndefDpleInternal::getDerivativeFwd and PsdIndefDpleInternal::getDerivativeAdj

@jgillis - could you have a look at this when you have time? Should be a quick task for you.

**Comment by jgillis** [comment]
This will be something for next week.

**Comment by jaeandersson** [comment]
No hurry.

**Comment by jgillis** [comment]
There is a feature that went missing in this branch:

When a function had ad_mode set to forward, calculating asking for an adjoint derivative went via derivative_via_jac and forward mode. This was unittested in function.py

Trying to enable that triggers an infinite loop.

**Comment by jaeandersson** [comment]
I agree that we need to find a solution to this , but I don't think that "ad_mode" is the right way. You might want to allow forward mode in some contexts but not in others. I think FunctionInternal basically needs to know if (1) forward and/or reverse mode derivatives can be calculated at all and (2) the relative costs of forward and reverse mode derivative calculations...

**Comment by jaeandersson** [comment]
Anyway, all of this is probably best implemented with virtual functions, not options.
Proposal: add the following:
```c++
virtual double weightAD();
```
The mode will then be determined by the condition
```c++
double w=weightAD();
if (w*nf <= (1-w)*na) {
  ... // use forward mode
} else {
   ... // use reverse mode
}
where `nf` and `na` are estimates of the number of forward and reverse sweeps respectively.

The implementation of "weightAD()" would be class specific. If reverse mode is not available, it could return 0 to force forward mode. To force reverse mode, it wound return 1. For sparsity pattern propagation, I would use the same approach, but with a different weighting factor.

**Comment by jgillis** [comment]
Weights are also fine. Be may guest to make a stub and i'll try to make it work with customfunction so we have feature preservation and we can merge into develop

**Comment by jaeandersson** [comment]
OK.

**Comment by jaeandersson** [comment]
All tests pass now. The `ad_mode` option has been replaced with the `hasDerForward`, `hasDerReverse` virtual functions plus an `ad_weight` option. `hasDerForward` will be true if forward derivatives have been implemented _or_ if the `custom_forward` (formerly `derivative_generator_forward`) option has been set. That is, there is no need to set `ad_mode` for PyFunction: the algorithm will detect if derivatives are available at all. The `ad_weight` and `ad_weight_sp` options can be used to force forward or reverse mode for a function where both forward and reverse mode are available. 
I'm ready to merge the branch, but I am not able to start the testbot. @jgillis?

**Comment by jaeandersson** [comment]
Merging branch. The `generatedocs` step fails in the testbot, but I guess that's an internal testbot issue, not related to the changes done.

**Comment by jaeandersson** [comment]
Merged.
