### ISSUE TITLE
Overzealous typemap cleanup?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1338]
In noticed that typemaps have lost some abilities:

```python
from casadi import *

x = SX.sym("x")
SX([[x,0],[0,1]]) # fails

blockcat([[x,0],[0,1]]) # works
```

**Comment by jaeandersson** [comment]
I would say that using `blockcat` would be the normal syntax here. Do we really want to support `SX([[x,0],[0,1]])`? Note that this has never worked in C++ (it's just a consequence of the SX-to-SXElement that existed in SWIG.
I do think the syntax is natural for creating an a numerical matrix:
```python
DMatrix([[1,0],[0,1]]) # works
SX([[1,0],[0,1]]) # fails
```
This can easily be achieved by changing the datatype in the constructor:
```c++
    /// Dense matrix constructor with data given as vector of vectors
    explicit Matrix(const std::vector< std::vector<DataType> >& m);
```
from `DataType` to `double`.

**Comment by jaeandersson** [comment]
After #1322, `SX([[1,0],[0,1]])` works correctly. `SX([[x,0],[0,1]])` doesn't, but I'd say that's a feature, not a bug. The correct syntax should be blockcat.
