### ISSUE TITLE
Documentation of operators

### ISSUE THREAD

**Issue by choeger** [casadi/casadi#1344]
I find a lot of OP_* operators when grepping through the source code, but their semantics seem to be unspecified. 

E.g. OP_ASSIGN seems a very special operator, where is it allowed?

OP_IF_THEN_ZERO: Is that one non-strict in the THEN argument?

**Comment by jaeandersson** [comment]
The OP_* operators are internal and there are no reasons for a user to use them directly. Therefore they are also not part of the public API. They are nothing more than enums defined in `casadi_calculus.hpp`. They are used to implement the virtual machines (SXFunction and MXFunction).

> E.g. OP_ASSIGN seems a very special operator, where is it allowed?

OP_ASSIGN is not in use.

> OP_IF_THEN_ZERO: Is that one non-strict in the THEN argument?

I don't know what you mean by non-strict. It's not short-circuiting, if that's what you mean. It calculates `f(x,y) := x ? y : 0` and `y` is always evaluated, even if `x!=0`. Note that the user syntax is:
```python
from casadi import *
cond = MX.sym('cond')
x = MX.sym('x')
print if_else(cond, x, 0)
```
