### ISSUE TITLE
Simpler API for explicitRK and implicitRK

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1347]
When implementing multiple shooting, especially for simple examples used in courses, it would help to have an integrator with a much simpler usage than what the Integrator class offers today.

I suggest repurposing explicitRK and implicitRK for this. That is, give up the requirement that the DAE and generated function to have the same syntax as the built-in integrators. Instead of the daeIn/daeOut I suggest it to accept a function with 2 inputs and 1 output: [x,p]->[xdot]. And instead of the integratorIn/integratorOut, I suggest it to simply calculate [x(0),p]->[x(tf)].

No advanced usage (quadratures, algebraic variables, explicit time dependence) would be supported. For this the existing Integrator class can be used.

**Comment by ghorn** [comment]
`[x,p] -> [xdot]` is good
I would strongly argue for `[x(0),p,h] -> [x(h)]` to avoid the need for a time transformation.

**Comment by jaeandersson** [comment]
> [x(0),p,h] -> [x(h)]

OK, I can buy that.

**Comment by jgillis** [comment]
strongly in favour

**Comment by jaeandersson** [comment]
:+1: 

Should the refactored explicitRK and implicitRK be made available under different names?

**Comment by jaeandersson** [comment]
OK, so this is what I'm implementing in the end:
 * explicitRK is replaced by simpleRK with the declaration `MXFunction simpleRK(Function f, int N=10, int order=4);`. It returns a function with 3 inputs (x0, p and tf) and 1 output (xf).
 * implicitRK is replaced by simpleIRK with the declaration `MXFunction simpleIRK(Function f, int N=10, int order=4, const std::string& scheme="radau", const std::string& solver=newton, const Dictionary& solver_options = Dictionary());`
 * In addition, an simpleIntegrator function is created with the declaration `MXFunction simpleIntegrator(Function f, const std::string& integrator="cvodes", const Dictionary& integrator_options = Dictionary());`. It would have the same API (by wrapping f and the Integrator class) as the function created by the above classes.

@jgillis @ghorn: Any objections?

**Comment by jaeandersson** [comment]
I'll also add "csparse" as default linear solver in "newton", so that it works without explicitly passing a dictionary.

**Comment by jgillis** [comment]
I do have so comments:
 * the total integration time 'h' that Greg proposed is missing. I think it is good to have as MX-argument.
 * in the spectrum of userfriendliness, there is still opportunity to shift a few notches up:

A return type of MXFunction still implies a syntax like `simulate([x[k],u[k]])[0]`  or `simulate(x=x[k],p=u[k])[0]`  as opposed to `simulate(x[k],u[k])` in optoy.

The input type of the ode still requires the construction of an MXFunction upfront. One may shorten this like:

```python
@simpleOde(2,1)  # 2 states, one control
def ode(x,u):
   p = x[0]
   q = x[1]
   return vertcat([p,q+u])
```

**Comment by jaeandersson** [comment]
> A return type of MXFunction still implies a syntax like simulate([x[k],u[k]])[0] or simulate(x=x[k],p=u[k])[0] as opposed to simulate(x[k],u[k]) in optoy.

Or `[xf] = integrator([x[k],u[k]])`. I don't think this is a problem. You can't use CasADi if you don't know how to call a function. 

> The input type of the ode still requires the construction of an MXFunction upfront. One may shorten this like: ...

I don't think that's motivated. Again, you need to be able to construct a function with two inputs and one output to be able to use CasADi. And note that the function does not need to be of MXFunction type, it can be any type derived from Function.

Please have a look at the committed integrator.

Here is a simple usage example:
```
from casadi import *
x = SX.sym("x"); p = SX.sym("p")
f = SXFunction([x,p],[p*sin(x)])
F = simpleIRK(f)
x0=1; p0=2; h=3
[xf] = F([x0,p0,h])
print xf # 3.13252
```
