### ISSUE TITLE
Auto-init functions?

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1350]
@mvukov suggested automatically initializing Function instances on first use. I'm not fond of that idea, but I could imagine having initialization be done as part of the constructor, by default. Then you would also need to pass options via the constructor:
```python
nlp = ...
solver = NlpSolver("ipopt", nlp, hessian_approximation="limited-memory")
solver.setInput(x0,"x0")
solver.setInput(lbx, "lbx")
solver.evaluate()
xopt = solver.getOuput("x")
lam_x = solver.getOuput("lam_x")
```
or, more compactly still (with shorthands for evaluation):
```python
nlp = ...
solver = NlpSolver("ipopt", nlp, hessian_approximation="limited-memory")
sol = solver({"x0": x0, "lbx" : lbx})
xopt, lam = [sol[i] for i in ('x', 'lam_x')]
```

**Comment by mvukov** [comment]
:+1:

**Comment by jaeandersson** [comment]
cf. #1351

**Comment by ghorn** [comment]
Does the user ever need to do anything besides `setOption` between the constructor and `setInput`/`evaluate` ?

**Comment by jaeandersson** [comment]
There are more things, like setInputScheme, setOutputScheme.

**Comment by jaeandersson** [comment]
The point was about the default behavior. It should still be possible to construct functions without initializing them. For example, one could have the following mean create, but not initialize:
```python
solver = NlpSolver("ipopt", nlp, False)
solver.setOption(...)
solver.setInputScheme(...)
solver.init()
```

Just to be clear, I'm not sold on the whole idea (yet), just wanted to brainstorm it.

**Comment by ghorn** [comment]
I'm not sold either. One option would be defining `isInit() = init(); return true`

**Comment by jaeandersson** [comment]
hack hack hack

**Comment by jaeandersson** [comment]
So, here is my (pretty radical) proposal: 
 * Remove "init" completely, the constructor will (always) handle what is now done in the init function.
 * Remove "setOption" completely. Options are supplied as a dictionary to the constructor. This dictionary will not be stored by the object.
 * setInputScheme are setOutputScheme become options.

Since this is a very breaking change, it is certainly for CasADi 3.0. At the same time as this is implemented, I would remove getInput/evaluate/setOutput and make the function (at least in Python), tuple-in, tuple-out (instead of list-in, list-out). 
```python
x = MX.sym('x')
y = MX.sym('y', 10)
f = MXFunction([x,y], [sin(x)+y], verbose=true, name='f')
z0 = f(1, 2)
```
Or alternatively, dictionary-in, dictionary-out:
```python
nlp = ...
solver = NlpSolver("ipopt", nlp, hessian_approximation="limited-memory")
arg = {'x0': x0, 'lbx':lbx}
sol = solver(arg)
print sol['x]
print sol['lam_x']
```
In MATLAB, replace dictionary with `struct`.

**Comment by ghorn** [comment]
I like this proposal. Some people like to abuse `setOption` to change things after init is finished so expect complaints... I guess `reinit` would go away huh

**Comment by jaeandersson** [comment]
I think it is a common error that people set options after init() and then are confused when the the option appears to have no effect. This would resolve that. There is no `reinit`. There is only `init`.

**Comment by mvukov** [comment]
:+1:

**Comment by jaeandersson** [comment]
Step 1 would be to add the Dictionary constructor with side effect of init. E.g.
```python
solver = NlpSolver("ipopt", nlp, dict)
```
would be shorthand for
```python
solver = NlpSolver("ipopt", nlp, dict)
solver.setOption(dict)
solver.init()
```

**Comment by ghorn** [comment]
:+1: 

(still waiting for the undocumented feature crew to complain)

**Comment by jaeandersson** [comment]
After some thinking, I realize that it would make sense to implement this feature and at the same time resolve an issue that has been bugging me for some time.

Currently, it is good practise but not required for the user to name the instances of Function. This results in a lot of "unnamed_mx_function" and the like being created, which makes error messages and generated code less much readable.

I propose to add the function name as a mandatory first argument of the constructor at the same time as implementing the auto-init feature. I.e.

```python
solver = NlpSolver('my_solver', 'ipopt', nlp, opts)
```
would be shorthand for
```python
solver = NlpSolver('ipopt', nlp, opts)
solver.setOption('name', 'my_solver')
solver.setOption(opts)
solver.init()
```

This would allow the new syntax to be added without breaking existing code. Then, in a later release and when init() has been made fully redundant, the old syntax would be deprecated. 

@jgillis @ghorn @mvukov - any objection?

**Comment by jgillis** [comment]
If I was to be enforced specifying a name, I'd probably end up with 'dummy' all over the place...
NlpSolver is usually a top-level thing with only one occurrence; the current default of 'unnamed_nlp_solver'

**Comment by jaeandersson** [comment]
It's no more strange than having to give a name to all symbolic primitives:
```python
x = MX.sym('x')
```
the argument is also just for printing.

**Comment by jaeandersson** [comment]
I think what people will typically end up doing is to use the name of the variable as name passed:
```python
f = SXFunction('f', ...)
nlp = MXFunction('nlp', ...)
solver = NlpSolver('solver', ...)
```

**Comment by mvukov** [comment]
:+1:

**Comment by jaeandersson** [comment]
Speak now or forever hold your peace

**Comment by ghorn** [comment]
I always name my functions but I see no reason to force it on anyone else, especially when the name option is so easy to use.

**Comment by ghorn** [comment]
I like having a minimal casadi python script be as lightweight and clear as possible

**Comment by mvukov** [comment]
I see forcing name definition as an interesting option when doing code generation - such that functions are automatically named in the generated code.

In a use case when the user does not do code generation, I see no benefit of forcing users to define it.

Maybe make it optional but make a doc with "good practices".

**Comment by jaeandersson** [comment]
There are a number of points I want to make:
 * To say that things should be good practise doesn't mean much. Reality is that people don't name expressions. You can say the same about naming symbolic variables. Why not name all symbolic expressions "dummy" by default? If course, a printout such as `dummy*dummy - 2*sin(dummy-dummy)` might be a bit hard to understand and each `dummy` might be a different expression, but hey, CasADi doesn't care about the print-name during evaluation.
 * If we don't simultaneously change the function signature, introducing the auto-init feature will be a breaking change. This way, we can have the old syntax and new syntax side by side and then deprecate at a later release. This is very important.
 * The whole issue will make scripts more minimalist since there what was previously done on multiple lines would be done on a single line. There would be no confusion about when options can be set etc. Also, there would no longer be any need for the function to store the options internally - they are only needed in the constructor. This decreases memory overhead.

**Comment by jaeandersson** [comment]
> In a use case when the user does not do code generation, I see no benefit of forcing users to define it.

It is not just about code generation. It is also (importantly) about error messages and log messages. When you get an error, it is very useful to know in which function object it occurred. Same with logging, print-to-screen etc.

**Comment by jgillis** [comment]
Let's do this!
Op 23 mei 2015 13:23 schreef "Joel Andersson" <notifications@github.com>:

**Comment by mvukov** [comment]
> It is not just about code generation. It is also (importantly) about error messages and log messages. When you get an error, it is very useful to know in which function object it occurred. Same with logging, print-to-screen etc.

@jaeandersson this is a very good point! :+1: for forcing name definition :smile:

**Comment by jaeandersson** [comment]
Implementing this feature is trivial. A separate issue can be used for deprecating the old syntax.

**Comment by ghorn** [comment]
What about making it an optional input instead of an option, so it's less verbose than a full blown option?
`solver = NlpSolver('ipopt', opts, name='my solver lol')`

**Comment by jaeandersson** [comment]
> What about making it an optional input instead of an option, so it's less verbose than a full blown option?

It doesn't make sense. It would make the "auto-init" feature a breaking change. And I see no advantage of:
```python
solver = NlpSolver('ipopt', {}, name='my solver lol')
```
over
```python
solver = NlpSolver('ipopt', {'name' : 'my solver lol'})
```

I don't understand why you don't agree that every user-created function should be given a name. It makes user code much more maintainable, gives better error messages etc. And by adding this feature at the same time as auto-init is introduced, allows auto-init to be added in a maintainable way.

**Comment by ghorn** [comment]
> I don't understand why you don't agree that every user-created function should be given a name.

I personally like it, in fact in the haskell bindings I require names. I'm mostly afraid of raising the barrier to entry. It's fine though, go ahea

**Comment by jaeandersson** [comment]
OK, commits incoming...

**Comment by jaeandersson** [comment]
The new syntax is now available for all classes inheriting from Function. I've opened a separate issue (#1429) for the deprecation of the old syntax.
