### ISSUE TITLE
Function call with dictionary in, dictionary out

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1351]
We've discussed how to simplify the syntax for function evaluation. One option has been to to support something like:
```python
xf,qf = fcn(x0=4, p=b).xf.qf
```
I think a better approach would be to simply always support passing a dictionary instead of vector. The output would then also be a dictionary:
```python
sol = fcn({'x0':4, 'p':b})
xf, qf = (sol[i] for i in ('xf','qf'))
```
I find this more natural, since the dictionary keys are then always passed with string quotes, instead of the mixed use. It also extends naturally to C++ and MATLAB (in MATLAB it would be struct in, struct out).

**Comment by ghorn** [comment]
The syntax `xf,qf = fcn(x0=4, p=b).xf.qf` seems very unpythonic

**Comment by jaeandersson** [comment]
> The syntax `xf,qf = fcn(x0=4, p=b).xf.qf` seems very unpythonic

I'm not proposing that. I'm proposing `sol = fcn({'x0':4, 'p':b})`

**Comment by jgillis** [comment]
What is the advantage of `fcn({'x0':4, 'p':b})` over `fcn(x0=4,p=b)`?

**Comment by jaeandersson** [comment]
Since the return type is a dictionary, it feels natural if the argument is a dictionary.

**Comment by ghorn** [comment]
@joris are you proposing to overload `Function` calls with schemes using *kwargs? Because I have to admit that seems nice for `Function`s with schemes.

**Comment by jaeandersson** [comment]
I think more important is the return type.

**Comment by jaeandersson** [comment]
I quite like the following syntax in c++:
```c++
MX res1, res2;
assign_map("res1", res1, "res2", res2, f(make_map("arg1", arg1, "arg2", arg2));
```
It matches the following syntax that I've added already:
```c++
MX res1, res2;
assign_vector(res1, res2, f(make_vector(arg1, arg2));
```

**Comment by jaeandersson** [comment]
After some research, I think this is the most pythonic syntax:
```python
from operator import itemgetter
xf, qf = itemgetter('xf', 'qf')(fcn({'x0':4, 'p':b}))
```
@jgillis @ghorn - what say you?

**Comment by jgillis** [comment]
I doubt this is an improvement over `xf, qf = (fcn({'x0':4, 'p':b})[i] for i in ('xf','qf'))`..

**Comment by jaeandersson** [comment]
It is a huge improvement. Look at this example:

```python
from casadi import *
from operator import itemgetter
x = MX.sym('x')
f = MXFunction('f', [x], [sin(x),cos(x)])
print 'Without itemgetter'
cosx, sinx = (f([sqrt(x+2)])[k] for k in (0,1))
print countNodes(cosx+sinx) # 11
print 'With itemgetter'
cosx, sinx = itemgetter(0, 1)(f([sqrt(x+2)]))
print countNodes(cosx+sinx) # 7
```

**Comment by ghorn** [comment]
this is all sugar around the core dictionary in, dictionary out, right?

**Comment by jaeandersson** [comment]
Well, it's about how to.structure the example scripts and other user code. I like dictionaries (or structs in Matlab) because it should be clear to all Python users how they work. We want to use standard constructs as much as possible.

**Comment by jaeandersson** [comment]
Reopened, implicit type conversion not working:
```python
from casadi import *
x = SX.sym('x')
f = SXFunction('f', [x], [sin(x),cos(x)], {'input_scheme':['x'],'output_scheme':['sinx','cosx']})
print f({'x': DMatrix(3)}) # works
print f({'x': 3}) # fails
```
