### ISSUE TITLE
clone a Function for evaluation in a separate thread

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1354]
I'm wishing for something like:

`casadi::Function casadi::Function::threadsafe_copy();`

which would do some sort of deep clone, returning a function which promises not to mutate any global state. What's involved in this?

**Comment by jaeandersson** [comment]
See my comment to #1355: My plan was to make cloning unnecessary (and remove it completely), rather than trying to fix it.

**Comment by jaeandersson** [comment]
Since Parallelizer is now gone (cf. #1064), and since the Map node that replaces it does not require cloning, this feature is pretty much unnecessary as I see it. I refer to #1356 for progress towards thread-safe evaluation.
