### ISSUE TITLE
Separate work vector from Function

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1356]
Continuation of #914. The work vectors should be moved out completely from MXFunction, as well as other Function-derived classes. This will decrease memory overhead, give thread safety during evaluation (also for codegen) as well as decrease unnecessary copying. Cf. also #1355, #1354

**Comment by jaeandersson** [comment]
Note: When this is completed, the functions that can be used "thread-safe" should be marked "const". If the function can't change internal data of the class, it should be safe to evaluate in parallel.

**Comment by jaeandersson** [comment]
@jgillis @ghorn I think we should remove all usage of "setInput-evaluate-getOutput" in examples and tutorials in the 2.4 release and communicate this as one syntax change together with the removal of "constructor-setOption-init".

**Comment by jgillis** [comment]
Indeed. But it would still be a (deprecated) feature, right?

**Comment by jaeandersson** [comment]
Yes, both `setInput-evaluate-getOutput` and `constructor-setOption-init` and the new syntax would be available in 2.4 with deprecation warning. After 2.4, they would go away.

**Comment by jaeandersson** [comment]
I just want us to avoid having a major breaking syntax change in 2.4 and another major breaking syntax change in 2.5.

**Comment by ghorn** [comment]
SGTM

**Comment by jaeandersson** [comment]
This issue will continue into 2.5.

**Comment by jaeandersson** [comment]
The following interfaces need updating:
 * KNITRO
 * WORHP
 * SNOPT

Otherwise the old syntax is pretty much phased out, except for the unit tests. When everything except the unit tests are updated, I'll deprecate the old syntax and mark the corresponding unit tests "known_bug".

**Comment by jaeandersson** [comment]
ping @jgillis

**Comment by jaeandersson** [comment]
Buffered evaluation (setInput - evaluate - getOutput) has now been completely internally. Old syntax only survives in the test suite.
@jgillis - what do you think we should do with the test suite? Let the test fail or restructure the tests?
