### ISSUE TITLE
MXFunction generated code missing functions

### ISSUE THREAD

**Issue by sebastian-ekstrom** [casadi/casadi#1362]
When using the generateCode method of an MXFunction object, the generated code can make use of the functions `sq` and `sign`. However, those two functions are not actually generated, meaning that if the code does make use of them, it will return an error when called. The Python script below provides an example of this problem: the code generated from the SXFunction evaluates just fine, but the one from the MXFunction does not; and looking into the generated C files, `nlp1.c` has `sq` and `sign`defined, but `nlp2.c` does not.
```python
from os import system
from casadi import *

def to_external_function(fcn, name):
    print 'Generating code for', name
    fcn.generateCode(name + '.c')
    system('gcc -fPIC -shared -O3 ' + name + '.c -o ' + name + '.so')
    fcn_e = ExternalFunction('./' + name + '.so')
    return fcn_e

# function 1

x1 = SX.sym('x', 2)
f1 = x1[0]*x1[0] + x1[1]*x1[1]

nlp1 = SXFunction(nlpIn(x=x1), nlpOut(f=f1))
nlp1.init()

nlp1_cg = to_external_function(nlp1, 'nlp1')
nlp1_cg.init()

nlp1_cg.setInput([1,1])
nlp1_cg.evaluate()
print 'Function 1 result:', nlp1_cg.getOutput()

# function 2

x2 = MX.sym('x', 2)
f2 = x2[0]*x2[0] + x2[1]*x2[1]

nlp2 = MXFunction(nlpIn(x=x2), nlpOut(f=f2))
nlp2.init()

nlp2_cg = to_external_function(nlp2, 'nlp2')
nlp2_cg.init()

nlp2_cg.setInput([1,1])
nlp2_cg.evaluate()
print 'Function 2 result:', nlp2_cg.getOutput()
```

**Comment by jaeandersson** [comment]
Thanks for reporting this. This has been fixed now.
