### ISSUE TITLE
Weird error messages in Python

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1364]
Something has happened with the syntax errors:
```python
from casadi import *
x = SX.sym("x")
x.foo()
```
This returns the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5589e33176d9> in <module>()
----> 1 x.foo()

/Users/janderss/local/casadi/casadi.pyc in <lambda>(self, name)
  14820     for _s in [ExpSX, GenSX, PrintSX]:
  14821         __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
> 14822     __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
  14823     __repr__ = _swig_repr
  14824 

/Users/janderss/local/casadi/casadi.pyc in _swig_getattr(self, class_type, name)
     69 
     70 def _swig_getattr(self, class_type, name):
---> 71     return _swig_getattr_nondynamic(self, class_type, name, 0)
     72 
     73 

/Users/janderss/local/casadi/casadi.pyc in _swig_getattr_nondynamic(self, class_type, name, static)
     64         return method(self)
     65     if (not static):
---> 66         return object.__getattr__(self, name)
     67     else:
     68         raise AttributeError(name)

AttributeError: type object 'object' has no attribute '__getattr__'
```

**Comment by jaeandersson** [comment]
@jgillis ?

**Comment by jgillis** [comment]
Looks like a swig issue to me

**Comment by jgillis** [comment]
Cannot reproduce this with swig 2.0

**Comment by jaeandersson** [comment]
OK.

**Comment by jaeandersson** [comment]
I'm reopening this. There _has to_ be a way to fix this, even if it means patching SWIG. Error messages are not very unreadable if you can't see which function is failing.

**Comment by jgillis** [comment]
Just reproduced this in swig 3.0..

**Comment by jgillis** [comment]
The swig code makes little sense; there is no `object.__getattr__` in my Python.

**Comment by jaeandersson** [comment]
Ah, ok. So it's really a swig 3.0 thing.

**Comment by jaeandersson** [comment]
did you try swig master or the matlab branch?

**Comment by jgillis** [comment]
Matlab branch

**Comment by jaeandersson** [comment]
ok, keep in mind that matlab branch is not in synch with swig master

**Comment by jaeandersson** [comment]
Is this fixed?  Then we should remove the wontfix label.

**Comment by jgillis** [comment]
I would bet it is.

**Comment by jgillis** [comment]
Can you test?

**Comment by jaeandersson** [comment]
Yup.

**Comment by rdeits** [comment]
I'm getting this same error on my own swig-based project. Do any of you know if there's an upstream bug open in swig 3 for this? There's nothing on https://github.com/swig/swig/issues but I thought there might be other channels I'm not aware of.

**Comment by daniele-niero** [comment]
add the  -modern flag when you launch the swig wrappers, something like this:

swig -python -modern myInterface.i

This will generate post 2.2 modern python classes, the ones that derive from 'object'.
Previous to this big change in python classes didn't have any special methods such as __getattr__.
Unless you want compatibility with python <= 2.2, this will fix the problem,

**Comment by jaeandersson** [comment]
Thanks!

**Comment by pstjohn** [comment]
I seem to be getting this same error with the current OS X binary (python 34)

**Comment by jgillis** [comment]
This will be properly fixed in 3.1..

Op 22-jul.-2016 00:50 schreef "Peter St. John" <notifications@github.com>:

**Comment by pstjohn** [comment]
Cool, thanks!

The exact error I'm getting (which is stopping me from doing things like `np.asarray(sx_object)`) is:

```python
>>> casadi.SX.sym('x', 4).__array__()
Traceback (most recent call last):
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 19210, in foo
    return v(*args,**kwargs)
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 9241, in __array__
    return self.full()
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 8286, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 19272, in foo
    raise exc_info[1].with_traceback(exc_info[2].tb_next)
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 19270, in foo
    raise ne.with_traceback(exc_info[2].tb_next)
  File "/Users/pstjohn/Packages/casadi/casadi.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: Unkown attribute: <class 'casadi.casadi.SX'> has no attribute 'full'.
```

**Comment by jaeandersson** [comment]
Yeah, this is unrelated. Let's continue in #1831

**Comment by vdwees** [comment]
FYI I got the 
`AttributeError: type object 'object' has no attribute '__getattr__'`
error when compiling casadi with swig 3.0.8 (the default version for Ubuntu 16.04)
Installing swig version 3.0.12 fixed the issue.
Related: https://github.com/swig/swig/issues/588
