### ISSUE TITLE
qpOASES missing in Windows binaries

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1367]
Didn't we fix this?

**Comment by jgillis** [comment]
I did not, and I doubt anyone else could have done it.

**Comment by jgillis** [comment]
Is it highly beneficial to have it by Monday? In that case, I can do an rc2..

**Comment by jaeandersson** [comment]
No, don't worry. 'nlp.ipopt' works fine for the course.

**Comment by jgillis** [comment]
Fixed as of 2.3.0
