### ISSUE TITLE
codegen examples

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1369]
Examples are an important form of casadi documentation. They are also unit-tested so they remain valid, no?

We should add codegen examples, specifically OCPs.

**Comment by jgillis** [comment]
Virtually all examples are run in the test-suite.
Not all of them are actually tested for numerical results though.

**Comment by ghorn** [comment]
Just running an OCP with a simple asserts on solution properties would prevent 99% of regressions relevant to users

**Comment by jgillis** [comment]
We have such examples now
