### ISSUE TITLE
np.array weirdness

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1373]
I'm not sure what is going on on my system, but the following code does weird things

```python
import casadi
import numpy as np
print np.array(casadi.DMatrix([2]))
print np.array(casadi.DMatrix([1,2,3.0]))
```

System: debian jessie, 64 bit, source build, fe37e5f4b294014c6

python 2.7.8-3 
python-numpy 1:1.8.2-2

```
[[ 0.]]
Traceback (most recent call last):
  File "debugme.py", line 6, in <module>
    print np.array(casadi.DMatrix([1,2,3.0]))
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1615, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
  File "/usr/lib/python2.7/dist-packages/numpy/core/arrayprint.py", line 449, in array2string
    elif reduce(product, a.shape) == 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
v
```

**Comment by jaeandersson** [comment]
Output on OSX:
```
[[ 2.]]
[[ 1.]
 [ 2.]
 [ 3.]]
````

**Comment by ghorn** [comment]
What weird things does it do?

**Comment by jgillis** [comment]
Very weird things..

**Comment by ghorn** [comment]
Wow that sounds weird

**Comment by jgillis** [comment]
The first line gives zero, the second line some weird printing error.
I suspect a low-level memory issue

**Comment by jgillis** [comment]
It is a casadi regression alright. Running bisect..

**Comment by jaeandersson** [comment]
> It is a casadi regression alright. Running bisect..

How weird. It's not like anyone made any changes to the get/set typemaps...

**Comment by jgillis** [comment]
```
7347188e57e8f43b4a8945cd821eb395824fff83 is the first bad commit
commit 7347188e57e8f43b4a8945cd821eb395824fff83
Author: Joel Andersson <j.a.e.andersson@gmail.com>
Date:   Fri Mar 20 13:10:06 2015 +0100

    #1360 Return-by-value in SWIG for all Matrix::get* overloads

:040000 040000 a5acee7b593a32e9fd05297d91336ce6e1ea244a b9f2850c36c9c4b9bd511fec96db4cadb351a4cd M	casadi
:040000 040000 4e67dcd5cabed017a5ed0026bbf68e8d675c7d64 8f76d6de6f92923925f78eb4e30652da01b00009 M	test
```

**Comment by jaeandersson** [comment]
How surprising... How can I reproduce it?

**Comment by jgillis** [comment]
A virtual machine with the above specs?

**Comment by jaeandersson** [comment]
OK, will try.

**Comment by jgillis** [comment]
What is happening here is that `void get(std::vector<double>& SWIG_OUTPUT(m), bool tr=false) const;` is used in matrix.i after 7347188e57e8f43b4a8945:
```
      r = n.zeros((self.size1(),self.size2()))
      self.get(r)
      return r
```
It is not clear to me how it can work correctly in some configurations.

**Comment by jgillis** [comment]
ping @jaeandersson

 * Any idea how this can work on your system?
 * For a fix I see at least two options: 1) revive `get(Matrix<>&)`, possibly with another name 2) do a densify, followed by a `get(std::vector<double>& SWIG_OUTPUT(m), bool tr=false)`

**Comment by jaeandersson** [comment]
I don't understand why we support return-by-reference at all in SWIG. It's not safe or pythonic. And savings are marginal at best.

**Comment by jgillis** [comment]
Right, this may be a good time to purge that.

Apparently the offending commit is not in the release-candidate or master, which is fortunate.
It still puzzles me how you can experience a working develop..
