### ISSUE TITLE
2.3 release

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1378]
Are we ready for a 2.3.0 release?

Should it include the recent change in signature of Parallelizer?

**Comment by jaeandersson** [comment]
No, Parallelizer changes are for 2.4. And the change is not completed, Parallelizer will be removed completely.

**Comment by jaeandersson** [comment]
(Yes, to 2.3.0 release.)

**Comment by jaeandersson** [comment]
There were some fixes to to the release candidate, like 972df107f4a5eee24e6d50ac0dc4039c3991d795.

**Comment by jaeandersson** [comment]
Other commits are for 2.4.

**Comment by jgillis** [comment]
@jaeandersson @ghorn   feel free to test the new rc

**Comment by ghorn** [comment]
I can test next week. I'm moving and starting the internship at the moment

**Comment by jgillis** [comment]
Tomerge: 958b94af6b608f38

**Comment by ghorn** [comment]
Which commit should I test?

**Comment by jgillis** [comment]
release-2.3.0-rc2

**Comment by ghorn** [comment]
rc2 seems to be ok for me

**Comment by jaeandersson** [comment]
Can we generate the official release and get over with it? :P

**Comment by ghorn** [comment]
most well tested RC ever

**Comment by jaeandersson** [comment]
I've closed the milestone as well. I see no use in making a lot of publicity around this release as 2.4 is just around the corner.
