### ISSUE TITLE
Generic inputs for MXFunction

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1379]
It should be possible to pass more generic expressions as inputs to MXFunction in the same way as is already possible for SXFunction. This would simplify user syntax and makes printouts more readable (without Vertsplit/Horzsplit). Reasonable, and implementable, are combinations of Vertcat/Horzcat/Diagcat and Reshape.

**Comment by ghorn** [comment]
Would this be able to help the problem of using sparse design variables?

**Comment by jaeandersson** [comment]
What problem?

**Comment by ghorn** [comment]
Adding support for sparse design variables

**Comment by jaeandersson** [comment]
Sparse inputs have been supported since long for SXFunction and MXFunction. Do you mean for NlpSolver? This has no effect on that.

**Comment by jaeandersson** [comment]
This issue will allow you to do things like: 
```python
x = MX.sym("x")
y = MX.sym("y")
f = MXFunction([vertcat((x,y))],[x+y])
```
It makes modelling more natural. Structures can be refactored to use this feature.

**Comment by jgillis** [comment]
A note for any evesdropping users that want to have this feature right now: https://gist.github.com/jgillis/6c8d3a4b9567e39ba30e

**Comment by jaeandersson** [comment]
Errors reported for 4693d0017702095fa584830ac841563e579f7e4b. Will have a look.

**Comment by jaeandersson** [comment]
Feature now implemented, but there are probably still bugs to be ironed out. Also need to investigate the unit test failure (that I didn't get on my computer when running `python alltests.py`).

**Comment by jaeandersson** [comment]
@jgillis @ghorn  Note that this feature is slightly more efficient than using "spit". It also gives much more readable outputs. So it makes sense to have structures use it internally, once it becomes stable.

**Comment by jaeandersson** [comment]
Tested replacing `SX` by `MX` in `sensitivity_analysis.py` example. Feature definitely not working yet...

**Comment by jaeandersson** [comment]
Should work now. Closing issue.
