### ISSUE TITLE
Remove or refactor IMatrix, avoiding operations not defined for integers

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1385]
I am starting to think that it makes sense to get rid of `Matrix<int>` a.k.a. IMatrix. I am trying to think of a good reason to keep it, but I can't think of any. DMatrix works fine for representing integers.

This would make the API smaller and get rid of problems of the type you see below (which I get after updating Clang):

```
[ 46%] Building CXX object casadi/core/CMakeFiles/casadi.dir/std_vector_tools.cpp.o
In file included from /Users/janderss/dev/casadi/casadi/core/casadi_instantiations.cpp:26:
In file included from /Users/janderss/dev/casadi/casadi/core/sx/sx_element.hpp:33:
In file included from /Users/janderss/dev/casadi/casadi/core/mx/../matrix/matrix.hpp:35:
/Users/janderss/dev/casadi/casadi/core/sx/../matrix/../runtime/runtime.hpp:413:27: warning: using floating point absolute value function 'fabs' when argument is of integer type
      [-Wabsolute-value]
          res = fmax(res, fabs(sums[head]));
                          ^
/Users/janderss/dev/casadi/casadi/core/sx/../matrix/matrix_impl.hpp:2642:12: note: in instantiation of function template specialization 'casadi::casadi_norm_inf_mul<int>' requested
      here
    return casadi_norm_inf_mul(ptr(), sparsity(), A.ptr(), A.sparsity(),
           ^
/Users/janderss/dev/casadi/casadi/core/sx/../matrix/../runtime/runtime.hpp:413:27: note: use function 'std::abs' instead
          res = fmax(res, fabs(sums[head]));
                          ^~~~
                          std::abs
```

**Comment by jgillis** [comment]
I'm halfhearted about this attempt but anyway: for indexing?

**Comment by jaeandersson** [comment]
MATLAB uses double matrices for indexing by default. If they can do it...

**Comment by ghorn** [comment]
Yeah if MATLAB does it it's probably solid design

**Comment by ghorn** [comment]
Why do you need to take the absolute value of an IMatrix?

**Comment by jaeandersson** [comment]
The fundamental problem is that a lot of operations are not all operations are defined for int, e.g
 sin, sqrt (return non-int) or things like NaN, inf. Since SWIG initializes all functions for template classes, this will cause problem even if you don't use them. Anyway, will think of sth.

**Comment by jgillis** [comment]
#2494
