### ISSUE TITLE
Named expressions

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1387]
It would be useful to be able to name intermediate symbolic expressions. This would be best implemented as an MX node:
```python
from casadi import *
x = MX.sym('x')
i = monitor(sin(x) + x, 'my intermediate expression')
y = 2*i
f = MXFunction([x], [y])
f.init()
```
Note that the operation itself will normally be free thanks to live variables (cf. reshape).

This "naming node", would never be simplified away (if at all used) and would have derivative rules that allows it derivatives to be tracked:
```
f.derForward(2) # should create a new node named e.g. "forward(2) of 'my intermediate expression' ")
```
Furthermore, when codegen'd, a debug string should be optionally printed:
```c
#ifndef NDEBUG
printf("my intermediate expression:\n");
<print the nonzeros>
#endif
```
Similar functionality would also be useful in the MX VM.

At least in c++, it is possible to define a preprocessor macro to automatically include the file name, the line number and the statement:
```c++
MX x = MX::sym("x");
MX i = casadi_name(sin(x) + x)
```
Which could automatically generate a string such as "line xx in file yy: "sin(x) + x". In Python I'm not sure if the same would be possible, but I guess something could be done with "inspect":
```python
import inspect
fr=inspect.currentframe()
print fr.f_lineno
```

With this in place, the "printme" operation should be removed.

**Comment by jaeandersson** [comment]
Ping @jgillis

**Comment by jgillis** [comment]
This is an awesome idea.
It would become even better if we can do it for SX.
printme works with a numerical identifier now.
There could be a global lookup table were we map from identifier to expression name.

**Comment by jgillis** [comment]
Related: #305

**Comment by jaeandersson** [comment]
Why would we want to do it for SX? We should move away from SX for modelling.

**Comment by ghorn** [comment]
+1

**Comment by jaeandersson** [comment]
`monitor` is probably a better name than `named`.

**Comment by jaeandersson** [comment]
Feature implemented. Syntax:
```python
from casadi import *
x = MX.sym("x",3)
y = MX.sym("y")
z = exp(x+1)+y+3
z = z.monitor('hello, world!')
f = MXFunction([x,y],[z,z[1]])
f.init()
print "VM evaluation:"
f.evaluate()
print "------"

print "Forward mode AD:"
tf = f.tangent(1, 0)
tf.init()
tf.evaluate()
print "------"

print "Reverse mode AD:"
gf = f.gradient(0, 1)
gf.init()
gf.evaluate()
print "------"

print "Codegen:"
f.generateCode("f.c")
from os import system
system("gcc -fPIC -shared f.c -o f.so")
f2 = ExternalFunction("./f.so")
f2.init()
f2.evaluate()
print "------"
```
which outputs:
```
VM evaluation:
hello, world!:
[5.71828, 5.71828, 5.71828]
------
Forward mode AD:
fwd(0) of hello, world!:
[1, 1, 1]
hello, world!:
[5.71828, 5.71828, 5.71828]
------
Reverse mode AD:
adj(0) of hello, world!:
[0, 1, 0]
hello, world!:
[5.71828, 5.71828, 5.71828]
------
Codegen:
hello, world!
[5.71828, 5.71828, 5.71828]
------
```
