### ISSUE TITLE
Codegen of NAN and INFINITY

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1389]
Not-a-number and infinity are now codegen'd as "nan" and "inf", respectively. It makes sense to instead use NAN and INFINITY, which is (more) standard C syntax.

**Comment by mvukov** [comment]
You know that by the standard NaN check is done like:

```c++
if (a != a) // if NaN ...
{
...
}
```

**Comment by jaeandersson** [comment]
It's not about checking for NaN, it's about declaring a NaN.
Btw, `isnan` is available in C99, C++11.

**Comment by ghorn** [comment]
`isnan` is safer if it's available. `a != a` can be optimized out sometimes (`-ffast-math` ?)
