### ISSUE TITLE
parallelize jacobian/hessian

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1400]
Sometimes I spend up to half of the total time waiting for `NlpSolver::init()`. I think most of the time is setting up jacobian/hessian. Should this be parallelizable since it's running a bunch of sweeps?

**Comment by jaeandersson** [comment]
Sparsity pattern propagation can be parallelized, but I don't think that's the solution. You have to refactor your code. Or rather, find out what takes time and why. There is no reason why NlpSolver::init should be so slow.

**Comment by jgillis** [comment]
Is your jacobian of a form that requires bicoloring for efficient hierarchical sparsity calc?

**Comment by ghorn** [comment]
It's a standard direct collocation optimal control problem with a dense column. It's just really large when I expand it.

**Comment by ghorn** [comment]
@jaeandersson do you expect `expand` to be fast on a well-formulated problem?

**Comment by jaeandersson** [comment]
> @jaeandersson do you expect expand to be fast on a well-formulated problem?

No, it will be slow also for a well-formulated problem. Expand should not be used for large graphs.

**Comment by jaeandersson** [comment]
Don't expand it.

**Comment by ghorn** [comment]
It works 20x faster if I expand it

**Comment by jaeandersson** [comment]
It shouldn't be the case. Something is wrong.

**Comment by adbuerger** [comment]
Is there a reason not to further pursue the parallelization of the jacobian/hessian generation? I experience the same behavior as @ghorn and I think it would be really nice if this process could be sped up. When I e. g. set up a least squares parameter estimation for @jgillis silverbox example with 5000 measurements in PECas, which also uses direct collocation, the solution takes only about 10 seconds, while I spend minutes on initializing the NlPSolver.

**Comment by jaeandersson** [comment]
> Is there a reason not to further pursue the parallelization of the jacobian/hessian generation? I

What can be parallelized is the sparsity pattern propagation used to calculate the sparsity structure of Jacobians and Hessians. If you can show that this piece is actually the bottleneck, it is something that can be considered. 

@ghorn If I recall correctly, this issue got solved already?

**Comment by jgillis** [comment]
I think you'll find that reformulation with Map initializes a lot fast.

**Comment by jgillis** [comment]
Out of curiosity, did you use the same number of integration steps per control interval as in the example (10)?

**Comment by adbuerger** [comment]
@jgillis i used Lagrange polynomials of order 3. I got your sysid-example running (though without JitFunction for now), and it is tremendously faster! I think from this perspective, I have to think about refactoring my code rather than about prallelization of the existing setup.

**Comment by ghorn** [comment]
Reopening because parallel jacobian with `Map` is slower than naive for loops in my case. I will follow up

**Comment by ghorn** [comment]
This issue has diverged a bit. I no longer think it's necessary as `map` is performing well for me, and `init` is very fast.
