### ISSUE TITLE
Switches - "Conditional" MX atomic

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1413]
A useful atomic operation would be a switch. Suggested syntax would be:
```python
res = conditional(ind, arg, [f0, f1, f2], f_otherwise=Function())
```
which would codegen to something like:
```c
...
  w0 = ... /* index */
  {
    const real_t* arg1[] = {w+10, w+30, w+40};
    real_t* res1[] = {w+100, w+200};
    switch (int(w0)) {
    case 0: i=f0(arg1, res1, iw, w); break;
    case 1: i=f1(arg1, res1, iw, w); break;
    case 2: i=f2(arg1, res1, iw, w); break;
    default: i=f_otherwise(arg1, res1, iw, w); 
    }
    if (i) return i;
  }
```
If a function is a null pointer (the default for f_otherwise), it will amount to an error (`return 1;`). If there is only one function in addition to the "default" case, it would be codegen'd as an if-then-else:
```c
...
  w0 = ... /* index */
  {
    const real_t* arg1[] = {w+10, w+30, w+40};
    real_t* res1[] = {w+100, w+200};
    if (int(w0)) {
      i=f0(arg1, res1, iw, w);
    } else {
      i=f_otherwise(arg1, res1, iw, w); 
    }
    if (i) return i;
  }
```
This is mostly for readability, since the compiler will with very high probability perform this optimization automatically). To create a switch like this, there would be a shorthand-syntax:
```python
res = if_then_else(cond, arg, if_true, if_false)
```
which would be equivalent to (booleans are treated as 0 or 1 in CasADi):
```python
res = conditional(cond, arg, [if_false], if_true)
```
That is, the "Conditional" MX node would handle both if-then-else and switches.

It makes sense to have an overload of `if_then_else` without `if_false`:
```python
res = if_then_else(cond, arg, if_true)
```
in which case `if_false` is assumed to be a function with the same inputs as `if_true` but returning zeros (of the correct dimensions).

Note that this could be used to implement very generic lookup tables (more generic than e.g. #728).

**Comment by jaeandersson** [comment]
As a starting point, I think it makes sense to evaluate one out of a set of functions. These functions could potentially be inlined at a later step, cf. #1411.

This is pseudocode:
```c
real_t arg = ...     /* function input - same for all branches */
real_t res;           /* function output - same for all branches */
if ( c0(arg)) {
  res = f0(arg);
} else if (c1(arg)) {
  res = f1(arg);
} else if (c2(arg)) {
  res = f2(arg);
} else {
  res = f3(arg);
}
```
Possible syntax would be e.g.
```python
x = MX.conditional(c0, f0,
                               c1, f2,
                               c2, f2,
                               f3, arg)
```

**Comment by jaeandersson** [comment]
The arg could potentially be generated using `getSymbols`. Which would allow working with only expressions:
```python
z = MX.conditional(x<0, sqrt(-x),
                   x<1, exp(x),
                   sin(x))
```

**Comment by jaeandersson** [comment]
@ghorn @jgillis - your thoughts?

**Comment by jaeandersson** [comment]
```python
x = MX.conditional(c, f0, f1, f2, f3, arg)
```
where `c` is a vector of length `len([f0, f1, f2, f3])-1`. Example:
```python
t = MX.sym('t')
t_intervals = MX([0,2,4])
x = MX.conditional(t<t_intervals, sin(x), cos(x), sqrt(x), exp(x))
```

It would be codegen'd to something like:
```c
...
real_t* c = ... /* vector of conditions */
if ( *c++ != 0 ) {
  z2 = sin(z1);
} else if (*c++ != 0) {
  z2 = cos(z1);
} else if (*c++ != 0) {
  z2 = sqrt(z1);
} else {
  z2 = exp(z1);
}
...
```

**Comment by jaeandersson** [comment]
I am leaning towards something that translates to a switch.

**Comment by jaeandersson** [comment]
@jgillis @ghorn I updated the issue description to reflect my "final" proposal for supporting switches. Any objections? Are you ok with the syntax:
```python
res = conditional(ind, arg, [f0, f1, f2], f_otherwise=Function())
res = if_then_else(cond, arg, if_true, if_false)
```
?

**Comment by jgillis** [comment]
How should one create interpolation tables with this? By adding in a 'round' on top?

**Comment by jaeandersson** [comment]
You would have to create an MXFunction for each segment then a switch node to choose between the those functions. For piecewise polynomials there are more efficient ways - so it still makes sense to add a separate MX node to handle those.

**Comment by jaeandersson** [comment]
Example code:
```python
from casadi import *
x = MX.sym('x')
c = MX.sym('c')
my_cos = MXFunction([x],[cos(x)])
my_cos.setOption('name', 'my_cos')
my_cos.init()
my_sin = MXFunction([x],[sin(x)])
my_sin.setOption('name', 'my_sin')
my_sin.init()
my_exp = MXFunction([x],[exp(x)])
my_exp.setOption('name', 'my_exp')
my_exp.init()

# Test if-then-else
[z] = if_then_else(c, [x], my_sin, my_cos)
print z
test_if = MXFunction([x, c],[z])
test_if.setOption('name', 'test_if')
test_if.init()
test_if.generate("test_if")

# Test switch
[z] = conditional(c, [x], [my_sin, my_cos], my_exp)
print z
test_switch = MXFunction([x, c],[z])
test_switch.setOption('name', 'test_switch')
test_switch.init()
test_switch.generate("test_switch")

print file('test_if.c').read()
print file('test_switch.c').read()
```

**Comment by jaeandersson** [comment]
@jgillis @ghorn Any comments on syntax?

**Comment by jgillis** [comment]
Syntax looks good; but wasn't `if_then_else` taken already?

You didn't address my previous issue though.
If i want e.g. to create a piecewise function (lets say linear for x<=0 and quadratic for x>0), how would I do that?

```
conditional(sign(x)+1, [x], [my_linear, my_quadratic])
```
or for more functions:
```
if_then_else(round(x), [x], [my_linear, my_quadratic, my_something_else])
```

If the definition of conditional where
```
if (c<=0) {

} else if (c>0 && c<=1) {

} else if (c>1 && c<=2) {

}
```
rather than a switch, than it would be easier to set up piecewise things:

```
if_then_else(x, [x], my_linear, my_quadratic, my_something_else)
```

Just speculating here and wondering what the impact would be (performance, concentrating the non-differentiability in one node instead of two)

**Comment by jaeandersson** [comment]
I imagine using it together with the just added Find node (cf. #1416):
```python
t_boundaries = DMatrix([-1.4, 2, 10, 20])
t = MX.sym('x')

f0 = MXFunction(...) # for interval [-1.4, 2]
f1 = MXFunction(...) # for interval [2, 10]
f2 = MXFunction(...) # for interval [10, 20]

# Note: error if outside intervals!
[z] = conditional(find(t>=t_boundaries), [x], [f0, f1, f2])
```




```

**Comment by jaeandersson** [comment]
The "find" could be implicit (invoked if first argument is a non-scalar):
```python
[z] = conditional(t>=t_boundaries, [x], [f0, f1, f2])
```

**Comment by jgillis** [comment]
That makes sense..

**Comment by jaeandersson** [comment]
> That makes sense..

What? The find node or having it invoked implicitly?

**Comment by jgillis** [comment]
The former. Implicit is not very intuitive. A piecewise function that creates the find-conditional would make more sense.

**Comment by jaeandersson** [comment]
I did another iteration on this. Instead of an MX node, the Conditional class is now a Function. Syntax:
```python
from casadi import *
x = MX.sym('x')
my_cos = MXFunction([x],[cos(x)])
my_cos.setOption('name', 'my_cos')
my_cos.init()
my_sin = MXFunction([x],[sin(x)])
my_sin.setOption('name', 'my_sin')
my_sin.init()
my_exp = MXFunction([x],[exp(x)])
my_exp.setOption('name', 'my_exp')
my_exp.init()

# Create if-else
sw = Switch(my_sin, my_cos)
sw.init()
sw.generate('test_if')

# Create switch
sw = Switch([my_sin, my_cos], my_exp)
sw.init()
sw.generate('test_switch')

print file('test_if.c').read()
print file('test_switch.c').read()
```
There is now also a short-hand, where the functions are created implicitly:
```python
from casadi import *
c = MX.sym('c')
x = MX.sym('x')
z1 = if_else(c, sin(x), cos(x))
z2 = conditional(c, [sin(x), cos(x)], exp(x))

# Test if-else
print z1
test_if = MXFunction([x, c],[z1])
test_if.setOption('name', 'test_if')
test_if.init()
test_if.generate("test_if")

# Test switch
print z2
test_switch = MXFunction([x, c],[z2])
test_switch.setOption('name', 'test_switch')
test_switch.init()
test_switch.generate("test_switch")

print file('test_if.c').read()
print file('test_switch.c').read()
```

**Comment by jaeandersson** [comment]
Feature implemented. Currently does not handle the case when the different cases have different sparsity, but will treat that in a separate issue: #1571.
