### ISSUE TITLE
[MX] -> MXVector type conversion not working

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1415]
The following fails without an explicit typecast from Python list to `vector<MX>`:
```python
from casadi import *
x = MX.sym('x')
c = MX.sym('c')
f1 = MXFunction([x],[cos(x)])
f1.setOption('name', 'f1')
f1.init()
f2 = MXFunction([x],[sin(x)])
f2.setOption('name', 'f2')
f2.init()

[z] = if_then_else(c, [x], f1, f2)  # fails
#[z] = if_then_else(c, MXVector([x]), f1, f2) # works
print z
```

**Comment by jaeandersson** [comment]
@jgillis - any idea?

**Comment by jaeandersson** [comment]
Same also true for `vector<Function>`:
```python
from casadi import *
x = MX.sym('x')
c = MX.sym('c')
f1 = MXFunction([x],[cos(x)])
f1.setOption('name', 'f1')
f1.init()
f2 = MXFunction([x],[sin(x)])
f2.setOption('name', 'f2')
f2.init()
[z] = conditional(c, MXVector([x]), [f2], f1) # fails
[z] = conditional(c, MXVector([x]), FunctionVector([f2]), f1) # works
```

**Comment by jgillis** [comment]
This is absurd. Is it a const-ref argument?

**Comment by jaeandersson** [comment]
Sorry, I think it's a false positive... Forgot to mark as constant...

**Comment by jaeandersson** [comment]
Right, false positive. The FunctionVector thing is a genuine bug though. It can probably be explained by the fact that `mx_tools.hpp` comes before the instantiation of `vector<Function>`.

**Comment by jaeandersson** [comment]
Fixed the the `[Function] --> FunctionVector` typemap by reordering the includes in `casadi.i`. There is one remaining issue though:
```
from casadi import *
x = MX.sym('x')
c = MX.sym('c')
f1 = MXFunction([x],[cos(x)])
f1.setOption('name', 'f1')
f1.init()
f2 = MXFunction([x],[sin(x)])
f2.setOption('name', 'f2')
f2.init()
[z] = conditional(c, [x], [f2], f1) # works
[z] = c.conditional([x],[f2], f1) # fails
```
The second version should not really be used in Python (and probably should be hidden from the API), but it will be used in MATLAB. Unfortunately, this can't be fixed by reordering the statements in `casadi.i`, since `Function` has methods involving `vector<MX>`.

**Comment by jaeandersson** [comment]
(will push my fix later, git push doesn't work from where I am at the moment)
