### ISSUE TITLE
Improve efficiency in vertcat

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1426]
With the code below, `vertcat` is shown to possess a `O(N^2)` complexity. Same for `horzcat`.
The cause is that `Sparsity::appendColumns` is called N times, which in term entails a full copy of the sparsity pattern.

```
from casadi import *

import time

for n in [1000,2000,4000,8000]:
  x = [ casadi.SX.sym("x",2,1) for i in range(n) ] 

  t0 = time.time()
  vertcat(x)
  print time.time()-t0
```

**Comment by jgillis** [comment]
This is a regression from 2.2.0 . With the new way to represent the sparsity pattern internally, copying becomes somewhat unavoidable.

**Comment by jgillis** [comment]
Have a fix ready based on a

```
Sparsity SparsityInternal::zz_appendColumns(const std::vector< const SparsityInternal* > &sps) const;
```

which lives next to the old

```
Sparsity SparsityInternal::zz_appendColumns(const SparsityInternal &sp) const;
```

**Comment by jgillis** [comment]
Waiting for the develop branch to magically auto-repair first

**Comment by jaeandersson** [comment]
I don't understand your proposed fix. The solution is not in changing `SparsityInternal::zz_appendColumns`. There is already a `Sparsity::zz_vertcat` which has the correct complexity. What is needed is to update `Matrix<DataType>::zz_vertcat` to use `Sparsity::zz_vertcat` and not fall back on `Matrix<DataType>::appendColumns`.

**Comment by jgillis** [comment]
Oh okay, I forgot about the existance of `Sparsity::zz_vertcat`..

**Comment by jaeandersson** [comment]
Fix incoming

**Comment by jgillis** [comment]
So something like:

```c++
  template<typename DataType>
  Matrix<DataType> Matrix<DataType>::zz_horzcat(const std::vector<Matrix<DataType> > &v) {
    // Vector of sparsities
    std::vector< Sparsity > sp;

    // Non-zero vector
    std::vector<DataType> d;

    for (int i=0; i<v.size(); ++i) {
      sp.push_back(v[i].sparsity());

      const Matrix<DataType>& y = v[i];

      // Add the non-zeros at the end
      d.insert(d.end(), y.begin(), y.end());
    }

    return Matrix<DataType>(horzcat(sp), d);
  }
```

**Comment by jaeandersson** [comment]
Yes, more or less. This is what I have implemented:
```c++
    // Concatenate sparsity patterns
    std::vector<Sparsity> sp(v.size());
    for (int i=0; i<v.size(); ++i) sp[i] = v[i].sparsity();
    Matrix<DataType> ret(horzcat(sp));

    // Copy nonzeros
    typename Matrix<DataType>::iterator i=ret.begin();
    for (typename std::vector<Matrix<DataType> >::const_iterator j=v.begin();
         j!=v.end(); ++j) {
      std::copy(j->begin(), j->end(), i);
      i += j->size();
    }
    return ret;
```
It should be a little more efficient since there is no temporary `d` vector created.

**Comment by jaeandersson** [comment]
Fixed. Reopen if problem persists.

**Comment by jgillis** [comment]
Problem persists for MX

**Comment by jaeandersson** [comment]
I don't see how that's possible.

**Comment by jaeandersson** [comment]
Ah, I see now.

**Comment by jgillis** [comment]
It's not that surprising if you look at `Horzcat::Horzcat`...
