### ISSUE TITLE
Remove Function::init()

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1429]
#1350 introduces a more compact syntax for function object creation without having to call init. The followup of this is to remove the init-step completely, and move the logic into the constructor.

**Comment by jaeandersson** [comment]
To make using the new syntax easier and less verbose, I'd like to make two minor changes:
 - Rename Dictionary-->Dict
 - Add make_dict helper function in c++ with syntax `make_dict(

**Comment by mvukov** [comment]
> Rename Dictionary-->Dict

How about to start using an editor with auto-completion? :smile:

**Comment by jaeandersson** [comment]
> How about to start using an editor with auto-completion?

Hehe, a compact syntax is really nice when you're making a tutorial. And it's called dict, not dictionary in Python...

**Comment by jaeandersson** [comment]
This issue is pretty much done as far as 2.4 is concerned. The examples have been all updated and the unit tests have been updated except for (1) convex solvers, (2) NLP solvers and (3) CostumFunction. Need to add a deprecation message for using the old constructors also.

**Comment by jgillis** [comment]
I will handle the remaining issues..

**Comment by jaeandersson** [comment]
This should be completed now. Init has also been hidden from SWIG. "init" continues to live in the internal API as part of a three step initialisation triggered by the public constructor (or other constructor function):
 1. The internal constructor is called, allocating data members (some of them passed by the constructors) for the whole class class hierarchy. This step should not throw any errors.
 2. `FunctionInternal::init` is called for the class hierarchy, starting at the base class and and visiting derived classes until the reaching the completed class.
 3. `FunctionInternal::finalize` is called visiting the classes in reverse order, i.e. starting at the completed class.
