### ISSUE TITLE
Remove HomotopyNLPSolver

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1430]
From what I can tell, HomotopyNLPSolver is not used for anything, which is not surprising, since it doesn't even have an exposed constructor.

I think the functionality of solving sequences of similar NLPs is important, but I don't believe that having a dedicated class deriving from Function is the correct way forward.

@jgillis?

**Comment by jgillis** [comment]
duplicate of #881 . It was only ever experimental.
