### ISSUE TITLE
Replace IOScheme with vector of strings

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1431]
IOScheme has a lot of instantiations, one of them being CustomIO, which constructs an IOScheme from `std::vector<std::string>`. I don't see why CustomIO cannot be used for all schemes instead of all template instantiations. When only CustomIO is left, it should be possible to replace with `std::vector<std::string>`, meaning smaller API and less concepts to learn. IOSchemeVector can be replaced by `std::vector<std::pair<std::string, MatrixType> >`

**Comment by jaeandersson** [comment]
I also don't think the "descriptions" field in IOScheme is needed. That information can be kept somewhere else.

**Comment by jaeandersson** [comment]
Or, I'll backtrack on the descriptions part. I'd suggest using syntax "entry_name:description" for the strings. I.e. the same string can handle both the handle (before the colon ":", if it exists) and the description (after the colon).

**Comment by jaeandersson** [comment]
Blocked by #1351.

**Comment by jaeandersson** [comment]
@jgillis - would you mind finishing this issue? Only some work on the convex solvers remains. And since you were going to have a look at that anyway...

**Comment by jgillis** [comment]
I'll start now

**Comment by ghorn** [comment]
thank you

**Comment by jaeandersson** [comment]
IOScheme and IOSchemeVector classes gone.
