### ISSUE TITLE
Refactor typemaps

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1434]
The typemaps are still not really maintainable. There is way too much reinventing things that should be available in SWIG already. I am not sure, but maybe the correct way forward is to adopt the traits classes that exist in SWIG. Although I've never really understood whether these are part of the public SWIG API, since they are not mentioned anywhere in the user guide.

**Comment by jaeandersson** [comment]
Number of lines of code in casadiPYTHON_wrap.cxx now at 117406.

**Comment by jaeandersson** [comment]
Refactoring done. To do: Get it to work with MATLAB and JSON.

**Comment by jaeandersson** [comment]
MATLAB compiles again for me. I get linking errors, but I get that on the master branch as well so I don't think it's related.

**Comment by jaeandersson** [comment]
@ghorn You might want to have a look at JSON now... (ducking)

**Comment by ghorn** [comment]
"closed....(ducking)"

ಠ_ಠ
