### ISSUE TITLE
Use numpy.matrix instead of numpy.array in examples

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1441]
Using numpy data structures is not very intuitive at the moment, especially for new users. I propose to simplify the current usage and use numpy.matrix instead of numpy.array in all example and to use the shorthand: `A.full()` to get a `numpy.matrix` from a CasADi matrix.

For sparse matrices, I would like to use `scipy.sparse.csc_matrix` everywhere and use the syntax `A.sparse()` in order to get a `scipy.sparse.csc_matrix` from a CasADi matrix.

Note that this would match the MATLAB naming for getting dense and sparse MATLAB matrices from CasADi matrices, cf. #1300.

**Comment by ghorn** [comment]
I think that python users prefer array to matrix.

**Comment by jaeandersson** [comment]
DMatrix is used to represent scalars, vectors and matrices. That means if you want to use numpy.array, you'd like to get a scalar or zero-dimensional array, a one dimensional array or a two dimensional array depending on situation. Using numpy.matrix is much easier, because it's used for all of that.

For me this is a pragmatic issue: We have seen how new users struggle with numpy.array objects of one and two dimensions. Because of this mess, we have mostly chosen not to use numpy at all in many exercise sessions. Anyway, this won't result in CasADi becoming any less usable with numpy.array, it's only about making it easier to work with numpy.matrix and scipy.sparse.csc_matrix and decide to use them in examples, to make learning curve less steep.

**Comment by Pedro-Roque** [comment]
@jaeandersson it seems that numpy might discontinue numpy.matrix, https://numpy.org/doc/stable/reference/generated/numpy.matrix.html . What should we use, then? So far I have been using them and it seems to be mostly fine, but perhaps an alternative is needed in the close future

**Comment by jaeandersson** [comment]
> @jaeandersson it seems that numpy might discontinue numpy.matrix, https://numpy.org/doc/stable/reference/generated/numpy.matrix.html . What should we use, then? So far I have been using them and it seems to be mostly fine, but perhaps an alternative is needed in the close future

Right, this is not really a realistic change anymore, if it ever were. I'll close the issue.
