### ISSUE TITLE
Improved error handling, construct stack trace

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1442]
We have to structure our code better so that the user _always_ get a readable stack trace on errors, without involving some external debugger. This should also allow us to remove the "CATCH_OR_NOT" macro in SWIG.

As I see it, the best approach would be to wrap the implementation of all _public_ classes in try-catch blocks. This would mean much less work and be cleaner than trying to do something in the internal classes.

I suggest to catch all errors inheriting from `std::exception` (this includes all CasADi errors and errors and errors in the C++ standard library), append information about the called public function as well as name (for member functions in `casadi::Function`), and then rethrow.

**Comment by jaeandersson** [comment]
It should be possible to do this by a defining a simple macro and use this in strategic locations, something along the lines of.
```c++
// Macro for error handling
#define TRACE(fcn, ...) \
try { \
  fcn(__VA_ARGS__);\
} catch (exception& e) {\
  throw casadi::CasadiException(std::string("When calling \"" \
        CASADI_ASSERT_STR(fcn) "\"" CASADI_ASSERT_WHERE ", caught: \n")+ex.what()); \
}
```

**Comment by jgillis** [comment]
There something peculiar about relying on our disciplined coding to have stacktraces.
Bugs may appear, by definition, in unexpected places.

What about some compiler-specific things? https://www.gnu.org/software/libc/manual/html_node/Backtraces.html

**Comment by jaeandersson** [comment]
@jgillis @ghorn Have a look at d012551. Errors in `Function` should now result in more readable error messages:
```python
from casadi import *
x = SX.sym('x')
f = nlpsol('f', 'ipopt', {'f': x, 'x':x})
f.name_in(100)
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-3467ae82b0c9> in <module>()
----> 1 f.name_in(100)

/Users/jaeandersson/local/python/casadi/casadi.py in name_in(self, *args)
   7459
   7460         """
-> 7461         return _casadi.Function_name_in(self, *args)
   7462
   7463

RuntimeError: Error in Function::name_in for 'f' [IpoptInterface] at .../casadi/core/function.cpp:721:
vector
```

**Comment by ghorn** [comment]
nice

**Comment by jaeandersson** [comment]
I'll close the issue here since the design is in place and mostly implemented, at least for `Function`. Continued improvements, with more try-catch clauses in strategic locations, can be done when the need arises.
