### ISSUE TITLE
Syntax ambiguity for hessian

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1446]
The syntax for getting the Hessian is currently weird, e.g.
````c++

  inline MX hessian(const MX& ex, const MX& arg) { ...}
  inline void hessian(const MX& ex, const MX& arg, MX& H, MX& g) { ...}
```
This won't work in SWIG since H and g are return-by-reference. I'd like to change it to:
````c++
#ifndef SWIG
  inline MX hessian(const MX& ex, const MX& arg) { ...}
#endif // SWIG
  inline MX hessian(const MX& ex, const MX& arg, MX& SWIG_OUTPUT(g)) { ...}
```

This means that the function always has two outputs in SWIG.

**Comment by jgillis** [comment]
'hessian' always giving two outputs in swig? Not very intuitive imho

**Comment by jaeandersson** [comment]
The alternative is to have two different names, e.g. `hessian` and `hessianAndGradient`. Note that the two outputs thing is irrelevant in MATLAB:
```python
H, g = hessian(f, x) # Python
H, _ = hessian(f, x) # Python
```
but
```matlab
[H, g] = hessian(f, x) % MATLAB
H = hessian(f, g)
```

**Comment by jaeandersson** [comment]
@jgillis - what's your proposal? The old syntax could not be kept.

**Comment by jgillis** [comment]
A different name for the hessian+gradient variant perhaps?

**Comment by jaeandersson** [comment]
When you calculate the Hessian you get the gradient for free. I find it prudent to return both. Do we really want to clutter the API with another overload just to throw away a return argument?

@ghorn ?

**Comment by ghorn** [comment]
I think 2 overloads is about as cluttering as 2 functions w different names. And hessionWithGradient is extremely clear. I don't have a strong opinion

**Comment by jaeandersson** [comment]
@ghorn No one is proposing two overloads. The question is whether we should have a shorthand for throwing away the gradient, e.g.:
```python
H = hessian(...)
H, g = hessianWithGradient(...)
```
or
```python
H, g = hessian(...)
H, _ = hessian(...)
```

**Comment by ghorn** [comment]
Oh you're getting rid of 2 overloads. I prefer hessianWithGradient because the name fits. Likewise the name hessian only returns the hessian, which also fits.

**Comment by ghorn** [comment]
But what about hessianWithGradientAndValue

**Comment by ghorn** [comment]
jk

**Comment by jgillis** [comment]
I vote for hessianWithGradient
