### ISSUE TITLE
Implicit function needs better documentation

### ISSUE THREAD

**Issue by mzanon** [casadi/casadi#1449]
It is not super clear how to use it. In particular, it is not obvious that the first input should be an initial guess for the implicit variables. As sometimes it is fundamental to provide an initial guess different from 0, it would be nice to make this clearer.

**Comment by jgillis** [comment]
Note: there is an example for implicit function http://casadi.sourceforge.net/api/internal/de/d0f/solvers_2NewtonImplicitSolver_8py-example.html

**Comment by jgillis** [comment]
Indeed the documentation was not up to date. I provided an update: 6a75464f4794439d02
