### ISSUE TITLE
Output from interfaces should be redirected to std::cout and std::cerr

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1450]
Some solvers, e.g Ipopt prints to C's stdout and stderr instead of C++'s std::cout and std::cerr. This is a problem for the Matlab interface - where the output needs to be redirected to mexPrintf - or if the user wishes to redirect the output to a file. It would be much better if all interfaces makes sure to redirect all outputs to std::cout and std::cerr.

**Comment by jaeandersson** [comment]
I can see some different ways of solving this:
 - Redirecting stdout and stderr to std::cout and std::cerr
 - Recompile all dependencies with macros that replace `printf` and `fprintf` with e.g. `cplusplus_printf` and `cplusplus_fprint`. These functions are in turn just wrappers to printing to std::cout and std::cerr.
 - Override `printf` and `fprintf` and make sure the linker picks our routines over the standard library routines.

**Comment by jaeandersson** [comment]
For GCC there is the possibility to use the compiler flags `-fno-builtin-fprintf` and `-fno-builtin-printf` and then reimplement `printf`and `fprintf`.

**Comment by ghorn** [comment]
> Recompile all dependencies with macros that replace printf and fprintf with e.g. cplusplus_printf and cplusplus_fprint. These functions are in turn just wrappers to printing to std::cout and std::cerr.

The first option seems safest, but I've heard of people using the third option for matlab library problems before

**Comment by jgillis** [comment]
Bare in mind that their might be dependencies that come in the form of compiled libraries (worhp, notably).

**Comment by jgillis** [comment]
Note: http://stackoverflow.com/questions/4810516/c-redirecting-stdout

**Comment by jaeandersson** [comment]
A possibility is to do things the other way around... Redirect std::cout and std::cerr to stdout and stderr and then in turn redirect these two to a file.

Can be done the same way as I used to redirect std::cout and std::cerr to mexPrintf: https://github.com/jaeandersson/swig/commit/16ea06805b18918ea9fb9f6465814629da8f2b60.

**Comment by jaeandersson** [comment]
Forget about that, by default stdout is sent to std:: cout, so it doesn't help.

**Comment by jgillis** [comment]
How do we do the same thing for Python cf. 2604847cf86030c69e6db2f925caffedc29eeb02 ?
write it in `casadi.i` or require your branch of SWIG to compile casadi?

**Comment by ghorn** [comment]
http://zpasternack.blogspot.com/2011/07/adventures-in-redirection-part-deux.html?m=1

**Comment by jaeandersson** [comment]
Works for me now, at least for IPOPT. @jgillis - can you check whether you get output to the MATLAB GUI as expected?
