### ISSUE TITLE
Refactor PyFunction, implement MatlabFunction

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1452]

**Comment by jaeandersson** [comment]
I think the most natural way to implement this in both MATLAB and Python are as classes:
```python
class MyFunction:
  def name(self):
    return ...
  def n_in(self):
    return ...
  def n_out(self):
    return ...
  def input_sparsity(self, index):
     return ...
  def output_sparsity(self, index):
     return ...
  def __call__(self, arg):
     return
```

**Comment by jaeandersson** [comment]
I think it's possible - and makes sense - to write a typemap for a Python object of this form, without actually having any PyFunction class exposed to the user.

**Comment by jaeandersson** [comment]
@jgillis - what do you think?

**Comment by jaeandersson** [comment]
I mean, both Python and MATLAB offers the functionality to write function objects, objects that behave like functions, but with memory and with the ability to define additional methods. In MATLAB, user should probably derive from the `handle` base class and overload `subsref`

**Comment by jaeandersson** [comment]
@jgillis  close?

**Comment by jgillis** [comment]
This is unfinished, since the mechanism to provide derivatives is not stable.
Also, callbacks for NlpSolver is missing

**Comment by jgillis** [comment]
Derivatives and iteration callbacks possible
