### ISSUE TITLE
Verbosity levels

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1453]
There is now an option for verbosity which is basically only on/off. I propose to have an enum with some different levels:
```c++
enum PrintLevels {PL_NONE, PL_WARN, PL_PROG, PL_DEBUG, PL_ALL};
```

and then use this in FunctionInternal as follows:
```c++
if (logging<PL_WARN>()) { // if print level PL_WARN or higher
  userOut<true, PL_WARN>() << "here is my message" << endl;
}
```

I'm thinking what would be a good set of print levels. Here my proposal:
 * `PL_NONE`: No printing at all
 * `PL_WARN`: Only print warnings
 * `PL_PROG`: Print evaluation progress (and everything in PL_WARN), i.e. the iterations of an NLP solver.
 * `PL_DEBUG`: Print error messages useful for debugging (and everything in PL_PROG)
 * `PL_ALL`: Print everything, even if it's very verbose. e.g. numerical values of inputs and outputs during evaluation.

**Comment by ghorn** [comment]
duplicate #1348

**Comment by jaeandersson** [comment]
Modified above proposal somewhat, using templates.

**Comment by jaeandersson** [comment]
Reimplemented the Logger class using templates and printing levels.

The syntax is now:
```c++
userOut() << "here is my message" << endl;
```
`userOut` is templated with the first argument being whether we're printing an error (by default to std::cerr instead of std::cout, but for another destination it could simply be a different color):
```c++
userOut<true, PL_ALL>() << "here is my error message with level PL_DEBUG" << endl;
```

**Comment by jaeandersson** [comment]
Didn't realize that my implementation required C++11:
```
/Users/jaeandersson/local/include/casadi/core/casadi_logger.hpp:151:17: warning: default template arguments for a function template are a
      C++11 extension [-Wc++11-extensions]
  template<bool Err=false, PrintLevel PL=PL_PROG>
```

**Comment by ghorn** [comment]
feature request: verbose init only

**Comment by jaeandersson** [comment]
I didn't bother making this pre-C++11 conformant. It means that CasADi 2.4 is now requires support for C++11. Cf. #893.
