### ISSUE TITLE
Use of an inappropriate integrator does not give you an error message

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1454]
When setting up an cvodes integrator with a DAE instead of an ODE, no error message or similar is presented, but instead "something" is being computed and returned, like e. g.:

    dae = ca.MXFunction( \
        ca.daeIn(x = x, z = z, p = u), \
        ca.daeOut(ode = f, alg = g)
        )
    integrator = ca.Integrator("cvodes", dae)
    integrator.init()

I think it would be useful to throw an error when an inappropriate integrator is used.

**Comment by adbuerger** [comment]
Edited the original post, before the point of my concern was not even shown.

**Comment by jaeandersson** [comment]
Fixed.
