### ISSUE TITLE
Change definition of Matrix(Sparsity) constructor

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1457]
The reasonable definition of `MX(Sparsity)` or `SX(Sparsity)` or `DMatrix(Sparsity)` is `MX::ones(Sparsity)` and `SX::ones(Sparsity)` and `DMatrix::ones(Sparsity)` and not (as now) `MX::zeros(Sparsity)` and `SX::zeros(Sparsity)` and `DMatrix::zeros(Sparsity)`.

Cf. #1456.

**Comment by jaeandersson** [comment]
(the motivation for this is that sparsity pattern should be an optimisation feature. structural or nonstructural zero should give the same result)

**Comment by jgillis** [comment]
Why not remove it from the public api?

**Comment by jaeandersson** [comment]
We should probably remove it from the public API, yes. But we cannot do that before we provide reasonably efficient alternatives for all its functionalities.

**Comment by jaeandersson** [comment]
This should be completed.
