### ISSUE TITLE
Mixing DMatrix and MX in MATLAB

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1463]
Type conversion is not working correctly. When I try `DMatrix(1)+MX(1)` I get an error. For `MX(1)+DMatrix(1)` I get a segfault... It is related to the handling of friend functions. Basically, the current way has major design flaws. What is needed instead are wrappers for the friend functions, but without MATLAB proxy classes. And Matlab member functions that call these friend function wrappers.

**Comment by jgillis** [comment]
The `MX(1)+DMatrix(1)` variant works correctly for me..

**Comment by jaeandersson** [comment]
Should work now. The templated base classes have now been extended to contain by default empty non-templated base classes. In SWIG, these classes are extended to contain all the overloads of the friend functions, wrapped as static functions. This approach is used for SWIG Matlab, but should be used for Python also, since it's cleaner and more efficient.

**Comment by jgillis** [comment]
todo: unittest

**Comment by jaeandersson** [comment]
I'm not sure what can be unit tested here. What is needed is unit testing for MATLAB.

**Comment by jgillis** [comment]
Just add `DMatrix(1)+MX(1)` and `MX(1)+DMatrix(1)` to test.m ;-)
