### ISSUE TITLE
pkg-config missing from release debian

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1469]
If you install http://sourceforge.net/projects/casadi/files/CasADi/2.3.0/linux/libcasadi-v2.3.0.deb, pkg-config cannot find casadi. If you point me to where these files are generated, I can try fixing this.

**Comment by jgillis** [comment]
Here you go: https://github.com/casadi/binaries/blob/debian-standalone/.travis.yml

**Comment by jaeandersson** [comment]
what's the status of debian?

**Comment by ghorn** [comment]
Status is: the path forward is ppa's for ubuntu so that we can push out the latest releases and instantly reach LTS users. Casadi 2.3 should have a working build, but I haven't done the thing which builds the whole matrix of ubuntu's and pushes to the ppa because I don't know how.

**Comment by ghorn** [comment]
also joris has his own debian binary workflow which may or may not work with ppa's

**Comment by jaeandersson** [comment]
Reopen if needed.
