### ISSUE TITLE
Default names of dictionary fields for map evaluation

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1470]
If evaluation is done using the dictionary-in, dictionary-out style, and if no input or output scheme has been provided, the names will default to "0", "1", "2", etc. This won't work for MATLAB, so a prefix is needed, e.g. "i0", "i1", "i2".

**Comment by jaeandersson** [comment]
Default input scheme is now "a0", "a1", "a2" etc. Default output scheme is "r0", "r1", etc.

**Comment by ghorn** [comment]
what does "a" and "r" stand for?

**Comment by jaeandersson** [comment]
"function argument", "result of evaluation". But there is no deep thinking. I was thinking of "i0", "i1", "i2" and "o0", "o1", "o2" for input and output, but "o" is too similar to "0". Another option would be "r" and "l" for right-hand-side and left-hand-side, but "l" looks like "1" in many fonts... Do you have another proposal?

**Comment by ghorn** [comment]
There is such a thing as both input and output arguments

**Comment by ghorn** [comment]
I think `i` and `o` are clear enough
