### ISSUE TITLE
Constructors for NlpSolver and Integrator taking dictionaries instead of functions

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1471]
It would be useful to allow the user to pass a dictionary of expressions to the constructors of NlpSolver and Integrator. E.g.
```python
x = SX.sym("x")
f = x**2
g = x+3
solver = NlpSolver("solver", "ipopt", {"x":x, "f":f, "g":g})
```
as a shorthand for
```python
x = SX.sym("x")
f = x**2
g = x+3
nlp = SXFunction('nlp', nlpIn(x=x), nlpOut(f=f, g=g))
solver = NlpSolver("solver", "ipopt", nlp)
```

**Comment by mvukov** [comment]
Even simpler:
```
solver = NlpSolver({"solver":"ipopt", "x":x, "f":f, "g":g})
```
? :smile:

**Comment by jaeandersson** [comment]
@mvukov No, that's not an option. `{"x":x, "f":f, "g":g}` maps to to `std::map<std::string, casadi::SX>` or  `std::map<std::string, casadi::MX>`, so you don't want to mix in strings in the type.

Also, we want to enforce naming all function objects so the first arguments should not be left out. Note that there is an optional 4th argument also, a dictionary with options:
```python
x = SX.sym("x")
f = x**2
g = x+3
solver = NlpSolver("solver", "ipopt", {"x":x, "f":f, "g":g}, {"hessian_approximation":"limited_memory"})
```

**Comment by mvukov** [comment]
Oh, sorry, I misunderstood the first two arguments...
