### ISSUE TITLE
Wrong "zf" output for when using collocation-integrator for a DAE

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1472]
When using `Integrator.getOutput("zf")` on an `Integrator`-object initialized as a `collocation`-integrator for a DAE, the returned values do not correspond to the solutions of the algebraic states. In my case, they show a configuration that is not an applicable solution.

When doing the same for an `idas`-integrator, the values returned do show solutions for the algebraic variables that make sense. But for both integrators, the values returned for the differential states match, so both are possibly solving the problem correctly, but `collocation` simply hands back some data different from the solutions of the algebraic variables?

**Comment by ghorn** [comment]
short answer: either
1. consider zf internal
2. use radau collocation points
3. accept slightly inconsistent zf
4. solve for zf yourself using xf

**Comment by jaeandersson** [comment]
Looks like a bug in the collocation integrator. It's still a pretty crudely implemented class, I hope to be able to refactor it in the coming months.

**Comment by jaeandersson** [comment]
At a quick glance at the corresponding code, I think I might have found something that could explain the behaviour. @adbuerger - can you check if my commit (8e91207f495e158979260e2fe48b34d505eeb067) fixed it? You should be able to cherry-pick it to whatever branch you're working on.

**Comment by adbuerger** [comment]
I haven't yet installed CasADi from source but via the Debian-packages you provide, but I will install from source (wanted to do this either way) and tell you if it still occurs

**Comment by jaeandersson** [comment]
You can also just wait for the next Debian package to be generated, probably tonight.

**Comment by ghorn** [comment]
Despite the bug, I believe my answer is valid. @jaeandersson can you comment?

**Comment by jaeandersson** [comment]
I think @adbuerger is getting rubbish returns because he tried to use a feature that hadn't been implemented. Arguably, the integrators should return either:
 - the "correct" `z(tf)` obtained from using Radau points or solving an additional system of equations
 - an extrapolation of the algebraic variables at the collocation points.

But from what I could tell, the code returned neither.

**Comment by jaeandersson** [comment]
Fwiw, the fix I provided should return `z` at the last collocation point.

**Comment by ghorn** [comment]
I think returning the last `z` is a mistake. You should interpolate the same as `x`, then it will be exact for Radau and close for Legendre. Returning the last point for Legendre is not even close.

**Comment by ghorn** [comment]
I would rather you throw an error for Legendre

**Comment by jaeandersson** [comment]
You can't interpolate the same way as for x, since you have a point less (beginning of interval). So you need a polynomial of one order lower. Throwing error not possible, but one can return NaNs.

**Comment by jgillis** [comment]
@jaeandersson was this fixed?

**Comment by jaeandersson** [comment]
> @jaeandersson was this fixed?

This must have gotten fix as a byproduct of the latest integrator refactoring. The output times are now a subset of all the integrator steps, so no interpolation should be needed.
