### ISSUE TITLE
Unlock qpOASES options

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1474]
For some reason, I think due to incompatibility with previous versions, the "qpOASES" interface ignores most options by default. The options can be unlocked by defining the "cheat" `ALLOW_ALL_OPTIONS`.

I don't understand why this isn't the default behaviour.

**Comment by jaeandersson** [comment]
I'll just commit a fix and see what happens... If it breaks stuff, I'll revert back...

**Comment by jgillis** [comment]
Consider using a branch ;-)

**Comment by jaeandersson** [comment]
What is a branch?
