### ISSUE TITLE
Segfaults in windows binaries when combined with visual studio modules

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1477]
The swig runtime allows multiple swigpython modules to peacefully coexist.
This is achieved by adding a namespace (SWIG_TYPE_TABLE) to the swig type table.

In fact, there is still space for collision since all modules register the "SwigPyObject" type.
This is harmless in the case that the different modules use binary compatible C runtimes.

For the windows binaries, this may be a problem. The casadi interface is compiled with `i686-w64-mingw32-g++`, while a typical python install may be based on Visual Studio.
When one compiles an additional swig module using visual studio, the "SwigPyObject" type of one module seems to break the type of casadi, resulting in a segfault.

To reproduce: compile the following module in visual studio:

helloworld.cpp

```
#include <iostream>

std::string greeting() {
  return "Hello world";
}
```
helloworld.h
```
#include <iostream>

std::string greeting();
```
helloworld.i
```
%module helloworld

%include "std_vector.i"
%include "std_string.i"
 
namespace std {
%template(DoubleVector) vector<double>;
%template(IntVector) vector<int>;
%template(StringVector) vector<string>;
%template(DoubleMatrix) vector<vector<double>>;
}

%include "helloworld.h"
%{
#include "helloworld.h"
%}

#include <iostream>
```

python -c "import helloworld;import casadi;print helloworld.greeting();print helloworld.DoubleVector();print casadi.SX.sym('x')"

A naive fix of replacing '"SwigPyObject"' (including the double quotes) with '"MySwigPyObject"' seems to avoid the segfault.
I'm not exactly sure how it manages to work. Since there are potential msvc incompatibilities as well:
Python is compiled using `msvcr90.dll`, helloworld is compiled using `mscvr110.dll` and libgcc links to `msvcrt.dll`. Having read up on some forum posts during debugging (e.g. https://bugs.python.org/issue4709 ), this constellation is asking for trouble.

While this is really a swig issue rather than a casadi issue, it is not nice to expose users to segfaults.
I propose therefore to rename to CasadSwigPyObject for the casadi binaries.

**Comment by jgillis** [comment]
@toivoh any comments?

**Comment by toivoh** [comment]
I don't have any experience with this sort of problems, but it does sound troubling. If renaming to `CasadSwigPyObject` solves the problem then go for it.

**Comment by jgillis** [comment]
Closing since the renaming fixed it.
