### ISSUE TITLE
Refactor derForward, derReverse

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1478]
When implementing #1336, some things ended up being unsatisfactory:
- derForward, derReverse function signatures depends on the number of directions. This is unnecessary - better is to use horzcat.
- The naming scheme for inputs and outputs is unsatisfactory for undifferentiated inputs and outputs.

**Comment by jgillis** [comment]
:+1:

**Comment by jaeandersson** [comment]
@jgillis I'll try to get this included in 3.1.

**Comment by jaeandersson** [comment]
Finished, spun #1893
