### ISSUE TITLE
Matlab: size() gives wrong answer

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1482]

**Comment by jaeandersson** [comment]
Sounds like a typemap issue. `size(A)` in MATLAB calls `Matrix::shape()`, so probably a bug in the output typemap for `std::pair<int, int>`.

**Comment by jaeandersson** [comment]
Correction: it returns "nnz", meaning that the renaming does not work.

**Comment by jaeandersson** [comment]
Aah, it's an artefact of "size()" not being properly deprecated and brought back...

**Comment by jgillis** [comment]
todo: unittest
