### ISSUE TITLE
Matlab: better warnings for "No matching function for overload"

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1483]

**Comment by jgillis** [comment]
Related:  #1461

**Comment by jaeandersson** [comment]
The implemented solution is too hacky and will not work after https://github.com/jaeandersson/swig/issues/58. For example, we cannot introduce our own SWIG error IDs (here `SWIG:OverloadError`). And anyway, it makes no sense to have this error message constructed at runtime.

I see no reason why this cannot be implemented in `MATLAB::dispatchFunction` which now reads:
```c++
  Printf(f->code, "SWIG_Error(SWIG_RuntimeError, \"No matching function for overload function '%s'.\"\n", iname);
  Printf(f->code, "   \"  Possible C/C++ prototypes are:\\n\"%s);\n",protoTypes);
  Printf(f->code, "return 1;\n");
```
This means that a list of regex changes has to be provided in `casadi.i`.

**Comment by jaeandersson** [comment]
A somewhat hacky solution (but not as hacky as the one earlier) would be allowing a C++ function to be run in the error message script. Or by allowing the user to supply his own error handler, replacing the following line:
```c++
  case 1203: flag=_wrap_XmlFile_loadPlugin(resc,resv,argc,(mxArray**)(argv)); break;
  case 1204: flag=_wrap_XmlFile_doc(resc,resv,argc,(mxArray**)(argv)); break;
  case 1205: flag=_wrap_new_XmlFile(resc,resv,argc,(mxArray**)(argv)); break;
  default: flag=1; SWIG_Error(SWIG_RuntimeError, "No function id %d.", fcn_id);
  }
  if (flag) {
    mexErrMsgIdAndTxt(SWIG_ErrorType(SWIG_lasterror_code), SWIG_lasterror_msg);
  }
}
```

That would allow us to customize all error messages, removing references to SWIG and maybe a pointer to where to find API information.

**Comment by jaeandersson** [comment]
Close?

**Comment by jgillis** [comment]
Solved afaict
