### ISSUE TITLE
Rename mul(M,M,M)

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1488]
Cf. #1465, the three-argument variant of mul is easily confused with `mul([M,M,M])`. I propose renaming the variant to avoid confusion.

**Comment by jaeandersson** [comment]
A possible alternative name is "mac" for multiply–accumulate: https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation

**Comment by jgillis** [comment]
Let's wait for #1301

**Comment by jaeandersson** [comment]
New name is "mac". Cf. also https://github.com/casadi/casadi/issues/1499.

**Comment by jaeandersson** [comment]
Note that Python 3.5 has a matrix multiplication operator:
```
A @ B
```
http://legacy.python.org/dev/peps/pep-0465/
