### ISSUE TITLE
Toward a proper interrupt handler

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1498]
http://linuxtoosx.blogspot.com/2010/10/ctrl-c-signal-catching-from-c-program.html

**Comment by jgillis** [comment]
It seems an interrupt handler cannot do much. Killing the process is harsh. Throwing an exception is harsh. Setting a global flag and repeatedly checking seems to be the standard practice. e.g. http://scip.zib.de/doc/html_devel/interrupt_8c_source.php

**Comment by jgillis** [comment]
Set-flag-and-poll means that we can only interrupt inside casadi routines, not inside third-party code.
We probably cover most common usage if we poll in the MXFunction/SXFunction virtual machine loop.

**Comment by jaeandersson** [comment]
Why not check for an interrupt signal e.g. at every NLP iteration?

**Comment by jaeandersson** [comment]
I don't like the idea of crashing out of a program.

**Comment by jgillis** [comment]
http://www.caam.rice.edu/~wy1/links/mex_ctrl_c_trick/

**Comment by jgillis** [comment]
Essentialy a duplicate of #462
