### ISSUE TITLE
Recover documentation for friends

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1500]
Judging from https://github.com/casadi/casadi/compare/3b3b1b5a7bac...59a40b26cd00 , some things might have gone missing.

**Comment by jaeandersson** [comment]
Ah, do the functions have to belong to some group?

**Comment by jgillis** [comment]
Grouping is a bonus-feature to put them on the 'expressions' tab of the api docs.
The docstrings should be there regardless of grouping.

**Comment by jaeandersson** [comment]
Reopen if needed.
