### ISSUE TITLE
Problem wrapping overloaded friends with all-vector inputs

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1502]
e.g. substitute

**Comment by jaeandersson** [comment]
Options:
 - 1. Change syntax: e.g. to `[a, b, c] = substitute({x, y}, {x_def, y_def}, a, b, c);`
 - 2. Global function: `ex = substitute({x, y}, {x_def, y_def}, {a, b, c});` potentially conflicts with other MATLAB packages
 - 3. Global function with casadi prefix:  `ex = casadi_substitute({x, y}, {x_def, y_def}, {a, b, c});`
 - 4. Place in a separate MATLAB `+package`:
 - 5. Global function with casadi prefix:  `ex = casadi.misc.substitute({x, y}, {x_def, y_def}, {a, b, c});` Prefix can be dropped by the user using `import casadi.misc.*`.

**Comment by jaeandersson** [comment]
Solution is:
> 2. Global function: ex = substitute({x, y}, {x_def, y_def}, {a, b, c}); potentially conflicts with other MATLAB packages

It's in the `+casadi` package, so if a user is afraid of name conflicts, he should do `import casadi.*` to begin with.
