### ISSUE TITLE
shorthand indexing shape

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1508]
```
u=zeros(4,1);size(u(1:2))        %  2  1
u=SX.sym('u',4,1);size(u(1:2)) % 1 2
```

**Comment by jaeandersson** [comment]
So, you're indexing a 4-by-1 column vector with a 1-by-2 row vector...

**Comment by jgillis** [comment]
This is unacceptable behaviour that needs changing, right @jaeandersson ?

**Comment by jaeandersson** [comment]
I think we should try to change to the MATLAB behaviour so this is probably a legitimate issue.

**Comment by jaeandersson** [comment]
Are you sure this is the logic MATLAB uses? Looks very complicated to me. With xor? Also, I don't think this should be in `casadi.i`, it'd be placed with all the other logic in `matrix_impl.hpp` and `mx.cpp`.

**Comment by jaeandersson** [comment]
This is also inefficient. It results in temporary matrix created at every call, not only when needed (via recursive call).

**Comment by jaeandersson** [comment]
Reopened. This is not a MATLAB-specific issue. Also, the current fix crashes MATLAB for me.

**Comment by jaeandersson** [comment]
Example in Python:
```python
A = DMatrix([[10,20,30,40]])
print A.shape # (1,4)
print A[0:4].shape # (4,1)
A = numpy.matrix([[10,20,30,40]])
print A.shape # (1,4)
print A[0:4].shape # (1,4)
```
