### ISSUE TITLE
black-box function in constraints

### ISSUE THREAD

**Issue by samiit** [casadi/casadi#1509]
Is it possible to specify the constraints in CasADi for an IPOPT implementation, where the constraint has a black-box function (property fetcher, whose code may not be known to me), apart from other known functions.

Sam

**Comment by jgillis** [comment]
Yes, there is such funcionality: http://casadi.sourceforge.net/api/html/da/d35/Function_2customfunction_8py-example.html

**Comment by jaeandersson** [comment]
Using this is hardly recommendable. IPOPT needs derivatives and specify derivatives for black-box functions is nontrivial. This is something we are working on improving though.

**Comment by samiit** [comment]
Thanks. Is there an example with ipopt where this is implemented?

**Comment by jaeandersson** [comment]
casadi::CustomFunction is just another function deriving from the casadi::Function base class. It can be embedded into expressions the same way as SXFunction, MXFunction, Integrator etc.
