### ISSUE TITLE
Function calling without memory allocation in Python

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1511]
`Function` has the following overload for memory-less evaluation:

``` c++
    void operator()(const double** arg, double** res, int* iw, double* w);
```

This could actually be exposed to Python allowing the user to pass two lists instead of one. The first argument would be the list of inputs , which could be typemapped into `const double**` if stored in a column-major format. The second argument would be a list of output, which could be typemapped into `double**`.

The two work vectors could also be wrapped up in some data structure:

``` python
...
f = MXFunction('f', [...], [...])
...
f([arg0, arg1, arg2], [res0, res1, res2], intwork, realwork)
...
```

**Comment by jgillis** [comment]
:+1: for restoration of sanity

**Comment by jgillis** [comment]
This is implemented https://github.com/casadi/casadi/commit/3e9919e9195e8f057d09cd9bcc4f7fa59e6fc104#diff-ad1e1bf2c8d8bef2a0f3b3b85331ffd0R2491
