### ISSUE TITLE
Map std::vector<std::string>  to char matrix with multiple rows in MATLAB

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1512]
Currently mapped to cell array, but this is not suitable to have in a struct due to how MATLAB handles structs of cell arrays. Nor is the output readable in the prompt.

**Comment by ghorn** [comment]
so the matrix width would be the same as the length of the longest string? And you fill in the gaps with `\n`? Another alternative would be sparse matrices

**Comment by jaeandersson** [comment]
This is MATLAB standard procedure:
```matlab
char('hello','this','is','a','matrix','of','çhars')
```
See also the command `cellstr`.

It also gives a very readable output. For me it's a no-brainer.

**Comment by jaeandersson** [comment]
Resolved. Now `vector<string>` can be placed inside structs allowing options such as `io_scheme` to be used.

**Comment by jgillis** [comment]
There is some problem with vector<string> with one element: char('hello') is not accepted.
