### ISSUE TITLE
domain name troubles?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1525]
@nielsvd reports that there appears a page load failure every first time he goes to `casadi.org` or `docs.casadi.org`. Might be something wrong with our redirect settings.

Error "The connection was reset".

**Comment by jgillis** [comment]
This happens regardless of a trailing slash

**Comment by jgillis** [comment]
Note even lynx has this effect.

**Comment by jgillis** [comment]
Seems like it doesn't matter which browser is used.

Problem acts like a two-state state-machine installed for each subdomain:

```
     FAILING
           |
           v
      WORKING
```

After every failure comes a working response. One's in working mode, you stay in working mode.
But there is some mysterious condition that brings you back to failing state.
This is true regardless of the browser used.

What is that condition? "wait long enough" seems to work.

**Comment by jgillis** [comment]
Note this may make many casadi links appear dead to robots..

**Comment by jaeandersson** [comment]
I'm pretty much illiterate when it comes to this kind of stuff... Should be easy for someone with knowledge to fix.

**Comment by jgillis** [comment]
Issue seems to come and go according to the whether..

**Comment by jgillis** [comment]
Seems to have fixed itself. Haven't seen this in a couple of weeks..

**Comment by jgillis** [comment]
Seems to be active again.

**Comment by jgillis** [comment]
haven't seen this in ages
