### ISSUE TITLE
Cross-platform codegen

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1528]
How to do it?

@nielsvd suggests relying on cmake
Another option is to ship libclang

**Comment by jgillis** [comment]
See #949

**Comment by jgillis** [comment]
Pointers: http://fdiv.net/2012/08/15/compiling-code-clang-api

**Comment by jaeandersson** [comment]
IMO: ship libclang

**Comment by jgillis** [comment]
Essentially solved with JitFunction
