### ISSUE TITLE
Common subexpression elimination

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1540]
@nielsvd has a use case in robotics that needs it badly.

I was thinking of a hash tree implementation:
`hash(expr) = hash(str(OP)+sum_i(hash(dep_i)))`,
with hash(x):    str -> str

For commutative operations you would sort the hashes of the dependencies before hashing together.

And make the hash large enough to assume it is collision free

**Comment by ghorn** [comment]
What is the use case, out of curiosity?

**Comment by jaeandersson** [comment]
For MX or SX? For MX, there are other things that have to be resolved first (in particular caching of constants).

In principle, the way to go is to replace the constructors with a cache. I would have one cache per node class. Cf. e.g. `constant_sx.hpp`. To avoid code duplication, this functionality should be moved to a separated class (e.g. using CRTP idiom). 

In general, I would try to prevent duplicate expressions to be created in the first place, not try to locate and eliminate them afterwards. 

Cf. #333.

**Comment by jgillis** [comment]
SX

**Comment by jgillis** [comment]
Using one cache per node class looks indeed like a good idea.

To make it work efficiently at construction time, it makes sense to have an extra member for each SXNode indicating its hash.
But adding a member to SXNode may be undesirable in terms of the memory overhead/VM overhead.

**Comment by jgillis** [comment]
A 128 bit hash would have a fairly low collision chance (http://davidjohnstone.net/pages/hash-collision-probability). Would 16 bytes overhead be acceptable for SXNodes?

As I understand it, the sorted graph (=algorithm) is traversed top to bottom (no random access) in SXFunction, so it should not really matter for speed of the VM.

The current binary node seems to have: 3 ints, 2 pointers, and 1 char..

**Comment by nielsvd** [comment]
Public-domain implementation of SHA-1: http://www.dominik-reichl.de/projects/csha1/

**Comment by jgillis** [comment]
I saw some 'Joel' was told about the hash tree before: http://stackoverflow.com/questions/11326346/implementing-common-subexpression-elimination

**Comment by jgillis** [comment]
http://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed

**Comment by jgillis** [comment]
Murmur seems to be a good candidate: https://smhasher.googlecode.com/svn/trunk/MurmurHash3.cpp

**Comment by jaeandersson** [comment]
There is already caching of constants and of sparsity patterns. We cannot maintain multiple ways of caching things. So, if the current approach is not satisfactory, it should be changed everywhere, not just for this case. The sparsity patterns uses a hash of size "std::size_t", i.e. 32 or 64 bit depending on system I guess. Collisions are permitted and are dealt with, that's the reason why a `std::unordered_multimap` and not the cheaper `std::unordered_map` is used for the caching of sparsity patterns. For `constant_sx.hpp`, where collisions are not possible, `std::unordered_map` is used however.

I see no point in using some fancy (expensive) 128-bit hash, the above approach works fine. And if hash collisions are not fatal (they should not be), what's the benefit of SHA-1 or whatever? The current way to calculate hash values was taken from boost and is very cheap. I see no reason to replace it for something else. The implementation can be found in `sparsity.hpp`.

**Comment by jaeandersson** [comment]
> And make the hash large enough to assume it is collision free

Against this. We need to handle collisions (which is already done in for sparsity patterns).

**Comment by jgillis** [comment]
In private conversation, @jaeandersson made two releveant points:
 1) a cheap "true" equality check does not depend on collision-freeness of the hashing ( It's not clear to me yet why)
 2) codegen + compile may already do the cse, making a reimplementation in casadi unnecessary (codegen is easier in the upcoming release with JitFunction)

**Comment by jaeandersson** [comment]
> 1) a cheap "true" equality check does not depend on collision-freeness of the hashing ( It's not clear to me yet why)

If you use a `std::unordered_multimap` as a map from the hashed value to a cached node, you can have multiple hash values pointed to the same node. You just need to be prepared to do a linear search to find the right one. If the linear search consists of 0 or 1 values and extremely rarely (in principle almost never) 2 or more value, you still have the same complexity.

**Comment by jgillis** [comment]
Relying completely on JIT to do cse might not always work:
the graph may be so big that the compiler fails (out of memory) or takes an excessive amount of time.

**Comment by jaeandersson** [comment]
A completely different approach is to cache everything, that is avoid duplicate expressions to be created in the first place, but come up with an algorithm for recalculating subexpressions in order to save memory. Then, e.g.
```python
x = SX.sym('x')
y = SX.sym('y')
z1 = x + y
z2 = x + y
f = z1 ** z2
``` 
would be guaranteed to be equivalent to
```python
x = SX.sym('x')
y = SX.sym('y')
z = x + y
f = z ** z
```

**Comment by jaeandersson** [comment]
I'm not sure that it's possible to come up with such an algorithm though, without violating the AD complexity rules.

**Comment by jaeandersson** [comment]
In any case, I don't see why caching could not take place one level higher. That is, there is caching of the code the user writes, but not of the expressions created by AD. Think of a wrapper expression class on top of SX and MX that caches SX/MX expressions. Something like:
```c++
template<typename MatType>
class CashedExpression : public GenericMatrix<CashedExpression<MatType> >, 
  GenericExpression<CashedExpression<MatType> > {
...
}

typedef CashedExpression<SX> CachedSX;
typedef CashedExpression<MX> CachedMX;
```

**Comment by jaeandersson** [comment]
If there were such a class, we could completely remove e.g. the caching of constants in SX and you get a nice and clear rule:
 * `SX`/`MX` never caches
 * `CashedSX`,`CashedMX` always caches

To "encourage" people to used the cached classes, one can use `SX` to refer to `CashedSX` and rename the current `SX` something else.

**Comment by jgillis** [comment]
A simple case that would benefit from cse:

```python
from casadi import *

x = SX.sym("x")
y = sqrt(sin(x))

f = Function("f",[x],[hessian(y,x)[0]])
f.disp(True)
```

Note the multplie instances of `sin(@0)` and `cos(@0)`
```
f:(i0)->(o0) SXFunction
Algorithm:
@0 = input[0][0];
@1 = sin(@0);
@2 = sin(@0);
@2 = sqrt(@2);
@3 = (@2+@2);
@1 = (@1/@3);
@4 = cos(@0);
@4 = (@4/@3);
@4 = (@4/@3);
@0 = cos(@0);
@2 = (@2+@2);
@0 = (@0/@2);
@0 = (@0+@0);
@4 = (@4*@0);
@1 = (@1+@4);
@1 = (-@1);
output[0][0] = @1;
```

**Comment by jgillis** [comment]
@tmmsartor let's implement cse at SX Function init time.

**Comment by jgillis** [comment]
Idea for determining equality of MX nodes: recycle serialization byte stream: if it serializes the same, it is the same.

**Comment by jgillis** [comment]
Missing cases:

Function redefinitions
```
    x = MX.sym("x")
    y = MX.sym("y")
    z = MX.sym("z")
    f1 = Function('f',[x,y],[x+y])
    f2 = Function('f',[x,y],[x+y])
    
    print(cse(f1(x+y,z)-f2(x+y,z)))
```
