### ISSUE TITLE
Setting function inputs with zero dimension from a struct does not work in release-2.4.0-rc1

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1542]
I think there is a bug in the CasADi version from the `release-2.4.0-rc1` branch, since the following errors occur, while with 2.3.0, setting inputs from struct elements with zero dimension worked fine.

```
import casadi as ca
import casadi.tools as cat

a = ca.MX.sym("a", 0)

b = a

c = cat.struct_MX([
        cat.entry("a", expr = a)
    ])

# This one works well

ca.MXFunction("test", [a], [b])

# This one does not, returns RuntimeError:
# MXNode::hasDuplicates() not defined for class N6casadi8ConstantINS_16CompiletimeConstILi0EEEEE

ca.MXFunction("test", [c["a"]], [b])

# This one returns a DeprecationWarning, which is fine

ca.MXFunction([a], [b])

# This one returns the RuntimeError from above, but additionally
# causes Python to crash

ca.MXFunction([c["a"]], [b])
```

**Comment by jgillis** [comment]
Thanks for reporting!

**Comment by adbuerger** [comment]
You're welcome! Do you think this is a huge thing? I'm using this quite often within my PECas project when I set up functions automatically, so for me to switch to CasADi 2.4.0, this would be necessary to work, and I would really like to test your new features.

**Comment by jgillis** [comment]
I'm unsure yet if it is trivial or tricky to fix..

**Comment by jgillis** [comment]
Diagnostics: 
```
a.isConstant() # False
c.cat.isConstant() # True
```

**Comment by jgillis** [comment]
Diagnostics:

```
MX.sym("a",0).nz[:].isConstant() # True
MX.sym("a",1).nz[:].isConstant() # False
```

**Comment by jgillis** [comment]
I just realised your proposed usage of structures is a bit weird.

I'm suprised it works in 2.3.0, since the intended usage is to use "struct_symMX" for symbolic primitives, and struct_MX for expressions:
```python
c = cat.struct_symMX([
        cat.entry("a", shape=a.shape)
    ])
```
Since we are introducing support for simple mappings of symbolic primitives as MXFunction input arguments with 2.4.0, the bug is still relevant though..

**Comment by adbuerger** [comment]
Oh, ok, I didn't realize that, sorry about that.

But if I instead use `struct_symMX` for the symbolic primitives, as soon as I (in this case, with CasADi from master branch) use a zero dimensional and a non-zero dimensional object in combination, I get following situation:

    import casadi as ca
    import casadi.tools as cat

    a = ca.MX.sym("a", 0)
    b = ca.MX.sym("b", 1)

    c = a + b

    d = cat.struct_symMX([
            cat.entry("a", shape = a.shape), \
            cat.entry("b", shape = b.shape),
        ])

    e = cat.struct_MX([
            cat.entry("c", expr = c)
        ])

    # The following returns a RuntimeError saying:
    #
    # RuntimeError:  on line 159 of file "/home/ab/casadi/casadi/core/function/x_function_internal.hpp"
    # XFunctionInternal::XFunctionInternal: Xfunction input arguments must be purely symbolic.
    # Argument #1 is not symbolic.

    ca.MXFunction([d["a"], d["b"]], [e["c"]])


Shouldn't it work that way then, or am I doing something wrong here?

**Comment by jgillis** [comment]
This is indeed not supposed to work. The following is:
```
Ca.MXFunction([d], [e["c"]])
```

**Comment by adbuerger** [comment]
Which makes sense of course. Thanks very much!

**Comment by jgillis** [comment]
Lowering priority since it does not correspond to a recommended usage pattern.

**Comment by jgillis** [comment]
Structure is reaching EOL
