### ISSUE TITLE
Get more serious about binary plugins

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1544]
At the moment, it is not clear what version of solvers built plugins are linked with.
At the minimum, there should be a page/file with the versions of the binary plugins listed.

**Comment by jgillis** [comment]
Possibly, the binary plugins should be downloadable separately in a range of versions.

**Comment by jaeandersson** [comment]
If you want to have a range of versions, do we need a naming scheme? E.g. `libcasadi_nlpsolver_ipopt_3_11.dylib`?

**Comment by jgillis** [comment]
I think yes. "version" would be an option that you pass on to the NlpConstructor perhaps?

**Comment by jgillis** [comment]
The versioning shouldnt be finely grained, only if its not binary compatible

**Comment by jaeandersson** [comment]
I'm not convinced of the naming scheme... Maybe it's enough to have a check that the versions match when loading the plugin? Both the versions of CasADi and of the interfaced tool.

**Comment by jgillis** [comment]
Maybe versioning is not needed. The user might make a folder structure in the home dir:

```
casadi_plugins
  -  snopt
     -  snopt7.4
           libcasadi_nlpsolver_snopt.so
     -  snopt7.5
           libcasadi_nlpsolver_snopt.so
```

Which mimicks exactly a sourceforge structure.

And another directory for the solvers libraries:

```
third_party_solvers
  -  snopt
     -  snopt7.4
           libsnopt.so
     -  snopt7.5
           libsnopt.so
```

Then you could run casadi either with `LD_LIBRARY_PATH=casadi_plugins/snopt/snopt7.4;third_party_solvers/snopt/snopt7.4` or  `LD_LIBRARY_PATH=casadi_plugins/snopt/snopt7.5;third_party_solvers/snopt/snopt7.5`, depending on your mood at the moment.

**Comment by jaeandersson** [comment]
I think that this is recipe for a great mess. We should support one (and only one) SNOPT version per CasADi version. It's not reasonable to build multiple versions. Just let the user update SNOPT. We should also make it easy to build the plugins stand-alone.

**Comment by jgillis** [comment]
I see. Saves me a lot of work anyway.

**Comment by jaeandersson** [comment]
Why? Windows users should be able to download a SNOPT version of choice. I think that the current confusion can be contributed to a large degree to the fact that we haven't specified clearly which version we support.
