### ISSUE TITLE
Possibility to reshape with automatically computed second dimension (like in Numpy)

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1549]
I think it would be useful if the CasADi ``reshape`` function would provide a possibility so that a user only needs to set the first dimension, and the resulting second dimension is computed from the array size. In Numpy, one can do this by passing ``-1`` for the dimension to be computed, see http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

**Comment by jaeandersson** [comment]
In Matlab, you can set a dimension to 0-by-0 ([]).

**Comment by adbuerger** [comment]
I'm sorry but I do not really understand your answer. What I meant was that in Numpy, you can do something like

    import numpy
    a = numpy.random.rand(4, 4)
    desired_first_dimension = 2
    b = a.reshape((desired_first_dimension, -1))

which is practically the same as

    b = a.reshape((desired_first_dimension, a.size / desired_first_dimension))

and results in an 2x8 array. Though it's not complicated to fill in the longer expression, it find the `-1` useful as a shortcut.

**Comment by adbuerger** [comment]
And btw, sorry to bring up this old issue, but I stumbled across this thing again just now.

**Comment by jaeandersson** [comment]
-1 as second dimension would indeed work. I guess you can allow both (-1, x) and (x, -1)

**Comment by adbuerger** [comment]
That would be great, thank you!
