### ISSUE TITLE
inherit options?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1550]
It can be hard to make options percolate in the intended manner from a function to other functions that derive from it such as: forward derivative, reverse derivative, helper MXFunction, ...

I propose a couple of new options to guide the behaviour such as:
```
inherit_forward  OT_STRINGVECTOR
inherit_reverse  OT_STRINGVECTOR
```
The contents would be a list of strings that governs which options are passed through.

In addition there could be:
```
options_forward OT_DICTIONARY
options_reverse OT_DICTIONARY
```

which would contain options that are custom for the dependant functions.

**Comment by jaeandersson** [comment]
:+1:

**Comment by jgillis** [comment]
Perhaps "propagate" is a better term ?

**Comment by jaeandersson** [comment]
Actually I think this a wontfix. When the work vector change is completed, the Function should not store the options that was used to created anymore.

**Comment by jaeandersson** [comment]
I'm closing this "wontfix" due to the above reason. Also, the existing design allows derived functions to selectively set options for generated options (some code duplication can be avoided there though).
