### ISSUE TITLE
An errata in the user guide about logical operations

### ISSUE THREAD

**Issue by BachiLi** [casadi/casadi#1551]
The logical operations in chapter 9.2 of the user guide (http://casadi.sourceforge.net/users_guide/casadi-users_guide.pdf) for python and C++ are probably reverted.  "&&", "||", and "!" do not work for python and it should be "logic_and", "logic_or", "logic_not".

**Comment by jaeandersson** [comment]
Thank you for reporting. It has been corrected now (might take some time before the corrected guide is uploaded).
