### ISSUE TITLE
Segfault when trying to embed functions into SX

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1552]
This is not supported, but should fail more gracefully.

**Comment by jaeandersson** [comment]
Ct. https://groups.google.com/forum/m/#!topic/casadi-users/JBjHUv-lAtY

**Comment by jgillis** [comment]
Somwhat urgent for 2.4.0 I'd say...

**Comment by jaeandersson** [comment]
Fixed in develop and 2.4.1.

**Comment by jaeandersson** [comment]
This is the fix: 7fc94e34d653d270b02fc41477f98f7db6928466
