### ISSUE TITLE
Redistribution of pthread.h fails

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1556]
pthread.h is not correctly copied to the jit headers on my mac. For me, `phthread.h` is a symbolic link to `pthread/pthread.h` and only the symbolic link is copied without the `pthread/pthread.h`. Curiously, `pthread_impl.h` and `sched.h` which are also symbolic links, to `pthread/pthread.h` and `pthread/pthread_impl.h` respectively are distributed correctly.

**Comment by jaeandersson** [comment]
I guess the issue is not correctly taking into account that some of the dependencies can be symbolic links.

**Comment by jgillis** [comment]
Is this moot?

**Comment by jaeandersson** [comment]
This will be solved by properly providing a link to or distributing the standard library.
