### ISSUE TITLE
IPOPT location change not recognized when CasADi is rebuilt, causes segmentation fault

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1558]
On Ubuntu 14.04, I updated IPOPT by building it from the SVN repository, and while doing this, I changed the location of the IPOPT libs from /usr/lib to /usr/local/lib, so the new ones are now in /usr/local/lib, the old ones got deleted from /usr/lib.

Running CasADi without rebuilding it says "module 'ipopt' not found", which is ok. When I now do

    -cmake -DWITH_PYTHON=ON ..
    make 
    sudo make install

nothing is rebuilt, it says everything is up-to-date, so the new location of IPOPT seems not to be taken into account. So I ran an additional ``make clean`` beforehand, and rebuilt CasADi. Then I was able to start IPOPT from CasADi, but after the greeting message, Python crashed with a segmentation fault.

To make it work again, I had to manually remove all CasADi-related files from /usr/local/lib, /usr/local/include and all their subdirectories. Without this, not all necessary files were replaced in the installation directories, but wrongly declared as "up-to-date" by make.

**Comment by jaeandersson** [comment]
I'm not sure I know of a solution to this. I think it will get resolved once the build system becomes more mature. Ideally with versioning of the binaries... But in the meantime, I'm not sure I know a way forward...

**Comment by adbuerger** [comment]
Well, I do not think that this is really urgent now in any way. I just wanted to tell you if you encounter it once yourself, or some other user might run into this situation.

**Comment by jaeandersson** [comment]
OK, I guess it's well known that things can happen if there are old libraries lingering in the system... For the actual feature, there is already a dedicated issue #1258. So I'll close this wontfix.

**Comment by adbuerger** [comment]
OK. But just for correctness (don't know if this is important) the old libraries were removed from the system, and the new ones were found by the built system. It did just not rebuild all necessary libraries etc.
