### ISSUE TITLE
Demostration on how to write a SWIG module that uses CasADi

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1559]
If a user writes a C++ extension to CasADi, it should be possible to easily generate Python/MATLAB bindings using the `%modules` feature in SWIG.

**Comment by jaeandersson** [comment]
Ready for merging. The demonstration is enabled with the "WITH_EXTENDING_CASADI" option.

**Comment by jaeandersson** [comment]
@jgillis I'd like to have this included in 2.4.

**Comment by jgillis** [comment]
I like this idea a lot.
I think it would be added value to 1) have this example completely isolated as in https://github.com/casadi/howto/tree/mysolver_cpp, and 2) have it work together with the binaries.

Build-systems can be daunting and it may cost greater-than-necessary effort for the user to extract this minimally working example from a casadi clone into a vanilla working directory. Actually, if not isolated, it may in fact appear easier to add C++ code directly in our casadi folder.

**Comment by jaeandersson** [comment]
Agreed. What about a separate github repo where casadi-master is included as a submodule? Note that you don't need to build CasADi, but you do need the source and the `casadi.i`. You can also make use of the "cmake" directory etc.

**Comment by jaeandersson** [comment]
I'll close this here as it exists and works. Design can be improved further but better handle it in a separate issue.
