### ISSUE TITLE
requesting an optimal control example using map

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1564]
A simple multiple shooting with RK4 or Euler integration would be really useful.

**Comment by ghorn** [comment]
I added the simplest possible example showing a speedup using openmp parallelism. This should be turned into an OCP example demonstrating the parallelism speedup.

It's so close I can taste it

**Comment by jgillis** [comment]
There is an example: sysid.py

**Comment by ghorn** [comment]
doh
