### ISSUE TITLE
Avoid polluting user directory with temporary files

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1570]
There are ways of creating temporary files, both on linux and windows, that avoids polluting this user directory: http://stackoverflow.com/questions/8087805/how-to-get-system-or-user-temp-folder-in-unix-and-windows

This should be preferable both for safety and user-friendliness reasons.

**Comment by jgillis** [comment]
There should be an unclean variant, such that you may inspect the code.

**Comment by jaeandersson** [comment]
> There should be an unclean variant, such that you may inspect the code.

You can do codegen and inspect.

**Comment by jaeandersson** [comment]
I believe that this has been fixed.
