### ISSUE TITLE
Switch with mismatching sparsity

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1571]
The Switch class (cf. #1413) currently assumes that the sparsities of the different cases match, which may not be the case, especially for derivatives. If this is not the case, a "not implemented" error is thrown.

**Comment by jgillis** [comment]
For reference, here's an example:

``python`
from casadi import *

x0 = MX.sym("x0", 1)
x1 = MX.sym("x1", 1)

x = veccat(x0, x1)

y = sin(x0)
z = cos(x1)

F0 = Function("F0",[x],[y])
F1 = Function("F1",[x],[z])
s = Function.conditional('s',[F0,F1],F0)

fr = s.reverse(1)

fr(0,0,0,0)
```

**Comment by jaeandersson** [comment]
If you want to keep the atomic simple, ensure that Switches with mismatching sparsity are never created. Just wrap it in an MXFunction.
