### ISSUE TITLE
Remove deprecated functions, post 2.4

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1572]

**Comment by ghorn** [comment]
wooo

**Comment by jaeandersson** [comment]
Next steps:
 * Remove use of old syntax (in particular setInput, evaluate, getOutput) in test suite. This will allow these functions to be hidden from SWIG.
 * Complete #1356

@jgillis - did you plan to refactor the test suite? In the test suite, there are currently 442 calls to evaluate, 1087 calls to setInput, 777 calls to getOutput, 92 calls to getInput and 4 calls to setOutput, so there is a bit of work to update this manually.

**Comment by jaeandersson** [comment]
Current balance in test suite: 
 * `.evaluate`: 367 calls
 * `.setInput`: 792 calls
 * `.getInput`: 84 calls
 * `.setOutput`: 1 call
 * `.getOutput`: 641 calls
 * `.setInputNZ`: 37 calls
 * `.getInputNZ`: 0 calls
 * `.setOutputNZ`: 0 calls
 * `.getOutputNZ`: 0 calls
 * `.output`: 1 call
 * `.input`: 1 call

Don't know of any way to automate this...

**Comment by jaeandersson** [comment]
@jgillis - what were your plans concerning the test suite?
