### ISSUE TITLE
some scheme helpers don't match InputOutputScheme enum

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1574]
the enum has `ControlledDaeIn` but the helper is `controldaeIn`

**Comment by ghorn** [comment]
another: `lpIn` vs `LPSolverInput`

**Comment by ghorn** [comment]
`stabilizedQpIn` vs `StabilizedQpSolverInput`

**Comment by ghorn** [comment]
`lpOut` vs `LpSolverOutput`

**Comment by jaeandersson** [comment]
They should all go away IMO.

**Comment by ghorn** [comment]
I like them :(

**Comment by ghorn** [comment]
To clarify, they are more convenient for me than the nlpIn() helpers. The alternative would be to provide an nlpIn() which takes a dictionary instead of (string, arg, string, arg, etc)

**Comment by jaeandersson** [comment]
ControlSimulator is gone #1591.
