### ISSUE TITLE
Commit scrutinizing

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1578]
Todo stack

Joris
 * [x] 54c029e9c1b1d08

**Comment by ghorn** [comment]
would appreciate review of:

* [ ] https://github.com/casadi/casadi/blob/adb0e4ecb075e5be5fbad509713e305a2ffb79fa/casadi/interfaces/ipopt/ipopt_interface.cpp#L73-L97

**Comment by jgillis** [comment]
@ghorn seems like that has been obliterated
