### ISSUE TITLE
Remove public classes inheriting from Function

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1585]
I think we should move towards having only a single public `Function` class and remove the public classes for `SXFunction`, `NlpSolver`, `Integrator` etc. This will make the API cleaner and smaller, but some functionality which is currently provided as member functions of these classes would have to be provided in other ways.

Here's what I propose to do with existing classes:
 * `SXFunction` and `MXFunction` are replaced with static member functions in the `SX` and `MX` classes respectively. I.e. the new syntax becomes `SX.Function` and `MX.Function` in Python/MATLAB and  `SX::Function` and `MX::Function` in C++. Upper case F in `Function` deviates from the current naming convention so we have to decide whether to change this name or change the naming convention.  `SX.function` and `MX.function` are probably not options as `function` is most certainly a keyword in at least MATLAB.
 * `NlpSolver`, `Integrator` etc. are replaced with functions in the `casadi` namespace with the same name. They return `Function` instances. The above remark about naming convention also applies.

**Comment by jaeandersson** [comment]
Updated proposal:
 * `Function` is renamed `Functor` (current `Functor` class is removed/renamed). This is a better name.
 * Lower initial letter is used for the functions. It means old and new design can live side by side and the old design can be deprecated gently.

In short:
 * `Function` -> `Functor`
* `SXFunction` -> `SX.functor`
* `MXFunction` -> `MX.functor`
* `NlpSolver` -> `nlpSolver`
* `Integrator` -> `integrator`

**Comment by ghorn** [comment]
:poop: on Function -> Functor

I thought we'd settled this. The rest I agree with

**Comment by jaeandersson** [comment]
Right, Functor in Haskell... So, what about `SX.create` and `MX.create` instead of `SXFunction`, `MXFunction`?

**Comment by ghorn** [comment]
why not SX.Function or SX.function ?

**Comment by jaeandersson** [comment]
`SX.Function` breaks the naming convention in CasADi where upper case initial letter is used for classes and lower case initial letter is used for functions. `SX.function` not possible since `function` is a keyword in MATLAB.

**Comment by jaeandersson** [comment]
I think a short name would be good. This is something that is written often and needs to be kept short for presentation snippets. What about `fun`? This is in line with `SX.sym` for creating a symbolic primitive.

So in conclusion:
 * `Function` unchanged
 * `SXFunction` -> `SX.fun`
 * `MXFunction` -> `MX.fun`
 * `NlpSolver` -> `nlpSolver`
 * `Integrator` -> `integrator`

**Comment by jaeandersson** [comment]
`fun` is a keyword in F#... But I don't think that should be a blocker...

**Comment by jaeandersson** [comment]
I'm going to make one amendment: 
 * `NlpSolver` -> `solver`

This would be a first step towards a uniform syntax for creating solver instances, e.g.
 * `mysolver1 = solver('mysolver, 'ipopt', {'x':x, 'f':x*x, 'g':x+2})
 * `mysolver2 = solver('mysolver, 'qpoases', {'x':x, 'f':x*x, 'g':x+2})

I'm expanding on this in #1590.

**Comment by jgillis** [comment]
SX.fun sounds good. Better than the alternatives.

**Comment by jaeandersson** [comment]
Is there a better name for `ImplicitFunction` than `implicitFunction`? Something short and catchy like `optimizer`, `integrator`?

**Comment by jgillis** [comment]
rootfinder?

**Comment by jaeandersson** [comment]
`rootfinder` sounds good. I guess `solver` would be ambiguous? Important to note that we will probably want to use the same syntax for both linear and nonlinear systems of equations.

**Comment by jgillis** [comment]
Yes, solver is a word with virtually no context-free semantics.

**Comment by jaeandersson** [comment]
So:
 * `Function` unchanged
 * `SXFunction` -> `SX.fun`
 * `MXFunction` -> `MX.fun`
 * `NlpSolver`, `QpSolver`, `LpSolver`, `SdpSolver` etc. -> `optimizer`
 * `Integrator` -> `integrator`
 * `ImplicitFunction` -> `rootfinder`
 * `Simulator` -> `simulator` (?)

What about `LinearSolver`?

**Comment by jgillis** [comment]
Is simulator still needed now there is mapaccum?

**Comment by jaeandersson** [comment]
If Simulator can be removed, great. It's not even differentiable at the moment. That belongs to a separate issue though.

**Comment by jaeandersson** [comment]
The Simulator class currently uses the fact that the Integrator class can do time stepping and that it keeps an internal state. This is something hard to maintain anyway.

**Comment by jaeandersson** [comment]
I think the Integrator class should be refactored to allow calculating the output at multiple time points. Merging Integrator and Simulator.

**Comment by jaeandersson** [comment]
Cf. #1591, #1592.

**Comment by ghorn** [comment]
fun sounds good, there is also fcn. I have no preference

**Comment by jaeandersson** [comment]
Okey, so we have:
 * `Function` unchanged
 * `SXFunction` -> `SX.fun`
 * `MXFunction` -> `MX.fun`
 * `NlpSolver`, `QpSolver`, `LpSolver`, `SdpSolver` etc. -> `optimizer`
 * `Integrator`, `Simulator` -> `integrator`
 * `ImplicitFunction` -> `rootfinder`
 * `ControlSimulator` removed

Open questions:
CustomFunction, ExternalFunction, LinearSolver

**Comment by jaeandersson** [comment]
Note that for C++ users, the `auto` keyword can be used to get more compact syntax:
```c++
# Current syntax
casadi.SXFunction f("f", {x, y}, {f, g});
# New syntax
casad.Function f = casadi.SX.fun("f", {x, y}, {f, g});
# New syntax (alternative)
auto f = casadi.SX.fun("f", {x, y}, {f, g});
```

**Comment by jaeandersson** [comment]
Update:
`SXFunction` -> `SX.fun`, `MXFunction` -> `MX.fun` change completed. `CustomFunction` removed.

To do:
 * `NlpSolver`, `QpSolver`, `LpSolver`, `SdpSolver` etc. -> `optimizer`
 * `Integrator`, `Simulator` -> `integrator`
 * `ImplicitFunction` -> `rootfinder`
 *  Remove `ControlSimulator`

Proposal:
 * `ExternalFunction` -> `Function.external`
 * `LinearSolver` -> `solver`

Ping @ghorn @jgillis

**Comment by jaeandersson** [comment]
I'm not sure what to do with LinearSolver actually. It is a bit different from other function objects since it supports transposes (it has to due to reverse mode AD rule). Meaning you have two ways of evaluating it, transposed or non-transposed. The transpose property cannot be an input, since it is needed for e.g. the sparsity pattern propagation.

So a possibility would be to keep `LinearSolver` as a public class, but have it not be a `Function` anymore. It would still be a mutable object:
```python
linsol = LinearSolver(...)
linsol.factorize(A)
b1 = linsol.solve(rhs1)
b2 = linsol.solve(rhs2)
b3 = linsol.solve(rhs3)

# Embed it in a graph
MX b = MX::solve(rhs, linsol)
```

**Comment by jaeandersson** [comment]
Style question:
 * `a = optimizer(...)` or `a = Function.optimizer(...)`
 * `a = integrator(...)` or `a = Function.integrator(...)`
 * `a = rootfinder(...)` or `a = Function.rootfinder(...)`

Making it a static function makes the syntax slightly more verbose, but is unambiguous and would be consistent with existing syntax.

**Comment by jaeandersson** [comment]
Now, if `SX` instances are being created using the `SX` class, `MX` instances created using the `MX` class and `Function` being created using the `Function` class, then the just added `SX.fun` and `MX.fun` are actually inconsistent...

We could in principle overload the `Function` constructor...
 * `Function('x', [x], [sin(x)])

`SXFunction` or `MXFunction` would be determined by function overloading. A nasty problem is that this would be ambiguous for e.g. `Function('x', [], [DMatrix(4)]).

Going to the other extreme, avoiding ambiguity, the proposed `optimizer`/`integrator`/`rootfinder` syntax is actually problematic. An unambitious variant would be to introduce `SX.solver` and `MX.solver`:
```python
from casadi import *
x = SX.sym("x")
y = SX.sym("y")
z = SX.sym("z")
f = x**2 + 100*z**2
g = z + (1-x)**2 - y
nlp = {'x':vertcat([x,y,z]), 'f':f, 'g':g}
solver = SX.solver("solver", "ipopt", nlp)

# Solve the Rosenbrock problem
print solver({"x0" :[2.5,3.0,0.75], "ubg" : 0, "lbg" : 0})
```

**Comment by jaeandersson** [comment]
Ping @ghorn @jgillis

**Comment by jaeandersson** [comment]
Already done:
 * `SXFunction` -> `SX.fun`
 * `MXFunction` -> `MX.fun`
 * `CustomFunction`, `ControlSimulator`, `HomotopyNlpSolver` removed.
 * `Map` -> `f.map(...)`
 * `Switch` -> `Function.if_else` and `Function.conditional`
 * `ExternalFunction` -> `Function.external`

Here is my final proposal for the rest:
 * `NlpSolver` -> `Function.nlp_solver` (NLP is a function) and `Function.solver` (NLP is an expression)
 * `QpSolver` -> `Function.qp_solver` (QP is a function) and `Function.solver` (QP is an expression)
 * `Integrator`, `Simulator` -> `Function.integrator`
 * `ImplicitFunction` -> `Function.rootfinder`

I.e., each type of solver (NLP solver, QP solver etc) have their own problem-specific creator function as well as one which has the same syntax for all solvers (`Function.solver`). The latter takes an expression:
```python
# NLP: High-level interface (standard) <== Current syntax for NlpSolver
nlp = {'x':x, 'f':inner_prod(x,x), 'g':x+3}
s = Function.solver('my_solver', 'ipopt', nlp)

# NLP: Low-level interface (non-standard) <== Current syntax for NlpSolver
nlp = MX.fun('nlp', nlpIn(x=x), nlpOut(f=inner_prod(x,x), g=x+3))
s = Function.nlp_solver('my_solver', 'ipopt', nlp)

# QP: High-level interface (standard) <== New
qp = {'x':x, 'f':inner_prod(x,x), 'g':x+3}
s = Function.solver('my_solver', 'qpoases', qp)

# QP: Low-level interface (non-standard) <== Current syntax for QpSolver
qp = {'H': H, 'A':A}
s = Function.qp_solver('my_solver', 'qpoases', qp)
```

**Comment by jaeandersson** [comment]
OK, here is the final, final design:
 - [x] `SXFunction` -> `SX.fun`
 - [x] `MXFunction` -> `MX.fun`
 - [x] `CustomFunction`, `ControlSimulator`, `HomotopyNlpSolver` removed.
 - [x] `Map` -> `f.map(...)` (non-static member function)
 - [x] `MapAccum` -> `f.mapaccum(...)` (non-static member function)
 - [x] `Switch` -> `Function.if_else` and `Function.conditional`
 - [x] `ExternalFunction` -> `Function.external`
 - [ ] `NlpSolver` -> `Function.nlp_solver`
 - [ ] `QpSolver` -> `Function.qp_solver`
 - [ ] `Integrator` -> `Function.integrator` 
 - [ ] `Simulator` -> `Function.integrator`
 - [x] `ImplicitFunction` -> `rfp.rootfinder` (non-static member function)

**Comment by jaeandersson** [comment]
Not so final final after all.. I changed `SX.fun` and `MX.fun` to `Function`:
```python
x = MX.sym( 'x')
f = Function('f', [x], [sin(x)])
```
is simply more readable than
```python
x = MX.sym( 'x')
f = MX.fun('f', [x], [sin(x)])
```
especially since the return value is Function.

**Comment by jaeandersson** [comment]
Accessing the functions specific for a particular class requires a naming convention, e.g.
```c++
    /// Access rhs function for a rootfinder
    Function rootfinder_fun();
```
for accessing the rhs function for a rootfinder class.

To keep the syntax compact, I think a shorter name would be desired. I would propose the following, shorter names:
 * `LinearSolver` -> `Function.linsol`
 * `ImplicitFunction`-> `Function.nlsol` (instead of `Function.rootfinder` in current iteration)
 * `QpSolver`-> `Function.qpsol` (instead of `Function.qp_solver` in current iteration)
 * `NlpSolver`-> `Function.nlpsol` (instead of `Function.nlp_solver`in current iteration)
 * `Integrator` -> `Function.integrator` (already satisfied)

**Comment by jaeandersson** [comment]
I'm going for `Function.ivpsol` (=initial-value problem solver) instead of `Function.daesol`. `daesol` makes you think there is another `odesol`.

**Comment by nbibin001** [comment]
Hi I was trying to use the Casadi 2.4.1 with Matlab. Was trying with a simple example to get started with. Below is what I was trying. I get back an error on this line.
solver = Function.nlpsol('solver', 'ipopt', nlp); 

Error: No appropriate method, property, or field 'nlpsol' for class 'casadi.Function'.
I looked at the Function.m class file in the Casadi folder casadi-matlabR2014b-v2.4.1. Couldn't find anything with nlpsol in it. I am using the 2.4.1 Casadi Matlab version. Could anyone help me with it ? Appreciate your help.


 % Load CasADi 
 import casadi.* 
   % Create NLP: Solve the Rosenbrock problem: 
 %     minimize    x^2 + 100*z^2 
 %     subject to  z + (1-x)^2 - y == 0 
x = SX.sym('x'); 
 y = SX.sym('y'); 
 z = SX.sym('z'); 
 v = [x;y;z] 
 f = x^2 + 100*z^2; 
 g = z + (1-x)^2 - y; 
 nlp = struct('x', v, 'f', f', 'g', g); 
   % Create IPOPT solver object 
 solver = Function.nlpsol('solver', 'ipopt', nlp);

**Comment by jgillis** [comment]
Hi there. The code snippet you located is for casadi versions higher than 2.4.x,
For the stable 2.4.1 release (which is recommended), you need to use the syntax belonging to 2.4:
https://github.com/casadi/casadi/blob/master/test/matlab/rosenbrock.m

**Comment by jgillis** [comment]
Out of curiosity, what did you do to obtain the above code for the development branch?

**Comment by nbibin001** [comment]
Hey Thanks a lot Gillis. I was able to make it to work now. I got the above code snippet from this link
https://github.com/casadi/casadi/blob/develop/test/matlab/rosenbrock.m

**Comment by jgillis** [comment]
I see, but how did you end up there? Googling? Link in our documentation?

**Comment by nbibin001** [comment]
I guess googling Casadi + Matlab

**Comment by nbibin001** [comment]
I am experimenting with this to implement an MPC framework in an embedded target. I was able to do this with mathwork's MPC toolbox. But want to try with Casadi if at all possible and compare the benefits in terms of memory and processor throughput for the embedded controller.

**Comment by jaeandersson** [comment]
There are some open source projects for doing MPC with CasADi. One is DO-MPC by Segio Lucia (https://github.com/do-mpc/do-mpc/wiki). I know that he has used it in several projects in Dortmund & Magdeburg. Another is MPC-TOOLS-CASADI by Michael Risbeck (https://hg.cae.wisc.edu/hg/mpc-tools-casadi). Michael is actually my office mate at UW-Madison at the moment.

**Comment by jaeandersson** [comment]
All classes inheriting from Function now gone - except "Callback", which will remain.
