### ISSUE TITLE
Remove ControlSimulator

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1591]
If I'm not mistaken, ControlSimulator has been superseded by the more powerful and general-purpose mapaccum operator.

**Comment by jaeandersson** [comment]
ControlSimulator is currently used in several examples: 
 * ./examples/python/simulation.py
 * ./examples/python/lqr_control.py
 * ./api/examples/integrators/controlsimulator.py
 * ./api/examples/integrators/monodromy.py (commented out due to the lack of derivative support)

@jgillis - should be easy to convert these examples to use mapaccum, right?

**Comment by jgillis** [comment]
Yes, should be easy.

**Comment by jaeandersson** [comment]
Will you do the honor?
