### ISSUE TITLE
add primitives with better numerical properties

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1595]
```
sqrt(x*x+y*y) = hypot(x,y)
log(1+x) = log1p(x)
expm1(x) = exp x - 1
```

**Comment by jaeandersson** [comment]
I didn't know about "hypot". Looks like a useful function and the derivative rule is trivial: If f = hypot(x,y), then, df/dx = 1/f.

**Comment by jaeandersson** [comment]
If you want to avoid a not-a-number, you could define the derivative rule as `x/(f + std::numeric_limits<double>::min())`...

**Comment by ghorn** [comment]
That derivative is undefined, what is casadi's policy on such things?

Either way, I would try to keep the properties of `hypot(x,y)` the same as `sqrt(x*x+y*y)`

**Comment by jaeandersson** [comment]
Policy is that 0/0 will give you a not a number. But you're never guaranteed to get not-a-number. x/x will simplify to 1, for example. Derivative of `sqrt(x*x+y*y)` will follow the chain rule, of course.For f=sqrt(x), derivative is 0.5/f, so and multiplied with 2*x, the expression may or may not simplify to x/f. So there might not be any gain.
