### ISSUE TITLE
Reimplement support for robust optimal control

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1596]
Given the major effort required to bring current classes up to date with the work vector less evaluation (#1356), the new constructor design (#1350) and the refactoring of the Function classes in CasADi (#1585), the conclusion is that it's easier to remove these classes from the trunk and reincarnate them once the refactoring of the core is completed. The reimplementation would also resolve some issues with the current code such as the need to avoid code duplication and to support derivative calculations more fully.

**Comment by jgillis** [comment]
Done in 3.1. Only the practically useful slicot dple solver was resurected and refactored.

**Comment by ghorn** [comment]
:+1:

**Comment by EveCharbie** [comment]
Hi :)

I am trying to use ```out = casadi.dplesol(A, V, "slicot")```, but I have trouble finding documentation or example helping me in the process. I only found this here https://casadi.sourceforge.net/v3.2.3/api/html/dc/d61/group__dple.html#ga1ec3c8a873d19fbc557bb4a5658c276f :
```
P_0 = A_(K-1)*P_(K-1)*A_(K-1)' + V_k
P_k+1 = A_k*P_k*A_k' + V_k  for k = 1..K-1
```
Could you please confirm my interpretation?
I consider ```state_k+1 = integration(states_k)``` using collocations, or IRK, or DMS
1. I understand that ```P_k+1 = A@P_k@A.T + V``` is the Lyapunov equation
2. A -> jacobian of state_k+1 with respect to states_k (with noise)
3. V = ```B@sigma_w@B``` : B -> jacobian of states dynamics with respect to motor noise and sigma_w -> motor_noise
Then, I am not sure how I should use the output from dplesol, is it just ```P_k+1 = P_k + casadi.dplesol(A, V, "slicot")```?

Thank you,
Eve
