### ISSUE TITLE
Random crashes on matlab+windows

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1599]
* [ ]  ~ 50 % chance on crash on a R2015a with a R2014b binary when invoking jit
* [ ] crash on my flanders make laptop with R2014b and R2014b binary when invoking jit
Does not manifest itself with the Debug mode build
```
[  0] 0x0000000020be421a C:\Users\jgls\Downloads\casadi-matlabR2014b-v2.4.1\libcasadi_compiler_clang.dll+19087898 ZN6casadi13ClangCompiler11getIncludesERKSsS2_+00000298
[  1] 0x0000000020be597b C:\Users\jgls\Downloads\casadi-matlabR2014b-v2.4.1\libcasadi_compiler_clang.dll+19093883 ZN6casadi13ClangCompiler4initEv+00002667
```
```
[  0] 0x000000007e0187aa C:\Users\jgls\Downloads\casadi-matlabR2014b-v2.4.1\casadiMEX.mexw64+00034730 SWIG_Matlab_ExitFcn+00029546
[  1] 0x000000007e124e29 C:\Users\jgls\Downloads\casadi-matlabR2014b-v2.4.1\casadiMEX.mexw64+01134121 ZN6casadi6to_ptrEP11mxArray_tagPPNS_6MatrixIiEE+00000153
[  2] 0x000000007e2d74ff C:\Users\jgls\Downloads\casadi-matlabR2014b-v2.4.1\casadiMEX.mexw64+02913535 Z34_wrap_GenericExpressionCommon_plusiPP11mxArray_tagiS1_+00000063
[  3] 0x000000007e3fc632 C:\Users\jgls\Downloads\casadi-matlabR2014b-v2.4.1\casadiMEX.mexw64+04113970 mexFunction+00009058
```
In RelWithDebug mode, the error is much rarer but still there:
```
[  0] 0x000000002487421a C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi_compiler_clang.dll+19087898 ZN6casadi13ClangCompiler11getIncludesERKSsS2_+00000298
[  1] 0x000000002487597b C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi_compiler_clang.dll+19093883 ZN6casadi13ClangCompiler4initEv+00002667
[  2] 0x00000000a4602c1d C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi.dll+00011293 ZN6casadi12SharedObject4initEb+00000029
[  3] 0x00000000a47ec676 C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi.dll+02016886 ZN6casadi8CompilerC2ERKSsS2_RKSt3mapISsNS_11GenericTypeESt4lessISsESaISt4pairIS1_S4_EEE+00000214
[  4] 0x00000000a46f78a6 C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi.dll+01013926 ZN6casadi16FunctionInternal8finalizeEv+00000550
[  5] 0x00000000a473d5de C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi.dll+01299934 ZN6casadi10MXFunction9constructERKSsRKSt6vectorINS_2MXESaIS4_EES8_RKSt3mapISsNS_11GenericTypeESt4lessISsESaISt4pairIS1_SA_EEERKS3_ISsSaISsEESM_+00000670
[  6] 0x00000000a473d848 C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\libcasadi.dll+01300552 ZN6casadi10MXFunctionC2ERKSsRKSt6vectorINS_2MXESaIS4_EES8_RKSt3mapISsNS_11GenericTypeESt4lessISsESaISt4pairIS1_SA_EEE+00000296
[  7] 0x00000000a42c7021 C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\casadiMEX.mexw64+02912289 Z28_wrap_new_MXFunction__SWIG_2iPP11mxArray_tagiS1_+00001505
[  8] 0x00000000a42d70cd C:\Users\jgls\Downloads\casadi-matlabR2014b-c26c724-dsym\casadiMEX.mexw64+02977997 Z20_wrap_new_MXFunctioniPP11mxArray_tagiS1_+00000317
```

**Comment by jaeandersson** [comment]
Ouch, what kind of crashes?

**Comment by jgillis** [comment]
segfaults

**Comment by jgillis** [comment]
To try: make a RelWithDebInfo build

**Comment by jgillis** [comment]
The error does not occur on Python-64 bit windows.

**Comment by jgillis** [comment]
After checking if the system_includes file exist, there still seems to be some error:
MATLAB crash file:C:\Users\jgillis\AppData\Local\Temp\matlab_crash_dump.2036-1:


------------------------------------------------------------------------
          Access violation detected at Mon Oct 19 03:00:21 2015
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Default Encoding   : windows-1252
  Graphics card 1    : Oracle Corporation ( 0x80ee ) VirtualBox Graphics Adapter Version 4.3.18.0
  MATLAB Architecture: win64
  MATLAB Root        : c:\Program Files\MATLAB\R2014b
  MATLAB Version     : 8.4.0.150421 (R2014b)
  Operating System   : Microsoft Windows 7 Professional N 
  Processor ID       : x86 Family 6 Model 69 Stepping 1, GenuineIntel
  Software OpenGL    : 0
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : Version 6.1 (Build 7601: Service Pack 1)

Fault Count: 1


Abnormal termination:
Access violation

Register State (from fault):
  RAX = 00000000727a3000  RBX = 00000000727a1a6f
  RCX = 0000000000000000  RDX = 000000000000002c
  RSP = 000000000401c130  RBP = 00000000727a2c74
  RSI = 0000000081333a20  RDI = 0000000032696d08
 
   R8 = 000000000000001c   R9 = 0000000000000000
  R10 = 0000000000000000  R11 = 0000000082f93d10
  R12 = 0000000000011a6f  R13 = 0000000000000001
  R14 = 00000000000064df  R15 = 0000000000000001
 
  RIP = 000000008207ccdd  EFL = 00010216
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x000000008207ccdd E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08703197
[  1] 0x000000008207f887 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08714375
[  2] 0x0000000082082ed8 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08728280
[  3] 0x0000000081876b52 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+00289618
[  4] 0x0000000081847dd4 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+00097748
[  5] 0x0000000082073044 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08663108
[  6] 0x00000000820732ee E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08663790
[  7] 0x000000008207404c E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08667212
[  8] 0x000000008204b499 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08500377
[  9] 0x000000008202153f E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+08328511
[ 10] 0x0000000082a5db32 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+19061554
[ 11] 0x0000000081b5f3c9 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+03339209
[ 12] 0x0000000081b5fba0 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+03341216
[ 13] 0x0000000081affdcb E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+02948555
[ 14] 0x0000000081b17a27 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+03045927
[ 15] 0x0000000081afd960 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+02939232
[ 16] 0x0000000081afe000 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+02940928
[ 17] 0x0000000081b01d5c E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+02956636
[ 18] 0x0000000081b02513 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+02958611
[ 19] 0x0000000081af913d E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+02920765
[ 20] 0x000000008185055b E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+00132443
[ 21] 0x0000000081843945 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+00080197
[ 22] 0x0000000082a67468 E:\casadi-matlabR2014b-e31bacb\libcasadi_compiler_clang.dll+19100776 ZN6casadi13ClangCompiler4initEv+00006104
[ 23] 0x000000007e032e7d       E:\casadi-matlabR2014b-e31bacb\libcasadi.dll+00011901 ZN6casadi12SharedObject4initEb+00000029
[ 24] 0x000000007e25ec56       E:\casadi-matlabR2014b-e31bacb\libcasadi.dll+02288726 ZN6casadi8CompilerC2ERKSsS2_RKSt3mapISsNS_11GenericTypeESt4lessISsESaISt4pairIS1_S4_EEE+00000214
[ 25] 0x000000007e129286       E:\casadi-matlabR2014b-e31bacb\libcasadi.dll+01020550 ZN6casadi16FunctionInternal8postinitEv+00000550
[ 26] 0x000000007e16fb3e       E:\casadi-matlabR2014b-e31bacb\libcasadi.dll+01309502 ZN6casadi10MXFunction9constructERKSsRKSt6vectorINS_2MXESaIS4_EES8_RKSt3mapISsNS_11GenericTypeESt4lessISsESaISt4pairIS1_SA_EEERKS3_ISsSaISsEESM_+00000670
[ 27] 0x000000007e16fda8       E:\casadi-matlabR2014b-e31bacb\libcasadi.dll+01310120 ZN6casadi10MXFunctionC1ERKSsRKSt6vectorINS_2MXESaIS4_EES8_RKSt3mapISsNS_11GenericTypeESt4lessISsESaISt4pairIS1_SA_EEE+00000296
[ 28] 0x000000007639e5a1    E:\casadi-matlabR2014b-e31bacb\casadiMEX.mexw64+02418081 Z28_wrap_new_MXFunction__SWIG_2iPP11mxArray_tagiS1_+00001473
[ 29] 0x000000007643dd3d    E:\casadi-matlabR2014b-e31bacb\casadiMEX.mexw64+03071293 Z20_wrap_new_MXFunctioniPP11mxArray_tagiS1_+00000461
[ 30] 0x000000007653404f    E:\casadi-matlabR2014b-e31bacb\casadiMEX.mexw64+04079695 mexFunction+00009295
[ 31] 0x00000000fc5f3701 c:\Program Files\MATLAB\R2014b\bin\win64\libmex.dll+00079617 mexRunMexFile+00000129
[ 32] 0x00000000fc5f2762 c:\Program Files\MATLAB\R2014b\bin\win64\libmex.dll+00075618 inSwapMexfileReader+00000690
[ 33] 0x00000000fc5f2248 c:\Program Files\MATLAB\R2014b\bin\win64\libmex.dll+00074312 mexUnlock+00006008
[ 34] 0x00000000043005e3 c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067043 Mfh_file::dispatch_fh+00000659
[ 35] 0x0000000004300aee c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 36] 0x0000000004e92b2f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00273199 inGetNameInSymbolTable+00017071
[ 37] 0x0000000004e940c0 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00278720 inGetNameInSymbolTable+00022592
[ 38] 0x0000000004e91b4f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 39] 0x0000000004e91ab1 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 40] 0x0000000004eb406f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 41] 0x0000000004eb27af c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 42] 0x0000000004eb1359 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 43] 0x00000000043005e3 c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067043 Mfh_file::dispatch_fh+00000659
[ 44] 0x0000000004300aee c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 45] 0x000000000596f2d6  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00127702 mcos::COSInterfacePtr::operator=+00005350
[ 46] 0x000000000596f13f  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00127295 mcos::COSInterfacePtr::operator=+00004943
[ 47] 0x000000000596b695  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00112277 omDoesClassImplementSubsasgn+00001141
[ 48] 0x000000000597ea81  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00191105 mcos::COSJITInterface::isClassHandle+00001473
[ 49] 0x000000000597e096  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00188566 mcos::COSJITInterface::getDispatcherID+00006182
[ 50] 0x000000000596ed9e  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00126366 mcos::COSInterfacePtr::operator=+00004014
[ 51] 0x000000000596ee60  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00126560 mcos::COSInterfacePtr::operator=+00004208
[ 52] 0x000000000596cdba  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00118202 omDoesClassImplementSubsref+00003994
[ 53] 0x000000000596c85e  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00116830 omDoesClassImplementSubsref+00002622
[ 54] 0x000000000596c7e6  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00116710 omDoesClassImplementSubsref+00002502
[ 55] 0x0000000004300d54 c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068948 Mfh_MATLAB_fn::dispatch_fh+00000452
[ 56] 0x00000000059a116d  c:\Program Files\MATLAB\R2014b\bin\win64\mcos.dll+00332141 omUnmarkArrayForAssignment+00000525
[ 57] 0x0000000004300aee c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 58] 0x0000000004e92b2f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00273199 inGetNameInSymbolTable+00017071
[ 59] 0x0000000004f7b6f7 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01226487 inFullEvalFcn+00011159
[ 60] 0x0000000004e95592 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00284050 inGetNameInSymbolTable+00027922
[ 61] 0x0000000004e91b4f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 62] 0x0000000004e91ab1 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 63] 0x0000000004eb406f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 64] 0x0000000004eb27af c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 65] 0x0000000004eb1359 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 66] 0x00000000043007a4 c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067492 Mfh_file::dispatch_fh+00001108
[ 67] 0x0000000004300aee c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 68] 0x0000000004e92b2f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00273199 inGetNameInSymbolTable+00017071
[ 69] 0x0000000004f7b6f7 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01226487 inFullEvalFcn+00011159
[ 70] 0x0000000004e95592 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00284050 inGetNameInSymbolTable+00027922
[ 71] 0x0000000004e91b4f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00269135 inGetNameInSymbolTable+00013007
[ 72] 0x0000000004e91ab1 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00268977 inGetNameInSymbolTable+00012849
[ 73] 0x0000000004eb406f c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00409711 inPathNotification::function_delete_notification+00098591
[ 74] 0x0000000004eb27af c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00403375 inPathNotification::function_delete_notification+00092255
[ 75] 0x0000000004eb1359 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00398169 inPathNotification::function_delete_notification+00087049
[ 76] 0x00000000043007a4 c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00067492 Mfh_file::dispatch_fh+00001108
[ 77] 0x0000000004300aee c:\Program Files\MATLAB\R2014b\bin\win64\m_dispatcher.dll+00068334 Mfunction_handle::dispatch+00000766
[ 78] 0x0000000004ee4a88 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608904 inPathNotification::function_delete_notification+00297784
[ 79] 0x0000000004ee4a04 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608772 inPathNotification::function_delete_notification+00297652
[ 80] 0x0000000004ee49c5 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608709 inPathNotification::function_delete_notification+00297589
[ 81] 0x0000000004ee4992 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608658 inPathNotification::function_delete_notification+00297538
[ 82] 0x0000000004ee4947 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00608583 inPathNotification::function_delete_notification+00297463
[ 83] 0x0000000004e5d69d c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+00054941 inEvalExp+00001309
[ 84] 0x0000000004f8525d c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01266269 inEvalCmdWithLocalReturn+00000285
[ 85] 0x0000000004f85181 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01266049 inEvalCmdWithLocalReturn+00000065
[ 86] 0x0000000004f85005 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01265669 inEvalCmdWithLocalReturnInDesiredWSAndPublishEvents+00000197
[ 87] 0x0000000004f84f82 c:\Program Files\MATLAB\R2014b\bin\win64\m_interpreter.dll+01265538 inEvalCmdWithLocalReturnInDesiredWSAndPublishEvents+00000066
[ 88] 0x0000000004d8865a   c:\Program Files\MATLAB\R2014b\bin\win64\iqm.dll+00296538 iqm::InternalEvalPlugin::inEvalCmdWithLocalReturn+00000170
[ 89] 0x0000000004d882cc   c:\Program Files\MATLAB\R2014b\bin\win64\iqm.dll+00295628 iqm::InternalEvalPlugin::execute+00000252
[ 90] 0x00000000fd0b6c50   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00224336 mcrRegisterExternalFunction+00013184
[ 91] 0x0000000004d741fa   c:\Program Files\MATLAB\R2014b\bin\win64\iqm.dll+00213498 iqm::Iqm::setupIqmFcnPtrs+00026106
[ 92] 0x0000000004d740e6   c:\Program Files\MATLAB\R2014b\bin\win64\iqm.dll+00213222 iqm::Iqm::setupIqmFcnPtrs+00025830
[ 93] 0x0000000004d64329   c:\Program Files\MATLAB\R2014b\bin\win64\iqm.dll+00148265 iqm::Iqm::deliver+00001113
[ 94] 0x00000000064d8558 c:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00034136 ioReadLine+00000280
[ 95] 0x00000000064d8362 c:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00033634 ioCmdLineEditSave+00011986
[ 96] 0x00000000064d842b c:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00033835 ioReadLine+00000107
[ 97] 0x00000000064de956 c:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00059734 mnDebugPrompt+00001510
[ 98] 0x00000000064de48a c:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00058506 mnDebugPrompt+00000282
[ 99] 0x00000000064debee c:\Program Files\MATLAB\R2014b\bin\win64\libmwbridge.dll+00060398 mnParser+00000462
[100] 0x00000000fd0dd834   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00383028 mcrInstance::mnParser_on_interpreter_thread+00000036
[101] 0x00000000fd0a68e7   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00157927 mcr::runtime::setInterpreterThreadToCurrent+00019751
[102] 0x00000000fd0a6923   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00157987 mcr::runtime::setInterpreterThreadToCurrent+00019811
[103] 0x00000000fd0a7121   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00160033 mcr::runtime::setInterpreterThreadToCurrent+00021857
[104] 0x00000000fab5d3a6   c:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00512934 UIW_AttachThreadInput+00001270
[105] 0x00000000fab5cc35   c:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00511029 wsd_to_MSW+00004373
[106] 0x00000000fab5ccb9   c:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00511161 wsd_to_MSW+00004505
[107] 0x0000000076a6d67a                     C:\Windows\system32\USER32.dll+00579194 CreateWindowExA+00000894
[108] 0x0000000076a2136b                     C:\Windows\system32\USER32.dll+00267115 DdeDisconnectList+00002619
[109] 0x0000000076a22ab4                     C:\Windows\system32\USER32.dll+00273076 DdeDisconnectList+00008580
[110] 0x0000000076d1c82f                      C:\Windows\SYSTEM32\ntdll.dll+00968751 KiUserCallbackDispatcher+00000031
[111] 0x0000000076a7e00a                     C:\Windows\system32\USER32.dll+00647178 VTagOutput+00002730
[112] 0x0000000076a5aa9d                     C:\Windows\system32\USER32.dll+00502429 OpenClipboard+00000233
[113] 0x0000000076a6dc9d                     C:\Windows\system32\USER32.dll+00580765 PeekMessageA+00000509
[114] 0x00000000fab0a26b   c:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00172651 UIW_ShowMenuItem+00003995
[115] 0x00000000fab5dce2   c:\Program Files\MATLAB\R2014b\bin\win64\uiw.dll+00515298 UIW_SuspendAttachThreadInput+00000466
[116] 0x0000000100118223 c:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01212963 services::system_events::PpeDispatchHook::dispatchOne+00032291
[117] 0x0000000100123c95 c:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01260693 sysq::addProcessPendingEventsUnitTestHook+00005813
[118] 0x0000000100123d50 c:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01260880 sysq::addProcessPendingEventsUnitTestHook+00006000
[119] 0x0000000100125b75 c:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01268597 sysq::getCondition+00004629
[120] 0x00000001001274ba c:\Program Files\MATLAB\R2014b\bin\win64\libmwservices.dll+01275066 svWS_ProcessPendingEvents+00000138
[121] 0x00000000fd0a783d   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00161853 mcr::runtime::setInterpreterThreadToCurrent+00023677
[122] 0x00000000fd0a84aa   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00165034 mcr::runtime::setInterpreterThreadToCurrent+00026858
[123] 0x00000000fd0a0135   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00131381 mcr_process_events+00007477
[124] 0x00000000fd0a1a12   c:\Program Files\MATLAB\R2014b\bin\win64\mcr.dll+00137746 mcr_process_events+00013842
[125] 0x0000000006808f2d c:\Program Files\MATLAB\R2014b\bin\win64\MVMLocal.dll+00167725 mvm_server::inproc::LocalFactory::terminate+00048285
[126] 0x00000000fa8ef1ea   c:\Program Files\MATLAB\R2014b\bin\win64\mvm.dll+00782826 mvm::detail::initLocalMvmHack+00000490
[127] 0x00000000fa8ef7a8   c:\Program Files\MATLAB\R2014b\bin\win64\mvm.dll+00784296 mvm::detail::SessionImpl::privateSession+00000376


This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

**Comment by jgillis** [comment]
Fixed as per https://github.com/casadi/binaries/commit/343fbc93c76d0ac3f6e5a6dab37dc601339f3339
