### ISSUE TITLE
Refactor CustomFunction

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1601]
The CustomFunction, DerivativeGenerator, Functor, PyFunction, Callback etc functions need consolidation. A single class, with the same syntax in C++ and Python/MATLAB should be enough if making use of directors in SWIG.

**Comment by jaeandersson** [comment]
New design complete. @jgillis - could you have a look and give feedback? The idea of the new Callback class is to expose a *selected* subset of virtual functions from FunctionInternal.

Most unit tests have been removed (they were very specific to the old design) so migrating was not easy.

**Comment by jaeandersson** [comment]
Note that the user is responsible for not deleting the Callback class. Once it is deleted, lingering references to it will fail (hopefully gracefully, with an assertion error) if one tries to use them. I think that this is the cleanest approach, and avoids having to do hacks with the reference counting in Python/MATLAB.

**Comment by jgillis** [comment]
I'm not sure I like the user having the responsibility for keeping it in reference.
In practice, this would mean that the user is going to write hacky code, using global most likely.

**Comment by jgillis** [comment]
Looks good. I'm re-adding unittests...

**Comment by jaeandersson** [comment]
About ownership, the most important is to avoid circular dependencies. I think it is very dangerous to delete the public class from the internal class. Just adding something to a memory pool shouldn't be hard or need global variables. I'm open for other designs, but to have clear ownership is for me absolutely critical.

I removed DerivativeGenerator completely, I don't think it makes sense to keep this functionality in anyway. It provides a way to hack the behaviour of the built-in classes that I don't think is needed and that can have unexpected results. Better simply to say that the user overrides everything or nothing. Or makes a patch and a pull request.
 
Note that Callback is used for everything now, also for NLP function callbacks. This results in a pretty ugly syntax, so there is definitely the need for some helper class for NLP callback functions.
