### ISSUE TITLE
codegenerator should produce the same code if you generate a string or write a file

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1605]
Right now the string version cannot be compiled. It's missing CODEGEN_PREFIX and real_t at least

**Comment by jaeandersson** [comment]
:+1:

**Comment by jaeandersson** [comment]
@ghorn I've separated `CodeGenerator::dump` (just output the C source) from `CodeGenerator::generate` (output the file(s), possibly including header file). It's a non-backwards compatible change, but relatively minor.
