### ISSUE TITLE
codegen generate_main seems to be broken

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1607]

**Comment by ghorn** [comment]
seems to be generating `"main_eval"` instead of `fname + "_eval"`

also seems to be generating `w%d` instead of `&(w[%d])`

**Comment by jaeandersson** [comment]
It's not unit tested and has to my knowledge never been used... so it's not entirely surprising...

**Comment by ghorn** [comment]
I use it...

**Comment by jaeandersson** [comment]
Fixed.
