### ISSUE TITLE
ExternalFunction should take the name of a shared library location

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1608]
This is an opinion, not a bug.

Right now the `ExternalFunction` constructor does:
```C++
ExternalFunction::ExternalFunction(const string& name, const Dict& opts) {
  assignNode(ExternalFunctionInternal::create("./" + name + ".so", name));
```

I propose to change to
```C++
ExternalFunction::ExternalFunction(const string& name, const Dict& opts) {
  assignNode(ExternalFunctionInternal::create(name, name));
```

The user has just compiled the shared library, so they know what it's called and where it is. If the user wants high-level automation, they can use the JIT functionality.

**Comment by jaeandersson** [comment]
This has to be cleaned up in general. So I agree that the current design is bad. Anyway, did you notice that there is another constructor that takes both function name and library name?

**Comment by ghorn** [comment]
I didn't notice.

**Comment by jaeandersson** [comment]
".so" ending by default on Windows makes no sense anyway.
This simplified constructor is intended to match the code that you get when using the shorthand notation for codegen, i.e. `f.generate()` instead of creating ´CodeGenerator` objects.

**Comment by jaeandersson** [comment]
I think this has been resolved. If not, reopen.
