### ISSUE TITLE
CodeGenerator::generate and Function::generate name sanitization discards path information

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1609]
If I try to generate code in a different directory, the separators `/` are turned into underscores and the code is generated in the current working directory.

**Comment by jaeandersson** [comment]
On related note, "name sanitization" should go away IMO: #1588.
If you don't name your function object in a way so that it is not a valid symbol name, it should throw an error.

**Comment by jaeandersson** [comment]
Reopen, with an example snippet if needed.
