### ISSUE TITLE
Clean use of CasADi as a SWIG module

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1613]
After #1559, it should be possible (again) to extend CasADi's C++ API and generate extensions for MATLAB/Python using the multiple modules feature.

The implementation requires some hacks, which should be removed for maintainability. Futhermore, the required interface information (in particular casadi.i), should be generated along with the CasADi headers, i.e. it should not be needed to checkout CasADi from sources to use this feature.

**Comment by jaeandersson** [comment]
Helpful simplifications: #1629 #1630.

**Comment by jgillis** [comment]
:+1: 
"should be generated" -> you mean copied to the install directory?

**Comment by jaeandersson** [comment]
> you mean copied to the install directory

Right, that's what I meant.

**Comment by jaeandersson** [comment]
Reopen if needed.
