### ISSUE TITLE
substitute in c++ requires cast of dmatrix

### ISSUE THREAD

**Issue by nielsvd** [casadi/casadi#1614]
In casadi 2.3 the following syntax would work:
```
substitute(  SX  , SX  ,  DMatrix::zeros(  x  )  )
```

In casadi 2.4, this wil result in a compiler error:
```
error: call of overloaded ‘substitute(casadi::SX&, casadi::SX&, casadi::Matrix<double>)’ is ambiguous
```

The problem is circumvented by casting the DMatrix into an SX.

**Comment by jaeandersson** [comment]
This is surprising. Can you provide more of the error message? I don't see how the above would match any overload other than 
```c++
    friend inline MatType substitute(const MatType& ex, const MatType& v,
                                     const MatType& vdef) {

```
with `MatType` being `SX`.

**Comment by nielsvd** [comment]
Code:
```
  SX a = SX::sym("a",3);
  SX b = substitute(pow(a,2),a,DMatrix::zeros(3));
```

Error (gcc 5.2.0):
```
subs_test.cpp: In function ‘int main()’:
subs_test.cpp:9:49: error: call of overloaded ‘substitute(casadi::Matrix<casadi::SXElement>, casadi::SX&, casadi::Matrix<double>)’ is ambiguous
   SX b = substitute(pow(a,2),a,DMatrix::zeros(3));
                                                 ^
In file included from /usr/local/include/casadi/core/matrix/matrix.hpp:36:0,
                 from /usr/local/include/casadi/core/sx/sx_element.hpp:33,
                 from /usr/local/include/casadi/core/core.hpp:30,
                 from /usr/local/include/casadi/casadi.hpp:29,
                 from subs_test.cpp:1:
/usr/local/include/casadi/core/matrix/generic_matrix.hpp:441:27: note: candidate: casadi::Matrix<casadi::SXElement> casadi::substitute(const casadi::Matrix<casadi::SXElement>&, const casadi::Matrix<casadi::SXElement>&, const casadi::Matrix<casadi::SXElement>&)
     friend inline MatType substitute(const MatType& ex, const MatType& v,
                           ^
/usr/local/include/casadi/core/matrix/generic_matrix.hpp:441:27: note: candidate: casadi::Matrix<double> casadi::substitute(const casadi::Matrix<double>&, const casadi::Matrix<double>&, const casadi::Matrix<double>&)
```

**Comment by jaeandersson** [comment]
The problem is the the following constructor, which allows implicit type conversion for both DMatrix->SX and SX->DMatrix.
```c++
    template<typename A>
    Matrix(const Matrix<A>& x) : sparsity_(x.sparsity()), data_(std::vector<DataType>(x.nnz())) {
      copy(x.begin(), x.end(), begin());
    }
```

**Comment by jgillis** [comment]
Why is substitute even defined for dmatrix?

**Comment by jaeandersson** [comment]
> Why is substitute even defined for dmatrix?

It's defined as a friend function in Matrix, as part of the new design. It means that it gets instantiated for all Matrix instantiations, including `Matrix<double>`.

Anyway, the problem is unrelated to substitute. You'll get the same issue for any function which is defined for both `DMatrix` and `SX`. Probably also e.g. `mul(SX, DMatrix)`, which could match either `mul(SX, SX)` or `mul(DMatrix, DMatrix)`. The fundamental problem is that `SX` automatically type converts to `DMatrix`, since that constructor is not explicit.

It should be fixable, but it's more complicated than simply adding `explicit`, since that constructor is also used for e.g. `DMatrix`-to- `SX` conversion, which should remain implicit.

**Comment by jaeandersson** [comment]
Actually, it could be a new issue, related to the addition of explicit type conversion in `SXElement`:
```c++
    /// Type conversion to double
    inline explicit operator double() const { return getValue();}
```
If so, it should be easy to fix.

**Comment by jaeandersson** [comment]
Maybe not so easy... Anyway I guess the goal should be to have the following type conversions:
 * Implicit: DMatrix-to-SX, IMatrix-to-SX, IMatrix-to-DMatrix
 * Explicit: SX-to-DMatrix, SX-to-IMatrix, DMatrix-to-IMatrix

**Comment by jaeandersson** [comment]
Reopen if problem still persists.
