### ISSUE TITLE
Broken printing of if_else expressions

### ISSUE THREAD

**Issue by toivoh** [casadi/casadi#1618]
With CasADi 2.4.0 I get strange results when trying to print `if_else` expressions where the consequent or alternative are constants. It seems that printing just leaves these out in those cases. For example,

    from casadi import *
    x,y,z = map(MX.sym,"xyz")
    print if_else(x,y,z)
    print if_else(x,1,z)
    print if_else(x,y,2)
    print if_else(x,1,2)

prints

    if_else(x, y, z){0}
    if_else(x, z){0}
    if_else(x, y){0}
    if_else(x){0}

**Comment by jaeandersson** [comment]
OK, thanks for reporting.

**Comment by jaeandersson** [comment]
It's not really broken. "if_else" is the name of the "if-else" function. So what is being printed is a function call.

**Comment by toivoh** [comment]
Yes, but why do some of the arguments to the function call sometimes disappear from the printing? That was my issue.

**Comment by jaeandersson** [comment]
Ah, I see. It just lists all of the symbolic primitives the function depends on in no particular order.

**Comment by toivoh** [comment]
But you agree that it would be better if the printout would allow you to figure out both the condition, consequent, and alternative?

**Comment by jaeandersson** [comment]
A conditional in CasADi is a function so what you see is a function call. Arguably, the function being called should be output as well, but I don't see why a the "conditional" should be handled any different to other function calls.

**Comment by jaeandersson** [comment]
Cf. #1553

**Comment by toivoh** [comment]
I agree completely, but I don't understand why `f(x,1,2)` should print like `f(x)` for any function, `else_if` included.

**Comment by jaeandersson** [comment]
Because it breaks down the true/false expressions into symbolic primitives. And x is a symbolic primitive whereas 1 and 2 are not. So 1 and 2 will be used to define the constructed function, but won't need to be passed to it.

**Comment by toivoh** [comment]
That may be the case, but when I print an expression, as a user, I still
want to be able to see what it does?

**Comment by jaeandersson** [comment]
What you see is a function call to a function that depends only on x. The name of the function is "if_else"... If you want to see what is really being calculated, it's best to do C code generation.

**Comment by toivoh** [comment]
So when you referred to the `if_else` function above, what you actually meant was that when I call the function `if_else` in CasADi, it now generates another function called `if_else`, which is specialized on some of the input arguments, so that the printouts `if_else(x, y, z){0}` and `if_else(x, y){0}` actually refer to different functions? That not at all obvious to me.

Now that I (think I) understand what is going on, I understand why it prints like it does. But is this not really an implementation detail? This surely confused me in debugging CasADi code, and I'm sure it will confuse others as well.

I understand if you won't do it because it's too much work or overhead, but seeing as `if_else` apparently _is_ a special case in that it generates specialized functions (or does this happen in general?), I think that it would be preferable to special case the printing of calls to those specialized functions so that the call 

    if_else(x, y){0}

would print as

    if_else(x, y, 2){0}

instead, by inserting the implicit argument `2` into the printout. I think that this would communicate perfectly what is being calculated, in a very compact format.

**Comment by jaeandersson** [comment]
If we were to start printing things like "if_else(x, y, 2){0}" instead of "if_else(x, y){0}", would open a can of worms. Currently, the rule for printing is very simple, but if you start making special cases you end up with something unmaintainable. What you really want is a refactoring of the printing algorithm, where "if_else" is defined as an intermediate function. This is more or less what you get if you try to do C code generation.

**Comment by jaeandersson** [comment]
Another, much simpler thing you could do is to change the name of the generated function from "if_else" to something else. Like "if_else_wrap" or something.

**Comment by toivoh** [comment]
Ok, thanks for clarifying. Yes, just changing the name when you generate a function that does not work like the original `if_else` would be an improvement to reduce confusion.

**Comment by jaeandersson** [comment]
I changed the default name to "switch". There is no CasADi function with that name. The name of the corresponding class is called Switch, hence the name. Switch handles both "if_else" and "conditional" (an "if_else" is just a Switch with one case plus the default case).

**Comment by toivoh** [comment]
Thanks!
