### ISSUE TITLE
repmat(x,1,n) doesn't simplify anymore

### ISSUE THREAD

**Issue by toivoh** [casadi/casadi#1619]
With CasADi 2.4.0, it seems that `repmat` does not simplify in some very simple cases. The code

    from casadi import *
    x = MX.sym("x")
    print repmat(x,1,1)
    print repmat(x,1,2)
    print repmat(x,2,1)

prints

    repmat(x, 1)
    repmat(x, 2)
    vertcat(x, x)

so it seems that `repmat` does not simplify when the first count is one. With CasADi 2.1, I got

    MX(x)
    MX(horzcat(x, x))
    MX(vertcat(x, x))

instead.

**Comment by jaeandersson** [comment]
Thanks for reporting!
