### ISSUE TITLE
Type maps for std::vector<double> don't recognize empty list

### ISSUE THREAD

**Issue by toivoh** [casadi/casadi#1621]
This is causing trouble in JModelica.org, since we have some functions in the Python swig module that take `std::vector<double>` arguments, and we inherit the type maps defined in CasADi's swig module. It was not so easy to find an example in CasADi itself that demonstrates the problem, but in CasADi 2.4.0, the code

```
from casadi import *
collocationInterpolators([0,1])
collocationInterpolators([0])
collocationInterpolators([])
```

gives an error on the last line:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toivo/jmodelica.org/jmodelica.org2/install/Python/casadi/casadi.py", line 35876, in collocationInterpolators
    return _casadi.collocationInterpolators(*args)
TypeError: Failed to convert input to [double].
You have: ([])
```

It seems to me that an empty Python list should always be accepted to be converted into an empty `std::vector<double>`. Hopefully this is a pretty simple fix. Or is there a reason it was not done this way?

**Comment by jaeandersson** [comment]
Should be pretty easy to fix (by modifying the casadi_vector fragment in casad.i). We are moving away from having `std::vector<double>` in the public API, as part of making the API more minimalistic, that's probably why it wasn't detected.

**Comment by toivoh** [comment]
I'm not using the type map anymore, so this is not pressing on my part.

**Comment by jaeandersson** [comment]
Reopen if needed
