### ISSUE TITLE
Request: Make out type map for `std::vector<double>` produce an `ndarray` in Python

### ISSUE THREAD

**Issue by toivoh** [casadi/casadi#1622]
CasADi's out type maps for `std::vector<double>` currently map to Python lists filled with floats on the Python side. This affects us in JModelica.org, since we have some functions in the Python swig module that return `std::vector<double>` arguments, which we would like to become numpy `ndarray` objects in Python, and we inherit the type maps defined in CasADi's swig module.

Would it be possible to change the type map to produce ndarrays on the Python side, or provide a way to disable it in `casadi.i` so that we can define our own?

There's not many functions in CasADi that return an `std::vector<double>`, but as a demonstration, in CasADi 2.4.0

    from casadi import *
    print type(collocationPoints(3))

prints

    <type 'list'>

**Comment by jaeandersson** [comment]
I think we want to remove the typemaps for `vector<double>` altogether in CasADi. We have our `DMatrix` type, which works fine for vectors, so there is no good reason to keep `vector<double>` in the public API. It just means extra maintenance and more failure modes.

Anyway, you should be able to redefine any typemap (including this one). You can clear existing typemaps for a type or overwrite typemaps before you use them.

**Comment by jaeandersson** [comment]
Anyway, I don't think having the output typemap be ndarray makes sense (it the typemap is to be kept in the first place). But this shouldn't be a blocker for you since you can always redefine the typemaps as mentioned above.

**Comment by toivoh** [comment]
Yes, I see that this wouldn't make sense to you. Anyway, I was able to redefine the typemap, so it all worked out. Thanks for the tip!
