### ISSUE TITLE
Caching of codegen-and-compile

### ISSUE THREAD

**Issue by kurtgeebelen** [casadi/casadi#1627]
@jgillis Please make it faster

**Comment by jaeandersson** [comment]
Compilation should be fast enough without caching. And I don't see how caching is possible without polluting the work directory.

**Comment by kurtgeebelen** [comment]
Can't you put it in a hidden folder in the work directory? Or like @ghorn did in rawesome, in a hidden folder in the home directory?

**Comment by jaeandersson** [comment]
> Can't you put it in a hidden folder in the work directory?

You mean the temporary files? They should be placed in a system-designated temporary directory (typically `/tmp`). They should also be deleted, which is currently not the case: https://github.com/casadi/casadi/issues/1570.

**Comment by jaeandersson** [comment]
Ah, now I understand. You mean the cache.

I'm not convinced this is a good approach. Too error prone. I'd rather investigate why the compilation isn't fast enough for you.

**Comment by jgillis** [comment]
Perhaps its a simple as using ccache:
```
{"compiler": "shell", "jit": True, "jit_options": {"compiler": "ccache gcc","flags": ["-O3"]}}
```

**Comment by jaeandersson** [comment]
If that works, it's a pretty elegant solution.

**Comment by jgillis** [comment]
Sadly, ccache will not work for a one-shot compilation+linking.
It only works with a "-c" compile flag.

**Comment by jgillis** [comment]
Solution: https://gist.github.com/jgillis/3dfd5b491ec733f01d8e
