### ISSUE TITLE
Reimplement options existance checking

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1637]
With the redesign of `Function`, the full list of options will no longer be stored in every object instance. It is still useful to be query if an option exist, to provide a proper error message should an option be misspelled.

This would only concern the names, the type, default value and description would be stored (only) in the docstring.

The implementation could be placed in virtual functions inside the `FunctionInternal` derived classes:
```c++
class FunctionInternal {
...
  virtual bool has_option(const std::string& n) {
    static std::set<std::string> opts = {"verbose", "ad_weight", "ad_weight_sp", "jac_penalty", ... };
    return opts::count(n);
 }
};

class NlpSolver : public FunctionInternal {
...
  virtual bool has_option(const std::string& n) {
    if (FunctionInternal::has_option(n)) return true;
    static std::set<std::string> opts = {"iteration_callback", "eval_errors_fatal", ...}
    return opts::count(n);
 }
};

class IpoptInterface : public NlpSolver {
...
  virtual bool has_option(const std::string& n) {
    if (NlpSolver::has_option(n)) return true;
   ....
   /* check if valid option in ipopt */
   ...
 }
};

```

This function would be called during the init step.

**Comment by jgillis** [comment]
I would say hand-maintaining two separate lists (list of names here and a list of names+types+descr in the docstring) is unmainainable.

**Comment by jaeandersson** [comment]
New design is now in place. Should be much more memory efficient and hopefully more maintainable.
