### ISSUE TITLE
lookup table support

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1638]
GSL 2.0 supports 1D and 2D lookup tables. I believe both support continuous derivatives up to 2nd order, which would make them suitable for many optimization problems.

http://www.gnu.org/software/gsl/manual/html_node/2D-Higher_002dlevel-Interface.html#g_t2D-Higher_002dlevel-Interface

It would be great to have built-in support for this.

**Comment by jaeandersson** [comment]
:+1: 

Since GSL is GPL, the code would have to be interfaced of course.

**Comment by ghorn** [comment]
It might be better to just roll our own version. How hard can bicubic interpolation be?

**Comment by jaeandersson** [comment]
I do think it makes sense to make our own version. This is the issue for this: #1484.
