### ISSUE TITLE
Matlab missing function: sum

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1641]
```
sum(MX.sym('x'))
```

**Comment by jaeandersson** [comment]
Related: I think `sumRow` and `sumCol` should be renamed `sum1` and `sum2`. We already have e.g. `size1` and `size2`. Furthermore, `size1(A)` is more strongly typed and less error prone than `sum(A, 1)` and `sum(A, 2)`.

**Comment by jgillis** [comment]
ping @jaeandersson

**Comment by jaeandersson** [comment]
I did the renaming "sumRows -> sum1", "sumCols -> sum2". But for "sum", I'm not sure. It's a built-in routine in Python and in MATLAB, it behaves differently for single row (sum row) multiple rows (sum columns), which creates confusion.
