### ISSUE TITLE
Reimplement profiling support (if needed)

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1644]
The current profiling is not implemented in a maintainable way. If the functionality is needed (questionable now that code generation is getting better and better), it should be possible to reimplement with a fraction of the code.

**Comment by jaeandersson** [comment]
To clarify: The current profiling is done on a much too low level, making it extremely verbose and harming the readability of the code. If profiling is needed, it should be implemented in the base class (Function or FunctionInternal, at some place where all calls passes through).

**Comment by jgillis** [comment]
Not supported anymore
