### ISSUE TITLE
Name conflicts when calling matrix friend functions

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1645]
If you have a function with the same name as one of the friend functions in the current scope, it can be difficult to call CasADi's function, e.g.
```c++
class Foo {
public:
void jacobian() {
 SX x = SX.sym("x");
 SX f = sin(x);
 SX z = jacobian(f, x); // Error - name conflict
 SX z = f.zz_jacobian(x); // Ugly workaround
}
};
```
The solution is to replace the member functions "zz_nnn" with static functions without the "zz_" prefix.
```c++
class Foo {
public:
void jacobian() {
 SX x = SX.sym("x");
 SX f = sin(x);
 SX z = jacobian(f, x); // Error - name conflict
 SX z = SX::jacobian(f, x); // OK
}
};

**Comment by jaeandersson** [comment]
Ping @toivoh

**Comment by toivoh** [comment]
+1
Great to have an officially approved way to point out the actual function that you want. Would these static functions be able to replace the friend functions as well, or doesn't ADL look for static functions in classes?

**Comment by jaeandersson** [comment]
No, for ADL you still need the friend functions. Otherwise you would always need to qualify which overload you want:
```c++
MX x = MX::sym("x");
MX f = MX::plus(MX::sin(x), 4); // uugh
```

**Comment by toivoh** [comment]
Ok, thanks for the clarification.

**Comment by jaeandersson** [comment]
This issue has been completed as part of #1586. The friend functions should now provide a static function alternative that prevents name conflicts like the example above.
