### ISSUE TITLE
Interface Gurobi

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1648]

**Comment by adbuerger** [comment]
Is there an example somewhere on how to use Gurobi from CasADi with integer variables? Since that would be really interesting!

**Comment by jaeandersson** [comment]
There are no examples for that. But the integer variables is simply an option "discrete", cf. https://github.com/casadi/casadi/blob/develop/docs/examples/python/lotka_volterra_minlp.py. You can use this option either together with the high-level (NLP style) interface (https://github.com/casadi/casadi/blob/develop/docs/examples/python/chain_qp.py) or with the low-level (matrix style) interface, https://github.com/casadi/casadi/blob/develop/docs/examples/cplusplus/lowlevel_qp.cpp.

**Comment by adbuerger** [comment]
Ok cool! But this would define all variables as discrete variables, so it would not (yet?) be possible to have a mixed-integer problem using this option, right?

**Comment by jaeandersson** [comment]
The "discrete" option takes a list of booleans, one for each decision variables, cf. https://github.com/casadi/casadi/blob/develop/docs/examples/python/lotka_volterra_minlp.py.

**Comment by adbuerger** [comment]
Ah, now I get it. Thanks!

**Comment by brittanh** [comment]
I've installed Gurobi and I have an academic license plus I've added it's location to the Python path  but I still get the error message that :
`"Plugin 'gurobi' is not found."`
Anyone have any suggestions?

**Comment by jgillis** [comment]
The `gurobi` is not currently shipped in our binaries.
You can obtain it via a source build.

**Comment by brittanh** [comment]
Sorry I'm not the most computer savy but I downloaded gurobi from there website. But instead of using that install I should do a source build myself?

**Comment by jgillis** [comment]
You'd need both the downloaded gurobi, and a source build of casadi, (or a binary of casadi that has the interface).
If you're not computer savy, building from source is going to be a tough adventure.

I can add the gurobi interface in our binaries for you.
Which OS system are you on?

**Comment by brittanh** [comment]
Ahh okay. Thank you so much that would be amazing! I'm on Mac OSx

**Comment by brittanh** [comment]
Also I was using casadi v3.2.2 so would it be possible to get the binary using that version? I know there has been some relatively large changes to the newest casadi version so my code wouldn't work with it.

**Comment by jaeandersson** [comment]
> I know there has been some relatively large changes to the newest casadi version

The syntax changes from 3.2 to 3.3 should be very modest.

**Comment by brittanh** [comment]
Where would I find the binary with the gurobi interface including? I'm on a bit of a deadline (I'm using casadi for my masters project) so I appreciate the help!

**Comment by jgillis** [comment]
This slipped out of my attention, sorry.

Here are Python/mac builds that include the guobi interface (put path to libgurobi65.so in your DYLD_LIBRARY_PATH)
https://sourceforge.net/projects/casadi/files/CasADi/commits/d317a1c/osx/

**Comment by brittanh** [comment]
Fantastic thanks a bunch! Much appreciated :)

**Comment by brittanh** [comment]
I'm still having some trouble and get the same error message:
`Plugin 'gurobi' is not found` 

I downloaded the binary and imported this version of casadi into my Python script.
I added libgurobi75.so to the DYLD_LIBRARY_PATH path (i didnt have libgurobi65.so) and also added `/usr/local/lib/gurobi.py` to the PYTHONPATH as well.

Any thoughts on what I'm doing wrong?

**Comment by jgillis** [comment]
needs to be libgurobi65.so
it *might* work if you rename your version

**Comment by brittanh** [comment]
okay I'll give that a try first

**Comment by jgillis** [comment]
pleasralso report the full error message

**Comment by brittanh** [comment]
`CasADi warning: "The assertion "handle!=0" on line 287 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp" failed. 
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_gurobi.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi' :
    Error code: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi/libcasadi_conic_gurobi.dylib, 5): no suitable image found.  Did find:
	/usr/local/lib/libgurobi65.so/libcasadi_conic_gurobi.dylib: stat() failed with errno=20
  Tried '' :
    Error code: dlopen(libcasadi_conic_gurobi.dylib, 5): no suitable image found.  Did find:
	/usr/local/lib/libgurobi65.so/libcasadi_conic_gurobi.dylib: stat() failed with errno=20
  Tried '.' :
    Error code: dlopen(./libcasadi_conic_gurobi.dylib, 5): no suitable image found.  Did find:
	/usr/local/lib/libgurobi65.so/libcasadi_conic_gurobi.dylib: stat() failed with errno=20
" issued  on line 143 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp". 
Traceback (most recent call last):
  File "process_main.py", line 44, in <module>
    _, xmeasureAll_pf, uAll_pf, obj_pf, optRest_pf, params_pf, runtime_pf = pfNMPC(optProblem, system, MPCit, N, T, tmeasure, xmeasure, u0, params)
  File "/Users/brittanyhall/Documents/GitHub/masters-project/Code/Pathfollowing_BHall/DistllationColumnModel/ColA/pfNMPC.py", line 75, in pfNMPC
    primalPF, _, elapsedqp = pathfollowing(lambda p: ColCSTR_pf(p), p_init, p_final, xstart, ystart, delta_t, lb_init, ub_init, 0, N)
  File "/Users/brittanyhall/Documents/GitHub/masters-project/Code/Pathfollowing_BHall/DistllationColumnModel/ColA/pathfollowing.py", line 51, in pathfollowing
    qp_exit, y, x_qpopt, lam_qpopt, mu_qpopt, qp_run = qp_solve(prob, p_init, x_init, y_init, step, lb, ub, N, x0, lb_init, ub_init)
  File "/Users/brittanyhall/Documents/GitHub/masters-project/Code/Pathfollowing_BHall/DistllationColumnModel/ColA/qp_solve.py", line 69, in qp_solve
    optimize = conic('optimize','gurobi',qp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi/casadi.py", line 13703, in conic
    return _casadi.conic(*args)
RuntimeError:  on line 382 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp"
Plugin 'gurobi' is not found.`

I also tried your suggestion of changing the file name and that resulted in the same error.

**Comment by jgillis** [comment]
Can you shoew the exact content of your DYLD_LIBRARY_PATH?

**Comment by brittanh** [comment]
`echo $DYLD_LIBRARY_PATH` in the terminal gives me:

`/usr/local/lib/libgurobi65.so`

**Comment by jgillis** [comment]
repeat with just /usr/local/lib

On Dec 5, 2017 7:10 PM, "Brittany Hall" <notifications@github.com> wrote:

echo $DYLD_LIBRARY_PATH in the terminal gives me:

/usr/local/lib/libgurobi65.so

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/casadi/casadi/issues/1648#issuecomment-349390955>, or mute
the thread

**Comment by brittanh** [comment]
Still no luck unfortunately (I get the same error message I posted above)

**Comment by jgillis** [comment]
Hi!
I'm sure the error message changes in a subtle way if you run it with the
corrected PATH.. please repost. it'sa pitty this takes so long. Shouldnt be
more than 5mins to debug with the computer in front..

**Comment by brittanh** [comment]
Here it is:
```
CasADi warning: "The assertion "handle!=0" on line 287 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp" failed. 
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_gurobi.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi' :
    Error code: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi/libcasadi_conic_gurobi.dylib, 5): image not found
  Tried '' :
    Error code: dlopen(libcasadi_conic_gurobi.dylib, 5): image not found
  Tried '.' :
    Error code: dlopen(./libcasadi_conic_gurobi.dylib, 5): image not found
" issued  on line 143 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp". 
Traceback (most recent call last):
  File "process_main.py", line 44, in <module>
    _, xmeasureAll_pf, uAll_pf, obj_pf, optRest_pf, params_pf, runtime_pf = pfNMPC(optProblem, system, MPCit, N, T, tmeasure, xmeasure, u0, params)
  File "/Users/brittanyhall/Documents/GitHub/masters-project/Code/Pathfollowing_BHall/DistillationColumnModel/ColA/pfNMPC.py", line 77, in pfNMPC
    p_init,p_final,xstart,ystart,delta_t,lb_init,ub_init,0,N)
  File "/Users/brittanyhall/Documents/GitHub/masters-project/Code/Pathfollowing_BHall/DistillationColumnModel/ColA/predictor_corrector.py", line 46, in predictor_corrector
    qp_exit, y, qp_val, lam_qpopt, mu_qpopt, qprun = qp_solve(prob, p, x_init, y_init, step, lb, ub, N, x0, lb_init, ub_init)
  File "/Users/brittanyhall/Documents/GitHub/masters-project/Code/Pathfollowing_BHall/DistillationColumnModel/ColA/qp_solve.py", line 69, in qp_solve
    optimize = conic('optimize','gurobi',qp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi/casadi.py", line 13703, in conic
    return _casadi.conic(*args)
RuntimeError:  on line 382 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp"
Plugin 'gurobi' is not found.
```

**Comment by jgillis** [comment]
The typo in `DYDL_LIBRARY_PATH`, is that just in the post here, or on your terminal as wel?

**Comment by brittanh** [comment]
Sorry that was just in the post here

**Comment by jgillis** [comment]
Let's hard-code the link to gurobi..

`sudo install_name_tool -change "libgurobi65.so" "/usr/local/lib/libgurobi65.so" /Users/brittanyhall/Downloads/casadi-py27-d317a1c/casadi/libcasadi_conic_gurobi.dylib`

**Comment by brittanh** [comment]
Okay I got it working I think. I now ust need to change my code to work with the newer version of Casadi  (Function no longer has attribute gradient for example).

Your help has been much appreciated!

**Comment by jgillis** [comment]
For the gradient, check the suggestions on https://github.com/casadi/casadi/wiki/Changes-v3.1.0-to-v3.2.0#api-changes -- I will upload a newer version of CasADi which hopefully doesnt need the `install_name_tool` thing

**Comment by brittanh** [comment]
I think your binary as is was okay. My fiance (who is computer savvy) pointed out something wrong I was doing with how I directed the Python code to the path of this casadi version.
(I didn't want to delete the other version I had)
