### ISSUE TITLE
Define simple, just-in-time compiled functions as string with C code

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1650]

**Comment by jaeandersson** [comment]
The following is now possible:
```python
from casadi import *
body = '''
real_t a = sqrt(arg[0]>=0 ? arg[0] : -10*arg[0]);
res[0] = a * arg[1];
res[1] = cos(a);
'''
f = jit('myfcn', 2, 2, body, {'compiler':'shell'})
print f([3, 4])
```
Ping @jgillis @ghorn

**Comment by jgillis** [comment]
Nice!

**Comment by jaeandersson** [comment]
Derivative information can be supplied by setting the "jac" and "hess" options. The Jacobian is assumed to be dense and you provide the function body for all inputs with respect to all outputs. The Hessian is assumed to be the Jacobian of the (flattened) Jacobian, also dense.
