### ISSUE TITLE
hessian function not working in Matlab

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1652]
Hessian has an overload with a special output argument signature:

% hessian(const MatType &ex, const MatType &arg, MatType& output_g)

```
x = SX.sym('x');

hessian(x^2,x) % fails
```

**Comment by ghorn** [comment]
ouch

**Comment by jaeandersson** [comment]
Is it a conflict with the other overload? Maybe it works if you only have that overload.

**Comment by jgillis** [comment]
This seems to have been fixed.
