### ISSUE TITLE
Unexpected behaviour when using zero-size SX

### ISSUE THREAD

**Issue by giusgiordano** [casadi/casadi#1653]
```
import casadi as ca

a = ca.SX.sym('a')
b = ca.SX.sym('b',0)

print a+b
```

The output is empty, i.e. SX([]), which is not what one would expect.

**Comment by ghorn** [comment]
I would expect dimension mismatch

**Comment by jaeandersson** [comment]
It's expected behaviour. A binary operation with a *scalar* A and a *matrix* B will result in a matrix with the dimensions of B. In your example, since a is scalar, a+b will get the dimension of b, i.e. 0-by-1.

**Comment by jaeandersson** [comment]
Cf. in MATLAB:
```
>> zeros(0,1) + 1

ans =

   Empty matrix: 0-by-1
```

**Comment by ghorn** [comment]
This behavior is intuitive for multiplication, but not as much for addition. Is the motivation to prevent special case clutter?
