### ISSUE TITLE
Failing with binaries in MATLAB 2015b

### ISSUE THREAD

**Issue by mjm522** [casadi/casadi#1655]
I am new to Casadi. Following are the steps I did to get Casadi installed. I am running MATLAB 2015b on Ubuntu 14.04 Lts - 64bit

1) sudo apt-get install gcc g++ gfortran git cmake liblapack-dev pkg-config --install-recommends
2) sudo apt-get install swig ipython python-dev python-numpy python-scipy python-matplotlib --install-recommends
3)sudo apt-get install coinor-libipopt-dev
4) downloaded following binary: casadi-matlabR2015a-6aebb26.tar.gz (8.8 MB)
5) extracted to a folder CasadiInstallation
6) on MATLAB command line:
 addpath('CasadiInstallation'); savepath;
import casadi.*
x = MX.sym('x')

The error I get:

Undefined function or variable 'casadiMEX'.

Error in casadi.GenMX.sym (line 684)
      [varargout{1:max(1,nargout)}] = casadiMEX(416, varargin{:});

Could you please help to rectify the situation?

**Comment by jgillis** [comment]
Sorry I missed this.
This is unexpected. Could you run ldd on the CasadiInstallation/casadiMEX.mexa64 and report back please?

**Comment by mjm522** [comment]
thanks for the reply, the problem was with the folder name.
