### ISSUE TITLE
Rewrite SNOPT interface

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1656]
The SNOPT interface is suboptimal/obsolete in several ways: 
 * It does not work with different versions of SNOPT and relies on redistributing some header files for a particular version of SNOPT. This is highly unfortunate.
 * The way options are handled is not transparent or efficient.
 * It still uses the old way of evaluating the NLP functions
 * It interacts with SNOPT via the "snOptC" interface, which is unfortunate since it requires sorting the variables by linear and nonlinear. The "snOptA" interface, which is the recommended one, is more natural - there it's enough to mark which equations are linear.
 * SNOPT is reentrant so in principle, the evaluation should be thread-safe. This won't be the case now however, due to mutable memory stored in the interface class itself.

With all these issues put together, the easiest way forward is probably simply to rewrite the interface from scratch.

**Comment by ghorn** [comment]
snoptA is recommended for new users. SnoptC is more efficient.
