### ISSUE TITLE
Mac OSX version crashes when using Matlab 2012b (2.4.2)

### ISSUE THREAD

**Issue by adomahidi** [casadi/casadi#1658]
Just downloaded the Matlab binaries for version 2.4.2. When I do 

```
import casadi.*
x = SX.sym('x', 1);
```

Matlab 2012b crashes. Is this a known issue?

**Comment by jgillis** [comment]
Yes, this is expected. The binary is for R2015a or later.
If I would have an installation disk for older Matlab's I could publish other binaries..
R2012b is alltogether too old, I believe. R2013a is probably the oldest that can be supported.

**Comment by jaeandersson** [comment]
To expand a bit on that: There have been new features added to the MATLAB language, in particular regarding the support for object oriented programming. The MATLAB backend for SWIG, and hence CasADi-MATLAB bindings, rely on some of these features.

**Comment by adomahidi** [comment]
Thanks for the info! So what is the minimum version of Matlab supported? Do you think building on my own will be successful for 2012b, or is that version too old?

**Comment by jgillis** [comment]
Well we have binaries for R2013a on Windows, so that version would probably work.

**Comment by jaeandersson** [comment]
Regardless of your MATLAB version, building CasADi-MATLAB from sources is kind of a pain...
