### ISSUE TITLE
Remove link dependency on Python

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1662]
Should a Python module really be linked to python librararies?
Some argue it should not ( http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/ ).

Removing the dependency fixes the "Fatal Python error: PyThreadState_Get: no current thread" issue from https://groups.google.com/forum/#!topic/casadi-users/j3QvaabC1IY .
I just uploaded new 2.4.2 binaries for mac without the dependency and they seem to run fine...

**Comment by jaeandersson** [comment]
I have nothing to add to the discussion...

**Comment by jgillis** [comment]
What does that mean?

**Comment by jaeandersson** [comment]
I mean, I don't know how the Python module should be linked. What is considered clean and so on.

**Comment by jgillis** [comment]
dependency is removed on linux and mac, maintained for windows
