### ISSUE TITLE
support full(SX([1;2]))

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1664]

**Comment by jgillis** [comment]
`DM(SX([1;2]))` is now possible in Python.

**Comment by jgillis** [comment]
@jaeandersson . Is `SX(vertcat([1,2])).full()` not supposed to do the same thing as `DM(SX([1,2])).full()`?

**Comment by jaeandersson** [comment]
I thought it was cleaner if the user was forced to do an explicit conversion to DM. So no, full(SX) is not supported currently.

**Comment by jaeandersson** [comment]
I'm closing this issue. full(SX) isn't supported without an explicit type cast which I think it's good. From what I can tell, there is no difference between Python and MATLAB.
