### ISSUE TITLE
Regressions of 3.0 encountered during unittests upgrade

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1669]
* [x] IM,SX has no full member.
 * [x] `a=DM.ones(2,2);a.set(np.matrix([[2,2],[2,2]]))` type error; This is on purpose. set is an internal thing now. you can use `[:,:]` or `project` to achieve the sam.
 * [x] ipopt when  used as qp should set fixed_variable_treatment properly. cf https://github.com/casadi/casadi/blob/master/casadi/interfaces/ipopt/ipopt_interface.cpp#L1229-L1241

**Comment by jaeandersson** [comment]
> IM,SX has no full member

Correct, needs fixing.

> "a.set(np.matrix([[2,2],[2,2]]))" should not be allowed.

I removed that overload as I found it unnecessary. It also doesn't exist for MX.
