### ISSUE TITLE
Typemap failure in directors/callbacks

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1675]
Consider the following.
The printout reads `<Swig Object of type 'casadi::Dict *' at 0x7f8e5861cbd0>`, which means that the options structure has failed to be cast to a Python dict.

``` python
from casadi import *

class Fun(Callback):
  def __init__(self, name, opts={}):
    Callback.__init__(self)
    self.construct(name, opts)

  def eval(self,argin):
    return argin

  def get_n_forward(self): return 1

  def get_forward(self, name, nfwd, opts):
    print opts


f = Fun("test")

f.jacobian()
```

**Comment by jgillis** [comment]
Is have "Dict&" non-const really a crucial thing?

**Comment by jgillis** [comment]
ping @jaeandersson

**Comment by jaeandersson** [comment]
> Is have "Dict&" non-const really a crucial thing?

"Dict&" is not needed in the `Callback` class so you can change it to:
```
virtual Function get_forward(const std::string& name, int nfwd, Dict& opts);
```
That should be much easier to treat in SWIG, using standard output typemaps. I guess that should resolve your problem?

Whether to change it also in `FunctionInternal` is an open question. I made it non-const deliberately, to allow inherited classes to modify the list of options without copying everything first.
