### ISSUE TITLE
Missing feature in vertcat inputs

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1677]
The following is a very typical use case in which you want to obtain a `y0 z0 y1 z1 ...` ordering using concatenated inputs. It throws an error (non-symbolic input).

```python
from casadi import *;

y=MX.sym('y',10);
z=MX.sym('z',10);

x=horzcat([y,z]).T;
f=Function('f',[vec(x)],[y+z])
```

Obviously, one can work around this by starting from a 2-by-10 and distilling out y and z..

**Comment by jaeandersson** [comment]
This is not possible in the current design. The generalized inputs for MXFunction are based around the idea that each input component represents a continuous segment from the whole input. That is why horzcats and reshapes are allowed but *not* transposes.

**Comment by jgillis** [comment]
This answer bumps the importance of #1388
