### ISSUE TITLE
Possibility for Matlab-Python-interoperability for CasADi?

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1678]
Nearly everything I do, I program in Python, so I'm also using CasADi from Python and I like it really much that way. But, some other people might be bound to using Matlab (company restrictions, personal preference, ...), and in such a case cannot use what I build from CasADi, and vice versa.

I think it would be of great use if there could be an interoperability between Matlab- and Python-CasADi. I don't know how hard it would be to achieve this aim though, a first test using both interfaces showed the following (from a Matlab console):

    >> import casadi.*
    >> x = MX.sym('x');
    >> py.casadi.jacobian(sin(x), x)

    Error using py.casadi.jacobian
    Conversion of MATLAB 'casadi.MX' to Python is not supported. 

Is it possible ta achieve such an interoperability (at an appropriate cost)?

**Comment by jaeandersson** [comment]
I'm not sure how the Python-MATLAB interoperability you're talking about works. I would think that it's not easy to get working with CasADi.
What you can do already now is to generate MATLAB MEX code from Python. That is, construct your expressions, generate Jacobians and then generate a MEX-file for evaluating from MATLAB.

**Comment by adbuerger** [comment]
I thought about something like my casiopeia-project, but in the end every CasADi project built in Python, that gives you some Python classes that can perform certain actions and integrate into each other.

In these cases, it would be pretty cool if a Matlab user could use Python classes from Matlab instead of having to implementing everything on his/her own again (and vice versa). Since it uses the same software in the end, i. e. CasADi, "only" from a different interface (I know the word "only" is not really appropriate here).

I just wanted to have it mentioned as an idea. But your hint on generating MEX code is already pretty cool though, maybe this is already enough for what (at least) I would like to try.

**Comment by jaeandersson** [comment]
I think it would be hard to support generic interoperability between Python and MATLAB. I cannot see how it can be possible with the way SWIG works.
