### ISSUE TITLE
Return status not set when IPOPT times out

### ISSUE THREAD

**Issue by toivoh** [casadi/casadi#1681]
Apologies if this has already been fixed, I tried to run my example with the current `develop` branch, but I wasn't able to figure out which syntax I should use.

Anyway, on CasADi 2.4.0 at least, when optimizing with IPOPT and the solver exits because it has run out of time, CasADi does not set the string for return status in the solver statistics. (If a previous optimization was run, the return status of that optimization is returned instead).
To reproduce with CasADi 2.4.0:

    import numpy as np
    from casadi import *

    nx = 100

    x = MX.sym('x',nx)
    f = MX(0)
    g = x**2-1

    nlp = MXFunction(casadi.nlpIn(x=x),
                     casadi.nlpOut(f=f, g=g))

    options = {'max_cpu_time': 1e-6}
    nlp_solver = casadi.NlpSolver("nlp_solver", "ipopt", nlp, options)
    args = {"lbg" : np.zeros(g.shape),
            "ubg" : np.zeros(g.shape),
            "x0"  : np.zeros(x.shape)}

    res = nlp_solver(args)
    print nlp_solver.getStats()['return_status']

**Comment by jaeandersson** [comment]
Just change getStats to stats should work.

**Comment by toivoh** [comment]
Ok, seems to have been fixed! Thanks!
