### ISSUE TITLE
possible misspelling of function name in rosenbrock.m

### ISSUE THREAD

**Issue by rcleuthold** [casadi/casadi#1684]
When I download and run the rosenbrock.m file in matlab after installing CasADi, I have a problem. 

I expect: it to compile (and do something), but it gives the error: 
" Undefined function or variable 'nlpsol'.
Error in rosenbrock (line 39)
solver = nlpsol('solver', 'ipopt', nlp); %nlpsol "

But, the problem seems to be fixable:
replace:
% Create IPOPT solver object
solver = nlpsol('solver', 'ipopt', nlp); 
with: 
% Create IPOPT solver object
solver = NlpSolver('solver', 'ipopt', nlp); %nlpsol

at which point, it works...

I'm not sure if my problem is because I have matlab 2015b, and installed from "R2014b or later" (https://github.com/casadi/casadi/wiki/InstallationInstructions), on an Ubuntu 14.04 machine. 

Best regards, 
rcl

**Comment by jgillis** [comment]
Hi there!

It seems you are mixing CasADi versions.
The code you obtained is for v3.0.0-rc1, while you are 'fixing' it into v2.4.2 syntax.
I'm wondering, how did you come by the matlab example?

**Comment by rcleuthold** [comment]
Hi,

It's the example file at the end of:
https://github.com/casadi/casadi/wiki/matlab

You're probably right that I've got some sort of versioning/installation
problem... But since it seems to run now, I might just use the not-fix and
the download-extract-drag-dropped binary I got from (
https://github.com/casadi/casadi/wiki/InstallationInstructions
Matlab/Linux/2014b...)  (Unless you suggest there's some serious reason why
I should build-from-source?

Thanks + best,
Rachel

**Comment by jaeandersson** [comment]
Building the MATLAB interface from sources can be a bit of a pain so best is if you can use the pre-built binaries.

**Comment by rcleuthold** [comment]
Actually, I have an unrelated question...

Can I use a casadi to solve optimisation problems within a matlab parfor
loop?

Best + thanks,
Rachel

**Comment by jaeandersson** [comment]
Please keep the threads on topic. But, no I doubt that you'll be able to do anything with parfor.

**Comment by rcleuthold** [comment]
Thank you :)
