### ISSUE TITLE
Dated documentation

### ISSUE THREAD

**Issue by shisha101** [casadi/casadi#1687]
I am really eager to use the full capability of CasADi, however I am being completely bottle necked by the documentation as it is not consistent and not all the code from the examples work.

Maybe I am missing something, for instance in the issues here on Github say that the simulation class has been deprecated and merged with Ivpsol, however the .py examples on Github still show them and not the new version, i also don't know where to find documentation of the new implementation.
The tutorial .pdfs are also outdated.

Could someone please point me to where the most up-to-date and functional documentation is. 

The most important things for me at the moment are integrators. for instance I would like to have an integrator where I can separate between symbolic parameters and inputs, without having to create a ControlSimulator as I wish to integrate in a step by step fashion, and according to git is already being deprecated

**Comment by jgillis** [comment]
Hello there!

It's not that the documentation is dated; it's just that you're looking in the wrong spot.
Stable version 2.4.3 (which coincides with master branch) has its documentation here:
  http://docs.casadi.org/2.4.3

The upcoming release (corresponding to develop branch) has its documentation here:
http://docs.casadi.org/3.0.0-rc1

**Comment by shisha101** [comment]
Thanks for the tip, I'll check it out :+1:
