### ISSUE TITLE
Error Unpacking Symbolics

### ISSUE THREAD

**Issue by mrisbeck** [casadi/casadi#1690]
The following fails in 3.0.0-rc2:

    >>> import casadi
    >>> casadi.__version__
    '3.0.0-rc2'
    >>> x = casadi.SX.sym("x", 2)
    >>> [x0, x1] = x[:]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "casadi/casadi.py", line 7505, in __getitem__
        return self.get(False, s)
      File "casadi/casadi.py", line 6839, in get
        return _casadi.SX_get(self, *args)
    RuntimeError: The assertion "stop<=len" on line 63 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/slice.cpp" failed. 
    Slice (start=2, stop=3, step=1) out of bounds with supplied length of 2

Also fails with `MX.sym`.

**Comment by jaeandersson** [comment]
Yes, that is not supposed to work, although the error message should be better. You can use `vertsplit`
```
x = casadi.SX.sym("x", 2)
[x0, x1] = vertsplit(x)
```
But better might be to reverse the logic and use `vertcat`:
```
x0 = casadi.SX.sym("x0")
x1 = casadi.SX.sym("x1")
x = vertcat([x0, x1])
```
Note that this is nos possible for both SX and MX.

**Comment by mrisbeck** [comment]
It worked in version 2.4. Any reason for the change? It's quite useful when defining functions that can accept a variety of inputs (lists, tuples, NumPy arrays, etc.) and it seems like all of a sudden there's a special case for Casadi symbolics. Okay, so I can always do `x0 = x[0]; x1 = x[1]` and so on, but that seems rather ugly. Reversing the logic isn't an option because the intended use in inside a function.

**Comment by jaeandersson** [comment]
CasADi's matrix datatypes are intended to be syntax compatible with each other, but not with lists, tuples or NumPy arrays. Relying on that to be the case is not a good idea. The deprecated syntax was unfortunate for a number of reasons:
 * It operated on the nonzero elements of the matrix only, meaning that the a sparse matrix with all zeros will behave differently from a dense matrix with all zeros.
 * It assumes that the components are scalars (1-by-1 matrices) and doesn't generalize to the case when the components are vectors.
 * For `MX`, it was less efficient. Accessing (all) elements using `x0 = x[0]; x1 = x[1]` is less efficient than `[x0,x1] = vertsplit(x)`, which is in turn less efficient and IMO less readable than: 
```python
x0 = SX.sym("x0")
x1 = SX.sym("x1")
x = vertcat([x0,x1])
```
