### ISSUE TITLE
RC1 build fails WITH_OPENMP

### ISSUE THREAD

**Issue by mccullerlp** [casadi/casadi#1692]
Hi, I am able to successfully build casadi with the options

  cmake -DCMAKE_BUILD_TYPE="${_buildtype}" \
        -DCMAKE_INSTALL_PREFIX="/usr" \
        -DWITH_PYTHON=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python2 \
        -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
        -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so \
        -DWITH_CLANG=ON \
        -DWITH_EIGEN3=ON \
        "${srcdir}/${_pkgname}-${pkgver}${pkgkey}"

this is on an up-to-date ARCH linux.

However if I add -DWITH_OPENMP the build fails on casadi/core/function/map.cpp with the errors.

> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp: In member function ‘virtual void casadi::MapReduce::eval(casadi::Memory&, const double**, double**, int*, double*) const’:
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp:365:41: error: no matching function for call to ‘casadi::FunctionInternal::eval(const double**&, double**&, int*&, double*&)’
>          f_->eval(arg_i, res_i, iw_i, w_i);
>                                          ^
> In file included from /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.hpp:29:0,
>                  from /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp:26:
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:141:18: note: candidate: virtual void casadi::FunctionInternal::eval(casadi::Memory&, const double**, double**, int*, double*) const
>      virtual void eval(Memory& mem, const double** arg, double** res, int* iw, double* w) const;
>                   ^
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:141:18: note:   candidate expects 5 arguments, 4 provided
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:142:18: note: candidate: virtual void casadi::FunctionInternal::eval(const double**, double**, int*, double*, int) const
>      virtual void eval(const double** arg, double** res, int* iw, double* w, int mem) const;
>                   ^
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:142:18: note:   candidate expects 5 arguments, 4 provided
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp: In member function ‘virtual void casadi::MapOmp::eval(casadi::Memory&, const double**, double**, int*, double*) const’:
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp:517:39: error: no matching function for call to ‘casadi::FunctionInternal::eval(const double**&, double**&, int*&, double*&)’
>        f_->eval(arg_i, res_i, iw_i, w_i);
>                                        ^
> In file included from /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.hpp:29:0,
>                  from /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp:26:
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:141:18: note: candidate: virtual void casadi::FunctionInternal::eval(casadi::Memory&, const double**, double**, int*, double*) const
>      virtual void eval(Memory& mem, const double** arg, double** res, int* iw, double* w) const;
>                   ^
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:141:18: note:   candidate expects 5 arguments, 4 provided
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:142:18: note: candidate: virtual void casadi::FunctionInternal::eval(const double**, double**, int*, double*, int) const
>      virtual void eval(const double** arg, double** res, int* iw, double* w, int mem) const;
>                   ^
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/function_internal.hpp:142:18: note:   candidate expects 5 arguments, 4 provided
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp: In member function ‘virtual void casadi::MapOmp::generateBody(casadi::CodeGenerator&) const’:
> /home/mcculler/today/casadi/src/casadi-3.0.0-rc1/casadi/core/function/map.cpp:543:27: error: ‘class casadi::CodeGenerator’ has no member named ‘call’
>      g.body << "    " << g.call(f_, "arg_i", "res_i", "iw_i", "w_i") << ";" << endl;
>                            ^
> make[2]: *** [casadi/core/CMakeFiles/casadi.dir/function/map.cpp.o] Error 1
> make[1]: *** [casadi/core/CMakeFiles/casadi.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by jaeandersson** [comment]
Indeed, it looks like the OpenMP support is broken in the release candidates. We will make sure to fix it for the ready release. Thanks for reporting this.

**Comment by ghorn** [comment]
I'm surprised @jgillis missed this. Aren't you using this at work?

**Comment by jgillis** [comment]
No, I'm using OpenCL...

**Comment by ghorn** [comment]
How portable is OpenCL? Is it at all a replacement for the OpenMP functionality?

**Comment by jgillis** [comment]
I wasn't suggesting it is a replacement; just commenting why I usually compile without OpenMP..

**Comment by jaeandersson** [comment]
Fixed the compilation errors.

**Comment by jgillis** [comment]
@ghorn OpenACC may be a drop in replacement if you're interested
