### ISSUE TITLE
Python syntax for vertcat

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1694]
In MATLAB, vertcat expects a multiple arguments. In Python however, a list/tuple is expected. This could be changed as follows:
```python
vertcat([a, b, c])
vertcat(v)
```
becomes
```python
vertcat(a, b, c)
vertcat(*v)
```

Also applies to horzcat, diagcat

**Comment by jaeandersson** [comment]
What say you @ghorn @jgillis ?

**Comment by jgillis** [comment]
:+1: also mtimes in python

**Comment by jaeandersson** [comment]
Implemented part of #1693. I'm not in favour of variable argument mtimes. It would suggest that it's an efficient way of calculating the product, which it is not, at least not in its current form.
