### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by BrechtBa** [casadi/casadi#1705]
I would like to used Casadi in a python3 project.
I've tried just building it but that of course didn't work.

Is support planned in the near future?
Does anybody have some suggestions on how to build to python3?

**Comment by jgillis** [comment]
Hi there!
Getting python3 to work should be a moderate effort since SWIG supports it.
It is not (yet) a high priority thing. What is your use case?

**Comment by BrechtBa** [comment]
Thanks for the fast response,

I would like to use casadi together with ipopt to solve system identification problems and optimal control problems in a home automation package (https://github.com/BrechtBa/homecon).
To communicate with a KNX home automation system I use Smarthome.py which works only in python3.

I have a working solution in which I supply all derivatives (analyticaly by hand) to pyipopt which calls ipopt.
I would like to use Casadi as it will be easier, more flexible and much much faster.

**Comment by jgillis** [comment]
Looks like a sweet use case. We'll check if we can squeeze it in the short-term to do list and keep you up to date!

**Comment by BrechtBa** [comment]
I've made an attempt at solving the issue myself, 
forked the repository and created a separate branch.

I've managed to get cmake to run without errors and picking up python3.4.
Didn't have time to do further checks.

**Comment by jgillis** [comment]
Yeah we had an experimental branch ourselves at one point: https://github.com/casadi/casadi/tree/test-python3

**Comment by BrechtBa** [comment]
I saw the branch but didn't look into it deeply.
Seems like I've implemented something very similar.
 :-(  double work

**Comment by pstjohn** [comment]
I just wanted to add a thumbs up to this effort. Ubuntu 16.04 just got released, and its shipping with python 3.5 as the default. For me at least, casadi seems to be the last holdout thats not python3 compatible.

**Comment by jgillis** [comment]
Okay, I'm bumping priority..

**Comment by jgillis** [comment]
To get someting future proof, we need to patch swig to become `py_limited_api`-compatible

**Comment by jgillis** [comment]
Current develop branch is python3-compatible now.
To enable, use 'WITH_PYTHON3' cmake build flag.

Binaries have been succesfully generated for Linux (3.4 and 3.5) and Windows (3.4, 32 and 64 bit)

**Comment by pstjohn** [comment]
Wow, fantastic -- thank you guys so much for getting this working! Hugely appreciated 👍

**Comment by BrechtBa** [comment]
Great job, I'll try it out as soon I can.

**Comment by jgillis** [comment]
Released as 3.0.1

**Comment by bsamadi** [comment]
I have installed casadi from casadi-py35-np1.9.1-v3.1.0-rc1.tar.gz
When I try `from casadi import *`, I get this error:

`>python3`
`Python 3.4.3 (default, Sep 14 2016, 12:36:27)                                                                                       `
`[GCC 4.8.4] on linux                                                                                                                `
`Type "help", "copyright", "credits" or "license" for more information.                                                       ` 
`>>> from casadi import *                                        `
Traceback (most recent call last):                                                                                                  
  File "/home/jserver/casadi-py35-np1.9.1-v3.1.0-rc1/casadi/casadi.py", line 18, in swig_import_helper                              
    return importlib.import_module(mname)                                                                                           
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module                                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                                     
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import                                                                   
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load                                                                
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked                                                       
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked                                                                
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible                                                     
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper                                                            
  File "<frozen importlib._bootstrap>", line 1715, in load_module                                                                   
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed                                                      
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory                                        
                                                                                                                                    
During handling of the above exception, another exception occurred:                                                                 
                                                                                                                                    
Traceback (most recent call last):                                                                                                  
  File "<stdin>", line 1, in <module>                                                                                               
  File "/home/jserver/casadi-py35-np1.9.1-v3.1.0-rc1/casadi/__init__.py", line 32, in <module>                                      
    from casadi.casadi import *                                                                                                     
  File "/home/jserver/casadi-py35-np1.9.1-v3.1.0-rc1/casadi/casadi.py", line 21, in <module>                                        
    _casadi = swig_import_helper()                                                                                                  
  File "/home/jserver/casadi-py35-np1.9.1-v3.1.0-rc1/casadi/casadi.py", line 20, in swig_import_helper                              
    return importlib.import_module('_casadi')                                                                                       
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module                                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                                     
ImportError: No module named '_casadi'

**Comment by jgillis** [comment]
Hi! Python 3.4 and 3.5 are not binary compatible. Could you retry with casadi py34?

**Comment by bsamadi** [comment]
It worked perfectly. Thank you Joris.

**Comment by thorade** [comment]
There is one SWIG issue about Py_LIMITED_API, maybe they are interested in having support for it in normal SWIG?
