### ISSUE TITLE
Support binary for CentOS 6?

### ISSUE THREAD

**Issue by pstjohn** [casadi/casadi#1716]
I was wondering if you might consider making a binary version of the package available for CentOS 6. Specifically, since it can be quite difficult to build casadi from sources (with all the dependencies) in a user's home directory, a binary installation would be quite useful for large-scale computing.

Unfortunately, most CentOS / Red Hat environments only support up to glibc v. 2.12, which causes the binary import to fail:

```
>>> import casadi
...
glibc.so.6: version `GLIBC_2.14' not found (required by casadi/_casadi.so)
...
$ ldd --version
ldd (GNU libc) 2.12
```

Any chance we could get a binary install compiled against an older glibc?

Thanks!

**Comment by jgillis** [comment]
Hey there! From first looks, not so easy to do. Our binarybuild environment is ubuntu 12.04 on travis.
Even the old gcc-4.4 relies on libc >= 2.14 on that platform.

Are you perchance aware of libc2.12 compatible gcc on ubuntu 12.04?

**Comment by pstjohn** [comment]
Only in theory, I'm guessing the cleanest way would be to use docker to set up a centos 6 build environment. https://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

I'm definitely no expert on travis or docker though, so there may be issues I'm not seeing.

**Comment by jgillis** [comment]
Oh okay this is news to me; good call!

**Comment by pstjohn** [comment]
Whats the overall method by which casadi binaries get built? I'm starting to seriously consider whether I'd be able to put in a PR to address some of these issues, but the binary system seems super complicated :)

Do you know if casadi would build on a `manylinux`

**Comment by jgillis** [comment]
Nice to have you contributing to distribution of CasADi!

I'd the person in charge of the current binaries. From my part, I won't spend effort to setup new means of distribution such as pip or conda-forge from ground-up, but of course I'll assist and publicize if you'd do it.

fwiw, you may find all build-scripts for our current binaries at https://github.com/casadi/binaries
Each branch corresponds to a build configuration, such as `windows`, `linux`, `linux-matlab`..

The thord-party dependency builds can be consulted here https://github.com/casadi/testbot/tree/merged/recipes

Btw, I have seen CentOS builds here:
https://copr.fedorainfracloud.org/coprs/mcculler/Casadi/

**Comment by pstjohn** [comment]
Cool, I'm certainly happy to start putting the recipes together, but if/when I inevitably run into compile issues I would certainly appreciate the support! I did see the build-scripts in casadi/binaries and was planning to use those as a starting point. (wow, super complicated though 😄 )

For those centOS builds, centOS 7 should probably run the binaries that you already distribute (I think the libc there goes up to 2.17..) I know conda is running a docker image of an older linux distribution, so if we are able to get one working that should solve this issue.

**Comment by pstjohn** [comment]
Closing this in favor of #1868
