### ISSUE TITLE
work vector allocation as an optimization

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1725]
I came across https://en.wikipedia.org/wiki/Register_allocation, which seems to be equivalent to graph coloring. The idea is reordering non-interfering operations in order to minimize the necessary number of registers.

We do the same thing with work vectors. I would be curious to see how much compression is possible.

**Comment by jaeandersson** [comment]
I'll close this issue as I see no indication that the current algorithms aren't working very well already. The current design is based on a depth-first ordering of the DAG and then last-in-first-out ordering per work vector segment length (i.e. number of nonzeros of the operation). We don't really have a fixed number of "registers", so the algorithms in that link do not really apply. Also, our registers consist not of scalars, but vector segments of different length. If you want to get a more efficient work vector use, your main options are (1) use a different topological sort and (2) extend the live variable use to segments of different length. I don't think either is worth investing time in at the moment.
