### ISSUE TITLE
JIT is not supported in integrator()

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#1748]
The documentation says that `integrator()` supports the `'jit'` option, but if it said to `True` an error is generated.

Example:
```python
import casadi as cs

q = cs.MX.sym('q')
v = cs.MX.sym('v')
u = cs.MX.sym('u')

x = cs.vertcat(q, v)
dx = cs.vertcat(v, u)

i = cs.integrator('Integrator', 'cvodes', {'x' : x, 'p' : u, 'ode' : dx}, {'jit' : True})
```
Output:
```
RuntimeError:  on line 2166 of file "/home/kotlyar/software/casadi/casadi/core/function/function_internal.cpp"
'generateBody' not defined for N6casadi15CvodesInterfaceE
```

**Comment by jaeandersson** [comment]
That's correct. JIT is not supported. Can you point to which documentation you found that? I believe that there was an option called "jit" in a previous CasADi version for JIT-compiling the DAE functions (not the whole integrator). That functionality can be added back easily. The integrators in CasADi need an overhaul in general, so I prefer to do all the integrator work together.

**Comment by mkotlyar** [comment]
@jaeandersson it says it in the inline documentation for `casadi.integrator` in Python:
```
    +-----------------+-----------------+-----------------+-----------------+
    | jit             | OT_BOOL         | Use just-in-    | casadi::Functio |
    |                 |                 | time compiler   | nInternal       |
    |                 |                 | to speed up the |                 |
    |                 |                 | evaluation      |                 |
    +-----------------+-----------------+-----------------+-----------------+
```

**Comment by jaeandersson** [comment]
This should work now.
