### ISSUE TITLE
Clean up and translate example collection

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1755]
Some of the examples in the `docs/examples` directory are outdated, other are essentially duplicates. Some are too complex too be readable.

We need to make an effort to have a manageable and useful collection of problems. These should ideally be available for all languages.

**Comment by ghorn** [comment]
> These should ideally be available for all languages.

This would also cross-document other language interfaces for people who are already familiar with one interface. Would be even better to have a latex specification of each problem.

**Comment by jaeandersson** [comment]
> Would be even better to have a latex specification of each problem.

Good idea. We can make one central file where all the examples are listed along with some notes on the problem they solve and how they solve it.
