### ISSUE TITLE
class DaeBuilder from winter-school casadi/matlab

### ISSUE THREAD

**Issue by rcleuthold** [casadi/casadi#1756]
Hello! 

I've been following the casadi user-guide (3.0.0, april 8, 2016) DaeBuilder example (rocket-thrust), in the matlab-casadi front-end (winter-school version), 

and at the lines: 
% specify initial conditions
dae.set_start('h', 0); 
dae.set_start('v', 0); 
dae.set_start('m', 1); 

I get the following error: 
No appropriate method, property, or field 'set_start' for class
'casadi.DaeBuilder'.

Error in SwigRef/subsref (line 29)
        [varargout{1:nargout}] = builtin('subsref',self,s);

Error in tryingAgain (line 29)
dae.set_start('h', 0);

I'm not sure if this is one of those things that changed between casadi revs. (Should I update casadi to whatever most recent version you have online, or is there a specific user-guide I should be following, or have I made a mistake somewhere else?)

Best/thanks, 
RL

**Comment by rcleuthold** [comment]
short update: 

I think this is just a typo in the user-guide, because 
dae.set_start('h', 0);     % doesn't work
dae.setStart('h', 0);       % doesn't give an error

and similarly
dae.set_unit('h', 'm');      % gives error (copy of above...)
dae.setUnit('h', 'm');      % no error 

anyways. best, etc, RL

**Comment by jaeandersson** [comment]
It's not a typo. "set_start" is the syntax in CasADi 3.0.0. You probably have a release candidate installed, and this was a change that happened after that release candidate.
