### ISSUE TITLE
SX.nz bug in Win64

### ISSUE THREAD

**Issue by mrisbeck** [casadi/casadi#1764]
In Windows 64 bit Casadi 3.0.0, `SX.nz` appears to be off by one. Running

```python
import casadi
x = casadi.SX.sym("x", 2)
print x.nz[:]
```
will print `SX(x_0)`, which is missing the second element. On Win32 and Linux, you get `SX([x_0, x_1])` as expected. The context is something like

```python
import casadi
import casadi.tools

N = 10
x = casadi.tools.entry("x", shape=(2,), repeat=N+1)
struct = casadi.tools.struct_symSX([(x,)])
```

which leads to the following error message:

```
  File "casadi\tools\structure.py", line 934, in __init__
    self.master = vertcat(*[i.nz[:] for i in s])

OverflowError: Python int too large to convert to C long
```

Presumably the indexing is off by one and the error is caused by whatever comes before `x_0` in memory.
I don't think this is new to version 3.0.0, as another user was having this problem in 2.4 (also on Win64).

**Comment by jaeandersson** [comment]
Ouch... @jgillis - are you able to reproduce this?

**Comment by jgillis** [comment]
Reproduced with 3.0.0 and develop.
(Does not reproduce on python34, 64 bit)

**Comment by jgillis** [comment]
`x.nonzeros()` does work correctly

**Comment by jgillis** [comment]
The python slice passed to 'NZProxy.__getitem__' is 'slice(0, 9223372036854775807L, None)' in the failing case, and '9223372036854775807' in the working..

**Comment by jgillis** [comment]
Note that 'x.nz[0:2**31-1]' gives the correct answer.
