### ISSUE TITLE
Simplified C API for codegen

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1767]
The C API of generated code is quite complicated to use. It makes sense to make an abstraction layer on top of it, still in C and consisting of a memory struct and a couple of functions. That should make it much more user friendly.

**Comment by ghorn** [comment]
I've done this for work. Give it a name like `controller` and you get something like:

`controller.h`:
```c
#ifndef CONTROLLER_H_
#define CONTROLLER_H_

#ifdef __cplusplus
extern "C" {
#endif

  typedef struct _controller_work_t * controller_work_t;

  controller_work_t alloc_controller_work();
  void free_controller_work(controller_work_t work);
  void eval_controller(controller_work_t work,
                       const double* input0, const double* input1,
                       double* output0, double* output1, double* output2);

#ifdef __cplusplus
}
#endif

#endif // CONTROLLER_H_
```


`controller.c`:
```c
/* define a CODEGEN_PREFIX to avoid symbol conflicts */
#define CODEGEN_PREFIX controller

/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

...
// here is the casadi-generated code
...

/* The following wrapper was automatically generated by greg. */

#include "controller.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

struct _controller_work_t {
  int n_iw;
  int n_w;
  int *iw;
  real_t *w;
};

controller_work_t alloc_controller_work() {
  int sz_iw, sz_w;
  controller_work(&sz_iw, &sz_w);
  controller_work_t work = calloc(1, sizeof(struct _controller_work_t));
  assert(work != NULL);
  work->n_iw = sz_iw;
  work->n_w = sz_w;
  work->iw = calloc(work->n_iw, sizeof(int));
  work->w = calloc(work->n_w, sizeof(real_t));
  assert(work->iw != NULL);
  assert(work->w != NULL);
  return work;
}

void free_controller_work(controller_work_t work) {
  free(work->iw);
  free(work->w);
  free(work);
}

void eval_controller(controller_work_t work,
                      const double* input0, const double* input1,
                      double* output0, double* output1, double* output2) {
  // check input/output dimensions
  int f_type, n_in, n_out, sz_arg, sz_res;
  controller__init(&f_type, &n_in, &n_out, &sz_arg, &sz_res);
  assert(n_in == 2);
  assert(n_out == 3);

  // check the workspace
  int sz_iw, sz_w;
  controller_work(&sz_iw, &sz_w);
  assert(sz_iw == work->n_iw);
  assert(sz_w == work->n_w);

  // set up input/output buffers
  const real_t * arg[sz_arg];
  real_t * res[sz_res];
  arg[0] = (const real_t *)input0;
  arg[1] = (const real_t *)input1;
  res[0] = (real_t *)output0;
  res[1] = (real_t *)output1;
  res[2] = (real_t *)output2;

  // call the function
  controller(arg, res, work->iw, work->w);
}
```

**Comment by ghorn** [comment]
I changed a few bits for clarity so there might be a typo.

**Comment by jaeandersson** [comment]
The above code uses variable length arrays, which is valid C99, but not valid C++ or valid C, pre-C99. http://stackoverflow.com/questions/1887097/variable-length-arrays-in-c

**Comment by ghorn** [comment]
That's a good point, but the abstraction is still reasonable. You could malloc those arrays and put them in the memory struct.

**Comment by jaeandersson** [comment]
Sure.

**Comment by mkotlyar** [comment]
I did something similar to what @ghorn did, but in C++:
```c++
/*
 * CasADiGeneratedFunction.h
 *
 *  Created on: Apr 19, 2016
 *      Author: kotlyar
 */

#pragma once

#include <vector>
#include <string>
#include <array>
#include <initializer_list>

#define CASADI_GENERATED_FUNCTION_INTERFACE(name) #name, name, name##_incref, name##_decref, name##_n_in, name##_n_out, \
	name##_name_in, name##_name_out, name##_sparsity_in, name##_sparsity_out, name##_work

	class CasADiGeneratedFunction
	{
	public:
		typedef double real_t;

		CasADiGeneratedFunction(
			const std::string& name,
			int (*fun)(const real_t** arg, real_t** res, int* iw, real_t* w, int mem),
			void (*fun_incref)(void),
			void (*fun_decref)(void),
			int (*fun_n_in)(void),
			int (*fun_n_out)(void),
			const char* (*fun_name_in)(int i),
			const char* (*fun_name_out)(int i),
			const int* (*fun_sparsity_in)(int i),
			const int* (*fun_sparsity_out)(int i),
			int (*fun_work)(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w));

		~CasADiGeneratedFunction();

		const std::string& name() const;
		int n_in() const;
		int n_out() const;

		//void operator()(std::array<const real_t *, 3> arg, std::array<real_t *, 3> res);
		void operator()(std::initializer_list<const real_t *> arg, std::initializer_list<real_t *> res);

	private:
		const std::string _name;
		int (*_fun)(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
		void (*_fun_incref)(void);
		void (*_fun_decref)(void);
		int (*_fun_n_in)(void);
		int (*_fun_n_out)(void);
		const char* (*_fun_name_in)(int i);
		const char* (*_fun_name_out)(int i);
		const int* (*_fun_sparsity_in)(int i);
		const int* (*_fun_sparsity_out)(int i);
		int (*_fun_work)(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);

		/*
		"To allow the evaluation to be performed efficiently with a small memory footprint, the
		user is expected to pass four work arrays. The function fname_work returns the length
		of these arrays, which have entries of type const double*, double*, int and double,
		respectively."

		CasADi user guide, section 5.3.
		http://casadi.sourceforge.net/users_guide/casadi-users_guide.pdf
		*/
		std::vector<const real_t *> _arg;
		std::vector<real_t *> _res;
		std::vector<int> _iw;
		std::vector<real_t> _w;
	};

/*
 * CasADiGeneratedFunction.cpp
 *
 *  Created on: Apr 19, 2016
 *      Author: kotlyar
 */

#include <CasADiGeneratedFunction.hpp>

#include <stdexcept>
#include <sstream>

	CasADiGeneratedFunction::CasADiGeneratedFunction(
		const std::string& name,
		int (*fun)(const real_t** arg, real_t** res, int* iw, real_t* w, int mem),
		void (*fun_incref)(void),
		void (*fun_decref)(void),
		int (*fun_n_in)(void),
		int (*fun_n_out)(void),
		const char* (*fun_name_in)(int i),
		const char* (*fun_name_out)(int i),
		const int* (*fun_sparsity_in)(int i),
		const int* (*fun_sparsity_out)(int i),
		int (*fun_work)(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w))
	:	_name(name),
		_fun(fun),
		_fun_incref(fun_incref),
		_fun_decref(fun_decref),
		_fun_n_in(fun_n_in),
		_fun_n_out(fun_n_out),
		_fun_name_in(fun_name_in),
		_fun_name_out(fun_name_out),
		_fun_sparsity_in(fun_sparsity_in),
		_fun_sparsity_out(fun_sparsity_out),
		_fun_work(fun_work)
	{
		_fun_incref();

		int sz_arg, sz_res, sz_iw, sz_w;
		if (int code = _fun_work(&sz_arg, &sz_res, &sz_iw, &sz_w) != 0)
			throw std::runtime_error(name + "_fun_work() returned " + std::to_string(code));

		_arg.resize(sz_arg);
		_res.resize(sz_res);
		_iw.resize(sz_iw);
		_w.resize(sz_w);
	}

	CasADiGeneratedFunction::~CasADiGeneratedFunction()
	{
		_fun_decref();
	}

	const std::string& CasADiGeneratedFunction::name() const
	{
		return _name;
	}

	int CasADiGeneratedFunction::n_in() const
	{
		return _fun_n_in();
	}

	int CasADiGeneratedFunction::n_out() const
	{
		return _fun_n_out();
	}

	void CasADiGeneratedFunction::operator()(std::initializer_list<const real_t *> arg, std::initializer_list<real_t *> res)
	{
		if (arg.size() != n_in())
		{
			std::stringstream msg;
			msg << "Invalid number of input arguments passed to CasADi function \"" << name() << "\". "
					<< "Expected " << n_in() << ", got " << arg.size() << ".";
			throw std::logic_error(msg.str());
		}

		if (res.size() != n_out())
		{
			std::stringstream msg;
			msg << "Invalid number of output arguments passed to CasADi function \"" << name() << "\". "
					<< "Expected " << n_out() << ", got " << res.size() << ".";
			throw std::logic_error(msg.str());
		}

		std::copy(arg.begin(), arg.end(), _arg.begin());
		std::copy(res.begin(), res.end(), _res.begin());

		_fun(_arg.data(), _res.data(), _iw.data(), _w.data(), 0);
	}
```

**Comment by ghorn** [comment]
@mkotlyar I think you may have reproduced `Function::external` without the libcasadi dependency

**Comment by mkotlyar** [comment]
@ghorn , it is indeed somewhat similar to `casadi::external()`. However, if I use `casadi::external()`, I a) depend on CasADi b) can not avoid overhead  associated with dynamic memory allocation (can I?):
```
vector<double> x = {1, 2, 3, 4};
vector<DM> arg = {reshape(DM(x), 2, 2), 5};
vector<DM> res = f(arg);
```

If I simpy want to call CasADi-generated functions and pass raw pointers to my data structures, I need to do something similar to what I did.

**Comment by ghorn** [comment]
I agree with everything you said. I would prefer a C version with C++ wrappers for portability, but what you did looks nice as well.

I think Joel is also working on an alternative API to the generated code, which would be great because it's "official".

**Comment by jaeandersson** [comment]
> I think Joel is also working on an alternative API to the generated code, which would be great because it's "official".

Not really an alternative API, but rather some convenience structs and functions on top of the existing API. This is all written in C for portability and defined in a header-only file called "casadi_mem.h": https://github.com/casadi/casadi/blob/develop/casadi/core/casadi_mem.h. There is a struct containing all the function points:
```c
typedef struct {
  casadi_signal_t incref;
  casadi_signal_t decref;
  casadi_getint_t n_in;
  casadi_getint_t n_out;
  casadi_name_t name_in;
  casadi_name_t name_out;
  casadi_sparsity_t sparsity_in;
  casadi_sparsity_t sparsity_out;
  casadi_work_t work;
  casadi_eval_t eval;
} casadi_functions;
```
An option "with_mem" has been added to the CodeGenerator class which generates a pointer to a singleton instance of this struct, e.g.:
```c++
from casadi import *
x = SX.sym('x')
f = Function('f', [x], [sin(x)])
f.generate({'with_mem':True})
```
which will generate something like:
```c
casadi_functions* f_functions(void) {
  static casadi_functions fun = {
    f_incref,
    f_decref,
    f_n_in,
    f_n_out,
    f_name_in,
    f_name_out,
    f_sparsity_in,
    f_sparsity_out,
    f_work,
    f
  };
  return &fun;
}
```
That removes the need to query the entry points one by one.

There is also a structure that holds all the meta information as well as input and output buffers:
```c
typedef struct {
  /* Function pointers */
  casadi_functions* f;

  /* Work arrays */
  const real_t** arg;
  real_t** res;
  int* iw;
  real_t* w;
  int mem;

  /* Meta information */
  int n_in, n_out;
  casadi_io* in;
  casadi_io* out;
} casadi_mem;
```
where `casadi_io` holds meta information specific to an input or output:
```c
typedef struct {
  const char* name;
  int nrow;
  int ncol;
  int nnz;
  int numel;
  const int* colind;
  const int* row;
} casadi_io;
```

Finally, there are three functions, `casadi_alloc`, `casadi_eval` and `casadi_free`, for allocating an instance of `casadi_mem`, numerically evaluating it and freeing the memory, respectively. All of them are inline functions, so no additional linking is required:
```c
inline casadi_mem* casadi_alloc(casadi_functions* f) {
 ...
}
inline int casadi_eval(casadi_mem* mem) {
...
}
inline void casadi_free(casadi_mem* mem) {
...
}
```

Any feedback on this design?

**Comment by jaeandersson** [comment]
It would be possible to make an iteration of the design that removes the need for dynamic memory allocation.

**Comment by jaeandersson** [comment]
I did another iteration on the `casad_mem.h` file. Everything said above remains the same, but I reorganized the functions so that you can optionally use the functions without "malloc" and "free".

**Comment by mkotlyar** [comment]
I like this design.
What do you think about adding a RAII-style C++ class which would 
 a. Automatically manage a `casadi_mem` instance by calling `casadi_alloc()` in ctor and `casadi_free()` in dtor
 b. Override `operator()` to call `casadi_eval()`?

**Comment by mkotlyar** [comment]
I took a closer look at the C interface and I see an improvement that can be made.
Currently, `casadi_alloc()` allocates memory for `casadi_mem` and initializes it. This dynamic allocation is unnecessary, because the `casadi_mem` struct size is known and its definition is visible to the caller of `casadi_alloc()`. The caller might need to initialize an already allocated (possibly on stack) `casadi_mem` struct. For this purpose, there is `casadi_init()`; however, it does not initialize the internal arrays (`casadi_alloc_arrays()`, `casadi_init_arrays()`).

I propose moving calls to `casadi_alloc_arrays()`, `casadi_init_arrays()` from `casadi_alloc()` to `casadi_init()`, and corresponding changes to the `casadi_free()` and `casadi_deinit()`.

**Comment by jaeandersson** [comment]
> I took a closer look at the C interface and I see an improvement that can be made.

I don't quite follow the above suggestions, can you provide a small example? You cannot move any array dimensions to `casadi_mem`, this data structure is intended to be agnostic of the model so that it can be used in calling C code.

**Comment by mkotlyar** [comment]
@jaeandersson , as far as I understand, currently the following sequence of calls is needed:
```c
// Allocate and init casadi_mem struct
casadi_mem* mem = casadi_alloc(my_functions());

// Set pointers to arguments and results
mem->arg[0] = ...
mem->res[0] = ...

// Call the function
casadi_eval(mem);

// Free casadi_mem struct
casadi_free(mem);
```
I propose avoiding malloc'ing/freeing of the `casadi_mem` struct, since its definition is visible to the caller:
```c
casadi_mem mem;
casadi_init(&mem);

// Set pointers to arguments and results
mem.arg[0] = ...
mem.res[0] = ...

// Call the function
casadi_eval(&mem);

// Deinit casadi_mem struct and free internal arrays
casadi_deinit(&mem);
```

**Comment by jaeandersson** [comment]
> I propose avoiding malloc'ing/freeing of the casadi_mem struct, since its definition is visible to the caller and the struct can have auto storage:

But almost exactly that syntax is already possible. I explicitly designed it to that you could choose to use it as above - that's why there is an `#ifdef CASADI_STATIC` in the code.

A problem with the code as I can see it is that there is no simple way to allocate the work vectors statically. Currently, you'd need to do:

```c
casadi_mem mem;
casadi_init(&mem);

// Assign work vectors
static double* arg[SZ_ARG];
static const double* res[SZ_RES];
static double w[SZ_W];
static double wi[SZ_IW];
mem.arg = arg;
mem.res = res;
mem.w = w;
mem.iw = iw;

// Set pointers to arguments and results
mem.arg[0] = ...
mem.res[0] = ...

// Call the function
casadi_eval(&mem);

// Deinit casadi_mem struct and free internal arrays
casadi_deinit(&mem);
```

But `SZ_ARG`, `SZ_RES`, `SZ_W` and `SZ_IW` aren't readily available. These can be easily included in a the (optionally) generated header file though.

**Comment by jaeandersson** [comment]
Anyway, I'll make an iteration on this.

**Comment by jgoppert** [comment]
What is the cleanest way to do this currently, I found myself writing something like @mkotlyar did with a class and a macro, and then wanted to check if something already existed. Is casadi_mem.h the recommend approach?

**Comment by jgoppert** [comment]
I'm happy with mem.h, just wrote a c++ wrapper around it.
