### ISSUE TITLE
sum() and norm() in the MATLAB frontend

### ISSUE THREAD

**Issue by versvisa** [casadi/casadi#1768]
I need to calculate the squared norm of a vector. I can't find anything about it in the user guide. And none of the following commands work.

    x = MX.sym('x',3,1)
    sum(x)
    norm(x)
    x.sum()
    x.norm()

Is this not implemented? Do I have to write a loop?

**Comment by ghorn** [comment]
try `norm2` or `norm_2`

**Comment by ghorn** [comment]
also `sum1` and `sum2` for summing over rows/cols

**Comment by jaeandersson** [comment]
For sum of squares, use `sum_square`

**Comment by jgillis** [comment]
sum added in #1641
