### ISSUE TITLE
GenericType(vector<bool>) makes an OT_INT_VECTOR

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1769]
expected behavior:
`GenericType(std::vector<bool>).getType() == OT_BOOL_VECTOR`
actual behavior:
`GenericType(std::vector<bool>).getType() == OT_INT_VECTOR`

casadi 3.0

**Comment by jaeandersson** [comment]
It is actually expected behavior currently and should not be a problem if GenericType is used in the intended way. The way the variable is stored is supposed to be an internal matter for GenericType.
