### ISSUE TITLE
nlpsol callbacks should expose `p`, possibly drop Lagrange multipliers

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1770]
@jaeandersson suggested having `(x, p, f, g)` and dropping the lagrange multipliers

**Comment by jaeandersson** [comment]
In each case, it makes little sense to force having "nlpsol callback inputs" being equal to "nlpsol outputs".

**Comment by jaeandersson** [comment]
Closing as there are currently no plans to work on this
