### ISSUE TITLE
add Dict to Function::call to support dynamic options

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1771]
Some options cannot really be changed after initialization, like `expand`. Others like `tol`, `max_iters` `reltol`, `tf`, etc can probably be changed after initialization, but there is currently no interface.

Would it be reasonable to add a `Dict` to `Function::call` for changing options which can be changed at runtime?

Probably the biggest use-case for this would be `tf` in `Integrator` in order to avoid the time reformulation.

**Comment by jaeandersson** [comment]
Against this. It goes against the idea of functions being "pure". If an "option" changes for each call, it should be an input. In fact, that's the definition of an input.

Concerning, `tf`, the plan is to change this from an option to an input. When calling an integrator object, the user supplies the initial conditions, parameters and a vector of time points.

**Comment by ghorn** [comment]
I suppose half of the ipopt options should then be inputs instead of options. You can't differentiate them though.

**Comment by jaeandersson** [comment]
> I suppose half of the ipopt options should then be inputs instead of options. You can't differentiate them though.

Why half? If you change options, you create a new instance. It's not like you can change IPOPT options on the fly.
