### ISSUE TITLE
Deprecate Function::jacobian, Function::derivative

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1777]
The functions for generating derivative functions in Function are currently difficult to use and, if kept, will need to have their signatures changed to align with the corresponding changes to the internal classes. 

Since #1774 introduces a much easier to use and much more flexible way to generate derivatives, we can simply deprecate these functions instead of trying to update the signatures or maintain backwards compatibility. Already now, these functions are of internal character and avoided in examples.

**Comment by jgillis** [comment]
make way, casadi 4.0 is here..

**Comment by jaeandersson** [comment]
> make way, casadi 4.0 is here..

I think we have since long moved away from `Function::jacobian` in favour of working with expressions and using `casadi::jacobian`. For sure we have avoided it in all new examples and exercises. Working with expressions is just much more intuitive and in most circumstances at least as efficient.

**Comment by jaeandersson** [comment]
@jgillis When this is implemented, parts of the unit tests will be obsolete. Preferred solution? Remove, refactor or replace with new unit tests?

**Comment by jaeandersson** [comment]
Note that the idea is to use the (more user-friendly) functions operating on expressions instead:
```c++
jacobian(const MatType &ex, const MatType &arg, bool symmetric=false);
```
Potentially, we could change the signature for these to take a dictionary:
```c++
jacobian(const MatType &ex, const MatType &arg, const Dict& opts=Dict());
```

Then the user could set a parameter to force a particular AD mode for example:
```python
J = jacobian(f, x, {'ad':'forward'}) # Force the use of forward mode AD
```
This feels more intuitive than setting "ad weight" parameters...

**Comment by jgillis** [comment]
Its fine if you purge, provided that you link to this issue. I will review

**Comment by jgillis** [comment]
This would be an alternative to ad_weight not a replacement?

**Comment by jaeandersson** [comment]
> This would be an alternative to ad_weight not a replacement?

I think I'd like to remove "ad_weight" as a user-settable option. It would remain internally and in Callback. The only time you would use it right now is to force an AD mode, but if there is a more user-friendly way of doing that, it's no longer needed.

**Comment by jaeandersson** [comment]
@jgillis I deprecated `Function::jacobian`, `Function::hessian` in branch_1777: https://github.com/casadi/casadi/tree/issue_1777

There are so many unit tests that depend on them so just deleting them would leave the test framework severely crippled... Maybe you can have a look.

There are also some examples that have not been updated to 3.0 syntax:
 * docs/examples/python/lqr_control.py
 * docs/examples/python/simulation.py
 * docs/examples/python/mhe_spring_damper.py
