### ISSUE TITLE
Variable assignment by unpacking an iterable no longer works

### ISSUE THREAD

**Issue by prakriteesh** [casadi/casadi#1778]
I am using the master branch - Casadi 3.0.0. 

I try the following code segment from the demo [http://nbviewer.jupyter.org/github/casadi/casadi/blob/master/docs/notebooks/demo.ipynb](url)

```
x  = SX.sym("[p,q,c]")  
p,q,c = x
```

The last line (p,q,c assignment by unpacking x) fails with this error message:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 7519, in __getitem__
>     return self.get(False, s)
>   File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 6853, in get
>     return _casadi.SX_get(self, *args)
> RuntimeError: The assertion "stop<=len" on line 63 of file "/home/prakriteesh/casadi/casadi/core/slice.cpp" failed. 
> Slice (start=3, stop=4, step=1) out of bounds with supplied length of 3

It used to work in Casadi 2.4.0. Was there a syntax change I need to take care of ?

**Comment by jaeandersson** [comment]
This syntax isn't supported anymore. See for example discussion on https://groups.google.com/forum/#!topic/casadi-users/fnvRCrnwX_I.

It appears as if the "demo.ipynb" file is outdated. I made an update of it: https://github.com/casadi/casadi/commit/5970156f3ed3d578ab7f95f843e052d00cbbc57f, but it might make more sense to remove it completely. The user guide provides a much better (and up-to-date) introduction to CasADi.

For your concrete problem, instead use e.g.
```python
p = SX.sym("p")
q = SX.sym("q")
c = SX.sym("c")
x = vertcat(p, q, c)
```
