### ISSUE TITLE
Interface blockSQP

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1784]
blockSQP (https://github.com/djanka2/blockSQP) is an SQP method suitable for block-structured problems, e.g. from direct multiple shooting transcriptions. It's a pretty minimalistic C++ code that could be distributed along with CasADi. It's C++ API is essentially just like any general purpose NLP method, but with the user specifying the sizes of the Hessian blocks. This structure can easily be detected by simply:
 * Calculating the sparsity pattern of the Hessian (we have very efficient algorithms for that)
 * Applying `Sparsity::scc` to detect the strongly connected components, i.e. the Hessian blocks - possibly requiring a reordering of variables.

Ping @djanka2

**Comment by jaeandersson** [comment]
Prerequisite #1800

**Comment by jgillis** [comment]
ping @timmercy @gpipelee

**Comment by jaeandersson** [comment]
Lots of the commits for this issue were accidentally marked #1827

**Comment by jaeandersson** [comment]
"blocksqp" branch now merged with develop. The final design does not make use of "scc", instead a simple algorithm that assumes that assumes no reordering is being used. Blocksqp has been partly, but not completely, adopted to CasADi data structures. Remains to remove the use of "blocksqp::Matrix" etc. The QP solver (currently qpOASES) also needs to be decoupled from blockSQP. A hack allows CasADi's interface to ma27 to be used, crucial for distribution.

**Comment by jaeandersson** [comment]
I'll reopen since it's still leaky and hacky.

**Comment by jaeandersson** [comment]
blockSQP has now been refactored and included in CasADi. Lots of improvements are possible, but this can be treated in separate issues.
