### ISSUE TITLE
Runtime functions in lib/casadi instead of stringified

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1789]
runtime.hpp is getting crowded with functions and plugins with codegen functionality doesn't have the ability to use the same code for codegen and for C++ VM. It would make sense to move the implementation to separate, importable header files. These will be distributed along with CasADi in the `lib/casadi` directory, similar to the clang headers. This also makes CasADi more hacking friendly and debuggable for users.

The templated/nontemplated option can be resolved, e.g. with macros (didn't test this):

``` c++
#ifdef __cplusplus 
#define REAL_TEMPLATE template<typename real_t>
#else
#define REAL_TEMPLATE
typedef real_t double;
#endif

...
REAL_TEMPLATE real_t CASADI_PREFIX(polyval)(const real_t* p, int n, real_t x) {
...
}
```

**Comment by jgillis** [comment]
@jaeandersson  close?
