### ISSUE TITLE
if_else() jacobian broken when using MX

### ISSUE THREAD

**Issue by jbaayen** [casadi/casadi#1792]
Using CasADi 2.4.3, the following code

```
x = MX.sym('x')
F = MXFunction([x], [if_else(x > 10, x, 0)])
F.init()
print F.jac(0, 0)

x = SX.sym('x')
F = SXFunction([x], [if_else(x > 10, x, 0)])
F.init()
print F.jac(0, 0)
```

results in

```
[jorn@mac test]$ python test.py 
0
(10<x)
```

I would expect to get (10<x) for both MX and SX. 

This issue breaks our B-Splines when using MX symbols.

**Comment by jaeandersson** [comment]
If you add an argument "False" to "if_else", MX should behave like SX. The default behavior for MX is to be "short-cicuiting". I tested it for the above case, but there is a missing feature for it to work:
```python
from casadi import *

# SX, never short-cirtuiting
x = SX.sym('x')
J = jacobian(if_else(x > 10, x, 0), x)
print J
F = Function('F', [x], [J])
print F(9), F(11)

# MX, non-short circuiting
x = MX.sym('x')
J = jacobian(if_else(x > 10, x, 0, False), x)
print J
F = Function('F', [x], [J])
print F(9), F(11)

# MX, short circuiting
x = MX.sym('x')
J = jacobian(if_else(x > 10, x, 0), x)
print J
F = Function('F', [x], [J])
print F(9), F(11)

```
Returns
```
(10<x)
0 1
(10<x)
0 1
@1=(10<x), fwd1_switch(@1, x, switch(@1, x){0}, 00, 1){0}
Traceback (most recent call last):
  File "if_else.py", line 22, in <module>
    print F(9), F(11)
  File "/Users/jaeandersson/local/casadi/casadi.py", line 12260, in __call__
    ret = self.call(args)
  File "/Users/jaeandersson/local/casadi/casadi.py", line 11305, in call
    return _casadi.Function_call(self, *args)
RuntimeError: The assertion "s==sparsity_out(i)" on line 168 of file "/Users/jaeandersson/dev/casadi/casadi/core/function/switch.cpp" failed.
Not implemented
```

**Comment by jbaayen** [comment]
I guess you tested with version 3, considering the RuntimeError you get (I don't get one)?

How much work would it be to implement the missing feature?

**Comment by jaeandersson** [comment]
> I guess you tested with version 3, considering the RuntimeError you get (I don't get one)?

Possibly.

> How much work would it be to implement the missing feature?

Not too much. I'll try to have it included in the 3.1 release, due in the next couple of weeks.

**Comment by jgillis** [comment]
@jbaayen Seems to me that 'F = MXFunction([x], [if_else(x > 10, x, 0,False)]'  works just fine in 2.4.* ?

**Comment by jbaayen** [comment]
@jgillis, yes, indeed it does. However, I then run into another issue: #1805.

**Comment by jgillis** [comment]
@jaeandersson fixed?

**Comment by jaeandersson** [comment]
Yes, should be fixed.
