### ISSUE TITLE
Error when iterating over SX, MX and DM arrays in CasADi 3.0.0

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1796]
In numpy, I can iterate over arrays as exemplified below:

    import numpy as np

    mat = np.random.rand(3,3)

    for e in mat:
        print e

I also could do this with DMatrix objects in previous CasADi versions. Now in CasADi 3.0.0, I get:

    import numpy as np
    import casadi as ca

    mat = ca.DM(np.random.rand(3,3))

    for e in mat:
        print e

    [...]

    RuntimeError: The assertion "stop<=len" on line 63 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/slice.cpp" failed. 
    Slice (start=9, stop=10, step=1) out of bounds with supplied length of 9

so it seems to go at least one step to far; the first 9 elements are being printed just fine. The same thing happens when iterating over SX and MX objects.

**Comment by jaeandersson** [comment]
The CasADi matrix classes are not iterable, cf.  https://groups.google.com/forum/#!topic/casadi-users/fnvRCrnwX_I

**Comment by adbuerger** [comment]
Oh, ok, thanks for pointing this out to me!
