### ISSUE TITLE
Overzealous inline in MX Function.call

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1798]
As apparent from the output of the below script, inlining is applied even though never_inline is set to True:
```py
from casadi import *
x=MX.sym("x")

F = Function("F",[x],[sin(x)])
print F.call([x],False,True)
```
```
[MX(sin(x))]
```
Affects 3.0.0 and on

**Comment by jgillis** [comment]
Information about inlining goes down the drain right here: https://github.com/casadi/casadi/blob/master/casadi/core/function/function_internal.cpp#L1761

**Comment by ghorn** [comment]
wow, nice catch
