### ISSUE TITLE
problem by compiling source casadi

### ISSUE THREAD

**Issue by catta134** [casadi/casadi#1799]
hi, i'm a student in control engeneering, for i project i need to install and work by casadi in linux and i need the source code, so i decided to do the procedure by complie the source code..
when i do the making, i have an error, and you can see in the attach file.. the library swig is correctly install in package python version 2.7. i have install python by the default setting. i hope to take a solution early, i'm not a good programmer so can you help me..
thanks a lot..
![screenshot - 05312016 - 10 34 19 pm](https://cloud.githubusercontent.com/assets/19674704/15689669/60ab07b2-2780-11e6-9d94-f42b9a25c302.png)

regards

**Comment by jgillis** [comment]
Hi there!

It appears from the screenshot that you are doing an in-source build?
Could you try with a build from within a 'build' directory?

`mkdir ~/Deskstop/casadi/build && cd build && cmake .. && make`

**Comment by catta134** [comment]
thanks a lot you have solved my problem..

**Comment by jaeandersson** [comment]
@jgillis Don't in-source builds work? They are very natural if you're using e.g. eclipse.

**Comment by jgillis** [comment]
It's not tested in any case; and if its not tested, it will break eventually..

**Comment by mvukov** [comment]
@jaeandersson Eclipse does not work well with in-source-tree builds, preferred is something like:
casadi_wokspace/src (git-cloned source tree)
casadi_wokspace/build

**Comment by jaeandersson** [comment]
Thanks, @mvukov!
