### ISSUE TITLE
is_equal false negative for some MX constants

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1806]
```
> is_equal(MX([1,1]), MX([1,1]))
False

is_equal(MX(1), MX(10) <= MX(11))
False
```

works with SX and DM

**Comment by jaeandersson** [comment]
`is_equal(MX([1,1]), MX([1,1]))` is false due to the lack of constant caching. It's because the "checking depth" is 0 by default. I've now implemented equality checking so that `is_equal(MX([1,1]), MX([1,1]), 1)` is true however.
