### ISSUE TITLE
ImplicitFunction: Cannot evaluate with SX

### ISSUE THREAD

**Issue by jbaayen** [casadi/casadi#1808]
If I create an ImplicitFunction, I can only evaluate it using MX symbols, and not using SX:

```
x = SX.sym('x')
y = SX.sym('y')
f = SXFunction('f', [y, x], [y - x**2])
F = ImplicitFunction('F', 'newton', f)

# Works:
z = MX.sym('z')
F.call([0.0, z])

# Fails:
z = SX.sym('z')
F.call([0.0, z])
```

The latter call returns 

> RuntimeError: The assertion "canEvalSX()" on line 1403 of file "/usr/src/JModelica/ThirdParty/CasADi/CasADi/casadi/core/function/function_internal.cpp" failed. 
> Please notify the CasADi developers.

This is an issue for us as we prefer to stay with SX symbolics as long as possible, as they perform much better for our type of problem.

This is using CasADi 2.4.3.

**Comment by jgillis** [comment]
The newton rootfinder/implictfunction is basically a while loop with a stopping criterion performing newton steps. While the newton steps can in principle be expressed with SX, the loop cannot.

If you don't mind to have a (preset) fixed number of iterations without stopping criterion, you could expand into SX in practice.

**Comment by jgillis** [comment]
The newton rootfinder/implictfunction is basically a while loop with a stopping criterion performing newton steps. While the newton steps can in principle be expressed with SX, the loop cannot.

If you don't mind to have a (preset) fixed number of iterations without stopping criterion, you could expand into SX in practice.

**Comment by jbaayen** [comment]
Aha, I see. Just for my own conceptual understanding, why can a while loop with a stopping criterion be expressed with MX, but not with SX? 

Having a preset fixed number of iterations would have a significant negative performance impact in our case.

**Comment by jaeandersson** [comment]
> can a while loop with a stopping criterion be expressed with MX

Yes, if the while loop is part of a function (like `F` here).

**Comment by jgillis** [comment]
Currently, SX has no notions of Functions. So an SX node could not call one in a loop.
