### ISSUE TITLE
typemap confusion in extending_casadi

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1811]
Consider adding the following methods to `extending_casadi.hpp/cpp`:
```
    void foobar(const std::vector<DM> & test) {
      std::cout << test << std::endl;
    }
    
    void foobar(const std::vector<SX> & test) {
      std::cout << test << std::endl;
    }
```

You'll see from 
```
python -c "from extending_casadi import *;from casadi import *;x=SX.sym('x');foobar([x])"
```
that you get `[DM(nan)` instead of `[SX(x)]`

**Comment by jgillis** [comment]
The reason for different behaviour appears to be SWIG_PYTHON_CAST_MODE, which is #defined in `casadi.i` and `extending_casadi.i`.
There are several strange things about this:
 * in casadi, all ifdefs involving SWIG_PYTHON_CAST_MODE appear _after_ the #define
 * in extending_casadi, all ifdefs involving SWIG_PYTHON_CAST_MODE appear _before_ the #define
 * SWIG_PYTHON_CAST_MODE is governed by "-castmode", "-nocastmode" flag of swig. Why do we define it explicitly?

In my setup, removing #define SWIG_PYTHON_CAST_MODE makes null difference for CasAdi and removes this bug.

**Comment by jgillis** [comment]
@jaeandersson    any thoughts on removing `#define SWIG_PYTHON_CAST_MODE ` ?

**Comment by jaeandersson** [comment]
> @jaeandersson any thoughts on removing `#define SWIG_PYTHON_CAST_MODE` ?

I'm not sure what the purpose of it was in the first place. Those workarounds shouldn't be needed at all and if the code is cleaned up, I think the issues will go away. I'm happy with anything that removes hacks like `SWIG_PYTHON_CAST_MODE` while not breaking anything.
