### ISSUE TITLE
Add general purpose `classify_linear` function

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1816]
I'm proposing a function that works on expressions to classify null/linear/nonlinear dependency.
The interface would be as in https://gist.github.com/jgillis/5aebf6b09ada29355418783e8f60e8ef, but then efficiently implemented using a sparsity sweep, as we had in the old SNOPT interface.

**Comment by jaeandersson** [comment]
This sounds like a weird design to me. I think it would be much more natural to have two separate functions, one for checking if "x depends on y" and another for checking if "x depends linearly on y". If you really have to combine these two checks into one (why?) I would suggest outputting two boolean vectors, not a vector with 0/1/2.

**Comment by jgillis** [comment]
why -> to compute the Jacobian only once
