### ISSUE TITLE
Problem using HSL binaries with CasADi on Linux?

### ISSUE THREAD

**Issue by i25959341** [casadi/casadi#1824]
Using the link, https://github.com/casadi/casadi/wiki/Obtaining-HSL, i managed to get the HSL library , but it s still not working due to the following error.

```
 Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
/homes/kl909/lib/libhsl.so: undefined symbol: GOMP_taskwait

```

**Comment by jgillis** [comment]
Ah sorry I missed this. Please re-post on the forum if this still persists.
Fwiw, this is the build script that we use internally to build a functioning HSL: https://github.com/casadi/testbot/blob/merged/recipes/hsl_trusty.sh
