### ISSUE TITLE
SX __array__ methods error

### ISSUE THREAD

**Issue by pstjohn** [casadi/casadi#1831]
Moving from 2.4.4 to 3.0.0 seems to have broken some of the functionality of the SX objects:

In 2.4.4:

``` python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import casadi
>>> casadi.__version__
'2.4.4'
>>> casadi.SX.sym('x', 4).__array__()
array([[SX(x_0)],
       [SX(x_1)],
       [SX(x_2)],
       [SX(x_3)]], dtype=object)
>>> [x for x in casadi.SX.sym('x', 4)]
[SX(x_0), SX(x_1), SX(x_2), SX(x_3)]
```

In 3.0.0:

``` python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import casadi
>>> casadi.__version__
'3.0.0'
>>> casadi.SX.sym('x', 4).__array__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "casadi/casadi.py", line 9238, in __array__
    return self.full()
  File "casadi/casadi.py", line 8283, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SX, name)
  File "casadi/casadi.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "casadi/casadi.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: Unkown attribute: <class 'casadi.casadi.SX'> has no attribute 'full'.
>>> [x for x in casadi.SX.sym('x', 4)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "casadi/casadi.py", line 9188, in __getitem__
    return self.get(False, s)
  File "casadi/casadi.py", line 8371, in get
    return _casadi.SX_get(self, *args)
RuntimeError: The assertion "stop<=len" on line 63 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/slice.cpp" failed. 
Slice (start=4, stop=5, step=1) out of bounds with supplied length of 4
```

These were both done with the Mac OSX binaries

**Comment by jaeandersson** [comment]
We deliberately dropped the ability to iterate over CasADi matrices, since we felt that it was ambiguous what iterating over a sparse matrix actually means. To get a Python list of nonzeros, do `SX.sym('x', 4).nonzeros()` instead of `[x for x in casadi.SX.sym('x', 4)]`

**Comment by jaeandersson** [comment]
(the error message is pretty miserable though...)

**Comment by jaeandersson** [comment]
This needs to be fixed. It should work or fail gracefully. Right now it tries to call "full" for SX, which isn't even defined.

**Comment by jaeandersson** [comment]
@jgillis How do we want `__array__` to behave for the symbolic types? My vote is to remove it completely. If you're mixing CasADi and numpy, you should always do explicit type conversions IMO.

**Comment by pstjohn** [comment]
What would be the recommended way of casting an SX array to a numpy array in v3? (i.e., a numpy array full of symbolic elements of the same size as the original SX). I found that a useful feature for linear algebra involving both scalars + symbolics

**Comment by jaeandersson** [comment]
Mixing numpy arrays and CasADi matrices has never worked well. Numpy containers are simply not designed to have symbolic datatypes like CasADi matrices and it has been a patchwork to try to get it working, and it tends to break every time there is a numpy update. Furthermore, it's very inefficient (a n-by-m dense matrix where each element is stored as a 1-by-1 sparse matrix!) and restrictive in what you can do with it. Working with CasADi matrix operations can be orders of magnitude more efficient.

So rather than having a hacky interface that is a nightmare to maintain and will break constantly, I'd rather not support it at all.

**Comment by pstjohn** [comment]
Fair enough. My applications mainly follow the collocation examples, but I can appreciate that in other use cases this can cause some problems. There the memory inefficiency doesn't matter as much, since you re-concatenate to vectors before solving the problem, and the setup time is negligible compared to the solution. Thanks for the help sorting this out though! (Porting older code to python 3 and updating to the newest casadi... )

I suppose it would be easier to keep everything straight if casadi implemented N-dimensional arrays (so you could organize variables by [finite element, degree, state]), but that might not be a trivial extension.

**Comment by pstjohn** [comment]
As a slightly related question: is this the intended functionality of `cs.dot`?

```python
>>> import casadi as cs
>>> x = cs.SX.sym('x', (3,3))
>>> y = cs.SX.sym('y', (3,3))
>>> cs.dot(x,y).shape
(1, 1)
```

I would have expected a more standard matrix multiplication:
```python
>>> import numpy as np
>>> x = np.eye(3)
>>> y = np.eye(3)
>>> x.dot(y).shape
(3, 3)
```

**Comment by jaeandersson** [comment]
> is this the intended functionality of `cs.dot`?

Yeah. We decided to try to be consistent with MATLAB/Octave naming conventions when possible. And in MATLAB, "dot" means inner product, previously called called "inner_prod" in CasADi. For the same reason, matrix multiplication is called "mtimes" now. Cf. https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0

**Comment by pstjohn** [comment]
Gotcha, thanks again - (sorry, should have seen that...)
As an FYI [PEP465](https://www.python.org/dev/peps/pep-0465/) was accepted: Could be neat to implement if you're looking for an unambiguous way to specify matrix multiplication.

**Comment by jaeandersson** [comment]
> As an FYI PEP465 was accepted: Could be neat to implement if you're looking for an unambiguous way to specify matrix multiplication.

Yeah, implementing `__matmul__` is straigtforward. We'd probably support both `mtimes(A, B)` and `A @ B` in this case.

**Comment by karry3775** [comment]
How do we create a mutable array in casadi? I would like to define an array of definite size and then assign value to it with a loop. I am using MX as of now, but I can't convert it to numpy arrays or plot it.

**Comment by jaeandersson** [comment]
> @karry377 question for forum
