### ISSUE TITLE
Undefined function 'SwigGet' for input arguments of type 'char'.

### ISSUE THREAD

**Issue by gh4St** [casadi/casadi#1836]
Hello

I built CasADi v2.4.2 from source on Linux. The build process with the modified SWIG is tedious, but worked in the end. Now, finally, I can test it but my casadiMEX throws this error.

```
Undefined function 'SwigGet' for input arguments of type 'char'.

Error in casadi.GenSX.sym (line 685)
     [varargout{1:nargout}] = casadiMEX(389, varargin{:});
```

Could this be a path issue? I had the CasADi and the SWIG folder on my MATLAB path.
I would be grateful for any inputs/ideas.

Thanks a lot!

**Comment by jaeandersson** [comment]
You need to add the path which has "+casadi" to your MATLAB path.  Did you do that?

**Comment by gh4St** [comment]
Well, apparently one can not add a package folder to the MATLAB path but needs to add its parent folder. I did that. In which file is the function SwigGet?

**Comment by jaeandersson** [comment]
The file `SwigGet.m` should be in the same directory as `+casadi`. I.e. the same as your install prefix.

**Comment by gh4St** [comment]
Ok, thanks. So the file SwigGet.m is not in my casadi install directory at all. Could this be a consequence of using v2.4.2 together with the latest commit of the SWIG repository from https://github.com/jaeandersson/swig? The following casadi commit might be a hint that this is indeed the case: https://github.com/casadi/casadi/commit/cf22cfa752e4ebf877d6405eb84daa83b848aa44

**Comment by jaeandersson** [comment]
Yeah, we're developing SWIG-MATLAB/Octave and CasADi at the same time. They need to be in sync for it to work.
