### ISSUE TITLE
Bring back monitoring functionality in OracleFunction

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1841]
The "monitoring" functionality was useful but was dropped during refactoring. Since all the function calls to user problem functions are now redirected via `OracleFunction::calc_function`, this feature can easily be reintroduced in the OracleFunction class in a convenient way.

My suggestion would be to add an option called "monitor" and have all the monitored functions listed as a pipe separated list.  Note that you can get a complete list of functions by calling `F.get_function()`:
```python
# Which functions are there?
F = Function('F', ..., ...)
print "all monitors: ", F.get_function()
# Montor eval_f and eval_g:
F = Function('F', ..., ..., {'monitor': 'eval_f|eval_g'})
```
This list would be used to set an additional field in the `RegFun` structure:
```c++
    // Information about one function
    struct RegFun {
      Function f;
      bool jit;
      bool monitored; // <-- new
    };
```

**Comment by jgillis** [comment]
#1782

**Comment by jaeandersson** [comment]
Ah, forgot that we already had an issue for this.
