### ISSUE TITLE
problemi with function vertcat

### ISSUE THREAD

**Issue by catta134** [casadi/casadi#1844]
hi, i have a problem with function vertcat, i have followedw your tutorial on youtube, and i try a simple code on python by linux and editor spider. I link you my code and my error, i hope to take a solution for me
thanks
regards
![schermata del 2016-07-31 15-28-32](https://cloud.githubusercontent.com/assets/19674704/17276804/7bb97b00-5733-11e6-8af9-31d2911f6203.png)

**Comment by jaeandersson** [comment]
It's probably a version mismatch. The video tutorial was using CasADi 2.x. In CasADi 3.0, the syntax for vertcat changed from `vertcat([a, b, c])` to `vertcat(a, b, c)`

**Comment by catta134** [comment]
ok, there is a page that refrance the change between casadi 2.2 and casadi 3.0,
thanks a lot

**Comment by catta134** [comment]
hi, and if I want to use struct_symMX(...) and then use vertcat, how can i do if vertcat don't like [ ]?..
there is other way to do this?
thnaks

**Comment by jgillis** [comment]
If you have a list already:
`collection = [a, b, c]`,

You can still use vertcat as:
`vertcat(*collection)`

**Comment by catta134** [comment]
sorry. but doesn't work..
i have:

V[ "Q", k, ["q0", "q1", "q2"] ]
Out[48]: 
[MX(vertsplit(vertsplit(V){200}){0}),
 MX(vertsplit(vertsplit(V){200}){1}),
 MX(vertsplit(vertsplit(V){200}){2})]
 and when i do 
vertcat(V[ "Q", k, ["q0", "q1", "q2"] ])
the output say me

  File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 15659, in _vertcat
    return _casadi._vertcat(*args)

NotImplementedError: Wrong number or type of arguments for overloaded function '_vertcat'.
  Possible Python usages are:
    vertcat([Sparsity] )
    vertcat([MX] )
    vertcat([IM ] )
    vertcat([DM ] )
    vertcat([SX] )
You have: _vertcat(([MX]))
You have: _vertcat([MX])

how can I solve this mistake, i should write this structure in another way, as use numpy array, or I should write this list that is type Struct_symMX differently..
thanks for answer.

**Comment by jgillis** [comment]
And `vertcat(*V[ "Q", k, ["q0", "q1", "q2"] ])`?

**Comment by catta134** [comment]
ok, in this way a pass the pointer's argument of struct, I thought that notation is not correct.. ok
thanks a lot, this ticket is close..

**Comment by jgillis** [comment]
This concept is called "unpacking": https://docs.python.org/2/tutorial/controlflow.html#unpacking-argument-lists
