### ISSUE TITLE
nlpsol failed with user-defined functions in version 3.1.0-RC1

### ISSUE THREAD

**Issue by nxtruong** [casadi/casadi#1854]
I'm using version 3.1.0-RC1 in Matlab R2015b. I need to solve an NLP that uses a user-defined function (by subclassing Callback) which has a user-defined Jacobian (by overloading has_jacobian and get_jacobian). nlpsol() failed with the following error message:

> Error using casadiMEX
The assertion "hasDerivative()" on line 2498 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/function/function_internal.cpp" failed.
Please notify the CasADi developers.

> Error in casadi.nlpsol (line 857)
  [varargout{1:nargout}] = casadiMEX(860, varargin{:});

A minimal working example that results in this error is given below.

**File testfun.m**
```matlab
classdef testfun < casadi.Callback
    methods
        function self = testfun(name)
            self@casadi.Callback();
            construct(self, name);  % This must be last statement
        end
        
        function v=get_n_in(self)
            v = 1;
        end
        
        function v=get_n_out(self)
            v = 1;
        end
        
        function argout = eval(self, argin)
            x = full(argin{1});
            argout = {x^2};
        end
        
        function b = has_jacobian(self)
            b = true;
        end
        
        function J = get_jacobian(self, name, opts)
            J = testfunj(name);
        end
    end
end
```

**File testfunj.m**
```matlab
classdef testfunj < casadi.Callback
    methods
        function self = testfunj(name)
            self@casadi.Callback();
            construct(self, name);  % This must be last statement
        end
        
        function v=get_n_in(self)
            v = 1;
        end
        
        function v=get_n_out(self)
            v = 1;
        end
        
        function argout = eval(self, argin)
            x = full(argin{1});
            argout = {2*x};
        end
    end
end
```

**Code that causes error**
```matlab
import casadi.*
f = testfun('f');

x = MX.sym('x');
y = MX.sym('y');

nlp = struct('x', [x;y], 'f', 2*x-y, 'g', f(x)-y);
solver = nlpsol('solver', 'ipopt', nlp);  % <-- error
res = solver('x0', [0;0], 'lbx', [-2; -inf], 'ubx', [2; inf], 'lbg', 0, 'ubg', 0);
x_opt = full(res.x)
f_opt = full(res.f)
```

**Comment by nxtruong** [comment]
For more information, a similar code for Python 2.7 with CasADi 3.1.0-RC1 results in the following similar error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/truong/software/casadi-py27-3.1.0-rc1/casadi/casadi.py", line 9587, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: When trying to check the assertion "hasDerivative()" on line 2498 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/function/function_internal.cpp", caught:
The assertion "self_!=0" on line 116 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/function/callback_internal.cpp" failed.
Callback object has been deleted

The code is given below.
```python
from casadi import *

class testfunj(Callback):
    """Test function Jacobian class."""
    def __init__(self, name, opts={}):
        Callback.__init__(self)
        self.construct(name, opts)
    
    def get_n_in(self): return 1
    def get_n_out(self): return 1

    def eval(self, arg):
        x = arg[0]
        f = 2*x
        return [f]


class testfun(Callback):
    """Test function class."""
    def __init__(self, name, opts={}):
        Callback.__init__(self)
        self.construct(name, opts)
    
    def get_n_in(self): return 1
    def get_n_out(self): return 1

    def eval(self, arg):
        x = arg[0]
        f = x**2
        return [f]

    def has_jacobian(self): return True
    def get_jacobian(self, name, opts):
        return testfunj(name)

f = testfun("f")
x = MX.sym("x")
y = MX.sym("y")
nlp = {'x': vertcat(x,y), 'f':2*x-y, 'g':f(x)-y}
solver = nlpsol('solver', 'ipopt', nlp)  # <-- cause error
```

**Comment by jgillis** [comment]
Thank you for raising this issue!
The error is caused by the fact that you supplied first-derivatives only, while our interface's Hessian strategy is full-Hessian by default.

Either switch to first-order information only:
```
options = {"ipopt.hessian_approximation" : "limited-memory"}
solver = nlpsol('solver', 'ipopt', nlp, options) 
```
, or provide a jacobian for testfunj as well..
