### ISSUE TITLE
information about possible solution to execute a code function after substitution value to variables

### ISSUE THREAD

**Issue by catta134** [casadi/casadi#1855]
hi, I will be short. I should insert a function where I must calculate inversion of a matrix square not singular, but in this matrix there are some element SX's type. to invert matrix i try to use function in library  numpy.linalg but give an error when i execute code. my ask is this, there is a way to say to the function that the execution of the code should be run after insert the value of the variables and not when I define the function, because this could be the error that python console give to me.
I attach a screenshot about my program.
this program could be a test before insert some equation of inverting matrix by use the dae solver.
regards
  
![screenshot from 2016-08-22 11-26-05](https://cloud.githubusercontent.com/assets/19674704/17849935/4d5f5f16-685b-11e6-97bd-cb53979b4271.png)

**Comment by jgillis** [comment]
Hi there,

In general, yes you can embed pieces of foreign numerical code (C++,Python,Matlab) inside a CasADi MX graph; that's a feature we have. However, I don't think this feature is what you need here.

In this case, you could work with CasADi linear solvers.

Either work with a non-pivoting algorithm directly on symbolic SX:
```py
x=SX.sym("x")
A=blockcat([[1,2,3],[1,3,4],[x,1,-3]])
f = Function('f',[x],[casadi.solve(A,DM.eye(3))])
f = Function('f',[x],[casadi.inv(A)]) # or equivalent
```,
or use one of pivoting numerical codes we have interfaced (together with MX):
```py
x=MX.sym("x")
A=blockcat([[1,2,3],[1,3,4],[x,1,-3]])
f = Function('f',[x],[casadi.solve(A,DM.eye(3),"lapacklu")])
```

Good luck!

Please post follow-up questions to http://forum.casadi.org.

**Comment by catta134** [comment]
thanks a lot
