### ISSUE TITLE
Add possibility to have mex function return dense matrices

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1858]

**Comment by jgillis** [comment]
@jaeandersson  comments before merge?

**Comment by jaeandersson** [comment]
Yeah... I'm not sold on that implementation. I think that the return type should be predictable, not depend on how many nonzero entries there are. You make a small change in your model and the output becomes a different type - that doesn't feel right.

I thought you'd make it an option for the CodeGenerator class.

**Comment by jaeandersson** [comment]
@ghorn - Please weigh in

**Comment by jgillis** [comment]
Yeah maybe; ideas:
'mex_dense_outputs' OT_BOOLVECTOR is predictable,
'mex_dense' OT_INTEGER (0: always sparse, 1: decide based on casadi sparsity, 2: always dense)

**Comment by jaeandersson** [comment]
What is the use case for this again? Converting from dense to sparse must be really fast.

**Comment by jgillis** [comment]
Not speed; convenience.
Apparently some (all?) optimization methods in Matlab (FMINCON at least) bark when the returned function value is sparse.
I failed to produce a generic pure-matlab function that transforms a mex file and applies sparse/full on the outputs. One needs to known the number of ouputs in order to catch all of them afaict.
The only way to make our mex work with fmincon at present is to write a specific Matlab function wrapping the mex

**Comment by jaeandersson** [comment]
How about
```matlab
function varargout = fullify(f, varargin)
  [varargout{1:nargout}] = f(varargin{:});
  for i=1:numel(varargout)
    varargout{i} = full(varargout{i});
  end
end
```

**Comment by jgillis** [comment]
Ah clever. You pass through the information of nargout from the user.. Didn't think of that

**Comment by jgillis** [comment]
Nice! Now something that returns a function..

**Comment by jgillis** [comment]
```
function f_full = function_full(f)
   f_full = @(varargin) fullify(f,varargin{:});
end
```

**Comment by jgillis** [comment]
Let's find a proper name and add it to casadi..

**Comment by jaeandersson** [comment]
Note that the generated functions always have a first string argument, so they are already not drop-in-replacements for a standard function. I'm thinking it's better to be consistent with the return type so that generated functions can be interchangeable.

**Comment by jgillis** [comment]
Right, its not drop-in, but it can be used as drop-in with a simple lambda.
Having a outputs dense is not achievable with a lambda, unless we ship your proposed helper function.

**Comment by jaeandersson** [comment]
How about a compilation macro that has the generated functions return dense matrices?
```c
mxArray* CASADI_PREFIX(to_mex)(const int* sp, const real_t* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
#ifdef MEX_DENSE_RETURN
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  densify(x, sp, d, (double*)mxGetData(p));
#else
  mxArray* p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
  int i;
  mwIndex* j;
  for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *sp++;
  for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *sp++;
  if (x) {
    double* d = (double*)mxGetData(p);
    for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
  }
#endif
  return p;
```

**Comment by jgillis** [comment]
The point being that the codegenerator options API is not getting polluted?

**Comment by jaeandersson** [comment]
The point would be more that the generated code (before compilation) would be portable. Cf. the handling of `CODEGEN_PREFIX` or `real_t`. You can specify your own type by defining the `real_t` macro.

**Comment by jgillis** [comment]
[casadi-users] Code generation and function call  forum post

**Comment by jaeandersson** [comment]
How about making it a compile-time option?
```c
#ifndef CASASI_MEX_NOSPARSE
...
#endif
```

**Comment by jaeandersson** [comment]
Matlab codegen will still be a problem.

**Comment by jaeandersson** [comment]
This is now supported. (`CASADI_MEX_NO_SPARSE` define)
