### ISSUE TITLE
Announce: Fedora/EL7 packages for Casadi 

### ISSUE THREAD

**Issue by mccullerlp** [casadi/casadi#1860]
Here is my user repository for Fedora and Redhat/Centos/Scientific Linux 7 packages of Casadi. It also builds on fedora up to 23. The build logs look like it is failing on 24 due to a more pedantic GCC 6 (ambiguous symbol lookup error) in that distribution.

https://copr.fedorainfracloud.org/coprs/mcculler/Casadi/

Posting in case you are interested in linking on unofficial downloads or for users to find here. Ipopt is compiled in but not too many of the other optimizers as the official repositories don't have them. Clang support is also missing as EL7 doesn't build the clang libs for LLVM. Perhaps I'll make a build that allows it on Fedora which does include them.

**Comment by jgillis** [comment]
Very nice job! I'll put the link on the wiki.
Could you announce this on the forum?

**Comment by jgillis** [comment]
Ah one thing: could you replace https://github.com/casadi/casadi/wiki with http://casadi.org?
One day in the future, we will have a proper website. The wiki is just the current redirection for our official adress..
