### ISSUE TITLE
User-Manual compilation on TexShop (3.71)

### ISSUE THREAD

**Issue by sebchalmers** [casadi/casadi#1861]
Compilation does not work:

1) ./casadi-users_guide.tex:124: Undefined control sequence.
2) ./casadi-users_guide.tex:1455: Missing $ inserted.
3) ./casadi-users_guide.tex:1456: Missing $ inserted.

**Comment by jgillis** [comment]
Hey Seb,

Yeah, building documentation locally is not really supported at the moment..
Alternatives are:
Online: http://docs.casadi.org click select version from bottom and choose user guide
Offline: download example_pack from http://files.casadi.org

You could also spy on the build script for Ubuntu 14.04 that compiles the documentation: https://github.com/casadi/binaries/blob/docs/.travis.yml

**Comment by sebchalmers** [comment]
Ok thanks !

I also noticed (?) that the casADi/Matlab syntax has changed since last winter ? The solutions to the exercises are not running anymore ?

Best,
Sebastien Gros
Assistant Professor
+46 31 772 15 55

Department of Signals and Systems
Chalmers University of Technology
SE-412 96 Göteborg, SWEDEN



On 06 Sep 2016, at 13:12, jgillis <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Seb,

Yeah, building documentation locally is not really supported at the moment..
Alternatives are:
Online: http://docs.casadi.org<http://docs.casadi.org/> click select version from bottom and choose user guide
Offline: download example_pack from http://files.casadi.org<http://files.casadi.org/>

You could also spy on the build script for Ubuntu 14.04 that compiles the documentation: https://github.com/casadi/binaries/blob/docs/.travis.yml

**Comment by jgillis** [comment]
Right, with feedback from the core we decided to a refactor of the way functions are called. It's documented here: https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0#new-calling-syntax

**Comment by sebchalmers** [comment]
Ok, thanks for the info.

I’ll give a course in NTNU next week and plan to use casADi and reuse some of the exercises of Freiburg. I’ll try to adjust the documents & solutions.

Best,
Sebastien Gros
Assistant Professor
+46 31 772 15 55

Department of Signals and Systems
Chalmers University of Technology
SE-412 96 Göteborg, SWEDEN



On 06 Sep 2016, at 13:35, jgillis <notifications@github.com<mailto:notifications@github.com>> wrote:


Right, with feedback from the core we decided to a refactor of the way functions are called. It's documented here: https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0#new-calling-syntax

**Comment by jgillis** [comment]
Turns out there was simply a typo in the tex source. Should compile fine now in 3.1
