### ISSUE TITLE
Operation that reads matrix from file

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1867]
Sometimes it makes sense to allow matrices to be read from a file:

``` matlab
% Matrix whose data is read at first call
x = MX.sym('x');
data = MX.load('A.txt', 2, 3);
f = Function('f', {x}, {data*x});
% Generate data and call
A = [1 2 3; 4 5 6];
dlmwrite('A.txt',A);
Ax = f(4);
```

**Comment by jgillis** [comment]
Related: operation that reads matrix from a piece of memory. (e.g. for efficient image processing)

**Comment by jaeandersson** [comment]
> Related: operation that reads matrix from a piece of memory. (e.g. for efficient image processing)

How's that even possible?

**Comment by jgillis** [comment]
This was added in 2072da5359b7448ff8672d00e45210075f9f33c6 (casadi 3.5)
