### ISSUE TITLE
Conda-forge recipe

### ISSUE THREAD

**Issue by pstjohn** [casadi/casadi#1868]
So I'll open this up in a new issue from #1716, but I think it could be a really nice feature to support a conda recipe for casadi. The advantages of conda is be that you can create isolated environments that are built from configure files, so you can easily make sure you have the same dependencies from user to user (and makes sharing / publishing results a lot easier).

One of the first steps would likely be to get a conda recipe working for IPOPT, which I'm working on in conda-forge/staged-recipes#1607. Also discussed in coin-or/COIN-OR-OptimizationSuite#3

**Comment by pstjohn** [comment]
casadi is up and running on conda-forge! Linux and mac users can now install casadi directly using conda (sadly the dependency chain doesn't currently support windows, this could change in the future depending on interest).

After installing either [miniconda](https://conda.io/miniconda.html) or [anaconda](https://www.continuum.io/downloads), installation is as easy as

```bash
conda config --add channels conda-forge 
conda install casadi
```

You should then be able to load up python and `import casadi` with no problems. We're currently building against python 2.7, 3.5, and 3.6, and numpy 1.12. It also includes the ipopt interface.

If you get errors and don't have a recent conda install, try a `conda update conda`.


We should channel error reports specific to the conda install to the relevant feedstock, [conda-forge/casadi-feedstock](https://github.com/conda-forge/casadi-feedstock)

Let me know if you have any other questions? I'm not sure how you would want to merge this into the existing install instructions (if at all), let me know if there's anywhere I can help on that front.

**Comment by pstjohn** [comment]
I'll close the issue too. (Centos 6 builds work with the conda binaries).

**Comment by jaeandersson** [comment]
Awesome! I updated the [instructions](https://github.com/casadi/casadi/wiki/InstallationInstructions). Does that look good?

**Comment by pstjohn** [comment]
Yup! Looks great, thanks for the acknowledgement!

It ships with mumps for ipopt: if there are other third-party solvers you think I should add that come with permissive licenses, I can certainly work on getting those added as well. It uses openblas, since there were license concerns with building against the MKL libraries from conda.

If anyone's looking for more information about the process, the [build script](https://github.com/conda-forge/casadi-feedstock/blob/master/recipe/build.sh) is public in the feedstock repository, and you can even see the [verbose build output](https://circleci.com/gh/conda-forge/casadi-feedstock/1) on the various CI systems.

(mostly FYI, I wouldn't bog down the install instructions with those details)

**Comment by jgillis** [comment]
Thanks for your contribution; first class!
