### ISSUE TITLE
SX function call node

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1869]
After some thinking, I think that it should be possible to efficiently embed function calls into SX expressions. I would restrict to calls with simplified calling syntax (i.e. `void f(const double* arg, double* res)`).

Major task to implement, but could have profound impact to the kind of problems that could be handled by SX. I don't remember if there was already an issue created for this, couldn't find any.

**Comment by jgillis** [comment]
Related branch: https://github.com/casadi/casadi/tree/mx_in_sx

**Comment by jgillis** [comment]
Extra rationale: Callbacks

**Comment by jgillis** [comment]
Converged on this strategy:
Allows to embed arbitrarily shaped Functions into an SX graph.

 * Does not touch `ScalarAtomic / SXAlg`, instead, extra info is store in a separate data structure in SXFunction
 * Introduces SX Nodes `CallSX` and `OutputSX`
 * Just like MX OutputNode, `OutputSX` has op -1 and is disregarded when sorting into an algorithm.
 * Primary use-case: multi-dimensional lookup tables

Sample outputs from unittests:

```
Algorithm:
@0 = input[0][0];
@1 = input[1][0];
@2 = (@0/@1);
@3 = input[0][1];
@3 = (@3/@1);
@4 = input[0][2];
@4 = (@4/@1);
@5 = 10;
@6 = input[2][0];
@5 = (@5*@6);
@6 = (@1*@6);
[@2,@3,@4,@5,@7] = f(@2,@3,@4,@5,@6);
@8 = (@2*@1);
@8 = (@8-@6);
@8 = sin(@8);
output[0][0] = @8;
```
```c
/* F:(i0[3],i1,i2)->(o0[2],o1[3x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=(a0/a1);
  a3=arg[0]? arg[0][1] : 0;
  a3=(a3/a1);
  a4=arg[0]? arg[0][2] : 0;
  a4=(a4/a1);
  a5=10.;
  a6=arg[2]? arg[2][0] : 0;
  a5=(a5*a6);
  a6=(a1*a6);
  arg[3]=w+18;
  arg[4]=w+21;
  arg[5]=w+22;
  res[2]=w+23;
  res[3]=w+25;
  w[18] = a2;
  w[19] = a3;
  w[20] = a4;
  w[21] = a5;
  w[22] = a6;
  if (casadi_f1(arg+3, res+2, iw, w+0, 0)) return 1;
  a2 = w[23];
  a3 = w[24];
  a4 = w[25];
  a5 = w[26];
  a7 = w[27];
  a8=(a2*a1);
  a8=(a8-a6);
  a8=sin(a8);
  if (res[0]!=0) res[0][0]=a8;
```

**Comment by jgillis** [comment]
Finally here 🥲
