### ISSUE TITLE
multiple_shooting_from_scratch.cpp error

### ISSUE THREAD

**Issue by ZahraBoroujeni** [casadi/casadi#1872]
I want to compile the "multiple_shooting_from_scratch.cpp" from example

But I get the error below:
```
src/mpc_planner/src/multiple_shooting_from_scratch.cpp:144: undefined reference to `casadi::Function::operator()(std::map<std::string, casadi::MX, std::less<std::string>, std::allocator<std::pair<std::string const, casadi::MX> > > const&)'
collect2: error: ld returned 1 exit status

```
Do you know how could I solve the problem?

**Comment by jaeandersson** [comment]
Did everything work until that point? Did you make a clean build?

**Comment by ZahraBoroujeni** [comment]
Yes, everything works till line 144: " `MXDict I_out = F(MXDict{{"x0", X[k]}, {"p", U[k]}});`"

**Comment by ZahraBoroujeni** [comment]
I followed the structure below to add casadi libraries and it solved the problem:
https://groups.google.com/forum/#!topic/casadi-users/CPYN_dwQGlA
