### ISSUE TITLE
Octave short-circuit warning

### ISSUE THREAD

**Issue by mrisbeck** [casadi/casadi#1874]
In the 3.1rc1 release for Octave, there's a line inside `+casadi/Function.m` that causes an annoying warning. Line 1525 is

    if numel(s)==1 & s.type=='()'

which causes the warning

    warning: Matlab-style short-circuit operation performed for operator &

because Octave recently changed the behavior of `&` in if statements to match Matlab. It doesn't cause any problems, but it's annoying. If you change it to

     if numel(s)==1 && s.type=='()'

then the warning goes away.

**Comment by jaeandersson** [comment]
Resolved. @jgillis - make sure this gets included in the next RC.
