### ISSUE TITLE
Unused variables in generated code should be marked

### ISSUE THREAD

**Issue by mvukov** [casadi/casadi#1875]
For simple SISO functions the current signature

```
int j_nominal_fun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
```

fails to be compiled as last 3 arguments are not used. Simple fix should be:

```
(void) iw;
(void) w;
(void) mem;
```

The compilers would be happy is configured to work with high pedantry levels.

**Comment by mvukov** [comment]
OK, maybe not only for SISO, but you got my point.

**Comment by jaeandersson** [comment]
Yeah, the unused variables in the generated code is a known issue. At the present time, no effort has been made to avoid unused variables.

**Comment by jaeandersson** [comment]
Duplicate of #1741

**Comment by mvukov** [comment]
This could be a duplicate, but has not been resolved in #1741 -- this is still an issue in 3.2.0.

**Comment by jaeandersson** [comment]
The above warnings (`-Wunused-parameter`) were mentioned in https://github.com/casadi/casadi/issues/1741#issuecomment-290543573. I've now created a separate issue for `-Wextra` warnings.

**Comment by jaeandersson** [comment]
Cf. #2014
