### ISSUE TITLE
OpenModelica XML-Import does not function

### ISSUE THREAD

**Issue by paulrusu8** [casadi/casadi#1882]
I run CasADi from my EclipseIDE on PyDev and try to import an XML-Model from OpenModelica. 
Having the same code as in the Python examples in this repository, it gives me following error message:
 
         "File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/casadi/casadi.py", line 13467, in parse_fmi
         return _casadi.DaeBuilder_parse_fmi(self, *args)
         RuntimeError: The assertion "flag" on line 54 of file"/Users/travis/build/casadi/binaries/casadi/casadi/interfaces/tinyxml/tinyxml_interface.cpp" failed. 
         Cound not open Mosaic.xml". 

The examples run through without a hitch and I cannot see the difference but the definition of the Model and the Vendor. 

Is there a solution or a workaround for this problem?

Thanks.

**Comment by jaeandersson** [comment]
The `parse_fmi` never supported import of XML code from OpenModelica. It sort of supports import of an extension of FMI that was (is?) supported by JModelica.org, but at this point, the function is mostly legacy.

We hope to vastly improve the JModelica/CasADi interoperability in the coming weeks and months, so I think your best bet is to either use JModelica to on your model and extract the CasADi expressions or use OpenModelica to produce flat Modelica code and then use JModelica. Note that JModelica only supports an older version of CasADi at the moment, so you're probably best off simply using the CasADi version that is distributed with whatever JModelica version you have and not rely on your own CasADi installation.
