### ISSUE TITLE
error during import

### ISSUE THREAD

**Issue by simbach** [casadi/casadi#1883]
Dear all,

i get following error when I try to execute `from casadi import *`.
I'm using python 3.5 at a Windows 8.1 64 bit machine.
All needed packages are installed, I think.

Thank you in advance,
Simon

`ImportError                               Traceback (most recent call last)
C:\Casadi\casadi-py34-np1.9.1-v3.1.0-rc1\casadi\casadi.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

C:\Users\bachlers\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap.py in module_from_spec(spec)

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap_external.py in create_module(self, spec)

C:\Users\bachlers\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-88409e829c89> in <module>()
----> 1 from casadi import *

C:\Casadi\casadi-py34-np1.9.1-v3.1.0-rc1\casadi\__init__.py in <module>()
     30 import sys
     31 if sys.version_info >= (3, 0):
---> 32   from casadi.casadi import *
     33 else:
     34   from casadi import *

C:\Casadi\casadi-py34-np1.9.1-v3.1.0-rc1\casadi\casadi.py in <module>()
     19         except ImportError:
     20             return importlib.import_module('_casadi')
---> 21     _casadi = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):

C:\Casadi\casadi-py34-np1.9.1-v3.1.0-rc1\casadi\casadi.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_casadi')
     21     _casadi = swig_import_helper()
     22     del swig_import_helper

C:\Users\bachlers\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: No module named '_casadi'`

**Comment by jaeandersson** [comment]
@jgillis ?

**Comment by jgillis** [comment]
If you use Python 3.5, you must dowload the 3.5 binaries (download link
under the table). Note to self: extend the table

Op 20-okt.-2016 15:54 schreef "Joel Andersson" <notifications@github.com>:
