### ISSUE TITLE
casadi autogenerated function gives different results on subsequent calls

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1891]
The bug could be in how I call the autogenerated code, since it doesn't manifest when I use `ExternalFunction`.

here's as minimal example as I could make: https://github.com/ghorn/casadi_bug

**Comment by jaeandersson** [comment]
The bug is due to a missing assertion, added back. The assertion (which was triggered when trying to evaluate with the VM) is covered by #1571.
