### ISSUE TITLE
Make API smaller

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1894]
The API is still too large. Things that could potentially be removed:
 - [x] `Function::map(vector<MX>)`: Alternative `Function::map(n)::operator()`
 - [x] `Function::map(std::map<string,MX>)`: Alternative `Function::map(n)::operator()`
 - [ ] `Function::map(..., reduced_in, reduced_out, ...)`
 - [x] `Function::forward(vector<MX>, ...)` : Alternative `Function::forward(n)::operator()`
 - [x] `Function::reverse(vector<MX>, ...)`
 - [x] `Function::forward(vector<SX>, ...)`
 - [x] `Function::reverse(vector<SX>, ...)`
 - [x] `Function::forward(vector<DM>, ...)`
 - [x] `Function::reverse(vector<DM>, ...)`
 - [x] `SX::grad()`, `MX::grad()`
 - [x] `SX::tang()`, `MX::tang()`
 - [x] `SX::jac()`, `MX::jac()`
 - [x] `SX::hess()`, `MX::hess()`

**Comment by jaeandersson** [comment]
Ping @jgillis @ghorn

**Comment by jgillis** [comment]
Nothing against this
