### ISSUE TITLE
Function should only have const functions

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1897]
Function represents a pure function and it makes sense to have all methods declared const, both internally (except initialization) and publically.

Data members that are allowed to change after creation, typically caches and memory pools, should be marked `mutable`.

**Comment by ghorn** [comment]
:+1:

**Comment by jgillis** [comment]
:+1:

**Comment by jaeandersson** [comment]
Remaining non-const functions are either deprecated or going to be deprecated (jacobian, hessian).
