### ISSUE TITLE
jacobian w.r.t sliced variables

### ISSUE THREAD

**Issue by JonasKoenemann** [casadi/casadi#1902]
Hi,

i am not sure if this is a bug or desired behavior, but shouldn't that be working?

```
x = casadi.MX.sym('x',5);
y = [x(1);x(2)];
jacobian(y+y,y);
```
gives
```
Error using casadiMEX
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

```

Best
Jonas

**Comment by jaeandersson** [comment]
This is expected behavior. The argument of a differentiation has to be a combination of symbolic primitives, reshape, horzcat and vertcat (if single column). In your case, define a symbolic primitive of length 2 or two of length 1, then do vertcat [ ; ]
