### ISSUE TITLE
Python docstring only showing for some of the Python functions

### ISSUE THREAD

**Issue by roversch** [casadi/casadi#1904]
I downloaded the `casadi-py27-np1.9.1-v3.1.0-rc1` binaries from the website. I run casadi in IPython 4.0.0, Python 2.7.12 on Mac OSX El Capitan.

For example: 

    nlpsol?
gives me the C++ docs
<img width="329" alt="screen shot 2016-11-08 at 16 59 05" src="https://cloud.githubusercontent.com/assets/1436556/20106385/41e58ea0-a5d5-11e6-9bed-41c97fd3bbfb.png">

But 

    Function?
gives me the Python docs
<img width="542" alt="screen shot 2016-11-08 at 17 03 36" src="https://cloud.githubusercontent.com/assets/1436556/20106402/515ad71e-a5d5-11e6-9607-4e06fa8f4670.png">

**Comment by jgillis** [comment]
Thx for reporting! Turns out osx builds where using an old swig variant still.
