### ISSUE TITLE
Getting 'segfault' inside casadilib when running Python script

### ISSUE THREAD

**Issue by roversch** [casadi/casadi#1905]
Running casadi binary `casadi-py27-np1.9.1-c3b586e` 

- on Mac OSX El Capitan (10.11.6), 
- Xcode version 7.3, 
- with Python 2.7.12. 

This binary corresponds to commit `c3b586e471b9e95655b44a42535945e23863b7ce`, which is the latest one on the develop branch. When running a Python script, I get a segfault in `libcasadi.3.0.dylib:casadi::SharedObject::count_up()`

More details:

    thread #1: tid = 0x21c6e, 0x0000000109ecccb1 libcasadi.3.0.dylib`casadi::SharedObject::count_up() + 33, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
    frame #0: 0x0000000109ecccb1 libcasadi.3.0.dylib`casadi::SharedObject::count_up() + 33
    libcasadi.3.0.dylib`casadi::SharedObject::count_up:
    ->  0x109ecccb1 <+33>: movl   0x8(%rcx), %edx
        0x109ecccb4 <+36>: addl   $0x1, %edx
        0x109ecccb7 <+39>: movl   %edx, 0x8(%rcx)
        0x109ecccba <+42>: popq   %rbp

and the full backtrace is:

    thread #1: tid = 0x21c6e, 0x0000000109ecccb1 libcasadi.3.0.dylib`casadi::SharedObject::count_up() + 33, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
    frame #0: 0x0000000109ecccb1 libcasadi.3.0.dylib`casadi::SharedObject::count_up() + 33
    frame #1: 0x0000000109eccc86 libcasadi.3.0.dylib`casadi::SharedObject::SharedObject(casadi::SharedObject const&) + 38
    frame #2: 0x0000000109eb3838 libcasadi.3.0.dylib`casadi::Sparsity::Sparsity(casadi::Sparsity const&) + 40
    frame #3: 0x0000000109eb16bd libcasadi.3.0.dylib`casadi::Sparsity::Sparsity(casadi::Sparsity const&) + 29
    frame #4: 0x000000010a515b13 libcasadi.3.0.dylib`casadi::Nlpsol::get_sparsity_out(int) + 131
    frame #5: 0x000000010a515a06 libcasadi.3.0.dylib`casadi::Nlpsol::get_sparsity_in(int) + 102
    frame #6: 0x000000010a2d458a libcasadi.3.0.dylib`casadi::FunctionInternal::init(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 3754
    frame #7: 0x000000010a357789 libcasadi.3.0.dylib`casadi::OracleFunction::init(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 57
    frame #8: 0x000000010a515bd9 libcasadi.3.0.dylib`casadi::Nlpsol::init(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 57
    frame #9: 0x0000000108e07d25 libcasadi_nlpsol_ipopt.dylib`casadi::IpoptInterface::init(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 85
    frame #10: 0x00000001046430cf libcasadi.dylib`casadi::FunctionInternal::construct(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 63
    frame #11: 0x000000010473ac74 libcasadi.dylib`casadi::nlpsol(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, casadi::Function const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 100
    frame #12: 0x000000010473aced libcasadi.dylib`casadi::nlpsol(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::MX, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::MX> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, casadi::GenericType, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, casadi::GenericType> > > const&) + 61
    frame #13: 0x000000010420fce0 _casadi.so`_wrap_nlpsol__SWIG_1(_object*, _object*) + 672
    frame #14: 0x00000001040f4647 _casadi.so`_wrap_nlpsol(_object*, _object*) + 1511
    frame #15: 0x000000010008e759 Python`PyEval_EvalFrameEx + 29013
    frame #16: 0x000000010008740e Python`PyEval_EvalCodeEx + 1617
    frame #17: 0x0000000100091c9e Python`fast_function + 117
    frame #18: 0x000000010008df09 Python`PyEval_EvalFrameEx + 26885
    frame #19: 0x0000000100091d31 Python`fast_function + 264
    frame #20: 0x000000010008df09 Python`PyEval_EvalFrameEx + 26885
    frame #21: 0x0000000100091d31 Python`fast_function + 264
    frame #22: 0x000000010008df09 Python`PyEval_EvalFrameEx + 26885
    frame #23: 0x000000010008740e Python`PyEval_EvalCodeEx + 1617
    frame #24: 0x0000000100086db7 Python`PyEval_EvalCode + 48
    frame #25: 0x00000001000aa83c Python`run_mod + 53
    frame #26: 0x00000001000aa8df Python`PyRun_FileExFlags + 133
    frame #27: 0x00000001000aa430 Python`PyRun_SimpleFileExFlags + 702
    frame #28: 0x00000001000bbd9e Python`Py_Main + 3094
    frame #29: 0x00007fff9599a5ad libdyld.dylib`start + 1

**Comment by jgillis** [comment]
Could you please retry with a build in https://sourceforge.net/projects/casadi/files/CasADi/commits/6ed326b/osx/ ?

**Comment by roversch** [comment]
I do _not_ get the segfault anymore, and my script runs as usual (+ I get Python docs as well). Thanks!

**Comment by jgillis** [comment]
This is worrying. There was a missing dependency of the included libgfortran.
This should give a runtime error, not a segfault..

**Comment by jgillis** [comment]
Lowering priority since the immediate cause of the crash was solved
