### ISSUE TITLE
Matlab graphics buffer trashed

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1906]
```
addpath(casadimatlab)
for i=1:1000, casadi.SX.sym('x'),end
```

**Comment by jgillis** [comment]
Affects also v3.0.0

**Comment by jgillis** [comment]
Print related; `for i=1:1000, casadi.SX.sym('x');end` is harmless

**Comment by jgillis** [comment]
Can be replicated without CasADi, too:
`for i=1:1000,'x',drawnow('update'),pause(0.0001),end`

**Comment by jgillis** [comment]
Present in MatlabR2016b as well

**Comment by jaeandersson** [comment]
works for me, r2015a

**Comment by jgillis** [comment]
Mac?

**Comment by jaeandersson** [comment]
yes

**Comment by jgillis** [comment]
Its probably linux only

**Comment by jgillis** [comment]
Matlab forum indicates that its a java/graphics card thing on linux
No relation to CasADi
