### ISSUE TITLE
MATLAB examples broken

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1907]
Refactoring appears to have broken some MATLAB examples:
 - docs/examples/matlab/sensitivity_analysis.m uses deprecated syntax in the 3.1 release, got broken when legacy syntax was removed. Fix is here: https://github.com/casadi/casadi/commit/06175a58baf10ddb414843f37eed8c65662d7735 Can be cherry-picked to 3.1.
 - docs/examples/matlab/sysid.m chokes. Probably requires a refactoring equivalent to its Python counterpart docs/examples/python/sysid.m.

**Comment by jgillis** [comment]
Was fixed a while ago
