### ISSUE TITLE
Error during installation of casadi

### ISSUE THREAD

**Issue by marioolivari** [casadi/casadi#1908]
Dear all,

I've been trying to install casadi from source files.

I compiled IPOPT with support for parametric sensitivities (sIPOPT).
I installed the HSL solver.

Running make of casadi, I get this error:

[ 96%] Building CXX object docs/examples/cplusplus/CMakeFiles/parametric_sensitivities.dir/parametric_sensitivities.cpp.o
/home/mpsim/casadi/docs/examples/cplusplus/parametric_sensitivities.cpp: In function ‘int main()’:
/home/mpsim/casadi/docs/examples/cplusplus/parametric_sensitivities.cpp:133:27: error: ‘class casadi::Function’ has no member named ‘getStat’
   var_numeric_md = solver.getStat("var_numeric_md");
                           ^
/home/mpsim/casadi/docs/examples/cplusplus/parametric_sensitivities.cpp:143:32: error: ‘class casadi::Function’ has no member named ‘getStat’
   Dict con_numeric_md = solver.getStat("con_numeric_md");
                                ^
docs/examples/cplusplus/CMakeFiles/parametric_sensitivities.dir/build.make:62: recipe for target 'docs/examples/cplusplus/CMakeFiles/parametric_sensitivities.dir/parametric_sensitivities.cpp.o' failed
make[2]: *** [docs/examples/cplusplus/CMakeFiles/parametric_sensitivities.dir/parametric_sensitivities.cpp.o] Error 1
CMakeFiles/Makefile2:4435: recipe for target 'docs/examples/cplusplus/CMakeFiles/parametric_sensitivities.dir/all' failed
make[1]: *** [docs/examples/cplusplus/CMakeFiles/parametric_sensitivities.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I have no idea what I did wrong, I followed all instructions in the website.

Thank you very much,
Mario

**Comment by jgillis** [comment]
Quick guess: set WITH_DEPRECATED_FEATURES ON?

**Comment by jaeandersson** [comment]
sIPOPT support is most likely broken.

**Comment by marioolivari** [comment]
Dear all,

The option WITH_DEPRECATED_FEATURES in CMakeCache.txt was already ON.
I try to recompile the sIPOPT support.

Thank you for the fast response.

**Comment by jaeandersson** [comment]
I had to refresh my memory on this one: sIPOPT support was dropped with the release of CasADi 3.0. So if you need sIPOPT support, you need to use CasADi 2.4 or older. The reason for dropping it is that it's an IPOPT extension, but if it's a proper extension then it should be merged with the main IPOPT code, which does not appear to be happening. Instead it's left as an "extra" with weird syntax. Parametric sensitivities are still very useful, but I'd rather have it implemented part of the NLP solver core, cf. #724. Unfortunately, there were still lingering references to sIPOPT in the code and in the installation instructions. These have now been removed.

**Comment by marioolivari** [comment]
Thank you! Indeed, the problem was the sIPOPT support.
