### ISSUE TITLE
integrator print_time option doesn't print timing

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1913]
I don't see this option in the list https://github.com/casadi/casadi/blob/89cd11358d499382d42d09ab0bc0936d2bb3332e/casadi/core/function/integrator.cpp#L201-L225. Shouldn't it reject the option?

**Comment by jaeandersson** [comment]
Inherited from a base class https://github.com/casadi/casadi/blob/89cd11358d499382d42d09ab0bc0936d2bb3332e/casadi/core/function/function_internal.cpp

**Comment by jgillis** [comment]
Fixed in develop
