### ISSUE TITLE
Segfault for ill-formed Sparsity constructor call

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1918]
`Sparsity(5,-1)`

**Comment by JonasKoenemann** [comment]
In matlab the display of sparsity is broken, not that i need it but i just noticed..
```
>> casadi.Sparsity(0,0)

ans = 

Error using casadiMEX
function Sparsity_disp requires at least 2 arguments

Error in casadi.Sparsity/disp (line 991)
      [varargout{1:nargout}] = casadiMEX(172, self, varargin{:});
```

**Comment by jaeandersson** [comment]
> In matlab the display of sparsity is broken, not that i need it but i just noticed..

Yeah, but that doesn't belong to this issue. Created a new one.
