### ISSUE TITLE
Sparsity pattern printing in MATLAB

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1920]
https://github.com/casadi/casadi/issues/1918#issuecomment-267007988 :

In matlab the display of sparsity is broken, not that i need it but i just noticed..
```
>> casadi.Sparsity(0,0)

ans = 

Error using casadiMEX
function Sparsity_disp requires at least 2 arguments

Error in casadi.Sparsity/disp (line 991)
      [varargout{1:nargout}] = casadiMEX(172, self, varargin{:});
```

**Comment by jgillis** [comment]
Cursing myself https://github.com/casadi/casadi/commit/6eeb57d92a0689ecec45558a421b1fcedd3e62a8
