### ISSUE TITLE
Problem using blocksqp with CasADi 3.1.1 from Python on Windows

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1932]
When I try to use `blocksqp` for solving an NLP in CasADi 3.1.1 from Python 2.7 (32bit) on Windows 7 (64bit), I get the following error:

    Traceback (most recent call last):
      File "myfile.py", line 245, in <module>
        nlpsolver = ca.nlpsol("nlpsolver", "blocksqp", nlp)
      File "D:\casadi-py27-np1.9.1-v3.1.1\casadi\casadi.py", line 15088, in nlpsol
        return _casadi.nlpsol(*args)
    RuntimeError: The assertion "handle!=0" on line 274 of file "/home/travis/build/
    casadi/binaries/casadi/casadi/core/function/plugin_interface.hpp" failed.
    PluginInterface::load_plugin: Cannot load shared library 'libcasadi_linsol_ma27.dll':
       (
        Searched directories: 1. casadipath from GlobalOptions
                              2. CASADIPATH env var
                              3. PATH env var (Windows)
                              4. LD_LIBRARY_PATH env var (Linux)
                              5. DYLD_LIBRARY_PATH env var (osx)
        A library may be 'not found' even if the file exists:
              * library is not compatible (different compiler/bitness)
              * the dependencies are not found
       )
      Tried 'D:\casadi-py27-np1.9.1-v3.1.1\casadi' :
        Error code (WIN32): 126
      Tried '' :
        Error code (WIN32): 126
      Tried '.' :
        Error code (WIN32): 126

The file is definitely in place. When I use `{"linsol": "csparse}"`, csparse is found (though it's not working due to `'neig' not defined for N6casadi16CsparseInterfaceE`).

On Ubuntu 16.04, the problem does not occur

**Comment by jgillis** [comment]
You must have libhsl.so on your LD_LlBRARY_PATH for this

Op 13-jan.-2017 18:19 schreef "Adrian Bürger" <notifications@github.com>:

**Comment by adbuerger** [comment]
Ah ok sorry, I got confused, I saw ma27 being used in tests an examples, so I thought that it would be shipped with CasADi. Of course I had libhsl.so on Ubuntu, but not on Windows, so this was always working for me. Thanks for your quick answer!

**Comment by jgillis** [comment]
I'd be trivial to ship, but this is not allowed..
