### ISSUE TITLE
multipliers for homotopy

### ISSUE THREAD

**Issue by rcleuthold** [casadi/casadi#1936]
Hi Joris and Joel, 

I'm trying to use casadi/ipopt/python to solve an nlp with a homotopy. For this, I want to plug the muliplier solutions (lam_x and lam_g) as inputs into the next step (lam_x0 and lam_g0). 

This doesn't seem to work very well, so I feel like I've got something wrong in my understanding of how these multipliers are defined.

How do the multipliers diferentiate between upper and lower (inequality) bounds, and how would I pass them into the next homotopy step? 

Thanks and best, 
Rachel

**Comment by jaeandersson** [comment]
You might already be doing it the right way. The problem with using is an interior point method like IPOPT for a homotopy is that for every solution, the optimizer has to go via the "central path" to the solution, i.e. solve the problem with different barrier parameters. Do you not see any difference at all when you provide a good primal-dual guess? Another thing you could consider is to change the initial value for the barrier parameter. @mzanon might have some more tips.

**Comment by mzanon** [comment]
I agree with Joel. The best option would probably be to use SQP instead. If you do have a good SQP solver I advise you to use that one.

**Comment by jgillis** [comment]
I expect to have some time on Wednesday to have a look at Worhp.

**Comment by jgillis** [comment]
Worhp should be up and running for mac:
https://sourceforge.net/projects/casadi/files/CasADi/commits/ead65e0/osx/

You'll need a license file, pointed at by WORHP_LICENSE_FILE, and the macports version of WORHP library in the DYLD_LIBRARY_PATH.

**Comment by jgillis** [comment]
Best to continue on the forum
