### ISSUE TITLE
binary installation of CasADi on Mac using python fails

### ISSUE THREAD

**Issue by JXZhou88** [casadi/casadi#1937]
Hi Joris and Joel,

i am new to CasADi and have been struggling with the binary installation on Mac using Python. I followed the steps listed on your website: https://github.com/casadi/casadi/wiki/InstallationInstructions
First, i installed python 3.6 on my mac, then i downloaded the binary file "casadi-py35-np1.9.1-v3.1.1" from the binary table, unzipped it, put it in my home directory and proceeded to python using IDLE(Python). I tried to execute each of the following commands one by one:
-------------------------------------------------------------------------------------
  from sys import path
  path.append(r".../casadi-py27-np1.9.1-v3.1.1")
  from casadi import *
  x = MX.sym("x")
  print(jacobian(sin(x),x))
-------------------------------------------------------------------------------------
and after the third line "from cased import *" the following error occurred:
-------------------------------------------------------------------------------------
  Traceback (most recent call last):
    File "<pyshell#9>", line 1, in <module>
      from casadi import *
    File "/Users/<myusernamehere>/casadi-py35-np1.9.1-v3.1.1/casadi/__init__.py", line 28, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'bumpy'
-------------------------------------------------------------------------------------
Do you know how to get rid of this problem?

Thank you very much in advance. 

Best regards!

J. Zhou

**Comment by jgillis** [comment]
Hi there! The version of python mentioned in the binary must match that of the Python that you are using.
Could you possibly try this with a Python 2.5 build?

**Comment by JXZhou88** [comment]
Hi Joris, 

Thanks for your reply, i downloaded spyder and it worked perfectly.
