### ISSUE TITLE
Accessing solver status

### ISSUE THREAD

**Issue by bacalfa** [casadi/casadi#1939]
Is there a way to check the solver status using the Python interface? For example, after executing:

```
solver = nlpsol("solver", "ipopt", nlp, opts)
res = solver(x0=z0, lbx=lbx, ubx=ubx)
```

I'd like to check if the solver finished normally. For some initial guesses, I'm getting the following message:

`solver:nlp_grad_f failed: NaN detected for output grad_f_x, at (row 1, col 0).`

and then IPOPT says:

`EXIT: Invalid number in NLP function or derivative detected.`

I'd like to be able to detect when that happens before I use the `res` variable.

**Comment by jgillis** [comment]
`solver.stats()` should do the job.
