### ISSUE TITLE
Accessing NLP from Solver

### ISSUE THREAD

**Issue by bacalfa** [casadi/casadi#1940]
Is there a way to access the nlp object from the solver object (Python)? Example:

```
nlp = {'x': x, 'f': f(x)}
...
solver = nlpsol("solver", "ipopt", nlp, opts)
```

Can I access the `nlp` variable (and its keys and values) if I only have the `solver` variable?

**Comment by jgillis** [comment]
Afaik, you cannot.

You may obtain it in the form of a Function with:
`nlp = solver.oracle().factory("nlp",["x","p"],["f","g"])`

From there, you may call such function symbolically (e.g. `nlp(*nlp.sx_in())`) to obtain expressions.

Yet its probably easier if you keep it yourself or change your design such that it is not needed.

**Comment by jaeandersson** [comment]
Yeah, don't try to extract the dictionary like this. Remember what you passed to the constructor.

**Comment by bacalfa** [comment]
I actually changed my mind about this after giving it a bit more of though. It makes sense to pass the `nlp` variable and then call `nlpsol`. Thanks, guys!
