### ISSUE TITLE
Cannot load shared library libcasadi_importer_clang

### ISSUE THREAD

**Issue by mahaarbo** [casadi/casadi#1941]
Hi, I'm using ipopt on a nonlinear problem, and wanted to try to speed it up a bit using the jit option. But I get the error message ` Cannot load shared library 'libcasadi_importer_clang.dylib': `, and searching for this library, I can't seem to find it anywhere.  

I'm using `casadi-py27-np1.9.1-v3.1.0-rc1` on mac OS X (10.11.4) with XCode 7.3.1 at the moment. I downloaded casadi using the binaries.

**Comment by jgillis** [comment]
Hi there!

Shipping of clang is currently not enabled for our mac builds.
Please change the jit compiler to a shell compiler:

{"compiler": "shell", "jit": True, "jit_options": {"compiler": "gcc"}}

**Comment by mahaarbo** [comment]
Great, that solved it 👍  Down from about 0.35 s to 0.2 s. Now to tune the horizon and such.

**Comment by jgillis** [comment]
You may try more e.g. setting optimization flags:

`{"compiler": "shell", "jit": True, "jit_options": {"compiler": "gcc","flags": ["-O3"]}}`

**Comment by bonassifabio** [comment]
> You may try more e.g. setting optimization flags:
> 
> `{"compiler": "shell", "jit": True, "jit_options": {"compiler": "gcc","flags": ["-O3"]}}`

Hi, I'm using casadi with Matlab 2021b. What is the correct format to pass the jit_options parameter to opti.solve? I'm trying using a structure but does not seem to work:
`p_opts = struct;
    p_opts.expand = true;
    p_opts.ipopt.print_level = 0;
    p_opts.print_time = false;
    p_opts.jit = true;
    p_opts.jit_options = struct('compiler', 'gcc');
    
    s_opts = struct;
    s_opts.print_level = 0;
    
    opti.solver('ipopt', p_opts, s_opts);`

Thanks
