### ISSUE TITLE
Solving Problems in Parallel

### ISSUE THREAD

**Issue by bacalfa** [casadi/casadi#1942]
Is it possible to solve multiple problems in parallel? In Python, when I try to use the `joblib` package to parallelize a for loop that solves multiple instances of a model I get the following error:

`TypeError: can't pickle SwigPyObject objects`

I believe that refers to `nlp` and/or `solver` variables that are arguments to the function to be executed in parallel.

**Comment by ghorn** [comment]
Can you create and solve the problem inside the for loop?

Can you use the `multithreading` module to avoid pickling?

**Comment by bacalfa** [comment]
Mmm... I'll think about it. I'm trying to keep the function's signature as simple and general as possible. I'm implementing a simple multistart procedure to try to obtain better local optimal solutions (a global solver would be nice, hence my comment on another topic, but sometimes multistart with local solver can be a decent approach).

**Comment by bacalfa** [comment]
Apparently, using the module `multiprocessing` works if I create `SX.sym` objects inside the function to be evaluated in parallel (i.e., I can't pass variables, such as `dict`s that contain `SX.sym` objects). But that breaks the modularity I'm trying to achieve, because the multistart function shouldn't have to be defined in the scope of a particular model. Eventually, I'd like to implement a class for my problem (right now, I have separate functions and scripts) and I'm not sure if there'll be a way to keep the multistart function as a stand-alone "tool" (which can be used for any model).

**Comment by bacalfa** [comment]
Update: it works if I define all variables that depend on `SX.sym` objects inside the function that is evaluated in parallel. Thanks for the suggestion, @ghorn! I implemented a simple multistart algorithm [here](https://github.com/bacalfa/MultiStart_CasADi). Feedback is welcome! :)

**Comment by jaeandersson** [comment]
Awesome, I'm a little bit lost in all this.. Why do you create the solver objects in parallel? About parallelism, the following is the current status:
 * CasADi symbolics is *not* thread-safe. There are static variables (caches etc) that prevent the symbolic processing to be done in parallel
 * Once created, the solver objects -- CasADi Function instances -- are designed to be tread safe. That is, you can have multiple threads calling the same solver object with different data.
 * For thread-safety, it's necessary to have different threads work on different temporary memory structures. This is implemented, but not yet fully debugged, especially when classes are nested. For example, an integrator object that in turn contains a linear solver object etc.

For an NLP solver, there are two steps as you've noted:
 * Create a solver instance with the "solver = nlpsol" function. This is *not* thread-safe.
 * Call solver(...) to solve the actual NLP with the provided data. This is designed to be thread-safe and will be thread-safe for most classes. But not all due to bugs that we should iron out with user-feedback.

**Comment by jgillis** [comment]
Within reach with #308. See also #1736

**Comment by jgillis** [comment]
Following works:

```python
from casadi import *
from multiprocessing import Pool

x = MX.sym("x")
f = Function("f",[x],[x**2])

p = Pool(3)
print(p.map(f, [1, 2, 3]))
```

**Comment by jgillis** [comment]
Should also work now for ipopt:

```python
from casadi import *
from multiprocessing import Pool

x = MX.sym("x")

solver = nlpsol("solver","ipopt",{"x":x,"f":sin(x)**2})

def mysolve(x0):
  return solver(x0=x0)["x"]

p = Pool(3)
print(p.map(mysolve, [0, 3, 6]))
```

**Comment by adbuerger** [comment]
Hi @jgillis I'm trying to speed up some computations using multiprocessing with CasADi 3.4.5 (from Python 3.5 on Ubuntu 16.04) where I have multiple Python classes that contain different optimization problems and store their results, as exemplified below.

I can evaluate them in parallel, so that's working great! However, I cannot get the modified objects back, the queue `q` that should contain the modified objects `solver_1` and `solver_2` appears to be empty, though no error is thrown.

    import multiprocessing as mp
    import casadi as ca

    class Solver_1(object):

        def __init__(self):
            self.x = ca.MX.sym("x")
            self.x0 = 2.0
            self.nlpsolver = ca.nlpsol("solver","ipopt", \
                {"x": self.x,"f": ca.sin(self.x)**2})

        def solve(self):
            self.sol = self.nlpsolver(x0 = self.x0)

    class Solver_2(object):

        def __init__(self):
            self.x = ca.MX.sym("x")
            self.x0 = 2.0
            self.nlpsolver = ca.nlpsol("solver","ipopt", \
                {"x": self.x,"f": ca.cos(self.x)**2})

        def solve(self):
            self.sol = self.nlpsolver(x0 = self.x0)

    solver_1 = Solver_1()
    solver_2 = Solver_2()

    def solve(obj, q):
        obj.solve()
        q.put(obj)

    q = mp.Queue()

    p1 = mp.Process(target = solve, args = (solver_1, q))
    p1.start()
    p2 = mp.Process(target = solve, args = (solver_2, q))
    p2.start()

    q.empty() # returns True

I then tried to run

    q.put(solver_1)

outside multiprocessing, which returns

    Traceback (most recent call last):
      File "/usr/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
        obj = ForkingPickler.dumps(obj)
      File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
        cls(buf, protocol).dump(obj)
      File "/usr/local/lib/python3.5/dist-packages/casadi/casadi.py", line 13618, in __getstate__
        return {"serialization": self.serialize()}
      File "/usr/local/lib/python3.5/dist-packages/casadi/casadi.py", line 13094, in serialize
        return _casadi.Function_serialize(self, *args)
    RuntimeError: .../casadi/core/function_internal.cpp:1550: 'serialize' not defined for IpoptInterface

though if I follow #308 correctly this should be possible, right? Am I doing something wrong, or am I just using the wrong version of CasADi? Is this already implemented in the 3.4.5. release or do I have to use some nightly build (for now)?

Thank your for your help!

**Comment by jgillis** [comment]
This issue is closed on develop, so you'll need a nightly build: https://github.com/casadi/binaries/releases/tag/commit-3cdfbd6

Cfr https://web.casadi.org/blog/parfor/, serializing free SX/MX symbols is not supported, so you'll have to restructure your approach a bit.

**Comment by wilkosch** [comment]
@jgillis  I just tried on both windows and ubuntu release 3cdfbd6 matlab2016a in matlab 2017/2018 with the code provided by the blogpost and both fail with the following message:

Starting parallel pool (parpool) using the 'local' profile ...
connected to 12 workers.
Warning: Serializing of CasADi Function failed:Error using casadi.Function.deserialize (line 1693)
.../casadi/core/serializer.cpp:274: Assertion "t=='V'" failed:
Notify the CasADi developers.

Error in casadi.Function.loadobj (line 1699)
             obj = casadi.Function.deserialize(s.serialization);

Error in parallel.internal.pool.deserialize (line 9)
data = distcompdeserialize( distcompByteBufferHandles2MxArray( bbhArray ) );

Error in parallel.internal.pool.deserializeFunction (line 12)
dataOut          = parallel.internal.pool.deserialize(...

Error in remoteParallelFunction (line 33)
            [C, notFound] = parallel.internal.pool.deserializeFunction(initData);
> In casadi.Function.loadobj (line 1704)
  In parallel.internal.pool.deserialize (line 9)
  In parallel.internal.pool.deserializeFunction (line 12)
  In remoteParallelFunction (line 33)
Warning: While loading an object of class 'casadi.Function':
Output argument "obj" (and maybe others) not assigned during call to "casadi.Function.loadobj".
> In parallel.internal.pool.deserialize (line 9)
  In parallel.internal.pool.deserializeFunction (line 12)
  In remoteParallelFunction (line 33)
Error using casadi.Function/call (line 780)
No matching function for overload function 'Function_call'.  Possible prototypes are:
    CALL(self,struct:DM,bool,bool)
    CALL(self,{DM},bool,bool)
    CALL(self,{SX},bool,bool)
    CALL(self,struct:SX,bool,bool)
    CALL(self,struct:MX,bool,bool)
    CALL(self,{MX},bool,bool)
  You have: Function, struct:double

Error in casadi.Function/paren (line 1487)
        res = self.call(arg);

Error in casadi.Function/subsref (line 1472)
        [varargout{1:nargout}]= paren(self, s.subs{:});

Error in testtest (line 59)
parfor i=1:N

**Comment by jgillis** [comment]
Strange, thanks for testing and reporting.

Could you run a simple test?

```matlab
x=MX.sym("x")
f=Function("f",{x},{x^2})
Function.deserialize(f.serialize())
```

**Comment by adbuerger** [comment]
@jgillis Thank you for your hints! Using the nightly build, removing all free SX/MX symbols from the class and restructuring my code the following way

```Python
import multiprocessing as mp
import casadi as ca

x = ca.MX.sym("x")

nlpsolver = ca.nlpsol("solver","ipopt", \
    {"x": x,"f": ca.sin(x)**2})

class Solver(object):
    def __init__(self):
        self.x0 = 2.0
        self.nlpsolver = nlpsolver

    def solve(self):
        self.sol = self.nlpsolver(x0 = self.x0)

solver_1 = Solver()

def solve(obj, q):
    obj.solve()
    q.put(obj)

q = mp.Queue()

p1 = mp.Process(target = solve, args = (solver_1, q))
p1.start()

q.empty() # returns False now

q.get() # Fails with the error given below
```
I can now put the `solver_1` object into the queue `q`. However, when I try to retrieve the object from there, I get an error message similar to the one given above by @wilkosch 

```Python
Traceback (most recent call last):
  File "mp.py", line 31, in <module>
    q.get() # Fails
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
  File "/mnt/data/casadi_builds/casadi-linux-py35-3cdfbd6-64bit/casadi/casadi.py", line 14942, in __setstate__
    self.__init__(Function.deserialize(state["serialization"]))
  File "/mnt/data/casadi_builds/casadi-linux-py35-3cdfbd6-64bit/casadi/casadi.py", line 14842, in deserialize
    return _casadi.Function_deserialize(*args)
RuntimeError: .../casadi/core/serializer.cpp:274: Assertion "t=='V'" failed:
Notify the CasADi developers.
```

The simple example below works fine:

```Python
import casadi as ca

x = ca.MX.sym("x")
f = ca.Function("f",[x],[x**2])
ca.Function.deserialize(f.serialize())
```

**Comment by jgillis** [comment]
Thank you both for your eager and thorough testing.
Apparently there was a mistake in non-debug mode (and only debug mode was tested).
A fixed build, https://github.com/casadi/binaries/releases/tag/commit-e87f29f, should be available somewhere this afternoon

**Comment by jgillis** [comment]
Check again later?

**Comment by adbuerger** [comment]
Ah, sorry, I was just wondering because some of the jobs at https://travis-ci.org/casadi/casadi/builds/422939604 said failed/cancelled. The build are there now. Also, I ran the code above and everything is working perfect, thanks!

**Comment by jgillis** [comment]
Now is a good time to report issues with this type of parallelization, so do not hesitate to report further problems.

**Comment by wilkosch** [comment]
Works for me on the problems in blogpost! Thank you for the quick fix @jgillis. CasADi is love CasADi is life :D.
I am wondering whether this variant should work:
```matlab
%% Problem creation with map
N = 250;

fsol = zeros(1,N);
rs = linspace(1,3,N);

x = casadi.SX.sym('x');
y = casadi.SX.sym('y');

v = [x;y];
f = (1-x)^2+(y-x^2)^2;
g = x^2+y^2;
nlp = struct('x', v, 'f', f, 'g', g);

% Create IPOPT solver object
solver = casadi.nlpsol('solver', 'ipopt', nlp);
solver_map = solver.map(N,'thread');

x0s = repmat([2.5 3.0]', 1, N);
lbxs = repmat(-inf, 2, N);
ubxs = repmat(inf, 2, N);
lbgs = repmat(-inf, 1, N);
ubgs = rs;

res = solver_map('x0' , x0s,...      % solution guess
           'lbx', lbxs,...           % lower bound on x
           'ubx', ubxs,...           % upper bound on x
           'lbg', lbgs,...           % lower bound on g
           'ubg', ubgs);           % upper bound on g
```
For me it segfaults in linux/ubuntu/osx matlab.

```
user@user-desktop~$ matlab
  Instance Error 2 in DMUMPS_F77         101
 ** MPI_ABORT called
MATLAB: management.cpp:671: find: Assertion `' failed.
*** Error in `/usr/local/MATLAB/R2018a/bin/glnxa64/MATLAB': malloc(): memory corruption: 0x00007f7b00000012 ***
 PB allocation in DMUMPS_185
 PB allocation in DMUMPS_185
At line 1182 of file ../../../ThirdParty/Mumps/MUMPS/src/dmumps_load.F
Fortran runtime error: Attempt to DEALLOCATE unallocated 'load_flops'
 PB allocation in DMUMPS_185
 PB allocation in DMUMPS_185
Aborted (core dumped)
```

**Comment by jgillis** [comment]
Nah sorry, that failure is still expected. We will fix that in the long run.
Thank you for the kind words. Do buy a CasADi T-shirt  ;-)

**Comment by adbuerger** [comment]
That ist so cool! Works perfectly, thanks! Can I get my T-shirt in size M, please? :-)

**Comment by adbuerger** [comment]
I stumbled across one more thing:

```Python
import pylab as pl
import casadi as ca
import pickle

x = ca.MX.sym("x")
u = ca.MX.sym("u")

s = ca.interpolant("s", "bspline", [pl.linspace(0, 10, 11)], pl.linspace(0.2, 0.5, 11))

dxdt = s(u) * x

ode = {"x": x, "p": u, "ode": dxdt}
f = ca.integrator("f", "cvodes", ode)

d = pickle.dumps(f) # works
pickle.loads(d) # fails with the error given below
```

fails with the message given below:

```Python
Traceback (most recent call last):
  File "integ.py", line 16, in <module>
    pickle.loads(d) # fails with the error given below
  File "/mnt/data/casadi_builds/casadi-linux-py35-a92892c-64bit/casadi/casadi.py", line 14942, in __setstate__
    self.__init__(Function.deserialize(state["serialization"]))
  File "/mnt/data/casadi_builds/casadi-linux-py35-a92892c-64bit/casadi/casadi.py", line 14842, in deserialize
    return _casadi.Function_deserialize(*args)
RuntimeError: .../casadi/core/plugin_interface.hpp:187: Assertion "m" failed:
Plugin "bspline" does not support deserialize
```
Is it possible to realize deserialization of `bspline`? If it's not easily possible, I can also work around it.

**Comment by jgillis** [comment]
Waw, you sure are combining a lot of our features.. added bspline support in 6d29fee

**Comment by adbuerger** [comment]
Yes, and it's all working great! Thanks once again for your support!
