### ISSUE TITLE
Option for iteration printing in sqpmethod

### ISSUE THREAD

**Issue by mahaarbo** [casadi/casadi#1943]
Perhaps it'd be possible to include an option to suppress the `printIteration` function in sqpmethod? 
E.g. adding a `print_iteration` option to sqpmethod?

**Comment by jaeandersson** [comment]
First of all, note that "sqpmethod" is mainly intended a boilerplate code, if you want to write your own solver. Would be great if it gets used and improved though. Is it working for your application? I added that option in the develop branch of CasADi. If you want to use the code, you should probably be prepared to hack on it and make pull requests if you fix something...

**Comment by mahaarbo** [comment]
The sqpmethod works okay for my application (model predictive path following controller), but so slow it can only be used for simulation and not really robust for long horizons (issues with ensuring PD of Hessian I imagine). I originally wanted to solve it with that and IPOPT, but decided against it after looking at the source, and comparing timing.

**Comment by jaeandersson** [comment]
Yeah, Hessian regularization is definitely an issue. What kind of time discretization do you have? Is it a single-shooting type discretization?

**Comment by mahaarbo** [comment]
I've tested multiple shooting with runge-kutta and collocation with legendre polynomials of 3rd order.
