### ISSUE TITLE
how to get partial derivate

### ISSUE THREAD

**Issue by JXZhou88** [casadi/casadi#1944]
Hi there, 

i have a simple question regarding how to get the partial derivative of a vector field dx = f(x,u,w) w.r.t the variable w. The .jacobian() operator gives back d(dx)/dx.

Thanks in advance.

**Comment by jgillis** [comment]
Hi! Please use the forum for questions like this.

you can do `jacobian(expr,w)` (prefered) or `f.jacobian(2,0)`

**Comment by JXZhou88** [comment]
sorry for posting in the wrong section and thank you for the quick reply!
