### ISSUE TITLE
problem installing casadi from source on debian 8

### ISSUE THREAD

**Issue by schloegl** [casadi/casadi#1945]
I tried to install casadi from source on Debian according to the documention. Specifically I was running the following commands: 

`	sudo apt-get install gcc g++ gfortran git cmake liblapack-dev pkg-config --install-recommends
	sudo apt-get install coinor-libipopt-dev

	git clone https://github.com/casadi/casadi.git -b master casadi
	cd casadi
	mkdir build
	cd build

	cmake -DWITH_PYTHON=ON ..
	make 
	sudo make install 

	cd .. # Go back to the main casadi source directory
	cd test/python
	python alltests.py`

Running the test fails with this message: 

`~/src/casadi/test/python$ python alltests.py
Traceback (most recent call last):
  File "alltests.py", line 24, in <module>
    from mx import *
  File "/home/schloegl/src/casadi/test/python/mx.py", line 24, in <module>
    from casadi import *
  File "/usr/lib/python2.7/dist-packages/casadi/__init__.py", line 34, in <module>
    from casadi import *
  File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 28, in <module>
    _casadi = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 24, in swig_import_helper
    _mod = imp.load_module('_casadi', fp, pathname, description)
ImportError: dynamic module does not define init function (init_casadi)`

Do you have any idea what is wrong here ?

**Comment by jgillis** [comment]
Whats the cmake output? Is it detecting python3 perhaps?

**Comment by schloegl** [comment]
Thanks for the hint, yes python 2.7 and 3.4 are installed. here is the output from the previous installation 

`~/src/casadi/build$ cmake -DWITH_PYTHON=ON ..
-- Flag needed for enabling C++11 features: -std=c++11
-- x86_64 architecture detected - setting flag -fPIC
-- Could not find HSL; looking in environmental variable HSL ()
-- Could not find WSMP; looking in environmental variable WSMP ()
-- Could not find METIS; looking in environmental variable METIS ()
-- A library with BLAS API found.
-- A library with LAPACK API found.
CMake Warning at CMakeLists.txt:431 (message):
  Blasfeo directory not found.  If you want blasfeo, do git submodule init;
  git submodule update.


-- Detected an IPOPT configuration without sIPOPT headers. Build will proceed, but without sIPOPT functionality.
-- checking for one of the modules 'bonmin'
-- Could NOT find BONMIN (missing:  BONMIN_LIBRARIES BONMIN_INCLUDE_DIRS) 
-- Could not find KNITRO include dir
-- Could not find KNITRO library
-- CPLEX Library: CPLEX_LIBRARY-NOTFOUND
-- ILOCPLEX Library: CPLEX_ILOCPLEX_LIBRARY-NOTFOUND
-- CONCERT Library: CPLEX_CONCERT_LIBRARY-NOTFOUND
-- CPLEX Bin Dir: CPLEX_BIN_DIR-NOTFOUND
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR CPLEX_ILOCPLEX_LIBRARY CPLEX_CONCERT_LIBRARY CPLEX_CONCERT_INCLUDE_DIR) 
-- checking for one of the modules 'clp'
-- Could NOT find CLP (missing:  CLP_LIBRARIES CLP_INCLUDE_DIRS) 
-- Could not find SNOPT include dir
-- Could not find SNOPT libs
-- Could NOT find GUROBI (missing:  GUROBI_LIBRARY GUROBI_CXX_LIBRARY GUROBI_INCLUDE_DIR) 
-- Numpy path found: /usr/include/python3.4m/numpy
-- Python libs: /usr/lib/x86_64-linux-gnu/libpython3.4m.so
-- Numpy includes: /usr/include/python3.4m/numpy;/usr/include
-- Numpy libs: /usr/lib/python2.7/dist-packages/numpy/core/multiarray.so
-- 
-- The following features have been enabled:

 * dynamic-loading , Compile with support for dynamic loading of generated functions (needed for ExternalFunction)
 * lapack-interface , Interface to LAPACK.
 * sundials-interface , Interface to the ODE/DAE integrator suite SUNDIALS.
 * csparse-interface , Interface to the sparse direct linear solver CSparse.
 * tinyxml-interface , Interface to the XML parser TinyXML.
 * dsdp-interface , Interface to the interior point SDP solver DSDP.
 * qpoases-interface , Interface to the active-set QP solver qpOASES.
 * blocksqp-interface , Interface to the NLP solver blockSQP.
 * ipopt-interface , Interface to the NLP solver Ipopt.

-- The following OPTIONAL packages have been found:

 * BLAS
 * Threads
 * LAPACK
 * IPOPT
 * PkgConfig

-- The following REQUIRED packages have been found:

 * SWIG
 * PythonLibs
 * NUMPY
 * PythonInterp

-- The following features have been disabled:

 * hsl-interface , Interface to HSL.
 * blasfeo-interface , Interface to blasfeo.
 * hpmpc-interface , Interface to hpmpc.
 * mosek-interface , Interface to the interior point SOCP solver MOSEK.
 * clang-interface , Interface to the Clang JIT compiler.
 * ecos-interface , Interface to the interior point SOCP solver ECOS.
 * opencl-support , Enable just-in-time compiliation to CPUs and GPUs with OpenCL.
 * bonmin-interface , Interface to the MINLP framework Bonmin.
 * knitro-interface , Interface to the NLP solver KNITRO.
 * cplex-interface , Interface to the QP solver CPLEX.
 * clp-interface , Interface to the LP solver CLP.
 * ooqp-interface , Interface to the QP solver OOQP (requires BLAS and HSL libraries).
 * gurobi-interface , Interface to the (mixed-integer) QP solver GUROBI
 * sqic-interface , Interface to the QP solver SQIC.
 * slicot-interface , Interface to the controls library SLICOT.
 * worhp-interface , Interface to the NLP solver Worhp (requires gfortran, gomp).

-- The following OPTIONAL packages have not been found:

 * BONMIN
 * KNITRO
 * CPLEX
 * CLP
 * SNOPT
 * GUROBI

-- Configuring done
-- Generating done
-- Build files have been written to: /home/schloegl/src/casadi/build

`
After unistalling 
`   apt-get remove libpython3-dev python3-numpy 
    apt-get install libpython2.7-dev
`
and recompiling and installing casadi, the problem is gone, and the test runs successfully. Thanks.

**Comment by schloegl** [comment]
Ok, most tests run successfully, the followng two tests still fail:

`

======================================================================
ERROR: test_Callback_Jacobian (function.Functiontests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/schloegl/src/casadi/test/python/function.py", line 927, in test_Callback_Jacobian
    self.checkfunction(f,g,inputs=num_inputs,fwd=False,adj=False,indirect=False)
  File "/home/schloegl/src/casadi/test/python/helpers.py", line 391, in checkfunction
    trialjac = trial.jacobian(i,j)
  File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 6700, in jacobian
    return _casadi.Function_jacobian(self, *args)
TypeError: SWIG director method error. The assertion "op.second.can_cast_to(entry->type)" on line 254 of file "/home/schloegl/src/casadi/casadi/core/options.cpp" failed. 
Illegal type for input_scheme: OT_INTVECTOR cannot be cast to OT_STRINGVECTOR.


======================================================================
ERROR: test_Callback_sens (function.Functiontests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/schloegl/src/casadi/test/python/function.py", line 1190, in test_Callback_sens
    self.checkfunction(f,g,inputs=num_inputs,sens_der=False,hessian=False,adj=False,evals=1)
  File "/home/schloegl/src/casadi/test/python/helpers.py", line 405, in checkfunction
    trialgrad = trial.gradient(i,j)
  File "/usr/lib/python2.7/dist-packages/casadi/casadi.py", line 6735, in gradient
    return _casadi.Function_gradient(self, *args)
TypeError: SWIG director method error. The assertion "op.second.can_cast_to(entry->type)" on line 254 of file "/home/schloegl/src/casadi/casadi/core/options.cpp" failed. 
Illegal type for input_scheme: OT_INTVECTOR cannot be cast to OT_STRINGVECTOR.


----------------------------------------------------------------------
Ran 446 tests in 58.368s

FAILED (errors=2, skipped=17)
`

**Comment by jgillis** [comment]
Those are errors are not really worrying; you'r good to go. I'll open a separate issue for them.
