### ISSUE TITLE
Linux installation instructions wiki

### ISSUE THREAD

**Issue by Mathadon** [casadi/casadi#1947]
For getting CasADi to detect my CPLEX installation, I had to execute:

```
export PATH=/opt/ibm/ILOG/CPLEX_Studio1263/concert/include:/opt/ibm/ILOG/CPLEX_Studio1263/cplex/include:/opt/ibm/ILOG/CPLEX_Studio1263/cplex/lib/x86-64_linux/static_pic:/opt/ibm/ILOG/CPLEX_Studio1263/concert/lib/x86-64_linux/static_pic:$PATH
```

before running cmake in order to get CasADi to detect the installation. This could be added to the wiki(https://github.com/casadi/casadi/wiki/InstallationLinux)?

**Comment by jaeandersson** [comment]
I updated the instructions, can you check if it's ok?

**Comment by Mathadon** [comment]
Looks good :)
