### ISSUE TITLE
add functionality to attach strings to MX nodes

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1951]
The difficulty with `printme` and `attachAssert` is that you don't know which node in the original source triggers the print or the assert.

What would it look like to have functions `attachAssertMessage` or `printme_message` which took an additional arbitrary string?

**Comment by jaeandersson** [comment]
Can you not just evaluate the code with a `DM` datatype instead of `MX`?

**Comment by jgillis** [comment]
Note that you can pass an identifier in the form of an int

**Comment by jgillis** [comment]
There is `MX::attachAssert(const MX& y, const std::string &fail_message)` and `MX::monitor(const std::string& comment)`
