### ISSUE TITLE
Efficient Matrix-Matrix Multiplication

### ISSUE THREAD

**Issue by bacalfa** [casadi/casadi#1953]
Is there an efficient function to multiply "matrices" that can be of different types? For example, a m-by-n SX object multiplied by a n-by-q DM object. I noticed that the operator * is element-wise multiplication. As an aside, the numpy.dot function does matrix-matrix multiplication if the two arguments are 2-D arrays, but it seems that the casadi.dot function requires the arrays to have the same size.

Example:

```
A = SX.sym("A",10,3)
B = np.random.rand(3,5)
print(dot(A,B))
```

Traceback (most recent call last):
  File ".../testcasadi.py", line 116, in <module>
    print(dot(A,B))
  File ".../casadi-py35-np1.9.1-v3.1.1/casadi/casadi.py", line 18194, in dot
    return _casadi.dot(*args)
RuntimeError: The assertion "x.size()==y.size()" on line 1722 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/function/../matrix_impl.hpp" failed. 
dot: Dimension mismatch

**Edit:**

I just noticed that if I make A an MX object instead of SX, the error becomes:

RuntimeError: The assertion "size2()==y.size2() && size1()==y.size1()" on line 754 of file "/Users/travis/build/casadi/binaries/casadi/casadi/core/mx/mx_node.cpp" failed. 
MXNode::dot: Dimension mismatch. dot requires its two arguments to have equal shapes, but got (3, 10) and (5, 3).

**Comment by jaeandersson** [comment]
`mtimes` is for matrix multiplication. See the [user guide](guide.casadi.org).

**Comment by jaeandersson** [comment]
`dot` is for inner product, like in MATLAB/Octave.
