### ISSUE TITLE
eliminating DM multiplications

### ISSUE THREAD

**Issue by Mathadon** [casadi/casadi#1960]
I just did a test using casadi 3.1, which may suggest that some further improvements are possible.

Consider a discrete state space model:
x[k+1] = A*x[k] + B*u[k] + d

for an MPC implementation I implemented this as follows:

```
Xi[0]=X0
for i...
Xi[i+1] = mtimes(*A_discr, Xi[i]) + mtimes(*B_discr, Ui[i])  + *b_discr;
```
and also as

```
for i...
Xi[i+1] = mtimes(*powA_i[i+1],X0);
for (int k=0 ; k<i+1; k++){
	Xi[i+1] += mtimes(mtimes(*powA_i[k], *B_discr), Ui[i-k]);
	Xi[i+1] += mtimes(*powA_i[k], *b_discr);
}
```

with powA_i[i] = A_discr^i. I.e. in the second formulation I eliminate matrix multiplications up front. Xi, Ui are MX vectors and A_discr, B_discr, b_discr are DM's.

I ran an optimisation in ipopt using both formulations and code generation. Both gave the same result so I assume my implementation is correct. The computation time (wall time of 'mainloop') of the first implementation was about 10 % slower for a problem with 27 states X and 32 inputs U. Assuming that there may be some fixed overhead for solving the problems, the computation time difference may actually be larger when just looking at the evaluation time of the equations.
Also, the c code of the second formulation is about twice as large as the first formulation.

Are these differences expected?  

Please let me know if these kinds of issues belong in the user forum as I'm not sure!

Thanks!

**Comment by jaeandersson** [comment]
Yes, that sounds reasonable. Reordering the order of your operation, especially if it means precalculating certain subexpressions (like you did with with A above), can have impacts on the speed. Note that there is a multiply-accumulate operation in CasADi: `mac(A,B,C) = mtimes(A,B)+C`. Probably won't matter for you though.

**Comment by Mathadon** [comment]
okay, thx!
