### ISSUE TITLE
slack variables in QP

### ISSUE THREAD

**Issue by tor2d** [casadi/casadi#1961]
Hi.

I'm using CasADi and qpOASES to create an MPC algorithm by solving a QP. Because qpOASES fails when constraints are violated, I need to add slack variables to the constraints. However, doing so changes the QP from feasible to unfeasible. I find it hard to understand why this happens, as this is a standard straight forward implementaiton in MPC applications. Does anyone of you understand what is happening and how to solve this problem? 

I do the following in each iteration
tmp_Sk = S{k}
g = [g; [X{k}]];
lbg = [lbg; [lbx - tmp_Sk(1); ...];
ubg = [ubg; [ubx + tmp_Sk(1); ...];

**Comment by jaeandersson** [comment]
Please use the [forum](forum.casadi.org) for questions about usage. But since it's really a question about qpOASES, maybe it's better directed to the qpOASES people?
