### ISSUE TITLE
Accessing value of a symbolic variable

### ISSUE THREAD

**Issue by samiit** [casadi/casadi#1964]
I'm just getting introduced to CasADi, so please excuse me if it is a too trivial question.
I wanted to know if there is a way that I can access value of a symbolic variable, after optimization is done.
E.g. in the below code, how can I get the value of specific variables, `F[0]`
```
from casadi import *
F = SX.sym('Flow', 2)
obj = sum( F[i]**2 for i in range(2) )
c1 = F[0]**2 + F[1]
nlp = {'x':F, 'f': obj, 'g':c1}
solver = nlpsol('test', 'ipopt', nlp )
sol = solver(x0 =[5,5], ubg = 0, lbg = 0, lbx = [5,3])

```
I know the current method to access values using 
`sol['x'].full()`.
But is there a way to refer to the value associated with the Symbolic expression?

Thanks,
Sam

**Comment by jgillis** [comment]
Dear Sam, from a user perspective, your question makes perfect sense.
However, the anwer is no. We haven't come up yet with a maintainable way to implement this.

Some partial answers:
 - https://github.com/casadi/python-optistack/
 - http://casadi.sourceforge.net/v3.0.0/tutorials/tools/structure.pdf
 - https://gist.github.com/jgillis/de15f427174858f15414

**Comment by samiit** [comment]
Thanks for that answer in real-time!
