### ISSUE TITLE
Undeclared variables in the constraints

### ISSUE THREAD

**Issue by samiit** [casadi/casadi#1965]
As I'm just getting familiar with CasADi, I would like to know what happens if there are variables in the constraints, that are not declared as decision variables.
```
from casadi import *
F = SX.sym('Flow', 2)
C = SX.sym('conc', 1)

obj = sum( F[i]**2 for i in range(2) )
c1 = F[0] + F[1]**2 - C[0]
nlp = {'x':F, 'f': obj, 'g':c1} # here only F is included into the decision variables
solver = nlpsol('test', 'ipopt', nlp )
sol = solver(x0 =[5,5], lbg = 0, ubg = 0)
for i in range(2):
    solVal = sol['x']
    print 'F' + str(i+1), '=', solVal[i]
```

How can we get/fix their values, to say, some constant?

**Comment by jgillis** [comment]
Dear Sam,

You may bundle those constants as a parameter:

```
from casadi import *
F = SX.sym('Flow', 2)
C = SX.sym('conc', 1)

obj = sum( F[i]**2 for i in range(2) )
c1 = F[0] + F[1]**2 - C[0]
nlp = {'x':F, 'p',: C, 'f': obj, 'g':c1} # here only F is included into the decision variables
solver = nlpsol('test', 'ipopt', nlp )

for i in range(2):
    sol = solver(x0 =[5,5], C=i, lbg = 0, ubg = 0)
```

Please consider using our [forum](forum.casadi.org) for user questions..

**Comment by samiit** [comment]
Sorry for that. I did not know about the forum. I'll use it in future.

Thanks for your quick answer though.

**Comment by jgillis** [comment]
No problem, hope you'll have a nice time exploring CasADi..

**Comment by samiit** [comment]
I implemented your solution. Thanks.
I think you might consider correcting the last line -- the keyword for parameter is `p`.
