### ISSUE TITLE
Using casadi in simulink

### ISSUE THREAD

**Issue by BrunoMorabito** [casadi/casadi#1966]
Hi all,

I have an optimization problem that should run online in a simulink simulation. My idea was to import the matlab function which solves the optimization ( and calls casadi as "import casadi .") in a simulink block, but it turned out that "import" is not accepted for the compilation of the model.

The question is: is there a way interface casadi with simulink? There exist a tutorial for that?

Thanks very much in advance.

BTW CasADi is awesome!

Bruno

**Comment by jgillis** [comment]
Yes its possible, i guidamed a thesis student to do it. Basically you have to disable codegeneration of the matlab block. You have to run it through the matlab interpeter instead.

**Comment by BrunoMorabito** [comment]
There is an example or something?
