### ISSUE TITLE
Non-shortcircuiting if_else should be default for MX

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1968]
The shortcircuiting `if_else` for MX is error prone. I think we should change the default behavior to be `non-shortcircuiting`, just like for SX. Then, if you really want short-circuiting, you have to specify this. Or work with Function instead (which might be much cleaner).

Cf. #1967

```python
from casadi import *
c = SX.sym('c')
x = SX.sym('x')
y = SX.sym('y')
print(if_else(c, x, y)) # ((c?x:0)+((!c)?y:0))
c = MX.sym('c')
x = MX.sym('x')
y = MX.sym('y')
print(if_else(c, x, y, True)) # switch(c, x, y){0}
print(if_else(c, x, y, False)) # ((c?x:0)+((!c)?y:0))
print(if_else(c, x, y)) # switch(c, x, y){0}   <=== change this
```

**Comment by jaeandersson** [comment]
@ghorn @jgillis Agreed?

**Comment by ghorn** [comment]
Is the error-proneness is orthogonal to the decision?

**Comment by jaeandersson** [comment]
> Is the error-proneness is orthogonal to the decision?

Currently, the default behavior for MX (but not SX), is that when it encounters an expression such as
```
if_else(c, <some expression>, <some expression>)
```
to identify the primitives in the expressions and construct functions that are passed to the Switch node. This can lead to unnecessary recalculations in very simple cases, like:
```
x = <some very large and wieldy expression>
y = x + 1;
if_else(c, x, y)
```
It's better that the default for MX is the same as the default for SX, which is also less error prone.

**Comment by jgillis** [comment]
I have no opinion of this.
If your model needs switches, you must be doing it wrong he;-)

**Comment by jaeandersson** [comment]
OK, I'll go ahead with this then. Not sure if we need a soft deprecation for this... maybe not.
