### ISSUE TITLE
Inefficient c-code generation?

### ISSUE THREAD

**Issue by Mathadon** [casadi/casadi#1971]
I looked into the generated C code from casadi 3.1 when generating c code from an NLP solver. I have some suggestions based on an analysis of the code. It looks like the code generator could more efficiently formulate code that is inefficiently formulated by the user.

Code snippets:
```
  if (arg[1])
    copy(arg[1], 190, w4);

-- removed some irrelevant code here

  fill(w9, 25, 0.);
  /* #27: @10 = @9; (@10[0] += @1) */
  copy(w9, 25, w10);
  for (rr=w10+0, ss=(&w1); rr!=w10+1; rr+=1) *rr += *ss++;
  /* #28: @1 = 0 */
  w1 = 0.;
  /* #29: (@10[1] = @1) */
  for (rr=w10+1, ss=(&w1); rr!=w10+2; rr+=1) *rr = *ss++;
  /* #30: @1 = @4[46] */
  for (rr=(&w1), ss=w4+46; ss!=w4+47; ss+=1) *rr++ = *ss;
  /* #31: (@10[1] += @1) */
  for (rr=w10+1, ss=(&w1); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #32: @1 = 0 */
  w1 = 0.;
  /* #33: (@10[2] = @1) */
  for (rr=w10+2, ss=(&w1); rr!=w10+3; rr+=1) *rr = *ss++;
  /* #34: @1 = @4[47] */
  for (rr=(&w1), ss=w4+47; ss!=w4+48; ss+=1) *rr++ = *ss;
  /* #35: (@10[2] += @1) */
  for (rr=w10+2, ss=(&w1); rr!=w10+3; rr+=1) *rr += *ss++;

--- more of the same code removed here

  /* #117: (@10[23] = @1) */
  for (rr=w10+23, ss=(&w1); rr!=w10+24; rr+=1) *rr = *ss++;
  /* #118: @1 = @4[68] */
  for (rr=(&w1), ss=w4+68; ss!=w4+69; ss+=1) *rr++ = *ss;
  /* #119: (@10[23] += @1) */
  for (rr=w10+23, ss=(&w1); rr!=w10+24; rr+=1) *rr += *ss++;
  /* #120: @1 = 0 */
  w1 = 0.;
  /* #121: (@10[24] = @1) */
  for (rr=w10+24, ss=(&w1); rr!=w10+25; rr+=1) *rr = *ss++;
  /* #122: @1 = @4[69] */
  for (rr=(&w1), ss=w4+69; ss!=w4+70; ss+=1) *rr++ = *ss;
  /* #123: (@10[24] += @1) */
  for (rr=w10+24, ss=(&w1); rr!=w10+25; rr+=1) *rr += *ss++;
  /* #124: @5 = zeros(46x1, dense) */
  fill(w5, 46, 0.);


```
this code essentially copies inputs of the NLP into other vectors.

There are a few things that look like they could be simplified:

First issue:
```
 /* #28: @1 = 0 */
  w1 = 0.;
  /* #29: (@10[1] = @1) */
  for (rr=w10+1, ss=(&w1); rr!=w10+2; rr+=1) *rr = *ss++;
  /* #30: @1 = @4[46] */
  for (rr=(&w1), ss=w4+46; ss!=w4+47; ss+=1) *rr++ = *ss;
  /* #31: (@10[1] += @1) */
  for (rr=w10+1, ss=(&w1); rr!=w10+2; rr+=1) *rr += *ss++;
  /* #32: @1 = 0 */
```
This looks like it essentially sets

```
w1 = 0
w10[1] = w1
w1 = w[46]
w10[1] = w1
```
or equivalently
```
w10[1] = w[46]
```

Second issue:
This block of code is repeated multiple times. So in the case where a for loop could actually be used, it's not used. 

I looks like these two issues are related to the slicing operations that I do and how I declare variables, which seems to be a 1 to 1 mapping. Code:

```
MX Uopt 	= MX::sym("Uopt", n_optVarTot, 1);
MX p 		= MX::sym("p", n_timeVarTot + n_states, 1);					// parameters: time-dependent inputs and initial states
MX X0 		= p(casadi::Slice(0, n_states));							// initial states
MX Utime 	= p(casadi::Slice(n_states, n_states+ n_timeVarTot));

vector<MX> Ui = vector<MX>(intervals);
vector<MX> Uopt_i = vector<MX>(intervals);
vector<MX> Utime_i = vector<MX>(intervals);	

for i = ...
     Ui[i] = MX::zeros(n_inputs,1);
     Uopt_i[i] = Uopt(Slice(n_optVar*i, n_optVar*(i+1)));
     Utime_i[i] = Utime(Slice(n_timeVar*i, n_timeVar*(i+1)));
     int nOpt_i = 0, nTime_i = 0;
     for (int k = 0 ; k < n_inputs; k++){
          if (someCondition) {
               Ui[i](k,0) = someMXVector[nOpt_i]; 
               nOpt_i++;
          }else{	
               Ui[i](k,0) = Utime_i[i](nTime_i,0);	
               nTime_i++;
          }
     }
}
```

So I may be able to avoid it as a user, but still, these operations (mostly the first issue) could be made more efficient when doing some analysis while generating code? After all, all this code excerpt just gets the correct indices for an input vector and there is no need to actually generate code for the temporary variable `Ui` that is declared and used in some operation. The indices are known at compilation time so they can just directly be stored as some index vector over which can be iterated afterwards, instead of copying all numerical values of the index vector.

Third issue:
In snippet
```
  fill(w9, 25, 0.);
  /* #27: @10 = @9; (@10[0] += @1) */
  copy(w9, 25, w10);
```
why not just do?
```
fill(w10, 25, 0.);
```
Variable w9 is reused later on, but still it seems like extra overhead/memory is required for these operations. Why is this not omitted?

Do these questions/suggestions make sense?

edit: I tried to reformulate the code with a list access, but this does not seem to be supported in C++? I can't get a slice with a custom list (e.g. [0, 1, 5, 3]) of elements either? So then I can't simplify my code unless I reorder the elements in the vector?

**Comment by jaeandersson** [comment]
The auto-generated code is just that, auto-generated. There are a lot of optimizations that can be made, but the question is what makes sense to spend time on. An operation such as a copy is usually very fast and rarely a bottleneck in code. Even if it is a bottleneck, how much time should you spend on making something, what, 20 % faster?

About list access and C++, you should be able to slice using a `std::vector<int>{0, 1, 5, 3}`.

Your code is not structured in an efficient way. Rather than creating variables for "Uopt", "p" in the beginning and work with slices of them, you'd get more efficient code if you call "MX::sym" for each segment and collect them all in `std::vector<MX>` instances. And finally, define `Uopt` and `p` are a "vertcat" on those vectors. In general, slicing is not very efficient and should be avoided when possible.

**Comment by Mathadon** [comment]
Thanks for the tips. I will look into it!

I would indeed like to properly structure my code as I have the feeling this could lead to order(s) of magnitude difference in computation time if I don't think about what I'm doing. The problem is that as a novice user, it's not trivial to know what leads to efficient code and what doesn't, since I don't know what happens in the back end. So ideally this lack of knowledge is something that the casadi back-end can compensate for as much as possible when generating code. I realise that making the code generation fool-proof requires development work and that this is probably not high on the priority list, but that's some feedback from me anyway :) 
An alternative would be that I learn how casadi works, or what's efficient and what is not. I went through the casadi user guide, but it doesn't go into much detail about this. Is there additional material that I can have a look at?

Thanks!

**Comment by jaeandersson** [comment]
> An alternative would be that I learn how casadi works, or what's efficient and what is not. I went through the casadi user guide, but it doesn't go into much detail about this. Is there additional material that I can have a look at?

We have a new paper almost ready that describes the internals of CasADi a bit better. I will post this to the forum as soon as it's official, hopefully in the next couple of weeks.
