### ISSUE TITLE
DM to float conversion

### ISSUE THREAD

**Issue by KRaetze** [casadi/casadi#1973]
When you try to convert a DM vector or matrix using the `DM.__float__` method you get an error to notify the developers.

The error can be triggered by simply doing:

```
x = DM.zeros(1,2)
x.__float__()
```

**Comment by jgillis** [comment]
Fair enough, we were a bit liberal in issuing 'notify the developers' statements.
In this particular case, it's obvious that the user is mistaken. Per Python rules, __float__ is supposed to return a scalar number, which is impossible given the vector input.

**Comment by KRaetze** [comment]
This is true. However, in my particular case this behavior is also triggered as soon as I want to do something like this:

```
x =  [DM.ones(1,4), DM.zeros(1,5)]
list(map(abs, x))
```

In this case, it is not necessarily the users fault to call for `__float__`. Doing the same operation for a numpy array

```
x =  [np.ones((1,4)), np.zeros((1,5))]
list(map(abs, x))
```

results in the right behavior. Or am I mistaken to use the build-in `abs` function in this context?

**Comment by jgillis** [comment]
Ah, what you want is `fabs`, not `abs`

**Comment by KRaetze** [comment]
Works perfectly, thank you very much!
