### ISSUE TITLE
Suggestion to add a function for creating block diagonal matrices from provided arrays

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1978]
I think it would be great to have a function that allows creating a block diagonal matrix from a list (or similar) of given matrices, similar to `scipy.linalg.block_diag`, see https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.block_diag.html

Though this can in principle be achieved by repeated application of `casadi.blockcat` and according placement of zeros, I think having a convenience function would be useful.

Is it possible to implement such a function?

**Comment by jgillis** [comment]
Diagcat

Op 31-mrt.-2017 08:30 schreef "Adrian Bürger" <notifications@github.com>:

**Comment by jgillis** [comment]
diagcat

**Comment by adbuerger** [comment]
Cool, thanks!
