### ISSUE TITLE
Bonmin exitflags missing

### ISSUE THREAD

**Issue by Im-Sum-Guy** [casadi/casadi#1979]
When used in CasADi, Bonmin seems to lack exitflags. It should have them but they are commented out on line 365 of casadi/interfaces/bonmin/bonmin_interface.cpp
Does anyone know why this is? If possible, this should be fixed as the output returned by Bonmin is not very useful if you can't determine whether it is actually a solution or not.

**Comment by jaeandersson** [comment]
Sorry for late answer. We'll have a look at this.
