### ISSUE TITLE
Using WORHP

### ISSUE THREAD

**Issue by alexe15** [casadi/casadi#1980]
Hey, I am wondering if there is any documentation about how to use WORHP in CasADi. I installed WORHP properly (I can run the examples) but if I run e.g. 

nlp     = struct('x',yyCas,'f',ffiLocCas,'g',hhiCas,'p',pCas);
nnlp{i} = nlpsol('solver','worhp',nlp,nlp_opts);

I get an error message that states that no WORHP plugin is found

Error using casadiMEX
 on line 332 of file
 "/home/travis/build/casadi/binaries/casadi/casadi/core/function/plugin_interface.hpp"
Plugin 'worhp' is not found.

Error in casadi.nlpsol (line 672)
  [varargout{1:nargout}] = casadiMEX(852, varargin{:});

Error in run_ALADIN (line 49)
    nnlp{i} = nlpsol('solver','worhp',nlp,nlp_opts);

Error in main_PF_distr (line 339)
[xoptAL, loggAL] = run_ALADIN(ffifun,hhifun,nnhi,AA,zzci0,...

Is there an example somewhere, how to use WORHP in CasADi? I am using CasaDi 3,0 with MATLAB 2016b. 
Thanks in advance!
Alex

**Comment by jgillis** [comment]
The Worhp interface in the _binaries_ has been not working well.
Upcoming 3.2.0 will ship with a Worhp 1.10 interface
