### ISSUE TITLE
Make sure precompiled binaries can be used for C++ projects

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1982]

**Comment by jgillis** [comment]
Thats not true. At least the python ones contain everything. (Develop packages)

**Comment by jaeandersson** [comment]
> Thats not true. At least the python ones contain everything. (Develop packages)

Discovered that.

**Comment by jaeandersson** [comment]
CasADI compiles pretty smoothly in MSVC now. Errors have been resolved. Some warnings have been suppressed, others have been resolved.
