### ISSUE TITLE
Options are not properly passed to the conic solver

### ISSUE THREAD

**Issue by andrescodas** [casadi/casadi#1983]
I cannot get rid of the copyright notice of qpoases when using the conic solver

Check it in the example
` ./casadi/docs/examples/python/simple_lp.py `

by replacing the solver defining line by
`solver = conic('solver', 'qpoases', {'a':A},{'printLevel':'none'})`

With ipopt it appears the time statistics:
`solver = conic('solver', 'nlpsol', {'a':A},{'nlpsol':'ipopt','nlpsol_options.ipopt.print_level':0})`

**Comment by andrescodas** [comment]
When setting 'print_level 0' through the file ipopt.opt, I get the output:

WARNING: Tried to set option "print_level" to a value of "0",
         but the previous value is set to disallow clobbering.
         The setting will remain as: "print_level 0"

**Comment by jaeandersson** [comment]
When building from sources, there is a "WITH_NO_QPOASES_BANNER" in CasADi. @jgillis - can we enable this by default?

**Comment by jgillis** [comment]
I just flipped that switch
