### ISSUE TITLE
Regression bug linsol jac_sparsity

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1986]
```python
from casadi import *;
a=DM([[1,0,-1],[0,5,0],[0,0,3]]);
a=sparsify(a);
y=MX.sym('y',3);
print jacobian(solve(a,y),y).dim()
```

In 3.0.0, shows a sparse matrix,, in 3.1.0..develop, shows a dense matrix

**Comment by jaeandersson** [comment]
Ouch

**Comment by jgillis** [comment]
bump

**Comment by jaeandersson** [comment]
There is a bug inside SparsityInternal::btfUpper. The computed Dulmage-Mendelsohn decomposition is wrong and not consistent with dmperm in MATLAB or Octave.
