### ISSUE TITLE
3.6 binaries?

### ISSUE THREAD

**Issue by sundstrn** [casadi/casadi#1987]
Hi, 
 I run Visual Studio 2017 Preview on a Windows 7, 64-bit machine. Python 3.6 is supported by VS2017, hence I'd like to install the corresponding Casadi binaries. Any plans for when you'll add them?

BR /Nina

**Comment by jgillis** [comment]
Rather busy these days; probably by June..

**Comment by sundstrn** [comment]
OK, thanks for the quick reply!

**Comment by jgillis** [comment]
Now available in 3.2.0-rc1.
