### ISSUE TITLE
Remove WITH_SELFCONTAINED CMake option

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1990]
The `WITH_SELFCONTAINED` option looks like a weird design to me. Isn't a more natural design to allow the user to override `LIBRARY DESTINATION`, `ARCHIVE DESTINATION` and `RUNTIME DESTINATION`?
```
      install(TARGETS ${name}
        LIBRARY DESTINATION ${CASADI_LIBRARY_DESTINATION}
        ARCHIVE DESTINATION ${CASADI_ARCHIVE_DESTINATION}
        RUNTIME DESTINATION ${CASADI_RUNTIME_DESTINATION}
      )
```
Cf. #1988 #1989

**Comment by jaeandersson** [comment]
Ping @jgillis

**Comment by jgillis** [comment]
Legacy, from a time where the build system was going through rough waters, and i needed to deploy binaries.

**Comment by jaeandersson** [comment]
It ended up not getting removed, but refactored.
