### ISSUE TITLE
casadi_mem.h does not get installed

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#1992]
The [casadi_mem.h](https://github.com/casadi/casadi/blob/master/casadi/core/casadi_mem.h) file containing simplified C API for codegen (see #1767) does not get copied to the `include` dir when `CasADi` is installed with `sudo make install`.

casadi 3.1.1

**Comment by jaeandersson** [comment]
This has been resolved in the issue_1982 branch (not yet in develop), along with a major refactoring/cleanup of the build system. The "casadi_mem.h" file has now been renamed "mem.h" and been placed in the "casadi" directory. That is `#include <casadi/mem.h>`. Will be included in CasADi 3.2.

**Comment by jaeandersson** [comment]
Cf. https://github.com/casadi/casadi/commit/68ff6c301e4e1db80ecfc32de426db3d016831fb
