### ISSUE TITLE
Code generated with "with_mem" option set to True does not compile

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#1994]
If following example
```python
from casadi import *
x = SX.sym('x')
f = Function('f', [x], [sin(x)])
gen = CodeGenerator("f", {'mex' : False, 'with_header' : True, 'with_mem' : True})
gen.add(f)
gen.generate()
```
generates the follwing lines in the header
```c++
// f.h
#include "casadi_mem.h"
```
and in the source
```c++
// f.c
#include "casadi_mem.h"
#include <math.h>
```
When `f.h` and `f.c` are compiled in a separate project, the `casadi_mem.h` header is not visible to the compiler, even if `casadi` is in the include path. This is because `casadi_mem.h` is not copied to the include dir on installation (see #1992). Even if it was, the `#include "casadi_mem.h"` would not work, because `casadi_mem.h` is (supposedly) copied to `casadi/core`. The proper file path should be `<casadi/core/casadi_mem.h>` in order for the compiler to see it.

**Comment by jaeandersson** [comment]
Resolved in https://github.com/casadi/casadi/commit/68ff6c301e4e1db80ecfc32de426db3d016831fb
