### ISSUE TITLE
#define real_t causes name conflict with other libraries

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#1995]
In generated headers and in `casadi_mem.h` there is a definition of `real_t` type which looks like following:
```c++
/* Floating point type */
#ifndef real_t
#define real_t double
#endif /* real_t */
```
This can cause name conflicts with other libraries. For example, the [Blaze](https://bitbucket.org/blaze-lib/blaze) library defines the type `real_t` in its own namespace. If both Blaze header and `casadi_mem.h` (or a casadi-generated header)  are included in same compilation unit, it leads to an error:
```
/home/mkatliar/software/blaze/blaze/system/Precision.h:69:54: error: expected unqualified-id
BLAZE_CONSTRAINT_MUST_BE_FLOATING_POINT_TYPE( blaze::real_t );
                                                     ^
/home/mkatliar/Documents/MPI/cms/build/src/mpc/generated/include/cms_generated.h:7:16: note: expanded from macro 'real_t'
#define real_t double
               ^
```

**Comment by mkotlyar** [comment]
Furthermore, the declaration of `casadi_eval_t()` uses `double` and not `real_t`, and in the generated code the `to_double` define is 
```
#define to_double(x) (double) x
```
Shouldn't they both use `real_t`?

**Comment by mkotlyar** [comment]
1. Should `real_t` be a define or can it be a typedef? Making it a typedef will avoid conflict with the same name defined in a different namespace.
 2. Perhaps `real_t` should be renamed to something more specific, like `casadi_real_t'?

**Comment by mkotlyar** [comment]
`qpOASES` uses real_t too.

**Comment by jaeandersson** [comment]
"real_t" is an option in CodeGenerator, so I'd say we should just generate "double" by default. The user can always choose to change the "real_t" option in CodeGenerator to something else. I don't really like defining a "casadi_real_t" type, this is the kind of customization I'd prefer to do *before* code generation.
