### ISSUE TITLE
linearization function

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1997]
Cf. https://groups.google.com/forum/#!topic/casadi-users/dSMTyKtHbkQ

A linearization of an expression with respect to a variable can be easily and efficiently implemented as:
```python
def linearize(f, x):
  v = SX.sym('v', x.sparsity())
  v0 = SX.zeros(x.sparsity())
  return substitute(f + jtimes(f, x, v), vertcat(v, x), vertcat(x, v0))
```
Makes sense to add to the list of standard functions.

**Comment by rakeshv24** [comment]
@jaeandersson Can you share an example on how to use this function to linearize a nonlinear model around any state point along a trajectory?

**Comment by salmagro** [comment]
As a manner of reminder to myself, here you can find a simple example of how to use the linearization function.

For instance, let's consider the equation $f(x) = x^2$. Let's linearize the function $f(x)$ around the point $x_0$.
Using the built-in CasADI function you will get the following results:
```python
import casadi as cs

x = cs.SX.sym('x')
x0 = cs.SX.sym('x0')
rhs = x*x # Nonlinear equation

f = cs.Function('f', [x], [rhs])
f_linear = cs.Function('f_linear', [x, x0], [cs.linearize(rhs, x, x0)])
```
Note that is necessary to construct the functional object to use `cs.linearize`.

**Numerical example:**
Find the linear approximation $f(2.15)$ around $x_0 =2$.
```python
f(2.15) # -> DM(4.6225)
f_linear(2.15, 2.0) #-> DM(12.6)
```
As you see the linear approximation is not even close to its real value. I have noticed that with the current implementation on [commit](https://github.com/casadi/casadi/commit/9d47ecd5c66aa4d59dbdeed1afe81f161af11128), it is necessary to evaluate the linear function with the following syntax:

```python
f_linear(2.15 - 2.0, 2.0) #-> DM(4.6)
# f_linear(2.15 - 2.0, 2.0) ≈ f(2.15)
``` 
**Symbolical example:**
I wonder why the developer has not implemented the `cs.linearize` function as:
```python
def linearize_new(f, x, x0):
  x_lim = cs.SX.sym('x_lim', x.sparsity())
  return cs.substitute(f + cs.jtimes(f, x, x_lim - x0), cs.vertcat(x_lim, x), cs.vertcat(x, x0))
```
From my point of view, this implementation is more intuitive at the moment to evaluate it, numerically or symbolically.

```python
f_linear_new = cs.Function('f_linear_new', [x, x0], [linearize_new(rhs, x, x0)])

cs.linearize(rhs, x - x0, x0) # -> SX((sq(x0)+((x0+x0)*(x-x0))))
linearize_new(rhs, x, x0) # ->SX((sq(x0)+((x0+x0)*(x-x0))))
```
<details>
  <summary>Plotting code</summary>

```python
import numpy as np
import matplotlib.pyplot as plt
# Plot
t = np.linspace(0,7, 20)
plt.plot(t, f(t))
plt.plot(t, f_linear_new(t, 2), 'r')
plt.plot(2.15, f_linear_new(2.15, 2), 'r*')
```
</details>

![linear_example](https://user-images.githubusercontent.com/52298571/188081818-36f86b12-bc68-4353-b298-cce088ffd20f.png)
