### ISSUE TITLE
Broken veccat in Joris style with casadi 3.1

### ISSUE THREAD

**Issue by mzanon** [casadi/casadi#2003]
With previous versions of casadi, this syntax was correct
```python
V['d',i,veccat]
```
With casadi 3.1 it does not work anymore. I think it's because the under the hood something like this happens
```python
veccat(V['d',i])
```
while now it should be
```python
veccat(*V['d',i])
```

**Comment by jgillis** [comment]
As a temporary workaround, you may use `casadi._veccat`.
I'll be adding `cat` as a convenient alias.

**Comment by jaeandersson** [comment]
> I'll be adding `cat` as a convenient alias.

I propose `vvcat` instead of `cat`. Because `vec` + `vcat`.
