### ISSUE TITLE
Getting wrong optimal point with ipopt solver method

### ISSUE THREAD

**Issue by nitish6174** [casadi/casadi#2009]
Consider the following code:

```python
from casadi import SX, nlpsol

# Initialize problem
x = SX.sym('x', 2)

# Objective function
# Min: -(x^2 + y^2)
f = -(x[0]**2 + x[1]**2)

# Constraints
# x + y <= 10
# 0 <= x,y <= 100
g = x[0] + x[1]
solver_params = {
    "ubg": 10,
    "lbx": [0, 0],
    "ubx": [100, 100],
    "x0": [2, 2]
}

# Solve
solver = nlpsol("solver", "ipopt", {'x':x, 'f':f, 'g':g}, {})
sol = solver(**solver_params)

# Print solution
print "-----"
print "objective at solution = ", sol["f"]
print "primal solution = ", sol["x"]
```

It can be easily seen that the optimal point for the above problem is (0, 10) and (10, 0) with objective value of -100. However, the above code gives the solution as (5, 5) i.e. optimal value of -50 which is wrong.
This happens only when ```x0``` is either not set or is of the form (c, c).
However, setting ```x0``` to some other value like (2,1) or anything which is not of form (c, c) converges correctly to either of (0, 10) or (10, 0) as the solution.

I tried more examples and observed that when the gradient of objective function at ```x0``` is symmetrical w.r.t the feasible region, the algorithm does not converge to the optimal point.

I feel this issue belongs to IpOpt library and not to CasADi but still posting it here as my code is in CasADi and hope someone can resolve it here itself.
Sorry if this is already known but couldn't find any such issue on Casadi's or IpOpt's github.

**Comment by jgillis** [comment]
Not much we can do about it. Ipopt is a local solver; it may find a local optimum.
Perhaps you are interested in a global solver #1647 ?

**Comment by nitish6174** [comment]
But (5, 5) isn't even a local minima. Anyway, starting again from any point just around (5, 5) will lead to the optimal solution (unless that point is again of form (c,c)).  
As I am dealing with convex functions only, local optimum point finder suffices for me. It's only this corner case which needs to be resolved.  
The hack of starting around (5, 5) solves that.  
Thanks for your reply and mentioning about SCIP.

**Comment by jgillis** [comment]
Okay, I jumped too quickly to the conclusion. Yes, there may indeed be initial conditions that do not lead to convergence.
