### ISSUE TITLE
MATLAB equivalent to python function(method?) struct_symSX () and entry()

### ISSUE THREAD

**Issue by olzhas** [casadi/casadi#2022]
Hi,
could you please tell the MATLAB equivalent to python function(method?) struct_symSX () and entry() ?

thank you in advance for the assistance.

**Comment by jgillis** [comment]
Duplicate of #1388 
No progress yet on this part.
Perhaps you could have a look at @JonasKoenemann or https://gist.github.com/jgillis/de15f427174858f15414
