### ISSUE TITLE
Bonmin interface missing

### ISSUE THREAD

**Issue by Im-Sum-Guy** [casadi/casadi#2033]
The following is the result when trying to use bonmin:

CasADi warning: "The assertion "handle!=0" on line 265 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/function/plugin_interface.hpp" failed. 
PluginInterface::loadPlugin: Cannot load shared library 'libcasadi_nlpsol_bonmin.dll': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried 'C:\Users\...\Desktop\Matlab\CASADI' :
    Error code (WIN32): 127
  Tried '' :
    Error code (WIN32): 126
  Tried '.' :
    Error code (WIN32): 126
" issued  on line 127 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/function/plugin_interface.hpp". 
Error using casadiMEX
 on line 332 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/function/plugin_interface.hpp"
Plugin 'bonmin' is not found.

Note:
'libcasadi_nlpsol_bonmin.dll' is in fact in the 'C:\Users\...\Desktop\Matlab\CASADI' path

**Comment by jgillis** [comment]
Hi!
Is this with the binaries?

**Comment by Im-Sum-Guy** [comment]
I haven't touched the binaries and have only seen this issue after installing the latest update so my guess is that it has something to do with that.

**Comment by jgillis** [comment]
Thanks for reporting, ill have a look

Op 23-jun.-2017 10:04 schreef "Im-Sum-Guy" <notifications@github.com>:

**Comment by jgillis** [comment]
Does not reproduce on my local machine nor appveyor.

Is the problem isolated to 'bonmin'? e.g. does 'ipopt' work?

**Comment by Im-Sum-Guy** [comment]
Hey, I think that there was a problem with how I updated casadi. I did a fresh install and I'm not seeing the issue any more.

**Comment by jgillis** [comment]
How did you update CasADi?
Could it be you didn't start a fresh Matlab after updating?
