### ISSUE TITLE
C interface to SNOPT changed

### ISSUE THREAD

**Issue by kribe48** [casadi/casadi#2034]
Hi! I am trying to integrate SNOPT with casADi. It seems like the C interface to SNOPT has been updated ( `snopt_cwrap.h` in https://github.com/snopt/snopt-interface) and are not compatible with your `snopt_interface.cpp`. Some changes that I have found are:

- The `snProblem` struct does no longer include variables such as `x, bl, bu, pi ...`
- `solveC` is called directly with the removed variables from `snProblem` and returned by reference.
-  The `iPrint`argument to `snInit` is removed.

Is this something you already noticed and are planning to fix?

Regards, Kristoffer

**Comment by jaeandersson** [comment]
Ah, breaking changes! I won't be able to fix it right now (@jgillis?). But if you're able fix it yourself, feel free to make a pull request.

**Comment by jgillis** [comment]
Was fixed in aff21e7becd3c4ef215eb7f009f9f50c44bbd45c
