### ISSUE TITLE
WORHP can handle when lbx==ubx 

### ISSUE THREAD

**Issue by kribe48** [casadi/casadi#2035]
I used WORHP v.1.10 together with casADi to solve an NLP with equality constraints, and ended up with the error `WorhpInterface::evaluate: Worhp cannot handle the case when LBX == UBX`.  I tried to solve this by removing the lines 276-285 in `worhp_interface.cpp` where assertions are made to check if lbx==ubx. After that, WORHP was able to solve the problem. Hence, it seems like the assertions is not necessary anymore and that WORHP handles the classification of equality constraints internally.

**Comment by jaeandersson** [comment]
Thanks for reporting. I've removed the assertions.
