### ISSUE TITLE
Rename or add rows (columns)

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2036]
The MATLAB/Octave syntax for getting the number of rows (columns) is "rows" ("columns"). CasADi is currently using "size1" ("size2").
Cf. https://groups.google.com/forum/#!topic/casadi-users/vfxdLX9sbM4

**Comment by jaeandersson** [comment]
@jgillis Rename or allow both syntaxes?

**Comment by jgillis** [comment]
Rename, but deprecate for til 3.3

**Comment by jaeandersson** [comment]
OK, agreed. `rows` is more understandable than `size1`.

**Comment by jaeandersson** [comment]
Just realized that `rows`/`columns` is Octave specific. It doesn't work in MATLAB. @jgillis Should we still make it the default?

**Comment by jaeandersson** [comment]
Added new syntax side-by-side. Didn't deprecate old since it's disruptive and not valid MATLAB.
