### ISSUE TITLE
General Question about Casadi

### ISSUE THREAD

**Issue by tn0432** [casadi/casadi#2037]
I have a theoretical question about the optimization method. Casadi applies the primal-dual interior point (IPOPT) for NLP solver. And I also know another solver named least-squares Gauss-Newton optimization. What is the main difference between two methods in term of computation cost and numerical stability? I believe that two methods should give the same answer. 

Thanks  

P.S. It is not an issue, just want to clarify my understanding.

**Comment by jaeandersson** [comment]
Please consult a textbook on numerical optimization.
