### ISSUE TITLE
Determine if input is SX or MX

### ISSUE THREAD

**Issue by RubenRybnick** [casadi/casadi#2038]
Hey,

first sry for my English.

I want to transfer a Matlab script into Python and that lovely Matlab Script uses Casadi. In Matlab its pretty easy to check if the Matrix is some kind of Casadi Matrix. I just use

isa(matrix,'casadi.MX') and it works fine

i tried something similar in Python but it doesnt work. I just did a easy check like:

x=SX.sym('x',2,2)

a= x is SX

and it says false. Same with

x is SX.sym etc. Does somebody have a solution? I dont know how to solve this. Thank you

**Comment by jgillis** [comment]
`isinstance` is what your after. `is` checks for equivalence
