### ISSUE TITLE
Migrate binaries to conda

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2062]
Major undertaking. Prob several weeks

We better split up into casadi-c++ and casadi-python, casadi-matlab, ...

Prerequisites:
 * [ ] CasADi runs with VS

**Comment by pstjohn** [comment]
`conda-forge` is a great option, if the alternative is to host your own conda channel. [conda-forge/casadi-feedstock](https://github.com/conda-forge/casadi-feedstock) could certainly be improved, and windows builds need to be added. If that's the route you want to go I'm happy to add you as a maintainer.

Dependency resolution can be handled nicely through conda, but we still need windows binaries for several dependencies.

**Comment by jgillis** [comment]
Pro:
 - no need to maintain existing packages (e.g. ipopt)
 - quality dependencies (e.g ipopt *)

Con:
 - wheel will need to ship all things but the kitchen sink
 - dependencies can fluctuate chaotically

(*)
```
    certifi-2021.10.8          |  py310h5588dad_1         145 KB  conda-forge
    intel-openmp-2021.4.0      |    h57928b3_3556         3.2 MB  conda-forge
    ipopt-3.14.4               |       hf6be2e5_0         1.0 MB  conda-forge
    libblas-3.9.0              |     12_win64_mkl         4.5 MB  conda-forge
    libflang-5.0.0             |h6538335_20180525         519 KB  conda-forge
    liblapack-3.9.0            |     12_win64_mkl         4.5 MB  conda-forge
    llvm-meta-5.0.0            |                0           3 KB  conda-forge
    metis-5.1.0                |    h0e60522_1006         4.4 MB  conda-forge
    mkl-2021.4.0               |     h0e2418a_729       181.7 MB  conda-forge
    mumps-seq-5.2.1            |      hb3f9cae_10         6.4 MB  conda-forge
    openmp-5.0.0               |           vc14_1         577 KB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    tbb-2021.4.0               |       h2d74725_1         149 KB  conda-forge
```

**Comment by jgillis** [comment]
Moved to github actions, still pip wherls
