### ISSUE TITLE
Truncate string formatting of large matrices

### ISSUE THREAD

**Issue by pstjohn** [casadi/casadi#2064]
This is an odd error you get if you mistakenly try to get a string representation of a large matrix:
```python
import casadi as cs
cs.DM.zeros(2000, 2000)
```
```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

With casadi 3.1.1 and jupyter notebook 5.0.0

It's because it tries to print out the entire matrix structure. How hard would be it be truncate the row/column output similar to numpy?

**Comment by jaeandersson** [comment]
Numpy appears to truncate when the number of elements is greater than 1000. That's reasonable I guess

**Comment by pstjohn** [comment]
I think its actually far less than that:
```python
import numpy as np
np.zeros((2000, 2000))
```
```
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])
```

**Comment by jaeandersson** [comment]
Truncation has been implemented and is the default behavior:
 * `print_dense` and `print_vector` truncate matrices/vectors with more than 1000 elements
 * `print_sparse` truncates matrices with more than 1000 nonzeros

Truncation can be disabled by calling `print_dense`, `print_sparse` and `print_vector` directly while setting `truncate=false`.

Note that the standard `print` function is a heuristic that redirects to `print_dense`, `print_sparse`, `print_vector` or `print_scalar`.

**Comment by pstjohn** [comment]
Awesome! Thanks for implementing this
