### ISSUE TITLE
Drop numpy ABI dependency?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2067]
We are using a select few C numpy commands to read in numpy matrices and write them out.
This means that, to compile CasADi's  python interface, you have to have numpy headers available,
and binaries might break on a numpy ABI mismatch.

What if we replace those few numpy calls with interpreted python commands?

**Comment by jaeandersson** [comment]
Are we talking about the content of `casadi_numpy.hpp` ?

**Comment by jgillis** [comment]
Yes, in particular arrayobject.h

Op 28-aug.-2017 00:50 schreef "Joel Andersson" <notifications@github.com>:

Are we talking about the content of casadi_numpy.hpp ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/casadi/casadi/issues/2067#issuecomment-325230027>, or mute
the thread

**Comment by jaeandersson** [comment]
Makes sense.

**Comment by jgillis** [comment]
Numpy purged
