### ISSUE TITLE
 Error using casadiMEX vector::_M_range_check

### ISSUE THREAD

**Issue by BrunoMorabito** [casadi/casadi#2072]
Hi all,

I am trying to run a least square parameter estimation with matlab, but I encounter the following error 

> Error using casadiMEX
vector::_M_range_check
> Error in casadi.nlpsol (line 856)
  [varargout{1:nargout}] = casadiMEX(861, varargin{:});
>Error in run_paramEst (line 140)
  S = nlpsol('S','ipopt',nlp);

here a piece of the code:

    while time < 0.850
          opt.t0 = timeMeas(ii);
          opt.tf = timeMeas(ii+1);
           odeIntegrator = integrator('odeIntegrator','idas',ode,opt);
          r_ii = odeIntegrator('x0',x0,'p',parDynamics);
    
          x0 = r_ii.xf;
    
           yk = outputFunction(r_ii.xf,parOutput);
           arg = struct('y',yk,'y_meas', realOutput(ii));
    
          eval_fun_J_term = fun_J_term.call(arg);
          J = J + eval_fun_J_term.cost;
    
         time = timeMeas(ii+1);
         ii = ii+1;
    end 
    nlp = struct('x',[parDynamics;parOutput],'f',J);
    S = nlpsol('S','ipopt',nlp);
    p0 = [0.3574;2.39;-0.17];
    resLeasSquare = S('x0',p0);
 
    p_star = resLeasSquare.x;`

It seems that it has something to do with the inputs and outputs. The inputs of the objective function J should be parOutput, and parDynamics. And they do appear in the objective function I am trying to minimize.

**Comment by BrunoMorabito** [comment]
Problem solved. I wrote 
`outputFunction = Function('outputFunction',{x,parOutput},{CRP_opt},{'x'},{'outputFunction'});`

instead of

`outputFunction = Function('outputFunction',{x,parOutput},{CRP_opt},{'x','parOutput'},{'outputFunction'});`

**Comment by jaeandersson** [comment]
Great that it got resolved. In the next release (3.3), you should get a much more readable and detailed error message for errors like this.
