### ISSUE TITLE
casadi 3.2.x binaries and numpy compatibility

### ISSUE THREAD

**Issue by blumenta** [casadi/casadi#2078]
Hi, I need some help. I downloaded casadi binaries (casadi-py27-np1.9-v3.2.1) but when trying to import casadi the following exception is raised:
"""
CasADi is not running from its package context.

            You probably specified the wrong casadi directory.

            When setting PYTHONPATH or sys.path.append,
            take care not to add a trailing '/casadi'.
"""
(This is using Python version : 2.7.13, numpy: 1.9.3 or 1.9.2)

When downgrading numpy to 1.9.0 or 1.9.1 I get the following error:
"""
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-910a8d258b63> in <module>()
----> 1 import casadi

/home/blumenta/packages/casadi-py27-np1.9-v3.2.1/casadi.py in <module>()
    345 SwigPyIterator_swigregister(SwigPyIterator)
    346 
--> 347 L_INT = _casadi.L_INT
    348 L_BOOL = _casadi.L_BOOL
    349 LL = _casadi.LL

AttributeError: 'module' object has no attribute 'L_INT'
"""

Are these errors due to compatibility problems with the numpy version? If so, which version should I use? The same kind of problems are encountered with casadi 3.2.x versions using python 3.5 and 3.6

The binaries I have for casadi 3.1.1 and below work fine, the one I'm currently using is casadi-py27-np1.9.1-v3.1.1 with numpy 1.9.2. I would like to update though. 

Thanks,

Alejandro Blumentals

**Comment by blumenta** [comment]
Ahh, yes...

It appears that when I extract the contents of  
casadi-py36-np1.11-v3.2.2.tar.gz

I get only a 'casadi' folder. The 'include' folder is not in the tar file as it used to be in the previous versions...

**Comment by blumenta** [comment]
Hi, I don't know if anyone else has been having issues with the latest binaries.
Here is the issue I found and how I resolved it locally.

The newer binary releases like casadi-py36-np1.11-v3.2.2.tar.gz have a different directory structure than the older releases. 
In the 3.1 version releases the directory layout was 
casadi-pyversion-npversrion-casadiversion/
-/casadi
-/include

In the 3.2 version releases the directory layout is 
casadi-pyversion-npversrion-casadiversion/
-/casadi
    -/casadi
    -/include
    -casadi.py
To correct the issue I had to move the include folder one level up so as to have the same directory layout than in older releases.  Ideally the directory layout of the binary releases for casadi 3.2 python versions on linux should be corrected so that the end users don't have to do this manipulation.

**Comment by jgillis** [comment]
This is weird. The archive is in fact correct. It seems like your unzipper programs treats archives with a single folder-or-file on top-level in a diffferent way than archives with multiple folder-or-files on top-level.

To test the hypothesis, it would be _very_ helpful if you could test the four variants of archive structure:
https://github.com/casadi/casadi/releases/tag/3.2.2

**Comment by blumenta** [comment]
I downloaded the 4 archives test{a,b,c,d}.tar.gz
I executed for each file the command : tar -xvzf test.tar.gz > test.txt
and I attach the results in test{a,b,c,d}.txt . The resulting directory structure is like what I defined in my comment above. 
I tried the same with  the archive casadi-py35-np1.9.1-v3.1.1.tar.gz and got the correct structure, I attach the results in teste.txt .  


[testa.txt](https://github.com/casadi/casadi/files/1344113/testa.txt)
[testb.txt](https://github.com/casadi/casadi/files/1344114/testb.txt)
[testc.txt](https://github.com/casadi/casadi/files/1344115/testc.txt)
[testd.txt](https://github.com/casadi/casadi/files/1344116/testd.txt)
[teste.txt](https://github.com/casadi/casadi/files/1344127/teste.txt)

**Comment by jgillis** [comment]
Thanks for your help!

I'm confused though. The desired outcome is this (with casadi-pyversion-npversrion-casadiversion on your pythonpath):
```
casadi-pyversion-npversrion-casadiversion
  - casadi
      - casadi
      - include
      - casadi.py
  - (dummy.txt)
```
Is none of the test cases providing you that structure?
in 31, it was
```
casadi-pyversion-npversrion-casadiversion
  - casadi
      - casadi
      - casadi.py
  - include
```

**Comment by jgillis** [comment]
Closing due to non-activity. I think we should promote the pip install option more; less things can go wrong with it..
