### ISSUE TITLE
'lam_p' not being calculated for Nlpsol

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2080]
The calculation of `lam_p` appears to be broken: https://groups.google.com/forum/#!topic/casadi-users/tTa3eT_ZUmI

Cf. #724

**Comment by andrescodas** [comment]
Hi @jaeandersson ,

By coincidence, I have been debugging on something related.  Check the following bug:

from casadi import *

x = SX.sym("x", 2)

lbx = -DM.ones(x.shape[0], 1)
ubx = +DM.ones(x.shape[0], 1)

lbx[0] = 1
ubx[0] = 1

f = x[0] + x[1]  # objective
nlp = {'x': x, 'f': f}

MySolver = "ipopt"

solver = nlpsol("solver", MySolver, nlp)

sol = solver(lbx=lbx, ubx=ubx)

gradLag = jacobian(f, x) + sol['lam_x'].T
gL = Function('gL',[x],[gradLag])

print("-----")
print("KKT stationarity = ", gL(sol['x']))
assert(norm_inf(gL(sol['x'])) < 1e-6)

  I realized that whenever there are equalities on the decision variables, the dual variables related to them are not returned by Ipopt.  In ipopt_nlp.cpp, In the call 

 tnlp_adapter->ResortBnds(z_L, z_L_, z_U, z_U_);

The values related to the fix variables are not populated.  I believe this is somehow related to the indexes set on bnds_pos_not_fixed within ResortBnds, but I need to debug more to come to a conclusion.  I believe this will also fix the issue I explained on this post:

https://groups.google.com/forum/#!topic/casadi-users/yyvpj5gaf0k

**Comment by jaeandersson** [comment]
Will now be calculated if you set the option `calc_multipliers` to true.

**Comment by andrescodas** [comment]
By default, fixed variables are dealt as parameters and eliminated from the problem by Ipopt:

If you want to force Ipopt to calculate multipliers for those variables, you should set the option
opts = {'ipopt.fixed_variable_treatment': 'make_constraint'}

see:

https://www.coin-or.org/Ipopt/documentation/node44.html#opt:fixed_variable_treatment

**Comment by jaeandersson** [comment]
> By default, fixed variables are dealt as parameters and eliminated from the problem by Ipopt:

@andrescodas Sure, this is a long-known issue #667

What the implemented solution does is to circumvent that in a non-solver specific way and calculates the multipliers for all parameters, both those seen by e.g. IPOPT ("lam_x") and those not seen by IPOPT ("lam_p"). Using the KKT conditions, multipliers can be calculated cheaply using reverse mode AD if you have the primal solution ("x") and the multipliers for the nonlinear constraints ("lam_g").

**Comment by jaeandersson** [comment]
Will close this, although continued improvements can definitely be made.
