### ISSUE TITLE
const-correctness of casadi_eval_t arguments

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#2091]
`casadi_eval_t` is defned as follows:
https://github.com/casadi/casadi/blob/64b7712a548e929515ba68b271e60c42546742ef/casadi/mem.h#L49

The `arg` points to an array of pointers which are not supposed to be modified by `casadi_eval_t`. Therefore, the type of `arg` should be `const casadi_real_t * const *`, i.e. the pointers should be const too.

The same applies to `res`: since the pointers are not supposed to be modified by the function, it should be `casadi_real_t * const *`.

The way it is defined now requires `const_cast<>` in some cases.

**Comment by jaeandersson** [comment]
No, your assessment is incorrect. `arg` (`res`) consists of input (output) arguments as well as temporary memory used by the code generated function. The `arg` and `res` vectors can be longer than just the function arguments. See for example here: 

https://github.com/casadi/casadi/blob/c632825644462547683a3cf5b5ca98c3b3ea6e53/docs/examples/cplusplus/codegen_usage.cpp#L143

The length of the array is `sz_arg`, which is not necessary the same as `n_in` (it can be longer).
