### ISSUE TITLE
NLP Example Compiling Error

### ISSUE THREAD

**Issue by Pedro-Roque** [casadi/casadi#2092]
Hi everyone,

I cannot compile this example on my setup:
https://github.com/casadi/casadi/blob/master/docs/examples/cplusplus/nlp_codegen.cpp

I am compiling only up to line 59:
https://github.com/casadi/casadi/blob/master/docs/examples/cplusplus/nlp_codegen.cpp#L59

The errors are the following:
`nlp_codegen.cpp: In function ‘int main()’:
nlp_codegen.cpp:56:77: error: ‘nlpsol’ was not declared in this scope
   Function solver = nlpsol("solver", "ipopt", {{"x", x}, {"f", f}, {"g", g}});
                                                                             ^
nlp_codegen.cpp:59:10: error: ‘class casadi::Function’ has no member named ‘generate_dependencies’
   solver.generate_dependencies("nlp.c");
`

**Comment by jaeandersson** [comment]
How did you try to compile it? It looks like you haven't set up your compiler right. I don't see how this has anything to do with codegen if your error message is that "nlpsol" isn't defined.

**Comment by jaeandersson** [comment]
Can you run other examples?

**Comment by Pedro-Roque** [comment]
Hello Jean,

What I've done was installing CasADi from sources, on Linux Mint (Ubuntu based 16.04), using the instructions provided and with -DWITH_IPOTP , which enabled the NLP solver.

Did make and sudo make install afterwards. Everything went alright.

Now, I tried to compile the example with "g++ -std=c++11 nlp_codegen.cpp", and got these errors:
`nlp_codegen.cpp:(.text+0x19a): undefined reference to `casadi::MX::~MX()'
nlp_codegen.cpp:(.text+0x1c7): undefined reference to `casadi::MX::~MX()'
nlp_codegen.cpp:(.text+0x20d): undefined reference to `casadi::MX::MX(double)'
nlp_codegen.cpp:(.text+0x2b0): undefined reference to `casadi::MX::~MX()'
nlp_codegen.cpp:(.text+0x2dd): undefined reference to `casadi::MX::~MX()'
`
It seems that I am not able to find the installed library. However, the library exists under /usr/local/include/casadi . Anything you can pin-point me to?

**Comment by jaeandersson** [comment]
It's a linking error, you need to link with `libcasadi.so`. Maybe `g++ -std=c++11 -lcasadi nlp_codegen.cpp` ?

**Comment by jaeandersson** [comment]
The library is probably installed under `/usr/local/lib`, which is probably in your path on Ubuntu.

**Comment by Pedro-Roque** [comment]
It still did not work, and I can confirm that I have `libcasadi.so` under `/usr/ocal/lib `

**Comment by Pedro-Roque** [comment]
Got the same problem, and I can confirm that libcasadi.so is under /usr/local/lib .

Moreover, I tried with `g++ -std=c++11 /usr/local/lib/libcasadi.so nlp_codegen.cpp` and  `g++ -std=c++11 -L/usr/local/lib -lcasadi nlp_codegen.cpp` without success

**Comment by jaeandersson** [comment]
Your errors are not really CasADi related. You might need to ask someone with experience in writing and compiling C++ code on Linux systems. CasADi is built in a standard way: There is an include directory and a library. You might want to use CMake to build your example: There is a FindCASADI.cmake in the CasADi source if you want to compile a stand-alone example.

**Comment by Pedro-Roque** [comment]
Ok, I managed to get it to find CasADi lib, now the error went to:
 "Cannot open "nlp.so". Error code: nlp.so: cannot open shared object file: No such file or directory". This is not on the lib folder, so maybe I forgot one flag? I used the -DWITH_IPOPT though.

**Comment by zehuilu** [comment]
When I was reproducing the same example with my own cmake stuff, I had the same error here. And adding the current folder to LD_LIBRARY_PATH solely didn't work (like this [way](https://stackoverflow.com/questions/30380257/how-can-ld-library-path-be-changed-within-cmake)).

But it works if I have a prefix for the .so file showing an absolute path. Like this:
`casadi::Function solver = casadi::nlpsol("solver", "ipopt", "/absoluate_prefix/nlp.so");`

I post my solution here in case anyone has a similar issue and wants an explicit answer. An example with all cmake stuff is [here](https://github.com/zehuilu/Tutorial-on-CasADi-with-CPP/blob/main/example/example_use_nlp_external.cpp#L28-L29).
