### ISSUE TITLE
Inlining instructions ignored?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2102]
```python

from casadi import *

N = 3
a = SX.sym("a",N,N)
A = MX.sym("a",N,N)

f = Function("f",[a],[det(a)]);

print f.call([A],True,False)
```

**Comment by jaeandersson** [comment]
Hmm, it's not able to inline an SXFunction into an MX graph. Although, maybe we could certainly implement this...

**Comment by jaeandersson** [comment]
It's missing an error message though..

**Comment by jgillis** [comment]
Thought this was a regression. It's not very useful functionality anyway
