### ISSUE TITLE
Wrong sz_w in codegen output

### ISSUE THREAD

**Issue by nielsvd** [casadi/casadi#2105]
Using code generation in the latest version of the ``develop`` branch (3.2.0+-573-gff1bf4b2f) the ``NAME_w()`` routine gives a non-zero value for ``sz_w``, even if the work vector ``w`` is used nowhere in the file.

mwe:
```python
from casadi import *
x = SX.sym('x',5,5);
f = Function('f',[x],[det(x)]);
cg = CodeGenerator('foo');
cg.add(f);
print(cg.dump())
```
returns at the bottom of the code generated file:
```c
CASADI_SYMBOL_EXPORT int f_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 25;
  return 0;
}
```

**Comment by jaeandersson** [comment]
This is known and expected. Not a bug but a (minor) performance issue.
