### ISSUE TITLE
Discrepancy in mtimes versus jtimes

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2107]
```python
x = SX.sym("x")

for c in [SX.zeros(0,1),SX.zeros(1,0)]:
  print mtimes(jacobian(x,x),c).shape, jtimes(x,x,c).shape
```

**Comment by jaeandersson** [comment]
The shape of `jtimes` should is that of the output expression, always. It's just a convenient name for a directional derivative. It is not guaranteed to be the same as `mtimes(jacobian(...))`. That being said, the handling of zero dimensions is weird indeed.

**Comment by jgillis** [comment]
Is it `times(...)` + a change in sparsity, then?

**Comment by jaeandersson** [comment]
No, not `times`. It's a (conceptual) matrix multiplication, not elementwise multiplication.

**Comment by jaeandersson** [comment]
For forward mode and `v.size()==x.size()`, `jtimes(f,x,v)` should be equivalent to `reshape(mtimes(jacobian(vec(f),vec(x)), vec(v), f.size())`

**Comment by jgillis** [comment]
Obvious typo of course i meant mtimes

**Comment by jaeandersson** [comment]
Should be fixed now.
