### ISSUE TITLE
Avoidable complexity in ndeps suspected in sort_depth_first

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2109]
Instead of looping through all dependencies,
```
        int max_deps = -1, dep_with_max_deps = -1;
        for (int i=0; i<t->n_dep(); ++i) {
          if (t->dep(i).get() !=0 && static_cast<NodeType*>(t->dep(i).get())->temp == 0) {
            int ndep_i = t->dep(i)->n_dep();
            if (ndep_i>max_deps) {
              max_deps = ndep_i;
              dep_with_max_deps = i;
            }
          }
        }
```

idea: a `stack<int> temp_stack` next to existing `int temp` member, which holds indices into dependencies, sorted by `n_dep`. Instead of the for loop, we pop elements until we find one with `temp==0`.
The down-side is obvious: more memory usage.

**Comment by jgillis** [comment]
```python

from casadi import *

import time

N = 2

while True:
  v = hcat([MX.sym("a%d" % i) for i in range(N)])
  w = MX.sym("w")
  z = v+w

  t0  = time.time()
  f = Function("f",[v],[z])
  print(N, time.time()-t0)
  
  N*=2
```

```
(2, 0.0003390312194824219)
(4, 0.00026798248291015625)
(8, 0.0003020763397216797)
(16, 0.00033092498779296875)
(32, 0.0005190372467041016)
(64, 0.0009500980377197266)
(128, 0.0015690326690673828)
(256, 0.005113840103149414)
(512, 0.016993045806884766)
(1024, 0.07013487815856934)
(2048, 0.25435805320739746)
(4096, 1.0950219631195068)
(8192, 4.05722713470459)

```

**Comment by jgillis** [comment]
Instead of adding memory to MXnode, we may resirt to a hasmap local to thde method..

**Comment by jaeandersson** [comment]
We can't add more mutable members. If anything, we should remove `int temp`. The bucket sort algorithm is linear in complexity and I'm sure that it can be adopted to handle a large number of `ndep`.

**Comment by jaeandersson** [comment]
The `for (int i=0; i<t->n_dep()` loop is just for convenience, to get a particular order of the nodes. When it was written "ndep" was a small number, so it didn't really matter. The algorithm can be refactored to get rid of the for loop, without any added data members. It will result in a different (but valid) topological sorting however, which might have a performance penalty if done wrong.

**Comment by jgillis** [comment]
Ive planned an update that leaves topological order intact, does not add
data members, and has improved complexity in n_dep. Dont worry i will not
merge at will

Op 16-okt.-2017 18:51 schreef "Joel Andersson" <notifications@github.com>:

The for (int i=0; i<t->n_dep() loop is just for convenience, to get a
particular order of the nodes. When it was written "ndep" was a small
number, so it didn't really matter. The algorithm can be refactored to get
rid of the for loop, without any added data members. It will result in a
different (but valid) topological sorting however, which might have a
performance penalty if done wrong.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/casadi/casadi/issues/2109#issuecomment-336950071>, or mute
the thread

**Comment by jgillis** [comment]
Nice expression to check if topological ordering is preserved:
```
from casadi import *
import numpy as np
np.random.seed(0)

N = 10
x = [MX.sym("x%d" % i) for i in range(N)]
xs = list(x)
for i in range(10):
  a = [x[np.random.randint(N)] for i in range(1+np.random.randint(N-1))]
  c = diagcat(*a)
  x[np.random.randint(N)] = c
  

f = Function('f',xs,[c])

  
cg = CodeGenerator('foo')
cg.add(f)
```

**Comment by jgillis** [comment]
Joel suggests to drop the heuristic entirely, yielding a linear complexity:

```
(2, 0.00024390220642089844)
(4, 0.00015497207641601562)
(8, 0.0002789497375488281)
(16, 0.00027489662170410156)
(32, 0.0002689361572265625)
(64, 0.00032901763916015625)
(128, 0.0006480216979980469)
(256, 0.0013301372528076172)
(512, 0.0029571056365966797)
(1024, 0.004503965377807617)
(2048, 0.00882101058959961)
(4096, 0.021209001541137695)
(8192, 0.03648996353149414)
(16384, 0.06220698356628418)
(32768, 0.18300414085388184)
(65536, 0.3071708679199219)
(131072, 0.5114729404449463)
(262144, 0.9716949462890625)
(524288, 2.106825113296509)
```
