### ISSUE TITLE
Sparsity propagation in Callbacks

### ISSUE THREAD

**Issue by andrescodas** [casadi/casadi#2113]
Up to Casadi 3.2.2 I was using set_jac_sparsity with Callbacks but now on develop this function is no longer available. This was useful to unveil variables relationships with which_depends.  It seems that I can restore this functionality if I could override sp_fwd, sp_rev and sparsity_jac but these seems not to be interfaced to python.  Is this the way to go, or is there other way I'm missing?

**Comment by jgillis** [comment]
Now back in 3.5.2, see release notes
