### ISSUE TITLE
Fix bilin

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2123]
While adding unittests, some issues appeared with `bilin`.
Dependency missing:
https://github.com/casadi/casadi/blob/3.3.0-rc1/casadi/core/bilin.cpp#L32
Projection with mismatching shapes:
https://github.com/casadi/casadi/blob/3.3.0-rc1/casadi/core/bilin.cpp#L57

Afaict, the correct thing to do is to not have a project there, but fix `sp_reverse`: there should be nonzero-contributions for `arg[0]` coming from `x y'`

```python
from casadi import *

x = MX.sym("x",3,3)
y = MX.sym("y",3,1)
z = MX.sym("z",3,1)

import numpy
numpy.random.seed(42)
x0 = numpy.random.random((3,3))
y0 = numpy.random.random((3,1))
z0 = numpy.random.random((3,1))

f = Function('f',[x,y,z],[mtimes(mtimes(y.T,x),z)],["x","y","z"],["f"])

J = f.factory("f",["x","y","z"],["jac:f:x"])
print(J(x0,y0,z0))

f = Function('f',[x,y,z],[bilin(x,y,z)],["x","y","z"],["f"],{"verbose":True})

J = f.factory("f",["x","y","z"],["jac:f:x"])
print(J(x0,y0,z0))
```

**Comment by jaeandersson** [comment]
> Afaict, the correct thing to do is to not have a project there, but fix sp_reverse: there should be nonzero-contributions for arg[0] coming from x y'

I don't think that's correct. You need the project in order to avoid creating a lot of extra projection nodes in the derivatives. Anyway, this is orthogonal to `sp_reverse`. The projection should not change the sparsity pattern of the Jacobian.

**Comment by jaeandersson** [comment]
I think it's just a typo:
```c++
      asens[d][0] = rank1(project(asens[d][0], sparsity()),
                          aseed[d][0], dep(1), dep(2));
```
should be
```c++
      asens[d][0] = rank1(project(asens[d][0], dep(0).sparsity()),
                          aseed[d][0], dep(1), dep(2));
```
I think
