### ISSUE TITLE
SQPmethod in IPOPT

### ISSUE THREAD

**Issue by jiangyntech** [casadi/casadi#2124]
Hi, 
I need some help. 
When I use SQP solver in casadi MATLAB to solve a simple convex QP problem, 
it can not get the right solution.

Problem is 
min 0.5 x^2
s.t. -2<= x<= -1

The code is 
`x=SX,sym('x',1);
f = 0.5*x*x;
qp = struct('x',x,'f',f);
cas = nlpsol('solver','sqpmethod',qp,struct('qpsol','qpoases'));
sol = cas('lbx',-2,'ubx',-1,'x0', -1.5);`

Whatever x0 cause sol.x = 0.
I just tried this problem in different version of casadi matlab as well as casadi python.
No one can get the right solution. 
Could anyone tell me how to fix this problem?

Thanks a lot.
Yuning Jiang

**Comment by jaeandersson** [comment]
The 'sqpmethod' class is experimental. If you want to use it, you need to be prepared to jump into the code, fix things yourself and submit pull requests.
