### ISSUE TITLE
CasADi codegen support for ISO C90

### ISSUE THREAD

**Issue by roversch** [casadi/casadi#2130]
In C90, you have to declare all variables at the beginning of a block (e.g. function).

The CasADi code generated files do not stick to this rule, giving compiler errors for older compilers (a client of ours wants to use Windows SDK 7.1, supported still by MATLAB R2016b).

For example:

```
./xxx.c(80) : error C2143: syntax error : missing ';' before 'type'
./xxx.c(81) : error C2065: 'a5' : undeclared identifier
./xxx.c(86) : error C2143: syntax error : missing ';' before 'type'
./xxx.c(87) : error C2065: 'a6' : undeclared identifier
./xxx.c(90) : error C2065: 'a6' : undeclared identifier
./xxx.c(91) : error C2143: syntax error : missing ';' before 'type'
```

**Comment by jaeandersson** [comment]
This should already be enforced, but maybe strictly. Codegen generally adhere to declaring variables in the outermost block. Can you give an example of something that fails?

**Comment by roversch** [comment]
For example, compiling the file in attachment [vde_pendulum.c](https://github.com/casadi/casadi/files/1481894/vde_pendulum.txt)

 with 

`gcc-7 -std=c90 -pedantic -Werror vde_pendulum.c`

(since I don't have this Windows SDK 7.1 compiler) I get

```
vde_pendulum.c: In function 'vde_pendulum':
vde_pendulum.c:18:16: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 #define real_t double
                ^
vde_pendulum.c:51:3: note: in expansion of macro 'real_t'
   real_t a1=arg[0] ? arg[0][1] : 0;
   ^~~~~~
...
...
```
and a lot of similar errors. The problem is that some calculations (in this case, on `real_t a_0`) are done before `real_t a_1` is declared.

To pass, I think the code should have a bunch of declarations
```c
real_t a_0, a_1, a_2, a_3, a_4, ... ;
```
at the top of the function.

**Comment by jaeandersson** [comment]
I see. This is how codegen already works in general, but I think SXFunction is an exception. Try for example:
```python
from casadi import *
x = MX.sym('x')
y = MX.sym('y')
Function('f',[x,y],[y*sin(x)]).generate()
```
which produces:
```c
...
/* f:(i0,i1)->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #2: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #3: @0 = (@0*@1) */
  w0 *= w1;
  /* #4: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}
...
```
In principle, we could refactor SXFunction so that it works the same way.

**Comment by roversch** [comment]
Great! I'll check if it's an option to switch to MX..

**Comment by jaeandersson** [comment]
Had a peak at the code and looks like the change for SXFunction was trivial: https://github.com/casadi/casadi/commit/3de7d3af60f9e854ce9a227518f2613a88b691b2

You should be able to cherry-pick this commit.

Not saying that this will make the code comply with C90 in general, but it should bring it closer.

**Comment by jgillis** [comment]
This is fixed now; and unittested: https://github.com/casadi/casadi/blob/develop/test/python/helpers.py#L525
