### ISSUE TITLE
Adding Gurobi to binaries

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2133]

**Comment by OscarVM** [comment]
Dear Joris.
I am working with casadi for my master thesis. I would like to use different solvers and i am interested to work with the interface from casadi to gurobi for MIQPs (and i don´t know if it would work also for MILPs). As i am starting to work with python and so, i am not very used to binary building, and as i am working at this time with Windows i have read that building them can be a little complicated. Is there any estimate when the Gurobi interface will be added to the binaries? If not what would be a good start for adding the interfaces to work with.
Thanks for the help.
Oscar V.

**Comment by jgillis** [comment]
3.4.0-rc1 has it..
