### ISSUE TITLE
Make sure CSparse derived methods are properly attributed

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2134]
Some routines in Sparsity(Internal) have implementations derived from CSparse. This should be pointed out more clearly in the code and proper copyright statements must be included. Likewise, most of the routines in casadi_qr.hpp and casadi_ldl.hpp are derived from code listed in the Tim Davis book and user guide respectively. This needs to be clarified and caution must be taken so that this code isn't copied to autogenerated code in breach of copyright restrictions.

**Comment by jgillis** [comment]
close?

**Comment by jaeandersson** [comment]
Done, spun #2158. Need to make sure we document this in the release notes.
