### ISSUE TITLE
RuntimeError: cannot evaluate since parameter variables are free 

### ISSUE THREAD

**Issue by samiit** [casadi/casadi#2150]
Hi,
When evaluating the numerical value of the Jacobian at the optimized solution, through this code

```
E = cs.Function('E', [optProb.nlp['x']], [cs.jacobian(optProb.nlp['g'], optProb.nlp['x'])])
### Jacobian evaluation
A = E(optProb.sol['x'])
```
I am getting the following error:

`RuntimeError: .../casadi/core/sx_function.cpp:69: Cannot evaluate "E:(i0[189])->(o0[77x189,252nz]) SXFunction" since variables [xp1, xp2, xp3, xp4, xp5, xp6, xp7, xp8, xp9, xp10, xp11] are free.`

When there was only one parameter (xp1), it worked but now with 11 parameters, it is giving this error.

I was wondering whether it is similar to the [old issue](https://sourceforge.net/p/casadi/discussion/1271244/thread/2967e204/) with parameters. Is there any plan to resolve it?

Thanks,
Sam

**Comment by jgillis** [comment]
Hi!

I'm not sure what your data-structures look like, but if I'm making an educated guess, you should be able to do:
```python
E = cs.Function('E', [optProb.nlp['x'],optProb.nlp['p']], [cs.jacobian(optProb.nlp['g'], optProb.nlp['x'])])
### Jacobian evaluation
A = E(optProb.sol['x'],numerical_values_for_your_parameters)
```

**Comment by samiit** [comment]
Thank you very much Joris. That solved it.

Sam
