### ISSUE TITLE
python nlpsolver stats inconsistent

### ISSUE THREAD

**Issue by schoelst** [casadi/casadi#2151]
Hi,

I am using CasADi's Python interface to compare a number of problem formulations and solvers (ipopt, qpoases, hpmpc) in terms of required iterations and computation time. A simple example of what I am doing is comparison of ipopt and the sqpmethod (with qpoases or hpmpc) in the `simple_nlp.py`, by pulling the stats through `solver.stats()` after the problem is solved.

The stats dict for ipopt contains `iter_count` and `return_status`, but these are not contained in the stats dict for the sqpmethod. Is it possible to obtain these two entries somehow?
The information is printed on the console, I know, but I would like to obtain it in an scriptable way so I can automate the evaluation process.

Thanks a lot for your help!

**Comment by jgillis** [comment]
`return_status` is present for `sqp_method` in at least 3.3.0.
I'm adding `iter_count` on develop now...
