### ISSUE TITLE
CMakeLists.txt not suited for add_subdirectory

### ISSUE THREAD

**Issue by FrankDrop** [casadi/casadi#2152]
I added casadi as a submodule in my project, and added it to my CMakeLists.txt by doing
add_subdirectory(casadi)

Then, I obtain the following error when running cmake on my project:

> CMake Error at casadi/CMakeLists.txt:66 (include):
> include could not find load file:
> language_support

I believe the problem is on line 66 of CMakeLists.txt in the root directory:
`set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)`

That is, CMAKE_MODULE_PATH points to '/mainproject/cmake', where it should point to '/mainproject/casadi/cmake' to find the file '/mainproject/casadi/cmake/language_support.cmake'.

This fixed my issue:
`set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)`

**Comment by jgillis** [comment]
Thanks for reporting!
