### ISSUE TITLE
unused arrays in C code

### ISSUE THREAD

**Issue by Zilleplus** [casadi/casadi#2157]
platform: Windows 10: Windows Subsystem For Linux
casadi version: casadi (3.2.2)
python version: 3.5.2

I noticed that the arrays that are required by the generated c-code of a function are not always used.
I put a simple example together below where and "sz_w" of size 3 is required but never used. 

**python code:**
```
import casadi as cd
def test_f(x):
    y= x[0]**2 + x[0]**3 + x[1]*2
    return y

x = cd.SX.sym('x',2,1)
f = cd.Function('test_function', [x], [cd.gradient(test_f(x),x)])
f.generate("test_grad.c")
```

**function:**
```
int test_function(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][0] : 0;
  real_t a1=(a0+a0);
  real_t a2=sq(a0);
  a1=(a1+a2);
  a2=(a0+a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][0]=a1;
  a1=2.;
  if (res[0]!=0) res[0][1]=a1;
  return 0;
}
```
**function with sizes :**
```
int test_function_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 3;
  return 0;
}
```

**Comment by jaeandersson** [comment]
This has been asked before. It's not a bug. The work vector sizes are the same for code-gen, non-codegen CasADi for simpler coding. In this case, the work vector is not needed in codegen (a0, a1, a2 are used instead).
