### ISSUE TITLE
Create Rootfinder instances using expressions

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2165]
Unlike `Integrator`, `Conic` and `Nlpsol` instances, `Rootfinder` instances are still defined by passing a Function instance in the constructor. The class would be much easier to use if we simply used the formulation:

```
  g(x, p) = 0
  y = h(x, p)
```
Inputs: `x0` and `p`.
Outputs: `x` and `y`.

Instances would be created using the syntax:
```python
solver = rootfinder('solver', 'newton', dict(x=.., g=...))
```

This isn't quite as flexible as the current formulation, but I think the loss is minimal. This way, the function evaluation will go through the OracleFunction helper functions which means better debugging, more flexibility and timing statistics.

**Comment by jaeandersson** [comment]
If we go ahead with it, I'd add the new syntax in CasADi 3.4 with soft deprecation of the old syntax. Then refector the class for 3.5.

**Comment by jgillis** [comment]
i like that! but is it even natural to have y? We don't have y for integrators or nlpsol

**Comment by jaeandersson** [comment]
Good point. `y` isn't really needed. You can easily chain it with your own output function.

**Comment by jaeandersson** [comment]
OK, going ahead with:
```
  g(x, p) = 0
```
Rootfinder inputs: x0 and p, output x

Interestingly, a rootfinding problem is then a special case of a nonlinear program.

**Comment by jaeandersson** [comment]
Usage example, new syntax:
```python
from casadi import *
x = SX.sym('x')
p = SX.sym('p')
myarctan = rootfinder('myarctan', 'newton', dict(x=x, p=p, g=tan(x)-p))
print(myarctan(0, 0.2)) # 0.197396
print(atan(0.2)) # 0.19739555984988078
```

**Comment by jaeandersson** [comment]
The new syntax only affects the struct passed to `casadi::rootfinder`, NOT the input/output scheme of Rootfinder. The input scheme becomes [x,p], output scheme [g]. Not [x0,p] and [x], which would be the analog to Nlpsol.
