### ISSUE TITLE
Cryptic error if wrong operation is executed on SX variables

### ISSUE THREAD

**Issue by Zilleplus** [casadi/casadi#2168]
Casadi 3.2.2

I searched the issue's and couldn't find one with this mentioned, so here it is:
Take the example: 
```
import casadi as cd
test = cd.SX.sym('test', 3 , 1)
cd.np.linalg.norm(test)
```

This will result in the error:
'SX' object has no attribute 'full'

This is somewhat cryptic, maybe something like "linear algebra operations only supported on MX" would be better.

**Comment by jaeandersson** [comment]
`numpy.linalg.norm` is a numpy function. It's hard for us to control how they will behave if you throw CasADi objects on them. In this case, you should use the corresponding CasADi function: `cd.norm_1`, `cd.norm_2`, `cd.norm_fro` or `cd.norm_inf`.

**Comment by Zilleplus** [comment]
Ok thanks !

Why not add this to the manual? That specific error message is quite common with these numpy functions, its very frustrating at times.

**Comment by jaeandersson** [comment]
Do you have a suggestion on where to add this in the manual?

**Comment by Zilleplus** [comment]
The subsection on 3.6 Arithmetic operations describes a few basic operations.(which you can also do with the casadi.np submodule) I wrongfully assumed after reading this that the submodule casadi.np was a numpy interface on these functions. (which i found an excellent feature)

So maybe put a warning at the end of the subsection that using those functions with SX is dangerous. And should be avoided. Also mention that error(maybe even with the example), if someone has that error he/she can search the pdf for it.

**Comment by jaeandersson** [comment]
Sure, we can do that.

**Comment by jaeandersson** [comment]
Ah, saw that @jgillis had taken care of it.
