### ISSUE TITLE
ipython notebook out of date

### ISSUE THREAD

**Issue by jgoppert** [casadi/casadi#2170]
```python
from casadi.tools import *
```
is now

```python
from casadi.tools.graph.graph import *  # for dotdraw
```

Also print from python2 is used, it should be updated to use the print_function

```python
from __future__ import print_function

# use this
print(x)

#instead of this
print x
```

undefined reference to file

**Comment by jgoppert** [comment]
Lowres images also coming out of dotdraw, better results with slight command change:

![image](https://user-images.githubusercontent.com/473772/35830044-de404466-0a92-11e8-9da9-2888884b3ea1.png)

**Comment by jgillis** [comment]
Hi!

`from casadi.tools import *` should bring `dotdraw`into the current statement if `import pydot` succeeds.
I'm a bit puzzled by your statement that you need `from casadi.tools.graph.graph import *`..

Other suggestions implemented.

**Comment by jgoppert** [comment]
Thanks! Not sure about the import issue,  might have been something weird in my environment.
