### ISSUE TITLE
Problem with installing HSL solver in ubuntu 16.04

### ISSUE THREAD

**Issue by Flancis** [casadi/casadi#2172]
Hi,

I am installing the HSL solver from source, following the instructions below. [https://github.com/casadi/casadi/wiki/Obtaining-HSL](url)

However, whenever I came to the seventh step `make`, it gives the following error.
make: *** No targets specified and no makefile found.  Stop.

Any ideas why?

Thanks in advance.

**Comment by jgillis** [comment]
It's the `configure` step that should generate a Makefile. Make sure step 6 passes without errors first.

**Comment by Flancis** [comment]
Hi,

Like you said, in the `configure` step it gives the following error.

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgfortran... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking for nagfor... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking whether the Fortran compiler works... no
configure: error: in `/home/u2/coinhsl-2014.01.10':
configure: error: Fortran compiler cannot create executables
See `config.log' for more details

In the `config.log` there are the following.

This file contains any messages produced by compilers while

running configure, to aid debugging if configure makes a mistake.



It was created by coinhsl configure 2014.01.10, which was

generated by GNU Autoconf 2.69.  Invocation command line was



  $ ./configure --prefix=/home/u2/Software/HSL LIBS=-llapack --with-blas=-L/usr/lib -lblas CXXFLAGS=-g -O2 -fopenmp FCFLAGS=-g -O2 -fopenmp CFLAGS=-g -O2 -fopenmp



## --------- ##

## Platform. ##

## --------- ##



hostname = u2-VirtualBox

uname -m = x86_64

uname -r = 4.10.0-28-generic

uname -s = Linux

uname -v = #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017



/usr/bin/uname -p = unknown

/bin/uname -X     = unknown



/bin/arch              = unknown

/usr/bin/arch -k       = unknown

/usr/convex/getsysinfo = unknown

/usr/bin/hostinfo      = unknown

/bin/machine           = unknown

/usr/bin/oslevel       = unknown

/bin/universe          = unknown



PATH: /home/u2/bin

PATH: /home/u2/.local/bin

PATH: /usr/local/sbin

PATH: /usr/local/bin

PATH: /usr/sbin

PATH: /usr/bin

PATH: /sbin

PATH: /bin

PATH: /usr/games

PATH: /usr/local/games

PATH: /snap/bin





## ----------- ##

## Core tests. ##

## ----------- ##



configure:2449: checking for a BSD-compatible install

configure:2517: result: /usr/bin/install -c

configure:2528: checking whether build environment is sane

configure:2578: result: yes

configure:2719: checking for a thread-safe mkdir -p

configure:2758: result: /bin/mkdir -p

configure:2771: checking for gawk

configure:2801: result: no

configure:2771: checking for mawk

configure:2787: found /usr/bin/mawk

configure:2798: result: mawk

configure:2809: checking whether make sets $(MAKE)

configure:2831: result: yes

configure:2966: checking for gfortran

configure:2996: result: no

configure:2966: checking for g95

configure:2996: result: no

configure:2966: checking for xlf95

configure:2996: result: no

configure:2966: checking for f95

configure:2996: result: no

configure:2966: checking for fort

configure:2996: result: no

configure:2966: checking for ifort

configure:2996: result: no

configure:2966: checking for ifc

configure:2996: result: no

configure:2966: checking for efc

configure:2996: result: no

configure:2966: checking for pgfortran

configure:2996: result: no

configure:2966: checking for pgf95

configure:2996: result: no

configure:2966: checking for lf95

configure:2996: result: no

configure:2966: checking for ftn

configure:2996: result: no

configure:2966: checking for nagfor

configure:2996: result: no

configure:2966: checking for xlf90

configure:2996: result: no

configure:2966: checking for f90

configure:2996: result: no

configure:2966: checking for pgf90

configure:2996: result: no

configure:2966: checking for pghpf

configure:2996: result: no

configure:2966: checking for epcf90

configure:2996: result: no

configure:2966: checking for g77

configure:2996: result: no

configure:2966: checking for xlf

configure:2996: result: no

configure:2966: checking for f77

configure:2996: result: no

configure:2966: checking for frt

configure:2996: result: no

configure:2966: checking for pgf77

configure:2996: result: no

configure:2966: checking for cf77

configure:2996: result: no

configure:2966: checking for fort77

configure:2996: result: no

configure:2966: checking for fl32

configure:2996: result: no

configure:2966: checking for af77

configure:2996: result: no

configure:3019: checking for Fortran compiler version

configure:3028:  --version >&5

./configure: line 3030: --version: command not found

configure:3039: $? = 127

configure:3028:  -v >&5

./configure: line 3030: -v: command not found

configure:3039: $? = 127

configure:3028:  -V >&5

./configure: line 3030: -V: command not found

configure:3039: $? = 127

configure:3028:  -qversion >&5

./configure: line 3030: -qversion: command not found

configure:3039: $? = 127

configure:3054: checking whether the Fortran compiler works

configure:3076:  -g -O2 -fopenmp   conftest.f -llapack >&5

./configure: line 3078: -g: command not found

configure:3080: $? = 127

configure:3118: result: no

configure: failed program was:

|       program main

| 

|       end

configure:3123: error: in `/home/u2/coinhsl-2014.01.10':

configure:3125: error: Fortran compiler cannot create executables

See `config.log' for more details



## ---------------- ##

## Cache variables. ##

## ---------------- ##



ac_cv_env_CC_set=

ac_cv_env_CC_value=

ac_cv_env_CFLAGS_set=set

ac_cv_env_CFLAGS_value='-g -O2 -fopenmp'

ac_cv_env_CPPFLAGS_set=

ac_cv_env_CPPFLAGS_value=

ac_cv_env_CPP_set=

ac_cv_env_CPP_value=

ac_cv_env_F77_set=

ac_cv_env_F77_value=

ac_cv_env_FCFLAGS_set=set

ac_cv_env_FCFLAGS_value='-g -O2 -fopenmp'

ac_cv_env_FC_set=

ac_cv_env_FC_value=

ac_cv_env_FFLAGS_set=

ac_cv_env_FFLAGS_value=

ac_cv_env_LDFLAGS_set=

ac_cv_env_LDFLAGS_value=

ac_cv_env_LIBS_set=set

ac_cv_env_LIBS_value=-llapack

ac_cv_env_build_alias_set=

ac_cv_env_build_alias_value=

ac_cv_env_host_alias_set=

ac_cv_env_host_alias_value=

ac_cv_env_target_alias_set=

ac_cv_env_target_alias_value=

ac_cv_path_install='/usr/bin/install -c'

ac_cv_path_mkdir=/bin/mkdir

ac_cv_prog_AWK=mawk

ac_cv_prog_make_make_set=yes



## ----------------- ##

## Output variables. ##

## ----------------- ##



ACLOCAL='${SHELL} /home/u2/coinhsl-2014.01.10/missing --run aclocal-1.11'

AMDEPBACKSLASH=''

AMDEP_FALSE=''

AMDEP_TRUE=''

AMTAR='$${TAR-tar}'

AR=''

AUTOCONF='${SHELL} /home/u2/coinhsl-2014.01.10/missing --run autoconf'

AUTOHEADER='${SHELL} /home/u2/coinhsl-2014.01.10/missing --run autoheader'

AUTOMAKE='${SHELL} /home/u2/coinhsl-2014.01.10/missing --run automake-1.11'

AWK='mawk'

BLAS_LIBS=''

CC=''

CCDEPMODE=''

CFLAGS='-g -O2 -fopenmp'

CPP=''

CPPFLAGS=''

CYGPATH_W='echo'

DEFS=''

DEPDIR=''

DLLTOOL=''

DSYMUTIL=''

DUMPBIN=''

ECHO_C=''

ECHO_N='-n'

ECHO_T=''

EGREP=''

EXEEXT=''

F77=''

FC=''

FCFLAGS='-g -O2 -fopenmp'

FFLAGS=''

FGREP=''

FLIBS=''

GREP=''

HAVE_MA27_FALSE=''

HAVE_MA27_TRUE=''

HAVE_MA28_FALSE=''

HAVE_MA28_TRUE=''

HAVE_MA57_FALSE=''

HAVE_MA57_TRUE=''

HAVE_MA77_FALSE=''

HAVE_MA77_TRUE=''

HAVE_MA86_FALSE=''

HAVE_MA86_TRUE=''

HAVE_MA97_FALSE=''

HAVE_MA97_TRUE=''

HAVE_MC19_FALSE=''

HAVE_MC19_TRUE=''

HAVE_MC68_FALSE=''

HAVE_MC68_TRUE=''

HAVE_METIS_FALSE=''

HAVE_METIS_TRUE=''

INSTALL_DATA='${INSTALL} -m 644'

INSTALL_PROGRAM='${INSTALL}'

INSTALL_SCRIPT='${INSTALL}'

INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'

LD=''

LDFLAGS=''

LIBOBJS=''

LIBS='-llapack'

LIBTOOL=''

LIPO=''

LN_S=''

LTLIBOBJS=''

MAKEINFO='${SHELL} /home/u2/coinhsl-2014.01.10/missing --run makeinfo'

MANIFEST_TOOL=''

MKDIR_P='/bin/mkdir -p'

NM=''

NMEDIT=''

OBJDUMP=''

OBJEXT=''

OTOOL64=''

OTOOL=''

PACKAGE='coinhsl'

PACKAGE_BUGREPORT='hsl@stfc.ac.uk'

PACKAGE_NAME='coinhsl'

PACKAGE_STRING='coinhsl 2014.01.10'

PACKAGE_TARNAME='coinhsl'

PACKAGE_URL=''

PACKAGE_VERSION='2014.01.10'

PATH_SEPARATOR=':'

RANLIB=''

SED=''

SET_MAKE=''

SHELL='/bin/bash'

STRIP=''

TARGET_DLL_FALSE=''

TARGET_DLL_TRUE=''

VERSION='2014.01.10'

ac_ct_AR=''

ac_ct_CC=''

ac_ct_DUMPBIN=''

ac_ct_F77=''

ac_ct_FC=''

am__EXEEXT_FALSE=''

am__EXEEXT_TRUE=''

am__fastdepCC_FALSE=''

am__fastdepCC_TRUE=''

am__include=''

am__isrc=''

am__leading_dot='.'

am__nodep=''

am__quote=''

am__tar='$${TAR-tar} chof - "$$tardir"'

am__untar='$${TAR-tar} xf -'

bindir='${exec_prefix}/bin'

build=''

build_alias=''

build_cpu=''

build_os=''

build_vendor=''

datadir='${datarootdir}'

datarootdir='${prefix}/share'

docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'

dvidir='${docdir}'

exec_prefix='NONE'

host=''

host_alias=''

host_cpu=''

host_os=''

host_vendor=''

htmldir='${docdir}'

includedir='${prefix}/include'

infodir='${datarootdir}/info'

install_sh='${SHELL} /home/u2/coinhsl-2014.01.10/install-sh'

libdir='${exec_prefix}/lib'

libexecdir='${exec_prefix}/libexec'

localedir='${datarootdir}/locale'

localstatedir='${prefix}/var'

mandir='${datarootdir}/man'

mkdir_p='/bin/mkdir -p'

oldincludedir='/usr/include'

pdfdir='${docdir}'

prefix='/home/u2/Software/HSL'

program_transform_name='s,x,x,'

psdir='${docdir}'

sbindir='${exec_prefix}/sbin'

sharedstatedir='${prefix}/com'

sysconfdir='${prefix}/etc'

target_alias=''



## ----------- ##

## confdefs.h. ##

## ----------- ##



/* confdefs.h */

#define PACKAGE_NAME "coinhsl"

#define PACKAGE_TARNAME "coinhsl"

#define PACKAGE_VERSION "2014.01.10"

#define PACKAGE_STRING "coinhsl 2014.01.10"

#define PACKAGE_BUGREPORT "hsl@stfc.ac.uk"

#define PACKAGE_URL ""

#define PACKAGE "coinhsl"

#define VERSION "2014.01.10"



configure: exit 77

**Comment by Flancis** [comment]
It seems like I don't have the gfortran compiler installed previously. After installing it, it gives some new errors.

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gfortran... gfortran
checking whether the Fortran compiler works... no
configure: error: in `/home/u2/coinhsl-2014.01.10':
configure: error: Fortran compiler cannot create executables
See `config.log' for more details

**Comment by jgillis** [comment]
The issue tracker is no goog place to discuss this
