### ISSUE TITLE
DaeBuilder.add_w() is missing?

### ISSUE THREAD

**Issue by mkatliar** [casadi/casadi#2175]
Documentation for `DaeBuilder` class states that it is possible to define intermediate variables:
```
’w’ Local variables w. Calculated from time and time dependent variables. They may
also depend, acyclically, on other w.
```

The corresponding function `DaeBuilder.add_w()` is missing, although the property `DaeBuilder.wdef` exists.

**Comment by jaeandersson** [comment]
Yes, it probably hasn't been implemented. I guess there's some confusion with d too

**Comment by jaeandersson** [comment]
The dependent variables are now called `v`, which combines the old `w` and the old `d`.
