### ISSUE TITLE
Dependent parameters d in DaeBuilder can depend on state

### ISSUE THREAD

**Issue by mkatliar** [casadi/casadi#2176]
In chapter 7 of CasADi manual it is stated:
```
’d’ Dependent parameters d, depends only on p and c and, acyclically, on other d
```

However, in [this example](https://github.com/casadi/casadi/blob/master/experimental/sailboat.py) dependent variable which depends on the state is created.

Also, the following code seems to work:

```python
import casadi as cs

b = cs.DaeBuilder()
x = b.add_x('x')
p = b.add_p('p')
d = b.add_d('d', p + x)
b.add_ode('xdot', d)
b.disp(True)

b.eliminate_d()
b.disp(True)

f = b.create('f', ['x', 'p'], ['ode'])
print(f, f(0, 0))
```

Should the documentation be corrected?

**Comment by jaeandersson** [comment]
Yes, d can depend on the state too

**Comment by jaeandersson** [comment]
Hmm, or maybe I take that back. It might be intended to be constant in time

**Comment by jaeandersson** [comment]
This has been refactored now. There is a single dependent variable type `v` now, which can depend on state or anything else (as well as on other `v`, acyclically).
