### ISSUE TITLE
WORHP interface within MATLAB

### ISSUE THREAD

**Issue by mamaliabd** [casadi/casadi#2181]
Dear all,

I would appreciate it if you could have a look at this error.
`CasADi - 2018-02-14 15:43:07 WARNING(".../casadi/core/plugin_interface.hpp:292: Assertion "handle!=0" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_nlpsol_worhp.so': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/home/mohammad/casadi-matlabR2014b-v3.3.0' :
    Error code: /home/mohammad/MATLAB/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libworhp.so)
  Tried '' :
    Error code: /home/mohammad/MATLAB/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libworhp.so)
  Tried '.' :
    Error code: ./libcasadi_nlpsol_worhp.so: cannot open shared object file: No such file or directory") [.../casadi/core/plugin_interface.hpp:148]
Error using casadi.nlpsol (line 787)
.../casadi/core/plugin_interface.hpp:387: Plugin 'worhp' is not found.`

I used the WORHP licence and its deb installation and also changed the compiler to gcc 4.8.
I know this issue has been asked by Mario Zanon before! but since I didn't see any response in the google group I am asking it here!

I am using Ubuntu and Matlab 2017a and casadi 3.3.
Thanks a lot in advance
Cheers,
Mohammad

**Comment by jaeandersson** [comment]
Let's use the google group and not start a parallel discussion.
