### ISSUE TITLE
Improvement proposal: combining purely symbolic expressions into a purely symbolic struct

### ISSUE THREAD

**Issue by mkotlyar** [casadi/casadi#2187]
This proposal is based in these threads: 
https://groups.google.com/forum/#!topic/casadi-users/y_56uoO8bMw
https://groups.google.com/forum/#!searchin/casadi-users/struct_symMX%7Csort:date/casadi-users/jxxNf4wMtSU/RzyRxzqoBQAJ

# Introduction
Suppose we have an optimization problem, where optimization variables X, Y, Z are matrices:

```python
import casadi as cs

def solve_optimization_problem(X, Y, Z, f):
    """
    X, Y, Z are optimization variables of any shape; 
    f is a symbolic expression depending on X, Y, Z.

    @return returns optimal values of X, Y, Z in a dictionary.
    """

    # In order to create a single optimization variable, 
    # we vectorize and concatenate all optimization variables.
    # If an optimization variable is added, this line needs to be modified:
    nlp = {'x': cs.vertcat(cs.vec(X), cs.vec(Y), cs.vec(Z)), ...}
    solver = cs.nlpsol('solver', 'ipopt', nlp)

    solution = solver(x0=..., )
    x_opt = solution['x']

    # At this point, we want to extract parts of the solution corresponding to X, Y, Z.
    # We need to cycle through all variables, extract corresponding part
    # from the solution vector and reshape it accordingly.
    # If an optimization variable is added, extra 2 lines need to be added here:
    i = 0
    sol_X = cs.reshape(x_opt[i : i + X.numel()], X.shape)
    i = i + X.numel()
    sol_Y = cs.reshape(x_opt[i : i + Y.numel()], Y.shape)
    i = i + Y.numel()
    sol_Z = cs.reshape(x_opt[i : i + Z.numel()], Z.shape)

    # Here we combine all values in a dictionary, one entry per variable.
    # Again, if an optimization variable is added, 
    # the following line should be modified too:
    return {'X': sol_X, 'Y': sol_Y, 'Z': sol_Z}
```

This works, but is ugly, because there are 3 places in the code which need to be changed if the number of optimization variables changes. One could write a function which packs/unpacks variables in/from a vector, but there must be an extra object which keeps track of variables' order etc.

I like the way it can be implemented with struct_symMX:

```python
import casadi.tools as ct

w = ct.struct_symMX([
    ct.entry('X', shape=(XM, XN)),
    ....
])

# ....

solution = w(solver(...)['x'])
sol_X = solution['X']
# ....
```

There are two concerns about this approach though:
1. If X,Y,Z are already existing symbolic variables, I see no way of combining them into a symbolic structure. This is closely related to this thread: https://groups.google.com/forum/#!searchin/casadi-users/struct_symMX|sort:date/casadi-users/jxxNf4wMtSU/RzyRxzqoBQAJ
2. In the thread above, Joel said: 
"But why use struct_symSX in the first place? This is a legacy feature in CasADi. struct_symSX/struct_symMX are Python-specific abstractions on top of SX/MX, added at a time when it wasn't possible to do e.g."
And he recommends the vertcat() approach, which has the issues described above.

# The problem
What is a nice way to combine multiple symbolic variables so that 
1. Such combination can be used as a single pure symbolic variable;
2. A vector of corresponding size can be split into parts according to the sparsity/shape of the variables.

# Proposed solution
The problem can be solved by modifying the `casadi.tools.struct_MX` class such that if all its elements are purely symbolic then the `.cat` expression is purely symbolic too. The necessary changes are minimal and are presented here: https://github.com/casadi/casadi/compare/master...mkotlyar:dev_misha . With the proposed changes, the following code will work:

```python
import casadi as cs, casadi.tools as ct

def solve_optimization_problem(X, Y, Z, f):

    # Multiple symbolic variables are combined in a structure,
    # which is purely symbolic too. If an optimization variable is added, 
    # this is the only place in the code which needs to be modified:
    w = ct.struct_MX([
        ct.entry('X', expr=X),
        ct.entry('Y', expr=Y),
        ct.entry('Z', expr=Z)
    ])

    # No need for vertcat(...)
    nlp = {'x': w, ...}
    solver = cs.nlpsol('solver', 'ipopt', nlp)

    solution = solver(x0=..., )

    # Here the optimal solution vector is converted to a dictionary-like object.
    # No need to write code to extract parts from the solution vector.
    x_opt = w(solution['x'])

    # The x_opt value is already a dictionary
    return x_opt
```

**Comment by jgillis** [comment]
The `struct*` things are indeed legacy (superseeded by #1388 ). I'd be happy to merge in patches for `struct` though.
