### ISSUE TITLE
Map parallelism using std::thread

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2191]
OpenMP has issues.

**Comment by jaeandersson** [comment]
Yes. Looks simple enough. OpenMP can continue to exist as an alternative.

**Comment by jgillis** [comment]
efd06ed16028903

**Comment by jaeandersson** [comment]
Does it work well?

**Comment by jgillis** [comment]
Seems to work nicely on linux and mac. Fighting mingw now..

**Comment by jaeandersson** [comment]
awesome

**Comment by jgillis** [comment]
We'll have parallelism-enabled binaries again for 3.4
