### ISSUE TITLE
Support for Root finder in Integrator

### ISSUE THREAD

**Issue by jgoppert** [casadi/casadi#2201]
If you try to inegrate something like this, it is very slow due to not using root finding within the sundials interface.

```python
v = ca.SX.sym('v')
z = ca.SX.sym('z')
X = ca.vertcat(z, v)
rhs_freefall = ca.vertcat(v, -9.8)
rhs_ground = ca.vertcat(v, -100*z)
f = ca.if_else(z > 0, rhs_freefall, rhs_ground)
```

It would be nice to have the integrator handle root finding and state reset like this example:
https://github.com/olivierverdier/python-sundials/blob/master/sundials/test_cv_ball.py

It would be very useful for hybrid systems like the bouncing ball.

![screenshot from 2018-03-01 17-14-28](https://user-images.githubusercontent.com/473772/36872695-19df68a0-1d74-11e8-83c2-eb99645eb159.png)

**Comment by jaeandersson** [comment]
This is unlikely to happen in any reasonable time frame. The main advantage of using the integrators in CasADi is support for sensitivity analysis and it's very hard to get that working together with a feature like this. Then there is also the question on how to identify the zero-crossing functions and pass them on to sundials, which is very challenging.

**Comment by jgoppert** [comment]
OK, thanks for considering. Maybe I'll pursue it further if I find time.

**Comment by jaeandersson** [comment]
OK. Make sure that you coordinate it with us before if you plan to code up something and make a pull request. We're very restrictive in accepting non-trivial changes to the core.

**Comment by jaeandersson** [comment]
Note: https://github.com/casadi/casadi/wiki/contribute

**Comment by mvanlobensels** [comment]
@jaeandersson Hi Joel, is there any proper way to implement hybrid systems in CasADi based on switching conditions?
