### ISSUE TITLE
Interpolant segfaults for solver "bspline"

### ISSUE THREAD

**Issue by schoelst** [casadi/casadi#2202]
Hi all,

when computing a bspline interpolation for the minimum example below, I get a segfault (I am using CasADi 3.2.3)

`
std::vector<double> param = {0.0, 1.0};
std::vector<double> vals = {42.0, 0.42};
casadi::interpolant("smooth_f", "bspline", {param}, vals);
`

`linear` works fine however.  - It is not a problem for my use case, but I found it while debugging..

Cheers,

Tobi

**Comment by jgillis** [comment]
Thanks for reporting!
In fact this particular bug was already adressed in develop branch (and new release will come out very soon).
