### ISSUE TITLE
Segfault in core

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2204]
```python
from casadi import *
x=MX.sym('x');
y=MX.sym('y');
z = x+y
z.name()
```

**Comment by jgillis** [comment]
https://groups.google.com/forum/#!topic/casadi-users/Ylwie97hz6o

**Comment by jgillis** [comment]
Taking all blame here. Smoke test got accidentally committed.

**Comment by jaeandersson** [comment]
Heh. that was a textbook segfault!
