### ISSUE TITLE
Logic Expression Equality

### ISSUE THREAD

**Issue by jgoppert** [casadi/casadi#2208]
I am building a function where there are many logical expressions scattered throughout a  modelica model, some which are logically equivalent. I would love to create a dictionary of these expressions, so I can share common expressions, for instance:

```python
x = ca.SX.sym('x')
c_0 = ca.SX.sym('c_0')
condition_dict = {x < 0: c_0}
​
new_expr = x < 0
if new_expr not in condition_dict.keys():
    print('not found, creating new symbol')
    condition_dict[new_expr] = ca.SX.sym('c_1')
symbol = condition_dict[new_expr]
symbol
```
```bash
not found, creating new symbol
SX(c_1)
```

What would be required to support this type of logical expression equality? Is there an easy way to grab the elements and see if they are exactly equal for now? Or is there a way to get the hash to work with the dictionary lookup?

**Comment by jgoppert** [comment]
Talking through this, I found a hack for myself for now, but it would be nice if it worked out of the box. I am just testing string equality, which should work in my case.

```python
x = ca.SX.sym('x')
c_0 = ca.SX.sym('c_0')
orig_expr = x < 0
condition_dict = {str(orig_expr): c_0}
str_to_expr = {c_0: x < 0}
​
def get_condition(new_expr):
    if str(new_expr) not in condition_dict.keys():
        print('not found, creating new symbol')
        new_sym = ca.SX.sym('c_1')
        condition_dict[str(new_expr)] = new_sym
        str_to_expr[new_sym] = new_expr
    return condition_dict[str(new_expr)]
​
print(get_condition(x<0))
print(get_condition(x<1))
```
```bash
c_0
not found, creating new symbol
c_1
```

**Comment by jaeandersson** [comment]
This sounds like a special case of common subexpression elimination. Comparing the strings can go wrong - not all information is contained in the printout, at least not in the general case (SX might work). Symbolic primitives can also have duplicate names. There is the function `is_equal`, but it's recursive so it's not efficient for deep trees.

**Comment by jgoppert** [comment]
I tried is_equal out, it seems to work only for symbols and not expressions?

```python
for l, r in [(x, x), (-x, -x), (x < 0, x < 0)]:
    print('{:5s}\t==\t{:5s}\t{:s}'.format(str(l), str(r), str(ca.is_equal(l, r))))
x    	==	x    	True
(-x) 	==	(-x) 	False
(x<0)	==	(x<0)	False
```

**Comment by jaeandersson** [comment]
It's for expressions too, you have to specify depth as the third argument. But it's recursive.

**Comment by jgoppert** [comment]
Thanks, that works.
