### ISSUE TITLE
casadi code generator options not in user guide

### ISSUE THREAD

**Issue by Zilleplus** [casadi/casadi#2224]
The options for the code generator are not in the user guide, i listed them [here](https://github.com/kul-forbes/nmpc-codegen/blob/master/src_matlab/%2Bnmpccodegen/%2Bcontroller/%40Casadi_code_generator/code_generator_options.md) for the last 3 minor versions:

I think this should be in the user guide in chapter 5. I can add them into the user guide myself and make a pull request.

**Comment by jaeandersson** [comment]
Sure, if you want to do that, go ahead.

**Comment by Zilleplus** [comment]
Just added them, pull request is ready.

**Comment by jaeandersson** [comment]
I've committed a table of options to the `develop` branch. We don't make tables for different CasADi versions like that - the user guide is versioned the same way as the rest of CasADi.
