### ISSUE TITLE
casadi object has no attribute 'daeIn'

### ISSUE THREAD

**Issue by pablocordova** [casadi/casadi#2226]
Hi, I'm checking a project that uses casadi, but It gives me error:
```
import casadi

....
model = casadi.Function(casadi.daeIn(x=x,p=p)
....
```

> AttributeError: 'module' object has no attribute 'daeIn'

How is that possible?, I searched if `daeIn` was deprecated but I didn't find.
I tried with casadi: 3.4.0, 3.3.0 and 3.2.0
python: 2.7
in a virtual environment.

**Comment by jgillis** [comment]
IO schemes like `daeIn, integratorIn, nlpIn, etc..` have been gone since at least 3.0.0.
For a recent reference implementation for DAE, you may look at the following example:
https://github.com/casadi/casadi/blob/master/docs/examples/python/dae_single_shooting.py#L67-L69

**Comment by nog642** [comment]
This page: https://github.com/casadi/casadi/wiki/Changes-v2.4.0-to-v3.0.0

makes no mention of this change. I think the documentation should be fixed to explain the change, and how to migrate code.
