### ISSUE TITLE
Uniform return status for NLP/conic solvers 

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2228]
837ed93925e7e06

**Comment by jaeandersson** [comment]
The evaluation has an `int` return value - why is this not being used? E.g. `int QpoasesInterface::eval(..)` would return 0 even for an unsuccessful return, but then set some internal QpoasesMemory::success state.

The behavior I'd expect would be for QpoasesInterface::eval to return 0 upon successful return or 1 upon fatal error.

**Comment by jaeandersson** [comment]
Potentially, positive and negative return flags could be used for fatal and non-fatal errors, respectively.
