### ISSUE TITLE
Solution Status from Ipopt

### ISSUE THREAD

**Issue by acauligi** [casadi/casadi#2235]
How would the user be able to determine if an optimal solution was found simply by checking the output of the nlpsol() function?

For example, the Ipopt solver outputs a print statement to the screen reporting the problem status, but there is no key/value pair in the output dictionary that sets a status flag for that problem.

**Comment by jgillis** [comment]
There is `solver.stats()` which describes the return status, and (since 3.4.1) a boolean `success` that determines if the solve was succesful.
