### ISSUE TITLE
find() says: Notify the CasADi developers.

### ISSUE THREAD

**Issue by deego** [casadi/casadi#2242]
This is in octave 4.2.2 with casadi 3.4.0:

Octave__17:00:02_0015776_6> a = MX.sym('a', 1,20); b = find(a)
error: casadiMEX: .../casadi/core/casadi_find.cpp:33: Assertion "x.is_column()" failed:
Notify the CasADi developers.
error: called from
    find at line 773 column 27

**Comment by jgillis** [comment]
Thanks for reporting. Should be fixed now.
