### ISSUE TITLE
Minor: Octave: @numel, @size, etc. incorrectly return 1 when inside cellfun: 

### ISSUE THREAD

**Issue by deego** [casadi/casadi#2253]
Minor: `@numel`, `@size`, etc. incorrectly return 1 when inside cellfun: 

This is a a frequent source of bugs for me. 

`@numel`, `@size`, etc. do not work properly on casadi objects when these functions are applied as part of cellfun.

Octave__16:28:06_0021905_53> p = SX.sym('p', 2,3)
Octave__16:29:46_0021905_54> nums = cellfun(`@numel`, {p,p}) => [1 1]

This was supposed to be [6 6].

Let's try to work around by defining an anonymous function:

Octave__16:30:13_0021905_55> nums = cellfun(@(x) numel(x), {p,p})
nums =
   1   1

Still no luck!  That's probably because octave tries to be smart and converts @(x) numel(x) back into `@numel`.

We finally have luck this way:

Octave__16:31:47_0021905_56> nums = cellfun(@(x) 0+ numel(x), {p,p})
nums =
   6   6

or, of course, we could use (horror!) the expensive loops to obtain sizes of {p,p}.  

So, cellfun is not easy to use for casadi objects and is a frequent source of hard-to-trace bugs for me. 

It's probably something about "registering" casadi's `@numel`, `@size`, etc. with cellfun. 

----
For completeness, here's a similar situation with size:

Octave__16:34:18_0021905_57> nums = cellfun(`@size`, {p,p}, 'unif', 0)
nums = 
{
  [1,1] =
     1   1
  [1,2] =
     1   1
}

We expected each size to be [2 3] instead of [1 1]. This is finally seen when we do this:

Octave__16:34:58_0021905_59> nums = cellfun(@(x) 0+size(x), {p,p}, 'unif', 0)
nums = 
{
  [1,1] =
     2   3
  [1,2] =
     2   3
}

**Comment by jgillis** [comment]
I can replicate this in octave 4.2.1. Weird behaviour..

**Comment by jgillis** [comment]
Could debug octave's `octave-value/ov-classdef.cc` numel method..

**Comment by jgillis** [comment]
couldn't reproduce with Matlab. My guess its a bug/unimplented feature of octave classdef.

**Comment by jgillis** [comment]
Could you please take this issue with octave devs? There's nothing we can do about this I'm afraid.

```
classdef Foo

methods
  function r=size(self)
    r = [2 3];
  end

  function r=numel(self)
    r = 6;
  end
end
end
```

```
numel(Foo) % 6
cellfun('numel',{Foo Foo}) % [1 1]
```

I think the `classdef.cc` needs some love..
You can refer to https://savannah.gnu.org/bugs/?46571, which is similar, and who's patch perhaps would have already fixed it if the added numel were `virtual`.

**Comment by deego** [comment]
Hi Joris,

Many thanks for your research on this and pinning down the problem.

I have followed up with the octave bug here:

https://savannah.gnu.org/bugs/?46571

**Comment by mtmiller** [comment]
This is [Octave bug #53811](https://savannah.gnu.org/bugs/?53811).
