### ISSUE TITLE
Python opti.subject_to([constr1, constr2]) syntax doesn't work

### ISSUE THREAD

**Issue by b4be1** [casadi/casadi#2255]
Dear @jaeandersson and @jgillis, I cannot pass a list of constraints in Python using the new Opti interface

```python
from casadi import Opti
opti = Opti()
x = opti.variable()
opti.subject_to([x >= 0, x <= 0])
```

Apparently, the problem is in the line

```python
self.update_user_dict(args, meta)
```

inside function `opti.subject_to`. Expanding the argument list

```python
self.update_user_dict(*args, meta)
```

solves the problem.

**Comment by jgillis** [comment]
Thanks for reporting!
