### ISSUE TITLE
Define CasADi Function with input subvector of a MX variable - is there a way?

### ISSUE THREAD

**Issue by FreyJo** [casadi/casadi#2256]
Dear CasADi Team,
I have a complex dynamic system model, defined through an MX vector. And I want to to isolate some terms and define a function, which just takes a subvector of the state vector x as an input. This works for SX but not for MX variables. Unfortunately, I can not easily change the variable type in the model.
Thus the question: Is there any trick, how to create a Function as in the following minimal example, with MX variables?
```
%% minimal example
clear all;
close all;
clc

import casadi.*

% define a function
nx = 8;

x = SX.sym('x',nx,1); 
y = x(1:5);

f = 0;
for i=1:5
    f = f+x(i);
end

% works
f_fun_x = Function('f_fun_x',{x}, {f});
x0 = rand(nx,1);
full(f_fun_x(x0))

% does not work
f_fun_y = Function('f_fun_y',{y}, {f});
y0 = x0(1:5);
full(f_fun_y(y0))
```

The error reads as:
```
Error using casadi.Function (line 1502)
Error in Function::Function for 'f_fun_y' [MXFunction] at .../casadi/core/function.cpp:233:
.../casadi/core/function_internal.cpp:123: Error calling MXFunction::init for 'f_fun_y':
.../casadi/core/x_function.hpp:238: Xfunction input arguments must be purely symbolic.
Argument 0(i0) is not symbolic.
```

Any hints appreciated!

**Comment by jaeandersson** [comment]
Try to replace
```matlab
x = SX.sym('x',nx,1); 
y = x(1:5);
```
with 
```matlab
y = SX.sym('y', 5);
z = SX.sym('z', nx-5);
x = [y;z];
```

**Comment by FreyJo** [comment]
Thanks!
I had to do quite some modifications, but it worked as intended :+1:
