### ISSUE TITLE
NLP solver interface compiled but not callable

### ISSUE THREAD

**Issue by tournesol59** [casadi/casadi#2267]
I am on Debian 8.2. I try to use casadi for making differentiated equations (in the Matlab environment), then establishing an interpolation model evaluated at each point of an interval so that the square difference between the interpolation model and the equation be minimum. 
It is roughly the same approach as the direct_collocation.m script found in the casadi examples, with a different equation (df/dt=|du/dt|*(u-f)+b*du/dt). 

At the present I have been able to build ipopt successfully but not its dedicated matlab interface. I have also built casadi as a first demo without the ipopt interface and it works for other scripts. What I have now when trying to built casadi with the -DWITH_IPOPT=ON option, is that one of the last compilation module (97%): "rocket_mx_and_sx" is not able to link with the previously buillt ipopt_interface (libcasadi_nlpsolver_ipopt.so. I got the following:
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `Ipopt::IpoptApplication::IpoptApplication(bool, bool)'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `vtable for Ipopt::StreamJournal'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `Ipopt::Journal::~Journal()'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `Ipopt::StreamJournal::SetOutputStream(std::ostream*)'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `Ipopt::StreamJournal::StreamJournal(std::string const&, Ipopt::EJournalLevel)'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `vtable for Ipopt::OptionsList'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `vtable for Ipopt::RegisteredOption'
../../../lib/libcasadi_nlpsol_ipopt.so.3.5: undefined reference to `vtable for Ipopt::RegisteredOptions'
collect2: error: ld returned 1 exit status

Any help would be highly appreciated

**Comment by jgillis** [comment]
If this is still an issue, please post this at our forum.
