### ISSUE TITLE
Update nlpsol description in the user guide

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2276]
The introduction to `nlpsol` is very short in the user guide and does not detail important features such as parameter vectors and the new sensitivity support

**Comment by jgillis** [comment]
note that I'm transcribing the user guide to a new format, so unless high priority, let's wait with this change

**Comment by jaeandersson** [comment]
ok, great

**Comment by jgillis** [comment]
User guide is ready to start editing again: https://github.com/casadi/casadi/commit/483828e6718c41bc92d97acffec368c8a505f0b8

**Comment by jaeandersson** [comment]
Can be handled as part of #3068
