### ISSUE TITLE
Bug in Sqpmethod line-search

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2294]
The calculation of the l1 infeasibility doesn't look right.

**Comment by jgillis** [comment]
What's the status of this?

**Comment by jaeandersson** [comment]
I think the globalization needs to be reimplemented from a textbook code. Or at the very least verified. To make sure that it works well, I think we need a benchmark collection interfaced.

**Comment by jgillis** [comment]
Hmm, I messed with that myself: https://github.com/casadi/casadi/commit/78c2649425f50d919fa05021dcff3f7568f98981#diff-ad82d9d2b9dc7d804f1f44e9a97e71c6R792

**Comment by jgillis** [comment]
Also relevant: https://github.com/casadi/casadi/commit/b4f29cc0737e401dbef7cf56ddc7dbe753ab354b

**Comment by jgillis** [comment]
Current implementation seems to be a conflation of several ideas:
 - the basic textbook l1-linesearch (Nocedal 18.27+ 18.29; Moritz' course)
 - allowing non-monotonic merit evolution to avoid the maratos effect (l1_cand < meritmax; written as a distinct option in b4f29cc, but somehow got merged)
 - linf, a heresay that I cannot find back in any text-book   https://github.com/casadi/casadi/commit/78c2649425f50d919fa05021dcff3f7568f98981#diff-ad82d9d2b9dc7d804f1f44e9a97e71c6R792, and was only half-implemented (ie derivative rule was not updated)

**Comment by jgillis** [comment]
Reverted to textbook scheme
