### ISSUE TITLE
evaluate a curve fit with symbolic variables

### ISSUE THREAD

**Issue by mikkkkkkk** [casadi/casadi#2301]
I obtained a curve fitting from a set of data points using the command "fit", obtaining a cfit object.
Now I want to evaluate that fit using a symbolic vector x, but using the command "feval" it gives an error because First Input must be a real non-sparse numeric array.
I don't understand why I can't evaluate the fit using:
y = feval(myFit, x);  where "x" is a symbolic variable.
Are there any other type of curve fitting that I can perform and then use that fit with symbolic variables?

**Comment by jgillis** [comment]
Arguably a short coming in Matlab. You can work around it with https://nl.mathworks.com/matlabcentral/answers/96074-how-can-i-create-a-matlab-file-function-from-a-cfit-object-created-by-the-curve-fitting-toolbox or something equivalent with `eval`
