### ISSUE TITLE
Extracting/Outputting variables for Integrators

### ISSUE THREAD

**Issue by ShravanTata** [casadi/casadi#2302]
Hello,
Is there a feature to extract/specify to the integrator to output extra variables other than the states and algebraic equations? 

Thank you

**Comment by jgillis** [comment]
Hi,

Our Integrator class does not support that.
Yet, you can easily build such functionality on top.
If you have an output function `y=h(x,z,u)`, you just evaluate it with the outputs of the integrator.
If you work with a grid output, you could use a for-loop or a for-loop equivalent: https://web.casadi.org/docs/#for-loop-equivalents

**Comment by ShravanTata** [comment]
Hi Jgillis,
Thanks for the quick response. Any plans integrating this feature in the future?

Thanks

**Comment by jgillis** [comment]
This functionality will not be added to the Integrator class.
It might get added on some higher level functionality such as `DaeBuilder`, but I'm not aware of concrete plans..

**Comment by jgillis** [comment]
As I said, it's easy to do it yourself. If you fail to do so, feel free to post a question on our forum with a code sample.
