### ISSUE TITLE
Compiling Integrator class

### ISSUE THREAD

**Issue by ShravanTata** [casadi/casadi#2303]
Hi,
I am trying to compile my Integrator using the .generate function on the integrator. 
But unfortunately I keep getting that IDAS/CVODES is not supported for this. 
Am I doing something wrong?  

Thanks

` #: Set up the integrator
   self.integrator = cas.integrator('network',
                                    integration_method,
                                     self.dae.generate_dae(),
                                      self.opts)
  self.integrator.generate_deps('file.c')`

**Comment by jgillis** [comment]
Hi! please post your questions to the forum: http://forum.casadi.org
Please also extend your example such that it can be run by other people.
