### ISSUE TITLE
Must-haves for 3.5

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2307]
* [x] Codegen of QRQP+SQP
* [ ] Interface NLopt #736 
* [x] Expand for RK
* [x] codegen for collocation/RK
* [x] Ability to mimic do-it-yourself rk4 -> simplify: True
* [x] Opti for qp
* [x] Opti and max_iter
* [x] serialize qrqp/sqpmethod
* [x] re-distribute internal headers
* [x] #2298 
* [x] octave version bump
* [x] #1847 
* [ ] quadratic constraints
* [x] allow full finite diff for nlp
* [ ] docs
* [ ] Opti x0
* [x] #677
* [x] #2304

Nice to have:
* [ ] lsq for nlp
* [x] Serializer for SX
* [x] #2136

**Comment by jgillis** [comment]
* warning: type attributes ignored after type is already defined

**Comment by Pedro-Roque** [comment]
@jaeandersson @jgillis is Casadi compatible with OSQP already?

**Comment by Pedro-Roque** [comment]
Thanks @jgillis ! Some examples with QP and LQR are mostly commented out, is this for a specific reason?

**Comment by jgillis** [comment]
Which examples?

**Comment by Pedro-Roque** [comment]
https://github.com/casadi/casadi/blob/master/docs/examples/python/lqr_control.py
https://github.com/casadi/casadi/blob/master/docs/examples/python/simulation.py

perhaps a few others?

**Comment by Pedro-Roque** [comment]
Also @jgillis is there a Slack/support channel other than the forum ?

**Comment by jgillis** [comment]
Waw indeed, these aged very badly.. 
Examples are unittested, but there no check for decay into irrelevance..

**Comment by jgillis** [comment]
Not other official channel for community support.
I watch gitter, but its barren
