### ISSUE TITLE
MX serialize bug in 3.4.5

### ISSUE THREAD

**Issue by rcleuthold** [casadi/casadi#2310]
Hello! 
I switched today from 3.4.4 to 3.4.5, and now I get the following error when I try to pickle classes including casadi functionality. The error message is below. 
Any idea what to do? 
Thanks, Rachel

```Python
  ...
  File "/usr/local/lib/python2.7/dist-packages/casadi/casadi.py", line 13609, in __getstate__
    return {"serialization": self.serialize()}
  File "/usr/local/lib/python2.7/dist-packages/casadi/casadi.py", line 13085, in serialize
    return _casadi.Function_serialize(self, *args)
RuntimeError: .../casadi/core/function_internal.cpp:1550: 'serialize' not defined for MXFunction
```

**Comment by jgillis** [comment]
I'm was not aware of this specific regression, but next release has a totally revamped serialization, extended to almost all CasADi classes, versioned and properly tested..

**Comment by rcleuthold** [comment]
any idea when the next release is planned?

**Comment by jgillis** [comment]
Aim is mid November.
Are you reading in a pickle generated with 3.4.4?
Try re-pickling with 3.4.5..
