### ISSUE TITLE
Tutorial for Dulmage-Mendelsohn decomposition on python is not working

### ISSUE THREAD

**Issue by shuoyuanxu** [casadi/casadi#2313]
Dear sir/madam

I recently tried your Dulmage-Mendelsohn decomposition function tutorial http://casadi.sourceforge.net/v1.7.1/api/html/dd/d71/matrix_2dulmageMendelsohn_8py-example.htmland it doesn't seem to work. Can you maybe update it?

Thank you

**Comment by jgillis** [comment]
That link is indeed very old.
Try this one:
http://casadi.sourceforge.net/v3.4.4/api/html/d7/d68/matrix_2btf_8py-example.html

**Comment by shuoyuanxu** [comment]
Sorry to bother you again, but the result seems to be different from Matlab. Can you tell me the reason?

Thank you

**Comment by shuoyuanxu** [comment]
I found the resulted rowperm and colperm is sorted from small to big, is this intentional?

And does this software have the functionality of obtaining the index vectors indicating the block boundaries for the fine decomposition?

**Comment by shuoyuanxu** [comment]
And this the test data and code I usedhttps://github.com/shuoyuanxu/questions-about-Casadi
