### ISSUE TITLE
Release without bundled dependencies?

### ISSUE THREAD

**Issue by mmt** [casadi/casadi#2318]
Hi,

I'm interested in using Casadi, but in a context where I'd like a little more control over which external dependencies get installed along with it.  Is there a release which uses system versions of the external libraries?  Or where you can pick and choose which libraries are used?

This is both for consistency within a build system (e.g. Bazel) where multiple sub-packages might depend on a library like CSparse and also for flexibility related to licensing issues.

Thanks for any help / feedback,

Mark

**Comment by jgillis** [comment]
A source build gives you finegrained control over these parameters. We don't have the resources to offer customizable binary builds unfortunately

**Comment by mmt** [comment]
I'm actually not concerned about a binary release, but with the contents of the external_packages sub-directory of the repository.  It looks like that contains the source code of other packages?

**Comment by jgillis** [comment]
Oh, that's should be rather easy to do. All you need is a source tar with this directory stripped?

**Comment by mmt** [comment]
Great, I think that would do it.  Let me work with my team to make sure we get the build working with that directory just removed to be sure (I don't want to make unnecessary extra work for you!)

Thanks again for Casadi, its a really great project :)
