### ISSUE TITLE
Bug in Lotka-Volterra-minIp example

### ISSUE THREAD

**Issue by s1monhell** [casadi/casadi#2321]
When creating the initial guess trajectory
`% Get a feasible trajectory as an initial guess`
`xk = x0;`
`x_start = [xk];`
`for k=1:N`
`    ret = F('x0',xk, 'p',u_start(k));`
`    x_start = [x_start ret.xf];`
`end`

This does not integrate over the entire horizon, because `xk` always stays `x0`. It should be

`% Get a feasible trajectory as an initial guess`
`xk = x0;`
`x_start = [xk];`
`for k=1:N`
`    ret = F('x0',xk, 'p',u_start(k));`
`    xk = ret.xf;`
`    x_start = [x_start xk];`
`end`

**Comment by jgillis** [comment]
Thanks! fixed now.
