### ISSUE TITLE
Add log of Gamma function and it's derivative

### ISSUE THREAD

**Issue by kk49** [casadi/casadi#2323]
It's common to minimize on the negative log of a probability as part of curve fitting and other algorithms.
The Gamma function is used when dealing with Gamma, Poisson, etc... statistical distribution, so having the log of gamma and the derivative of log of gamma available would allow Casadi to be to generate these statistical models.

Theano has support for this, but I am not sure if the licensing between the two projects would allow borrowing that code. But they do have references back to the original papers that describe coding up approximations of the various functions.

https://en.wikipedia.org/wiki/Gamma_function

**Comment by jgillis** [comment]
C99 seems to have gamma related functions so it should be trivial to add?

**Comment by jgillis** [comment]
Hmm derivative rule (digamma) is not clean..

**Comment by kk49** [comment]
Do you think it would be cleaner to make a User Defined Function or try to update the Casadi code? I need to prove out that the rest of my model will work and produce good results with Casadi, but if it does I would have a very strong incentive to get this working.

**Comment by jaeandersson** [comment]
I think for you the easiest would be to add it as external function, using the C API in the user guide. Especially if you have the derivatives readily available.

**Comment by kk49** [comment]
Thanks! I'll try that.

**Comment by jaeandersson** [comment]
Good luck! A tip is to generate something similar using the codegen support and use it as a template for your external function.
