### ISSUE TITLE
implicit cast from float to int when using abs

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#2326]
reported on https://github.com/ghorn/dynobud/issues/100 but it's actually a casadi issue

**Comment by jaeandersson** [comment]
Afaict, `abs` should be changed to `fabs`.

**Comment by ghorn** [comment]
Good catch @guibou. You found this by compiling with clang right? I wonder why the casadi build didn't catch it as they compile with at least gcc and clang.

**Comment by guibou** [comment]
@ghorn yes, clang compiling. With `-Wall` and `-Wextra`.

**Comment by ghorn** [comment]
@jgillis how'd this get missed by the clang build?
