### ISSUE TITLE
How do I use Polynomial in matlab

### ISSUE THREAD

**Issue by s1monhell** [casadi/casadi#2335]
I use Casadi 3.4.5. on Mac for Matlab. I don't understand how i can use the polynomial class. Matlab tells me there is no such method or function. I know it said here in the issues section that this class will be moved to GenMX. What I want to do is integrate and differentiate a symbolic polynomial with casadi. How do I do this?

**Comment by jaeandersson** [comment]
This is a simple helper class, doing similar to what you can do with `polyder`, `polyval`, `polyint` etc in MATLAB. For usage, see https://github.com/casadi/casadi/blob/master/docs/examples/cplusplus/implicit_runge-kutta.cpp. There is really no point of using it from MATLAB, you might as well use the above MATLAB built-in functions directly.
