### ISSUE TITLE
Installing Casadi on 32bit Linux

### ISSUE THREAD

**Issue by Alexander-M1** [casadi/casadi#2343]
I'm trying to install Casadi on a Odroid-XU4 running 32bit Ubuntu 16.04.

When I try `sudo pip install casadi` I get the following error:
```
Could not find a version that satisfies the requirement casadi (from versions: )
No matching distribution found for casadi
```
Since I didn't have any problems installing other packages, I'm guessing it has something to do with Casadi being 64bit and the Linux machine 32bit.

[Someone has asked a question regarding 32bit architecture years ago](https://github.com/casadi/casadi/issues/659), so I'm guessing the software is now able to run on 32bit, only I can't find a way to get it to work. 
I have also tried compiling from source, but encountered a problem at 72% of the make procedure. 

So my question is, how can one install and run Casadi on a 32bit Linux machine?

![casadi-pip](https://user-images.githubusercontent.com/29629421/49109834-0cddb600-f28c-11e8-87d3-a43075a509be.png)
![casadi-build](https://user-images.githubusercontent.com/29629421/49109789-e9b30680-f28b-11e8-9ade-f8a275213b02.png)

**Comment by jgillis** [comment]
Hi Alexander,

There are 32 bit builds for CasADi now, but not for the old version `3.1.1`.
I'm not sure if they are compatible with the Odroid platform. Perhaps you can verify with `pip install casadi==3.4.5` (won't work together with omgtools though).
In your case, configure casadiwith `-DWITH_SUNDIALS=OFF`. Omgtools doesn't need that anyway.
