### ISSUE TITLE
'eval' not define for norm on row vector?

### ISSUE THREAD

**Issue by andrescodas** [casadi/casadi#2348]
works:
```
  a = [3;4];

  x = casadi.MX.sym('x',size(a));

  casadinorm = casadi.Function('norm_2',{x},{norm(x)});

  casadinorm(a)
```

fails:
```
  a = [3,4];

  x = casadi.MX.sym('x',size(a));

  casadinorm = casadi.Function('norm_2',{x},{norm(x)});

  casadinorm(a)
```
error: casadiMEX: .../casadi/core/mx_node.cpp:291: 'eval' not defined for class N6casadi5Norm2E
error: called from
    call at line 735 column 28
    paren at line 1433 column 13
    subsref at line 1414 column 29

**Comment by jgillis** [comment]
You're right, the 2-norm should fall back to Frobenius norm for either row or column vector.
