### ISSUE TITLE
Automatically detect simple bounds for Opti

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2357]
Should be optional/granular

**Comment by jgillis** [comment]
Issues:
 * When solver reports a NaN in nlp_jac_g, how to map back?

**Comment by jgillis** [comment]
opts = struct;
opts.simple_bounds = 'detect';

subject_to(a<=b, opts);

```python

with opti.options({"simple_bounds": "detect"}):
  subject_to(a<=b);

```

```python

with opti.simple_bounds({"simple_bounds": "detect"}):
  subject_to(a<=b);

```

**Comment by charleskhazoom** [comment]
has some version of this `opts.simple_bounds = 'detect';` been implemented yet ?

**Comment by jgillis** [comment]
Has arrived in 3.6
