### ISSUE TITLE
MX silently changes the size if the input is a [1,n] matrix

### ISSUE THREAD

**Issue by deego** [casadi/casadi#2366]
MX silently changes the size if the input is a [1,n] matrix. SX does the right thing:
                               
a=ones(2,4)
size(a) ## [2 4]
size(MX(a)) ## [2 4], MX does the right thing here. 

a=ones(1,4)
size(a) ## [1 4]
size(SX(a)) ## [1 4]  SX handles the [1,n] case well. 

a=ones(1,4)
size(a)  ## [1 4]
size(MX(a)) ## [4 1] ------ this should have been [1 4]

---

casadi 3.4.4 (with octave 4.2).

**Comment by jgillis** [comment]
Thanks a lot for reporting this issue.
Fixed in develop now
