### ISSUE TITLE
not(x) can result in something that is neither 0 nor 1

### ISSUE THREAD

**Issue by deego** [casadi/casadi#2380]
If you create a logical variable y , you expect it to behave like a logical variable going forward.
For example, if you try y=not(x), y tests whether x == 0.

Your program now assumes y is a logical variable, and z=not(y) will dtrt. For this case, z should tell you if x !=0.

But, z turns out to = x for casadi objects. 

For comparison, in matlab/octave, z = not(not(x))  is always either 0 or 1. It is equivalent to logical(x).

**Comment by jgillis** [comment]
Thanks for raising your issue.
Can you clarify a bit what is expected behaviour?

```matlab
x = SX.sym('x')
not(x)        % !x
not(not(x)) % x

f = Function('f',{x},{[x,not(x),not(not(x))]})
f(1) % [[1, 0, 1]]
f(0) % [[0, 1, 0]]
f(2) % [[2, 0, 2]]
```

Do you mean that `not(not(x))` should return `x~=0` instead?

**Comment by jaeandersson** [comment]
Yeah, the design is sort of that if you apply it to something that isn't zero or one, all bets are off. That allows us to simplify not(not(x)) to x.

**Comment by deego** [comment]
Hi jaeandersson and jgillis. 

Yes, that's what I had intended to suggest: that not(not(x)) should result in a boolean number, and thus, in x~=0.  I had a really strange bug in my code and this turned out to be the problem: a boolean had been constructed via not(x)  - I should have use x!=0.  The code then ended up taking another not() of the boolean, yielding the wrong answer.

But, like you said, if it's more efficient to have it not(not(x)) = x, I completely understand: When using casadi, the user should always use x!=0 when constructing a boolean instead of not(x). 

Thanks for explaining and in that case, please close this issue.

**Comment by jaeandersson** [comment]
Sounds good. Might be good to point out that x!=0 rather than not(x) should be used when x is not binary.
