### ISSUE TITLE
obscure warning when substituting undeclared object

### ISSUE THREAD

**Issue by Mathadon** [casadi/casadi#2381]
In C++ when doing something like:

```C
MX b = ...
MX c = ... 
MX a = MX::substitute({a},{b},{c}).front(); 
```
where a is thus not defined before using it, I get the following error (through the JModelica JVM):

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6d190ff8d8, pid=3818, tid=0x00007f6d37586700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libcasadi.so.3.5+0xc68d8]  casadi::SharedObject::count_up()+0x8
```
clearly, I cannot use `a` since it was not declared before using it, but it would be nice if CasADi could throw a warning that is a bit more specific about this?

**Comment by jgillis** [comment]
Hmm how is this even legal c++?

**Comment by Mathadon** [comment]
Just double-checked. Gcc 5.4 accepts it, although I was using vectors instead of regular MXs. I updated the original post accordingly.

**Comment by jgillis** [comment]
Okay, apparently self-initialisation is a thing in C/C++.

Debug case:
```
MX a = sin(a);
```

**Comment by jgillis** [comment]
This is a scary feature of C++, I'm afraid we cannot do anything about this.
Unfortunately `-Wall` does not even discover this, though valgrind does.

**Comment by Mathadon** [comment]
😕 I'll have to pay more attention then I guess! Thanks for looking into it!

**Comment by jgillis** [comment]
Clang does give a warning: https://godbolt.org/z/F6TffS
Perhaps you can file a bug report with gcc?
