### ISSUE TITLE
Restore raw-memory Callback::eval()

### ISSUE THREAD

**Issue by chrisdembia** [casadi/casadi#2385]
The develop branch does not have the following function:

```cpp
virtual int Callback::eval(const double** inputs, double** outputs, casadi_int*, double*,
        void*) const;
```

I was using this function in my custom `Callback`s because access to the raw memory was more convenient and avoided reallocating `DM`s for the return value on every call (using the `Callback::eval()` that uses `DM`s).

Would it be possible to restore this virtual function, or to provide the `DM` outputs as mutable reference argument rather than a return value?

**Comment by jaeandersson** [comment]
The Callback class is a high-level abstraction of FunctionInternal. Have you considered using the C API instead? That should be more lean.

**Comment by chrisdembia** [comment]
Ah I see. Can I still implement get_jacobian_sparsity()? (Branch issue_1847)

**Comment by jaeandersson** [comment]
I think you should be able to provide the sparsity via the C API. Is that what you mean?

**Comment by chrisdembia** [comment]
Yes, thank you.

**Comment by jaeandersson** [comment]
There is a naming convention to provide this information. Let me know if you get stuck.
