### ISSUE TITLE
External function option for sqpmethod f_gradient and lagrange_hessian

### ISSUE THREAD

**Issue by tsijs** [casadi/casadi#2399]
First of all, thank you for developing and maintaining this very useful tool!

I am exploring the possibility of using Casadi for a project I am working on as an interface to nlp solvers. I will have to use the external functions functionality to deal with my cost function, since that depends on a very nastily shaped nonlinear function that depends on external stuff. 

In a test-setup I can now use ipopt with an external function as cost function and two other external functions as gradient of the cost and hessian of the lagrangian. 

(I added two empty functions called jac_f and jac_jac_f in the source file of a generated function f to hack this together, so maybe this is the wrong approach altogether..)

However, when I now want to change from ipopt to your sqpmethod interface, I noticed that the option of passing the hessian of the lagrangian, the gradient of the cost and the jacobian of the constraints are no valid options. Was this done intentionally or would you suspect it to work if I change the source code of sqpmethod.cpp to add those options? 

Also, I wasn't sure if I should post this here or on the google group. If this is the wrong place, I will close this and ask it in the google group;)

**Comment by jgillis** [comment]
Develop branch has the options..

**Comment by tsijs** [comment]
Wow, I am blind.. Thanks for pointing it out!
