### ISSUE TITLE
Segfault when using SOS with CBC solver

### ISSUE THREAD

**Issue by jackvreeken** [casadi/casadi#2406]
Tested on 3d8e6786cbaa96a6f6dddbb362c5b2dfa496cd50

I'm not sure why, but this way of adding SOS constraints/weights is not correct for CBC. The piece of code below gives me a segfault on the call to `addObjects`, https://github.com/coin-or/Cbc/blob/releases/2.9.8/Cbc/src/CbcModel.cpp#L11864. `objects[i]` is `0x49` when I debug (not 100% what gdb is showing me), which is the number of SOS groups I have (73). I think it should instead be a pointer to something.

```cpp
    std::vector<CbcSOS> sos_objects;
    for (casadi_int i=0;i<sos_groups_.size();++i) {

      const std::vector<int>& sos_group = sos_groups_[i];
      sos_objects.emplace_back(&model, sos_group.size(), get_ptr(sos_group),
                    sos_weights_.empty() ? nullptr : get_ptr(sos_weights_[i]), i, sos_types_[i]);
    }
    if (!sos_objects.empty()) {
      CbcObject* temp = get_ptr(sos_objects);
      model.addObjects(sos_objects.size(), &temp);
    }
```
If I instead modify this to be more or less like what is in CBC's examples, it does work:
```cpp
    int numberSOS = sos_groups_.size();

    if (numberSOS > 0) {
      CbcObject **objects = new CbcObject *[numberSOS];

      // Set up SOS
      for (int i = 0; i < numberSOS; i++) {
        const std::vector<int>& sos_group = sos_groups_[i];
        objects[i] = new CbcSOS(&model, sos_group.size(), get_ptr(sos_group),
                               sos_weights_.empty() ? nullptr : get_ptr(sos_weights_[i]), i, sos_types_[i]);
      }

      model.addObjects(numberSOS, objects);

      for (int i = 0; i < numberSOS; i++)
        delete objects[i];
      delete[] objects;
    }
```
It's probably related to the vector types, and pointers, but my C++ is not as good as my C is so I don't quite know what's wrong.

**Comment by jgillis** [comment]
Thanks I'll have a look

**Comment by jgillis** [comment]
Indeed I messed up here. Strange that it passed my SOS unittests..
