### ISSUE TITLE
Linking problems with the newer gcc compilers

### ISSUE THREAD

**Issue by petlist** [casadi/casadi#2409]
Hi Joel, Joris,

I've been working on a project that has CasADi as a dependency. I noticed recently that it has  linking problems when I use the newer g++ compilers (>= 5) with your binaries. 

My setup: Ubuntu 18.04, g++-7.3, cmake-3.10, CasADi v3.4.5 linux binaries.
Error type: undefined reference to ...(everything related to CasADi)

I noticed in your Travis scripts that default OS is Trusty, may be that's the reason? 

Thanks,
Peter

**Comment by jkoendev** [comment]
https://groups.google.com/forum/#!topic/casadi-users/T4nvZMVR5xc

**Comment by jgillis** [comment]
Sure, this is the gcc 4 versus 5 ABI breakage.
I'm lacking resources at the moment to maintain more build variants.

At the moment, for C++ projects, you better ship your own CasADi.
In the future we should probably adopt https://conan.io/ or similar
