### ISSUE TITLE
MS Excel interface

### ISSUE THREAD

**Issue by samiit** [casadi/casadi#2412]
Is there any future work planned for having an interface for MS Excel, e.g., through OpenSolver? Currently, OpenSolver does the task of differentiation (probably through finite differences) for non-linear problems, but I am not sure. Any plans ahead?

**Comment by jgillis** [comment]
Certainly not planned. We can give support if you'd like to give it a shot yourself..

**Comment by jaeandersson** [comment]
I general, I think it would make little sense to use CasADi if you're not planning to use the algorithmic differentiation support.
