### ISSUE TITLE
Sparse linear solver LDL - nonsymmetric matrix false-negative

### ISSUE THREAD

**Issue by joycezyu** [casadi/casadi#2414]
I'm not completely sure if this is a new issue. 
It seems that the LDL implementation fails to raise an exception when I have an input A matrix which is not symmetric. LDL can actually solve for an incorrect solution. It's actually pretty surprising because the following line seems to suggest that it checks the symmetric pattern of the matrix before proceeding. 
https://github.com/casadi/casadi/blob/37b6e115191a2de5a8eb4593c7c4afc7c996ef08/casadi/core/matrix.cpp#L1928-L1929

Please instruct if it's an issue with my implementation. Thank you!

**Comment by jaeandersson** [comment]
You're correct, symmetry is not being checked right now so all bets are off if you throw a non-symmetric matrix at it. The assertion above only makes sure that the *sparsity patter* is symmetric, i.e. the location of the nonzeros. This is a necessary, but not sufficient criterion for the matrix being symmetric.

**Comment by joycezyu** [comment]
I see - and yes my case has a symmetric sparsity pattern so it passes the test. 
It seems that as long as the input matrix _is_ _truly _symmetric_ , the linear algebra checks out correctly. I will report more once I have more results.
Thanks Joel!
