### ISSUE TITLE
memory leak in SX

### ISSUE THREAD

**Issue by roversch** [casadi/casadi#2415]
If I run the following code, I get a memory leak of 16 bytes (checked with `valgrind`): 

````c++
#include "casadi/casadi.hpp"

int main() {
    casadi::SX::sym("x");
    return 0;
}
````

The reason is the initialization of `static` variables, which leads to a wrong reference count, namely in 

https://github.com/casadi/casadi/blob/6b0de13ac78cb59b10e7a7a11d8a96d8fecbf951/casadi/core/constant_sx.hpp#L313 

For example, all other constants (inf, -1, etc) do not increase the reference count at initialization. Removing `this->count++;` and `this->count--;` in the following line removes the memory leak.

**Comment by roversch** [comment]
By the way, this is the line where the static initialization occurs: 

https://github.com/casadi/casadi/blob/6b0de13ac78cb59b10e7a7a11d8a96d8fecbf951/casadi/core/sx_elem.cpp#L524

**Comment by jaeandersson** [comment]
I'm trying to remember if this was intentional or not. Technically it's not a memory leak (since nothing happens if you call it repeatedly), so you can call it a false positive in valgrind. Because NaN is the default value for SX, it's a bit special. @jgillis - do you know?

**Comment by roversch** [comment]
Whatever you call it, valgrind says `16 bytes still reachable`. I don't think it's a false positive, because that memory, allocated by `new` is not effectively freed, but you're right that it's not critical, as it only happens once at static initialization time.

**Comment by jaeandersson** [comment]
Leaving the definition of memory leak aside (whether non-growing qualifies), it should be easy to fix. With a singleton design pattern.

**Comment by jaeandersson** [comment]
@roversch Can you check if this resolves your issue?

**Comment by jaeandersson** [comment]
Also made corresponding update for other SX singletons.

**Comment by roversch** [comment]
I can confirm that this solves the issue.

**Comment by jaeandersson** [comment]
Great
