### ISSUE TITLE
Overhead in calling integrator functions from python

### ISSUE THREAD

**Issue by ShravanTata** [casadi/casadi#2416]
Hi All,

I am currently using the casadi integrators from Python to integrate my ode models. 
But comparing the same models with scipy (lsoda) I have a huge performance gain. Scipy is 8-10 times faster with same tolerance compared to Casadi.

I have explored most of the options available with Casadi integrator interfaces and tried CVODEs, RK and even IDAS but nothing compares to the lsoda scipy performance. 

I do not understand where is the loss in performance in Casadi for a such a huge difference. Could some help me out on this. 

Thank you,

Shravan

**Comment by jaeandersson** [comment]
Please direct this question to the forum, forum.casadi.org

**Comment by ShravanTata** [comment]
@jaeandersson It is unfortunate that no one has responded to this issue on the forum and I feel this is definitely an issue that needs to be looked at. Any support from the developer team is appreciated.

Thank you
