### ISSUE TITLE
simple C CasADi API

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2425]
With Serialization in place, we could add an interesting new way to use CasADi.

Model in high level, save to the disk:
```python
f = Function('f',...)
f.save('f.casadi')
```

Export c-symbols from libcasadi that mirror the codegen API:
```c
casadi_c_load('f.casadi');
...
casadi_c_work('f', &sz_arg, &sz_res, &sz_iw, &sz_w);
...
casadi_c_eval('f', arg, res, iw, w);
```

**Comment by jaeandersson** [comment]
So you'd have a dependency on libcasadi? Why not use the C++ API then?

**Comment by jgillis** [comment]
Right. C may be desirable as interface. Eg in bridging fortran

**Comment by jaeandersson** [comment]
I can see how that makes sense if you're using the plugins, something that cannot be code generated. If code generation is possible, that's probably desirable, right?

**Comment by jgillis** [comment]
That's the primary use case yes; could also have files to big to compile

**Comment by jgillis** [comment]
I'm in doubt about the exact signatures desirable. If you can keep them the same as codegen, you could still use <mem.h> as-is.

```
casadi_c_activate('f');
int memf = casadi_c_checkout();

casadi_c_activate('g');
int memg = casadi_c_checkout();

casadi_c_eval(arg, res, iw, w, memf);
casadi_c_eval(arg, res, iw, w, memg);
```

Problem is that setup would not be thread-safe

**Comment by jgillis** [comment]
First implementation running https://github.com/casadi/casadi/commit/d84570c3130b9d499c1c3686b33135fb4a79035e#diff-f899be2b9113deaacc5c25cdf1c553f1R131 , ready for testing @jdeschut
