### ISSUE TITLE
Large overhead in calling functions from Python

### ISSUE THREAD

**Issue by ShravanTata** [casadi/casadi#2433]
When I profile my python code with casadi I see that bulk of the time is being spent just calling the functions. This is just not acceptable for good performance. Am I doing something wrong here? I have attached a simpler example code for benchmarking and clearly even in the simple example repeated calling of casadi functions from Python have a severe overhead. Looking forward to your response.

```python
from IPython import embed
import os
from pycallgraph.output import GraphvizOutput
from pycallgraph import PyCallGraph
import casadi as cas
""" Benchmarking a casadi function written in python versus cpp."""

import timeit


setup = """
import casadi as cas
x = cas.SX.sym('x', 2)
y = cas.SX.sym('y')
f = cas.Function('f', [x, y],
                 [x, cas.sin(y)*x])
arg=[0.2, 0.1]"""

print("Normal call {}".format(timeit.timeit(
    "f(0.2, 0.1)", setup=setup, number=100000)))

print("Using function call {}".format(timeit.timeit(
    "f.call(arg)", setup=setup, number=100000)))

setup_numpy = """
import numpy as np
def f(x, y):
    return [x, np.sin(y)*x]
"""

print("Numpy {}".format(
    timeit.timeit("f(0.2, 0.1)", setup=setup_numpy, number=100000)))

x = cas.SX.sym('x', 2)
y = cas.SX.sym('y')
f = cas.Function('f', [x, y],
                 [x, cas.sin(y)*x])

with PyCallGraph(output=GraphvizOutput()):
    f(0.1, 0.2)

#################### CODE GEN ####################
f.generate('gen.c')
f.generate('libgen.cc', {'cpp': True, "with_header": True})
os.system("gcc -fPIC -shared gen.c -o gen.so")

setup_gen = """
import casadi as cas
f = cas.external('f', './gen.so')
"""

print(timeit.timeit("f(0.2, 0.1)", setup=setup_gen, number=100000))

```
[casadi_benchmark.py.tar.gz](https://github.com/casadi/casadi/files/31801/casadi_benchmark.py.tar.gz)

**Comment by jgillis** [comment]
Hi Shravan, this is simply an issue in priorities.

Reducing overhead in the SWIG bridge (what we use for Python and Matlab) has been of low priority.
In fact, we had a low overhead (memory-allocation free) a long time in the past, but it was deemed unmaintainable at the time (it required binaries tied to specific versions of numpy).

The reason for having it low priority is that, in the bulk of applications with CasADi, the computations happening inside CasADi dominate the SWIG call overhead by a long shot; think e.g. solving an NLP problem, completely with first and second derivatives going through a single SWIG call.

To connect with your example, using a map reduces the number of SWIG calls to one, reducing a major part of overhead:
```
setup = """
import casadi as cas
x = cas.SX.sym('x', 2)
y = cas.SX.sym('y')
f = cas.Function('f', [x, y],
                 [x, cas.sin(y)*x])
fm = f.map(100000)
arg=[0.2, 0.1]"""

print("Normal call {}".format(timeit.timeit(
    "f(0.2, 0.1)", setup=setup, number=100000)))

print("Mapped call {}".format(timeit.timeit(
    "fm(0.2, 0.1)", setup=setup, number=1)))
```

Having said that, I've played around with ctypes in the meantime,
and it's probably not that difficult to make a new shot at a maintainable low-overhead API using it or buffers.
Do you have a particular application in mind?

**Comment by ShravanTata** [comment]
Hi Jgillis,

I agree with the points you make. Indeed for most use cases I am happy with the efficiency of Casadi over SWIG calls. But in my particular application it is essential that I have to make multiple function calls. In my application, I am doing a time step based integration and hence I have to call the integrator function at every time step. This really makes the function calls a very big bottle neck for me. It would be really great if we could reduce this overhead. I really feel terrible to let go of Casadi just for this issue.

**Comment by jgillis** [comment]
Is codegeneration an option for you? Using our C API, and something like Boost.Python, one could drastically reduce overhead.

**Comment by ShravanTata** [comment]
Yes, code generation is definitely an option. Are you suggesting to use boost python for integration? Can you give me a few more hints about this?

**Comment by jgillis** [comment]
The C-api is documented here: https://web.casadi.org/docs/#api-of-the-generated-code
Example code: https://github.com/casadi/casadi/blob/3.4.5/docs/examples/cplusplus/codegen_usage.cpp

I have no experience with boost Python; creating an instructive example would take as much time as actually implementing it as feature for the upcoming CasADi release. How urgent is your request?

What I can give you now is ctypes code I played with earlier, it does give a big speedup allready.
Though, in the meantime, I learned that ctypes comes with a large overhead too.
The fastest interface seems to be to create a Python extension module; either with boost Python or from scratch.
```python
from IPython import embed
import os
import casadi as cas
""" Benchmarking a casadi function written in python versus cpp."""

import timeit




setup = """
import casadi as cas
x = cas.SX.sym('x', 2)
y = cas.SX.sym('y')
f = cas.Function('f', [x, y],
                 [x, cas.sin(y)*x])
fm = f.map(100000)
arg=[0.2, 0.1]"""


print("Normal call {}".format(timeit.timeit(
    "f(0.2, 0.1)", setup=setup, number=100000)))

print("Mapped call {}".format(timeit.timeit(
    "fm(0.2, 0.1)", setup=setup, number=1)))


x = cas.SX.sym('x', 2)
y = cas.SX.sym('y')
f = cas.Function('f', [x, y],
                 [x, cas.sin(y)*x])

f.generate('gen.c')
f.generate('libgen.cc', {'cpp': True, "with_header": True})
os.system("gcc -fPIC -shared gen.c -o gen.so")

setup_gen = """
from casadi_codegen_wrapper import CasadiCodegenWrapper
import casadi as cas
import numpy as np
from ctypes import c_double, POINTER
fwrap = CasadiCodegenWrapper("./gen.so","f")
output_buffer = fwrap.allocate_outputs()

arg1 = np.array([[0.2],[0.2]],dtype=c_double,order="F")
arg2 = np.array([[0.1]],dtype=c_double,order="F")
args = [arg1.ctypes.data_as(POINTER(c_double)),arg2.ctypes.data_as(POINTER(c_double))]
"""
print("Mapped call {}".format(timeit.timeit(
    "fwrap.call_minimal(args,output_buffer)", setup=setup_gen, number=100000)))
```

```python
import numpy as np
from ctypes import c_double, c_int, c_longlong, c_char_p, POINTER, cdll, byref

class CasadiSparsity:
  """
  Compressed Columun storage sparsity pattern
  """
  def __init__(self,sp):
    self.n_row = sp[0]
    self.n_col = sp[1]
    self.colind = np.array(sp[2:2+self.n_col+1])
    self.nnz = self.colind[-1]
    self.row = np.array(sp[2+self.n_col+1:2+self.n_col+1+self.nnz])
  def is_dense(self):
   return self.nnz == self.n_row*self.n_col

class CasadiCodegenWrapper:
  def __init__(self,library,name):
    self.name = name
    self.lib = cdll.LoadLibrary(library)
    self._f("n_in").restype = c_longlong
    self.n_in = self._f("n_in")()
    self._f("n_out").restype = c_longlong
    self.n_out = self._f("n_out")()

    f_name_in = self._f("name_in")
    f_name_in.argtypes = [c_longlong]
    f_name_in.restype = c_char_p

    self.names_in = [str(f_name_in(i)) for i in range(self.n_in)]

    f_name_out = self._f("name_out")
    f_name_out.argtypes = [c_longlong]
    f_name_out.restype = c_char_p

    self.names_out = [str(f_name_out(i)) for i in range(self.n_out)]

    sparsity_in = self._f("sparsity_in")
    sparsity_in.argtypes = [c_longlong]
    sparsity_in.restype = POINTER(c_longlong)

    self.sparsity_in = [CasadiSparsity(sparsity_in(i)) for i in range(self.n_in)]

    sparsity_out = self._f("sparsity_out")
    sparsity_out.argtypes = [c_longlong]
    sparsity_out.restype = POINTER(c_longlong)
    
    self.sparsity_out = [CasadiSparsity(sparsity_out(i)) for i in range(self.n_out)]

    #self.default_in = self._f("default_in")
    #self.default_in.argtypes = [c_longlong]
    #self.default_in.restype = c_double

    self.incref = self._f("incref")
    self.decref = self._f("decref")

    self.f = self._f()
    self.f.argtypes = [POINTER(POINTER(c_double)),POINTER(POINTER(c_double)),POINTER(c_longlong),POINTER(c_double),c_int]
    self.f.restype = c_int

    #self.checkout = self._f("checkout")
    #self.checkout.restype = c_int
    #self.release = self._f("release")
    #self.release.argtypes = [c_int]
    #self.release.restype = c_int
    #mem = self.checkout()
    #self.release(mem)
    self.incref()

    work = self._f("work")
    work.restype = c_int
    work.argtypes = [POINTER(c_longlong)]*4
    sz_arg = c_longlong()
    sz_res = c_longlong()
    sz_iw  = c_longlong()
    sz_w   = c_longlong()
    work(byref(sz_arg), byref(sz_res), byref(sz_iw), byref(sz_w))

    self.arg = (POINTER(c_double)*sz_arg.value)()
    self.res = (POINTER(c_double)*sz_res.value)()
    self.iw = (c_longlong*sz_iw.value)()
    self.w  = (c_double*sz_w.value)()

  def __del__(self):
    self.decref()

  def _f(self,name=None):
    name = self.name if name is None else self.name + "_" + name
    
    return getattr(self.lib,name)

  def allocate_outputs(self):
    r = []
    for i in range(self.n_out):
      sp = self.sparsity_out[i]
      assert sp.is_dense()
      r.append(np.zeros((sp.n_row, sp.n_col),dtype=np.double,order="F"))

  def call_minimal(self,arg,res):
    self.f(self.arg,self.res,self.iw,self.w,0)

if __name__ == "__main__":
  wrapper = CasadiCodegenWrapper("./f.so","f")

  output_buffer = wrapper.allocate_outputs()

  print(output_buffer)

  arg = np.array([[1,-1],[-1,2]],dtype=c_double,order="F")
  wrapper.call_efficient([arg],output_buffer)

  print(output_buffer)
```

**Comment by jbaayen** [comment]
My concern is that sometimes, functions are slower to evaluate when using code generation than without.

**Comment by ShravanTata** [comment]
@jgillis Thank you very much for the example. Clearly playing with arrays does have a huge performance boost. I will still have to look into how I can extend this to the integration example. 

But it would be great if we could add an interface like this with upcoming casadi release. It can have considerable performance when needed. Let me know if this is a possibility in the short term future. 

@jbaayen : Yes, I have seen this issue as well. Haven't looked into it though!

**Comment by jackvreeken** [comment]
A pure Python version is about 10 times faster than NumPy still (if we are just talking overhead for the small example you posted).

Generally though, SWIG is terribly slow due to all layers of wrapping it does. I have run into the exact issue you have, and worked very hard to reduce the number of calls to CasADi for that exact reason. Even for a simple class attribute access SWIG is about three times slower than CPython...

As far as a fast interface is concerned; pybind11 is a little faster than SWIG, but not by much. To wrap C++ classes directly the fastest ones are cppyy and Cython, but you will probably run into some limitations with both. I tried to wrap CasADi with cppyy, requiring very little manual work to get started, but I just couldn't get it to run for anything non-trivial... 

Another very fast and much more reliable option is to wrap the C++ API with a C89 API, use CFFI (for PyPy) and Cython (for CPython) to bridge that interface to Python, and then reimplement the class-based API in pure Python. From what I remember, this is what ZeroMQ does (with its many wrappers for all kinds of languages). Typically then, the C89 API is the "one true API", with the internal C++ implementation being hidden from view. This also means that the C89 API is then again wrapped with another layer for C++ for a public/user-facing C++ API (the "hourglass" approach). This all involves quite a bit more manual labour than SWIG<sup>†</sup>, although it is relatively menial work you only have to do once (assuming the API is reasonably stable).

<sup>†</sup>That said, `casadi.i` is already ~4500 lines itself as well...

**Comment by jgillis** [comment]
Jack, are you talking, like OP, about the overhead for calling CasADi Functions numerically, or the more general CasADi API?
For the former, I already had strategies in mind to minimize overhead. Just need to find time to implement..

**Comment by jackvreeken** [comment]
Isn't SWIG the cause for slow calls for both calling of CasADi Functions and the overall CasADi API, seeing as they are both very much object-based? 
Overhauling the entire API is a lot of work, so making more critical pieces accessible with a low-overhead POD C-API (which seems to be relatively fast even with SWIG, although still slower than Cython) makes sense to me.

**Comment by jgillis** [comment]
Did some exploratory work for minimal-overhead Function calls in Python.

Results for a scalar (x,y)->x+y:
```
Numpy: 500 ns
Native:  100 ns
CasADi: 75 ns
```

```
import os
from casadi import *
import numpy as np
import time

x = SX.sym('x')
y = SX.sym('y')
f = Function('f', [x, y],
                 [x+y])

a = 0.1
b = 0.2
x0 = np.array([a])
x1 = np.array([b])
res = np.array([1.1])

def foo(a,b):
  return a+b

id = fm_alloc(f)
fm_set_arg(id,0, memoryview(x0))
fm_set_arg(id,1, memoryview(x1))
fm_set_res(id,0, memoryview(res))

cc = casadi._casadi.fm_eval

N = 10000000

t0 = time.time()
for i in range(N):
  cc(id) # CasADi
  #foo(a,b)  # native
  #x0+x1 # numpy
print((time.time()-t0)/N*1e9, " [ns]")
print(res)
```


```
SWIGINTERN PyObject *_wrap_fm_eval(PyObject *SWIGUNUSEDPARM(self), PyObject *arg) {
  casadi_int id = PyLong_AsLongLong(arg);
  casadi::fm_eval(id);
  Py_RETURN_NONE;
}
```
Make use of `METH_O`:
```
	 { (char *)"fm_eval", _wrap_fm_eval, METH_O, (char *)"\n"
```

**Comment by jgillis** [comment]
Feature ready; see https://github.com/casadi/casadi/commit/3e9919e9195e8f057d09cd9bcc4f7fa59e6fc104#diff-ad1e1bf2c8d8bef2a0f3b3b85331ffd0R2491
