### ISSUE TITLE
Using Opti in simulink

### ISSUE THREAD

**Issue by Thomas1994Johansen** [casadi/casadi#2439]
Hei

I am running Casadi with the opti stack and using the output from this in a simulink diagram. This works well, but i was wondering if it is possible to update my problem at certain timesteps in my simulation and using the previously defined opti problem and only updating certain parts of this for each iteration. Solving my defined problem take much less time than actually defining the problem so I was hoping that this could reduce the time used in my simulations so i can actually run the optimization realtime.

**Comment by jgillis** [comment]
Update in what sense?
The only thing that you can efficiently update at the moment is numerical values of parameters in your problem..

**Comment by Thomas1994Johansen** [comment]
Thats exaclty what I want.
I am using my code as a path planner and then i want to run the optimization again for each 10 seconds but only updating the current position of my vehicle. 

My problem now is defined like this 

east_finish = 800;
north_finish = 1000;
speed_finish = 0;
heading_finish = pi/2;
north_start = 250;
east_start = 300;

a_max = 0.05;
a_min = -a_max;
omega_max = 0.55*pi/180;
omega_min = -omega_max;
jerk_max = 0.0005;
jerk_min = -0.0005;
angularAcc_max = 0.02*pi/180;
angularAcc_min = -0.02*pi/180;
shortest_dist = sqrt((north_finish-north_start)^2 + (east_finish-east_start)^2);
shortest_time = sqrt(shortest_dist/a_max)*2;

N = 50;
opti = casadi.Opti(); % Optimization problem

% ---- decision variables ---------
X = opti.variable(4,N+1); % state trajectory
north   = X(1,:); % NORTH
east   = X(2,:); % EAST
speed = X(3,:);   % Surge speed
heading = X(4,:); % Heading
U = opti.variable(2,N+1); % control trajectory
a = U(1,:); % Acceleration
omega = U(2,:); % Yaw rate
T = opti.variable();
opti.minimize(T);% + sum(a.^2) + sum(omega.^2));

f = @(x,u) [x(3)*cos(x(4)); x(3)*sin(x(4)); u(1); u(2)];

dt = T/N; % length of a control interval
for k=1:N % loop over control intervals
   % Runge-Kutta 4 integration
   k1 = f(X(:,k),         U(:,k));
   k2 = f(X(:,k)+dt/2*k1, U(:,k));
   k3 = f(X(:,k)+dt/2*k2, U(:,k));
   k4 = f(X(:,k)+dt*k3,   U(:,k));
   x_next = X(:,k) + dt/6*(k1+2*k2+2*k3+k4);
   opti.subject_to(X(:,k+1)==x_next); % close the gaps
   opti.subject_to((a(k+1)-a(k))/dt >= jerk_min);
   opti.subject_to((a(k+1)-a(k))/dt <= jerk_max);
   opti.subject_to((omega(k+1)-omega(k))/dt >= angularAcc_min);
   opti.subject_to((omega(k+1)-omega(k))/dt <= angularAcc_max);
end


% ---- control constraints -----------
opti.subject_to(a_min<=a<=a_max);
opti.subject_to(omega_min<=omega<=omega_max);

opti.subject_to(north(1)==north_start);
opti.subject_to(east(1)==east_start); 
opti.subject_to(heading(1)==0); 
opti.subject_to(speed(1)==0);



opti.subject_to(north(N+1)==north_finish); 
opti.subject_to(east(N+1)==east_finish); 
opti.subject_to(heading(N+1)==heading_finish); 
opti.subject_to(speed(N+1)==speed_finish);

opti.subject_to(T>=0);
opti.set_initial(T,shortest_time);
opti.solver('ipopt');
sol = opti.solve(); 

Then I want to only define the following values again every 10 seconds and solve the optimization with these new values.

opti.subject_to(north(1)==north_start);
opti.subject_to(east(1)==east_start); 
opti.subject_to(heading(1)==0); 
opti.subject_to(speed(1)==0);

sol = opti.solve();

**Comment by jgillis** [comment]
Look for 'set_value' and 'parameter' in the Opti chapter of docs.casadi.org
