### ISSUE TITLE
library loaded with "external" needs the be of a specific name

### ISSUE THREAD

**Issue by pariterre** [casadi/casadi#2453]
Hi there!

I am using CasADi to optimize human movement. I have an external library (biorbd) that takes care of the dynamics. Therefore I need to connect CasADi to that library. In order to learn how to do that, I just copied and run the example code for that. Here is a smaller and slightly modified version that actually reproduce the bug:
```c++

// C++ (and CasADi) from here on
#include <casadi/casadi.hpp>
using namespace casadi;
using namespace std;

void usage_cplusplus(){
  cout << "---" << endl;
  cout << "Usage from CasADi C++:" << endl;
  cout << endl;

  // Use CasADi's "external" to load the compiled function
  Function f = external("libf");

  // Use like any other CasADi function
  vector<double> x = {1, 2, 3, 4};
  vector<DM> arg = {reshape(DM(x), 2, 2), 5};
  vector<DM> res = f(arg);

  cout << "result (0): " << res.at(0) << endl;
  cout << "result (1): " << res.at(1) << endl;
}

int main(){

  // Variables
  SX x = SX::sym("x", 2, 2);
  SX y = SX::sym("y");

  // Simple function
  Function f("libf", {x, y}, {sqrt(y)-1, sin(x)-y});

  // Generate C-code
  f.generate("f");

  // Compile the C-code to a shared library
  string compile_command = "gcc -fPIC -shared -O3 f.c -o libf.so";
  int flag = system(compile_command.c_str());
  casadi_assert(flag==0, "Compilation failed");

  // Usage from C++
  usage_cplusplus();

  return 0;
}
```

Please note that I changed the ```-o f.so``` for ```-o libf.so``` as it is usually automatically added on UNIX unless specifically specified not to (that what actually caused my problem, since I was recompiling the generated f.c file using CMake). Then, when it is loaded (```Function f = external("libf");```), it loads, but crashes at the evaluation line (```f(arg);```) reporting an error in the dimensions of the arguments. The problem is indeed not this, it is the fact that inside the generated file f.c, the function names don't include the extra "lib". Since on UNIX this is the standard, I feel that ```external``` should allow for prefixing the library, or at least provide raise a more relevant error when the user tries to load a library with the wrong functions naming.

P.S. Please note that that "bug", may actually be the intended behavior. Still, it took me some time to figure out especially because the error reported is unrelated to be actual problem.

Thanks for the library! :)

**Comment by jgillis** [comment]
Hi!

Thanks for your feedback on our project.

I take it that you observe the crash if you replace `Function f("libf",...)` to `Function f("f",...)`, right?
This has been fixed in develop branch earlier.
One now gets the following (hopefully helpful) error message:
```
terminate called after throwing an instance of 'casadi::CasadiException'
  what():  .../casadi/core/function_internal.cpp:140: Error calling External::init for 'libf':
.../casadi/core/external.cpp:235: Assertion "any_symbol_found()" failed:
Could not find any function/symbol starting with 'libf_'. Make sure to read documentation of `external()` for proper usage.
```
