### ISSUE TITLE
Using C++ SXFunction from Python

### ISSUE THREAD

**Issue by alaurenzi** [casadi/casadi#2462]
Hi all,
suppose I have a casadi Function written in C++ and it is way too complex to be ported to Python.
Is there a way to still include the function in Casadi when used from Python (and being able to still compute derivatives)?

I've tried the code generation option, but it seems derivatives are not supported?

Thanks,
Arturo

**Comment by jgillis** [comment]
Derivatives are supported in code-gen, but this is not so well documented.
You may follow the recommendations in https://groups.google.com/forum/#!topic/casadi-users/bFTIg2tYgVs
