### ISSUE TITLE
dot product or vecnorm of a column of 3-vectors

### ISSUE THREAD

**Issue by lamont-granquist** [casadi/casadi#2474]
I've got a Nx3 matrix where the rows are 3-vectors and I want to get an Nx1 column vector of the vecnorm or dot product of those vectors with themselves.

In Matlab either:

```
r2 = dot(r,r,2);
```

or:

```
r2 = vecnorm(r,1,2).^2;
```

Both of those don't seem to work, or at least not on SX data types.  There is a dot(x,y) API implemented, but not with the third argument.

It looks like a workaround is:

```
r2 = r(:,1).^2 + r(:,2).^2 + r(:,3).^2;
```

It actually looks like there's another possible bug here as well where `dot(r,r)` in casadi when r is a matrix is working more like `sumsqr(r)` and returning a scalar which isn't what Matlab does.

I don't know if that's a bug or not really, but using casadi via the Matlab interface it is a little surprising...

**Comment by jaeandersson** [comment]
> I don't know if that's a bug or not really, but using casadi via the Matlab interface it is a little surprising...

I wouldn't call it a bug. `dot` is an inner product in CasADi. But I can see that it's confusing.

An alternative way of calculating what you're doing is:

```
r2 = (r .* r) * ones(3, 1)
````
That should be a bit more efficient, especially if you are using the `MX` data type.
