### ISSUE TITLE
xml Parser not working

### ISSUE THREAD

**Issue by stevo4992** [casadi/casadi#2476]
Hello,

I'm trying to parse a .xml File:

ivp = casadi.DaeBuilder()
        ivp.parse_fmi(f"C:/Users/NGRSTG/Desktop/Pycharm/WSO4/casadi_source/Sim_Dampfspeicher.xml")

I'm getting this error:

  File "C:\Users\NGRSTG\Python\Anaconda\lib\site-packages\casadi\casadi.py", line 24003, in parse_fmi
    return _casadi.DaeBuilder_parse_fmi(self, *args)
RuntimeError: Unknown alias

As far, as I understand. python isn't able to import _casadi.pyd

Does anyone know, how to solve this issue?

Best regards,
Stephan

(I installed casadi by extracting it from the .zip-File. The recommended test is working.)

**Comment by jaeandersson** [comment]
`DaeBuilder::parse_fmi` is essentially deprecated by now. How did you create `Sim_Dampfspeicher.xml`? I think `DaeBuilder::parse_fmi` would only work with (probably pretty old) versions of JModelica. If you are looking at ways to import Modelica into CasADi, there should be better ways available by now.

**Comment by jaeandersson** [comment]
For followup, I recommend the forum. There should be people there who know the answer.
