### ISSUE TITLE
cannot use coefficients to generate bspline Function object

### ISSUE THREAD

**Issue by chengdi123000** [casadi/casadi#2477]
# version
win10 64bit
python 3.7.3
cascadi: 3.4.5
# Code 
```python
"""
bspline(str name, [[float]] knots, [float] coeffs, [int] degree, int m, dict opts) -> Function
"""
import casadi as ca

name = 'lut_test'
knots = [[0,3]]
coeffs = [1,1,1] # 
degree = [2] # polynomial degree
m = 1 # dimension

lut= ca.Function.bspline(name,knots,coeffs,degree)
lut(1)
```
# expected output
```python
# (x-0)**3+(x-0)**2+(x-0)
lut(1)=3  
```
# actual output
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-83-f83e334e4f2a> in <module>
      8 m = 1 # dimension
      9 
---> 10 func = ca.Function.bspline(name,knots,coeffs,degree)

~/share/casadi/casadi.py in bspline(*args)
  12953 
  12954         """
> 12955         return _casadi.Function_bspline(*args)
  12956 
  12957     bspline = staticmethod(bspline)

RuntimeError: Error in Function::bspline for 'lut_test' [BSpline] at .../casadi/core/function.cpp:698:
.../casadi/core/function_internal.cpp:124: Error calling BSpline::init for 'lut_test':
.../casadi/core/bspline.cpp:136: Assertion "coeffs_size_==coeffs_.size()" failed:
Expected coefficient size -2, got 4 instead.
```

# comments
I expect to use `PChip` interpolation which is not implemented yet. So I want to use `scipy` to generate coefficients and insert it into `casadi.bspline()` and generate a `Function` object. But I cannot find the correct way to use `casadi.bspline()`. There is no example on this.

I found it is related to this line of code:
https://github.com/casadi/casadi/blob/6b0de13ac78cb59b10e7a7a11d8a96d8fecbf951/casadi/core/bspline.cpp#L122

But I cannot understand because of poor documentation on the definition of variables. I also do not know how to use `gdb` to find what is actually happening in this line of code.

**Comment by chengdi123000** [comment]
I think this line of code should be
```c++
 for (casadi_int i=0;i<degree_.size();++i) coeffs_size_*= (offset_[i+1]-offset_[i]-1)*(degree_[i]+1); 
```
- ` (offset_[i+1]-offset_[i]-1)` is the number of intervals defined by each dimension of knots.
- ` (degree_[i]+1)` is the number of coefficients for a polynomial defined on an interval.

**Comment by jgillis** [comment]
You need a higher multiplicity of the knots at the edges see e.g. De Boor
book.
It's [[0,0,0,3,3,3]] you need iirc.

**Comment by chengdi123000** [comment]
@jgillis OK, I see the problem. This is a `b-spline` implementation rather than `general piecewise polynomial`.  Thank you a lot.
