### ISSUE TITLE
Substitute value of a symbolic variable to evaluate a symbolic expression

### ISSUE THREAD

**Issue by PranjaLBiswas27** [casadi/casadi#2478]
Hi guys,

I am very new to Casadi and have been trying to understand how the basics work. Please bare with me if the question is very trivial :). For now I was trying to evaluate the following symbolic expression:

Casadi Symbolic Framework:
`import casadi.*`
`x = SX.sym('x',1);`
`f = (2*x^2)`
`f = `
`SX((2*sq(x)))`

MATLAB Symbolic Framework:
`syms x`
`f = 2*x^2`
`f =` 
`2*x^2`

Now I want to evaluate the expression `f` by substituing different values of x. In MATLAB I can use `subs(f,{x},{6})`, but I am not able to understand how to do the same in Casadi. 

Please let me know.

Kind Reagrds
Pranjal Biswas

**Comment by jgillis** [comment]
In CasADi, you work with Function objects to evaluate expressions
```
fun = Function('fun',{x},{f});
full(fun(6))
```

You can also do `substitute(f,x,6)`, but it's not recommended to do that for numerical evaluations

**Comment by PranjaLBiswas27** [comment]
Hi @jgillis ,

https://groups.google.com/forum/#!categories/casadi-users : Is this the active forum for Casadi?

Also, while evaluating:
`fun = Function('fun',{x},{f});`

I get the following error:

> No matching function for overload function 'new_Function'.  Possible Matlab usages are:
    Function()
    Function(Function)
You have: char, {SX}, {SX}

How can I solve this issue?

**Comment by jgillis** [comment]
That's correct.

The error doesn't make much sense to me.
Try with the lastest offiical release (3.4.5) on a restarted Matlab.

Please report back if you can't get this to work; if confirmed this would be a fundamentally important issue. I've never seen this code fail

**Comment by PranjaLBiswas27** [comment]
Hi  @jgillis ,

I did try with the latest release 3.4.5 after restarting but I get the same error. Although just to let you know I have, hpipm, blasfeo, MPT3, ForcesPro_v1.8 installed as well. Can the error be related to any conflicts with the?

**Comment by jgillis** [comment]
Can you do:
```
CasadiMeta.git_revision
GlobalOptions.getCasadiPath
```

**Comment by PranjaLBiswas27** [comment]
![Capture](https://user-images.githubusercontent.com/38991742/63605022-667dd180-c5cd-11e9-8f21-c94ec1e32c9e.JPG)


The is what I get.

**Comment by jgillis** [comment]
What does
```
edit SX
```
reveal?
More specifically, what path is shown in the editor?

**Comment by PranjaLBiswas27** [comment]
![Capture](https://user-images.githubusercontent.com/38991742/63605253-d3916700-c5cd-11e9-95f5-bf56affa0936.JPG)

Shows path related to Forces_Pro it seems.

**Comment by jgillis** [comment]
Oh that is new to me. Didn't know they were bundling CasADi..

**Comment by PranjaLBiswas27** [comment]
`edit Function` also shows Forces_Pro directory.

**Comment by jgillis** [comment]
Well in the old CasADi, use SXFunction instead. Maybe do the numerical call with cell arguments, don't remember

**Comment by PranjaLBiswas27** [comment]
`fun = SXFunction('fun',{x},{f});`

Yes, this works, but I cant evaluate using `full(fun{6})`, gives following error:

> Unrecognized method, property, or field 'brace' for class 'casadi.SXFunction'.

> Error in SwigRef/subsref (line 26)           

> [varargout{1:nargout}] = builtin('subsref',self,substruct('.','brace','()',s.subs));

**Comment by PranjaLBiswas27** [comment]
Ahh, `full(fun({6}))` works. Thanks a lot for the help, greatly appreciated.
