### ISSUE TITLE
Matlab interface - conditional method

### ISSUE THREAD

**Issue by EnricaSo** [casadi/casadi#2486]
Hello,
I need to use the ```conditional``` method in Matlab for SX objects. I get the following error:

```
Error using casadi.GenericMatrixCommon/conditional (line 479)
No matching function for overload function 'GenericMatrixCommon_conditional'.  Possible
prototypes are:
    CONDITIONAL(IM,{IM},IM,bool)
    CONDITIONAL(DM,{DM},DM,bool)
    CONDITIONAL(SX,{SX},SX,bool)
    CONDITIONAL(MX,{MX},MX,bool)
  You have: SX, SX, SX, logical
```
However, the boolean type does NOT exist in Matlab. All booleans are logicals. Indeed, if I convert anything to a boolean I get a logical, as follows:
```
boolean(0)

ans =

  logical
```
Any help?

Best,
Enrica

**Comment by jaeandersson** [comment]
You're constructing a symbolic expression. It cannot be converted into a boolean directly. The only way to get a boolean is to use the symbolic expression to define a CasADi function, then evaluate the function to get a numeric value. Please reread the user guide and use the forum for further questions.

**Comment by EnricaSo** [comment]
Hello, thank you for your answer! 
Could you articulate a bit more?

I had already posted a question on the forum, but nobody has replied yet and there is not much activity on it. The documentation of the ```conditional``` function is minimalist and I have several questions left.

In my application, I need to pass a 1-dim SX object as index of a 6-dim SX object. Is there any way of doing it? Is ```conditional``` doing this? If yes, what is the short_circuit doing? There is one is ```if_else``` as well, but its use is optional.

Then, based on what you suggested I've tried the following things, but there is no way I manage to get a boolean out of a function.
```
x = SX.sym('x') ;
f = Function('f',{x},{x});
arg = {1} ;
res = f.call(arg);
conditional(sx_index, sx_vector, sx_vector, res)
```
And I get the error:
```
You have: SX, SX, SX, {DM}
```
Thinking that the problem is the DM structure in input, I extract its content like this ```res{1,1}```
```
conditional(sx_index, sx_vector, sx_vector, res{1,1})
```
And I get the error:
```
You have: SX, SX, SX, DM
```
Cheers,
Enrica

**Comment by EnricaSo** [comment]
Also, the function
```
conditional(sx_index, sx_vector, sx_vector, is_quadratic(x^2,x))
```
according to the doc is returning a ```bool```, but this line gives the following error
```
You have: SX, SX, SX, logical
```

**Comment by jgillis** [comment]
Refering to the original question,
the error message is suggesting the problem is not with the (boolean) fourth argument, but rather with the second argument. It should be a cell of SX expressions `{SX}`.

Here's a usage example:
```
import casadi.*
e_index = SX.sym('index');

x = SX.sym('x');

v = [x^2;x^3];
v_cell = vertsplit(v);

default = 0;
c = conditional(e_index,v_cell,default,false);


% Test 

f = Function('f',{e_index,x},{c});


f(0,3) % 3^2
f(1,3) % 3^3
f(0.5,3) % default
f(-1,3) % default
f(2,3) % default
```
