### ISSUE TITLE
SX-based custom function

### ISSUE THREAD

**Issue by alphaville** [casadi/casadi#2488]
I would like to implement a symbolic function that is defined piecewise and it's not easy to express it in terms of functions such as `casadi.fmin`, `casadi.abs` etc. I went through the documentation of CasADi and saw that it's possible to subclass [Callback](https://web.casadi.org/docs/#subclassing-callback), so I tried the following example:

```python
import casadi.casadi as cs


class MyCallback(cs.Callback):

    def __init__(self, name, opts={}):
        cs.Callback.__init__(self)
        self.construct(name, opts)

    def get_n_in(self): return 1

    def get_n_out(self): return 1

    # Initialize the object
    def init(self):
        print('initializing object')

    # Evaluate numerically
    def eval(self, arg):
        print(arg)
        x = arg[0]
        f = cs.sin(x)
        return [f]
```

However, although I can provide an `MX` to it, CasADi raises an exception if I pass an `SX` as follows:

```python
soc = MyCallback('f')
u = cs.MX.sym("u", 1, 1)
print(soc(u))
```

What I would like to have is a custom implementation of an SX-based function with a custom Jacobian (i.e., I would like to be able to define a function like `casadi.norm_2`, which I will then be able to compose with other functions, combine with other symbols and compute Jacobians).

To be more specific, I would like to implement the squared distance to a second-order cone, which has a gradient. I then need to construct functions of the form `f(x) = dist_C^2(F(x))`, where `F` is a smooth mapping `F:R^n --> R^m`, and be able to compute the gradient of `f` wrt `x`.

**Comment by jgillis** [comment]
Duplicate of #1869 
iirc, you use CasADi through codegen. The overhead that MX entails wrt to SX typically disappears with codegen.

**Comment by alphaville** [comment]
@jgillis Thanks so much for your quick reply. Actually I figured out that I can do the following in Python:

```python
x = cs.SX.sym('x', 3)
r = cs.SX.sym('x', 1)
normx = cs.norm_2(x)

# First branch
condition1 = cs.norm_2(x) <= r
fun1 = 0

# Second branch
condition2 = r <= -cs.norm_2(x)
fun2 = normx**2 + r**2

# Thrird branch
condition3 = (-cs.norm_2(x) < r) * (cs.norm_2(x) > r)
fun3 = (1 - (1*normx + r)/2 * (1/normx))**2 * normx**2

# Function defined piecewise
y = condition1*fun1 + condition2*fun2 + condition3*fun3

print(cs.substitute(cs.substitute(y, x, [5, -10, 0]), r, 5))
print(cs.jacobian(y, x))
```

I'll close the issue now. Indeed, I use casadi to compute Jacobians and then generate code. Do you think I should rather switch to the more general `MX` instead of `SX`?
