### ISSUE TITLE
Feature request: piecewise polynomial support in interpolation

### ISSUE THREAD

**Issue by chengdi123000** [casadi/casadi#2489]
polynomial interpolation has been implemented in cascadi with two variants:
1. linear
2. spline
However, there is another widely used variant: piecewise polynomial (PP), which is not well supported in casadi. PP can be generated by many `matlab` or `scipy` functions such as `pchip`. And it is relatively easy to evaluate. 

Another problem is it is very difficult to convert PP coefficients to spline coefficients and use existing code to generate spline interpolators. 

Although the PP form evaluation can also be implemented using `if_else` and SX expressions, the expression is complex and ugly.

Some one metioned the potential non-smoothness problem. I think it is user's responsibility to generate a smooth enough PP.

**Comment by jgillis** [comment]
CasADi 3.5 allows you do cook up this functionality yourself:

```python
from casadi import *



# Piecewise-linear
x = MX(DM([1,3,7,8]))

# Between 1 and 3: 0+v+v**2
# Between 3 and 7: 3-v-v**2
# Between 7 and 8: 4*v**2
y = MX(DM([[0,3,0],[1,-1,0],[1,-1,4]]))

n = y.shape[0]

v = MX.sym("v")

L = low(x,v)


coeff = y[:,L]

res = dot(coeff,v**DM(range(n)))

f = Function('f',[v],[res])


for ve in [0,1,2,3,4,7,7.5,8,8.5]:
  print(ve, f(ve), [0+ve+ve**2,3-ve-ve**2,4*ve**2] )
```

I'd be happy to let you write a guest blog-post on it if you polish this up and illustrate it with a nice example..

**Comment by JasonZhou404** [comment]
I believe "low(x, v)"  is undocumented. I was stuck on looking for a CasADi version's "std::lower_bound" for value query ... Thanks

**Comment by jgillis** [comment]
It is. I didn't realize std::lower_bound exists, good to know! I'll adopt that for our api
