### ISSUE TITLE
Single-output MX-based function has two outputs after code generation

### ISSUE THREAD

**Issue by alphaville** [casadi/casadi#2492]
I need some help to understand the API of the auto-generated C code of CasADi. If I run,

```python
u = cs.SX.sym("u", 5)
p = cs.SX.sym("p", 2)
f = p[0] + p[1] * cs.dot(u, u)
F = cs.Function('F', [u, p], [f])
F.generate()
```

I obtain a C function (file `F.c`) with two input arguments and one output argument. Indeed, at the end of `F.c` we see

```c
if (sz_arg) *sz_arg = 2;
if (sz_res) *sz_res = 1;
```

However, if I use `MX` instead of `SX`, I obtain a function with four input arguments and two output arguments:

```c
if (sz_arg) *sz_arg = 4;
if (sz_res) *sz_res = 2;
```

I went through the documentation, but I wasn't able to find any explanation. Thanks a lot in advance.

**Comment by jgillis** [comment]
sz_arg/res is not just the space for input/outputs, but also sratch working space for the algorithm

**Comment by alphaville** [comment]
@jgillis Does it suffice to do something like this?

```c
// first obtain sz_arg, sz_res, sz_iw and sz_w and then do
casadi_real ** arg = malloc(sz_arg*sizeof(casadi_real*));
casadi_real ** res = malloc(sz_res*sizeof(casadi_real*));
casadi_real * work = malloc(sz_w*sizeof(casadi_real));
casadi_int * iwork = malloc(sz_iw*sizeof(casadi_int));
arg[0] = x1; // first input argument
arg[1] = x2; // second input 
res[0] = y; // output
F(arg, res, iwork, work, (void*) 0);
```

Or do I need to allocate memory for `arg[2]`, `arg[3]`, etc. In the above snippet, `arg[2][0]` is not a valid memory position.

 I also wanted to ask you about `mem`. I read in the [documentation](http://casadi.sourceforge.net/v3.4.4/users_guide/casadi-users_guide.pdf) that this needs to be allocated using `fname_alloc_mem`, but I don't have such a function in my auto-generated code. Is it safe to provide `(void*) 0`?

**Comment by jgillis** [comment]
It suffices. No need to touch arg[2] and beyond.

0 is safe for now: in 3.4, there's not a single instance of codegen using mem (=thread-local memory)
