### ISSUE TITLE
Using qpoases with the opti stack

### ISSUE THREAD

**Issue by bemilio** [casadi/casadi#2493]
Hello to the Casadi team, 

I tried to call qpoases on an optimization problem formulated through the Opti stack on MATLAB

` opti.solver('snopt'); 
sol = opti.solve(); `

This gives as output the following error:

> Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:159:
.../casadi/core/plugin_interface.hpp:387: Plugin 'qpoases' is not found. 

However, if I call `qpoases` without the `Opti` stack:

` S = casadi.qpsol('S', 'qpoases', qp) `

it works. Is `qpoases` supported on the Casadi Opti stack?

Thanks for the help.

**Comment by jgillis** [comment]
`Opti('conic')` in develop branch. Soon in release 3.5 ..

**Comment by DoanNguyenTrong** [comment]
Hi @jgillis 
The latest version now is 3.5.2 so is the feature released?
If yes, can you please tell me how can I config the `opti.solver()` to make it works with `qpoases` ?
Thank you.

**Comment by jgillis** [comment]
```
opti=Opti('conic')
...
opti.solver('qpoases')
```
