### ISSUE TITLE
MATLAB serialize/deserialize

### ISSUE THREAD

**Issue by pizzooid** [casadi/casadi#2500]
Hi there,
great software package! It helps a lot. 👍 

Sadly the serialize function is not documented in MATLAB.
How can it be used?
when trying:
```matlab
import casadi.*;
serializer = casadi.StringSerializer();
x = MX.sym('x', 1);
serialize(x, serializer)
```
it outputs
```
Error using casadi.MX/serialize (line 599)
No matching function for overload function 'MX_serialize'.  Prototype:
    SERIALIZE(self,casadi::SerializingStream &)
  You have: MX, StringSerializer

Error in Untitled2 (line 4)
serialize(x, serializer)
```
I see no way to get a SerializingStream inisde MATLAB, do you know a way?

Best Pietro

**Comment by jgillis** [comment]
Unfortunately did not find time to update the user guide.

Matlab example:
```matlab
import casadi.*;
serializer = casadi.StringSerializer();
x = MX.sym('x', 1);
serializer.pack(x);

str = serializer.encode();

deserializer = casadi.StringDeserializer(str);
xx = deserializer.unpack();
```

Note that, I you just stick to CasADI Function, you can make use of `fun.save` and `Function.load` or use Matlab built-in 'save' and 'load'

**Comment by pizzooid** [comment]
Perfect, thank you!
