### ISSUE TITLE
MacOS 10.15 segfault

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2502]
https://groups.google.com/d/msgid/casadi-users/882e9f56-4923-4ab2-9142-821a567cd964%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jgillis** [comment]
Fixed by switching to conda-forge 'c-compiler', 'cxx-compiler','fortra-compiler' for building

**Comment by mstoelzle** [comment]
Hi @jgillis,

I am using casadi on macOS catalina and I also getting the segmentation error when importing the casadi module:
`zsh: segmentation fault  python handler.py simulate --controller_id  --launch_environment_id    --plot`
Could you give me some advice how to fix this?
Thanks!

**Comment by jgillis** [comment]
Which version of CasADi? This was supposed to be fixed in recent releases..

**Comment by mstoelzle** [comment]
I installed casadi 3.5.3 through pip for Python 3.7

**Comment by jgillis** [comment]
Can you share a script to reproduce?

**Comment by jgillis** [comment]
Probably this was fixed only for Matlab

**Comment by mstoelzle** [comment]
```
import do_mpc as dm
import casadi as cd
```
However, I am not completely sure if its easily reproducible, as a collegue of mine does not have the problem with a different macBook

**Comment by jgillis** [comment]
Would you please test with these binaries (https://github.com/casadi/binaries/releases/tag/commit-05cb45b)?
They are based on 3.5.3 source code but the build system was switched like in the matlab fix..

**Comment by mstoelzle** [comment]
@jgillis I just tried it: It works perfectly with this binary! It seems to fix the issue. When do you expect this fix to be released?

**Comment by jgillis** [comment]
I did a 3.5.4 release with the fixes
I hope you can confirm that it works..

**Comment by mstoelzle** [comment]
@jgillis Its fixed and it works! Thanks a lot
