### ISSUE TITLE
Python2 syntax for vertcat

### ISSUE THREAD

**Issue by Fangwq** [casadi/casadi#2507]
Hi, I have a question for vertcat. How to use it with Python2.7 ? A problem appears in the following code. `ca.vertcat(*con_eq, *con_ineq)` is wrong where `con_eq` and `con_ineq` are all list type objects.  But `ca.vertcat(*con_eq)` or  `ca.vertcat(*con_ineq)` are all right.  How to solve this problem? Thank you very much!

**Comment by jaeandersson** [comment]
There is no overload to take two lists. Combine the lists before calling vertcat: `ca.vertcat(*(con_eq + con_ineq))`

**Comment by Fangwq** [comment]
It works, thank you very much!
