### ISSUE TITLE
Bug in Overhead-less CasADi Function evaluation API

### ISSUE THREAD

**Issue by ichumuh** [casadi/casadi#2510]
I've been trying out the fast new function evaluation API of `3.5.1`, but it seems to be buggy.
This small script loads my function that produces the bug. 
```
from casadi import *

A_ = np.random.random(1244)
B_ = np.zeros((126,66))

C = Importer('non_square.c', 'clang')
f = external('f', C)

[buf,f_eval] = f.buffer()
buf.set_arg(0, memoryview(A_))
buf.set_res(0, memoryview(B_))

f_eval()

B2_ = np.array(f(A_))
np.testing.assert_array_almost_equal(B_, B2_)
```
This zip contains `non_square.c`:
[example_function.zip](https://github.com/casadi/casadi/files/3762189/example_function.zip)
`B_` seems to contain the correct numbers, but they are placed in the wrong positions.
The result in `B2_` is correct, though.
Am I doing anything wrong or is this a bug?

**Comment by jgillis** [comment]
Note that the memoryview is interpreted by casadi in fortran order. C order is the default for numpy

**Comment by ichumuh** [comment]
Does that mean I'm supposed to do something like this?
```
A2_ = np.asfortranarray(A_)
B_ = np.asfortranarray(np.zeros((126,66)))
C = Importer('non_square.c', 'clang')
f = external('f', C)
[buf,f_eval] = f.buffer()
buf.set_arg(0, memoryview(A2_))
buf.set_res(0, memoryview(B_))
f_eval()
```
It does change the order, but it still doesn't match `B2_`.

**Comment by ichumuh** [comment]
I've modified your test https://github.com/casadi/casadi/commit/3e9919e9195e8f057d09cd9bcc4f7fa59e6fc104#diff-ad1e1bf2c8d8bef2a0f3b3b85331ffd0R2491
```
from casadi import *

A_ = np.random.random(16)
B_ = np.zeros((4, 4))

A = SX.sym("A", 4, 4)

f = Function("f", symvar(A), [A * 10])

[buf, f_eval] = f.buffer()
buf.set_arg(0, memoryview(A_))
buf.set_res(0, memoryview(B_))

f_eval()

B2_ = np.array(f(*A_))

np.testing.assert_array_almost_equal(B_, B2_)
```
The bug seems to happen, when I supply the parameter as an array instead of a matrix, like you are doing in the test.
Result:
```
Mismatch: 93.8%
Max absolute difference: 8.82787767
Max relative difference: 1.
 x: array([[6.424581, 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ]])
 y: array([[6.424581, 0.666208, 6.38774 , 2.390392],
       [4.098594, 2.731696, 3.032018, 5.145338],
       [0.864777, 6.299823, 2.938484, 8.827878],
       [4.242389, 1.074266, 7.116173, 2.670604]])
```

**Comment by ichumuh** [comment]
I think I found an example
```
from casadi import *

def buggy():
    m = SX.sym('m', 3,3)
    m[:2,:2] = SX.eye(2)

    A_ = np.ones(len(symvar(m)))
    AF_ = np.asfortranarray(A_)
    BF_ = np.asfortranarray(np.zeros(m.shape))

    f = Function('f', symvar(m), [m])
    [buf, f_eval] = f.buffer()
    for i in range(len(symvar(m))):
        buf.set_arg(i, memoryview(AF_))
    buf.set_res(0, memoryview(BF_))

    f_eval()

    B2_ = np.array(f(*A_))
    np.testing.assert_array_almost_equal(BF_, B2_)

def not_buggy():
    m = SX.sym('m', 3,3)
    m[0,0] = 1
    m[0,1] = 0
    m[1,0] = 0
    m[1,1] = 1

    A_ = np.ones(len(symvar(m)))
    AF_ = np.asfortranarray(A_)
    BF_ = np.asfortranarray(np.zeros(m.shape))

    f = Function('f', symvar(m), [m])
    [buf, f_eval] = f.buffer()
    for i in range(len(symvar(m))):
        buf.set_arg(i, memoryview(AF_))
    buf.set_res(0, memoryview(BF_))

    f_eval()

    B2_ = np.array(f(*A_))
    np.testing.assert_array_almost_equal(BF_, B2_)

buggy()
not_buggy()
```
It happens when I overwrite part of the matrix with `SX.eye`. When I directly assign the 1 and 0 it works.

**Comment by jgillis** [comment]
I think your issue is related to sparsity.
What happens at `f_eval()` is that the structural nonzeros are written into the memoryview in fortran order.
Suggest trying `f = Function('f', symvar(m), [densify(m)])` for the `buggy` case

**Comment by jgillis** [comment]
Depends on your point-of-view :-)

Best is to document current behavior, and have a variant (e.g. `f.buffer(true)`) that does the densify itself.
