### ISSUE TITLE
Select minimum out of an MX matrix and assign it as a constraint

### ISSUE THREAD

**Issue by moo-ops** [casadi/casadi#2514]
I am trying to find a point in an array which has the minimum distance to a state. I want to do it in a matrix calculation instead of looping to have a reasonable run time. 
I calculated the distance from the state to each point in the array in a matrix equation and then I used casadi mmin() to get minimum and use it as a constraint but I got the following error:

RuntimeError: Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:159:
.../casadi/core/function_internal.cpp:124: Error calling IpoptInterface::init for 'solver':
Error in Function::factory for 'nlp' [MXFunction] at .../casadi/core/function.cpp:1449:
Failed to create nlp_grad:[x, p, lam:f, lam:g]->[f, g, grad:gamma:x, grad:gamma:p] with {"gamma": [f, g]}:
.../casadi/core/factory.hpp:346: Gradient generation failed:
Error in MX::gradient at .../casadi/core/generic_matrix.hpp:1192:
Error in MX::jtimes at .../casadi/core/generic_matrix.hpp:1181:
Error in MX::reverse at .../casadi/core/mx.cpp:1676:
Error in MXFunction::ad_reverse at .../casadi/core/mx_function.cpp:1001:
Error in MX::ad_reverse for node of type N6casadi4MMinE at .../casadi/core/mx.cpp:1860:
.../casadi/core/mx_node.cpp:311: 'ad_reverse' not defined for class N6casadi4MMinE

**Comment by rowandempster** [comment]
Hey @moo-ops, I have the same application: Discretized occupancy grid environment with 25,000 cells, and I want to find the minimum distance in the cell vector to a symbolic state efficiently. Wondering if you arrived at some solution here?

**Comment by jgillis** [comment]
Perhaps smooth max is of use here:

http://erikerlandson.github.io/blog/2018/05/28/computing-smooth-max-and-its-gradients-without-over-and-underflow/

**Comment by rowandempster** [comment]
I'd be happy to try it out if a python implementation exists!

**Comment by rowandempster** [comment]
Posted a complete description of my problem setting and implementation variants I have tried here: https://groups.google.com/g/casadi-users/c/rEkSwnq9uG8/m/qRXd0oHkAQAJ

**Comment by jgillis** [comment]
AD rules have been added in #2043
logsumexp is underway #2893
