### ISSUE TITLE
Calling CasADi to generate derivatives...(if errors occur here, please use codeoptions.nlp.lightCasadi = 1)

### ISSUE THREAD

**Issue by lebronze** [casadi/casadi#2516]
i tried to use casadi3.5.1 in matlab2017b. And run the example 
`addpath('<yourpath>/casadi-matlabR2014a-v3.5.1')
import casadi.*
x = MX.sym('x')
disp(jacobian(sin(x),x))`
The result is cos(x).
However when i use casadi in my code, error comes.
"Calling CasADi to generate derivatives...(if errors occur here, please use codeoptions.nlp.lightCasadi = 1)" class casadi,CasadiMeta doesn't have 'getVersion'

The problem is i don't know where to set  codeoptions.nlp.lightCasadi = 1.
Please help me.

**Comment by jgillis** [comment]
Hi there!

This error message is not coming from CasADi itself but from some other package that uses CasADi internally. Figure out what version of CasADi is needed, and use that instead..
