### ISSUE TITLE
IPOPT interface with equality and non-equality constraints

### ISSUE THREAD

**Issue by junzengx14** [casadi/casadi#2538]
Hello, I went through the technical documents about implementing nlp problem with ipopt using casadi as interface. I'm wondering whether we could distinguish the equality and non-equality constraints in the nlp formulation? Currently, the answer looks like no to me but I would like to hear the notes from you guys.

Great thanks!

**Comment by jaeandersson** [comment]
If you set upper and lower bound equal, both the interface and IPOPT itself will treat it as an equality constraint. The same goes for other solvers.
