### ISSUE TITLE
Incorrect objective value calculation in nlpsol() with IPOPT

### ISSUE THREAD

**Issue by janismac** [casadi/casadi#2542]
Attached you can find a reproducible example where CasADi/IPOPT calculates inconsistent objective values. When substituting the "x" solution from IPOPT into the original objective function, it produces a value that is significantly different from the "f" output from IPOPT.

[casadi_issue.zip](https://github.com/casadi/casadi/files/4053102/casadi_issue.zip)

The problem occurs with IPOPT+MUMPS and IPOPT+MA57, but not with WORHP. So it likely a bug in IPOPT or the CasADi/IPOPT interface.

Environment:

    Windows 10
    MATLAB Version: 9.6.0.1072779 (R2019a)
    casadi-windows-matlabR2016a-v3.5.1

EDIT, the problem also occurs in v3.4.5. I could not test earlier versions due to MEX incompatibility.

The test script:

    load('report.mat')
    x_sym = casadi.SX.sym('x', size(x0,1), size(x0,2));
    p_sym = casadi.SX.sym('p', size(p,1), size(p,2));
    [f_sym, g_sym] = nlp_fn(x_sym,p_sym);

    nlpsolver = casadi.nlpsol('nlpsolver', 'ipopt', ...
        struct('x', x_sym, 'f', f_sym, 'g', g_sym, 'p', p_sym));

    soln = nlpsolver('x0',x0,'lbg',lbg,'ubg',ubg,'lbx',lbx,'ubx',ubx,'p',p);

    [f_soln, g_soln] = nlp_fn(soln.x,p);

    % These should be zero!
    error_f = full(soln.f - f_soln);
    error_g = full(soln.g - g_soln);

    fprintf('Absolute error f: %e\n', abs(error_f));
    fprintf('Relative error f: %e\n', abs(error_f)/abs(full(f_soln)));

    fprintf('Absolute error g: %e\n', max(abs(error_g)));
    fprintf('Relative error g: %e\n', max(abs(error_g))/max(abs(full(g_soln))));

The output:

    This is Ipopt version 3.12.3, running with linear solver mumps.
    NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

    Number of nonzeros in equality constraint Jacobian...:        0
    Number of nonzeros in inequality constraint Jacobian.:    21216
    Number of nonzeros in Lagrangian Hessian.............:     5257

    Total number of variables............................:     2797
                         variables with only lower bounds:     1980
                    variables with lower and upper bounds:      721
                         variables with only upper bounds:        0
    Total number of equality constraints.................:        0
    Total number of inequality constraints...............:     1980
            inequality constraints with only lower bounds:        0
       inequality constraints with lower and upper bounds:        0
            inequality constraints with only upper bounds:     1980

    iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
       0 1.6711284e+006 4.78e-002 5.94e+001  -1.0 0.00e+000    -  0.00e+000 0.00e+000   0
       1 7.0722325e+005 4.87e-002 3.61e+001  -1.0 1.33e+000    -  6.30e-001 1.43e-002f  1
       2 1.8540837e+005 1.08e-001 2.01e+001  -1.0 6.48e-001    -  3.47e-001 9.38e-001f  1
    [...]
      91 9.5836838e+002 8.21e-010 1.68e-007  -8.6 7.68e-005  -2.7 1.00e+000 1.00e+000h  1
      92 9.5836838e+002 4.42e-011 1.47e-007  -8.6 2.51e-005  -2.2 1.00e+000 1.00e+000h  1
      93 9.5836838e+002 3.56e-010 1.02e-007  -8.6 5.24e-005  -2.7 1.00e+000 1.00e+000h  1

    Number of Iterations....: 93

                                       (scaled)                 (unscaled)
    Objective...............:  9.5836837760934146e-001   9.5836837760934145e+002
    Dual infeasibility......:  1.0221225192446937e-007   1.0221225192446938e-004
    Constraint violation....:  3.5631083618534825e-010   3.5631083618534825e-010
    Complementarity.........:  2.5059035635161938e-009   2.5059035635161937e-006
    Overall NLP error.......:  1.0221225192446937e-007   1.0221225192446938e-004

    Number of objective function evaluations             = 153
    Number of objective gradient evaluations             = 94
    Number of equality constraint evaluations            = 0
    Number of inequality constraint evaluations          = 153
    Number of equality constraint Jacobian evaluations   = 0
    Number of inequality constraint Jacobian evaluations = 94
    Number of Lagrangian Hessian evaluations             = 93
    Total CPU secs in IPOPT (w/o function evaluations)   =      3.466
    Total CPU secs in NLP function evaluations           =      2.574

    EXIT: Solved To Acceptable Level.
       nlpsolver  :   t_proc      (avg)   t_wall      (avg)    n_eval
           nlp_f  |  15.00ms ( 98.04us)  15.62ms (102.10us)       153
           nlp_g  | 107.00ms (699.35us) 109.33ms (714.56us)       153
        nlp_grad  |        0 (       0)        0 (       0)         1
      nlp_grad_f  |  15.00ms (157.89us)  15.62ms (164.46us)        95
      nlp_hess_l  |   1.84 s ( 19.81ms)   1.83 s ( 19.71ms)        93
       nlp_jac_g  | 611.00ms (  6.43ms) 609.19ms (  6.41ms)        95
           total  |   6.04 s (  6.04 s)   6.04 s (  6.04 s)         1
    Absolute error f: 1.634983e+00
    Relative error f: 1.703101e-03
    Absolute error g: 1.696936e-07
    Relative error g: 2.149053e-08
    >>

**Comment by jgillis** [comment]
Confirmed

**Comment by jgillis** [comment]
Fixed with:

```matlab
options.bound_consistency=false;
options.ipopt.bound_relax_factor=0;
options.ipopt.honor_original_bounds='no';
```
