### ISSUE TITLE
veccat([]) -> Sparsity instead of MX

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2549]

**Comment by jgillis** [comment]
But what if we want SX?
Is DM a useful common ground?

**Comment by jgillis** [comment]
The following passes:
```python
    f = Function('f',[DM(0,1)],[])
    print(f)
    f = Function('f',[DM(0,1),SX.sym("x")],[])
    print(f)
    f = Function('f',[DM(0,1),MX.sym("x")],[])
    print(f)
```
So DM makes sense

**Comment by jgillis** [comment]
Check if C++ variants match up

**Comment by jgillis** [comment]
`veccat`, `vertcat`, `horzcat`, `diagcat` should all fall back to DM when receiving empty arguments.

**Comment by jgillis** [comment]
Do we give shape `(0,1)` also to `vertcat`, `(1,0)` to `horzcat` and `(0,0)` to diagcat? Or just in the case of `veccat`?

**Comment by jgillis** [comment]
Matlab?

**Comment by jaeandersson** [comment]
Yeah, why would we want to cast [] to Sparsity?

**Comment by jaeandersson** [comment]
Nevermind, I get it now. I think you can solve it by modifying the casting priorities in SWIG. They decide in which order checks are made. Sparsity should have lower priority than DM. MATLAB uses the same typemaps

**Comment by jgillis** [comment]
Changing casting priorities is opening a can of worms. `vertcat(spA,spB)` would then return type `DM` because of (possibly dubious) upconversion in our SWIG.

**Comment by jaeandersson** [comment]
I don't think we should cast Sparsity to DM. Isn't that constructor explicit?
