### ISSUE TITLE
Adapt symbolic cost function after minimize()

### ISSUE THREAD

**Issue by meydan87** [casadi/casadi#2557]
Hey guys,

I'm trying to set up a static casadi object with a symbolic costs function (parameter or variable) in order to be able to change the input for the costs each loop without recreation of the opti object.
A part of the cost function itself is symbolic and i don't want to change the cost function over the whole lifetime of the casadi object instead i only want to change some input parameters. Is this even possible ? 
I am pretty new to this topic. So if this is a dumb question, feel free to answer anyway ;)

Thx

**Comment by jgillis** [comment]
With `opti.parameter` you can have numerical values in your cost function that get updated after initialization,
but the structure should be baked.

If you need the structure to be flexible as well, and if you have a finite set of structures, you could enumerate them all with `conditional`.
