### ISSUE TITLE
Application of casadi to battery modelling

### ISSUE THREAD

**Issue by tinosulzer** [casadi/casadi#2566]
I don't know how actively you are looking to publicize applications of casadi, but just letting you know we have just release v0.2 of our battery modelling software [PyBaMM](https://github.com/pybamm-team/PyBaMM) which now relies quite heavily on casadi to do some of the heavy lifting. Great job (and thank you) by the way, the DAE solver is super fast!

**Comment by jgillis** [comment]
Thanks for reaching out to us with this application!

We should probably publicize a bit indeed, I've initiated a success stories page ( https://github.com/casadi/casadi/wiki/Success-stories )

**Comment by Mathadon** [comment]
Could add taco (https://www.tandfonline.com/doi/full/10.1080/19401493.2018.1498537) and JModelica too.
