### ISSUE TITLE
swig error: Unrecognized option -matlab

### ISSUE THREAD

**Issue by andreacarron** [casadi/casadi#2570]
I am trying to install casadi from sources with MATLAB and python support. 
My machine runs Ubuntu 18.04 LTS, I have successfully installed IPOPT and I am able to compile casadi without MATLAB. 

However, when I try to compile casadi with the option for MATLAB I run in the following error when I run make

```
[ 28%] Building CXX object swig/python/CMakeFiles/_casadi.dir/__/casadiPYTHON_wrap.cxx.o
[ 28%] Linking CXX shared module ../../lib/_casadi.so
[ 28%] Built target _casadi
[ 29%] Swig source
swig error : Unrecognized option -matlab
Use 'swig -help' for available options.
swig/matlab/CMakeFiles/casadiMATLAB.dir/build.make:61: recipe for target 'swig/casadiMATLAB_wrap.cxx' failed
make[2]: *** [swig/casadiMATLAB_wrap.cxx] Error 1
CMakeFiles/Makefile2:228: recipe for target 'swig/matlab/CMakeFiles/casadiMATLAB.dir/all' failed
make[1]: *** [swig/matlab/CMakeFiles/casadiMATLAB.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```

The strange thing is that swig supports the matlab option (at least from the help file). To install swig and casadi I followed these [instructions](https://github.com/casadi/casadi/wiki/matlab).

In particular, I run the following steps:

1. Uninstalled swig with `sudo apt-get remove swig`
2. Checked that swig was successfully uninstalled with `which swig`
3. Cloned the repository https://github.com/jaeandersson/swig and check out the branch matlab-customdoc. I have also tried the branch matlab. 
4. Run `sh autogen.sh`
5. `mkdir build`
6. `cd build`
7. `../configure`
8. `make`
9. `sudo make install`
10. Cloned casadi in a different folder
11. `mkdir build`
12. `cd build`
13. `cmake -DWITH_PYTHON=ON -DWITH_IPOPT=ON -DWITH_HSL=ON -DWITH_OPENMP=ON -DWITH_PYTHON3=ON -DWITH_MATLAB=ON -DWITH_DEEPBIND=ON ..`
14. `make` and then i run the aforementioned error

Thanks for the support!

**Comment by jgillis** [comment]
This is probably caused by cmake picking up the wrong swig, or keeping alive an earlier cached reference to swig.
`rm CMakeCache.txt` and `export PATH=<swig_install_dir>/bin:<swig_install_dir/share:$PATH`
