### ISSUE TITLE
Can't we use expm on SX matrix?

### ISSUE THREAD

**Issue by GPrathap** [casadi/casadi#2579]
Can't we use expm on SX matrix? if not any alternative for this?

```
 File "/usr/local/lib/python2.7/dist-packages/casadi/casadi.py", line 21563, in expm
    return _casadi.expm(*args)
RuntimeError: .../casadi/core/matrix_impl.hpp:2263: 'solve' not defined for SX
```

**Comment by jgillis** [comment]
Hi there.

See https://github.com/casadi/casadi/wiki/FAQ:-how-to-resolve-'eval_sx'-not-defined%3F

**Comment by GPrathap** [comment]
I did actually, you would have missed it, https://groups.google.com/forum/#!category-topic/casadi-users/kMz3YUKAFXc 

Anyway, thanks
