### ISSUE TITLE
Wrong derivative for "cosh"

### ISSUE THREAD

**Issue by simdens** [casadi/casadi#2585]
Casadi is using the wrong derivative for "cosh" function. Casadi uses 
dcosh(x)/dx = -sinh(x)
which is not correct. The correct derivative would be:
dcosh(x)/dx = sinh(x)

The bug is in file "core/calculus.hpp":
`    template<typename T> static inline void der(const T& x, const T& f, T* d) { d[0] = -sinh(x); }`
must be changed to
`    template<typename T> static inline void der(const T& x, const T& f, T* d) { d[0] =  sinh(x); }`

**Comment by jgillis** [comment]
:man_facepalming:
Seems to be wrong for 9 years.. Thx for notifying!
https://github.com/casadi/casadi/commit/19d03fdf3e6e12d096aa303dfd67a04ff031de2d#diff-41dacf74842d755e3f835ca4830f79bbR445

**Comment by isakhammer** [comment]
This bug gets the award for winning the hide-and-seek contest

**Comment by michaelhb** [comment]
Thanks for uncovering this - I'm working on a physics code which needs this derivative, and probably wouldn't have figured out what was wrong without this bug report. 

I'm eventually hoping to release the code, so I would vote for giving this a high priority in the next public version :)
