### ISSUE TITLE
Could lookup-table be used in ode functions 

### ISSUE THREAD

**Issue by phystry** [casadi/casadi#2586]
erro log in matlab
.../casadi/core/function_internal.cpp:1821: 'eval_sx' not defined for BSplineInterpolant

my ode function :
**fdhdp = casadi.interpolant('fdhdp','bspline',{ygrid},dhdp/1000);**
states = [tx;dv;v;Tx];
rhs = [ 1;
    1;
    1;
    **-fdhdp(Tx)**
    ]; 
f = Function('f',{states},{rhs});

**Comment by jgillis** [comment]
Hi there.

I've added a FAQ entry to adress your question: https://github.com/casadi/casadi/wiki/FAQ:-how-to-resolve-'eval_sx'-not-defined%3F
