### ISSUE TITLE
C++ documentation outdated

### ISSUE THREAD

**Issue by mohamdev** [casadi/casadi#2590]
Hello everyone :),

First, I want to thank you for the project, it's really great and helpful especially on Python interface.
Now i'm trying to use it on C++, and trying to follow the tutorials here : http://casadi.sourceforge.net/v1.6.1/api/html/dd/d81/chapter3.html

My issue is that the documentation is pretty outdated, and all I need for the moment is to be able to create a scalar, a vector or a matrix containing symbolic variables. That is all I need but I cant find how to do It. Could you tell me in where to take a look ? or how to create a symbolic vector or matrix ? 
I'm really sorry if my question seems stupid. Thank you for your feedback :)

**Comment by jgillis** [comment]
Bottom of docs.casadi.org has a table with syntax comparisons

**Comment by mohamdev** [comment]
Great !! Thank you so much, I didnt see it x) have nice day
