### ISSUE TITLE
More docs for Opti stack in python

### ISSUE THREAD

**Issue by ritou11** [casadi/casadi#2591]
The existing docs only contain basic usage guide for `Opti()`. It will be nice if more docs are provided for Opti stack, especially for `to_function` and `options`.

**Comment by borlum** [comment]
I would love this aswell; especially regarding `to_function`. I stumbled upon `options` for `to_function` but have no idea what I can specify. I am especially in need of a solution to also have my CasADi function with embedded solver also output a return status of some sort (if I could get the entire `opti.stats` I would over the moon:moon: -- but just a way of checking whether an optimal solution was indeed found would be perfect...)

**Comment by jgillis** [comment]
Also add `conic`.

**Comment by jgillis** [comment]
I'll be adding the docs soon. Stats is unfortunately not possible yet. Solver failure should raise a catchable error when you specificy `error_on_fail` as solver argument.
