### ISSUE TITLE
Ipopt option setting for Opti stack in Matlab

### ISSUE THREAD

**Issue by junzengx14** [casadi/casadi#2593]
I would like to set a custom `max_iter` in ipopt option for using Opti stack in Matlab, however I cannot find any documentations in the casadi docs. Could you share some instructions for that? I only found documentation for c++ and python.

Thank you!!!

**Comment by jgillis** [comment]
If you in the chapter on opti stack on the user guide (docs.casadi.org) you'll find the exact 'max_iter' case used as example

**Comment by junzengx14** [comment]
Oh great! Sorry for just missing them, I'm closing this issue.
