### ISSUE TITLE
Casadi solver does not run when the cost function "J" includes a power exponent

### ISSUE THREAD

**Issue by sespirio** [casadi/casadi#2596]
Hello,

I am trying to solve an optimization problem in which the objective function looks like this: 

`trial = ca.mtimes(g_fea_cons1.T, lam_cons1)`
`J = - (Et_cf / tf) + trial**2`

However, when I run the solver, it does not show any outcome or error, it simply gets stuck trying to do "something" infinitely. 

In debug mode, when building the problem, I can corroborate the dimensions of the variables:
g_fea_cons1.T : (1, 1024)
lam_cons1 : (1024, 1)
trial : (1, 1)
Et_cf : (1, 1)
tf : (1, 1)
J : (1, 1)

Therefore, I can discard the option that there is a mistake in the dimensions used. In fact, the solver runs well if I use `J = - (Et_cf / tf) + trial**1` but not if I use another exponent such as ^2, which is actually what I want to do.  Thus, I do not think there is an issue in other parts of the solver set up. It seems that by some reason Casadi does not want to work with a power exponent in the objective function. Why could be that? Any ideas on how to solve it?

Thanks in advance.

Sebastián

**Comment by jgillis** [comment]
Hi Sebastian,

This must be an issue with your problem formulation in connection to the solver backend (IPOPT?).
We use power-of-two a lot in diverse applications; the CasADi machinery itself has no issue with it.

Please re-open with a minimal failing example if need be.
