### ISSUE TITLE
Incorrect result of Function::jac()

### ISSUE THREAD

**Issue by alaurenzi** [casadi/casadi#2597]
Hi all, and thank you for the amazing library. I am however experiencing an issue with the `jac()` function. See the example below:

```python
import casadi
import numpy as np

x = casadi.MX.sym('x', 3)
u = casadi.MX.sym('p', 2)
f = x + casadi.vertcat(u, 0)

F = casadi.Function('f', [x, u], [f], ['x', 'u'], ['f'])
dF = F.jac()
print(dF(x=[0, 0, 0], u=[0, 0]))
dF = F.jacobian()
print(dF(x=[0, 0, 0], u=[0, 0]))
```

This prints
```
{'DfDx': DM(
[[1, 00, 00], 
 [00, 1, 00], 
 [00, 00, 1]]), 'DfDu': DM(
[[00, 00], 
 [00, 00], 
 [00, 00]])}
{'jac': DM(
[[1, 00, 00, 1, 00], 
 [00, 1, 00, 00, 1], 
 [00, 00, 1, 00, 00]])}
```

Notice how the result of `jac` is incorrect, and different from `jacobian` (which is correct). Moreover, swapping the input order to `u, x`, yields the correct result for the `DfDu`, and all zeros for `DfDx`. The second argument is the one showing problems. Am I missing something here?

Thanks in advance,
Arturo

Edit: version information
```
$ pip3 show casadi
Name: casadi
Version: 3.5.1
Summary: CasADi -- framework for algorithmic differentiation and numeric optimization
Home-page: http://casadi.org
Author: Joel Andersson, Joris Gillis, Greg Horn
Author-email: developer_first_name@casadi.org
License: GNU Lesser General Public License v3 or later (LGPLv3+)
Location: /home/arturo/.local/lib/python3.5/site-packages
Requires: 
Required-by: 
```

Edit2: I'll add that `jacobian_old` seems to work ok as well

**Comment by alaurenzi** [comment]
Any hint on this?

**Comment by alaurenzi** [comment]
Just to give an update, version `3.4.5` works fine

**Comment by EnricoMingo** [comment]
Hi all, is there an alternative for the jac() method with the same functionalities?

**Comment by jaeandersson** [comment]
> Hi all, is there an alternative for the jac() method with the same functionalities?

Yes, you probably avoid the `jac()` method as it's mostly an internal method. Try to use the "Function.factory()" function:
```python
J = F.factory('J', ['x', 'u'], ['jac:f:x', 'jac:f:u'])
```
Alternatively, you can just work with expressions:
```python
df_dx = casadi.jacobian(f, x)
F = casadi.Function('jacfcn', [x, u], [df_dx], ['x', 'u'], ['df_dx'])
```

**Comment by jaeandersson** [comment]
`Function::jac` is actually just a partially implemented method, not in use anywhere. It was meant to replace `Function::jacobian`, which is essentially the same thing but with Jacobian blocks grouped together. It's unfortunate that this incomplete method was left in the code, so I am removing this method now. The functionality will be moved into `Function::jacobian` however, cf. #2178.
