### ISSUE TITLE
Qpsolver equality constraint

### ISSUE THREAD

**Issue by PatrickSampaioUSP** [casadi/casadi#2603]
In the documentation we have that the qpsolver solves a problem like:
````
min          1/2 x' H x + g' x
x

subject to
LBA <= A x <= UBA
LBX <= x   <= UBX

with :
H sparse (n x n) positive definite
g dense  (n x 1)

n: number of decision variables (x)
nc: number of constraints (A)
````

However, in my problem i have a set of equalities constraints like:

Gx = UBG

How can i use the casADI qpsolver to receive a set of equalities constraints?

**Comment by PatrickSampaioUSP** [comment]
I'm currently using the MatLab quadprog method:

https://www.mathworks.com/help/optim/ug/quadprog.html#d120e113107

I'm refering to the Aeq and beq.

**Comment by jgillis** [comment]
You set the (relevant parts of) LBA and UBA equal to each other.
The interfaced QP solvers will recognise this and internally split out into equalities and inequalities

**Comment by PatrickSampaioUSP** [comment]
@jgillis thanks for you answer, if you could, please, answer those question, would help me a lot.

1 - I tried to set LBA = UBA but the solver returned

```
WARNING:   Stepsize is 0.000000000000000e+000
ERROR:  Premature homotopy termination because QP is infeasible
->ERROR:  Initial QP could not be solved due to infeasibility!
````

i'm using `qpoases`, should i use other in this case?


2 - I do not have any inequalities, is there a problem is the matrix lba is equal to the uba?

**Comment by jgillis** [comment]
Well, perhaps it really is infeasible?
lba and uba fully equal does not matter to CasADi, but I can't guarantee that none of the solvers would choke on it.
I suggest you try `conic('S','ipopt',qp,'nlpsol',struct('nlpsol','ipopt'));` and `conic('S','ipopt',qp,'osqp');`

Please follow-up on our forum forum.casadi.org for follow-up.
We'd like to reserve the issue tracker for bug reports or feature requests

**Comment by PatrickSampaioUSP** [comment]
Ok, i will close this issue then.

Thanks.
