### ISSUE TITLE
IO Names not checked for uniqueness

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2604]
```python
from casadi import *

x = MX.sym("x")
f = Function("f",[x],[x**2,x-2],["x"],["y","y"])
print(f)
```

**Comment by jgillis** [comment]
@tmmsartor

**Comment by jgillis** [comment]
Seems to be violated often internally

**Comment by jgillis** [comment]
@jaeandersson can you comment please?

**Comment by jaeandersson** [comment]
Sorry for late answer. You say that it's violated internally. Do you have an example? I thought that was resolved.

**Comment by jgillis** [comment]
Just add a quick assertion internally and run the unittests..

**Comment by jaeandersson** [comment]
Oh, I misunderstood. I meant that I thought that the issue of getting duplicate names because of differentiation had been resolved, but this is a different issue.

**Comment by jaeandersson** [comment]
Added an implementation of the check using hashes (should be faster than string comparison, but probably overkill): a426fa3d9f777e0dd21b027e4ca3de93e8bfa63b
Didn't push to develop as it breaks unit tests.

**Comment by jaeandersson** [comment]
I believe that this is a breaking change. Currently, you'll get duplicate names internally as part of the derivative generation, cf. #2040. Don't think we should disallow duplicate names before we've resolved that issue

**Comment by jaeandersson** [comment]
#2040 has now been resolved
