### ISSUE TITLE
Parametric Interpolant crashes Matlab

### ISSUE THREAD

**Issue by abe-mart** [casadi/casadi#2608]
After recently updating Casadi, I'm having issues with some of my code that was using a parametric interpolant.  The code worked previously.  Here's a minimal example:
```
import casadi.*
grid = linspace(0,10);
interpolant('LUT','linear',{grid},1)
```
Running this crashes Matlab with the error:
```
*** %n in writable segment detected ***
Killed
```
I tried re-installing Casadi, but I'm getting the same issue.  I'm running Casadi 3.5.1 with Matlab 2019b on Ubuntu 18.04.  Has something changed recently with this?

**Comment by jgillis** [comment]
Thanks for reporting!
I seem unable to reproduce this unfortunately.

Could you exclude the case that there might be multiple versions of CasADi on the Matlab path?
Also, a single Matlab session will only work with a single version of CasADi.

Please follow up if the above is not the issue for you.

**Comment by abe-mart** [comment]
I found I did have another Casadi version installed through pip to use with Python.  I removed both versions, reinstalled the Matlab version, and it is working now.
