### ISSUE TITLE
Including constraints in IDAS integrator

### ISSUE THREAD

**Issue by Alfpozzi** [casadi/casadi#2609]
Hi everyone,

I would like to understand if there is the possibility of including model constraints in the integrator (considering that the model is made of DAEs)?

I saw that IDAS allows for constraints on the algebraic variables with the command IDASetConstraint, but I would like to know if this possibility is implemented through the casadi interface.

Thanks in advance

Andrea

**Comment by jgillis** [comment]
`constraints` option now available
