### ISSUE TITLE
Opti Conic - error_on_fail 

### ISSUE THREAD

**Issue by LozioAlce** [casadi/casadi#2613]
Hi Guys, first of all, thank you for developing this amazing tool.

I am having an issue/doubt with the following problem that should be a SOCP.
I am able to get the solution with ipopt with try and catch while with superscs I cannot. 
It says:  try to set "error_on_fail" to false. (if I remove the try and catch)
I did not find any example of conic problems with Opti and how to pass the options.
Here my MATLAB code:

---------------------------------------------------------------------------------------------------------------------
clear
import casadi.*
opti    = casadi.Opti();
% opti    = casadi.Opti('conic') % if active does not work;
nx      = 6;
nu      = 3;
nTraj   = 100;
X       = opti.variable(nx,nTraj);
U       = opti.variable(nu,nTraj);
gamma   = opti.variable(1,nTraj);
uMax = 1.2;
uMin = 0.1;
dt = 0.1;
for nn = 1:nTraj-1
% inetgrate dynamic Euler
    opti.subject_to(   X(1:3,nn+1) == X(1:3,nn)+dt*X(4:6,nn) )
    opti.subject_to(   X(4:5,nn+1) == X(4:5,nn)+dt*U(1:2,nn) )
    opti.subject_to(   X(6,nn+1) ==X(6,nn+1)+dt* U(3,nn)-1 )
    % convexify lower bound constraints (cone)
    opti.subject_to(   gamma(nn) <=U(1,nn)^2+U(2,nn)^2+U(3,nn)^2 <= uMax )
    opti.subject_to(   uMin<=gamma(nn) )
end

nn = nTraj;
opti.subject_to(   gamma(nn) <=U(1,nn)^2+U(2,nn)^2+U(3,nn)^2 <= uMax )
opti.subject_to(   uMin<=gamma(nn) )

% initial condition
opti.subject_to(X(1:6,1) == zeros(nx,1))
% final condition
opti.subject_to(X(1:3,nTraj) == ones(3,1))

% opti.solver('superscs')  %<-- if active  does not work: Error using casadi.Opti/solve (line 253)
Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:159:
Error in Function::operator() for 'solver_qpsol' [SuperscsInterface] at .../casadi/core/function.cpp:1368:
.../casadi/core/conic.cpp:525: conic process failed. Set 'error_on_fail' option to false to ignore this error.

opti.solver('ipopt')
opti.minimize(sum(sum(U)))
try
    sol = opti.solve();
catch
    disp('error')
end

% Plot data
close all
xSol = opti.debug.value(X);  % does not work throws an error This action is forbidden since you have not solved the Opti stack yet (with calling 'solve').

uSol = opti.debug.value(U);
gammaSol = opti.debug.value(gamma);
figure(1)
plot(xSol(1:3,:)'), sgtitle('State')
figure(2)
plot(uSol'), sgtitle('Control')
figure(3)
plot(gammaSol), sgtitle('Gamma')

Thanks a lot for your help!

**Comment by LozioAlce** [comment]
Sorry, I found that the constraints should be written as :

 opti.subject_to(   uMin <=gamma(nn) <= uMax )
opti.subject_to(   U(1,nn)^2+U(2,nn)^2+U(3,nn)^2 <= gamma(nn) )

and added
opti.minimize(sum(gamma))

Now conic does not throw an error. But the solution of ipopt and superscsc are completely different in gamma.
Ipopt  gamma=1.2, 
superSCS gamma= 0.1.
Do you have any idea?

Also, how can I replicate the behaviour of try and catch in Conic? How to set  error_on_fail false?
Thanks

**Comment by LozioAlce** [comment]
I found out from the Python API that I should use soc(x,y) - (second Order Cone)
`soc(U(1:3,nn), gamma(nn))`
but I am not able to pass it to 'opti'

for example:
`opti.subject_to( soc( [U( 1: 3, nn)], Gamma(nn) ) ==0);`

Gives back this error:
'Error using casadi.Opti/solve (line 253)
Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:159:
.../casadi/core/optistack_internal.cpp:999: Assertion "return_success(accept_limit)" failed:
Solver failed. You may use opti.debug.value to investigate the latest values of variables. return_status is 'Not_Enough_Degrees_Of_Freedom'

Error in OptiConicExample (line 45)
        opti.solve()'

is there a way I can pass it to 'opti'?

**Comment by jgillis** [comment]
Sorry this question flew over the radar.

It is possible, but the syntax is a bit weird: https://github.com/casadi/casadi/commit/2ddf9403652d40ea2fca9fe703752228d645c17d

CasADi options can be passed as second argument to `opti.solver` (the third argument are solver-specific options)

**Comment by adarshrs** [comment]
Is this functionality available in MATLAB? It seems that soc is not recognized in the MATLAB interface. If not, what is the correct way to define SOCP problems in MATLAB using qpsol?
