### ISSUE TITLE
Return solver status in Opti stack

### ISSUE THREAD

**Issue by junzengx14** [casadi/casadi#2646]
In Opti stack, we can use
```
opti.solver('ipopt');
sol = opti.solve();
```
to solve an optimization problem, but sometimes the optimization becomes infeasible to solve.

I'm wondering if there is a way to return the status of the solution of problem (e.g. infeasible, well solved, etc), so that we can catch these status and do something else when the problem is infeasible.

**Comment by jgillis** [comment]
sol.stats(), but the default behaviour is to raisean exception unless the problem converged
