### ISSUE TITLE
Minimal step size for Cvodes

### ISSUE THREAD

**Issue by cm-jrc** [casadi/casadi#2653]
Hello,

I can't seem to find an option to set a minimal step size for the bdf solver of cvodes. 
Is the option accessible through casadi in some way, and if not, would it be possible to implement it?

Best Regards,
Christian

**Comment by jgillis** [comment]
Now accessible through `min_step_size` option in develop branch thanks to @tmmsartor

**Comment by cm-jrc** [comment]
Do you know when this option will make it into a released version?

**Comment by jgillis** [comment]
Probably within a week or so. Prof. Jim Rawlings also needs a new release
