### ISSUE TITLE
Version on Jetson

### ISSUE THREAD

**Issue by tomcattigerkkk** [casadi/casadi#2655]
Hi, 

I would like to run the CasADi on my NVIDIA Jetson platform. Any suggestion to build or install it? Thanks.

**Comment by jgillis** [comment]
Hi!
The Jetson provides a linux environment, no?
Just follow the standard source build instructions, and let us know if there are issues: https://github.com/casadi/casadi/wiki/InstallationLinux

**Comment by tomcattigerkkk** [comment]
@jgillis  Thanks for your reply. 

I got many similar errors while I compile the source within TX2, such as

/usr/bin/ld: ../../../lib/libcasadi_tinyxml.a(tinyxml.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTV12TiXmlUnknown' which may bind externally can not be used when making a shared object; recompile with -fPIC
../../../lib/libcasadi_tinyxml.a(tinyxml.cpp.o): In function `TiXmlUnknown::Clone() const':
tinyxml.cpp:(.text+0x2a4): dangerous relocation: unsupported relocation
/usr/bin/ld: ../../../lib/libcasadi_tinyxml.a(tinyxml.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTV12TiXmlComment' which may bind externally can not be used when making a shared object; recompile with -fPIC
../../../lib/libcasa

**Comment by jgillis** [comment]
And after reconfiguring cmake with `-DWITH_TINYXML=OFF`?

**Comment by tomcattigerkkk** [comment]
@jgillis 

now is 

/usr/bin/ld: ../../../lib/libcasadi_sundials.a(nvector_serial.c.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `N_VClone_Serial' which may bind externally can not be used when making a shared object; recompile with -fPIC
../../../lib/libcasadi_sundials.a(nvector_serial.c.o): In function `N_VNewEmpty_Serial':
nvector_serial.c:(.text+0x1f74): dangerous relocation: unsupported relocation
/usr/bin/ld: ../../../lib/libcasadi_sundials.a(nvector_serial.c.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `N_VDestroy_Serial' which may bind externally can not be used when making a shared object; recompile with -fPIC

**Comment by jgillis** [comment]
Again with `export CFLAGS=-fPIC` context?

**Comment by tomcattigerkkk** [comment]
@jgillis  
it works well now. Thanks.
