### ISSUE TITLE
Cannot load shared library

### ISSUE THREAD

**Issue by chjXu** [casadi/casadi#2666]
I
[test .txt](https://github.com/casadi/casadi/files/5276910/test.txt)

 installed it from the source according to the tutorial, and then I found an example to test whether the installation was successful, the compilation passed but the execution will report an error that the library cannot be loaded.

Exploring MX and Opti... 
CasADi - 2020-09-24 22:35:33 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_nlpsol_ipopt.so': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '' :
    Error code: libcasadi_nlpsol_ipopt.so: cannot open shared object file: No such file or directory

**Comment by jgillis** [comment]
Did you pass WITH_IPOPT=ON at the cmake step?

**Comment by chjXu** [comment]
> Did you pass WITH_IPOPT=ON at the cmake step?
Is that right?

cmake_minimum_required(VERSION 2.8.3)
project(casadi_test)
add_compile_options(-std=c++11)
find_package(CASADI REQUIRED)
include_directories(/usr/local/include)
if(WITH_IPOPT)
	add_executable(casadi_test blocksqp_multiple_shooting.cpp)
	target_link_libraries(casadi_test casadi ipopt)
endif()

cmake can pass, but make step has nothing.

**Comment by vruge** [comment]
can `pkg-config --libs ipopt` find ipopt?
if not, I would try
```shell
export PKG_CONFIG_PATH=$YOUR_IPOPT_PATH/lib/pkgconfig:$PKG_CONFIG_PATH
pkg-config --libs ipopt
```
and check cmake again.

**Comment by chjXu** [comment]
Thanks, i have solved this problem by installing the HSLMA27 solver.

**Comment by xkk3599** [comment]
Hi,I meet same question,and I want to how to solve it?
