### ISSUE TITLE
Inaccurate record_time for OSQP

### ISSUE THREAD

**Issue by sjhstone** [casadi/casadi#2667]
I'm using CasADi to compute solution for QP problems through `qpsol` using OSQP.

```matlab
qpsolOptions = struct;
qpsolOptions.record_time = true;
qpsolOptions.print_time = true; % and I tried false

qpsolver = casadi.qpsol('consensusQP', 'osqp', qp, qpsolOptions);
```

The QP is rather simple and small, with only equality constraints, however, it seems using OSQP through qpsol gives inaccurate timing information.

```
qpsolver.stats().t_proc_total
qpsolver.stats().t_wall_total
```
gives either `1.0000e-03` or `0`. When printed message gives result below 1 ms, say 972.00 us, the results in `stats()` are still 0.

Using YALMIP and OSQP to solve a larger QP with both quality and inequality constraints takes only at most `7.0250e-04` seconds by using
```
qpOptions = sdpsettings('verbose', 0, 'solver', 'osqp');
debugInfo = optimize(qpCons, qpGoal, qpOptions);
timingInfo = debugInfo;
```

So from a user perspective I think CasADi is returning inaccurate results. Is there any viable way to get more accurate timing information at the moment?

**Comment by jgillis** [comment]
Is this on Windows?

**Comment by sjhstone** [comment]
Yes, I'm using CasADi on Windows.
