### ISSUE TITLE
Unable to use casadi + osqp with an already installed version of osqp

### ISSUE THREAD

**Issue by GiulioRomualdi** [casadi/casadi#2670]
In the laboratory in which I work (https://dic.iit.it/), we started to use `casadi` for developing MPC controllers. Our code is mainly developed using C++, so for this reason we decided to use the C++ API offered by casadi.

Right now I'm trying to build casadi for source. As far as I understood it requires a custom version of `osqp`  https://github.com/jgillis/osqp/tree/cee489483c505151b0565a35003a428535e96c9f that it's based on `osqp v0.5.0` that it is installed along with `casadi`.

In our infrastructure, we already used `osqp` along with [`osqp-eigen`](https://github.com/robotology/osqp-eigen) that is based on `osqp v0.6.0.` 
Unfortunately, as can be read from the [`osqp changelog`](https://github.com/oxfordcontrol/osqp/blob/master/CHANGELOG.md#version-060-30-august-2019) the version `0.5.0` is not compatible with `0.6.0`. This means that if we want to use casadi in our framework we have to start using [your fork](https://github.com/jgillis/osqp/tree/cee489483c505151b0565a35003a428535e96c9f) of `osqp`. 

Is there a way to use `osqp 0.6.0`? More in general, is there a way to use a system based installation of `osqp` rather than a custom implementation? If I'm not mistaken `ipopt interface` already supports this feature. (Please check [here](https://github.com/casadi/casadi/wiki/InstallationLinux#installing-ipopt-recommended-if-you-plan-to-solve-optimal-control-problems).)

cc @traversaro @s-dafarra

**Comment by jgillis** [comment]
Our CMake is currently set up to use our fork, and not check for system installation, unfortunately.
Feel free to make a pull request that includes a `FindOSQP.cmake` or more modern cmake strategies.


If you don't like messing with build system, perhaps replace our fork with osqp 0.6.0 and merge in our modifications below.
If 0.6.0 is not compatible, that also means some changes in `osqp_interface.cpp` are needed..

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 991d75e..b3c241f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -94,6 +94,9 @@ option (ENABLE_MKL_PARDISO "Enable MKL Pardiso solver" ON)
 if (DFLOAT)
 	message(STATUS "Disabling MKL Pardiso Solver with floats")
 	set(ENABLE_MKL_PARDISO OFF)
+elseif(DEFINED EMBEDDED)
+	message(STATUS "Disabling MKL Pardiso Solver for embedded")
+	set(ENABLE_MKL_PARDISO OFF)
 endif()
 message(STATUS "MKL Pardiso: ${ENABLE_MKL_PARDISO}")
 
@@ -196,7 +199,10 @@ else()
     )
 endif()
 
-
+if (NOT CTRLC)
+    list(REMOVE_ITEM osqp_src "src/ctrlc.c")
+    list(REMOVE_ITEM osqp_headers "include/ctrlc.h")
+endif()
 
 # if we are building the Python interface, let's look for Python
 # and set some options
@@ -334,7 +340,7 @@ endif (MATLAB)
 # If we are building Python/Matlab/R interface:
 #   - do not build shared library
 #   - do not build demo
-if (NOT PYTHON AND NOT MATLAB AND NOT R_LANG)
+if (NOT PYTHON AND NOT MATLAB AND NOT R_LANG AND NOT EMBEDDED)
     # Create osqp shared library
     # NB: Add all the linear system solvers here
     add_library (osqp SHARED ${osqp_src} ${osqp_headers} ${linsys_solvers})
@@ -358,7 +364,7 @@ if (NOT PYTHON AND NOT MATLAB AND NOT R_LANG)
     add_executable (osqp_demo ${PROJECT_SOURCE_DIR}/examples/osqp_demo.c)
     target_link_libraries (osqp_demo osqpstatic)
 
-endif (NOT PYTHON AND NOT MATLAB AND NOT R_LANG)
+endif (NOT PYTHON AND NOT MATLAB AND NOT R_LANG AND NOT EMBEDDED)
 
 # Create CMake packages for the build directory
 # ----------------------------------------------
diff --git a/include/osqp.h b/include/osqp.h
index 4a25388..dc8111d 100644
--- a/include/osqp.h
+++ b/include/osqp.h
@@ -55,7 +55,7 @@ void osqp_set_default_settings(OSQPSettings *settings);
  * @return              Solver environment
  */
 OSQPWorkspace* osqp_setup(const OSQPData *data,
-                          OSQPSettings   *settings);
+                          const OSQPSettings   *settings);
 
 # endif // #ifndef EMBEDDED
 
diff --git a/include/util.h b/include/util.h
index 48ff6bf..a9c506e 100644
--- a/include/util.h
+++ b/include/util.h
@@ -30,7 +30,7 @@ const char* osqp_version(void);
  * @param  settings Settings to be copied
  * @return          New settings structure
  */
-OSQPSettings* copy_settings(OSQPSettings *settings);
+OSQPSettings* copy_settings(const OSQPSettings *settings);
 
 # endif // #ifndef EMBEDDED
 
diff --git a/src/osqp.c b/src/osqp.c
index 282f409..286e291 100644
--- a/src/osqp.c
+++ b/src/osqp.c
@@ -71,7 +71,7 @@ void osqp_set_default_settings(OSQPSettings *settings) {
 #ifndef EMBEDDED
 
 
-OSQPWorkspace* osqp_setup(const OSQPData *data, OSQPSettings *settings) {
+OSQPWorkspace* osqp_setup(const OSQPData *data, const OSQPSettings *settings) {
   OSQPWorkspace *work; // Workspace
 
   // Validate data
diff --git a/src/util.c b/src/util.c
index 696fe5c..a41f16d 100644
--- a/src/util.c
+++ b/src/util.c
@@ -220,7 +220,7 @@ void print_footer(OSQPInfo *info, c_int polish) {
 
 #ifndef EMBEDDED
 
-OSQPSettings* copy_settings(OSQPSettings *settings) {
+OSQPSettings* copy_settings(const OSQPSettings *settings) {
   OSQPSettings *new = c_malloc(sizeof(OSQPSettings));
 
   // Copy settings
```

**Comment by GiulioRomualdi** [comment]
Hi @jgillis, thank you for the replay. Start supporting `osqp 0.6.0` requires some modification in the  `osqp_interface.cpp`. 
Indeed now osqp requires only the upper triangular part of the Hessian matrix. As far as I understood the sparsity pattern of the hessian matrix is set in the following lines. 
https://github.com/casadi/casadi/blob/fadc86444f3c7ab824dc3f2d91d4c0cfe7f9dad5/casadi/interfaces/osqp/osqp_interface.cpp#L171-L178
where `H_` is a [casadi sparsity object](http://casadi.sourceforge.net/api/html/d5/da8/classcasadi_1_1Sparsity.html).

I was wondering if there is a way to extract the upper triangular part of the `H_` without using for loops. I've seen that there is already a method for retrieving the [number of nonzero elements on the upper part](http://casadi.sourceforge.net/api/html/d5/da8/classcasadi_1_1Sparsity.html#ac33dfd0f700b4c72262fb423d56c999d) and their [values](http://casadi.sourceforge.net/api/html/d5/da8/classcasadi_1_1Sparsity.html#a7f56376c469df0444754c9513239b3e6), but as far as I understood it is not possible to get the [`row `](http://casadi.sourceforge.net/api/html/d5/da8/classcasadi_1_1Sparsity.html#a80e67fc72b078784dcdf5697243a415e) and the [`colind`](http://casadi.sourceforge.net/api/html/d5/da8/classcasadi_1_1Sparsity.html#aa902ae9e4175be9311fa7d63419be004) for the only triangular part.

**Comment by jgillis** [comment]
There's friend functions 'triu' and 'tril' that can operate on Sparsity objects

**Comment by GiulioRomualdi** [comment]
> There's friend functions 'triu' and 'tril' that can operate on Sparsity objects

Thank you! 
#2671 should fix the issue
