### ISSUE TITLE
Bug in erf on Mac OS

### ISSUE THREAD

**Issue by tinosulzer** [casadi/casadi#2672]
erf returns slightly different value on Mac OS than Windows:

On Mac: `casadi.erf(3)` returns 0.9999779095030015
On Windows: `casadi.erf(3)` returns 0.9999779095030014
On Mac or Windows: `scipy.special.erf(3)` returns 0.9999779095030014

**Comment by jaeandersson** [comment]
This cannot really be considered a bug. CasADi is just relying on your standard library.
