### ISSUE TITLE
How to build a wheel for Python 3.6 on ARM64?

### ISSUE THREAD

**Issue by njgraham** [casadi/casadi#2675]
I've successfully built and installed on an Ubuntu ARM64/aarch64 Docker container as per https://github.com/casadi/casadi/wiki/InstallationLinux

After doing so, I can successfully `import casadi` from within that same running container.

What I want to do now is make a python wheel so that I can do `pip install casadi` on ARM just like I do on x86 (from pypi).   From ARM it tells me there are no pip packages which is why I was trying to build it.

So, how are the wheels built that are served here: https://pypi.org/project/casadi/#files ?  Can I do something like that on an ARM box?

This seemed relevant: https://github.com/casadi/testbot/blob/master/create_wheel_local.py - I actually ran that script and after fiddling with Python paths and wheel filename issues I was able to get it to work enough to import on another running container.  But, a lot of manual intervention was required - I know I'm not doing it right.

**Comment by njgraham** [comment]
The result from https://github.com/casadi/testbot/blob/master/create_wheel_local.py worked for me after renaming the archive like this:

```
mv casadi-3.5.5-cp3.6.9-none-manylinux1_x86_64.whl casadi-3.5.5-py3-none-any.whl
```

I think the reason I had to rename it was because [manylinux1 isn't supported on ARM](https://github.com/pypa/manylinux/issues/84).

I realize this is a complete hack and that the wheel probably won't work on anything other than our specially configured Docker images, but it works at least.

**Comment by rhenwood-arm** [comment]
a little late, but this document includes options to build wheels natively, cross-compiled, or using emulation: https://github.com/ARM-software/developer/blob/master/solutions/infrastructure/languages-and-libraries/python/multi-platform.md

**Comment by jgillis** [comment]
There are official aarch64 wheels for 3.5.5 now..

**Comment by njgraham** [comment]
> There are official aarch64 wheels for 3.5.5 now (produced using dockcross)..

Great news!  Where can I find them?  I tried the naive approach in an ARM container with python3:

```
root@bc46059a33d9:/casadi# uname -a
Linux bc46059a33d9 5.4.0-7634-generic #38~1596560323~20.04~7719dbd-Ubuntu SMP Tue Aug 4 19:12:34 UTC 2 aarch64 aarch64 aarch64 GNU/Linux
root@bc46059a33d9:/casadi# pip3 install casadi
Collecting casadi
  Could not find a version that satisfies the requirement casadi (from versions: )
No matching distribution found for casadi
```

Actually, after poking around a bit more, it seems that may they're not quite available yet?

> OK to be clear, we won't ship wheels, until pypa/manylinux#84 is fixed.
https://github.com/hynek/argon2-cffi/pull/74#issuecomment-742996555

The issue they're referring to has been open since 2016 :(

**Comment by jgillis** [comment]
They are on pypi. I encourage you to experiment a bit with them, and also upgrade your pip version. I heard that the contents does run on amd64 platform, but I have no confirmation of anyone getting the package to pip install.

**Comment by DavidAntliff** [comment]
> a little late, but this document includes options to build wheels natively, cross-compiled, or using emulation: https://github.com/ARM-software/developer/blob/master/solutions/infrastructure/languages-and-libraries/python/multi-platform.md

Link is now https://github.com/ARM-software/developer/blob/master/projects/python-wheels/multi-platform.md I think, if anyone is looking for it.
