### ISSUE TITLE
Unable to generate code for solver

### ISSUE THREAD

**Issue by bdch1234** [casadi/casadi#2682]
I'd like to generate c-code for an optimization problem, but I'm getting below error:
`CasADi -  WARNING("The function "solver", which is of type "IpoptInterface" cannot be code generated. The generation will proceed, but compilation of the code will not be possible.") [.../casadi/core/function_internal.cpp:2453]`

I'm sure there is something I have missed, would you please point me in the right direction?

**Comment by jaeandersson** [comment]
That's correct, you cannot generate C code for the interface to IPOPT.

**Comment by bdch1234** [comment]
Do you have any plans to support this? Or alternatively, would you have any pointers as to how I can manually add the missing C-code after generated?

**Comment by jaeandersson** [comment]
> @jaeandersson, do you have any plans to support this? Or alternatively, would you have any pointers as to how I can manually add the missing C-code after generated?

IPOPT is written in C++ to generating C code for the interface isn't really possible. What you can do is to generate C code for the cost function, gradient of the cost function, constraints, Jacobian of the constraints and Hessian of the Lagrangian and then call from CasADi in C++. `<casadi_src_root>/docs/embeddable_codegen` demonstrates this (although I'm not sure if the code is up-to-date). Other ways include serializing the expressions or using a different NLP solver that does support C code generation. Currently, that's only possible for `sqpmethod`, which is a very basic NLP solver. And you need to use a code generating `QP` solver as well. It's better to ask this question to the forum.

**Comment by bdch1234** [comment]
Understood, thanks for clarifying @jaeandersson. I'll look into that example.

Just one question on that though, would we still expect to see a performance increase by generating C-code, as compared to just using C++ interface to casadi?

**Comment by bdch1234** [comment]
Also, @jaeandersson would it not be possible to generate C-code which uses the C-interface to IPOPT?

[https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_C](url)
