### ISSUE TITLE
Using Dae solver inside loop for optimization

### ISSUE THREAD

**Issue by JulioPCO** [casadi/casadi#2687]
Good evening,

I am writing a moving horizon estimation (MHE) program for a Dae system and I am trying to solve this dae model inside a loop for the optimization, however the casadi enviroment does not provide results for this dae system. Below is part of the code so you can understand better.

![MHE](https://user-images.githubusercontent.com/74670609/100750045-3de5a980-33c4-11eb-88df-4ee06553163b.png)

First I have a model using the MX variables, x_var, z_var and so on, which I use to create the Dae solver. Then I create a new set of MX variables, X,Z that are going to be used for the moving horizon estimation and at a certain point of the MHE I need to calculate the states and the algebraic states for the objective function, so i call the dae function using the new variables X,Z and get the result (fk3.xf and fk3.zf).

 In the end, I use ipopt with the last code of the image. But when the solver runs, this fk3.xf and fk3.zf are not computed, I tested the code without this part of the objective function and it works normally. Am I doing something wrong or there is a better way to obtain the states and algebraic states of my model. Thanks in advance, I hope you understood and if you can help me I would be very grateful.

Sincerely,
Julio

**Comment by jaeandersson** [comment]
This is a question for the forum, http://forum.casadi.org/
