### ISSUE TITLE
opti.to_function: Is it possible to set max_cpu_time when calling the function?

### ISSUE THREAD

**Issue by jtorde** [casadi/casadi#2693]
`M = opti.to_function('M',{p},{xy});`

When calling `M(...)`Is there a way to set the max time Ipopt will spend running the problem? (i.e. set [this](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_max_cpu_time:~:text=3000.-,max_cpu_time) option)

Thanks!

**Comment by jgillis** [comment]
opti.solver('ipopt', options) does not work?

**Comment by jtorde** [comment]
Yes, but I mean once you have `M` created (and without using `opti` again). I would like to call `M(...)` several times with different max_cpu_time. Something like 

```
M = opti.to_function('M',{p},{xy});
M(max_cpu_time=1.5) %Solve once allowing only 1.5 seconds
M(max_cpu_time=1.5) %Solve again allowing only 1.5 seconds
```
The reason why I can't use `opti.` again is that I am exporting the function as a .casadi in Matlab, and reading this function from C++. 

Thanks again

**Comment by jgillis** [comment]
Okay, this is fundementally unsupported I'm afraid.
Perhaps you can save Function("nlp",{opti.x,opti.p},{ opti.f,opti.g}) and do the ipopt step in c++? Or save a range of parametric solvers.

Alternatively, you could create an iteration_callback that itself times and aborts. Given the requirement of matlab to c++, the only working approach would be compiling a small Callback subclass in c++, loading it in via external() in Matlab and couple it with the solver.
