### ISSUE TITLE
Feature request: Generate C-code for IPOPT interface

### ISSUE THREAD

**Issue by bdch1234** [casadi/casadi#2697]
Would it be possible to add support using the [C-interface to IPOPT](https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_C)?

**Comment by jgillis** [comment]
This is possible, but how would it be more useful than the existing casadi C API usage? It's not like the difficulty in compiling C++ and fortran depencies of ipopt on embedded targets would vanish..

**Comment by bdch1234** [comment]
Well I suppose the benefit would be that we could work in python to build our problem, create a standalone casadi-function for the solution, and then just export to C for additional performance. Figuring out how to compile dependencies for IPOPT would then be a one-off problem I guess.

Correct me if I'm wrong, but if we just use the C-API to casadi we would be using the virtual machines to evaluate, unless we generate C-functions for gradients/hessians/etc, and then use that (which to me seems like a more involved way of usage, as compared to above).

Also, not meaning to step on anyone's toes here, but by above logic wouldn't the whole feature of C-generation be un-useful (for lack of a better word) as well?

**Comment by jgillis** [comment]
Don't worry, there is are no toes to step on here.

Codegen has two main usages: speedup and portability (self contained c code will compile on any system). With Ipopt, portability is out of the window (not self-contained anymore). Speedup of function evaluations is obviously very important in optimization. Jit/external can take care of that, also in C api. The extra gain from codegenerating the solver interface itself would be neglible for all but the smallest problems; you just drop some virtual function calls to reach the compiled code for gradient, hessian etc.

I'm not saying that your request is a bad idea in principle, just that in practice I don't see a big impact that would merit high priority.

Of course, feel free to make some experiments/benchmarks pull requests.

**Comment by bdch1234** [comment]
Understood, thanks for clarifying. 

So if I have a problem which is function-evaluation heavy, and I want to get maximum performance when working from python, what are my options there? JIT sounds promising, but I understood that feature to be compiling C-code functions, which means that I need generate C-code for gradients/hessians again, or did I misunderstand that part?

**Comment by jgillis** [comment]
I've added a FAQ entry about jit: https://github.com/casadi/casadi/wiki/FAQ:-how-to-perform-jit-for-function-evaluations-of-my-optimization-problem%3F
But first check what your [bottleneck](https://github.com/casadi/casadi/wiki/FAQ:-is-the-bottleneck-of-my-optimization-in-CasADi-function-evaluations-or-in-the-solver%3F).

**Comment by bdch1234** [comment]
Wonderful! Many thanks @jgillis

**Comment by jgillis** [comment]
This jit/external thing has been here for many years;-)

**Comment by bdch1234** [comment]
I see, well then can I suggest adding a link to the FAQ in the docs-part of the homepage, or alternatively adding a section in the docs about it @jgillis ? When I read the jit-part of the docs I certainly didn't get that it can be used the way it is described in the FAQ.

**Comment by jgillis** [comment]
Yeah#2128
