### ISSUE TITLE
Opti stack with other solvers

### ISSUE THREAD

**Issue by junzengx14** [casadi/casadi#2701]
Hi developers,

I would like to know whether we can use other solvers while using opti stack, such as QPOASES, etc. Moreover, if we are sure that the problem is a quadratic convex one, how we apply other options of solvers, for example QPOASES? I'm not sure based on the current knowledge of the documentation.

**Comment by sjhstone** [comment]
Opti stack, to my understanding, is an interface for modelling NLP problems. Solving NLP in the conventional `nlpsol` way would involve some tedious work to concatenate all variables into a long vector, and carefully access the desired values by keeping indices separately.

You can try switching from `solver('ipopt')` to `solver('sqpmethod')` to get a workaround for your current QP while waiting for the developers to extend Opti's capability.

**Comment by junzengx14** [comment]
> Opti stack, to my understanding, is an interface for modelling NLP problems. Solving NLP in the conventional `nlpsol` way would involve some tedious work to concatenate all variables into a long vector, and carefully access the desired values by keeping track of the indices.
> 
> For QPs, at most 2 variables can be coupled in one term, index-tracking can be easier.
> 
> As Opti supports all solvers supported by `nlpsol`, it is safe to replace `ipopt` with any installed CasADi NLP solver plugin. You can try switching from `solver('ipopt')` to `solver('sqpmethod')` to get a workaround for your current QP while waiting for the developers to extend Opti's capability.

You really provide a great catch, thanks a lot! By the way, may I ask whether there are any similar options in `'sqpmethod'` such that we can hide optimization information? such as `"verbose": False` in ipopt? I tried as
```
option = {"print_header": False, "print_time": False}
```
but this looks insufficient and iteration information still appears...

**Comment by junzengx14** [comment]
> Opti stack, to my understanding, is an interface for modelling NLP problems. Solving NLP in the conventional `nlpsol` way would involve some tedious work to concatenate all variables into a long vector, and carefully access the desired values by keeping track of the indices.
> 
> For QPs, at most 2 variables can be coupled in one term, index-tracking can be easier.
> 
> As Opti supports all solvers supported by `nlpsol`, it is safe to replace `ipopt` with any installed CasADi NLP solver plugin. You can try switching from `solver('ipopt')` to `solver('sqpmethod')` to get a workaround for your current QP while waiting for the developers to extend Opti's capability.

By the way, I'm not sure whether the `nlpsol` is an "augmented" version of their quadratic programming module, if so, we shall be able to use sqpmethod and ipopt even in `qpsol`...really needs easier documentation from developers, lost in source code documentation currently...

**Comment by jgillis** [comment]
Opti('conic') to switch to conic problems (qp is a subset of that)

**Comment by jgillis** [comment]
Sqpmethod and ipopt can be used in qpsol context by going through 'nlpsol' plugin with 'nlpsol' option set to 'sqpmethod' or 'ipopt'
