### ISSUE TITLE
Is there a way to print out all the results of the optimization process?

### ISSUE THREAD

**Issue by lee-ck** [casadi/casadi#2714]
Hi all, 
Thanks to developers of casadi!

I am doing time optimization via casadi (ipopt),
I can know the final optimization value, but I want to print out and check how the time value changes in every iteration, but I'm not sure how.
I can't find it on Doc, can you help?

Thank you in advance,
Ck.Lee

**Comment by jgillis** [comment]
Objective values of iterates are available in
`solver.stats()`.
Decision variables can be accessed through an iteration callback.

**Comment by lee-ck** [comment]
> Objective values of iterates are available in
> `solver.stats()`.
> Decision variables can be accessed through an iteration callback.

Thank you jgilis!!
