### ISSUE TITLE
Modelica to CasADi to Matlab

### ISSUE THREAD

**Issue by Niklasm812** [casadi/casadi#2723]
Hi there,
I have a modelica model and some code for analysis in Matlab. I would like to transfer the Modelica model to CasADi and interface it with Matlab to calculate gradients. I started with the file `thermodynamics_example.py` from the documentationen. My idea was to use `parse_fmi` from Matlab to generate a `DaeBuilder()` object. That worked with the precompiled .xml files from `thermodynamics_example.py` . Then i tried to generate new .xml files via OpenModelica and JModelica. The same problems from issue #2268 and #1882 arose. Is there an existing solution or any suggestions for my specific problem? Thanks

**Comment by jaeandersson** [comment]
Hi @Niklasm812! I'm currently working on trying to update this toolchain and find a good solution to this. .xml export isn't supported by JModelica (now called OCT) anymore, and I don't think it has been well maintained from OpenModelica either. I have some ideas on how we can get this to work more smoothly - please send me an email to discuss more.
