### ISSUE TITLE
Find a function instance inside a nested expression

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2736]
It should be possible to find a reference to a particular function instance embedded in a bigger graph given its name.

Prototypes:
```c++
Function Function::find(std::string) const;
Function MX::find(std::string) const;
```

Only the first matching instance will be returned. If no match, an error will be thrown.

**Comment by jaeandersson** [comment]
Implemented Function::find. Currently only works for MXFunction. Should also add to other Function classes.

**Comment by jgillis** [comment]
Important missing Function: map

**Comment by jgillis** [comment]
Wait, is this not a duplicate of `Function::get_function()` ?

**Comment by jaeandersson** [comment]
> Wait, is this not a duplicate of `Function::get_function()` ?

`Function::get_function()` is for oracle classes specifically. It doesn't check recursively. Arguably, find should use get_function though

**Comment by jaeandersson** [comment]
If you want to rename the function, to avoid confusion with MX::find, I'd call it Function::find_function

**Comment by jaeandersson** [comment]
Closing this issue. It's been implemented for `MXFunction` and some other classes. For other classes, it can be implemented when the need arises.
