### ISSUE TITLE
FMI/Modelica import

### ISSUE THREAD

**Issue by kylebme** [casadi/casadi#2742]
What is the correct way to import FMIs or Modelica files as DAEs? I'm a bit confused by the existing documentation because it references JModelica which has been mostly closed-sourced. Is it still even possible?

**Comment by jaeandersson** [comment]
I don't know if there is a correct way, but as far as I know there are two ways that are currently being used:
1. You can create CasADi expressions using "transfer_model" in OCT (i.e. JModelica after it got closed-source)
2. Use the open-source code Pymoca https://github.com/pymoca/pymoca

Out of these, the first one is probably by far the most mature. I'm also currently working on improving this toolchain and make it conform with a refactored version of casadi::DaeBuilder, but this probably won't be part of the CasADi until the next release (it's currently in the develop branch, but not yet stable or feature-complete). Finally, there might be some way to do the export with OpenModelica. According to the OpenModelica user documentation, there is a way to export the models to CasADi, but I don't think it has been maintained on the OpenModelica side, and I'm unsure how feature complete it ever was.

Feel free to send me an email directly if you want to discuss this further. I am currently working intensively on improving the FMI/Modelica toolchain so there might be some synergies between what I'm doing and what you want to do. I'm trying to make sure that my work is as tool-agnostic as possible, developing components that can be used regardless of Modelica compiler (OCT, Pymoca, OpenModelica etc).
