### ISSUE TITLE
Overzealous "too many inputs/outputs" warning

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#2749]
A warning is currently emitted if one tries to create MXFunction instances with more than 10000 inputs or outputs. This may makes sense in most situations, but there are exceptions:
* When serializing expressions using `pack(vector<MX>)`
* When performing substitutions in graphs

There should be a way to suppress this warning, e.g. by an additional option in MXFunction replacing the hard coded "10000" with a user specified number or "0" to suppress the warning altogether.

**Comment by Mathadon** [comment]
+1 for this feature

**Comment by jaeandersson** [comment]
Added option `max_io`, which defaults to 10000 as before. Set `max_io` to 0 to suppress the warnings altogether. Option is set internally in some cases (like graph substitutions, serializing).
