### ISSUE TITLE
Numpy not listed as dependency

### ISSUE THREAD

**Issue by lassepe** [casadi/casadi#2752]
**Steps to Reproduce**

1. Create a virtual environment: `virtualenv casadi_test`
2. Install `casadi`: `pip install casadi`
3. Run the first example from the docs:
```python
from casadi import *


# Create scalar/matrix symbols
x = MX.sym('x',5)

# Compose into expressions
y = norm_2(x)

# Sensitivity of expression -> new expression
grad_y = gradient(y,x);

# Create a Function to evaluate expression
f = Function('f',[x],[grad_y])

# Evaluate numerically
grad_y_num = f([1,2,3,4,5]);
```

**Expected Behavior**

The code can be executed without any further packages installed since it only uses standard Python syntax and CasADi functionality.

**Observed Behavior**

The code errors with `ModuleNotFoundError: No module named 'numpy'`.

**Comments**

It seems like the numpy package is used inside the casadi python module but is not a dependency of the pip package.

**Additional Information**

- `pip freeze`: `casadi==3.5.5`
- `python --version`: `Python 3.9.2`

**Comment by jgillis** [comment]
Thanks, we'll address this in next release.
