### ISSUE TITLE
singular value decomposition

### ISSUE THREAD

**Issue by toshiEN** [casadi/casadi#2753]
Hello,
I am not able to find a single value decomposition finder in casadi in casdadi docs. I want to put it in optimization code, so I need svd finder which handles SX data type.

**Comment by jaeandersson** [comment]
CasADi doesn't support SVD. I have seen a chain rule for it here though: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.232.4922&rep=rep1&type=pdf.

**Comment by toshiEN** [comment]
OK. Thank you very much.
