### ISSUE TITLE
Mac Installation

### ISSUE THREAD

**Issue by Fahim13OSU** [casadi/casadi#2771]
I have Macbook pro 2020 and I am new to CASADI. I was using CASADI on my widows but now I am unable to use it on mackbook. Please help me to fix this issue

**Comment by jgillis** [comment]
Can you describe in what way the installation fails?

**Comment by Fahim13OSU** [comment]
So, I am not very much familiar with CASADI thats why I am sorry for any silly comments. but let me explain it from the start. 
1. I started using CASADI on on widows 10 where I got the problem which was already formulated and it uses below syntax for calling CASADI at the start of the program
addpath(genpath('../dependencies'))
addpath(genpath('./'))
import casadi.*
where the CASADI 3.4.5 was saved in the dependencies folder on same location there. Code was working fine on windows 10. 
2. I was trying to run same code by copying the whole folder into my macbook but it gave error by pointing CASADI functions unrecognized. Then i downloaded CASADI 3.4.5 for mac and after simply unzipping that folder I replaced it with the folder of CASADI copied from windows. 
I guess I am unaware of how to integrate CASADI on macbook with MATLAB. Please guide me from the beginning that how can I start using CASADI on my mackbook 2020 
Please let me know if you need further details to understand the problem.
Thanks

**Comment by jgillis** [comment]
Could I have a look at your system? meet.google.com/kif-zudf-xhx

**Comment by Fahim13OSU** [comment]
Yes sure

**Comment by Fahim13OSU** [comment]
Thank you very much,

Below are important takeaways of the meeting.
It was a very useful meeting.  On newer versions of macbook it is a security issue where you have to do following to once when you run the code.
For every CASADI field when you run it will give you an error click cancel and go to Apple on top left corner then preferences, then security and privacy and then allow.  
After doing this cancel the error and then you will get the 2nd error which will have an option of allow. do that and error will be fixed. 
based on your code you have to do this for every function where you are using CASADI. but the good thing is you have to do it once . I mean you don't have to do it again when you restart computer.

Thanks again for you help.
