### ISSUE TITLE
can I get an example of rootfinder in casadi using nlpsol solver? because newton one does not work in optimization with SX data type. 

### ISSUE THREAD

**Issue by toshiEN** [casadi/casadi#2773]
I have an optimisation code with rootfinder inside the optimization objective function. I find some steady state values and use this to formulate the objective function. But the optimization is not done properly as it says some derivative was not found properly in hessian or something. I hope you can help.

**Comment by jgillis** [comment]
Use MX to model your problem if you want to embed a rootfinder.
