### ISSUE TITLE
Error while solving Opti problem

### ISSUE THREAD

**Issue by cevheck** [casadi/casadi#2774]
While trying a real-time implementation of model predictive control on a double pendulum, the following error was produced (on Linux):
in 'casadi_root\+casadi\Opti.m' at line 243:
Error in Opti::set_value [OptiNode] at ...\casadi\core\optistack.cpp:143: 
...\casadi\core\optistack_internal.cpp:1449: Assertion "v.is_regular()" failed: Notify the CasADi developers.

I was wondering if there was an existing issue around this topic or a quick fix. I am trying to track certain desired trajectories, for my first 2 situations no errors occured and while trying the third one, the above error was produced.

Thanks in advance
Cedric Van Heck

**Comment by jgillis** [comment]
You are either setting a parameter with a value that is nan or inf, or forgetting to set the value of a parameter.
