### ISSUE TITLE
Modify nlp to conic in OptiStack

### ISSUE THREAD

**Issue by grupot3** [casadi/casadi#2775]
If I create `opti = casadi.Opti('nlp');` and then I add the variables, constraints and cost function, is there a way later on in the code to modify it to `conic`?

(The reason why I want to do this is because I want to solve it first with `Ipopt` and then with `Gurobi`)

Thanks

**Comment by jgillis** [comment]
If your problem is of QP nature, do use 'conic'. Ipopt can be accessed as
solver('nlpsol',struct('nlpsol','ipopt'))
The semantics of "subject to" may be different when using nlpsol, so we do mot allow a modification post-init.
