### ISSUE TITLE
List all symbolic variables

### ISSUE THREAD

**Issue by kunpengyao** [casadi/casadi#2777]
Hello! I am new to CasADi, I would like to know if there is a way to obtain a list of all symbolic variables (e.g. SX type) of a calculated symbolic expression? For example, I defined symbolic variables as `x` and `y` and obtained a function of them, say `f1`; then I defined `m` and `n`, which are variables of function `f2`. I expect to see [`x`, `y`, `m`, `n`] when I list all symbolic variables of `f1+f2`. Many thanks!

**Comment by jgillis** [comment]
`symvar(expr)`
