### ISSUE TITLE
I am facing exception :  Selected linear solver MA27 not available on casadi 2.3

### ISSUE THREAD

**Issue by bassemaed** [casadi/casadi#2778]
I am using Casadi 2.3 on ubuntu 18.04 and python 2.7.
I get this exception: 
Exception of type: OPTION_INVALID in file "../../../../Ipopt/src/Algorithm/IpAlgBuilder.cpp" at line 321:
Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.so", but the following error occured:
libhsl.so: cannot open shared object file: No such file or directory
Any help regarding this? been trying many things, nothing worked!

**Comment by jgillis** [comment]
Please check https://github.com/casadi/casadi/wiki/Obtaining-HSL and forum posts
