### ISSUE TITLE
casadi.integrator.forward() not (de-)serializable

### ISSUE THREAD

**Issue by dcebulla** [casadi/casadi#2782]
Dear all,

I am using CasADi version 3.5.5 via its MATLAB interface. Using a `parfor` loop it occurred to me, that an integrator for sensitivity generation (`casadi.integrator.forward()`) is not (de-)serializable, although, e.g., a "standard" integrator or an NLP solver object is. Using the following code (I try to give a minimum working example)

```matlab
t = casadi.SX.sym('t');
x = casadi.SX.sym('x', 1);
ode = struct('t', t, 'x', x, 'p', [], 'ode', t*x);
intg = casadi.integrator('intg', 'idas', ode, struct);
fwdIntg = intg.forward(1);
fs = fwdIntg.serialize();
fd = casadi.Function.deserialize(fs);
```

gives the following error:
`Error using casadi.Function.deserialize (line 1964)
basic_string::resize`

However, replacing `fwdIntg` by `intg` in the second last line, no error occurs.

I can bypass this problem by creating the required object within the `parfor` loop, but since this is not necessary for integrator and NLP solver objects, I don't know whether this is a bug, or simply a feature that has not been added yet. In the latter case I would propose to also make a casadi.integrator.forward also serializable.

**Comment by jgillis** [comment]
Thanks for reporting; it seems like something went wrong in https://github.com/casadi/casadi/commit/b588cd1162eefbec397e445ace25dc110a89a4de 

As a workaround, consider downgrading to 3.5.4

**Comment by jgillis** [comment]
No clue why idas integrator does de/serialize though; the implementation is wrong.

**Comment by dcebulla** [comment]
Thanks for your quick response, the workaround works great!
