### ISSUE TITLE
Symbolic Index of numpy array

### ISSUE THREAD

**Issue by fmccastro** [casadi/casadi#2785]
Hello!
I would like to know if there's a way to create a symbolic expression by acessing a numpy array with a symbolic index.
I may give an example of what I would like to do:

```import numpy as np'
from casadi import*

i = SX.sym('i')
a = np.array( [3, 4, 5] ) # or a = SX( np.array( [3, 4, 5] ) )

expression = a[i]
```
I am already aware of symbolic indexing with MX, but this is not feasible to solve my problem because the numpy array I want to acess is inside a python class ( see second example below):

```
index = SX.sym( 'index' )
f = Function( 'f', [ index ], [ self.localGPModels[state].localModelsIndex[ index ].center ] )
# self.localGPModels[state].localModelsIndex[ index ].center -> class
```
In this second example, you can see sort of what I want to do. I think I could solve this problem with the ``` conditional ``` command but the ```index``` may go from 0 to 100 and it would create too much overhead.

Thanks in advance!

**Comment by jgillis** [comment]
It sounds like you should be using `Callback` to embed Python code?
