### ISSUE TITLE
MX.sym

### ISSUE THREAD

**Issue by Fahim13OSU** [casadi/casadi#2786]
Hello, Hope you are doing great. When I try to define this on my mac book I get below mentioned error. How can I fix it?
Command :
NCS_CASADI   = MX.sym("NCS_CASADI");
NCP_CASADI   = MX.sym("NCP_CASADI");

Error:
Unable to resolve the name MX.sym.

Error in Decompositionfmincon (line 43)
NCS_CASADI   = MX.sym("NCS_CASADI");

**Comment by jgillis** [comment]
`casadi.MX.sym("NCP_CASADI")`, or `import casadi.*` first?
