### ISSUE TITLE
'eval_sx' not defined for CallbackInternal

### ISSUE THREAD

**Issue by Tonirayn** [casadi/casadi#2789]
Sorry, maybe it's a stupid question but I didn't understand why a callback like the MySVD one (I'm referring to the matlab example [code](https://github.com/casadi/casadi/blob/master/test/matlab/callback.m) ) can not be called using sx symbolic. is there a way to make an svd with recreating the function from scratch?

**Comment by jgillis** [comment]
A good SVD implementation is going to make heavy use of flow control (if-tests, while loop) etc which do not fit into SX graphs well. I'm afraid you will have to stick to MX, at least for this part of your algorithm.
We do not offer it as a built-in MX operation though.
