### ISSUE TITLE
HSL Solvers in Matlab

### ISSUE THREAD

**Issue by juandavid212** [casadi/casadi#2790]
Hello,
Is it a way to specify the location of the HSL binaries to casadi for using them on Matlab?
I've tried installing IPOPT and  HSL separately but I cannot call them from Matlab.
Thanks

**Comment by jgillis** [comment]
They just have to be accessible by the linker (e.g. using PATH env variable on Windows, LD_LIBRARY_PATH on linux). Adding the HSL folder to the matlab path will not help.

**Comment by juandavid212** [comment]
in bash
~/coinhsl-2021.05.05/build/lib$ ldd libcoinhsl.so
	linux-vdso.so.1 (0x00007ffcf2871000)
	liblapack.so.3 => /lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f8c1b022000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f8c1ad5a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8c1ac0b000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f8c1abc9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8c1a9d7000)
	libblas.so.3 => /lib/x86_64-linux-gnu/libblas.so.3 (0x00007f8c1a96a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8c1a94d000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f8c1a903000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8c1b925000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8c1a8fd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8c1a8da000)

Now in Matlab
>> getenv('LD_LIBRARY_PATH')

ans =

    '/home/juan/MATLAB/R2022a/sys/os/glnxa64:/home/juan/MATLAB/R2022a/bin/glnxa64:/home/juan/MATLAB/R2022a/extern/lib/glnxa64:/home/juan/MATLAB/R2022a/cefclient/sys/os/glnxa64:/home/juan/MATLAB/R2022a/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/home/juan/MATLAB/R2022a/sys/java/jre/glnxa64/jre/lib/amd64/server:/home/juan/coinhsl-2021.05.05/build'

**Comment by juandavid212** [comment]
I found the problem. 
https://github.com/casadi/casadi/wiki/Obtaining-HSL
It's necessary to update step 9.



9.Create a symbolic link from libcoinhsl.so to libhsl.so (libcoinhsl.dylib -> libhsl.dylib on OSX):

$> ln -s (hsl_install_directory)/libcoinhsl.so (hsl_install_directory)/libhsl.so

to
$> ln -s (hsl_install_directory)/lib/libcoinhsl.so (hsl_install_directory)/lib/libhsl.so
