### ISSUE TITLE
Issue with CASADI 3.5.5

### ISSUE THREAD

**Issue by Fahim13OSU** [casadi/casadi#2792]
I was running the same script on 3.4.5 CASADI and it was running fine there but now with new version I got this error.

Invalid MEX-file '/Volumes/OSU/Research/Cummins/Q1_2021/dependencies/casadi-osx-matlabR2015a-v3.5.5/casadiMEX.mexmaci64':
dlopen(/Volumes/OSU/Research/Cummins/Q1_2021/dependencies/casadi-osx-matlabR2015a-v3.5.5/casadiMEX.mexmaci64, 6): Symbol not found:
__ZN6casadi13GlobalOptions19casadi_include_pathE
  Referenced from: /Volumes/OSU/Research/Cummins/Q1_2021/dependencies/casadi-osx-matlabR2015a-v3.5.5/casadiMEX.mexmaci64
  Expected in: /Volumes/OSU/Research/Cummins/Q1_2021/dependencies/casadi-osx-matlabR2015a-v3.4.5/libcasadi.dylib
 in /Volumes/OSU/Research/Cummins/Q1_2021/dependencies/casadi-osx-matlabR2015a-v3.5.5/casadiMEX.mexmaci64

Error in casadi.interpolant (line 636)
  [varargout{1:nargout}] = casadiMEX(855, varargin{:});

Error in basicproblem_REEVBominlatest (line 49)
V_cyc = casadi.interpolant('LUT','linear',{0:length(v_cyc)-1},v_cyc(:));

**Comment by jgillis** [comment]
Could this be a situation where two CasADi versions are on the Matlab path, or you are swicthing versions withing a single Matlab session?
