### ISSUE TITLE
[Question] C++ - element access

### ISSUE THREAD

**Issue by mantielero** [casadi/casadi#2793]
[forum](https://groups.google.com/g/casadi-users/c/tc_hWfMb8kM)

I am trying to create some bindings for the Nim Programming Language. I managed to implement the first example in Nim. Now I am with the second example and I am having some issues:
```c++
#include <casadi/casadi.hpp>
using namespace casadi;

MX x = MX::sym("x",2); // Two states

// Expression for ODE right-hand side
MX z = 1-pow(x(1),2);
```

I am trying to wrap `x(1)` which seems to be called [element access](https://web.casadi.org/docs/#arithmetic-operations) in the documentation. I'd like to know what is the function that I need to wrap. Is it ny of these [get](https://github.com/casadi/casadi/blob/12fa60f676716ae09aa2abe34c1c9b9cf426e68a/casadi/core/mx.hpp#L345) methods? I don't think so because of the `bool` argument. Might it be related with [SubIndex](https://github.com/casadi/casadi/blob/12fa60f676716ae09aa2abe34c1c9b9cf426e68a/casadi/core/submatrix.hpp#L106). 

But if `x(1)`'s type is `SubIndex`, how is then related with `pow`? Looking to this [signature](https://github.com/casadi/casadi/blob/12fa60f676716ae09aa2abe34c1c9b9cf426e68a/casadi/core/generic_expression.hpp#L485) it looks like both `x` and `y` would have the same type.

**Comment by jgillis** [comment]
Please comment on my forum response if further help is needed.
