### ISSUE TITLE
NMPC to Linear MPC formulation

### ISSUE THREAD

**Issue by ptrem** [casadi/casadi#2800]
Hey guys,
I'm trying to linearize a NMPC.
The problem is a nonlinear cart pendulum.
My nonlinear model looks like:

```
def cartpend(x, u):
    m = 1
    M = 5
    L = 2
    g = -9.81
    d = 1
    
    Sx = ca.sin(x[2])
    Cx = ca.cos(x[2])
    D = m*L**2*(M+m*(1-Cx**2))
    dxdt = [x[1],
            (1/D)*(-m**2*L**2*g*Cx*Sx+m*L**2*(m*L*x[3]**2*Sx-d*x[1]))+m*L**2*(1/D)*u,
            x[3],
            (1/D)*((m+M)*m*g*L*Sx-m*L*Cx*(m*L*x[3]**2*Sx-d*x[1]))-m*L*Cx*(1/D)*u
            ]
    return ca.vertcat(*dxdt)
```

Now I try to linearize this NLP around the point xp,up.
I implemented two different linearizations.

First using the casadi jacobian function
```
def cartpend_lin(x, u, xp, up):
    A = ca.jacobian(cartpend(xp, up), xp)
    B = ca.jacobian(cartpend(xp, up), up)
    return cartpend(xp,up)+A@(x-xp)+B@(u-up)

RHS = cartpend(states, controls)
f =  ca.Function('f', [states, controls], [RHS])
```
And second using the casadi linearization tool directly.

```
RHS_lin = ca.linearize(RHS, ca.vertcat(states,controls), ca.vertcat(XP,UP))
f_lin = ca.Function('f_lin',[states, controls, XP, UP], [RHS_lin])
```

The fist method works quite fine while linearizing around a fixed point but struggles while linearizing around the current state point.
The second methond didn't work in any case.

Any suggestions how to linearize the model in an optimal way?

Thanks

**Comment by gmsanchez** [comment]
I haven't tried your example, but maybe you could look at this repository [mpc_comparison_rpic2017](https://github.com/gmsanchez/mpc_comparison_rpic2017). It has a non-linear MPC formulation using multiple shooting, collocation, linear time varying approximations using the Jacobian for discretization. Hope it helps!

**Comment by ptrem** [comment]
Hi Guido,
thanks for your response, but I've already got my code running.

Kind regards
Philipp

Von: Guido Sanchez ***@***.***>
Gesendet: Montag, 19. Juli 2021 21:23
An: casadi/casadi ***@***.***>
Cc: Philipp Gerard Trémuel ***@***.***>; Author ***@***.***>
Betreff: Re: [casadi/casadi] NMPC to Linear MPC formulation (#2800)


I haven't tried your example, but maybe you could look at this repository mpc_comparison_rpic2017<https://github.com/gmsanchez/mpc_comparison_rpic2017>. It has a non-linear MPC formulation using multiple shooting, collocation, linear time varying approximations using the Jacobian for discretization. Hope it helps!

**Comment by rakeshv24** [comment]
@ptrem How did you finally end up linearizing the system around the current state point? It would really help to know how to use CasAdi for this purpose. Thanks in advance!

**Comment by ptrem** [comment]
> 

Hi @rakeshv24 
the problem was not the linearization function itself. 
It was more the usage of the right fixpoint in the parameter vector.

I have published some implementations on my repository.
https://github.com/ptrem/mpc_control_cart_pendulum.git

Kind regards
Philipp

**Comment by rakeshv24** [comment]
Thank you @ptrem!
