### ISSUE TITLE
Undefined function or variable 'collocation_points'.

### ISSUE THREAD

**Issue by ChuongCS** [casadi/casadi#2804]
Hi,

When I run your code: direct_collocation_opti.m, it shows the error that 

Undefined function or variable 'collocation_points'.

I have tried to search around but I have not found where collocation_points() function is defined.

I'd really appreciate if you can help me figure out.

Thank you

**Comment by jaeandersson** [comment]
It's defined in <casadi root>/casadi/core/integration_tools.hpp.

You should be able to call it directly from MATLAB:
```
>> casadi.collocation_points(3)

ans =

    0.1551    0.6449    1.0000

```

**Comment by ChuongCS** [comment]
Hi Jaeandersson,
Thanks for pointing it out. I'd appreciate it.

I have tried to call casadi.collocation_points(3) from command window, but it show:

>> casadi.collocation_points(3)

      **_Unrecognized function or variable 'casadiMEX'._**

Moreover, when I run the direct_collocation_opti.m, it still shows the same issue.


Could you please help me figure out this issue?

**Comment by ChuongCS** [comment]
Thanks Jaeandersson, it is fixed now.
