### ISSUE TITLE
Specifying analytical derivatives

### ISSUE THREAD

**Issue by alaurenzi** [casadi/casadi#2809]
Hi to all users/maintainers of the amazing CasADi :)
I'm dealing with an application that involves the evaluation of a `casadi.Function` say `F(x, u)` inside the cost/constraints of an ipopt problem. Casadi will internally compute first and second derivatives to provide to ipopt as needed, and everything works fine. However, I happen to have analytical expressions for the first derivatives, computed by some library in a (let's say) computationally efficient way. I have a couple of questions regarding such a scenario:

 1) from the documentation/literature, I understand that CasADi implements efficient methods for computing the jacobian-vector product, whereas computing the full jacobian should not be expected to be as efficient. Does ipopt need the full jacobian (= "inefficient") or just the above-mentioned products (= "efficient")?
 2) what about the hessian computation? would it be considerably faster if I could provide analytical jacobians?
 3) is there a way for casadi to use my own derivatives `dFdx` and `dFdu`, such as from the `factory` class, so I can test the difference in performance?

Many thanks for your time,
Arturo

**Comment by jgillis** [comment]
Jacobian-vector products (aka forward or reverse sensitivities) form the basis functionality with which Jacobians could be constructed. If the Jacobian is sparse, this can be performed efficiently.
Ipopt is not a matrix-free solver; it will need the entire (sparse) constraint Jacobian to perform its work.
There are certainly cases where analytical Jacobians yield faster code. Hessians are typically not sped up: the most efficient way to compute a Hessian is a single reverse mode sweep followed by forward mode sweeps. A reverse mode is like computing a Jacobian-transpose times a vector without the need to construct the Jacobian first, probably much cheaper than a full Jacobian constructed by any means. The ideal action would be then to provide an analytical reverse mode.

You could use 'custom_jacobian': YourJacobianFunction and 'ad_penalty':0 options.
Look at `f.jacobian()`  to learn what input/output scheme is expected from `custom_jacobian`.

If you need the Hessian too, you could switch to another strategy and implement F as a Callback.

We are aware that our API is not really friendly for such task
