### ISSUE TITLE
CasADi crashes when trying to use SNOPT on Ubuntu 16

### ISSUE THREAD

**Issue by spenrich** [casadi/casadi#2810]
I'm trying to build and run CasADi 3.5.5 with SNOPT 7.6 support on Ubuntu 16.04. I've built and installed SNOPT 7.6 libraries to `$HOME/src/snopt/lib`, and set some relevant environment variables:
```bash
# SNOPT
export SNOPT="$HOME/src/snopt"
export LD_LIBRARY_PATH="$HOME/src/snopt/lib:$LD_LIBRARY_PATH"

# CasADi
export LD_LIBRARY_PATH="$HOME/local/lib:$LD_LIBRARY_PATH"
export PYTHONPATH="$PYTHONPATH:$HOME/local"
```
I then cloned the CasADi master branch (with all submodules) and ran the cmake command:
```bash
cmake \
  -D WITH_IPOPT=ON \
  -D WITH_SNOPT=ON \
  -D SNOPT_LIBRARY:FILEPATH=$SNOPT/lib/libsnopt7.so \
  -D WITH_PYTHON=ON \
  -D WITH_MATLAB=OFF \
  -D CMAKE_INSTALL_PREFIX:PATH=$HOME/local \
  -D PYTHON_PREFIX:PATH=$HOME/local \
  -D PYTHON_LIBRARY:FILEPATH=$HOME/opt/anaconda3/lib/libpython3.9.so \
  -D PYTHON_EXECUTABLE:FILEPATH=$HOME/opt/anaconda3/bin/python \
  -D PYTHON_INCLUDE_DIR:PATH=$HOME/opt/anaconda3/include/python3.9 ..
```
Cmake reports that both Ipopt and SNOPT are found. I then ran `make` and `make install` successfully, but the small Python example:
```python
import casadi as cs
x = cs.SX.sym('x', 2)
f = x[0]**2 + x[1]**2
g = x[0] + x[1] - 10
nlp = {'x': x, 'f': f, 'g': g}
solver_str = 'snopt'
solver = cs.nlpsol('solver', solver_str, nlp)
soln = solver(lbg=0)
print('\n####################################\n')
print('objective at solution = ', soln['f'])
print('primal solution = ', soln['x'])
print('dual solution (x) = ', soln['lam_x'])
print('dual solution (g) = ', soln['lam_g'])
```
but the Python interpreter crashes with the error:
```python-traceback
/home/spenrich/opt/anaconda3/bin/python: symbol lookup error: /home/spenrich/local/lib/libcasadi_nlpsol_snopt.so: undefined symbol: sninitf_
```
Any advice on what may be going wrong? Related issue from the Google forum: [https://groups.google.com/g/casadi-users/c/MM0ogLOgmaU](https://groups.google.com/g/casadi-users/c/MM0ogLOgmaU). Is CasADi 3.5.5 perhaps incompatible with SNOPT 7.6?

**Comment by jgillis** [comment]
Try updating the submodule found in `<casadi_source_dir>/external_packages/snopt-interface/snopt-interface` It may be out of date for newer SNOPT

**Comment by spenrich** [comment]
Thanks @jgillis! Ultimately not a CasADi bug -- I needed to downgrade `snopt-interface` to tag `v2.0.0` to be compatible with SNOPT 7.6. Anything newer relies on subroutines introduced in SNOPT 7.7. Closing this.
