### ISSUE TITLE
issue setting tolerances for IPOPT solver

### ISSUE THREAD

**Issue by huckl3b3rry87** [casadi/casadi#2812]
Hi, I am trying to relax some of the tolerances on feasibility for the optimization using the opti interface
```
		p_opts = {"expand": True, "print_time": False}
		s_opts = {"max_cpu_time": 0.1, 
				  "print_level": 0, 
				  "tol": 5e-1, 
				  "dual_inf_tol": 5.0, 
				  "constr_viol_tol": 1e-1,
				  "compl_inf_tol": 1e-1, 
				  "acceptable_tol": 1e-2, 
				  "acceptable_constr_viol_tol": 0.01, 
				  "acceptable_dual_inf_tol": 1e10,
				  "acceptable_compl_inf_tol": 0.01,
				  "acceptable_obj_change_tol": 1e20,
				  "diverging_iterates_tol": 1e20}
		opti.solver('ipopt', p_opts, s_opts)
```
but I am still getting infeasible problems with constraint violation that are smaller than these tolerances.  

For instance, after optimization when I run
```
opti.debug.show_infeasibilities()
```
I get a bunch of small violations
```
0 <= -2.56261e-11 <= 0 (viol 2.56261e-11)
```

any ideas? Thanks!

**Comment by jgillis** [comment]
perhaps the tolerances are on the scaled problem? Try shutting off ipopt scaling

**Comment by huckl3b3rry87** [comment]
@jgillis thank you so much for the quick response! I added ``"nlp_scaling_method": "none" `` to ``s_opts`` ( I think that is how I would turn off scaling?) and it did not seem to change things

**Comment by huckl3b3rry87** [comment]
ahh, seems like casadi is working fine, passing the options that I expected to Ipopt - I see this when I print more info from Ipopt.  
Thank you!

**Comment by marios-stam** [comment]
Hello I am having a similar problem, not matter what options I set I get the following using `opti.debug.show_infeasibilities()`
![image](https://github.com/casadi/casadi/assets/37310507/c9bfb48d-c3fe-452f-981a-0fb279898d41)

`(tol 0)` remains the same no matter what

Could you please help me?

**Comment by tobnie** [comment]
I am having the same issue, I did not get how you resolved it though, @huckl3b3rry87. How did you do it?
