### ISSUE TITLE
Apple Sillicon installation

### ISSUE THREAD

**Issue by fst2112** [casadi/casadi#2829]
I tried to install Casadi via pip on my M1 MacBook Pro and got an error:

```
$ pip install casadi
ERROR: Could not find a version that satisfies the requirement casadi (from versions: none)
ERROR: No matching distribution found for casadi
```

Is there a way to install Casadi on M1-MacBook?

Thanks for your help!

**Comment by lukasloetkolben** [comment]
I have the same problem. Did you found any solution?

**Comment by Haugann** [comment]
Same issue. Anyone got any tips?

**Comment by lukasloetkolben** [comment]
I build it from source.

```
git clone https://github.com/casadi/casadi.git casadi
cd casadi
git checkout 3.5.5
mkdir build
cd build
cmake -DWITH_PYTHON=ON -DWITH_PYTHON3=ON ..
make
sudo make install
```

**Comment by Haugann** [comment]
> I build it from source.
> 
> ```
> git clone https://github.com/casadi/casadi.git casadi
> cd casadi
> git checkout 3.5.5
> mkdir build
> cd build
> cmake -DWITH_PYTHON=ON -DWITH_PYTHON3=ON ..
> make
> sudo make install
> ```

I got it built, but after adding the build/casadi directory to the site-packages I get the following error when importing casadi:

`>>> from casadi import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/anaconda3/lib/python3.8/site-packages/casadi/__init__.py", line 36, in <module>
    from casadi.casadi import *
  File "~/anaconda3/lib/python3.8/site-packages/casadi/casadi.py", line 13, in <module>
    from . import _casadi
ImportError: dlopen(~/anaconda3/lib/python3.8/site-packages/casadi/_casadi.so, 2): no suitable image found.  Did find:
	~/anaconda3/lib/python3.8/site-packages/casadi/_casadi.so: mach-o, but wrong architecture
	~/anaconda3/lib/python3.8/site-packages/casadi/_casadi.so: stat() failed with errno=13`

**Comment by smurfd** [comment]
Hey, is there some dependency that causes Casadi 3.5.5 not to work with newest stable xcode and python 3.8.x on mac M1, macos 12.1?
I build casadi from source like mentioned above, it builds fine.

But when i try to import it though, i get this : 
```
Python 3.8.12 (default, Oct 12 2021, 22:38:27) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import casadi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.8/site-packages/casadi/__init__.py", line 36, in <module>
    from casadi.casadi import *
  File "/opt/homebrew/lib/python3.8/site-packages/casadi/casadi.py", line 13, in <module>
    from . import _casadi
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/casadi/_casadi.so, 0x0002): symbol not found in flat namespace '_PyCMethod_New'
```
Could it have todo with to new version of Clang?

**Comment by KexianShen** [comment]
I don't have conda but pyenv.

```bash
clang --version                                         
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```bash
pyenv shell 3.9.7
git clone --depth 1 https://github.com/casadi/casadi.git
cd casadi 
mkdir build 
cd build 
cmake -DWITH_PYTHON3=ON ..    
make -j6  
sudo make install   
```

```python
import casadi    # works fine
```

**Comment by MattBrth** [comment]
after building from source, and running sudo make install , i get this trying to use it : 

`import casadi
  File "/Users/matteo/.pyenv/versions/3.9.12/lib/python3.9/site-packages/casadi/__init__.py", line 36, in <module>
    from casadi.casadi import *
  File "/Users/matteo/.pyenv/versions/3.9.12/lib/python3.9/site-packages/casadi/casadi.py", line 13, in <module>
    from . import _casadi
ImportError: dlopen(/Users/matteo/.pyenv/versions/3.9.12/lib/python3.9/site-packages/casadi/_casadi.so, 0x0002): tried: '/Users/matteo/.pyenv/versions/3.9.12/lib/python3.9/site-packages/casadi/_casadi.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`
How can I manage this ?

**Comment by jgillis** [comment]
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by jgillis** [comment]
M1 wheels are now available for testing at https://github.com/casadi/casadi/releases/tag/nightly-develop
`pip install <url obtained from the appropriate whl files>`

**Comment by tudoroancea** [comment]
I tried to download the following wheel in a freshly created Python 3.9.6 venv: https://github.com/casadi/casadi/releases/download/nightly-develop/casadi-3.5.5.dev+develop.c1efa4a-cp39-none-macosx_11_0_arm64.whl
However when trying to run `from casadi import *` I face the following error:
```python
>>> from casadi import *
Traceback (most recent call last):
  File "/Users/tudoroancea/Developer/misc/casadi_test/venv/lib/python3.9/site-packages/casadi/casadi.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: dlopen(/Users/tudoroancea/Developer/misc/casadi_test/venv/lib/python3.9/site-packages/casadi/_casadi.so, 0x0002): Symbol not found: __ZN6casadi6MatrixINS_6SXElemEE10_logsumexpERKS2_
  Referenced from: <C2D927C6-C675-3AC2-BB36-FE83334160E9> /Users/tudoroancea/Developer/misc/casadi_test/venv/lib/python3.9/site-packages/casadi/_casadi.so
  Expected in:     <1FE6ABEE-DFCC-38F2-9B47-79629F9C4DC9> /usr/local/lib/libcasadi.3.6.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tudoroancea/Developer/misc/casadi_test/venv/lib/python3.9/site-packages/casadi/__init__.py", line 36, in <module>
    from casadi.casadi import *
  File "/Users/tudoroancea/Developer/misc/casadi_test/venv/lib/python3.9/site-packages/casadi/casadi.py", line 21, in <module>
    _casadi = swig_import_helper()
  File "/Users/tudoroancea/Developer/misc/casadi_test/venv/lib/python3.9/site-packages/casadi/casadi.py", line 20, in swig_import_helper
    return importlib.import_module('_casadi')
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_casadi'
```
For some reason it tries to import a .so file, which is absurd on macos. The files exists nonetheless and the other dynamic libraries (in the right .dylib format) seem to be in order.
Did I do something wrong?

**Comment by jgillis** [comment]
"/usr/local/lib/libcasadi.3.6.dylib" looks wrong, can you remove that global installation?

**Comment by tudoroancea** [comment]
That did the trick! Thanks!

**Comment by LUZWang** [comment]
When I run 'cmake -DWITH_PYTHON=ON -DWITH_PYTHON3=ON ..'.... _Anyone know what is going on?_

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at CMakeLists.txt:31 (cmake_policy):
  The OLD behavior for policy CMP0011 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:35 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Flag needed for enabling C++11 features: -std=c++11
CMake Deprecation Warning at swig/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at /opt/homebrew/Cellar/cmake/3.25.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.25.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.25.3/share/cmake/Modules/FindSWIG.cmake:153 (find_package_handle_standard_args)
  swig/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/chronos_c/casadi/build/CMakeFiles/CMakeOutput.log".
See also "/Users/chronos_c/casadi/build/CMakeFiles/CMakeError.log".

**Comment by gy2256** [comment]
I could not build the 3.5.5 from source 
```
[ 44%] Building CXX object casadi/core/CMakeFiles/casadi.dir/einstein.cpp.o
[ 44%] Building CXX object casadi/core/CMakeFiles/casadi.dir/casadi_call.cpp.o
[ 44%] Building CXX object casadi/core/CMakeFiles/casadi.dir/casadi_find.cpp.o
[ 45%] Building CXX object casadi/core/CMakeFiles/casadi.dir/casadi_low.cpp.o
[ 45%] Building CXX object casadi/core/CMakeFiles/casadi.dir/norm.cpp.o
[ 45%] Building CXX object casadi/core/CMakeFiles/casadi.dir/mmin.cpp.o
[ 46%] Building CXX object casadi/core/CMakeFiles/casadi.dir/transpose.cpp.o
[ 46%] Building CXX object casadi/core/CMakeFiles/casadi.dir/concat.cpp.o
[ 47%] Building CXX object casadi/core/CMakeFiles/casadi.dir/split.cpp.o
[ 47%] Building CXX object casadi/core/CMakeFiles/casadi.dir/reshape.cpp.o
[ 47%] Building CXX object casadi/core/CMakeFiles/casadi.dir/subref.cpp.o
[ 48%] Building CXX object casadi/core/CMakeFiles/casadi.dir/subassign.cpp.o
[ 48%] Building CXX object casadi/core/CMakeFiles/casadi.dir/getnonzeros.cpp.o
[ 48%] Building CXX object casadi/core/CMakeFiles/casadi.dir/getnonzeros_param.cpp.o
[ 49%] Building CXX object casadi/core/CMakeFiles/casadi.dir/project.cpp.o
[ 49%] Building CXX object casadi/core/CMakeFiles/casadi.dir/determinant.cpp.o
[ 49%] Building CXX object casadi/core/CMakeFiles/casadi.dir/inverse.cpp.o
[ 50%] Building CXX object casadi/core/CMakeFiles/casadi.dir/dot.cpp.o
[ 50%] Building CXX object casadi/core/CMakeFiles/casadi.dir/bilin.cpp.o
[ 50%] Building CXX object casadi/core/CMakeFiles/casadi.dir/rank1.cpp.o
[ 51%] Building CXX object casadi/core/CMakeFiles/casadi.dir/multiple_output.cpp.o
[ 51%] Building CXX object casadi/core/CMakeFiles/casadi.dir/assertion.cpp.o
[ 51%] Building CXX object casadi/core/CMakeFiles/casadi.dir/monitor.cpp.o
[ 52%] Building CXX object casadi/core/CMakeFiles/casadi.dir/repmat.cpp.o
[ 52%] Building CXX object casadi/core/CMakeFiles/casadi.dir/convexify.cpp.o
[ 52%] Building CXX object casadi/core/CMakeFiles/casadi.dir/function.cpp.o
[ 52%] Building CXX object casadi/core/CMakeFiles/casadi.dir/oracle_function.cpp.o
[ 53%] Building CXX object casadi/core/CMakeFiles/casadi.dir/function_internal.cpp.o
[ 53%] Building CXX object casadi/core/CMakeFiles/casadi.dir/callback.cpp.o
[ 54%] Building CXX object casadi/core/CMakeFiles/casadi.dir/callback_internal.cpp.o
[ 54%] Building CXX object casadi/core/CMakeFiles/casadi.dir/sx_function.cpp.o
[ 54%] Building CXX object casadi/core/CMakeFiles/casadi.dir/mx_function.cpp.o
[ 55%] Building CXX object casadi/core/CMakeFiles/casadi.dir/external.cpp.o
[ 55%] Building CXX object casadi/core/CMakeFiles/casadi.dir/jit_function.cpp.o
[ 55%] Building CXX object casadi/core/CMakeFiles/casadi.dir/linsol.cpp.o
[ 56%] Building CXX object casadi/core/CMakeFiles/casadi.dir/linsol_internal.cpp.o
[ 56%] Building CXX object casadi/core/CMakeFiles/casadi.dir/rootfinder.cpp.o
[ 56%] Building CXX object casadi/core/CMakeFiles/casadi.dir/integrator.cpp.o
[ 57%] Building CXX object casadi/core/CMakeFiles/casadi.dir/nlpsol.cpp.o
[ 57%] Building CXX object casadi/core/CMakeFiles/casadi.dir/conic.cpp.o
[ 57%] Building CXX object casadi/core/CMakeFiles/casadi.dir/dple.cpp.o
[ 58%] Building CXX object casadi/core/CMakeFiles/casadi.dir/interpolant.cpp.o
[ 58%] Building CXX object casadi/core/CMakeFiles/casadi.dir/expm.cpp.o
[ 58%] Building CXX object casadi/core/CMakeFiles/casadi.dir/code_generator.cpp.o
[ 59%] Building CXX object casadi/core/CMakeFiles/casadi.dir/switch.cpp.o
[ 59%] Building CXX object casadi/core/CMakeFiles/casadi.dir/bspline.cpp.o
[ 59%] Building CXX object casadi/core/CMakeFiles/casadi.dir/map.cpp.o
[ 60%] Building CXX object casadi/core/CMakeFiles/casadi.dir/mapsum.cpp.o
[ 60%] Building CXX object casadi/core/CMakeFiles/casadi.dir/finite_differences.cpp.o
[ 61%] Building CXX object casadi/core/CMakeFiles/casadi.dir/importer.cpp.o
[ 61%] Building CXX object casadi/core/CMakeFiles/casadi.dir/importer_internal.cpp.o
[ 61%] Building CXX object casadi/core/CMakeFiles/casadi.dir/integration_tools.cpp.o
[ 62%] Building CXX object casadi/core/CMakeFiles/casadi.dir/nlp_tools.cpp.o
[ 62%] Building CXX object casadi/core/CMakeFiles/casadi.dir/nlp_builder.cpp.o
[ 62%] Building CXX object casadi/core/CMakeFiles/casadi.dir/xml_node.cpp.o
[ 63%] Building CXX object casadi/core/CMakeFiles/casadi.dir/xml_file.cpp.o
[ 63%] Building CXX object casadi/core/CMakeFiles/casadi.dir/xml_file_internal.cpp.o
[ 63%] Building CXX object casadi/core/CMakeFiles/casadi.dir/variable.cpp.o
[ 64%] Building CXX object casadi/core/CMakeFiles/casadi.dir/dae_builder.cpp.o
[ 64%] Building CXX object casadi/core/CMakeFiles/casadi.dir/optistack.cpp.o
[ 64%] Building CXX object casadi/core/CMakeFiles/casadi.dir/optistack_internal.cpp.o
[ 65%] Building CXX object casadi/core/CMakeFiles/casadi.dir/serializer.cpp.o
[ 65%] Building CXX object casadi/core/CMakeFiles/casadi.dir/serializing_stream.cpp.o
[ 65%] Building CXX object casadi/core/CMakeFiles/casadi.dir/casadi_c.cpp.o
/Users/mac/research_code/others_code/casadi/casadi/core/casadi_c.cpp:222:10: warning: returning address of local temporary object [-Wreturn-stack-address]
  return casadi_c_loaded_functions.at(id).name().c_str();
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[ 66%] Linking CXX shared library ../../lib/libcasadi.dylib
[ 66%] Built target casadi
[ 66%] Swig source
Deprecated command line option: -noproxydel. Ignored, this option is now always on.
Deprecated command line option: -fastunpack. Ignored, this option is now always on.
Deprecated command line option: -modernargs. Ignored, this option is now always on.
Deprecated command line option: -py3. Ignored, this option is no longer supported.
:3: Error: Unable to find 'python.swg'
/opt/local/share/swig/4.1.1/stl.i:5: Warning 204: CPP #warning, ""stl.i not implemented for this target"".
[ 67%] Building CXX object casadi/interfaces/tinyxml/CMakeFiles/casadi_xmlfile_tinyxml.dir/tinyxml_interface.cpp.o
[ 67%] Building CXX object casadi/interfaces/sundials/CMakeFiles/casadi_rootfinder_kinsol.dir/kinsol_interface.cpp.o
[ 67%] Building CXX object casadi/interfaces/sundials/CMakeFiles/casadi_sundials_common.dir/sundials_interface.cpp.o
[ 68%] Building CXX object casadi/interfaces/csparse/CMakeFiles/casadi_linsol_csparse.dir/csparse_interface.cpp.o
[ 69%] Building CXX object casadi/interfaces/csparse/CMakeFiles/casadi_linsol_csparsecholesky.dir/csparse_cholesky_interface.cpp.o
[ 69%] Building CXX object casadi/solvers/CMakeFiles/casadi_rootfinder_nlpsol.dir/implicit_to_nlp.cpp.o
[ 69%] Building CXX object casadi/solvers/CMakeFiles/casadi_conic_nlpsol.dir/qp_to_nlp.cpp.o
make[2]: *** [swig/casadiPYTHON_wrap.cxx] Error 1
make[1]: *** [swig/python/CMakeFiles/_casadi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 69%] Building CXX object casadi/interfaces/tinyxml/CMakeFiles/casadi_xmlfile_tinyxml.dir/tinyxml_interface_meta.cpp.o
[ 69%] Building CXX object casadi/interfaces/sundials/CMakeFiles/casadi_rootfinder_kinsol.dir/kinsol_interface_meta.cpp.o
[ 69%] Building CXX object casadi/interfaces/csparse/CMakeFiles/casadi_linsol_csparsecholesky.dir/csparse_cholesky_interface_meta.cpp.o
[ 69%] Building CXX object casadi/interfaces/csparse/CMakeFiles/casadi_linsol_csparse.dir/csparse_interface_meta.cpp.o
[ 69%] Linking CXX shared library ../../../lib/libcasadi_xmlfile_tinyxml.dylib
[ 69%] Building CXX object casadi/solvers/CMakeFiles/casadi_rootfinder_nlpsol.dir/implicit_to_nlp_meta.cpp.o
[ 69%] Building CXX object casadi/solvers/CMakeFiles/casadi_conic_nlpsol.dir/qp_to_nlp_meta.cpp.o
[ 69%] Built target casadi_xmlfile_tinyxml
[ 70%] Linking CXX shared library ../../../lib/libcasadi_sundials_common.dylib
[ 70%] Built target casadi_sundials_common
[ 71%] Linking CXX shared library ../../../lib/libcasadi_rootfinder_kinsol.dylib
[ 71%] Built target casadi_rootfinder_kinsol
[ 71%] Linking CXX shared library ../../../lib/libcasadi_linsol_csparse.dylib
[ 71%] Linking CXX shared library ../../../lib/libcasadi_linsol_csparsecholesky.dylib
[ 71%] Built target casadi_linsol_csparse
[ 71%] Built target casadi_linsol_csparsecholesky
[ 72%] Linking CXX shared library ../../lib/libcasadi_rootfinder_nlpsol.dylib
[ 73%] Linking CXX shared library ../../lib/libcasadi_conic_nlpsol.dylib
[ 73%] Built target casadi_rootfinder_nlpsol
[ 73%] Built target casadi_conic_nlpsol
make: *** [all] Error 2
```

**Comment by inzombakura** [comment]
> When I run 'cmake -DWITH_PYTHON=ON -DWITH_PYTHON3=ON ..'.... _Anyone know what is going on?_
> 
> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required): Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
> 
> Update the VERSION argument value or use a ... suffix to tell CMake that the project does not need compatibility with older versions.
> 
> CMake Deprecation Warning at CMakeLists.txt:31 (cmake_policy): The OLD behavior for policy CMP0011 will be removed from a future version of CMake.
> 
> The cmake-policies(7) manual explains that the OLD behaviors of all policies are deprecated and that a policy should be set to OLD only under specific short-term circumstances. Projects should be ported to the NEW behavior and not rely on setting a policy to OLD.
> 
> CMake Deprecation Warning at CMakeLists.txt:35 (cmake_policy): The OLD behavior for policy CMP0005 will be removed from a future version of CMake.
> 
> The cmake-policies(7) manual explains that the OLD behaviors of all policies are deprecated and that a policy should be set to OLD only under specific short-term circumstances. Projects should be ported to the NEW behavior and not rely on setting a policy to OLD.
> 
> -- Flag needed for enabling C++11 features: -std=c++11 CMake Deprecation Warning at swig/CMakeLists.txt:1 (cmake_minimum_required): Compatibility with CMake < 2.8.12 will be removed from a future version of CMake.
> 
> Update the VERSION argument value or use a ... suffix to tell CMake that the project does not need compatibility with older versions.
> 
> CMake Error at /opt/homebrew/Cellar/cmake/3.25.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) Call Stack (most recent call first): /opt/homebrew/Cellar/cmake/3.25.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE) /opt/homebrew/Cellar/cmake/3.25.3/share/cmake/Modules/FindSWIG.cmake:153 (find_package_handle_standard_args) swig/CMakeLists.txt:4 (find_package)
> 
> -- Configuring incomplete, errors occurred! See also "/Users/chronos_c/casadi/build/CMakeFiles/CMakeOutput.log". See also "/Users/chronos_c/casadi/build/CMakeFiles/CMakeError.log".

I did `brew install swig`
