### ISSUE TITLE
`casadi.interpolant`, with `bspline`: Returning `NaN` for all-zero values.

### ISSUE THREAD

**Issue by peterdsharpe** [casadi/casadi#2837]
I'm using CasADi through Python and seem to have stumbled across this bug in `casadi.interpolant`.

Here is a minimal example:

```python
import numpy as np
import casadi as cas

x = np.array([1, 2, 3, 4, 5])
y = 0 * x

f = cas.interpolant(
    'Interpolator', 'bspline',
    [x],
    y,
)(np.array([3]))

print(f) # Returns DM(nan), not 0.
```

Expected behavior is that `f` returns the value of `0`.

Here's where it gets interesting. If I change line 5 as follows:

`y = 0 * x` --> `y = 1 * x`

then `f` is no longer `DM(nan)`, and correctly returns a numeric value. This is true for any non-zero multiplier on `x`; only `0 * x` causes an error. I don't believe it's an "int vs. float" issue, since `0. * x` still produces a `NaN`. In fact, the only time that this error occurs is if `y` is an array where all entries are exactly `0`.

The error also appears restricted to the `bspline` interpolant; replacing `'bspline'` with `'linear'` returns the correct numeric result for `f`.

-----
I'm running Python 3.8.11 on Windows 11 with CasADi 3.5.5 from PyPI.

**Comment by jgillis** [comment]
Division by zero happening here: https://github.com/casadi/casadi/blob/master/casadi/core/runtime/casadi_lsqr.hpp#L127
