### ISSUE TITLE
mmin/mmax codegen missing

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2853]

**Comment by XingchenFan** [comment]
Is this related to this error some of us have seen when mmax/mmin is called on MX variables?
'ad_reverse' not defined for class N6casadi4MMinE

**Comment by jaeandersson** [comment]
> Is this related to this error some of us have seen when mmax/mmin is called on MX variables?
'ad_reverse' not defined for class N6casadi4MMinE

Codegen and reverse mode AD support are two separate missing features.
