### ISSUE TITLE
Segmentation fault during parallel Function evaluation (no symbolics in parallel loop)

### ISSUE THREAD

**Issue by Daiver** [casadi/casadi#2854]
Hello! 
I'm trying to evaluate `casadi::Function` in `parallel for` loop but i faced with segmentation fault during function evaluation. 

Here a minimal example
```c++
const SX xSx = SX::sym("x");
const SX resSx = xSx * xSx;
const Function func("func", {xSx}, {resSx});

#pragma omp parallel for
for (int iterInd = 0; iterInd < 10000; ++iterInd){
    DM var = DM::zeros(xSx.numel());
    std::vector<DM> result = func(std::vector<DM>{var}); // <- segmentation fault happens here
}
```
My CasADi version is 3.5.5

As far as i can see something terrible happens inside `SparsityInternal`. 
I know that CasADi's symbolics are not thread-safe, but i thought that `Function` is ok with parallelism (at least according to this [thread](https://github.com/casadi/casadi/issues/1942#issuecomment-276092499) ).

Can someone explain me is it possible to execute `Function` in parallel?

PS Thank you for great library!

**Comment by jgillis** [comment]
Hi Daiver,

Functions can certainly be evaluated in a thread-safe manner. Simply pick one of the more low-level APIs that does not involve symbolics (sparsities in your case, really), e.g. https://github.com/casadi/casadi/blob/3.5.5/casadi/core/function.hpp#L461-L464

**Comment by Daiver** [comment]
Hi @jgillis, thank you for answer!
Is this correct way to call low-level `Function` API? 

```cpp
const SX xSx = SX::sym("x", 3);
const SX resSx = xSx * xSx;
const Function func("func", {xSx}, {resSx});

#pragma omp parallel for
for (int iterInd = 0; iterInd < 10000; ++iterInd){
    std::vector<double> varValue = {1, 2, 3};
    std::vector<double> result(resSx.numel());
    func(std::vector<const double *>{varValue.data()}, {result.data()});
    std::cout << result << std::endl;
}
```
This code works for me, but i want to check it. Do i understand correctly, that `Function(std::vector<const double *> inputs, std::vector<double *> outputs)` expects arrays of non zeros in case of sparse inputs/outputs?
