### ISSUE TITLE
interface gurobi

### ISSUE THREAD

**Issue by ZhuZheart98** [casadi/casadi#2861]
I already install gurobi in my pc(MacBook pro), which can be used. But when I used it by casadi in Python, there shows that:

/Users/zheng/venv/bin/python /Users/zheng/PycharmProjects/study/casadi_example/chain_qp.py
CasADi - 2021-12-28 16:48:42 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_gurobi.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/Users/zheng/venv/lib/python3.8/site-packages/casadi' :
    Error code: dlopen(/Users/zheng/venv/lib/python3.8/site-packages/casadi/libcasadi_conic_gurobi.dylib, 0x0005): Library not loaded: @rpath/libgurobi65.so
  Referenced from: /Users/zheng/venv/lib/python3.8/site-packages/casadi/libcasadi_conic_gurobi.dylib
  Reason: tried: '/Users/travis/miniconda2/envs/co... truncated") [.../casadi/core/plugin_interface.hpp:171]
Traceback (most recent call last):
  File "/Users/zheng/PycharmProjects/study/casadi_example/chain_qp.py", line 118, in <module>
    solver = qpsol('solver', 'gurobi', qp)
  File "/Users/zheng/venv/lib/python3.8/site-packages/casadi/casadi.py", line 15649, in qpsol
    return _casadi.qpsol(*args)
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'gurobi' is not found.

And qpoases is the same. But ipopt and bonmin can be used as normal. I added "export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HOME/Users/zheng/venv/lib/python3.8/site-packages/casadi
" in my ~/.bash_profile. How can I use gurobi and qpoases in python or matlab?

**Comment by jaeandersson** [comment]
Do you have `libgurobi65.so` in your path? It looks like it's not found at runtime.

**Comment by ZhuZheart98** [comment]
OK, thanks. I already put `libgurobi95.so` in my path. Does casadi only support gurobi 6.5? The qpoases solver is installed in casadi. And why is qpoases solver the same?

CasADi - 2022-01-26 12:33:10 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_qpoases.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/Users/zheng/venv/lib/python3.8/site-packages/casadi' :
    Error code: dlopen(/Users/zheng/venv/lib/python3.8/site-packages/casadi/libcasadi_conic_qpoases.dylib, 0x0005): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/zheng/venv/lib/python3.8/site-packages/casadi/libcasadi_conic_qpoases.dylib
  Reason: tried: '/Users/travis/minico... truncated") [.../casadi/core/plugin_interface.hpp:171]
Traceback (most recent call last):
  File "/Users/zheng/PycharmProjects/study/casadi_example/chain_qp.py", line 116, in <module>
    solver = qpsol('solver', 'qpoases', qp, {'sparse':True})
  File "/Users/zheng/venv/lib/python3.8/site-packages/casadi/casadi.py", line 15649, in qpsol
    return _casadi.qpsol(*args)
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'qpoases' is not found.

**Comment by jaeandersson** [comment]
> OK, thanks. I already put libgurobi95.so in my path. Does casadi only support gurobi 6.5?

Probably your CasADi binary was compiled with support for Gurobi 6.5 only. You might need to compile CasADi yourself from sources to be able to use Gurobi 9.5.

The qpOASES issue looks like a problem with binary incompatibility. The plugin loading fails due to some missing system library (libmkl_intel_lp64.dylib). Compiling from sources might resolve this too.

@jgillis knows better the state of the OSX binaries. I always compile CasADi from sources on OSX, using dependencies from Homebrew.

**Comment by ZhuZheart98** [comment]
Sorry about these days. I'm on my holiday about the Chinese new year. 

Thanks, and I will try to compile it myself. But I know a little about compiling. Does the compilation of CasADi have some examples ?

**Comment by lalajiayou** [comment]
hi, everybody. I wish you have solved this problem.
I'm now encountering the same problem, and I want to call the Gurobi academic solver. There is a FAQ: how to get third party solvers to work? (at https://github.com/casadi/casadi/wiki/FAQ:-how-to-get-third-party-solvers-to-work%3F), and I've made some attempts, but I still can't make it happen. I wonder if it is convenient for you to provide some help.
Looking forward to your reply!

**Comment by ZhuZheart98** [comment]
hello, I didn't solve this problem. Because I don't know how to compile gurobi. When I tried, I think maybe the gurbi 6.5.0 is the version that is suitable for CasADi. But the up-to-date version of gurobi is 9.5.2 . So I give up, and use the language designed for gurobi to solve my problem. I suggest you this.

**Comment by lalajiayou** [comment]
您好，已经收到您发来的邮件，会尽快给您回复。

**Comment by jgillis** [comment]
Current develop builds feature an 'adaptor' for gurobi that will accept libraries versioned by gurobi.

**Comment by lalajiayou** [comment]
您好，已经收到您发来的邮件，会尽快给您回复。

**Comment by ZhuZheart98** [comment]
the latest one in github？

**Comment by ZhuZheart98** [comment]
Thanks, I will try it

**Comment by jgillis** [comment]
https://github.com/casadi/casadi/releases/tag/nightly-develop

**Comment by gy2256** [comment]
How does the adaptor work? Any instructions?

**Comment by arun-pn** [comment]
Any updates on this issue? I am also trying to use gurobi solver in casadi to solve an MINLP problem. I have obtained a gurobi academic license, installed gurobi 11.0.1 in anaconda Python version 3.9.12. But the libcasadi_nlpsol_gurobi.dll file is missing in the installation whereas i can find the file libgurobi_adaptor.dll. So, my question is how can i use this file (libgurobi_adaptor.dll) to link the solver in casadi? Thank you

**Comment by ZhuZheart98** [comment]
> Any updates on this issue? I am also trying to use gurobi solver in casadi to solve an MINLP problem. I have obtained a gurobi academic license, installed gurobi 11.0.1 in anaconda Python version 3.9.12. But the libcasadi_nlpsol_gurobi.dll file is missing in the installation whereas i can find the file libgurobi_adaptor.dll. So, my question is how can i use this file (libgurobi_adaptor.dll) to link the solver in casadi? Thank you

i also wnat to ask this

**Comment by arun-pn** [comment]
Sorry, a follow up of what I posted earlier..
I have installed gurobi 11.0.1 in Anaconda Python 3.9.12, and the casadi version 3.6.5. The casadi version does not contain the libcasadi_nlpsol_gurobi.dll file, but has libgurobi_adaptor.dll file. So my question is how can I use the libgurobi_adaptor.dll file to link gurobi solver in casadi?
