### ISSUE TITLE
Bug in convexify eigen-reflect?

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2896]
```
from casadi import *
A = blockcat([[4,-4,0],[-4,10,0],[0,0,2]])
print(A,np.linalg.eig(A))
print(evalf(convexify(A,{"strategy":"eigen-reflect"})))
print(evalf(convexify(sparsify(A),{"strategy":"eigen-reflect"})))
```

**Comment by jgillis** [comment]
Reproduces in tri-diagonalize ->un-tri-diagonalize roundtrip, disabling all other algorithms.

**Comment by jgillis** [comment]
Bug dissappears for any `eps!=0` for `A = blockcat([[4,-4,eps],[-4,10,0],[eps,0,2]])`.
Caused by `sigma==0` clause in `casadi_cvx_house`

**Comment by victorfors** [comment]
There seems to be a typo in this fix in [casadi_cvx.hpp](https://github.com/jcotem/casadi/commit/32afcb34a2bee0b3c13254e09184d66b3d220b39#diff-f623258010c33a5968982f506de13c7f5ab05231e6a09d0ce232f55dbc6200fd)

```
// Note: third edition has *beta = 0
// Note: fourth edition has *beta = -2*(v0<0)
*beta = 2*(v0<0);
```

Missing the minus sign `*beta = -2*(v0<0);`
