### ISSUE TITLE
Casadi problem with numpy

### ISSUE THREAD

**Issue by amirsh213** [casadi/casadi#2903]
I'm getting the same error as mentioned in #2743 with the NumPy version 1.22.1 and casadi version 3.5.5. Is this issue fixed? What do you suggest? 

```
Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
```

**Comment by adamhall** [comment]
I am as well. What is the best workaround until 3.6 is released? Is it best to revert to numpy < 1.20?

**Comment by anwesh-reddy001** [comment]
I am also facing the same issue.. Any work around?

**Comment by patrickocal** [comment]
Yep: give up on casadi, cough up a little cash and start using something
actually works: ampl. You will also get within-day replies to your queries
by Bob Fourer (author/developer of ampl).

**Comment by cknoll** [comment]
> give up on casadi, cough up a little cash and start using something
actually works ...

I cannot support this view. The CasADi software helped us to achieve very nice results, e.g. for the swing up of the triple pendulum, see this video: https://tu-dresden.de/ing/elektrotechnik/rst/studium/laborversuchsstaende#

**Comment by jgillis** [comment]
In current develop branch ( https://github.com/casadi/casadi/releases/tag/nightly-develop ) runs fine up to the latest numpy (`1.24.2`). Please open a new issue if your code still fails with these wheels.

**Comment by KehanLong** [comment]
I installed casadi 3.5.5 with pip and the numpy issues are still there. Can you tell me how to install those latest develop branch in an anaconda virtual env?
