### ISSUE TITLE
Installation issue with pip

### ISSUE THREAD

**Issue by Kumudaya** [casadi/casadi#2904]
The installation of `pip install casadi` does not work for python 3.9.10

The terminal output shows:

ERROR: casadi from git+https://github.com/casadi/casadi.git#egg=casadi does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by jgillis** [comment]
Can you describe your environment?
Python 3.10.* are not yet on pypi, but Python 3.9.* should work..

**Comment by louis-dv** [comment]
I am having the same issue with Python 3.9.7

**Comment by aaaandi** [comment]
On my MacBook Pro (16-inch, 2021) M1 Max with macOS Monterey (version 12.3.1) it works with Python 3.9.11 (see details below).

```
Python 3.9.11 (v3.9.11:2de452f8bf, Mar 16 2022, 10:44:40) 
[Clang 13.0.0 (clang-1300.0.29.30)]
```

My virtual environment on PyCharm CE is set up with the interpreter `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-intel64`. So you need to use the Intel64 version in my opinion. Hope that is helpful!

**Comment by louis-dv** [comment]
I am using pyenv to manage Python versioning. Maybe there's some incompatibility somewhere... Anyway I was able to install the package from source. Thanks!

**Comment by alphaville** [comment]
This issue seems to occuring on Mac M1 (with ARM processor). I've had a couple of users reporting very similar error messages.

**Comment by jgillis** [comment]
Will be resolved in coming release
