### ISSUE TITLE
CommonExternal: Cannot open "./aaa.dll". Error code (WIN32): 126

### ISSUE THREAD

**Issue by beijiguang94** [casadi/casadi#2909]
On my Windows10+python3.8+casadi3.5.1, when running
`my_solver = casadi.nlpsol("solver", "ipopt", "./aaa.dll", ipopt_options)`
an error was reported:
`RuntimeError: .../casadi/core/importer_internal.cpp:229: Assertion "handle_!=0" failed:
CommonExternal: Cannot open "./aaa.dll". Error code (WIN32): 126`
I tried the _casadi.external()_ function according to [the official documentation](https://web.casadi.org/docs/#using-the-generated-code), but it still didn't work.
Any ideas?

**Comment by beijiguang94** [comment]
@jgillis @jaeandersson Please.

**Comment by jgillis** [comment]
Could be alot of things. Probably not related to CasADi at all. First, make sure the dll loads with ctypes.WinDLL

**Comment by beijiguang94** [comment]
Thanks, @jgillis. Your advice helped to find the reason: the .dll was a 32-bit file while my python is 64-bit. After recompiling to get a 64-bit .dll file, CasADi can now open it.
