### ISSUE TITLE
"Plugin 'qpoases' is not found." error when using Casadi in matlab on Mac.

### ISSUE THREAD

**Issue by AnishaKarthyedath** [casadi/casadi#2918]
Hi
I started using casadi very recently. When I am using a quadratic programming solver I am getting the following error. However the file mentioned in the error "libcasadi_conic_qpoases.dylib" is available inside the folder "casadi-osx-matlabR2015a-v3.5.5".

CasADi - 2022-05-05 15:21:20 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_qpoases.dylib': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/Users//Desktop/ToolBox/casadi-osx-matlabR2015a-v3.5.5' :
    Error code: dlopen(/Users/ToolBox/casadi-osx-matlabR2015a-v3.5.5/libcasadi_conic_qpoases.dylib, 5): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/ToolBox/casadi-osx-matlabR2015a-v3.5.5/libcasadi_conic_qpoases.dylib
  Reason: image not found
  Tried '' :
    Error code: dlopen(libcasadi_conic_qpoases.dylib, 5): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/ToolBox/casadi-osx-matlabR2015a-v3.5.5/libcasadi_conic_qpoases.dylib
  Reason: image not found
  Tried '.' :
    Error code: dlopen(./libcasadi_conic_qpoases.dylib, 5): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /Users/ToolBox/casadi-osx-matlabR2015a-v3.5.5/libcasadi_conic_qpoases.dylib
  Reason: image not found") [.../casadi/core/plugin_interface.hpp:171]
Error using casadi.qpsol (line 8)
.../casadi/core/plugin_interface.hpp:417: Plugin 'qpoases' is not found.

Could anyone please help me here to resolve this issue?

Thank you

**Comment by jgillis** [comment]
Let's add qpoases tests to matlab unittests

**Comment by jgillis** [comment]
Works on github actions for 3.6
