### ISSUE TITLE
MSYS2 Casadi build fails

### ISSUE THREAD

**Issue by PhilippeW83440** [casadi/casadi#2945]
Under Windows with MSYS2, after:
git clone https://github.com/casadi/casadi.git -b master casadi
cd casadi
git checkout 3.5.5
mkdir build
cd build
cmake -DWITH_PYTHON=ON -DWITH_IPOPT=ON ..
ninja -j `nproc`

We get the following errors: 

[127/313] Building CXX object casadi/core/CMakeFiles/casadi.dir/mx_node.cpp.obj
FAILED: casadi/core/CMakeFiles/casadi.dir/mx_node.cpp.obj
C:\msys64\mingw64\bin\c++.exe -DCASADI_VERSION=31 -DHAVE_SIMPLE_MKSTEMPS -DUSE_CXX11 -DWITH_DEEPBIND -DWITH_DEPRECATED_FEATURES -DWITH_DL -D_SCL_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -Dcasadi_EXPORTS -IC:/msys64/home/seapwe/casadi/. -IC:/msys64/home/seapwe/casadi/build -IC:/msys64/home/seapwe/casadi/build/casadi/core/runtime -fno-ipa-cp-clone  -O3 -DNDEBUG   -DSHARED_LIBRARY_PREFIX="\"lib\"" -DSHARED_LIBRARY_SUFFIX="\".dll\"" -DOBJECT_FILE_SUFFIX="\".obj\"" -MD -MT casadi/core/CMakeFiles/casadi.dir/mx_node.cpp.obj -MF casadi\core\CMakeFiles\casadi.dir\mx_node.cpp.obj.d -o casadi/core/CMakeFiles/casadi.dir/mx_node.cpp.obj -c C:/msys64/home/seapwe/casadi/casadi/core/mx_node.cpp
In file included from C:/msys64/mingw64/include/wtypes.h:8,
                 from C:/msys64/mingw64/include/winscard.h:10,
                 from C:/msys64/mingw64/include/windows.h:97,
                 from C:/msys64/home/seapwe/casadi/casadi/core/plugin_interface.hpp:43,
                 from C:/msys64/home/seapwe/casadi/casadi/core/linsol_internal.hpp:31,
                 from C:/msys64/home/seapwe/casadi/casadi/core/solve_impl.hpp:30,
                 from C:/msys64/home/seapwe/casadi/casadi/core/mx_node.cpp:67:
C:/msys64/mingw64/include/rpcndr.h:64:11: error: reference to 'byte' is ambiguous
   64 |   typedef byte cs_byte;
      |           ^~~~
In file included from C:/msys64/mingw64/include/c++/11.2.0/bits/stl_algobase.h:61,
                 from C:/msys64/mingw64/include/c++/11.2.0/algorithm:61,
                 from C:/msys64/home/seapwe/casadi/casadi/core/casadi_common.hpp:29,
                 from C:/msys64/home/seapwe/casadi/casadi/core/shared_object.hpp:29,
                 from C:/msys64/home/seapwe/casadi/casadi/core/mx.hpp:28,
                 from C:/msys64/home/seapwe/casadi/casadi/core/mx_node.hpp:29,
                 from C:/msys64/home/seapwe/casadi/casadi/core/mx_node.cpp:26:
C:/msys64/mingw64/include/c++/11.2.0/bits/cpp_type_traits.h:404:30: note: candidates are: 'enum class std::byte'
  404 |   enum class byte : unsigned char;
      |                              ^~~~
In file included from C:/msys64/mingw64/include/wtypes.h:8,
                 from C:/msys64/mingw64/include/winscard.h:10,
                 from C:/msys64/mingw64/include/windows.h:97,
                 from C:/msys64/home/seapwe/casadi/casadi/core/plugin_interface.hpp:43,
                 from C:/msys64/home/seapwe/casadi/casadi/core/linsol_internal.hpp:31,
                 from C:/msys64/home/seapwe/casadi/casadi/core/solve_impl.hpp:30,
                 from C:/msys64/home/seapwe/casadi/casadi/core/mx_node.cpp:67:
C:/msys64/mingw64/include/rpcndr.h:63:25: note:                 'typedef unsigned char byte'
   63 |   typedef unsigned char byte;
      |                         ^~~~
In file included from C:/msys64/mingw64/include/wtypes.h:8,
                 from C:/msys64/mingw64/include/winscard.h:10,
                 from C:/msys64/mingw64/include/windows.h:97,
                 from C:/msys64/home/seapwe/casadi/casadi/core/plugin_interface.hpp:43,
                 from C:/msys64/home/seapwe/casadi/casadi/core/linsol_internal.hpp:31,
                 from C:/msys64/home/seapwe/casadi/casadi/core/solve_impl.hpp:30,
                 from C:/msys64/home/seapwe/casadi/casadi/core/mx_node.cpp:67:
C:/msys64/mingw64/include/rpcndr.h:397:170: error: reference to 'byte' is ambiguous
  397 |   typedef void (__RPC_API *CS_TYPE_TO_NETCS_ROUTINE)(RPC_BINDING_HANDLE hBinding,unsigned __LONG32 ulNetworkCodeSet,void *pLocalData,unsigned __LONG32 ulLocalDataLength,byte *pNetworkData,unsigned __LONG32 *pulNetworkDataLength,error_status_t *pStatus);
      |                                                                                                                                                                          ^~~~

I will propose a fix for this issue: this is due to using namespace std in header files.
Which is then populated in other header files creating namespace confusion for e.g. a byte type

**Comment by jgillis** [comment]
Current develop branch builds pass 'compilers' tests on github actions.
Please re-open if there is still remaining issues
