### ISSUE TITLE
Extend OracleFunction to be calculateble from different threads

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#2954]

**Comment by jgillis** [comment]
@jcotem multi-threaded knitro works for me now.
Compile CasADi with "-DWITH_THREAD=ON".

**Comment by jcotem** [comment]
Hi @jgillis, 
Thanks for the update. I managed to make it work on my side, that's great. I'll have to do some changes regarding which parameters can modify the value of max_num_threads, since we can have multithreads in MIP,findiff or multistart. I'll look at it next week when I have time.
