### ISSUE TITLE
Can the parallel map have both iterable and non-iterable inputs?

### ISSUE THREAD

**Issue by zehuilu** [casadi/casadi#2963]
I want to use the parallel map to parallelly evaluate a function with both iterable and non-iterable inputs. I noticed that there is an example on [https://github.com/casadi/casadi/blob/master/docs/examples/python/sysid.py](https://github.com/casadi/casadi/blob/master/docs/examples/python/sysid.py).

For this example, the iterable inputs are `X` and `u_data.T`, and the non-iterable input is `params`.
```
# Create a function that simulates all step propagation on a sample
one_sample = Function('one_sample',[states, controls, params], [X])
...
Xn = one_sample.map(N, 'openmp')(X, u_data.T, repmat(params*scale,1,N))
```

But currently, it copies all the non-iterable inputs so that every input is iterable. The copy of non-iterable inputs might be unnecessary at run-time. Is it possible to indicate the non-iterable inputs when creating a function map instance?

**Comment by zehuilu** [comment]
Thanks for the prompt response! What if it's in a more general case where the parameters might be changing at run-time? For example, this can be some information from a moving obstacle. In this case, every time I run the function, I need to update the parameter and re-do `repmat`. Will anything be different than what you explained here?

**Comment by ha7ilm** [comment]
I can think of two cases:

1. you want solve slightly changed optimization problems from within an outer loop, and for some reason you need to change the arguments to `map`. In this case constructing and solving the problem in every iteration will probably be the bottleneck, but not this single operation of duplicating the references to symbols with `repmat` (that happens repeatedly, but doesn't take a lot of time). 

2. (more likely) you just want to just execute the `map()`-ed `casadi.Function` repeatedly, with different values for the parameters: `repmat` is called only once, when you construct the expression graph. This is also the case for the `sysid.m`. Note that still it's not an expensive operation compared to other things that happen there.

**Comment by zehuilu** [comment]
Thank you! These explanations really help!

**Comment by ha7ilm** [comment]
I would like to add that @jgillis pointed me to a version of `map()` that has the parameters `reduce_in` and `reduce_out`. 

```python
map(self, int n, [bool] reduce_in, [bool] reduce_out, dict opts)
```

`reduce_out` will sum the results.  
`reduce_in` is to avoid copying as you suggested. However, one should double check if inside the current implementation of CasADi the copying actually still happens. And according to what I explained earlier, I don't think it's worth to look for the runtime bottleneck here, particularly in a typical multiple shooting problem like in the `sysid` example.
