### ISSUE TITLE
Return time steps used internally by integrator

### ISSUE THREAD

**Issue by tinosulzer** [casadi/casadi#2969]
When solving an ODE system where only the end time is specified, is it possible to return the times (and corresponding states) at which SUNDIALS evaluated the ode function internally?

**Comment by jaeandersson** [comment]
No, you can't do that with the current interface. The interface doesn't even call SUNDIALS that way - it relies on integrating to specific time points and then SUNDIALS will take steps until it gets to the specific time and then interpolate to get the desired value.

If you want that kind of low-level access to SUNDIALS, you should probably call SUNDIALS directory, not via CasADi.

**Comment by tinosulzer** [comment]
Got it, thanks
