### ISSUE TITLE
Using sqrt() in constraint | NaN detected for output 

### ISSUE THREAD

**Issue by VasilyRakche** [casadi/casadi#2984]
Hi, 

I was trying to implement some constraints, if I define them in this way:

> opti.subject_to( sqrt(xi_R^2 + xi_L^2) - xi_R - xi_L == 0);

I am getting the following output:

> Number of nonzeros in equality constraint Jacobian...:     8008
> Number of nonzeros in inequality constraint Jacobian.:      601
> Number of nonzeros in Lagrangian Hessian.............:     3403
> 
> CasADi - 2022-12-23 16:30:24 WARNING("solver:nlp_jac_g failed: NaN detected for output jac_g_x, at nonzero index 828 (row 3, col 9).") [.../casadi/core/oracle_function.cpp:265]
> Error evaluating Jacobian of equality constraints at user provided starting point.
>   No scaling factors for equality constraints computed!
> CasADi - 2022-12-23 16:30:24 WARNING("solver:nlp_jac_g failed: NaN detected for output jac_g_x, at nonzero index 828 (row 3, col 9).") [.../casadi/core/oracle_function.cpp:265]
> Error evaluating Jacobian of inequality constraints at user provided starting point.
>   No scaling factors for inequality constraints computed!
> CasADi - 2022-12-23 16:30:24 WARNING("solver:nlp_jac_g failed: NaN detected for output jac_g_x, at nonzero index 828 (row 3, col 9).") [.../casadi/core/oracle_function.cpp:265]
> 
> Number of Iterations....: 0

Can it be that the problem is **sqrt** function in the constraints?

#### System:
Ubuntu 
Matlab 2021b

**Comment by ha7ilm** [comment]
https://github.com/casadi/casadi/wiki/FAQ%3A-Why-am-I-getting-%22NaN-detected%22in-my-optimization%3F
