### ISSUE TITLE
How to change solver options using Function object created by nlpsol?

### ISSUE THREAD

**Issue by s1mahoeg** [casadi/casadi#2987]
I use python to create a Function object with casadi nlpsol. The problem is solved with ipopt. I run a model predictive control loop and want to change the ipopt options dynamically based on the outcome of the previous results. Is there a way to change the ipopt options once the Function object was created? 

```python
sol = casadi.nlpsol("solver", "ipopt", nlp, dict(ipopt=ipopt_opts))

# do some stuff

# how to update ipopt options using 'sol'? I'm looking for something like this:
#      sol.set_options(new_ipopt_options)
```

In CasADi version 2 there was a way to do this:
```python
sol = casadi.NlpSolver("ipopt", nlp)

# set new option
sol.setOption(option_name, option_value)
# init to make sure that newly set options are taken over
sol.init()
```
I saw that `setOption` was declared as deprectated. Have you removed the functionality completely in version 3 or is there an alternative?

I have seen that there is an init-method in `ipopt_interface.hpp`, however I don't know how to access this.
```python
// Initialize the solver
void init(const Dict& opts) override;
```

Creating the Function objects using nlpsol takes several seconds for my NLPs which is way too time consuming for my application. Thus, currently I create several Function objects using nlpsol in advance, each with different ipopt options, and dynamically decide which Function object I want to use at the current loop iteration. However, I think it would be cleaner if I can change the solver options directly. Is this possible?

**Comment by jaeandersson** [comment]
No, in general you need to set the options by passing them via the constructor.

The init method you are referring to is called internally when you call the constructor. It is not meant to be called multiple times and even if you could, it won't save any time for you.

If the constructor is slow, you should probably try to find out why it is slow. You should be able to see that by enabling the "verbose" option. Chances are that it's the generation of Jacobian/Hessian functions that is slow. If that's the case, you can try to generate the Jacobian/Hessian on beforehand, and pass it to the NLP solver instance.
