### ISSUE TITLE
Issue finding hsl library version 3.5.6.pre2 on windows

### ISSUE THREAD

**Issue by Ailbhemit** [casadi/casadi#2988]
Hi,

(I copy this from the google forum as it may be a bug)
Due to an unexpected crash using casadi 3.5.5 (I will report this issue soon - working on minimal example) I am trying to use 3.5.6.pre2 on Windows (as the aforementioned crash does not occur). However I encounter the following error when trying to access .dll fines I have included with my python installation. 

2023-01-09 13:55:27,892 INFO Calling solver

Exception of type: DYNAMIC_LIBRARY_FAILURE in file "/work/build/external_projects/src/ipopt-external/src/Common/IpLibraryLoader.cpp" at line 59:

Exception message: Error 126 while loading DLL libhsl.so: The specified module could not be found.

EXIT: Library loading failure.

         nlp  :   t_proc      (avg)   t_wall      (avg)    n_eval

       total  |   7.00ms (  7.00ms)   6.84ms (  6.84ms)         1

2023-01-09 13:55:27,917 INFO Solver failed with status Invalid_Option

It seems as though casadi thinks I am running on linux? The .dlls are added to path and I do not see this error when using 3.5.5. (I am using python 3.9)

Thanks for your help,
Ailbhe

**Comment by jgillis** [comment]
Thank you, confirmed in develop branch.

**Comment by jgillis** [comment]
Fixed in develop
