### ISSUE TITLE
casadi compatibility with acados

### ISSUE THREAD

**Issue by dapp1491** [casadi/casadi#2993]
Hello,

I´m new in the implementation of this kind of software and I would like to know if there´s any compatibility issue that I should be expecting as a result from using newer versions of Casadi (casadi-windows-matlabR2016a-v3.5.5) instead of older versions (e.g., casadi-windows-matlabR2014b-v3.4.0 ). I'm aware that these compatibility issues should be better known on the other side (acados) but I wanted to know if Casadi has suffered a major change between these two releases that I should be aware of.

Thanks for your time

**Comment by jaeandersson** [comment]
I think that this is a question for the ACADOS developers
