### ISSUE TITLE
Support tangent-space Jacobians

### ISSUE THREAD

**Issue by matheecs** [casadi/casadi#3013]
Getting efficient and correct tangent space jacobians, like in space _so3_ and _se3_, is a common task for many optimization. Will casadi support tangent-space Jacobians?

These are some tools may helpful to implement:

1. [SymForce](https://github.com/symforce-org/symforce)
2. [Sophus](https://github.com/strasdat/Sophus)
3. [manif](https://github.com/artivis/manif)

**Comment by jaeandersson** [comment]
It's unlikely to happen, unless the development is part of some industrial project. It takes time and resources to implement and maintain features likes these.
