### ISSUE TITLE
Casadi Python 3.11 support

### ISSUE THREAD

**Issue by bnlerner** [casadi/casadi#3014]
Hi I was wondering if there is a plan to support python 3.11 with Casadi? I saw there is [actually nightly build](https://github.com/casadi/casadi/issues/2877) support for 3.10 but I think 3.11 will be a bit more of a lift due to CPython changes.

**Comment by jgillis** [comment]
There are nightly builds for 3.11 too: https://github.com/casadi/casadi/releases/tag/nightly-develop

**Comment by martin-built** [comment]
Nightly builds for 3.11 sounds great! It would be fantastic with a release for 3.11. Do you know if that could be possible in the near future? : )

**Comment by jgillis** [comment]
ETA official release  weeks
