### ISSUE TITLE
Steps how to debug the solver

### ISSUE THREAD

**Issue by VasilyRakche** [casadi/casadi#3016]
Hi, 
I am trying to solve the non-linear complementarity problem. I am using **CASDI, IPOPT with ma86 solver**. What I noticed is that for relatively small problems (with not that many complementeraity constraints), I get the convergence. But scaling up and introducing more constraints -> solver fails to converge. To mitigate this problem I thought of introducing smothering functions for complementarity constraints, and smoothening them as presented in the [Robust Trajectory Optimization over Uncertain Terrain with Stochastic Complementarity](https://arxiv.org/abs/2009.12409), basically representing it as follows with Expected Residual Minimization (ERM) continuous function:

![image](https://user-images.githubusercontent.com/30003101/220966233-12af6db4-1b12-46f1-bf9f-29800cdf6d67.png)

I have done the implicit integration of dynamics, and the complementary functions are represented as cost, in following manner:
```
% Pseudocode
for k=1:N
     state = state+dt*dynamics(state)
     cost+=erm(state)
end
minimize(objective)
subject_to(cost<1e-3) 
```

Solver fails to converge. I have tried to use `opti.debug.show_infeasibilities()` - but it outputs many instabilities with small violations.  I have indeed verified that the `subject_to(cost<1e-3)` violation is around `0.4` - I guess that could be a critical point. I tried just including the `cost` in the `objective` but it will not get minimized to the desired level of complementarity constraints. 

Last part of solver output, I assume that it can be helpful:

```
1162r-2.0000000e+00 1.25e-02 2.83e-02  -8.6 9.44e-02  -2.7 1.00e+00 1.76e-01h  1
1163r-2.0000000e+00 9.01e-03 7.03e-04  -8.6 1.23e-01  -3.2 1.00e+00 1.00e+00f  1
1164r-2.0000000e+00 9.01e-03 1.60e-02  -8.6 1.51e-01    -  1.00e+00 5.61e-03h  1
1165r-2.0000000e+00 9.01e-03 8.55e-04  -8.6 1.43e-01    -  1.00e+00 9.28e-01f  1
1166r-2.0000000e+00 9.01e-03 2.40e-05  -8.6 3.97e-02    -  1.00e+00 1.00e+00h  1
1167r-2.0000000e+00 9.01e-03 7.73e-06  -8.6 8.70e-03    -  1.00e+00 1.00e+00h  1
1168r-2.0000000e+00 9.01e-03 7.85e-08  -8.6 4.86e-04    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 1168

                                   (scaled)                 (unscaled)
Objective...............:  -1.9999999887246274e+00   -1.9999999887246274e+00
Dual infeasibility......:   9.9999999574799614e-01    9.9999999574799614e-01
Constraint violation....:   9.0068873135598117e-03    9.0068873135598117e-03
Complementarity.........:   2.5059036380886895e-09    2.5059036380886895e-09
Overall NLP error.......:   9.9999999574799614e-01    9.9999999574799614e-01


Number of objective function evaluations             = 1292
Number of objective gradient evaluations             = 124
Number of equality constraint evaluations            = 1293
Number of inequality constraint evaluations          = 1293
Number of equality constraint Jacobian evaluations   = 1175
Number of inequality constraint Jacobian evaluations = 1175
Number of Lagrangian Hessian evaluations             = 1169
Total CPU secs in IPOPT (w/o function evaluations)   =    335.814
Total CPU secs in NLP function evaluations           =    142.944

EXIT: Converged to a point of local infeasibility. Problem may be infeasible.
      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval
       nlp_f  |   8.30ms (  6.42us)   6.14ms (  4.76us)      1292
       nlp_g  |  89.63 s ( 69.32ms)   6.93 s (  5.36ms)      1293
  nlp_grad_f  |   6.42ms ( 51.39us)   6.40ms ( 51.18us)       125
  nlp_hess_l  |  33.02 s ( 28.37ms)  31.67 s ( 27.21ms)      1164
   nlp_jac_g  |  20.15 s ( 17.13ms)  19.26 s ( 16.38ms)      1176
       total  | 479.96 s (479.96 s)  93.96 s ( 93.96 s)         1
Error using casadi.Opti/solve (line 253)
Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:159:
.../casadi/core/optistack_internal.cpp:999: Assertion "return_success(accept_limit)" failed:
Solver failed. You may use opti.debug.value to investigate the latest values of variables. return_status is
'Infeasible_Problem_Detected'
Error in opt_bsa_erm (line 189)
sol = opti.solve();   % actual solve 
```

I know that it is not issue with your code, but I would just appreciate the general directions and guidelines on how to approach and debug these kind of problems.

**Comment by jaeandersson** [comment]
I would recommend writing to the open forum for free support/advice or write to consulting@casadi.org for requests for paid support
