### ISSUE TITLE
Plugin 'qpoases' is not found on Linux with Python 3.10

### ISSUE THREAD

**Issue by konnpaku-youmu** [casadi/casadi#3030]
I'm trying to use 'sqpmethod' for solving NLP. It failed. I also tried to run the given example simple_nlp.py with 'sqpmethod', failed.

The error messages are the same:

> CasADi - 2023-03-15 01:32:05 WARNING(".../casadi/core/plugin_interface.hpp:322: Assertion "handle!=nullptr" failed:
> PluginInterface::load_plugin: Cannot load shared library 'libcasadi_conic_qpoases.so': 
>    (
>     Searched directories: 1. casadipath from GlobalOptions
>                           2. CASADIPATH env var
>                           3. PATH env var (Windows)
>                           4. LD_LIBRARY_PATH env var (Linux)
>                           5. DYLD_LIBRARY_PATH env var (osx)
>     A library may be 'not found' even if the file exists:
>           * library is not compatible (different compiler/bitness)
>           * the dependencies are not found
>    )
>   Tried '/home/yz/anaconda3/envs/mpc/lib/python3.10/site-packages/casadi' :
>     Error code: /home/yz/anaconda3/envs/mpc/lib/python3.10/site-packages/casadi/libcasadi_conic_qpoases.so: cannot open shared object file: No such file or directory
>   Tried '' :
>     Error code: libcasadi_conic_qpoases.so: cannot open shared object file: No such file or directory
>   Tried '.' :
>     ... truncated") [.../casadi/core/plugin_interface.hpp:171]
> Traceback (most recent call last):
>   File "/home/yz/Projects/Data_driven_Predictive_Control/examples/python/simple_nlp.py", line 47, in <module>
>     solver = nlpsol("solver", MySolver, nlp, opts)
>   File "/home/yz/anaconda3/envs/mpc/lib/python3.10/site-packages/casadi/casadi.py", line 9966, in nlpsol
>     return _casadi.nlpsol(*args)
> RuntimeError: .../casadi/core/function_internal.cpp:144: Error calling Sqpmethod::init for 'solver':
> .../casadi/core/plugin_interface.hpp:417: Plugin 'qpoases' is not found.
> 

System info:

Python: 3.10 (anaconda)
Linux: 6.5.2

Also had qpoases installed in the system
> \> ls -l /usr/local/lib/libqpOASES_e.a
> -rw-r--r-- 1 root root 337002 Mar 15 01:25 /usr/local/lib/libqpOASES_e.a

**Comment by jgillis** [comment]
Can you please retry after removing your casadi and reinstalling through `pip install <appropriate whl url from  https://github.com/casadi/casadi/releases/tag/nightly-develop >`

**Comment by konnpaku-youmu** [comment]
> Can you please retry after removing your casadi and reinstalling through `pip install <appropriate whl url from https://github.com/casadi/casadi/releases/tag/nightly-develop >`

It worked. Thanks!
