### ISSUE TITLE
Casadi problem with Numpy

### ISSUE THREAD

**Issue by KehanLong** [casadi/casadi#3035]
I installed casadi 3.5.5 with pip and the numpy issues are still there, as illustrated in #2743, #2903 (the error is basically: Implicit conversion of symbolic CasADi type to numeric matrix not supported.). In #2903, it is suggested that we use the develop wheel casadi instead of the 3.5.5 one from pip.

Can anyone tell me how to install and use those latest develop branch [https://github.com/casadi/casadi/releases/tag/nightly-develop](https://github.com/casadi/casadi/releases/tag/nightly-develop) in an anaconda virtual environment?

**Comment by jgillis** [comment]
pip install <url to appropriate whl file>

**Comment by KehanLong** [comment]
Can you be more specific? 
I tried Pip install casadi, which only gives me the generic version. What command should I use to install the latest develop branch? Or, is it the same?

**Comment by jgillis** [comment]
Looks like github ate my markup. Can you check my edited answer?

**Comment by KehanLong** [comment]
Yes. I tried the command: pip install git+https://github.com/casadi/casadi.git@nightly-develop
but got the error of: "ERROR: git+https://github.com/casadi/casadi.git@nightly-develop does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found."
It looks like the repo is missing a setup.py or pyproject.toml file. Could you help me with it? Please let me know if there is a mistake I made.
