### ISSUE TITLE
HiGHS interface doesn't support non-empty discrete vector

### ISSUE THREAD

**Issue by ruudkassing** [casadi/casadi#3062]
In #2855 a first version of the interface to the HiGHS solver was added.

However, in this implementation there is was an error, which results in the interface not supporting a non-empty  `discrete` option vector:
```
RuntimeError: .../casadi/core/function_internal.cpp:145: Error calling HighsInterface::init for 'nlp_qpsol':
.../casadi/core/casadi_misc.hpp:588: Assertion "d.empty()" failed:
```

When the vector `_integrality` is code generated, it is initialised non-empty with a zero:
https://github.com/casadi/casadi/blob/dd307c9197710ec05a41d3cb57bbc9950b2a655f/casadi/interfaces/highs/highs_interface.cpp#L123

Therefore, when `assign_vector(discrete_, integrality_);` is called it fails, because `assign_vector()` requires the second argument to be an empty vector, see:
https://github.com/casadi/casadi/blob/dd307c9197710ec05a41d3cb57bbc9950b2a655f/casadi/core/casadi_misc.hpp#L586-L591

The fix is simple: using `copy_vector()` just like it is done for the other vectors during initialisation and subsequent assignment.

**Comment by jgillis** [comment]
Applied your fix in 64fe79cc48625ae5d21127767cace072a9069d8d
