### ISSUE TITLE
Error in interp1d in version 3.6.0

### ISSUE THREAD

**Issue by SGeevers** [casadi/casadi#3079]
When using casadi 3.6.0 with Python 3.9.0 and running

```python
import casadi as ca
from casadi import interp1d   
interp1d([1,2,3], ca.MX([4,5,6]), [1.1], 'linear')
```

I get the error message

> RuntimeError: .../casadi/core/sparsity.cpp:431: Assertion "x.size2()==y.size1()" failed:
> Matrix product with incompatible dimensions. Lhs is 2x1 and rhs is 3x1.

**Comment by jgillis** [comment]
Caused by 9d5e75feb6c6c86079e5b2d2b6295ce1e03e4f24

**Comment by jgillis** [comment]
Thanks a lot for reporting this regression error!
