### ISSUE TITLE
Rename develop branch main, remove master

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#3092]
If I recall correctly, `master` was chosen to point to the latest version to ensure users would get a stable version when building from sources. This is no longer a good argument - most users now use the binary builds and a person compiling CasADi from sources might be more interested in the latest development build in order to be able to do PR and the like.

So per discussion with @jgillis:
 * The default branch of the project will be called `main`. It will work like `develop` now. `main` appears is the preferred named and it makes sense not to change meaning of the existing `master` branch.
 * The `master` branch will be removed. If we want a branch with the old behavior, i.e. pointing to the latest release, we can call it `latest`.
 * Maybe introduce a `stable` branch, with the latest tested revision of `main`?

This will resolve a lot of confusion related to users making PRs to `master` and also make the project activity be better reflected in the Github diagnostics (I believe the activity page shows commits to the main branch, which makes CasADi look dead between releases).

**Comment by jaeandersson** [comment]
@jgillis suggested calling the latest tested revision `tested` instead of `stable`.

**Comment by jgillis** [comment]
Must take care that older links are not broken https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by jgillis** [comment]
Note:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by jgillis** [comment]
> I think the latest branch is essential to easily be able to install the c++ interface with the same version of CasADi as you would get for python through pip.

@victorfors can you comment how such a branch is more useful than a tag? Tags could be 'latest', '3', '3.6', '3.6.0'

**Comment by victorfors** [comment]
@jgillis For my purpose there would not be any additional benefit with a branch 'latest' than a tag 'latest'. I guess the standard workflow of Git that I'm used to is to have a branch for releases. It perhaps goes against the spirit of tags to have them moving like 'latest' would. Updating and handling local changes could be slightly more straightforward with a separate branch. But if you make changes I would expect you to be on the develop/main branch.

**Comment by jgillis** [comment]
Branches 'latest' and '3.6' are live
