### ISSUE TITLE
Installation Problem on Mac M1 for MATLAB

### ISSUE THREAD

**Issue by staycoolish** [casadi/casadi#3101]
Hello,

Although installation steps are simple, I couldn't make it work. Here's what I've done:

I downloaded it, unzipped and put into MATLAB's home directory. /Users/staycoolish/Documents/MATLAB/casadi-3

Then I added this path to MATLAB. I used Set Path -> Add Folder from MATLAB GUI and added it.

When I write

```
import casadi.*
x = MX.sym('x')
```

I get this error:

```
Unrecognized function or variable 'casadiMEX'.
Error in casadi.GenMX.sym (line 833)
[varargout{1:nargout}] = casadiMEX(355, varargin{:});
```

There is no mistake about the version (I checked versions for Intel Mac and even Windows), and there is no mistake about folder name (I tried casadi_3 and casadi as the folder's name as well, changing the Matlab Path accordingly).

What can be the problem?

**Comment by jgillis** [comment]
It looks like Matlab on M1 runs via rosetta. Can you peform your experiment using our "regular mac" binaries for Matlab?

**Comment by jgillis** [comment]
Alternatively, you could obtain the native M1 Matlab from https://blogs.mathworks.com/matlab/2022/05/05/exploring-the-matlab-beta-for-native-apple-silicon/

**Comment by staycoolish** [comment]
Thank you, I solved the issue. I downloaded the Intel Mac version, then when I write

```
import casadi.*
x = MX.sym('x')
```
I get this error:

<img width="247" alt="Screenshot 2023-04-13 at 01 20 38" src="https://user-images.githubusercontent.com/47630638/231602343-fa7bd590-93ef-4879-81b1-d059096052d9.png">

I solved this following this link: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

For every executable in casadi I repeated this process (hold Control, Open the file). Perhaps I should've downloaded the beta Matlab version for Apple Silicon :D

**Comment by basitimran37** [comment]
I am encountering the same problem with the latest 3.6.5 release and with native MATLAB for M1.

```
Unrecognized function or variable 'casadiMEX'.

Error in casadi.GenMX.sym (line 833)
     [varargout{1:nargout}] = casadiMEX(356, varargin{:});
```

**Comment by basitimran37** [comment]
Has this problem been fixed? I still see it in the latest version.
