### ISSUE TITLE
Allow Knitro parameters to be read from knitro.opts file

### ISSUE THREAD

**Issue by richteropt** [casadi/casadi#3108]
Since not all Knitro parameters can be set from the provided interface and the parameters itself are Knitro-version-dependent, a nice way would be to allow for the possibility to provide the Knitro parameters via an external opts file (see Knitro manual).

**Comment by jaeandersson** [comment]
Good feature suggestion. If it's trivial to add, you can implement it in a fork and make a pull request. Otherwise, you can contract one of the developers by writing to consulting@casadi.org
