### ISSUE TITLE
cg_options.real_min = 'real_T' - Do Not Work

### ISSUE THREAD

**Issue by scyrock** [casadi/casadi#3126]
Hello,
I am trying to create a **Simulink S-function** from a CasADi function. I follow the procedure suggested in the [S-function example](https://github.com/casadi/casadi.github.io/tree/main/content/blog/s-function) provided by @jgillis.

The `mex` compiling procedure fails:   
```
mex s_function.c f.c
Building with 'gcc'.
Error using [mex](matlab:matlab.internal.language.introspective.errorDocCallback('mex'))
/MATLAB Drive/CasADi/f.c: In function ‘f_qp_setup’:
/MATLAB Drive/CasADi/f.c:502:27: error: expected expression before ‘real_T’
   #define casadi_real_min real_T
                           ^~~~~~
/MATLAB Drive/CasADi/f.c:519:13: note: in expansion of macro ‘casadi_real_min’
   p->dmin = casadi_real_min;
             ^~~~~~~~~~~~~~~
```
I use the following solver settings:
`opti.solver('sqpmethod',struct('qpsol','qrqp'))`

**Comment by jgillis** [comment]
Is this error new? I don't understand; `real_T` is supposed to be defined by Matlab's headers.

**Comment by jgillis** [comment]
Can you try with `cg_options.real_min    = num2str(realmin);`?

**Comment by jgillis** [comment]
Works for me, will push a fix to the blog

**Comment by scyrock** [comment]
> Can you try with `cg_options.real_min = num2str(realmin);`?

Thanks for the quick reply. The solution works fine. 
Sorry for my late answer.
