### ISSUE TITLE
Exceptions inside oraclefunction remain hidden

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#3133]
https://github.com/casadi/casadi/issues/3064#issuecomment-1517396924

**Comment by jaeandersson** [comment]
Can you provide more details? What sort of exceptions remain hidden? With the change in #3064, exceptions are rethrown with additional information after being caught. Are you talking about evaluation errors?

**Comment by jgillis** [comment]
Example:
```python
x=MX.sym("x")
x_fail = x.attachAssert(x!=x,"Cuckoo")
nlp={'x':x, 'f':(x-1)**2, 'g':x_fail}

solver = nlpsol("mysolver","ipopt", nlp)
solver()
```

You would expect the string "Cuckoo" to appear in stdout or stderr.
This is the case in 3.5, but not in 3.6
