### ISSUE TITLE
Regressions concerning jac_sparsity

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#3134]
We had a weird regression bug reported in #3074 with testcase A and a tentative fix, shipped in 3.6.1

The fix causes a regression in unrelated code (testcase B):
```python
from casadi import *

p = MX.sym("p")
v = MX.sym("v")

u = MX.sym("u")
x = vertcat(p,v)

rhs = vertcat(v,u)

t0 = MX.sym("t0")
DT = MX.sym("DT")

F = Function('F', [x, u, t0, DT], [x + DT * rhs], ['x0', 'u', 't0', 'DT'], ['xf'])


x = []
g = []

Xk = MX.sym("Xk",2)
x.append(Xk)

T = MX.sym("T")
x.append(T)

g.append(T)

t0 = MX.sym("t0")
x.append(t0)

# Note: (t0+T)-(t0+T/2) does not simplify; sparsity pattern indicates dependence on T and t0
DTs = [T/2,(t0+T)-(t0+T/2)]

for i in range(2):
    Uk = MX.sym("Uk")
    x.append(Uk)
    Xk_next = MX.sym("Xk_next",2)
    x.append(Xk_next)
    Xf = F(x0=Xk, u=Uk, t0=t0, DT=DTs[i])["xf"]
    g.append(Xk_next-Xf)
    Xk = Xk_next

nlp = {"x": vvcat(x),"f": T, "g": vvcat(g)}

solver = nlpsol("solver","ipopt",nlp)
```

testcase B passes when #3074 fix is reverted, but testcase A then fails.

The commits of #3130 unfortunately changes nothing about the situation of A or B.

**Comment by jaeandersson** [comment]
> We had a weird regression bug reported in #3074 with testcase A and a tentative fix, shipped in 3.6.1
> 
> The fix causes a regression in unrelated code (testcase B):
> 
> ```python
> from casadi import *
> 
> p = MX.sym("p")
> v = MX.sym("v")
> 
> u = MX.sym("u")
> x = vertcat(p,v)
> 
> rhs = vertcat(v,u)
> 
> t0 = MX.sym("t0")
> DT = MX.sym("DT")
> 
> F = Function('F', [x, u, t0, DT], [x + DT * rhs], ['x0', 'u', 't0', 'DT'], ['xf'])
> 
> 
> x = []
> g = []
> 
> Xk = MX.sym("Xk",2)
> x.append(Xk)
> 
> T = MX.sym("T")
> x.append(T)
> 
> g.append(T)
> 
> t0 = MX.sym("t0")
> x.append(t0)
> 
> # Note: (t0+T)-(t0+T/2) does not simplify; sparsity pattern indicates dependence on T and t0
> DTs = [T/2,(t0+T)-(t0+T/2)]
> 
> for i in range(2):
>     Uk = MX.sym("Uk")
>     x.append(Uk)
>     Xk_next = MX.sym("Xk_next",2)
>     x.append(Xk_next)
>     Xf = F(x0=Xk, u=Uk, t0=t0, DT=DTs[i])["xf"]
>     g.append(Xk_next-Xf)
>     Xk = Xk_next
> 
> nlp = {"x": vvcat(x),"f": T, "g": vvcat(g)}
> 
> solver = nlpsol("solver","ipopt",nlp)
> ```
> 
> testcase B passes when #3074 fix is reverted, but testcase A then fails.
> 
> The commits of #3130 unfortunately changes nothing about the situation of A or B.

Is the fix for #3074 even needed after #3130? Can it not be safely reverted?

**Comment by jgillis** [comment]
Sadly, no. Testcase A fails then

**Comment by jaeandersson** [comment]
As I've said, I think the proper fix is to clean up the Jacobian sparsity code, and get rid of ~80 % of the code and having something more maintainable and less buggy. Remove the "compact" sparsity patterns altogether. But that's not a fix for a minor release.

If you have to patch the existing code, I'd try to go to the bottom of why the symmetry hack/fix is still needed, despite https://github.com/casadi/casadi/issues/3130
