### ISSUE TITLE
Accept "context" argument in Callback class

### ISSUE THREAD

**Issue by wanxinjin** [casadi/casadi#3181]
Hi, 

Maybe I am not aware of the full existing functionalities provided in Callback. But I think it might be useful to allow `get_jacobian`, `get_forward` and `get_reverse` methods to accept an additional argument "context", just like [torch.autograd.function.FunctionCtx.save_for_backward ](https://pytorch.org/docs/stable/generated/torch.autograd.function.FunctionCtx.save_for_backward.html)
This context can save some intermediate values in `eval`, which will be used in the user-customized derivatives.

I know the above request can be avoided by considering this "context" as an official output of `eval` method, which is then naturally input for user-customized derivative methods. But this is not convenient.

Hope you could consider this request. Thank you!

**Comment by jgillis** [comment]
Given that Callback is a class, could you not simply add your own data member?

**Comment by wanxinjin** [comment]
Ooh, that's also a way. I was overthinking the interface. Thank you for your inputs. I would close this issue.

**Comment by modu-robotics** [comment]
I had a similar question to this - https://github.com/casadi/casadi/discussions/3379
Did you manage to implement something similar in the link above?
I'd appreciate it if you could share your solution!
