### ISSUE TITLE
Add alpaqa interface

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#3207]
Complications
 * embedded in casadi cmake, source needs minor adaptions for dockcross/manylinux2014
 * standalone compilation fails
 * [x] dockcross/windows-shared-x64-posix is cmake 3.20 while 3.24 requested
   Conditionally depend on cmake 3.20

**Comment by gmsanchez** [comment]
Hi @jgillis 

Is this usable? I saw the interfaces on https://github.com/casadi/casadi/tree/main/casadi/interfaces/alpaqa

Thanks!
