### ISSUE TITLE
add function that reduces a vector to a scalar using some lambda function

### ISSUE THREAD

**Issue by Mathadon** [casadi/casadi#3230]
Suppose you want to sum all values of a vector for each value that does not exceed a threshold.

In C++ this might be implemented as follows:
```c++
int n = 10;
MX someVector = MX::sym(n,1);
MX result = MX(0);
for (int i = 0; i < n; ++i){
	result += if_else_zero(someVector(1) < 10, someVector(1) * 123);
}
```
The problem is that this generates a large node tree, which results in large C code when using `generate()`.

In javascript there exists a function called `reduce` that looks like this:

``` js
const array1 = [1, 2, 3, 4];

// 0 + 1 + 2 + 3 + 4
const initialValue = 0;
const sumWithInitial = array1.reduce(
  (accumulator, currentValue) => accumulator + currentValue,
  initialValue
);

console.log(sumWithInitial);
// Expected output: 10
```
where `(accumulator, currentValue) => accumulator + currentValue` is a shorthand notation for a function with two inputs and one output.

It would be useful to have this also in casadi, where a lambda function could be used to tell casadi how to reduce the vector. Casadi should then implement a for loop calling the lambda function when doing codegen such that the code size does not explode. Ideally, the iterator `for (int i = 0; i < n; ++i)` can be sparse by passing an array of indices (sparsity pattern) that indicates which subset of the vector should be parsed.

Or the concept could be generalised by mapping `n` inputs to `m` outputs instead of `n` to 1. This would be quite similar to `mtimes` except that `mtimes` only allows multiplications (and additions) whereas the proposed implementation would allow any function evaluation.

Is this something that could become a new `Function` at some point? Or perhaps it exists already? I did not find it in the C++ api.

**Comment by victorfors** [comment]
You can accomplish this with fold, see https://web.casadi.org/docs/#for-loop-equivalents

**Comment by Mathadon** [comment]
Indeed, that looks like what I need, thanks!
