### ISSUE TITLE
In NumPy 1.25.0+, errors with elementwise logical comparisons between CasADi and NumPy arrays

### ISSUE THREAD

**Issue by peterdsharpe** [casadi/casadi#3252]
## Bug Overview / Minimum Code Example / Observed Behavior

With `numpy >= 1.25.0` (released last week), elementwise logical comparisons between CasADi and NumPy vectors produce an error. Interestingly, order matters: `numpy_vector == casadi_vector` fails, but `casadi_vector == numpy_vector` works. This is best understood with the following example:

```python
import numpy as np
import casadi as cas

vec_np = np.ones([3])
vec_cas = cas.GenMX_ones(3, 1)

### Works correctly; prints `ones(3x1)`, regardless of NumPy version.
print(vec_cas == vec_np)

### If NumPy >= 1.25.0 is installed, this produces an error.
### If NumPy < 1.25.0 is installed, this correctly prints `ones(3x1)`, but with several warnings.
print(vec_np == vec_cas)
```

The warning produced for NumPy < 1.25.0 is:
```
RuntimeWarning: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
  warnings.warn("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
C:\Users\peter\AppData\Roaming\JetBrains\PyCharm2023.1\scratches\scratch_112.py:12: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
```

The error produced for NumPy >= 1.25.0 is essentially the same as the DeprecationWarning seen above. Here is an example error string from a slightly different unit test of essentially the same issue:
```
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'equal'>, '__call__', array(1), MX(opti52_x_1)): 'ndarray', 'MX'
```

As a practical example, this error might be encountered if a user attempts to use the `casadi.Opti.subject_to` interface to constrain a vector-valued `casadi.Opti` variable to be elementwise-equal to a NumPy vector.

## Expected Behavior

I would expect that order should not matter for an elementwise logical comparison (i.e., commutativity), and that no error should be produced regardless of NumPy version.

## Versions

- NumPy: 1.25.0
- CasADi: 3.6.3
- Python: 3.10.11
- OS: Windows 11

Please let me know if more info is desired.

**Comment by jgillis** [comment]
Can reproduce this. Thanks for reporting~

**Comment by peterdsharpe** [comment]
Thanks @jgillis !

I was seeing the same issue with `!=` and NumPy 1.25 - do you know if this commit fixes that as well? 

I suppose `!=` is less critical than `==`, since the former isn't typically used when setting up an optimization constraint - just curious.

**Comment by jgillis** [comment]
Yes, in 32a09d4
