### ISSUE TITLE
How can casadi do not exit the programme when throwing a "casadi::CasadiException"

### ISSUE THREAD

**Issue by Vonct** [casadi/casadi#3322]
Hi,
Just like the title said, when something like this happen:
```
terminate called after throwing an instance of 'casadi::CasadiException'
  what():  Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:157:
.../casadi/core/optistack_internal.cpp:1000: Assertion "return_success(accept_limit)" failed:
Solver failed. You may use opti.debug.value to investigate the latest values of variables. return_status is 'Maximum_Iterations_Exceeded'
```
I would like to switch to another algorithm rather than exit the code. Thus what settings can I do to the solver, so that I could use another algorithm according to a bool return by the solver?
Looking forward to a reply.

**Comment by jgillis** [comment]
try catch, or opti.solve_limited()
