### ISSUE TITLE
Opti stack and interpolants

### ISSUE THREAD

**Issue by mohseninima** [casadi/casadi#3387]
Hello,

I am trying to form an optimal control problem using opti stack with an interpolant. When finalizing the problem by running the `to_function command`, I get an error saying `.../casadi/core/function_internal.cpp:2009: 'eval_sx' not defined for BSplineInterpolant`

Is it not possible to use interpolants with opti stack?

**Comment by jgillis** [comment]
Try with option "expand" false.

**Comment by mohseninima** [comment]
That fixed it! Thank you
