### ISSUE TITLE
Python kernel crashing when FMU DLL replaced

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#3389]
I have noticed the Python kernel crashing when I make modifications of the Modelica source code and then recompile/reload the new DLL. A possible explanation is that the `FmuFunction` instance will stop working if the corresponding DLL is deleted/replaced.

A possible remedy would be to unpack the FMU into a temporary directory, to prevent the old DLL from being prematurely deleted.

**Comment by jaeandersson** [comment]
Can confirm that the bug can be avoided by using unique directory names. Not really a satisfactory solution, though.

**Comment by jaeandersson** [comment]
Relevant:
https://stackoverflow.com/questions/69655099/what-would-happen-if-i-delete-replace-the-shared-library-after-it-has-been-expli

**Comment by jaeandersson** [comment]
> Relevant: https://stackoverflow.com/questions/69655099/what-would-happen-if-i-delete-replace-the-shared-library-after-it-has-been-expli

The suggestion to explicitly remove the files rather than overwriting them seems to resolve the issue:
```python
mofile = 'vdp.mo'
fmu_file = 'vdp.fmu'
import zipfile
import os
import shutil
# Unzip FMU
unzipped_name = mofile[:mofile.find('.')]
#unzipped_name += '_mod'
unzipped_path = os.path.join(os.getcwd(), unzipped_name)
# Remove any existing directory with this name
if os.path.isdir(unzipped_path): shutil.rmtree(unzipped_path)  
# Unzip
with zipfile.ZipFile(fmu_file, 'r') as zip_ref: zip_ref.extractall(unzipped_name)
print('Unzipped %s into %s' % (fmu_file, unzipped_path))
```

Should update the FMU examples and notebook accordingly.

**Comment by jgillis** [comment]
> Relevant: https://stackoverflow.com/questions/69655099/what-would-happen-if-i-delete-replace-the-shared-library-after-it-has-been-expli

Oh waw, it's doing mmap on the file rather than loading😮
