### ISSUE TITLE
Cmeel-based publishing

### ISSUE THREAD

**Issue by lvjonok** [casadi/casadi#3423]
I am developing a c++ library with python bindings based on repositories such as [pinocchio](https://github.com/stack-of-tasks/pinocchio) and casadi itself.

I have found it very convenient to use wheel distributions based on [cmeel](https://cmeel.readthedocs.io/en/latest/) because it makes the whole process of dependencies installation easy with PIP wheels.

Will it be possible to create alternative cmeel-based wheel for casadi as [cmeel-cppad](https://github.com/cmake-wheel/cmeel-cppad) ? Probably, the question relates not the development, rather the permission to do so.

**Comment by jgillis** [comment]
You are for sure allowed to distribute casadi in alternative ways, but I don't have any bandwidth to look into this myself on unpaid time.

**Comment by lvjonok** [comment]
I have managed to do the alternative distribution, it is definitely not good as the original one, but [here](https://github.com/lvjonok/cmeel-casadi)

**Comment by lvjonok** [comment]
> @lvjonok : thanks for this work !
> 
> It is providing many dependencies (mumps, ipopt, osqpt, etc.), so this might not fit well within the cmeel ecosystem, but fixing this would require a ton of work. I've be working on it for some time already, but it's far from done. I'll continue in this direction, and document it when it's done.

I would be glad to help! If there is anything I can work on to get results faster, I am open.

When I looked through some repositories already built with cmeel, there are parts of `casadi` requirements, such as LAPACK. As right now it takes much time to build and test the whole package, maybe decomposition into many components would help.
