### ISSUE TITLE
Can I use IDAs in Casadi as simulink solver?

### ISSUE THREAD

**Issue by LeXu1327** [casadi/casadi#3497]
Hi all,
I have a question, Can I use IDAs in Casadi as simulink solver?
Typically, we choose ode45 or ode15s as simulink solver. Can I use IDAs in Casadi instead?

Thanks！

**Comment by jgillis** [comment]
No, using casadi's idas plugin as drop in replacement for simulink settings is not possible.

You could have a simulink s function block that uses casadi idas under the hood though, see https://web.casadi.org/blog/mpc-simulink2/
