### ISSUE TITLE
Add function_internal.hpp to the install interface

### ISSUE THREAD

**Issue by lvanroye** [casadi/casadi#3515]
Hello, 

I'm developing an optimal control problem solver called [fatrop](https://arxiv.org/abs/2303.16746). CasADI was very helpful for the development of this project. 

I am currently working on an optimal control problem specification tool, specifically designed for my solver. This toolkit is able to generate casadi functions (just like [rockit.Ocp.to_function](https://gitlab.kuleuven.be/meco-software/rockit/-/blob/master/rockit/ocp.py?ref_type=heads#L180)). To this end, I had to embed the solver in a casadi::Function. I first tried to implement a casadi::Callback, but I had some issues because the memory management is not integrated into the casadi::SharedObj memory management system.

Eventually, I implemented a custom casadi::FunctionInternal, while this works very well, this choice complexifies the installation process a lot. This is because the function_internal.hpp header is not installed by the casadi installation process. 

For me, it would be very handy if this header was installed as well. Is that something that is possible?

To this end, I think the following things should be done:
- install function_internal.hpp, shared_object_internal.hpp and shared_object.hpp
- add #include<casadi/config.h> to the includes of function_internal.hpp and shared_object.hpp

For information, it would be very helpful for me because I'm also planning to implement custom casadi Functions for embedding [Pinocchio](https://github.com/stack-of-tasks/pinocchio) functions in the same way. Thi will allow me to combine the flexibility and ease of use of casadi with the efficient (analytical derivative) robot dynamics implementations of Pinocchio.

**Comment by jaeandersson** [comment]
function_internal.hpp is part of the internal API, so I don't think it makes sense to have it be an install target. There are also no efforts to keep it stable from one release to another. If you want to couple your tool tightly with CasADi like this, I would suggest you to include CasADi as a git submodule.

**Comment by jgillis** [comment]
The purpose of Callback is really to cater for Python and Matlab users through offering an overloadable interface via swig.
If you are a c/c++ programmer and especially if you are distributing a numerical package tied to casadi, it makes much more sense to work with 'external'. This has a stable API, does reference counting, is efficient, and is robust against mixing binaries compiled wjth different compilers because the interface is C only.

**Comment by jaeandersson** [comment]
Agree that using the external C API probably makes more sense. It's more stable, more efficient and also work with things like C code generation. You can probably resolve your persistency issues you're having in Callback by appropriate static method or singleton patterns, but it's probably not worth it if you can just use the C API instead.

**Comment by lvanroye** [comment]
Thanks a lot for the recommendations, I'll proceed with the C API. Also thanks for the recommendation of the singleton pattern. I think I'll use that to access my own solver class from the C API implementation. I'll close this issue.

**Comment by jaeandersson** [comment]
> Thanks a lot for the recommendations, I'll proceed with the C API. Also thanks for the recommendation of the singleton pattern. I think I'll use that to access my own solver class from the C API implementation. I'll close this issue.

It's not necessary to use a singleton I think. You should also be able use the "incref/decref/alloc_mem/init_mem/free_mem functions in the C API. But singleton might be easier.

**Comment by lvanroye** [comment]
Interesting! Does the int mem arguments in the C API then refer to different instantiations of your user-defined function? 

Another quick question: is it possible to instantiate a new external Function without having to dl-load a shared library (and going through the file system)? Is it possible to instantiate an external function from c-function pointers to the name_init_mem, name_free_mem, name_release, name_eval ... functions?

Thanks!

**Comment by jaeandersson** [comment]
> Interesting! Does the int mem arguments in the C API then refer to different instantiations of user-defined function?

Correct. This could be useful if you need to evaluate it in parallel for example.

> 
> Another quick question: is it possible to instantiate a new external Function without having to dl-load a shared library (and going through the file system)? Is it possible to instantiate an external function from c-function pointers to the name_init_mem, name_free_mem, name_release, name_eval ... functions?
> 
> Thanks!

No, I think you need a shared library to use external. Otherwise, you can just use the C API directly. In principle, you could just-in-time compile the function, but this isn't really properly supported.
