### ISSUE TITLE
Store the IPOPT display parameters in a variable using CasAdi

### ISSUE THREAD

**Issue by Imran686** [casadi/casadi#3543]
<img width="1027" alt="lnmu" src="https://github.com/casadi/casadi/assets/72456599/18d4683b-ec43-463f-b4ef-2594435caf40">

I am using CasAdi to excess the IPOPT solver in python. IPOPT display certain parameters at every iteration as shown in the attached image. I need to specifically store the final barrier coefficient (mu) in a variable to use it further. How can I store the barrier coefficient (mu) from the display into a variable in python?

**Comment by jgillis** [comment]
If the sought information does not appear in solver.stats(), a workaround is to 'capture stdout' and parse it yourself. This works for most solvers, specifically ipopt.

**Comment by Imran686** [comment]
Thanks for the prompt response. The solver.stats() works for me.
