### ISSUE TITLE
Set bounds not constraint

### ISSUE THREAD

**Issue by mrrezaie** [casadi/casadi#3559]
Hi, I already know that this topic has been addressed in the earlier years, but I'm not able to find an easy and straightforward way to set bounds. 
https://groups.google.com/g/casadi-users/c/hX6bTw6lCSw
https://github.com/casadi/casadi/blob/main/test/python/nlp.py

```python
opti.subject_to( opti.bounded(0,A,1) )
```
This is the current implementation which is a constraint not bound and I was wondering if it would be possible to add this feature to easily set the lower and upper bounds rather than defining a constraint.

I'm asking for this feature because a same problem (with same solver options) was solved in pyomo twice as fast as casadi and I suspect this could be the reason.

Looking forward to this feature and thank you in advance.

**Comment by jgillis** [comment]
There is still now way to explicitly use bounds in Opti.
However, 3.6 added the `detect_simple_bounds` option to nlpsol.
I'm curious what the effect will be on your case when you set it to true.

**Comment by mrrezaie** [comment]
Thanks a lot for your response. I was not aware of this option and nothing could be found about it on the docs. I tested a couple of options and this is the output:

| expand | detect_simple_bounds | time (s) |
| --- | --- | --- |
| False | False | ~18 |
| False | True | ~12 |
| True | False | ~12 |
| True | True | ~6 |

If I set both of `expand` and `detect_simple_bounds` to `True`, it becomes 25%  faster than pyomo (8 s) 🚀. Thanks again.
