### ISSUE TITLE
ipopt Nan detect for output jac_g_x

### ISSUE THREAD

**Issue by andre-rebelo-teixeira** [casadi/casadi#3598]
Hello, I am having a problem that someone here might have a solution. 

This is an attitude mpc for free flier. I develop some on the work myself and got this code that currently has the error you see bellow

"CasADi - 2024-03-02 22:49:44 WARNING("solver:nlp_jac_g failed: NaN detected for output jac_g_x, at nonzero index 2 (row 79, col 0).") [.../casadi/core/oracle_function.cpp:377]
Error evaluating Jacobian of equality constraints at user provided starting point.
  No scaling factors for equality constraints computed!
CasADi - 2024-03-02 22:49:44 WARNING("solver:nlp_jac_g failed: NaN detected for output jac_g_x, at nonzero index 2 (row 79, col 0).") [.../casadi/core/oracle_function.cpp:377]
Error evaluating Jacobian of inequality constraints at user provided starting point.
  No scaling factors for inequality constraints computed!
CasADi - 2024-03-02 22:49:44 WARNING("solver:nlp_jac_g failed: NaN detected for output jac_g_x, at nonzero index 2 (row 79, col 0).") [.../casadi/core/oracle_function.cpp:377]"

I tried debugging this my self i came to a conclusion that my problem is withing the function "create_theta()", since when i bypass it and multiply two quaternion the code is able to give an optimal solution, but i cannot understand what i did wrong, since this is using an expression for quaternion integration that comes from here "Indirect Kalman Filter for 3D Attitude Estimation".

If anyone can offer some help it would be greatly appreciated. Full code bellow:

"import casadi as ca
import spatial_casadi as sc
import numpy as np
from pylab import plot, step, figure, legend, show, spy

class MPC:
    def __init__(self, J, c, A, desired_r, N=10, T = 1/10):

        # create opbject of opti class 
        self.opti = ca.Opti()
        
        ## declare parameters for values that do now change
        self.J = self.opti.parameter(3, 3)
        self.c = self.opti.parameter(3, 1)
        self.A = self.opti.parameter(3, 6)
        self.g = self.opti.parameter(3, 1)

        ## setting value for parameters
        self.opti.set_value(self.J, J)
        self.opti.set_value(self.c, c)
        self.opti.set_value(self.A, A)
        self.opti.set_value(self.g, np.array([0, 0, -9.81]))

        # declare parameters related to simulation, horizont and time step
        self.N = N 
        self.T = T

        self.I = self.opti.parameter(3, 3)
        self.opti.set_value(self.I, np.eye(3))

        ## store desired rotation
        self.desired_r = desired_r

        ## declare variables for optimization
        self.w = self.opti.variable(3, self.N+1)
        self.w_dot = self.opti.variable(3, self.N+1)
        self.q = self.opti.variable(4, self.N+1)

        ## declare control variables
        self.u = self.opti.variable(6, self.N+1)

        ## setup controller
        self.setup_controller()

    ## multiplication of quaternions
    def quaternion_multiplication(self, q, p):
        q1 = q[0]
        q2 = q[1]
        q3 = q[2]
        q4 = q[3]

        p1 = p[0]
        p2 = p[1]
        p3 = p[2]   
        p4 = p[3]

        a = ca.vertcat(
                ca.horzcat(q4, q3, -q2,  q1), 
                ca.horzcat(-q3, q4, q1, q2), 
                ca.horzcat(q2 , -q1, q4, q3), 
                ca.horzcat(-q1 , -q2,  -q3, q4)
            )

        b = ca.vertcat(p1, p2, p3, p4)

        q_ = a @ b
        return q_ / ca.norm_2(q_) 

    

    def create_theta(self, w):
        w_norm = ca.norm_2(w)
        epsilon = 1e-1

        w_norm += epsilon

        return ca.vertcat((w /  w_norm) * ca.sin(w_norm * self.T / 2), 
                            ca.cos(w_norm * self.T / 2) )
        

    def setup_controller(self):
        ## define initial conditions -> steady state all zeros

        zeros = self.opti.parameter(3, 1)
        self.opti.set_value(zeros, np.zeros(3))

        for i in range (0, self.N+1):
            self.opti.set_initial(self.q[:, i], sc.Rotation.from_euler('xyz',  [1, 0, 0]).as_quat(seq="xyzw"))
            #self.opti.set_initial(self.w[:, i], zeros)  

        # self.opti.callback(lambda j: plot(self.opti.debug.value(self.cost_function)))

        self.opti.subject_to(self.w[:, 0] == zeros)
        self.opti.subject_to(self.q[:, 0] == sc.Rotation.from_euler('xyz',  [0, 0, 0]).as_quat(seq="xyzw"))

## ERROR HERE
        for i in range(self.N+1):
            for j in range(6):
                self.opti.subject_to( self.opti.bounded(-(5000)**2, self.u[j, i], 5000**2))

        self.cost_function = 0

        for i in range (1, self.N+1):
            c_r = sc.Rotation.from_quat(self.q[:, i], seq='xyzw').as_matrix()
            ## trace (I - desired_r.transpose @ current_rot)
            self.cost_function += (ca.trace(self.I - (self.desired_r.as_matrix().T @ c_r)))**2

        self.opti.minimize(self.cost_function)

        ## declare contrains for the optimization problem 
        for i in range(1, self.N+1):
            c_r = sc.Rotation.from_quat(self.q[:, i], seq='xyzw').as_matrix()
            # constrain for system
            self.opti.subject_to(self.J @ self.w_dot[:, i]  + ca.skew(self.w[:, i]) @ self.J @ self.w[:, i] -  ca.skew(self.c) @ c_r.T @self.g == self.A @ self.u[:, i] )

            self.opti.subject_to(self.w_dot[:, i] == (self.w[:, i] - self.w[:, i-1]) / self.T)

            # Constrains for rotation movement -> quaternion integration
            self.opti.subject_to(self.q[:, i] == self.quaternion_multiplication(self.create_theta(self.w[:, i-1]), self.q[:, i-1]))

    

    def solve(self):
        opts_setting = {
            'ipopt.max_iter' :10000, 
            'ipopt.acceptable_tol':1e-1,
            'ipopt.acceptable_obj_change_tol':1e-1, 
            "nlp_scaling_method": "none",
            "tol": 5e-1, 
            "dual_inf_tol": 5.0, 
            "constr_viol_tol": 1e-1,
            "compl_inf_tol": 1e-1, 
            "acceptable_tol": 1e-2, 
            "acceptable_constr_viol_tol": 0.01, 
            "acceptable_dual_inf_tol": 1e10,
            "acceptable_compl_inf_tol": 0.01,
            "acceptable_obj_change_tol": 1e20,
            "diverging_iterates_tol": 1e20
        }

        self.opti.solver('ipopt')
        sol = self.opti.solve()
        return sol
         
def main():
    J = np.load('est_J1.npy')
    A = np.load('est_A1M.npy')
    c = np.load('est_c.npy')

    desired_r = sc.Rotation.from_euler('xyz', [20, 0, 0])

    mpc = MPC(J, c, A, desired_r)

    try: 
        sol = mpc.solve()
    except RuntimeError:
        print("An error occured -  debug mode")
       # print("------------------")
       # print(mpc.opti.debug.show_infeasibilities())
       # print("------------------")
       # print(mpc.opti.debug.value(mpc.cost_function))
       # print("------------------")
       # print(mpc.opti.debug.value(mpc.R))

if __name__ == '__main__':
    main()"

**Comment by Wayne-Z** [comment]
Hello, did you solve this error, I meet the similar problem due to the pow(x, 1/n) in g and acos(x) in f

**Comment by andre-rebelo-teixeira** [comment]
hello there. yes I solved the issue, my problem happened since casadi implemments the norm_2 as the square root of the squared sum, but they cannot handle the square root of zero. So i just has to sum a small value to my vector.
