### ISSUE TITLE
g and lam_g from nlpsol_out does not return any values

### ISSUE THREAD

**Issue by EveCharbie** [casadi/casadi#3603]
Hi :)
I am solving using Ipopt and I am trying to recompute the inf_pr and inf_du to display it on my online graph using a callback function.
Currently, I get the output from nlpsol_out using this:
```
args_dict = {}
for (i, s) in enumerate(nlpsol_out()):
    args_dict[s] = arg[i]
```
Then if I print args_dict during the resolution of the problem, I get:
```
{'x': DM([0.0025, 0, 0, ..., 0, -1.77561, 0]), 'f': DM(6.88243), 'g': DM(0x1), 'lam_x': DM([0, 0, 0, ..., 0, -0.047183, 0]), 'lam_g': DM(0x1), 'lam_p': DM(0x0)}
```
However, I do have constraints declared in my problem, thus 'g' and 'lam_g' does not seem to display the right thing.
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************
This is Ipopt version 3.14.12, running with linear solver MUMPS 5.2.1.
Number of nonzeros in equality constraint Jacobian...:     8383
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:     3991
Total number of variables............................:     1996
                     variables with only lower bounds:        0
                variables with lower and upper bounds:     1996
                     variables with only upper bounds:        0
Total number of equality constraints.................:     1600
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  0.0000000e+00 3.14e+00 0.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  6.8824317e+00 2.35e+00 9.52e-01  -1.0 2.92e+01    -  3.32e-01 2.50e-01f  3
   2  1.1340793e+01 2.06e+00 2.19e+00  -1.0 4.68e+01    -  5.92e-01 1.25e-01h  4
   3  1.4030567e+01 1.95e+00 2.80e+00  -1.0 6.44e+01    -  3.62e-01 5.39e-02h  4
```
Could you please help me understand?

**Comment by EveCharbie** [comment]
@jaeandersson would you happen to know if it is a CasADi problem or an IPOPT problem?

**Comment by jaeandersson** [comment]
This looks like a CasADi bug. 'g' and 'lam_g' should have the dimension of 'g' in your setup, which should be 1600 in your case. If you just want to look at the values in each iteration, you can try increasing the "print_level" for IPOPT. Iirc, level 8 or higher will include values of g and lam_g in each iteration. You can also set "file_print_level" to 8 or higher for the same result (and redirect the output to a file). Note that IPOPT works with equality constraints internally, so if you have inequality constraints in g, IPOPT will create new variables corresponding to those g entries. That doesn't seem to be the case for you though.

**Comment by jgillis** [comment]
This may happen if you make `detect_simple_bounds` true (default false).

**Comment by EveCharbie** [comment]
Thank you for your answer.
It seems like the problem was the user, woupsi! I had set ng = 0 in the callback function.
Thank you guys very much for the amazing work :)
