### ISSUE TITLE
Problem with installation on Matlab r2023b

### ISSUE THREAD

**Issue by aherremans** [casadi/casadi#3656]
After downloading a new Matlab version (r2023b) (on Mac), I have trouble installing CasADi. While I have unzipped CasADi and added it to my path, running a toy example

```
import casadi.*
x = MX.sym('x')
disp(jacobian(sin(x),x))
```

fails with the following error message 

```
Unrecognized function or variable 'casadiMEX'.

Error in casadi.GenMX.sym (line 833)
     [varargout{1:nargout}] = casadiMEX(356, varargin{:});
```

This problem didn't pop up when using an older version of Matlab.

**Comment by CharukaP** [comment]
I'm facing the same issue. Have you managed to solve this. Im using R2023b on mac ARM.

Unrecognized function or variable 'casadiMEX'.

Error in casadi.GenMX.sym (line 833)
     [varargout{1:nargout}] = casadiMEX(356, varargin{:});

**Comment by CharukaP** [comment]
Yes I have checked it and I'm trying to use the Casadi build highlighted in the image. For Matlab it is the R2023b build for ARM.

![46D9787C-C91B-409C-AD8E-D1BF7B2A2942](https://github.com/casadi/casadi/assets/148147781/2054a574-1f35-4502-9443-69758c02a77b)

**Comment by gregreich** [comment]
You need the other one

**Comment by CharukaP** [comment]
Thank you very much! It worked. However need to reset read and write permission in order to use it.

**Comment by aherremans** [comment]
This worked for me as well, thank you!

**Comment by gregreich** [comment]
Glad it helped. @aherremans: If it works for you now, please consider closing the issue.
