### ISSUE TITLE
Performance difference between CasADi 3.5.5 and 3.6.4

### ISSUE THREAD

**Issue by nickbianco** [casadi/casadi#3713]
Hello, @aymanhab and I are currently working on updating the versions of CasADi and Ipopt used to build the [core OpenSim libraries](https://github.com/opensim-org/opensim-core). After updating the build process to use CasADi 3.6.4, I noticed a significant slowdown in one of our trajectory optimization examples. A problem that previously was taking ~10 seconds to solve was now taking ~1.5 minutes.

Using the same build process, I downgraded to CasADi 3.5.5 and performance was restored back to the original ~10 second solve time. I noticed when solving this example problem with 3.6.4, the number of nonzeros in the equality constraint Jacobian was much larger (~5e6) compare to solving with 3.5.5 (~7e4). The number of variables, bounds, and equality constraints were the same between problems. I attached the full Ipopt output for both problem below.

These problems are solved in OpenSim using the `nlpsol` interface. I thought at first the difference might be related to the newer "detect_simple_bounds" flag, but enabling this flag changed nothing since we already provide simple variable bounds directly to `nlpsol`. 

Both 3.5.5 and 3.6.4 were built with Ipopt 3.14.16 and MUMPS 5.6.2. I haven't tried comparisons using any intermediate versions between  3.5.5 and 3.6.4.

### Ipopt output files
[ipopt_output_casadi_3.5.5.txt](https://github.com/user-attachments/files/15570697/ipopt_output_casadi_3.5.5.txt)
[ipopt_output_casadi_3.6.4.txt](https://github.com/user-attachments/files/15570698/ipopt_output_casadi_3.6.4.txt)

**Comment by jaeandersson** [comment]
No idea what might have cause the Jacobian nonzeros to blow up like that. Maybe @jgillis knows. Easiest way to debug is to do a git-bisect on the `main` branch to find the offending commit.

**Comment by nickbianco** [comment]
Sounds reasonable enough. I don't bandwidth for this at th moment, but when I do I can try to find the problematic commit.

**Comment by nickbianco** [comment]
I build our stack against CasADi 3.6.0 and still see the Jacobian nonzeros blowing up. Will continue bisecting from there.

**Comment by nickbianco** [comment]
@jaeandersson git-bisect identified 428c262e4e430ecbc9ea3c47a7780cae84b7a4cb as the offending commit, but the problem was on our end. The syntax changed for the Jacobian sparsity methods and we didn't update properly so our sparsity detection was being ignored completely.

Closing.
