### ISSUE TITLE
MATLAB Coder meets CasADi codegen - macos - MEX, dylib, path error

### ISSUE THREAD

**Issue by borlum** [casadi/casadi#3720]
When following the (by the way, fantastic guide) here:

https://web.casadi.org/blog/matlab-coder/

on MacOS 14.5, Apple Sillicon - I run into issues when I try to call the resulting MEX:

```
Invalid MEX-file '/Users/borlum/repos/casadi_codegen/solveOCP_mex.mexmaca64':
dlopen(/Users/borlum/repos/casadi_codegen/solveOCP_mex.mexmaca64, 0x0006): Library not loaded:
/Users/ghrunner/actions-runner/_work/casadi/casadi/build/external_projects/lib/libipopt.3.dylib
  Referenced from: <9D5678F9-58C4-39B4-9C04-886C2F31EE13>
  /Users/borlum/repos/GoFill/solveOCP_mex.mexmaca64
  Reason: tried:
  '/Users/ghrunner/actions-runner/_work/casadi/casadi/build/external_projects/lib/libipopt.3.dylib'
  (no such file),
  '/System/Volumes/Preboot/Cryptexes/OS/Users/ghrunner/actions-runner/_work/casadi/casadi/build/external_projects/lib/libipopt.3.dylib'
  (no such file),
  '/Users/ghrunner/actions-runner/_work/casadi/casadi/build/external_projects/lib/libipopt.3.dylib'
  (no such file)
```
 
It seems the path to the pre-built included ipopt is hardcoded to the path of its location on the GitHub runner that built CasADi for MacOS.

Not a big issue, I can link to my own built libraries - and I rarely use MEX.
The benefit now being able to codegen MATLAB that uses CasADi - and linking against a target compatible ipopt is HUGE. This is such a cool feature 👍

**Comment by jgillis** [comment]
Can't remember fixing it but since 3.6.6, there is no external_projects path in the install name:
```
otool -l casadi/libipopt.3.dylib | grep -A 3 LC_ID_DYLIB
```
