### ISSUE TITLE
Using rootfinder object inside optimization fails

### ISSUE THREAD

**Issue by MHW-UDS** [casadi/casadi#3727]
I'm using Matlab and base Casadi 3.6.3 (no additional plugins): minimal non-working example

```
clearvars
clc

import casadi.*

%% define rootfinding problem
x = SX.sym('x',[1,1]);
g = x-2;
g_fun = Function('g',{x},{g},{'x'},{'g'});
g_root = rootfinder('g_root','newton',g_fun);

clearvars x g

%% solver-oriented nlpsol approach
x = MX.sym('x',[1,1]);
f = x^2;
g = g_root(x);

x_lb = -Inf;
x_ub =  Inf;
g_lb = 0;
g_ub = 0;
solver_NVPs = ...
    {'x0',  10, ... 
     'lbx', x_lb, 'ubx', x_ub,...
     'lbg', g_lb, 'ubg', g_ub};

OP = struct('f',f,'g',g,'x',x);
sol_object = nlpsol('solver','ipopt',OP);
sol = sol_object(solver_NVPs{:});
```

Expected behavior: Optimal solution  x=2 and f=4. 
Actual behavior: "Converged to a point of local infeasibility. Problem may be infeasible." 

Same happens for Opti stack helper class (of course).

Any idea why it does not work although "Rootfinding objects in CasADi are differential objects and derivatives can be calculated exactly to arbitrary order"?

**Comment by jaeandersson** [comment]
As you probably figured out, the NLP constraint function which is always g==2. It doesn't actually depend on x. That makes the constraint 0 <= g<= 0 unfeasible.

**Comment by MHW-UDS** [comment]
Yes, I understood it as "find x s.t. rf-problem is satisfied and hence g=0" but is is "use x as an initial guess to the rf-problem and g=x where x satisfies the rf-problem".
Thanks for the reply, though!
