### ISSUE TITLE
Bug in triusolve

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#3746]
https://github.com/casadi/casadi/blob/72764dc73eab7b935db7e302278508855815883b/casadi/core/solve_impl.hpp#L434

**Comment by jaeandersson** [comment]
Same bug for trilsolve  
```
 g << g.trilsolve(this->dep(1).sparsity(), g.work(arg[1], this->dep(1).nnz()),
```

**Comment by andreasbell** [comment]
Is it possible to include the fix for this by @tmmsartor before the next release?

**Comment by jgillis** [comment]
This was merged
