### ISSUE TITLE
Indexing using MX variables/ expressions

### ISSUE THREAD

**Issue by maxesit** [casadi/casadi#3751]
Greetings,

I am working on a mixed nonlinear integer programming problem. (bonmin solver, opti plugin)

K is a discrete( integer) control variable.
I have an array A. 

What I need to do is inside of the constraints, call A[K]. 

This returns an error, because K is a MX variable. Floor(K) returns float only if K is float( MX if K is MX).
Is there a workaround for this, or a way in casadi to define K as an integer variable? (i.e. K = opti.variable(casadi_int) )

Thanks for your time!

**Comment by jgillis** [comment]
`A[K]` with `K` and `MX` is technically allowed when A is an `MX`.
You could do `MX(A)[K]`.

This doesn't strike me as a sound modeling technique but it may work:

```python
import casadi as ca

opti = ca.Opti()

K = opti.variable()
opti.set_domain(K,'integer')


A = [3,2,1,2,3]

A = ca.MX(A)

opti.minimize(A[K])

opti.subject_to(0 <= (K <= 4))

opti.solver("bonmin")
sol = opti.solve()

print(sol.value(K))
```
