### ISSUE TITLE
terminate called after throwing an instance of 'casadi::CasadiException'

### ISSUE THREAD

**Issue by Geonhee-LEE** [casadi/casadi#3758]
Hi, I have tried to implement the path tracking using casadi. I frequently encounter following error. It is formulated with the casadi opti stack .

```
terminate called after throwing an instance of 'casadi::CasadiException'
  what():  Error in Opti::value [OptiNode] at .../casadi/core/optistack.cpp:175:
.../casadi/core/optistack_internal.cpp:872: Assertion "solved()" failed:
This action is forbidden since you have not solved the Opti stack yet (with calling 'solve').
```

**Comment by jgillis** [comment]
This indicates that you attempt to post-process results from Opti while it was either never solved or failed to solve successfully.
You can post-process non-converged results with `opti.debug`
