### ISSUE TITLE
Crash with 3.6.6 which did not occur with 3.6.5

### ISSUE THREAD

**Issue by jbentvelsen** [casadi/casadi#3793]
Some of our models stopped working since casadi 3.6.6. Python crashes without any exception. I do get the folllowing message in the terminal: 

`Assertion failed: isNlpFeasible(minlp, primalTolerance), file /work/build/external_projects/src/bonmin-external/Bonmin/src/CbcBonmin/Heuristics/BonHeuristicDiveMIP.cpp, line 133  `

I have exported a particular setup which gives this crash (with casadi 3.6.6, not 3.6.5), tested with Python 3.9 and 3.11. 
[example_crash.zip](https://github.com/user-attachments/files/16510763/example_crash.zip)

Any idea what might be the issue?

**Comment by jgillis** [comment]
which OS?

**Comment by jbentvelsen** [comment]
> which OS?
I ran and created the example on Windows, but on our Gitlab pipeline running Linux we get the same error.

**Comment by jgillis** [comment]
Can you add the diagnostics suggested in https://github.com/casadi/casadi/wiki/FAQ:-How-to-debug-regressions-in-numerical-solvers-when-updating-CasADi%3F and check for differences between 3.6.5 and 3.6.6?

**Comment by jbentvelsen** [comment]
The files generated when using 3.6.6 are identical to equal-named files in 3.6.5 (under 3.6.5 I get a lot more files, because there is no crash during the first iteration). Would that mean the issue is a new release of ipopt?

**Comment by jgillis** [comment]
Strange, no update of Ipopt, bonmin or dependencies was performed. Will run valgrind to check for memory issues

**Comment by jgillis** [comment]
This is not about memory issues. First bad commit is 56511d09dd3d2f06519ed2d368149f3f13b2fdca.
This must be about DNDEBUG flags having vanished..

**Comment by jbentvelsen** [comment]
Thanks for fixing this! When do you plan to release Casadi 3.6.7?

**Comment by jgillis** [comment]
You can find corrected hinaries here: https://github.com/casadi/casadi/releases/tag/nightly-main

3.6.7 is probably a week away

**Comment by jbentvelsen** [comment]
Thank you! All our tests succeed again with this new version.
