### ISSUE TITLE
Casadi on Mac M1 installation issue.

### ISSUE THREAD

**Issue by basitimran37** [casadi/casadi#3843]
For M1 Mac, and with MATLAB R2023b for Apple Silicon, I am seeing the error.

```
Unrecognized function or variable 'casadiMEX'.

Error in casadi.SX (line 873)
        tmp = casadiMEX(610, varargin{:});
```

I did put `Casadi` in my root folder and added it to path in MATLAB using:

`addpath('/Users/basit/casadi-3.6.6-osx64-matlab2018b')` 

Error screenshot is attached: 
<img width="496" alt="image" src="https://github.com/user-attachments/assets/b87222de-cd92-477b-af4b-8d492e3639af">

**Comment by jgillis** [comment]
`/Users/basit/casadi-3.6.6-osx64-matlab2018b` seems to indicate you grabbed the wrong binary.
Look for `casadi-3.6.6-osx_arm64-matlab2018b` instead: https://github.com/casadi/casadi/releases/download/3.6.6/casadi-3.6.6-osx_arm64-matlab2018b.zip

**Comment by basitimran37** [comment]
Looks like there are multiple issues here. I got it working following the two steps:

1) Get the correct binary as you indicated above. The default link for Mac M1 binary does not download the correct zip file.
2) I followed the steps highlighted [here](https://github.com/casadi/casadi/issues?page=7&q=is%3Aissue+is%3Aopen)
