### ISSUE TITLE
FATROP / Python: Program freezes after inf evaluations 

### ISSUE THREAD

**Issue by EserSteffen** [casadi/casadi#3857]
Hello, 

I have been enjoying the addition of fatrop to casadi 3.6.6 and the speedups. 
However, I have encountered an issue that makes it hard to reliably use.
When a component of the constraint vector g evaluates to infinity, the whole program freezes (including unrelated threads).

I have attached a minimum failing example:
https://gist.github.com/EserSteffen/92a304115566e84a0cbd42e2a604719f

When chosing ipopt as the solver, the end of the file is reached. When chosing fatrop, the programm freezes. 
The issue only occurs when setting g to infinity, not f.

I am running this on windows, using python 3.12 with casadi 3.6.6
Not sure if this is an issue with the casadi interface or fatrop itself. 

Best regards,
Steffen

**Comment by jgillis** [comment]
Thanks for reporting

**Comment by jgillis** [comment]
Seems to be fixed in current main.
