### ISSUE TITLE
Difference in NLP generated by Python and C++

### ISSUE THREAD

**Issue by mihirus** [casadi/casadi#3863]
`generate_dependencies` in python and C++ generates C code that is not cross compatible. I have only been able to link to the shared library in the same language that the C code was generated from. 

Python code:
```
x = MX.sym('x', 2)
f = x[0]*x[0] + x[1]*x[1]
g = x[0] + x[1] - 10
nlp = {"x": x, "f": f, "g": g}
solver = nlpsol("solver", "ipopt", nlp)
solver.generate_dependencies("nlp_code_gen_py.c")
```

C++ code:
```
casadi::MX x = casadi::MX::sym("x", 2);
casadi::MX f = x(0)*x(0) + x(1)*x(1);
casadi::MX g = x(0)+x(1)-10;
casadi::Function solver = casadi::nlpsol("solver", "ipopt", {{"x", x}, {"f", f}, {"g", g}});
solver.generate_dependencies("nlp_code_gen_cpp.c");
```

Compiling using `gcc -fPIC -shared -O3 nlp_code_gen.c -o nlp_code_gen.so`, then importing that shared library and calling the solver in the other language results in a similar error in each language:

```
RuntimeError: .../casadi/core/function_internal.cpp:146: Error calling IpoptInterface::init for 'solver':
Error in Function::factory for 'nlp' [External] at .../casadi/core/function.cpp:1789:
Failed to create nlp_hess_l:[x, p, lam:f, lam:g]->[triu:hess:gamma:x:x] with {"gamma": [f, g]}:
.../casadi/core/external.cpp:492: Assertion "s_io[i] == ret.name_out(i)" failed:
Inconsistent output name. Expected: [triu_hess_gamma_x_x], got hess_gamma_x_x for output 0
```

Diff'ing the output C files results in a bunch of small syntax differences (`) {` vs `}(` and then the difference that results in this error. The first return in the following function has `triu_` in the beginning if generated from Python, and no `triu_` if C++. Adding/removing that string and then compiling to the shared library fixes the compatibility issue.

```
CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_out(casadi_int i) {
  switch (i) {
    case 0: return "triu_hess_gamma_x_x";
    default: return 0;
  }
}
```

**Comment by jgillis** [comment]
Surely this must be caused by mismatching CasADi version?
