### ISSUE TITLE
Plugin 'bonmin' is not found

### ISSUE THREAD

**Issue by saruchrathore** [casadi/casadi#3865]
I trying to solve a simple MILP in Spyder using Casadi. I am using a Ubuntu system. I have installed the 'coinbonmin' package from conda-forge. But I am getting the error 'Plugin 'bonmin' is not found'. 

What am I missing?

Note: 'ipopt' works.

**Comment by GuowenLi-PhD** [comment]
Hi @saruchrathore , did you fond the solution for this issue?

**Comment by GuowenLi-PhD** [comment]
Thanks @saruchrathore. FYI, I resolved this issue by installing casadi from `pip` instead of `conda`.
