### ISSUE TITLE
Does Casadi 3.6.6 respect `expand = True` in `opti.solver` plugin_options?

### ISSUE THREAD

**Issue by patrsc** [casadi/casadi#3872]
I experience a much higher compilation time in Casadi 3.6.6 (about 5 minutes) compared to Casadi 3.6.5 (about 15 seconds) when compiling generated C code of an optimization problem formulated with the opti stack (using ipopt solver).
 
I suspect that the issue is that
 
```
opti.solver("ipopt", plugin_options, solver_options)
```
 
does not respect `{expand: True}` inside `plugin_options`.
 
If I set `expand` to `False` in 3.6.5, I get a similar-size output of `opti.to_function` as in 3.6.6 with `expand` set to `True`. With `expand` set to `True` in 3.6.5 the output size is much smaller (about 1.7 MB compared to 2.9 MB).

**Comment by jgillis** [comment]
It's your lucky day. Today's 3.6.7 release fixes this regression.

**Comment by patrsc** [comment]
Great to hear! Thanks!
