### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by l29ah** [casadi/casadi#3877]
I'm trying to install casadi master on a python-3.12 Gentoo system and get the following error:
```
*** Error compiling '/var/tmp/portage/sci-libs/casadi-9999/image/usr/lib/python3.12/site-packages/casadi/tools/structure.py'...
  File "/usr/lib/python3.12/site-packages/casadi/tools/structure.py", line 271
    raise new_exc.__class__, new_exc, tb
                           ^
SyntaxError: invalid syntax

```
Is it me or casadi doesn't yet work with python-3.12?

**Comment by jgillis** [comment]
That's interesting because 3.12 is for sure supported. Can you show me the exact command used? Is it system python? Ideally, could you reproduce this in Docker?

**Comment by jgillis** [comment]
So its attempting to bytecompile a python file that is loaded only on the condition that we are in python <= 2.7
