### ISSUE TITLE
error when using 'horzcat' to make a SX 

### ISSUE THREAD

**Issue by robin-bird-go** [casadi/casadi#3885]
Hello, I'm new to using casadi c++ API, I struggled to create a SX matrix using horzcat, like things below:
`  SX test = horzcat(SX::zeros(1, 1), m * w, -m * v, SX::zeros(1, 1), Iz * r, -Iy * q);`

,where v,w are also SX variables(1*1).
the problem is that I ensure every element is SX type, but I still get the error :

`error: no matching function for call to ‘horzcat(casadi::Matrix<casadi::SXElem>, casadi::Matrix<casadi::SXElem>, casadi::Matrix<casadi::SXElem>, casadi::Matrix<casadi::SXElem>, casadi::Matrix<casadi::SXElem>, casadi::Matrix<casadi::SXElem>)’
  118 |         SX test = horzcat(SX::zeros(1, 1), m * w, -m * v, SX::zeros(1, 1), Iz * r, -Iy * q);
      |                                                                                           ^
`

I didn't find any useful discussion or documents telling this, I would be grateful if anyone can help me!!! T_T

I also want to know if there are other better ways of defining this matrix since a matrix could have many constant values that maybe don't necessarily be changed into SX type?

**Comment by jaeandersson** [comment]
You need to pass an std::vector or initializer list. Try SX::horzcat({...}).

**Comment by robin-bird-go** [comment]
> You need to pass an std::vector or initializer list. Try SX::horzcat({...}).

Thanks! I tried this way, and it works!
```
    std::vector<double> zero(1); 
    casadi::SX C_RB = casadi::SX::vertcat({
    casadi::SX::horzcat({casadi::SX::zeros(1, 4), m * w, -m * v}),
    casadi::SX::horzcat({casadi::SX::zeros(1, 3), -m * w, casadi::SX::zeros(1, 1), m * u}),
    casadi::SX::horzcat({casadi::SX::zeros(1, 3), m * v, -m * u, casadi::SX::zeros(1, 1)}),
    casadi::SX::horzcat({zero, m * w, -m * v, zero, Iz * r, -Iy * q}),
    casadi::SX::horzcat({-m * w, zero, m * u, -Iz * r, zero, Ix * p }),
    casadi::SX::horzcat({m * v, -m * u, zero, Iy * q, -Ix * p, zero})} );
```c++

**Comment by robin-bird-go** [comment]
I have solved my problem, Thanks for your patience~
