### ISSUE TITLE
Excessive printing when using fatrop interface

### ISSUE THREAD

**Issue by lvanroye** [casadi/casadi#3948]
Hello,

When utilizing the fatrop interface, excessive printing occurs. This issue seems to have been introduced in commit cd9d152b3da3f7410afcfeb0b8a0bb70874ac244. I believe it stems from the blasfeo_print_dmat statement located at line 398 of [‎casadi/interfaces/fatrop/fatrop_runtime.hpp](https://github.com/casadi/casadi/blob/cd9d152b3da3f7410afcfeb0b8a0bb70874ac244/casadi/interfaces/fatrop/fatrop_runtime.hpp#L398).

Best,
Lander

**Comment by jgillis** [comment]
Thanks for reporting, fixed in 091f249
