### ISSUE TITLE
Printing to std::cerr lost on Windows 7

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#532]
There appears to be problems with printing to screen when using the Windows binaries on a Windows 7. See the following forum post:

https://groups.google.com/forum/?fromgroups=#!topic/casadi-users/PBL-J8w6ZZA

It appears as if all output sent to std::cerr, from both IPOPT and CasADi gets lost.

**Comment by jgillis** [comment]
This is most likely fixed in develop #1450
