### ISSUE TITLE
Matrix exponential

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#542]

**Comment by ghorn** [comment]
That matrix exponential is part of `slicot`, see

http://slicot.org/objects/software/shared/doc/MB05MD.html
http://slicot.org/objects/software/shared/doc/MB05ND.html
http://slicot.org/objects/software/shared/doc/MB05OD.html

Perhaps it should be added as an interface.

**Comment by jgillis** [comment]
Probably `expm(A*t)` with is already very useful.

Nonetheless, for future reference here are AD rules for `Y=expm(A)`:

`Y_dot=expm([A 0; A_dot A])[ lower left block]`
`A_bar = integrate( expm(A'*(1-t)) Y_bar  expm(A't) ,t,0,1 )`

```matlab
eps = 1e-6;
t = 0.2;

n = 4;

Anum = rand(n);

dA = rand(n);
Yb = rand(n);

import casadi.*
x = MX.sym('x',n);
A = MX.sym('A',n,n);

dae = struct('x',x,'p',A,'ode',A*x);
intg = integrator('intg','cvodes',dae,struct('reltol',1e-14,'abstol',1e-14));


%Note: intg.reverse(1) has
%rx = MX.sym('rx',n);
%dae = struct('x',x,'p',vec(A),'ode',A*x,'rx',rx,'rode',A'*rx,'rquad',rx*x');

Intg = intg.map('identity','serial',n,[1],[]);

out = Intg('x0',eye(n),'p',A);
expmF = Function('expm',{A},{out.xf});

disp('We can mimic expm with CasADi integrators')
norm_1(expmF(Anum)-expm(Anum))


expmFf = expmF.forward(1);
expmFr = expmF.reverse(1);



(expm(Anum+dA*eps)-expm(Anum))/eps;
expmFf(Anum,0,dA);
out = expm([Anum zeros(n,n);dA Anum]);

disp('Proof first formula')
norm_1(out(n+1:end,1:n)-expmFf(Anum,0,dA))


%%
t = MX.sym('t');
ex = MX.sym('ex',n*n);

edae = struct('x', ex, 'p',vec(A),'t',t,'ode',vec(expmF(A'*(1-t))*Yb*expmF(A'*t)));
eintgr = integrator('intg','cvodes',edae,struct('reltol',1e-14,'abstol',1e-14));
out = eintgr('x0',0,'p',Anum(:));reshape(out.xf,n,n)
disp('Proof second formula')
norm_1(reshape(out.xf,n,n)- expmFr(Anum,0,Yb))
```

**Comment by jaeandersson** [comment]
This isn't really a clean atomic operation, though. I see no real added benefit over just using integrators.

**Comment by jgillis** [comment]
And for A constant:

`Ydot = A expm(A t) tdot`
`tbar = Ybar :  A expm(A t)`, where ':' sums the elementwise product

```matlab
%%

f = Function('f',{t,A},{expmF(A*t)});

ff = f.forward(1);
fb = f.reverse(1);

% dY = A expm(A*t) dt
disp('Other proof')
norm_1(ff(0.1,Anum,0,3,0)-Anum*expm(Anum*0.1)*3)


norm_1(sum(sum(Yb.*(Anum*expm(Anum*0.1))))-fb(0.1,Anum,0,Yb))
```

**Comment by jgillis** [comment]
Alternative formulas for general `Y = expm(A)`:

With the help of I. Najfeld, T.F. Havel, Derivatives of the Matrix Exponential and Their Computation, Advances in Applied Mathematics:

`Y_dot= expm([A A_dot; 0 A])[ upper right block]`
`A_bar = expm([A^T Y_bar; 0 A^T])[ upper right block]`

The terms in this paper are `directional derivative of matrix exponential ` and `gradient of matrix exponential`.

With this formula, the `expm` looks more like a sensible primitive. Not sure yet what complexity implications are of the doubling in dimensions.

```python
from casadi import *
import scipy.linalg

np.random.seed(0)
eps = 1e-6
t = 0.2

n = 3

Anum = np.random.random((n,n))
Adotnum = np.random.random((n,n))
Abarnum = DM(np.random.random((n,n)))



x = SX.sym('x',n)
xdot = SX.sym('xdot',n)
A = SX.sym('A',n,n)
Adot = SX.sym('Adot',n,n)

dae = {'x':x,'p':vec(A),'ode':mtimes(A,x)}
fsens_dae = {'x':veccat(x,xdot),'p':veccat(A,Adot),'ode':mtimes(blockcat([[A,DM.zeros(n,n)],[Adot, A]]),veccat(x,xdot))}


F = integrator('F','cvodes',dae,{'reltol':1e-14,'abstol':1e-14});

fsens_F = integrator('F','rk',fsens_dae)

FM = F.map('identity','serial',n,[1],[]);

A = MX.sym('A',n,n)

out = FM(x0=DM.eye(n),p=vec(A))
expmF = Function('expm',[A],[out["xf"]])


print "error nominal", expmF(Anum)-scipy.linalg.expm(Anum)


Y0 = expmF(Anum)
YP = expmF(Anum+eps*Adotnum)

FD= (YP-Y0)/eps


print "error fwd mode <-> finite diffs"
expmFF = expmF.forward(1)
S= expmFF(Anum,Y0,Adotnum)

print FD-S

print "Forward mode AD of general expm"
print S

print scipy.linalg.expm(np.array(blockcat([[Anum,Adotnum],[DM.zeros(n,n), Anum]])))

expmFR = expmF.reverse(1)
S= expmFR(Anum,Y0,Abarnum)

print "Reverse mode AD of general expm"
print S

print scipy.linalg.expm(np.array(blockcat([[Anum.T,Abarnum],[DM.zeros(n,n), Anum.T]])))
```

**Comment by rienq** [comment]
I just want to add the comment that any potential future support for matrix exponentials could be very useful also for geometric optimal control on Lie groups.. ;-)

**Comment by jgillis** [comment]
Matrix exponential with slicot is in fact running on a local version. You
can expect it for next release..

Op 4-mrt.-2017 00:40 schreef "rienq" <notifications@github.com>:

**Comment by mccullerlp** [comment]
Nice, I was just running into needing this in my code. I'll note that scipy also has an implementation

https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.sparse.linalg.expm.html#scipy.sparse.linalg.expm

alas it is not wrapped Fortran/C but actual python code. It may provide an alternative for scipy users that can't get slicot.

**Comment by jaeandersson** [comment]
@jgillis So this is working now?

**Comment by gmsanchez** [comment]
Hi! I am trying to use matrix exponential function in version 3.2.0 (using Linux binary) and when I run the following code

```
A = casadi.DM([[1,2,3],[4,5,6]])
casadi.expm(A)
```
throws the following error

```
CasADi warning: "The assertion "handle!=0" on line 287 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp" failed. 
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_expm_slicot.so': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/home/gsanchez/.local/lib/python2.7/site-packages/casadi' :
    Error code: /home/gsanchez/.local/lib/python2.7/site-packages/casadi/libcasadi_expm_slicot.so: cannot open shared object file: No such file or directory
  Tried '' :
    Error code: libcasadi_expm_slicot.so: cannot open shared object file: No such fi... truncated" issued  on line 143 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp". 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/home/gsanchez/test_expm_casadi.py", line 8, in <module>
    casadi.expm(A)
  File "/home/gsanchez/.local/lib/python2.7/site-packages/casadi/casadi.py", line 18155, in expm
    return _casadi.expm(*args)
RuntimeError:  on line 382 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp"
Plugin 'slicot' is not found.
```

I have libslicot-dev and libslicot0 installed on Ubuntu 16.04

Greetings!

**Comment by jgillis** [comment]
Yup, its working but disabled unintentionally in the binaries.
Ill flip the switch..

**Comment by jgillis** [comment]
Could you try again with https://sourceforge.net/projects/casadi/files/CasADi/commits/64b7712/linux/ ?

**Comment by gmsanchez** [comment]
@jgillis it works. Thanks a lot!

**Comment by krishnakumarg1984** [comment]
Does not work with the matlab linux binaries of casadi 3.2.3 (latest as of Sep 30,2017).

I get the exact same error message.

CasADi warning: "The assertion "handle!=0" on line 287 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp" failed. 
PluginInterface::load_plugin: Cannot load shared library 'libcasadi_expm_slicot.so': 
   (
    Searched directories: 1. casadipath from GlobalOptions
                          2. CASADIPATH env var
                          3. PATH env var (Windows)
                          4. LD_LIBRARY_PATH env var (Linux)
                          5. DYLD_LIBRARY_PATH env var (osx)
    A library may be 'not found' even if the file exists:
          * library is not compatible (different compiler/bitness)
          * the dependencies are not found
   )
  Tried '/home/kg314/casadi-matlabR2014b-v3.2.3' :
    Error code: libslicot.so.0: cannot open shared object file: No such file or directory
  Tried '' :
    Error code: libslicot.so.0: cannot open shared object file: No such file or directory
  Tried '.' :
    Error code: ./libcasadi_expm_slicot.so: cannot open shared object file: No such file or directory
" issued  on line 143 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp". 
Error using casadi.GenericMatrixCommon/expm (line 515)
 on line 382 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/plugin_interface.hpp"
Plugin 'slicot' is not found.

**Comment by jaeandersson** [comment]
Deleted cross-post

**Comment by krishnakumarg1984** [comment]
jgillis commented on May 29
"Yup, its working but disabled unintentionally in the binaries.
Ill flip the switch.."

Looking at the details, it seems that this has been fixed only for the python interface to casadi.

The matlab interface does not seem to have this bug fix. I do have the file 'libcasadi_expm_slicot.so' in my local casadi folder (which is in matlab path).

I am using the latest matlab casadi linux binary (http://files.casadi.org/3.2.3/linux/casadi-matlabR2014b-v3.2.3.tar.gz) 

I request you to investigate whether this feature has been unintentionally disabled in the matlab casadi binaries (just like the python case here).

**Comment by jgillis** [comment]
Hi Krishna,

The binary you link to does have the interface, and it is unit-tested too.
Note that we cannot ship solicit itself, only an interface to it.
Please follow up on the forum for further discussion about obtaining solicit.

**Comment by GPrathap** [comment]
I also had the same issue, in order to use **expm** in casadi 3.5
I had to install 

```
sudo apt-get install libslicot-dev 
sudo pip install slycot
```

**Comment by merlingoescrazy** [comment]
same problem here using Matlab 2023b

**Comment by MingxuanChe** [comment]
Hi. I am using casadi 3.6.3 with python and had the same "slicot not found" issue. Any update on this?

**Comment by chenghuailin** [comment]
I have the same issue

when running
`import casadi`
`A = casadi.DM([[1,2,3],[4,5,6],[7,8,9]])`
`casadi.expm(A)`
I got the error `libcasadi_expm_slicot.so`

I have already run
`sudo apt-get install libslicot-dev`
`pip install slycot`
and have
`libslicot-dev is already the newest version (5.0+20101122-4build1).`
`slycot(0.6.0)`

**Comment by chenghuailin** [comment]
I have the same issue using casadi 3.6.7

when running
`import casadi`
`A = casadi.DM([[1,2,3],[4,5,6],[7,8,9]])`
`casadi.expm(A)`
I got the error `libcasadi_expm_slicot.so`

I have already run
`sudo apt-get install libslicot-dev`
`pip install slycot`
and have
`libslicot-dev is already the newest version (5.0+20101122-4build1).`
`slycot(0.6.0)`

Can you reopen this issue?
