### ISSUE TITLE
casadi.logic_xor

### ISSUE THREAD

**Issue by bransfor** [casadi/casadi#586]
CasADi has the following functions `logic_and`, `logic_not`, and `logic_or`. An additional operator for xor could be added and called `logic_xor`. From a [SO discussion](http://stackoverflow.com/a/433161) 
```Python 
logic_xor = lambda x, y: casadi.isZero(x) != casadi.isZero(y)
```

**Comment by jaeandersson** [comment]
I took a shot at implementing this, but actually it makes little sense. xor is fundamentally a bitwise operation and at the moment, we don't support any bitwise operations (neither bitwise or not bitwise and). Appearently `x ^ y` is not even defined for double.

```
C++11 §5.12 Bitwise exclusive OR operator

The usual arithmetic conversions are performed; the result is the bitwise exclusive OR function of the operands. The operator applies only to integral or enumeration operands.
```

I'm open for a more general treatment of bitwise operations in CasADi - by reinterpreting the double type as an integer type (this is done in the sparsity pattern propagation), but introducing it for a single type doesn't make sense.
