### ISSUE TITLE
Codegen for NewtonImplicitSolver

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#676]
C-code generation for NewtonImplicitSolver would make it possible to generate efficient fixed-step Implicit Runge-Kutta integrators.

To implement it, the algorithm would need to be translated to C (cf. also #598) and then have the two functions `generateDeclarations` and `generateBody` implemented (cf. e.g. SymbolicQR).

**Comment by jgillis** [comment]
This has been implemented as `fast_newton`
