### ISSUE TITLE
Line-search in NewtonImplicitSolver

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#677]
NewtonImplicitSolver is now taking full Newton steps. Implementing line-search should give better convergence behavior. The implementation can be partly shared with the (filter?) line-search in SCPgen and the efforts should be coordinated.

Cf. also #676.

**Comment by jaeandersson** [comment]
Reopen if there is an intent to fix it.

**Comment by jgillis** [comment]
Implemented, awaiting push

**Comment by jaeandersson** [comment]
Closing any three-digit issue number deserves extra credit!
