### ISSUE TITLE
Write a CasADi backend to CUTEr

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#713]
By interfacing CUTEr, http://www.cuter.rl.ac.uk/doc.html, we would be able to benchmark NLP solvers interfaced with CasADi against the full CUTEr test set. We would rely on CUTEr to calculate derivative information since parsing the SIF source would be too much work.

Cf. #709 for background.

**Comment by jgillis** [comment]
Yup, there was no effort spent on this.
Also not that nl import of CasADi is not feature-complete

**Comment by zanellia** [comment]
I see, thanks for the quick reply!
