### ISSUE TITLE
OpenMP examples causing segfaults on exit

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#714]
For the vdp_collocation.cpp and cstr.cpp examples, the optimization appears to work just fine, but when the program finishes, I get a segfault. It only happens together with OpenMP enabled. I also think it might be only for OS X.

**Comment by jgillis** [comment]
Does this error still happen?

**Comment by jaeandersson** [comment]
Lets close this. I don't have a way to reproduce this since the original examples don't exist anymore. Also, the parallelisation works very differently from before, so there is no reason to believe that it lingers.
