### ISSUE TITLE
Submatrix access and assignments with symbolic slices

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#728]
It is possible to add support for indexing and slicing with symbolic slices for MX, e.g.

``` python
x = MX.sym("x",4)
s = MX.sym("s")
f = x[s]
...
```

Only makes sense if s takes integer values and should always be avoided when possible since there is a big loss in efficency (more overhead, less simplification, less sparse Jacobians).

**Comment by jaeandersson** [comment]
Implementing this, restricted to a scalar argument, should be pretty straightforward.
Access:
f(x, y) = x[y], with x dense and y scalar
Assign/add:
f(x, y, z): x[y] += z, with dense x and scalar y and z

**Comment by jaeandersson** [comment]
Maybe multiple assignments can be allowed...
==Access==
```
// (ind, x) -> (r) (ind in-place)
r = ind
for i,j
  r(i,j) = x[r(i,j)]
end
return r
```
==Assign/add==
```
// (r, ind, x) -> z (r in-place)
r = z
for i,j
  r(i,j) += x[ind(i,j)]
end
```

**Comment by jgillis** [comment]
Essentially implemented; but not yet supported in Matlab.

**Comment by jgillis** [comment]
Basically imllemented
