### ISSUE TITLE
IPOPT equality constraint multipliers are *slightly* off

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#820]
For equality bounds and `fixed_variable_treatment`=`relax_bounds` (as with QPOptions), the solution x is projected back onto the original bounds (`honor_original_bounds`). The multipliers associated with this constrained are not backprojected however.

Hence the bounds and its multipliers are slightly inconsistant.
This leads to convergence stagnation when IPOPT is used in SQPMethod.
Putting `bound_relax_factor` to zero seems to solve it, but this is dangerous.

An intermediate solution is to put `honor_original_bounds` to 'no' in QPOptions.
That way both x and its multipliers are slightly off, but consistently so.

A better solution is to backproject the multipliers ourselves. Since we have the hessian available for a QP by definition, this should be easy.

**Comment by jaeandersson** [comment]
I'm closing this since it's essentially handled by #724. With #724, `lam_x` and `lam_p` will be calculated by the interface by default.
