### ISSUE TITLE
IPOPT-QP crash

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#840]
Email from Seb:

> when using Ipopt-QP at (stupidly) tight tolerances… I get:
>
>  12 -3.1285463e+00 2.71e-14 2.84e-14 -15.0 3.47e-12    -  1.00e+00 1.00e+00h  1
>  13 -3.1285463e+00 1.91e-14 1.42e-14 -15.0 8.10e-15    -  1.00e+00 1.00e+00   0
>  14 -3.1285463e+00 2.35e-14 2.59e-16 -15.0 6.23e-15    -  1.00e+00 1.00e+00T  0
> terminate called after throwing an instance of 'Ipopt::TINY_STEP_DETECTED'
> Abort trap: 6
dh> cp-181003:WindFarmDistributed sebastien$

Not sure if it's a bug at all.

**Comment by jgillis** [comment]
Reopen if a failing example arises.
