### ISSUE TITLE
Decide on null-argument MXFunction.call semantics

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#856]
Consider the following:
```python
from casadi import *

x = MX.sym("x")
y = MX.sym("y")
f1 = MXFunction([x,y],[x+y])
f1.init()
    
f = MXFunction([x],[f1([x,[]])[0]])
f.init()
f.setInput(3)

f.evaluate()
print "f", f.getOutput()

f1.setInput(2,1)

f.evaluate()
print "f", f.getOutput()

f1.setInput(1,1)


f.evaluate()
print "f", f.getOutput()
```

Each block `f.evaluate();print "f", f.output()` gives a different result.
Passing a null argument to f1.call has the effect of not touching that input on f1, and hence using the data for that argument that happens to be in f1 at the time of f.evaluate().
This is not what i expected (i expected arguments would be set to zero), and is dangerous by itself, because it amounts to `f1.setInput()` having side-effects.

Any comments?

**Comment by jgillis** [comment]
With setinput/evaluate/getoutput dissapearing, this issue disappears i guess? @jaeandersson

**Comment by jaeandersson** [comment]
In fact, it should already have disappeared thanks to #1356.
