### ISSUE TITLE
Deciding on HomotopyNLPSolver

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#881]
A Input IOScheme of homotopyNLP
-------------------------------------------------

1.  nlpIn(x,p) + option "homotopy_param_index" `OT_INTEGER` to specify which of p is the homotopy parameter
2.   hnlpIn(x,p,tau)  , nlpOut

Considerations:
 * obtaining sensitivity w.r.t tau is equally cheap; just one forward sweep

B Range of homotopy parameter tau
-------------------------------------------------
1.  Always 0->1
2.  tau_start, tau_stop   options
3.  tau_start, tau_stop inputs in IOScheme of homotopyNLPSolver

Consideratios: 
 *  Before, we avoided having non-differentiable inputs, but joel consented to lift that restriction
 *  Changes to options are not supposed to have effect without init, but we might want to change tau_start and tau_stop a lot during a homotopy sweep. Supposed to != cannot
 *  CasADi solver are more developer friendly than user friendly, so option 1 fits here
 *  When doing a series of homotopies, we should avoid relinearizing when going from one homotopy sweep to another. Option 1 does not fit here

C Base class of homotopyNLP
-------------------------------------------------
1. NLPSolver
2. FX

Consideratios: 
 * there's a lot of code in NLPSolver baseclass that is equally useful for homotopyNLP
 * one may consider homotopy just as some preprocessor on X0 combined with a trick to solve more complex nlps

Use cases:
 * You attempt to solve a complex nlp, ipopt fails. You pick HomotopySolver to get the job done. From this point of view, is is just another NLPSolver. A1B2C1 makes most sense
 * You are doing a sweep of solutions over some parameter, and the problem is fragile. You construct a homotopyNLP and call it in a loop. B3 makes most sense. Actually, this is the same use case as before: the problem is too fragile to let a regular NLPSolver solve it, so you fall back to homotopy. The difference is just that you are solving the NLP in a loop

**Comment by jaeandersson** [comment]
From my understanding, the conclusion of the above is that `HomotopyNlpSolver` should be removed and if it's functionality is needed, it should be reimplemented as a feature inside the conventional NlpSolver class.

**Comment by jaeandersson** [comment]
Class removed. I suggest opening a new issue should there be a desire to revive this. Given that the above discussion is two years old, assumptions are probably not valid anymore anyway.
