### ISSUE TITLE
Improve solve in matrix_tools: sparsity and complexity

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#891]
The sparsity of `solve()` is a bit too conservative. Consider this:
```python
from casadi import *

x = ssym("x",3)
b = ssym("b")

A = diag(x)
bb = vertcat([b,SXMatrix.sparse(2)])

bb.sparsity().spy()

r = solve(A,bb)

print r
solve(A,bb).sparsity().spy()
```
Returning two non-structural zeros that could be structural.

On complexity: from playing around with the following code, we observe that complexity is O(n^2) instead of O(n):
```python
from casadi import *
import time

n = 100

t0 = time.time()
solve(DMatrix.eye(n),DMatrix.ones(n))
print time.time()-t0
```

**Comment by jaeandersson** [comment]
Closing this since it's part of a more generic effort to get a good linear solve operation.
