### ISSUE TITLE
Require support for C++11

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#893]
C++11 has been around for a while now and it would be nice to be able to use C++11 features without having to make fallbacks for older compilers. Also some features, notably caching, only works if you have support for C++11 hash tables.

In April 2014, the new Ubuntu LTS should be out.

Any good arguments to keep compatibility with pre-C++11 much longer?

**Comment by jaeandersson** [comment]
Another useful C++11 feature: `__func__`, enabling better error messages.

**Comment by jaeandersson** [comment]
I'm going to begin by enforcing the C++11 support in the examples, where it is arguably the most needed, especially in light of current refactoring. If you don't have C++11, you won't be able to compile the C++ examples.

**Comment by jgillis** [comment]
Note that C++11 support is effectively enforced in develop: a simple cpp that include `casadi/casadi.hpp` fails with standard g++.

**Comment by jaeandersson** [comment]
> Note that C++11 support is effectively enforced in develop: a simple cpp that include `casadi/casadi.hpp` fails with standard g++.

Yes, I know. Because of the printing to screen, right?

**Comment by jgillis** [comment]
Yes.

**Comment by jaeandersson** [comment]
Because of #1453, CasADi 2.4 is the first release C++11. In principle, pre-C++11 support can be enabled for 2.4 (in a minor revision), but there has to be a very good reason to do so. And anyway, future releases won't have this possibility.

This means that we are now free to use C++11 awesome features such as `auto`, lambda functions, explicit operator, `std::initializer_list`!
