### ISSUE TITLE
Fix worhp stealing the terminal

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#931]
Now that we learned to play with filehandles ( c6cff78496fe13ba7e36b9e878e7be992a67430 ) , maybe we can resolve this now

**Comment by jaeandersson** [comment]
Closed wontfix due to perceived lack of interest. Reopen if needed.

**Comment by jgillis** [comment]
It is a Worhp faq apparently:

can be fixed with an env variable WORHP_DISABLE_KEYBOARD_HANDLER

http://www.worhp.de/node/585

**Comment by jgillis** [comment]
As from 1.8, this is disabled by default.
