### ISSUE TITLE
Just-in-time compilation

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#949]
According to http://clang.llvm.org/docs/Tooling.html, libclang is a "stable high level C interface to clang". The fact that it is stable makes it a better idea to use this interface than clang's C++ API directly. This is a high level alternative to using LLVM directly (which turned out to be a dead end #915), without many of the limitations that comes with using OpenCL, cf. #596.

**Comment by jaeandersson** [comment]
Since there are different ways of doing just-in-time compilation (libclang, call system compiler, opencl), and since we want to add a dependency to the core, we could use a plugin-design for JIT.

**Comment by jaeandersson** [comment]
Updated title to reflect that the JIT functionality does not need to be libclang-specific.

**Comment by jgillis** [comment]
Pointers: https://github.com/FunkMonkey/libClang/tree/master/examples/clang-interpreter

**Comment by jaeandersson** [comment]
@jgillis I've pushed a fix to the branch issue_949. This gets jitfunction working with llvm 3.6 for me after adding the following to my .profile: 
```
export LLVM_DIR=/usr/local/Cellar/llvm/3.6.2/share/llvm/cmake
```
Might be homebrew specific. 

Can you confirm that it doesn't break existing builds? You need to add the cmake flag `-DOLD_LLVM=ON`.
