### ISSUE TITLE
Avoid creating complex expressions with free variables

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#966]
It makes sense to throw an error if you try to do something like:

``` python
x = msym("x", 2)
y = msym("y")
f = MXFunction([x], [y])
f.init()
a = msym("a", 2)
[f_call] = f.call([a]) # throw error?
```

I cannot see how that expression could be used for anything useful so throwing an error message directly might avoid a less informative error later.

Cf. https://groups.google.com/forum/#!topic/casadi-users/yQMCqfRGQxU.

**Comment by jgillis** [comment]
This issue is moot. We have `allow_free` since a while.
