### ISSUE TITLE
Fix CASADI_DEPENDENCIES (was: Build of casadi under ubuntu 13.10)

### ISSUE THREAD

**Issue by kiliangrundl** [casadi/casadi#981]
Hello,
I just had a problem building casadi in ubuntu 13.10. The build stopped when linking to libcasadi.so at the error_handling example with the message, that the functions dlopen() etc. are not defined (which are contained in libdl). In the link command the "-ldl' flag is given (correctly) however an error was raised. 

Now what I found was that it worked if I directly link the libcasadi.so with "-ldl' (By adding the "-ldl"-flag to the end of the command in the link-command given in ".../symbolic/CMakeFiles/casadi.dir/link.txt") 
So the whole linking works for me in the end if I add the following line to the symbolic/CMakeLists.txt the following line:

target_link_libraries(casadi ${CASADI_DEPENDENCIES})

Probably this is just a hack but I'm not sure how to fix it correctly or if this has to be fixed anyway. It seems strange to me that while linking the libcasadi the dl-library has to be added to the command already.

If someone can explain this to me I would be very happy. If this helps someone I would be very happy too...

**Comment by jgillis** [comment]
I think thia is no longer relevant
